### ISSUE TITLE
Request for more ion-slides properties

### ISSUE THREAD

**Issue by mmirzaee** [driftyco/ionic#10037]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
As you know, currently (at RC 5) ion-slide doesn't have some properties.
I opened this issue to ask for some properties as @brandyscarney said in this issue : [https://github.com/driftyco/ionic/issues/9988#issuecomment-272473892](https://github.com/driftyco/ionic/issues/9988#issuecomment-272473892)

**Expected behavior:**

I think these properties are so common and I used them in many projects : 

- slidesPerView
- centeredSlides
- spaceBetween

Thanks for your perfect product

**Comment by ivanmayes** [comment]
Agreed, stuck between ionDidChange not firing on rc3 and not being able to use slidesPerView: auto on rc4-5.  Please fix ASAP!

**Comment by mhartington** [comment]
spaceBetween, slidesPerView, and centeredSlides are all still there. Instead of having a component with 20+ inputs that can be set, we've created inputs for the more common ones. 

https://github.com/driftyco/ionic/blob/master/src/components/slides/slides.ts#L147

Any other property that is not an input, can still be set/changed via the component instance.

http://ionicframework.com/docs/v2/nightly/api/components/slides/Slides/#advanced

This is how values will be set going forward. We do not want to keep adding additional inputs when the component instance will do just fine.
