### ISSUE TITLE
IOS scrollbar is being added with a delay; blocking me to scroll content immediately. How to fix it?

### ISSUE THREAD

**Issue by 1BJK903** [driftyco/ionic#10129]
Hi all,

I have a `<ion-content>` element where a lot of content is being shown. I have a dynamic button which toggles me new content when I click on it. Before I click on it, I can't see a scrollbar, because the content fits to the screen...

**The problem:**

When I click on the button, however, the content that is being shown, is overflowing so you need a scrollbar. **The scrollbar is being added, but it's being added with a _delay_ of nearly 1 to 2 seconds**. I can't fix this problem at all... **so when I click on the button, the new content is being toggled and I want to scroll immediately down, yet I am being blocked, because the scrollbar isn't _set._.. it's set after a _couple of seconds_ and that is when I can start scrolling down.**

Is this a known bug? If not, how can I solve this delay?
```

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.8.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This delay that your talking about is because when you change the content of the entire screen you cause the browser to have to do at least two full render cycles, one for getting rid of the original content and one for all the new content. Also, in this case with so much repainting and rerendering it is most likely causing layout thrashing which is going to cause even more of a delay. This is not an Ionic issue but simply a UX issue with your code. I would recommend looking into a different pattern than simply erasing all the content on the page and adding all new content. Sorry I couldn't help more with this issue!
