### ISSUE TITLE
BUG: back button souldn't close modal

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic#10138]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I updated to RC5.
when I tap back button it close modal not the page.
the right way should close the page not only modal.
becasue modal is not a page. it doesn't match a url.

**Expected behavior:**

in some case like user login modal.
I have a main page and I will check if user is logined.
if not I will show a login modal.
but if back button will close modal not page.
user can see main page without login.

what a terrible logic.
it makes my app in trouble.

wish u fix it ASAP plz !!!!!!!!!!

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by yozman** [comment]
by the way
when I use RC3
it works well

**Comment by Jake21x** [comment]
try using .
enableBackdropDismiss:false

**Comment by basvdijk** [comment]
Quoted from: https://material.io/guidelines/components/dialogs.html#dialogs-behavior

> Dialogs can be dismissed by touching/clicking outside of a dialog or by using the system back > button (Android). Alternatively, dialog behavior can be overridden so that users must explicitly choose one of the actions.

I do not know how this goes for iOS, but for Android the behaviour is as it should be.

**Comment by yannbf** [comment]
People have been asking for this feature(close modal with back button) since beta, and it was finally implemented in RC4. In android the correct behavior is to dismiss a modal when pressing the back button, you can check in every major app (airbnb, facebook, etc).

The only terrible logic is the one you designed.. I would reccomend you to check if the user is logged in before rendering the first page, in `app.component.ts`.

```
getInitialPageToLoad() {
    return new Promise((resolve, reject) => {
      this.af.auth.subscribe(user => {
        if (user) {
          resolve(HomePage);
        } else {
          resolve(LoginPage);
        }
      });
    });
}
```

And in your constructor you could use:
`this.getInitialPageToLoad().then((page) => {  this.rootPage = page; })`

**Comment by mhartington** [comment]
This is by design. Both ios and android treat modals as a temporary screen, one that a user should be able to dismiss without breaking an app.

Android goes further and allows modals to be dismissed by tapping the hardware back button. 
As stated, this has been  a requested feature and is a key feature in many apps.
