### ISSUE TITLE
When playing embedded video on full screen, tabs are invisible but can be touched

### ISSUE THREAD

**Issue by AlQuraian** [driftyco/ionic#10143]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
When embedding a video say from YouTube, if you have the video playing in a tab and switched to another tab, the video keeps playing in the background. Also, when you play the video in full screen then click on the screen where the tabs buttons are (even through they are hidden) the app will switch to that tab.

**Expected behavior:**
- The video should stop playing when switching to another tab.
- When a video is playing in full screen, user interaction should be possible for the video not elements which are hidden. This only happen when running in mobile as full screen on desktop doesn't hide the tabs buttons.

**Steps to reproduce:**
- Create a tabbed app, add the following to one of the tabs ion-content:
`<iframe src="https://www.youtube.com/embed/O2WiI9QrS5s" frameborder="0" allowfullscreen></iframe>`
- Test

**Other information:**
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.4
Xcode version: Not installed

**Comment by mhartington** [comment]
>The video should stop playing when switching to another tab.
When a video is playing in full screen, user interaction should be possible for the video not elements which are hidden. This only happen when running in mobile as full screen on desktop doesn't hide the tabs buttons.


1) the video playing as the tabs are switched makes sense, since the DOM isn't getting removed, but just hidden. This would happen even if you end up just pushing a new page and not just switching tabs. 

I think a decent solution would be to create a play were you can control the videos play/pause functionality. As we cannot expect every video to be the same, I think it's ok for the dev to do a bit of work and hook into the view events to control the video.


2) Not following what you are saying. Are you talking about how the tabs are still visible when the app is fullscreen? 

![screen shot 2017-01-23 at 1 02 07 pm](https://cloud.githubusercontent.com/assets/2835826/22216231/3edc55fe-e16c-11e6-9b8f-7994903bcfcb.png)

**Comment by AlQuraian** [comment]
For number 2, the tabs are invisible on my phone when I'm playing the video on full screen, however, they are clickable. So, when I click on the area where the about button is, it will go to the about page. even thought the tab buttons are invisible.
Not sure if this is a bug or not though.

**Comment by mhartington** [comment]
Android or ios?

**Comment by AlQuraian** [comment]
Android 7.1.1

**Comment by mhartington** [comment]
Interesting. Ok, this second seems to be a bug.
Would you mind updating the title

**Comment by mhartington** [comment]
Closing and merging with https://github.com/driftyco/ionic/issues/10132
