### ISSUE TITLE
bug: Page Lifecycle Events not fired

### ISSUE THREAD

**Issue by cbratschi** [driftyco/ionic#10154]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am using an app with linear navigation i.e. without tabs.

The following lifecycle events are not triggered:

```TypeScript
import { Component } from '@angular/core';

import { NavController } from 'ionic-angular';

import { ScreenSaver } from '../../app/screen-saver';

@Component({
    selector: 'page-home',
    templateUrl: 'home.html'
})
export class HomePage {
    constructor(public navCtrl: NavController, private screenSaver: ScreenSaver) {
        //start screen saver
        screenSaver.init(navCtrl);
    }

    ionViewDidLoad() {
        console.log('ionViewDidLoad: home');
    }

    ionViewWillEnter() {
        console.log('ionViewWillEnter: home');
    }

    ionViewDidEnter() {
        console.log('ionViewDidEnter: home');
    }
}
```

According to the documentation those events should be fired.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
I'm not able to replicate.
On a blank app, all events fire as expected.
Do you have any more info?
Perhaps put together plunkr or demo and put to github?

**Comment by cbratschi** [comment]
app.html contains:

```HTML
<ion-nav [root]="rootPage"></ion-nav>
```

**Comment by cbratschi** [comment]
It actually works on sub-pages but not on the root page.

**Comment by mhartington** [comment]
This is to be expected. Since all these event are related to the nav-controller, there needs to be a parent nav-controller.  Since you're loading a root component, there is not parent nav-controller, no events fire. 

If you need to catch event when that root component is rendered, you can use the angular lifecycle hooks. 
Or, if you need to subscribe to when child components are loaded, there are observables you can use.

http://ionicframework.com/docs/v2/nightly/api/components/app/App/
