### ISSUE TITLE
*ngIf not taken into account when rendering ionic components (atleast content and header)

### ISSUE THREAD

**Issue by AMetnik** [driftyco/ionic#10283]
**Ionic version:**  (check one with "x")
[x ] **2.0.0**

**I'm submitting a ...**  (check one with "x")
[x ] bug report

**Current behavior:**
When adding *ngIf="boolean"

To `<ion-header>` or `<ion-content>`

**Expected behavior:**
The ion components appear correctly rendered when the ngIf is evaluated tru.
But they are not.

**Steps to reproduce:**
http://plnkr.co/edit/btuqNZRRVqdB1VYFsBUX?p=preview

**Comment by brandyscarney** [comment]
@AMetnik Thanks for the issue. `loaded` is not getting set to `true` in your plunker because `this` is a reference to the `Window` object. If you add a `console.log(this);` right before setting it you will see. If you change it to use an arrow function it will work properly, but you will have to call [`content.resize()`](http://ionicframework.com/docs/v2/api/components/content/Content/#resize) afterwards because you are dynamically showing the header:

```
  ionViewDidEnter() {
    setTimeout(() => {
      this.loaded = true;
      this.content.resize();
    }, 2000);    
  }
```

Note: I also moved it to the `ionViewDidEnter` in order to make sure the ViewChild `content` was set. Updated plunker: http://plnkr.co/edit/7rXGAxMKZ7XnvwJW3Bu2?p=preview

**Comment by AMetnik** [comment]
Is there an equivialent to content.resize(). To rerender the navbar/header as well?

Also I've updated the plunkr ([http://plnkr.co/edit/Tf0AlDlIkyPsZh1zqEKF?p=preview](http://plnkr.co/edit/Tf0AlDlIkyPsZh1zqEKF?p=preview))
But I guess this is just bad practice, and I could encapsulate the content with an inner div and set loaded on that.
