### ISSUE TITLE
popTo specific page no longer works, just navigates back one screen

### ISSUE THREAD

**Issue by joshgarwood** [driftyco/ionic#10342]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
1. From a tabbed interface, go to a new page with this.navCtrl.push(MyPage)
2. From MyPage go to another new page with this.navCtrl.push(MyPage2)
3. From Mypage2 go to another new page with this.navCtrl.push(MyPage3)
4. From MyPage2 try to go back to MyPage with: this.navCtrl.popTo(MyPage)

I would expect to be popped to MyPage, but instead it simply navigates back to MyPage3.

**Expected behavior:**
I would expect to be navigated to MyPage

**Steps to reproduce:**
See Current Behavior above

-->

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed

```

**Comment by mhartington** [comment]
Hi there! SO `popTo` is a private API, and not really meant to be used.
Also, the way you are using it is incorrect. 

Take for example, this history

```
Page1 -> Page4 -> Page1 -> Page5
```

Then in Page5 you can `navCtrl.popTo(Page1)`. Which component should it go back to?
Passing in Component class names wont work since it does not take into consideration the navigation stack.
Instead, you could pass an index, or a raw ViewController instance.

![screen shot 2017-02-07 at 3 42 11 pm](https://cloud.githubusercontent.com/assets/2835826/22710629/097334a0-ed4c-11e6-98ee-f4c096c988c7.png)

In this case, a ViewController instance != Component Class. 

There is a reason why it's marked private (_here be dragons and all_  🐉 )
