### ISSUE TITLE
ionContent keeps 'has-header' class when ionView sets hideNavBar to true

### ISSUE THREAD

**Issue by zefei** [driftyco/ionic#1038]
This occurs under current master. It was working in 1.0-beta, but I can't get ionNavBar to work in 1.0-beta, so I tried master. Everything around navbar works, but when ionView sets hideNavBar to true, ionContent keeps its top margin due to 'has-header' class, even though header isn't showing.

**Comment by lambrospetrou** [comment]
If I have the ion-nav-bar hidden but I have another HTML code acting as header with the class 'bar-header' then the ion-content class 'has-header' is being removed on SECOND load of the view whreas it works fine the first time.
It seems that ionic removes the has-header class when it loads the view from cache because it sees that the ion-nav-bar is hidden, but it ignores the fact that I have another element with the 'bar-header' class.

**Comment by lexyfeito** [comment]
@lambrospetrou any progress on this? i am having the exact same problem

**Comment by lambrospetrou** [comment]
I don't remember exactly where I had the issue but what you can do is subclass the .has-header class with your custom one .custom-has-header and put that on your ion-content.
