### ISSUE TITLE
Possible Memory Leaks / Excessive memory usage.

### ISSUE THREAD

**Issue by FlashGordon95** [driftyco/ionic#10481]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using a component such as ion-slides with a large dataset. Memory usage becomes incredibly high. The transition from side menu to the page in question is slow and the generated slides with ngFor are slow to respond. 
A part of the NgFor is loading data in via a provider which parses a json file to fill the slides with info.

The json file itself is 500~kb in size.

On iOS using a large dataset, the app crashes citing memory management issues.
On android there is no crashing but slow performance.
On OSX built app and Chrome served ionic app, we see beachballs and slow performance.

**Steps to reproduce:**
The issue I am seeing is scalable. Using a JSON file with 400~ lines / 30 objects provides a noticeable but acceptable delay (~2s). The delay scales up as the dataset scales in size. This could be caused by my code creating a new slide for each object in the dataset. Oddly with a dataset of say 9k lines 600 objects we start to see memory usage upwards of 1.2gb on Chrome and OSX (I understand OS X is not supported for building). 

**Related code:**
provider
```
@Injectable()
export class QuestionsData {
    data: any;
 
    constructor(public http: Http, public loadingCtrl: LoadingController) {
 
    }
     presentLoading() {
    let loader = this.loadingCtrl.create({
      content: "Please wait...",
      duration: 3000
    });
    loader.present();

  }
    //function we use to pull in data if we do not have it
    load(){
        
        if(this.data){
            return Promise.resolve(this.data);
        }
        
        return new Promise(resolve => {
            this.presentLoading();
            //this is just a standard http request in Angular2. Returns a Promise which we will subscribe too
            this.http.get('assets/data/questions.json').map(res => res.json()).subscribe(data => {
                
                this.data = data.questions;
                resolve(this.data); //resolve the data we have received making it available throughout the page
            });
 
        });
 
    }//load()
}//QuestionsData
```

html
```
<ion-slides #slides [options]="slideOptions">
 
        <ion-slide class="start-slide">
            <button ion-button color="primary" (click)="nextSlide()">Start!</button>
        </ion-slide>
        <ion-slide *ngFor="let question of questions; let i = index;">
 
            <h6>Question {{i+1}} / {{questions.length}}</h6>
            <flip-card [isFlipped]="question.flipcardFlipped">
                <div class="flip-card-front" [innerHTML]="question.questionImg"></div>
                <div class="flip-card-back" [innerHTML]="question.correctAnswer"></div>
            </flip-card>
 
            <h3>{{question.questionText}}</h3>
 
            <ion-list no-lines radio-group>
                <ion-item *ngFor="let answer of question.answers; let i = index;" text-wrap [ngStyle]="{ 'color' : (hasAnswered) ? (answer.correct) ? 'green' : 'red' : null }">
 
                    <ion-label>{{i+1}}. {{answer.answer}}</ion-label>
                    <ion-radio (click)="selectAnswer(answer, question)" [checked]="answer.selected" [disabled]="hasAnswered"></ion-radio>
                </ion-item>
            </ion-list>
        </ion-slide>
```

**Other information:**

When testing the issue in chrome developer tools can see a very large JS HEAP (20mil+). Quite a lot of memory usage. It appear the filling of the ion-slides is the issue as the loading of the questions takes ~600ms at worst from what iv seen however the entire XHR call can take up to 20.0s

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.6
OS: macOS Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by FlashGordon95** [comment]
![screen shot 2017-02-17 at 17 16 07](https://cloud.githubusercontent.com/assets/11082710/23075545/d11e268c-f534-11e6-8757-a2aefe0669b7.png)
Added Chrome debug timeline 
@jgw96 any ideas ?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. So i may ramble a bit here but the quick tldr is that this isnt really an Ionic issue, but more of just the fact that your loading in such huge json files and then parsing, grabbing info from those json objects, and then trying to render a relatively huge amount of slides all at once. So `ngFor` or anything that takes data and then stamps out dom elements from that data is always going to struggle with stamping large amounts of elements at a time. dom operations are always going to be slow in the browser as every time you do a dom operation it is going to have to trigger atleast part of the rendering pipeline, and possibly all of it. You can see this in the timeline you posted above if you look at the pie chart of where time is spent. The purple bit is all rendering time, which makes sense when stamping out such a large amount of elements at a time. This is also going to cause dropped frames (which your timeline shows a good number of) as the page is having to go through forced re-renders. Because of all this info I am going to close this issue for now and recommend that you come up with another UX that does not try to render so many slides at once (maybe you can lazily create some of these slides by measuring the slide index and loading more data and rendering more slides as the user gets to the end of a group of slides). Also for a little more info on how the rendering pipeline in browsers works i would recommend checking out this article https://aerotwist.com/blog/the-anatomy-of-a-frame/. Thanks for using Ionic!

**Comment by jgw96** [comment]
@FlashGordon95  oh and thanks big time for including a chrome timeline with this issue, it always makes perf issues much easier to triage.
