### ISSUE TITLE
Ionic 2: Icons inside of ion-items/buttons are cuts

### ISSUE THREAD

**Issue by slzr** [driftyco/ionic#10517]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Ionic 2.0.1: The icons inside of ion-items/buttons are cuts

**Expected behavior:**
Normal full icons inside ion-items/buttons, no cuts

**Steps to reproduce:**
Just put an `ion-icon` inside a `button ` with the `ion-item` directive inside a `ion-list` component

**Related code:**
```ts
<ion-list>
    <button ion-item icon-left (click)="logout()">
      <ion-icon name="log-out"></ion-icon>
      Logout
    </button>
</ion-list>
```
[Plunker example preview](http://plnkr.co/edit/ZcuDABy4BHueSGGTT0ee?p=preview)

**Other information:**
![image](https://i.stack.imgur.com/pjCRg.png)
[stackoverflow question](http://stackoverflow.com/questions/41961584/ionic2-icon-inside-menu-button-is-cut)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```bs
Your system information:
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.4.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by brandyscarney** [comment]
@slzr This is because you're mixing up button and item attributes. `icon-left` shouldn't be applied on items. The `icon-left` attribute is useful for button styles to place the icon to the left of the text. What you want here is either:

```
<button ion-item (click)="logout()">
  <ion-icon name="log-out"></ion-icon>
  Logout
</button>
```

<img width="304" alt="screen shot 2017-02-24 at 4 35 52 pm" src="https://cloud.githubusercontent.com/assets/6577830/23321887/6a271e7c-faaf-11e6-9a5d-5df5304dda9a.png">


or:

```
<button ion-item (click)="logout()">
  <ion-icon item-left name="log-out"></ion-icon>
  Logout
</button>
```

<img width="303" alt="screen shot 2017-02-24 at 4 36 42 pm" src="https://cloud.githubusercontent.com/assets/6577830/23321900/783ce3a2-faaf-11e6-9279-9c5f2e69799c.png">

For more information on item placement check out the API docs: http://ionicframework.com/docs/v2/api/components/item/Item/#item-placement

Thanks! :)

**Comment by FabiGjuzi** [comment]
using item-left displays icon in the middle of the field, pushing button to the bottom
