### ISSUE TITLE
iOS: Lock vertical scrolling while swiping back

### ISSUE THREAD

**Issue by RikdeVos** [driftyco/ionic#10611]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On iOS during swiping back, you can still scroll vertically.

<img src="https://cloud.githubusercontent.com/assets/230182/20414382/6de8bebe-ad32-11e6-9152-f69faa87aa96.gif" />

**Expected behavior:**
Lock vertical scrolling of the view whenever the user is swiping back

**Related issues:**
#9052 #7120 

Related issues are closed but unresolved. Posted solutions are not working.

**Comment by emin93** [comment]
Thanks for the cool little demonstrating GIF. This seems to be an issue since the first beta of Ionic 2. Found various other people reporting this issue back in summer 2016. These issues got closed because a GestureController was implemented. But they seem to have it removed already. Ionic 1 did it correct. But Ionic 2 doesn't and sadly it seems it's still an issue in the final version of Ionic 2 😢

**Comment by longzheng** [comment]
Also a problem for the menu control which exhibits a similar behaviour, scrolling while you are swiping (to open menu).

**Comment by jgw96** [comment]
Hello all! Unfortunately we are not able to solve this issue with UIWebView as the only solution causes UI flickers, which in our opinion is worse than this issue. But, the good news is that with [wkwebview](https://github.com/driftyco/cordova-plugin-wkwebview-engine) we can and have solved this issue without any ui flickers. Because of this I am going to close this issue with the recommendation that you install the wkwebview plugin i linked to above. Also, we are extremely close to making wkwebview the default for iOS as this will improve performance and allow us to move away from uiwebview (which is pretty buggy unfortunately)
