### ISSUE TITLE
Using Yarn Instead of Npm for Ionic

### ISSUE THREAD

**Issue by aswinmohanme** [driftyco/ionic#10647]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Npm is super slow and super awesome at testing the patience of a developer. It would be nice if Ionic switched to Yarn ( the faster alternative package manager).

React has already did that and they are happy about it https://facebook.github.io/react-native/blog/2016/11/08/introducing-button-yarn-and-a-public-roadmap.html

Thanks.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#123

**Comment by aswinmohanme** [comment]
Thanks

**Comment by vhbsouza** [comment]
@jgw96  this [driftyco/ionic-feature-requests#123](https://github.com/driftyco/ionic-feature-requests/issues/123) url is 404 ... Where can I follow this thread?

**Comment by gianpaj** [comment]
looks like this is done now
https://github.com/ionic-team/ionic-cli/commit/5107a6616f2aa8a0971065a44f4f0c7a24d725f9
https://github.com/ionic-team/ionic-cli/commit/8573ff20c02563343c11a19645df6566f58c8bcd

if you run `ionic` on >= 3.4.0, you'll see an option `--yarn` to enable that. Though not sure if it helps for an existing project. probably `ionic` it runs yarn instead of npm only when u start a project.

But since [npm 5](http://blog.npmjs.org/post/161081169345/v500) has a `package-lock.json` and it's faster, not sure if yarn is such a big deal.

**Comment by rafael-neri** [comment]
https://gist.github.com/rafael-neri/f24e328a123e2585bbabce135a787952

**Comment by rungissan** [comment]
ionic config set -g yarn true

**Comment by Mobiletainment** [comment]
With Ionic 4 and Angular CLI v6+ you can use `ng config -g cli.packageManager yarn`.

**Comment by dwieeb** [comment]
Along with configuring the Angular CLI as @Mobiletainment said, with Ionic CLI 4 you have to do this: 

```
ionic config set -g npmClient yarn
```

This isn't really documented, but I'd be happy to accept PRs if something isn't working properly.
