### ISSUE TITLE
<ion-slides> with different slide heights

### ISSUE THREAD

**Issue by heqiang421** [driftyco/ionic#10690]
1. slide1:979px
2. slide2:1686px
when the user slide to slide1 , it appear blank space (707px).

i hope slide-height of slides can be different

**Comment by twincle** [comment]
+1

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by EugeneSnihovsky** [comment]
@twincle thanks for, perhaps the only working solution. In additional for other developers. Solution need two fixes:
1. Initial value of `slidesMoving` should be `true`. Otherwise scroll on init will not work until slide manually changed
2. `slideDidChange` logic should be wrapped in try/cath. Otherwise app will throw an error `Cannot read property 'clientHeight' of undefined` when you try to swipe right on last slide
```
    public slidesHeight: string | number;
    public slidesMoving: boolean = true;

    public slideDidChange(): void {
        try {
            this.slidesMoving = false;
            let slideIndex: number = this._slides.getActiveIndex();
            let currentSlide: Element = this._slides._slides[slideIndex];
            this.slidesHeight = currentSlide.clientHeight;
        } catch (e) {
            console.log(2, e.message);
        }
    }

    public slideWillChange(): void {
        this.slidesMoving = true;
    }
```

**Comment by brunolm** [comment]
Is there an official fix for this? The workaround works but it's kinda weird

**Comment by ChrisProlls** [comment]
Same here ! Any news ?

**Comment by ShuaiW** [comment]
@twincle what is `slides` in `this.slides._slides[slideIndex]`?

**Comment by EugeneSnihovsky** [comment]
@ShuaiW I don't use this fix anymore, because I don't use ionic slides. I need infinite scroll on each of my slide and it is not possible with ionic slides. Instead of it I use [siema](https://github.com/pawelgrzybek/siema) and all works without problem.

Also I removed [cordova-plugin-ionic-webview](https://github.com/ionic-team/cordova-plugin-ionic-webview) from project because it has as many bugs as ionic slider, and some of them are critical:
- app view broken when I move app to background and then to foreground
- app view broken when I change device orientation by rotating device
