### ISSUE TITLE
ionic2 PopoverController bug

### ISSUE THREAD

**Issue by kongdewen1994** [driftyco/ionic#10769]
`let popover = this.popoverCtrl.create(PopoverPage);
    popover.present({
      ev: myEvent
    });`

Click the button enter the other pages in PopoverPage, android physical return key is invalid

**Comment by mhartington** [comment]
Hi there :smile: ! It seems that you did not fill out the provided issue template. The templates really helps us out by having you provide all the information we need in order to debug.

I'm going to close this issue since it does not provide the info we need. Please feel free to open a new issue, but fill out the provide template with the appropriate information.
