### ISSUE TITLE
Ionic 2: Visible lag while typing in any input

### ISSUE THREAD

**Issue by shyamal890** [driftyco/ionic#10837]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When app has considerable js code and one tries to type fast. This is what is happening:

![textarea-slow](https://cloud.githubusercontent.com/assets/6606965/24089423/71844c8e-0d5c-11e7-9ba1-21fea8f45d1f.gif)

**Expected behavior:**
The visible lag shouldn't happen it degrades UX interaction.

**Steps to reproduce:**
May be this would be reproduced in a heavy js coded app.

**Related code:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.10.0
Xcode version: Not installed

**Comment by mpaland** [comment]
Does a character input trigger any event in your app?

**Comment by shyamal890** [comment]
This is the input div

```
<ion-item class="comment-textarea-item">
        <ion-textarea fz-elastic
                      placeholder="Comment"
                      [(ngModel)]="currentChatModel.Text"></ion-textarea>
    </ion-item>
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. Unfortunately I cannot reproduce this issue in our testing apps. Would you mind sharing a repo or plunker i can reproduce this with? Are you binding to some kind of event or manipulating the input value in some way?

**Comment by shyamal890** [comment]
I tried to figure this out through chrome timeline tool. Here is the screenshot and json file of the recording.

![chrome timeline](https://cloud.githubusercontent.com/assets/6606965/24245133/a04c1884-0fe7-11e7-9a95-e31d2d610c9a.PNG)

As you can see from the timeline, during keypress and keydown event there is a lot of scripting happening. All of the functions called are from framework only, there is no event or manipulating call that we have setup. I guess for devices with less cpu power this would cause considerable lag. 



[TimelineRawData-20170323T164924.zip](https://github.com/driftyco/ionic/files/864499/TimelineRawData-20170323T164924.zip)

**Comment by jgw96** [comment]
Thanks for the timeline? Unfortunately i still cannot reproduce this issue. I am testing primarily on a first generation moto g running Android 4.4.4. Could you share a repo i could use to reproduce this issue?

**Comment by shyamal890** [comment]
@jgw96 Check this [plunker](https://plnkr.co/edit/XTM86C?p=preview). Open Modal, start typing.. 
More Context on what's causing the lag:
- When you start typing in the modal, on each keypress, for some reason change detection is triggered on the underlying view. 
- If the underlying view has a filter, it is triggered everytime you type a letter, which shouldn't happen as the changes in modal are isolated from the underlying view

**Comment by shyamal890** [comment]
Further debugging into this issue: 

If there are pages in the history, change detection is triggered in those pages too when input change occurs. This inturn is causing more scripting to happen, lowering down performance

**Comment by shyamal890** [comment]
**UPDATE:** How I am solving this issue currently. 

As noted above, the problem was when I typed into an input in a modal, it was causing change detection to trigger in pages in history. To avoid this, I added a variable called `inactivePage`. Utilized it as shown below:

**In Typescript:**
```
   ionViewDidEnter = () => {
        this.inactivePage = false;
    }

    ionViewDidLeave = () => {
        this.inactivePage = true;
    }
```

**In Html:**
```
<ion-content>
     <div *ngIf="!inactivePage">
         //My Content
     </div>
</ion-content>
```

Avoiding change detection in current page as modal open doesn't trigger `ionViewDidLeave`:

```
openModal = () => {
            var modal = this.modalCtrl.create(SomeModal);
            this.inactivePage = true;
            modal.present();
            modal.onDidDismiss(() => {
                this.inactivePage = false;
            })
    }
```

**Comment by jgw96** [comment]
Hello @shyamal890 , sorry about the delay on this. So im still looking into what is causing the issue in your plunker, but i made a minimal example of using a textarea in a modal [here](https://github.com/jgw96/textareTest) and I cannot reproduce this issue there.

**Comment by shyamal890** [comment]
@jgw96 Have you even tried to read, what I have written in this thread? If you tried, I am sure you would have understood by now. Ofcourse, your example isn't able to reproduce the issue as the page triggering the modal doesn't have anything to identify a change detection!

Please re-read the whole thread.

**Comment by jgw96** [comment]
Hello @shyamal890 , sorry about the confusion. Could you do a `git pull` on that repo i made and try again. I added a method on my home page component and unfortunately still cannot reproduce the issue. As i said above i have spent some time looking into your plunker and have not spotted the issue yet, but when i get some more time i will take another look.

**Comment by mpaland** [comment]
This is strange. I've tested the plunker of @shyamal890 and can observe a significant input delay when entering text, too! @jgw96 , do you see this effect in the provided plunker, too?
Tested this with actual FF 52.

**Comment by shyamal890** [comment]
@mpaland absolutely, now run chrome timeline and record when typing into textarea. Drill down into keydown, keypress call tree, you will see the filter function being triggered under the `DetectChanges` function.

**Comment by jgw96** [comment]
Hello all! Yep, as i stated above i am seeing the issue on his plunker, just having trouble reproducing it locally. I plan on deep diving into that plunker today

**Comment by shyamal890** [comment]
Btw, Justin, you included the new function to `home.ts` instead of `home.html`. Once you make the change, record timeline and drill down into keypress, keydown event.

**Comment by shyamal890** [comment]
Wow! No updates on such a critical issue for so long?! What to say....

**Comment by jgw96** [comment]
Hey @shyamal890 , very sorry for the delay on this. If you don't mind could you please provide a more minimal example that is running on the latest version of Ionic? You can use [this plunker]( http://plnkr.co/edit/z0DzVL?p=preview) as a base. A more minimal example will make this easier to triage. I have tried multiple bits of your code from the plunker in starter apps locally and unfortunately i have not been able to reproduce this issue, so if you could reproduce with a minimal example on Ionic 3.0.1 that would be great.

**Comment by shyamal890** [comment]
I am really sad, that you didn't even read my comment  https://github.com/driftyco/ionic/issues/10837#issuecomment-290721388

Anyways, here is a "REPO" made by copying the code in plunker.... https://github.com/jgw96/textareTest/pull/1

**Comment by jgw96** [comment]
Hello @shyamal890 . Thanks for pushing that PR to my repo. By cutting down on the amount of code (the plunker had a few other files, services etc) that made it much easier to track down the issue. Now for the explanation of why this is happening. In Ionic when a new page is navigated to we turn off change detection on its "sibling" pages for performance. I pushed a commit to that repo that shows that when the textarea is on a whole other page this issue does not happen as an example of this. With how our navigation stack works we do not turn off change detection when a modal is pushed, as modals are not actually a new navigation. This models how modals work in native apps. So, when your binding to a function in your template and a modal is pushed change detection is still going to be ran on that underlying page. [This article from narwl](https://blog.nrwl.io/essential-angular-change-detection-fe0e868dcc00) goes into more detail about this, but since your binding to a function ```let i of doWork()``` angular will always execute that function any time change detection runs. So the TLDR of this is that it is not recommended to bind to functions in Angular apps as everytime change detection runs in Angular it will execute that function.

**Comment by mpaland** [comment]
@jgw96 Justin, thanks for investigation and giving such a detailed answer.

**Comment by shyamal890** [comment]
Hey @jgw96 Thanks a lot for detailed explanation. However, why can't we switch off change detection on the underlying page when the modal is visible? As the change detection would run again when we navigate back to the underlying page and all would work well.

**Comment by jgw96** [comment]
No problem guys! Good question @shyamal890 . So we actually discussed this yesterday and the reason we cant do this "safely" aka without a big risk of breaking everyones apps, is because since a modal is not an actual navigation, it does not have any concept of "sibling" pages, or any info about the specifics of the nav stack. Because of this the only way we could do this is by cutting off change detection in the entire app every time a modal was opened and then looping back through each page and turning back on change detection every time a modal was closed. This turning on and off of change detection across an entire app would potentially be error prone, and not just a small error but a "my app is completely broken" error. Also, the small perf increase we would potentially get from doing this would not be worth the possibility of completely broken apps. Hope this explains things (:

**Comment by rodneicouto** [comment]
@jgw96 thank you for the explanation

To increase performance, can I disable the change notification in ion-input? with a html input,  If I do not use two-way bind ( ngModel ) the change event is not triggered. 

I realized reading the source code that there will always be a ngModel in ion-input. 

Using ngZone, can I disable change notification in ion-input?

**Comment by shyamal890** [comment]
@jgw96 @danbucholtz I am currently utilizing `ng-if` to switch off change detection in the page from which the modal is created. This is not an ideal way since I am losing scrolled data view when `ng-if` plots back the old data. 

Kindly rethink over a solution that would help developers avoid this issue as filtering is a very basic need. Moreover, regarding https://github.com/ionic-team/ionic/issues/10837#issuecomment-293907757 I implemented triggers on page/modal change, which means it would be very simple to create a service that monitors page/modal navigation internally in ionic.

**Comment by dkd051** [comment]
I have same issue. Some page okay, some page is very slow when typing.
Help me.
I am using ionic latest version.

**Comment by shyamal890** [comment]
I think I may have found a temporary fix to this issue using angular's [ChangeDetectorRef](https://angular.io/api/core/ChangeDetectorRef). 

Following code detaches change detection from main page from the the time modal is presented, till the modal is closed.

```
openModal = () => {
        var modal = this.modalCtrl.create(infoModal);
        this.ref.detach();
        modal.present();
        modal.onDidDismiss(() => {
            this.ref.reattach();
        })
    }
```

**Comment by kirillgroshkov** [comment]
Same issue here.

Tried detaching changeDetector - no improvement.

Currently ended up setting [hidden]="hidden" on <ion-tabs> conditionally when modal is open and getting it back before it's closed. Dramatic difference in performance.

**Comment by JeremyLopez** [comment]
@kirillgroshkov why did that improve performance?  I thought `hidden` only impacts CSS?

**Comment by kirillgroshkov** [comment]
@JeremyLopez it's still a mystery to me. So seems like it's not a change detection that is slowing down but rather something in Ionic, or maybe something that is triggering DOM changes (so when it's hidden - no DOM changes). I don't know. Would be nice to discover the root cause.

But I confirm that it really made things much faster for us and solved our problem (without understanding the root cause).

**Comment by issy123** [comment]
@jgw96 
Hi justin,

I am creating a chat app using ionic, and so far it's been great!
Except I still have the slow typing experience.

Now the chat has a large visible amount of chat messages (100+), and after some investigation i found out that using <ion-textarea> or <ion-input> instead of textarea/input it will trigger changedetection! Which is not something you want when dealing with a large array!

**Source code**
Now I see you like simple examples to reproduce errors (I do too!) so here is one:
http://plnkr.co/edit/mRRVD2TxEL2JsDEbvPTh?p=preview

You should only be concerned about home.page.ts/html (only 20 lines to read)

**steps to reproduce**
Open your console and try to type into the ion inputs, and try to type into the html inputs.
As you probably can notice each single keypress triggers two(!) changedetection events! While with normal html input it triggers zero.
