### ISSUE TITLE
Request - update app-scripts to 1.1.4, ionic-native to 3.1.0

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#10841]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**Current behavior:**
Versions included with 2.2.0 are app-scripts 1.1.3, and ionic-native 2.2.6

**Expected behavior:**
Versions to be app-scripts 1.1.4, ionic-native 3.1.0

**Also**, why is ionic-native versions so weird? no v3.0, no reason to make a new major release, etc..

**Comment by davec21** [comment]
I've always wondered why new Ionic Releases don't use the latest version of the tools made by the same company.. for the same product.

**Comment by brandyscarney** [comment]
App-scripts has been on `1.1.4` since the `2.2.0` release: https://github.com/driftyco/ionic2-app-base/commit/dbc54ed9fdde6681a9a2904b705ccaac84bc86d9

Where are you seeing it still on `1.1.3`?

We don't always update `ionic-native` with every release because we don't like to update it until we've had time to test it, and we don't want to wait on updating the framework because of native. 

Also, with major changes we usually like to have a blog and/or documentation prepared prior to updating our starters. I just updated the starters today to use Ionic Native 3.x though. You can see the changes made in these commits:

https://github.com/driftyco/ionic2-app-base/commit/9de16ab6daa2fde856d52efc97e0f0bdd7acd528
https://github.com/driftyco/ionic2-starter-tutorial/commit/d54d26c119c2709036c8860783d9565f60ebaf5f

Here is the (newly posted) blog on it: http://blog.ionic.io/ionic-native-3-x/

And here is the new documentation on it: http://ionicframework.com/docs/v2/native/

I'm going to close this since our starters are up-to-date. Thanks for the issue!
