### ISSUE TITLE
[Feature] Make ionic 2 PWA seo-friendly

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic#11014]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently, when navigating through the app pages the URL stays the same, and it's impossible for search engines to index specific page / route.

**Expected behavior:**
Just like Angular 2, when a route is assigned, the page URL is changing and it's possible to redirect user to specific page in the application. The Ionic [Deep Links plugin](https://ionicframework.com/docs/native/deeplinks/) has no effect for in-browser urls and it's impossible to share a link to an user profile page (such as mysite.com/user/theunreal), for example.

**Steps to reproduce:**
Irrelevant

**Related code:**

Irrelevant

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
C ordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.2.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. You can use our [Deeplinker](http://ionicframework.com/docs/api/navigation/DeepLinker/) to get URL's for PWA's.

**Comment by theunreal** [comment]
Hey @jgw96, Thanks for the great reference! Any idea why a number sign appears in the URL?
Example: `http://localhost:8100/#/my-page`

**Comment by miqmago** [comment]
@jgw96 thanks, link is no longer working, right now it is here: https://ionicframework.com/docs/2.2.0/api/navigation/DeepLinker

**Comment by BeliliFahem** [comment]
I think IonicPage ([see here] (https://ionicframework.com/docs/api/navigation/IonicPage/)) makes the PWA SEO-friendly. To confirm !

**Comment by vinicius91carvalho** [comment]
First of all, sorry for my poor English.

After searching through Deep Web (joking), I found the solution. And the coolest solution was that I was able to integrate my Pioneer Ionic application with Firebase Hosting using Cloud Functions.

After reading the following topic:

https://github.com/firebase/firebase-tools/issues/33

The @TheRoccoB user explains how to host the static Web application in Firebase Hosting and redirect traffic from a URL to Cloud Functions.

What I did was map the routes that I have to index as:

{
        "source": "/ shop / **",
        "function": "ssr"
      },
      {
        "source": "/ * / promotions / **",
        "function": "ssr"
      }

Since "ssr" is the name of my function in Cloud Functions. So I used the library https://github.com/prerender/prerender-node to check if the request is from a google crowler, in case I redirect the request to a https://github.com/prerender/prerender server.

const prerender = express ();
prerender.use (cors);
prerender.use (
    require ('prerender-node')
    // .set ('prerenderServiceUrl', 'http: // localhost: 3000')
    .set ('prerenderToken', '** TOKEN **')
);
prerender.use (require ('prerender-node'). set ('beforeRender', function (req, done) {
    // do you need to do?
    console.log ('Rendering URL:', req.path);
done ();
}));
prerender.use (require ('prerender-node') set ('afterRender', function (err, req, prerender_res) {
    // do you need to do?
    console.log (req.path + 'rendering completed!');
    console.log ('Errors:', err);
}));
prerender.get ('*', (req, res) => {
    console.log ('Calling function for URL:', req.path);
    res.set ('Cache-Control', 'public, max-age = 300, s-maxage = 600');
    res.status (200) .send (fs.readFileSync ('./ www / index.html'). toString ());
});
exports.ssr = functions.https.onRequest (prerender);
