### ISSUE TITLE
Ionic3: Deep links and initializing the application

### ISSUE THREAD

**Issue by konrin** [driftyco/ionic#11067]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
My app before displaying the first page initializes the current user and a number of actions. With the advent of deep links, the app stopped to wait for the initialization and immediately opens the page in the url, in consequence of which, there are different kinds of errors.

I like the implementation of lazy loading pages, but I don't like the current implementation of deep linking. How to disable deep linking preserving lazy loading? Or how to make the application first initialized, and only then passed on a deep link?

**Expected behavior:**
The application waits for the initialization, then reveals the deep link. Or disabling deep linking while maintaining lazy loading.

**Ionic info:**
```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.0-beta.3
Ionic CLI Version: 3.0.0-beta.5
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.7.2
Xcode version: Xcode 8.2.1
```

**Comment by AmitMY** [comment]
You can use the `route` method instead of the `routeWithNavController`. Then, when a `route` activates, you can subscribe to your authentication event, and when that happens it will open the given page.

**Comment by konrin** [comment]
@AmitMY I never use `routeWithNavController`, it is possible for more information?

**Comment by AmitMY** [comment]
This now became a support question, so I urge you to ask in the forums, but what I was writing above translates to:
```
const routes = {
	'/about-us': AboutPage,
	'/universal-links-test': AboutPage,
	'/products/:productId': ProductPage
};

this.deeplinks.route(routes).subscribe((match) => {
	this.authSubscription.whenDoneWithAuth().subscribe(() => {
		this.nav.setRoot(routes[match.$route]);
	});

	console.log('Successfully matched route', match);
}, (nomatch) => {
	// nomatch.$link - the full link data
	console.error('Got a deeplink that didn\'t match', nomatch);
});
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by AmitMY** [comment]
@jgw96 Just curious, did the ionic team not go to ng-conf? (it is live now, and you are here)

**Comment by chrisjpalmer** [comment]
I have done a dirty hack on my deep linker. It seemed that when I was transitioning through pages using the normal `navCtrl.push('myview')` it was fine, but when I started doing cool stuff like...

URL Bar: `http://localhost:8100/#/x/y`

```
let navStackReconfigured = Observable.of(navCtrl.pop()).flatMap(() => {
	return Observable.of(navCtrl.pop()).flatMap(() => {
		return Observable.of(navCtrl.push('z'));
	});
})

navStackReconfigured.subscribe(() => {});
```

...I ran into issues. Because the URL bar was somehow not in sync, the Deeplinker would inspect the URL bar and see that it still referred to the old stack. It would then attempt to reload (badly) the previous state of the nav stack.

I would end up with 
URL Bar:` http://localhost:8100/#/x/y`
when I should have gotten 
URL Bar: `http://localhost:8100/#/z`

This was the fix:
Inject DeepLinker and...
`this.deepLinker._urlChange = () => {};`
Now it doesn't care when the urlChanges in the URL bar.
This completely disables deeplinking, but I have an app with authentication so it doesn't bother me.
