### ISSUE TITLE
handleFocus  blurs wrong element because of timing  on new active view 

### ISSUE THREAD

**Issue by pberkaloff** [driftyco/ionic#1108]
handleFocus in  'js/utils/tap.js' blurs wrong element because of timing. 

When using a side menu to switch to a view, by the time handleFocus is called the ion-view for the new view has already been instantiated. if that  view contains a textarea or text input that is 'autofocus' it then calls  blurActive() which blurs the element which it should not.

`js/utils/tap.js:`

```
handleFocus: function(ele) {
      if(ionic.tap.activeElement() !== ele) {
        // only set the focus if it doesn't already have it
        if( ele.tagName.match(/input|textarea|select/i) ) {
          ionic.tap.activeElement(ele);
          ele.focus();
        } else {
         ionic.tap.blurActive();
          ionic.tap.activeElement(null);
          ionic.tap.blurActive();  //<<<<here
        }
      }
    },
```

**Comment by jasonwinshell-br** [comment]
Does this issue now have a solution?  When clicking on my clear button the soft keyboard is dismissed, presumably by the input losing focus.

My code is as follows. 

```
<div class="item item-input">
   <input type="text" required name="username" ng-model="formData.username"
      placeholder="User Name">
    <i  class="icon ion-close" ng-model="formData.username"
      ng-click="formData.username = ''"></i>
</div>
```

**Comment by Deminetix** [comment]
This is a different issue. 

When you tap the clear button you could call $event.preventDefault() and $event.stopPropagation() to stop it from closing your keyboard

**Comment by jasonwinshell-br** [comment]
Thanks for the response.

Calling " $event.preventDefault() and $event.stopPropagation() to | stop it from closing your keyboard" didn't work. 

I found (and commented) a couple of other posts on the Ionic forums about this. I didn't see any reliable answers.

http://forum.ionicframework.com/t/bluractive-does-not-allow-to-clear-search-field-without-losing-focus/2849

http://forum.ionicframework.com/t/bluractive-does-not-allow-to-clear-search-field-without-losing-focus/2849/3

???

**Comment by Deminetix** [comment]
Ah yes, i forgot this changed a while back. The current solution we are using is below - It's not perfect, you could use tag names instead of number id's, but you'll get the general idea. We've also been using it in production for ~4 months with no issues on any devices.

1. Create this directive
```
(function () {
    'use strict';

    angular
        .module('glow.app.core.focus')
        .directive('glFocus', glFocus);

    // --------------------

    /* @ngInject */
    function glFocus ($timeout) {

        return {
            restrict: 'A',
            link: link
        };

        function link (scope, element, attrs) {
            // autofocus
            if (attrs.glFocusAuto === 'true') {
                $timeout(function () {
                    element[0].focus();
                });
            }

            // event focus with an id
            scope.$on('gl-focus', function (e, id) {
                if (id === parseInt(attrs.glFocus)) {
                    element[0].focus();
                }                
            });
        }
    }

})();
```

2. Add the attribute to your input/textarea:
```
<input type='text' gl-focus='1' />
```

3. On the element that clears the input, do something like this:
```
clearInput();
$rootScope.$broadcast('gl-focus', 1); 
```

**Comment by jasonwinshell-br** [comment]
Deminetix,

I deconstructed the directive and did a one-off in my controller for the specific form element just to see if the approach works (see below). Still it's a mystery to me why this is necessary. If I call userNameDOMElement.focus () in doClearUser then nothing happens. Why is it necessary to broadcast a focus event (e.g. "my-focus") and then in the event handler, focus in a $timeout. What's going on in Ionic or Angular? I really would like to understand what's going on under the hood.

Thanks

var userNameDOMElement = document.querySelector('#login_username_id');

$scope.doClearUser = function (event, elem) {
   console.log ("doClearUser");
   $scope.formData.username = '';
   $rootScope.$broadcast('my-focus', userNameDOMElement);

}

$scope.$on('my-focus',
   function(evt, elem) {
      console.log (evt);
      console.log (elem);

      $timeout (
         function () {
            elem.focus ();
         },
         0
      );
   }

);

**Comment by Deminetix** [comment]
In that example you don't need the event, it was only built that way to allow seperation of concerns and make it re-usable in more than just one place.

You can remove the broadcast and call a method directly to timeout and focus. 

The timeout is ensure a scope is digested, as in my case there were situations where focus fired immediately as a view came in, it may not be necessary for the above code

**Comment by jasonwinshell-br** [comment]
Thanks for the simplification. I determined that the $timeout approach is still necessary for focus to be regained. Calling it directly on the DOM element does not work (commented out below). So it turns out that whatever $timeout is doing with the $digest loop plays an important role in making the code execute with the desired effect -- restoration of focus. Do you have any insights as to why this would be the case? 

One problem that remains is the behavior of the iOS soft keyboard. When focus on the input is lost the keyboard retracts. When this code reestablishes the focus an instant latter the keyboard goes back up. It's pretty annoying as you can imagine. I think it's essential that I correct this behavior. Thoughts?

A tiny improvement I'd like to make is how I might pass the DOM element (the one looked up by tag ID) directly from the ng-click method on the input. i.e. doClear (theInputDOMElement). That way I could dispense with putting IDs in inputs.


Thanks so much
Jason


$scope.doClearUser = function () {
  $scope.formData.username = '';

  //var elem = document.querySelector('#login_username_id');
  //elem.focus ();
  $timeout (
    function () {
      var elem = document.querySelector('#login_username_id');
      elem.focus ();
    },
    0
  );
}
