### ISSUE TITLE
iOS list elements too sensitive when scrolling (on device)

### ISSUE THREAD

**Issue by epetre** [driftyco/ionic#11141]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Try to scroll a list with like 20-30 elements. Scroll is too sensitive that it will click list element. To scroll without clicking, I've to press screen little hard and then scroll.

**Expected behavior:**
Element should not be clicked when scrolling a list.

**Steps to reproduce:**
I see this behavior on the **iOS devices only**.
It works properly in chrome (device mode) with `?ionicplatform=ios`.
Can't reproduce on safari browser because I don't see a way to use my mouse as a finger (a device mode).

**Other information:**
There was [this closed issue](https://github.com/driftyco/ionic/issues/8622) but since I can't reopen it, I thought I would post it here with a bit more details.

**Ionic info:**

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v4.4.3
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by AndreasGassmann** [comment]
This might be related to the issue I opened a couple of months ago: https://github.com/driftyco/ionic/issues/9945

Have you tried updating to ionic v3? There was a commit recently that was related to js-scrolling. I didn't have time to update my app just yet, but I'm curious if that would fix the issue.

**Comment by epetre** [comment]
I didn't update yet, I'll try on a branch tonight. But I think it's a bug with the way touch is handled on Safari, I played around a little bit with the css on safari, I can't fix it but I have a feeling that they don't handle touch manipulations like chrome does.

**Comment by dylanvdmerwe** [comment]
Also give ionic's WKWebView a try.

**Comment by jgw96** [comment]
Hey @epetre . So yeah, UiWebView has alot of edge cases such as this one because we are forced to use JS scrolling as UiWebView has broken scroll events. We are currently working on making our [fork of the wkwebview plugin](https://github.com/driftyco/cordova-plugin-wkwebview-engine) the default on iOS. Would you mind trying that in your app and seeing if that fixes this issue for you? WkWebView has non-broken scroll events, so we are able to use native scrolling just like we have been using on Android.

**Comment by AndreasGassmann** [comment]
@jgw96 Back when I opened my issue I tried WKWebView and it worked fine. But it looked like WKWebView has a lot of limitations, so I sadly wasn't able to use it in production. Depending on how long it takes to get WKWebView ready, it might be worth fixing this issue because it's something that even gets noticed by users.

**Comment by dylanvdmerwe** [comment]
WkWebView plugin went through a whole bunch of changes about a month ago. You should give it another bash, almost all limitations have been resolved.

**Comment by epetre** [comment]
Nice, thank you will report back here tonight (hopefully 😄 )

**Comment by epetre** [comment]
It works well, just seems to be a bit slower with big lists. How risky do you think it would be to include this in the production version? Other than being a bit slower, it seems to not have big issues.

Just tested it, couldn't wait, our users are complaining alot about this so I had to test.

**Comment by jgw96** [comment]
@epetre So we are planning on making wkwebview the default webview for iOS in the next release. It has had alot of work done to it in the last few weeks and is now in what we think is a production ready state. You can check out the [master branch of the conference app](https://github.com/driftyco/ionic-conference-app) to see an example setup. Since this seems to have fixed the issue for you I am going to close this issue for now. Thanks for using Ionic.

**Comment by epetre** [comment]
@jgw96 just a quick thing I noticed that made me remove it for now. 
It seems to be causing CORS issues.  I was starting to have issues whenever my API was returning error codes and other CORS issues, it seems to be behaving like the app is the server and he view runs in a browser.

If you already have a fix for this, please let me know :D

**Comment by dylanvdmerwe** [comment]
When using WKWebView, any integrations you use MUST implement CORS correctly. There is no fix or workaround.
