### ISSUE TITLE
Ionic 2 Error - No provider for ApplicationInitStatus!

### ISSUE THREAD

**Issue by musasheikh** [driftyco/ionic#11157]
Hello,

I got this error after running ionic app

Ionic 2 Error - No provider for ApplicationInitStatus!

Any solution?

**Comment by rapropos** [comment]
Please use [the support forums](https://forum.ionicframework.com) for support requests instead of submitting GitHub issues. If you had searched them with your error message, you would have found [this thread](https://forum.ionicframework.com/t/runtime-error-no-provider-for-applicationinitstatus/85521) which explains that you forgot to import `BrowserModule`.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by stanlee321** [comment]
I solve this by importing  
`import { BrowserModule } from '@angular/platform-browser';`
in [app.modules.ts](url)
and injecting this lines below as 
`  imports: [
    IonicModule.forRoot(MyApp),
    BrowserModule

  ],`

**Comment by caiyundong** [comment]
@stanlee321 should be app.module.ts

**Comment by stanlee321** [comment]
Sorry typo error. Yes, it is app.module.ts

**Comment by diegodelfin7** [comment]
Thanks @stanlee321 !!  See doc. https://angular.io/api/platform-browser/BrowserModule

**Comment by insync2** [comment]
Thanks@stalee321 Worked for me
