### ISSUE TITLE
rxjs dependency versioning

### ISSUE THREAD

**Issue by jorrit-wehelp** [driftyco/ionic#11164]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ionic-angular depends on rxjs 5.1.1, but this exact version can conflict with other dependencies in the project that use rxjs.

**Expected behavior:**
ionic-angular does not depend on exact version, but allows using bugfix releases without nagging warning from npm. (angular 4.0.0 itself depends on ^5.1.0)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. So we used to do this but the issue here is that its possible that if a breaking change sneaks into RX (and this has happened to us a few times before) that it will break the world haha, therefore thats why we use exact versions. Because of this I am going to close this issue for now.
