### ISSUE TITLE
click on toggle doesn't work on Android

### ISSUE THREAD

**Issue by acessoftware** [driftyco/ionic#11240]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I click on toggle it triggers a function in the browser and iOS and it doesn't on Android.  Actually in 50 times it triggered once. 

**Expected behavior:**
Toggle is supposed to trigger a function when it is clicked on.

**Steps to reproduce:**
Here is the code that I am using. I also tried to us ngModel instead of click. ionChange doesn't work because it triggers event on the load and that doesn't work for me. As I said, it works perfectly fine in the browser and on iOS, but on Android it does nothing. Not sure what's an issue. Thanks

` <ion-toggle item-right (click)="updateStatusChange('verified')" [formControl]="updateUserStatusForm.controls['verified']" checked="{{user.verified}}"></ion-toggle>
`
-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: OS X El Capitan
Node Version: v6.10.0
Xcode version: Xcode 8.2 Build version 8C38```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic, we will look into this.

**Comment by acessoftware** [comment]
I solved this with following code:

`<ion-item>
        <ion-toggle [(ngModel)]="isChecked" (ionChange)="applianceChange($event)"></ion-toggle>
</ion-item>

applianceChange(ev){
    if(ev._checked == this.isChecked){
        callAction();
    }
}

callAction(){
    ...
     this.appliance.state = this.isChecked //it's important to change value so it can react properly on ionChange
    ...
}`

You need to declare isChecked as boolean and give it a value in ngOnit or constructor when you make your server call. I hope this helps to somebody

**Comment by tattivitorino** [comment]
I am still having this kind of problem with the toggle. I have a list of custom components with the toggle inside each component where it is supposed to show/hide additional actions on the screen. hte problem is that they get all messed up in both android and ios. Instead of showing the ui inside its own component it triggers others. 
here's my code:

`<ion-toggle [(ngModel)]="_item.checked" (ionChange)="onToggleChange($event, _item)" color="secondary"></ion-toggle>`

here the ui it is supposed to control (now i am using ngIf to see if it works)

`<ion-col col-10 offset-1 col-md-8 offset-md-2 flex-col align-center justify-center
*ngIf="_item.checked"> </ion-col>`

here is my component class

`export class CheckDocumentacaoItemComponent {

  private _item:any = {};
  @Input() 
  set item(val:any){
    **this._item** = val;
    this.setupItem();
  }
  constructor(){}
  ngOnInit(){
    this.evtSubscribe();
    console.log('onInit');
  }
  ngOnDestroy(){
    this.evtUnsubscribe();
  }
  protected evtSubscribe(){
    this.events.subscribe('documentRecord:saved', 
      (record)=>{        
        if(this._item.id == record.id){
          console.log('DOC CHECK SAVED ID: ', record.id);
          if(this._item.date && this._item.date.indexOf('-') != -1){
              this._item.date = this.dateService.reverseDate(this._item.date);
          }
          this._buttonColor = 'secondary';
          this._buttonText = 'Atualizar Item';
          **this._item.checked = true;**
        }
      });
  }
  protected setupItem(){
    if(!this._item) return;
    **this._item.checked = false;**
    if(this._item.date && this._item.date.indexOf('-') != -1){
        this._item.date = this.dateService.reverseDate(this._item.date);
    }
    if(this._item.saved){
      this._buttonColor = 'secondary';
      this._buttonText = 'Atualizar Item';
      **this._item.checked = true;**
    }
  }
  protected onToggleChange(ev, item){
    **item.checked = ev._checked;**
    console.log('onToggleChange', item.id, item.checked, ev._checked);
  }
}`

My system infos:
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v6.5.0
Xcode version: Xcode 8.1 Build version 8B62
