### ISSUE TITLE
Unmet peer dependency with @angular/*@4.0.2

### ISSUE THREAD

**Issue by mnasyrov** [driftyco/ionic#11268]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Ionic 3.0.1 allows to use only `@angular/*@4.0.0` as peer dependencies.

**Expected behavior:**
Less strict version requirements for the peers, allow to use different patch version, e.g. `@angular/*@4.0.2`.

**Comment by AmitMY** [comment]
They do this strict versioning because they are more confident in having one usage instead of different dependencies support and problems.
Next version (I am guessing it would release by tomorrow) is running `4.0.2` 
https://github.com/driftyco/ionic/blob/master/package.json#L28

**Comment by jgw96** [comment]
Hello all! @AmitMY is exactly correct on this. Because we have been burned many a time in the past with non-strict dependencies, to provide the best user experience with versions of deps we know 100% for sure that are going to work out of the box, we have our package.json setup to be very strict. The next version of Ionic which will be out next week around Wednesday will be on `4.0.2`.
