### ISSUE TITLE
Nav Animations Fire Every Other Time

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#1142]
Animation effects between views only occur every other time.

Nightly Sample : http://codepen.io/calendee/pen/fJxaq
Beta Sample : http://codepen.io/patrickarlt/pen/jFCnt/

Click on the "Go To Bar" button.  No animation. Now click on the "Go To Home" button.  No animation.  Now click on the "Go To Bar".  The animation works this time. Now click on the "Go To Home" button.  The animation works this time.

Rinse and repeat the process above.

Forum : 
- http://forum.ionicframework.com/t/how-to-animate-between-states-that-are-not-nested/2947/6
  - http://forum.ionicframework.com/t/page-transition-animation-fires-every-other-time/741

**Comment by jfernandez1492** [comment]
@calendee  I believe you haven't find the solution yet. The problem is when 2 states aren't at the same path level, for example take app.tabs.home and app.facts, it will work on changes between app.tabs and app.facts because they both are directly below app but won't work with app.tabs.home and app.facts. On your example you switch between app.search and app.tabs which are below app. I've been struggling with this for a while. My email is jfernandez@uclv.cu, please contact me, if you can´t, please leave a comment.

**Comment by Sshuichi** [comment]
Any news about this issue ?
