### ISSUE TITLE
Boot time

### ISSUE THREAD

**Issue by jonatasfreitasv** [driftyco/ionic#11456]
My boot load time is 7 seconds, any why to make boot more fast ? I may be doing something wrong?

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0-rc.0

local packages:

    @ionic/app-scripts              : 1.3.4
    @ionic/cli-plugin-cordova       : 1.0.0-rc.0-alpha.b7f97e5d
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0-alpha.b7f97e5d
    Ionic Framework                 : ionic-angular 3.1.0

System:

    Node       : v7.5.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.2 Build version 8C38
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13

**Comment by MTechDE** [comment]
Did you run ionic cordova build android/ios --prod?

**Comment by manucorporat** [comment]
And use the WK plugin for iOS: https://github.com/driftyco/cordova-plugin-wkwebview-engine

**Comment by jgw96** [comment]
Hey @jonatasfreitasv , boot time is something that we are constantly working on lately. As you probably know, startup time is something that the entire web community has been struggling with lately, and since we are entirely mobile-focused startup time is incredibly important to us. Here is a list of the things on our end that currently can cause issues with boot time:

1. Angular is a relatively large framework
2. Angular currently requires relatively large polyfills
3. Treeshaking simply does not work well with Webpack / Angular

Now, these are things that not only we are working on fixing but that the Angular team is working on fixing too. We work directly with the Angular team and have been working together with them to try to solve these issues.  Despite all this, there are things that you can do on your end to help with load time as it sits now. To be clear, this is not going to solve the issue completely, as like I stated before we are making changes on our end for this issue too, but it will give your application a head start to faster load times. Here is a list of things you can do in your app to help with startup time today:

1. Implement lazy loading in your app. Mike did a really good blog post on this recently (http://blog.ionic.io/ionic-and-lazy-loading-pt-1/). The Untappd team saw great improvements in their startup time from implementing lazy loading.
2. Make sure you are not using any third-party libraries that are not essential to the functionality of your app. Third party libraries such as momentjs, lodash and more are older, were built in a time when mobile was not the dominant entry point to the web and because of this tend to be unnecessarily large. If you are using libraries like these I urge that you look at more modern alternatives that are smaller and more modular such as https://github.com/date-fns/date-fns.
3. Always makes sure you are doing a production build by building with the `--prod` flag.

Hopefully this helps with your app!
