### ISSUE TITLE
bug: Ionic Lazy Loading modules, pages,. are not cached

### ISSUE THREAD

**Issue by abusharaf** [driftyco/ionic#11593]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If you are using lazy loading in ionic 3.x and you went through the Nav Mechanism that ionic provide to a second page, that page constructor which is being loaded lazily is being executed each time the page is requested, is this a normal behavior, I don't think so as this actually not utilizing the cache, and also when you go back to the parent page which is being loaded on the startup of the app (No Lazy Load Here - Default) also it's constructor is being invoked each time and sometimes no</span>

<span is-issue-template></span>

**Comment by astec** [comment]
Page constructor is invoked every time you open a page (both standard or lazy loading) - this is by design.

So I believe it's not a bug.

**Comment by mhartington** [comment]
Let's look at how navController works:


- Your app starts off on Component A, the you navigate (push) to Component B.

At this point in time, Component B is created and the constructor is fired. Working as expected.

- You go back (pop) to Component A. 

Component B is destroyed since we do not cache forward views. Component A is till cached since it is the "back page" so it's constructor does not fire again.


- You push Component B again

Component B is recreated and the constructor is fired again.


This is how the navigation system cache works. If you navigate forward to new components, they are created and instantiated. Only view that you pop back to are cached.

**Comment by abusharaf** [comment]
Yah, that's clarify things here, and it's very good, thanks a lot, ok so another question regarding the case please:

- If i used the setRoot method instead of pop that means the nav flow will go to another stack let's say and the first stack that contains A & B will remain untouched, so i went back to it using your new deeplink system that means the cached version will render to the page is that correct?

**Comment by mhartington** [comment]
Not quite. `.setRoot` will clear the navigation stack. It's meant to be a "reset the history" method.

**Comment by abusharaf** [comment]
thanks for your swift response, and on the other hand the cache in this ionic latest version will be much utilized in the case of nested pages structure or tabs for example.

Thank again, this is one of the best platforms I've ever worked on, I hope you will always continue the great work 🥇
