### ISSUE TITLE
Ionic serve throw run time error

### ISSUE THREAD

**Issue by sdubey472** [driftyco/ionic#11647]
global packages:

@ionic/cli-utils : 1.0.0
Cordova CLI      : 7.0.1
Ionic CLI        : 3.0.0

local packages:

@ionic/app-scripts              : 1.3.7
@ionic/cli-plugin-cordova       : 1.0.0
@ionic/cli-plugin-ionic-angular : 1.0.0
Ionic Framework                 : ionic-angular 3.2.0

System:

Node       : v7.0.0
OS         : Linux 4.8
Xcode      : not installed
ios-deploy : not installed
ios-sim    : not installed

Error is given bellow

dev server running: http://localhost:8100/

Error: app-scripts serve unexpectedly failed.

(node:3412) UnhandledPromiseRejectionWarning: Unhandled promise rejecti on (rejection id: 1): Error: channel closed (node:3412) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections th at are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sdubey472** [comment]
Any one can help me to resolve this issue I am struggling from yesterday morning.

**Comment by AmitMY** [comment]
@sdubey472 I recommend opening an issue with https://github.com/driftyco/ionic-app-scripts , as this issue seem to be originating there.

I would also suggest updating node to 7.9.0, as from my experience it works, and next time, just use `ionic info` instead of laying all of the versions like that, and fill the issue template, as it is more readable and issues that are not to template should be closed.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#990
