### ISSUE TITLE
Fixed rxjs version

### ISSUE THREAD

**Issue by nfantone** [driftyco/ionic#11741]
To a certain extent, I can understand the reasons behind locking `@angular/*` dependencies' versions (though, I wonder why not declaring ranged dependencied, instead). But would someone explain why is `rxjs` fixed?  It's been targeting `5.1.1`, a [months old release](https://github.com/ReactiveX/rxjs/releases/tag/5.1.1), since [Angular 2.4.8 came out](https://github.com/driftyco/ionic/commit/555519da620b3db3c7b0111a45dbb747e58e4f51#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R38). This is especially intriguing since [Angular itself _does not_ lock](https://github.com/angular/angular/blob/master/package.json#L26) its `rxjs` dependency version (it fact, it doesn't for any of its dependecies).

The reason I'm asking is because today, I stumbled upon an issue while using `rxjs` related to `fromPromise` input type - which was solved, [merged](https://github.com/ReactiveX/rxjs/pull/2505) and [released in latest `5.4.0`](https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#540-2017-05-09). I upgraded my local `rxjs` version and, while everything worked just fine, `npm` expectedly complains about a missing peer dependency.

```
npm WARN ionic-angular@3.2.1 requires a peer of rxjs@5.1.1 but none was installed.
```

Is there something in `ionic` that would justify forcing this particular version?

**Comment by jgw96** [comment]
Hello, good question! In the past, we did not have all of our deps fixed, but this began to create issues around the latest releases of things having breaking changes or bugs that caused apps created with the ionic-cli to break right out of the box (obviously an issue for developer experience). Because of this, we decided to pin all of our dependencies to specific versions that we had done all of our testing with so that we could be sure that an out of the box ionic app worked as expected. So, while this meant that we would not always be on the latest and greatest by default, we were able to ensure a working experience. Now that things have stabilized in the Angular world, we have been updating dependencies faster and will continue to make sure we keep our deps as close to the latest as possible to get all the latest bug fixes in these libs.

**Comment by nfantone** [comment]
@jgw96 Hello and thanks for taking the time to explain me this!

I understand your points and was expecting something along those lines - but, to be honest, you didn't really answer my question which was:

> Is there something in `ionic` that would justify forcing this particular version? 

It seems to me that, in this case, locking seems more like a "conceptual" practice rather than an answering to a practical need. A practice that is hindering development for Ionic users.

**Comment by nfantone** [comment]
@jgw96 Sorry to insist on this, but today this bit me once again. A [bug in `timeout` operator](https://github.com/ReactiveX/rxjs/pull/2580), that was fixed in April and included in a May release of `rxjs`, had me scratching my head the whole morning.

You should _really_ consider unlocking versions for this case. Or, at the very least, depend on a more recent one?

**Comment by soumak77** [comment]
@jgw96 Is there any update here?  Can't you at lock down to `rxjs: ^5.4.0` so that minor patches can be consumed? Or at the very minimum remove the peer dependency so that builds do not break when using a version of rxjs other than `5.4.0`.
