### ISSUE TITLE
Textarea not scrollable

### ISSUE THREAD

**Issue by ashconnell** [driftyco/ionic#1280]
Tested on a bunch of android devices (Nexus 5: 4.4, Galaxy S4: 4.3, Galaxy S3) and iOS devices (iPhone4S: iOS6, iPhone5: iOS7.1) and the textarea is not scrollable when the content is larger than the textarea size.

Also of note, the `keyboard-open` class is not added to body element like inputs are.

Version: Beta3

I'm using basic recommended html

```
<div class="list">
    <div class="item item-input">
        <textarea></textarea>
    </div>
</div>
```

For others who also might need a quick fix, I am going to throw in an autogrow script.

**Comment by bassettsj** [comment]
Hi! :wave:

Have been working around this issue on a problem within our application. The fixes in df74b26 definitely helped! I still have one edgecase problem. I created an [example codepen](http://codepen.io/bassettsj/pen/XJNwVL) showing the behaviour seen when scrolling the page when the textarea is focused. I could look into adding a PR if you might be interested, but I thought I should check first if you think ionic core should support the pattern of adding a `.item-input-inset > label.item-input-wrapper > textarea` to applications. What are your thoughts?

**Comment by mikeacook** [comment]
I'm hitting the same issue on Ionic Beta 14, any update on this? @perrygovier

**Comment by karna41317** [comment]
Same here :( , when focused can't scroll.

**Comment by clickonchris** [comment]
I'm also confirming that this problem still exists beta14, and also 1.0rc1.  I'm testing on IOS.

**Comment by hasandogu** [comment]
Having the exact same issue. Can't scroll the page when the textarea has focus. It is especially difficult [read impossible] with an autogrowing text area and when it gets larger than the visible content.

**Comment by numerized** [comment]
I'm having the same issue, I'm using angular-elastic.

For me the temporary fix is to revert manually these changes at least in the keyboard.js and scrollview.js:
https://github.com/driftyco/ionic/commit/5f2fdfdd07d2cfcfa03113a4f94b302a13a6909e

**Comment by danfaber** [comment]
Hi, does anyone have any advice / updates on this.
I have the same issue as recent posts - when the focus is on a text area it is not possible to scroll the entire page.  I imagine this is because it thinks it should be scrolling within the text area itself - so I see that there might be no clean way around this (should it scroll the page or the text area!).
Thanks.

**Comment by msevestre** [comment]
What about using something like
https://github.com/monospaced/angular-elastic
That way the textarea automatically resizes to its content and the issue
with double scrolling disappears...

**Comment by danfaber** [comment]
Thank you @msevestre  - I've just added angular-elastic which made the text-areas better sized.  The scrolling problem still remained, so I reversed scrolling within checkboxes as @numerized recommended (https://github.com/driftyco/ionic/commit/5f2fdfdd07d2cfcfa03113a4f94b302a13a6909e) and all is good in the world.

**Comment by qualiabyte** [comment]
Yes, thanks @numerized and @msevestre. I also ran this issue where a large textarea becomes unscrollable when in focus. Manually reverting change 5f2fdfd (keyboard.js and scrollView.js) from ionic.bundle.js fixed the issue for me.

Also commented out the scrollChildIntoView event listener for now. It seems to scroll to the *middle* of the textarea (rather than the cursor position), not so useful when the text is screen-size or even larger. This is essential since I'm using angular-elastic for an auto-expanding textarea as well.

If there were a way to scroll to the *text cursor position* instead (maybe by tracking the last click coordinates), that might resolve some issues here and in #2901.

**Comment by Deminetix** [comment]
Yep agreed. It looks like Ionic just scrolls the center of the textarea to the center of the viewport, where-as it might work better if it scrolls to the position of the tap

**Comment by bittu1028** [comment]
I've added angular-elastic but the scrolling issue still remained. Cant scroll the view when it is focused on the text area.Any solution for that......

**Comment by mihail-petkov** [comment]
Adding `overflow-scroll="true"` to `ionic-content` fixed the problem for me! :)

**Comment by msevestre** [comment]
I can confirm that adding `overflow-scroll="true"` and using angular-elastic just works perfectly

**Comment by ravishtiwari** [comment]
Adding ```overflow-scroll="true"``` to ```ion-content``` does not resolves the issue. I am using __v1.1.0__ and have following markup:
```
<ion-item id="titleItem" class="item-input">
  <textarea overflow-scroll="true" id="title" placeholder="Enter title"></textarea>
</ion-item>
```

**Comment by mklilley** [comment]
Hi,

I am using ionic 1.2.4.  I also have a problem with a fixed size textarea.  When it is in focus i am no longer able to scroll the view.  I have inputs on the same view and I have no problem scrolling when they are in focus.

Is there any comment from the ionic team on this one?

**Comment by mica16** [comment]
Same issue, using ionic v1.1.0. 
@ravishtiwari Please note that you set overflow-scroll="true" on the ```textarea``` itself instead the ```ion-content```. 
However, it does not works for me. 
Applying native scrolling or not doesn't change anything for this issue. 
It's really frustrating, since this "feature" is by far the most used by users filling forms. 

Has anyone another idea ?  I also tested ```overflow-scroll``` associated with angular-elastic, it doesn't work.

**Comment by judezhu** [comment]
+1. same issue here. ```overflow-scroll ``` does't work for me as well.

**Comment by jgw96** [comment]
Hey all! Are you still having this issue with the latest version of ionic 1 (v1.3.0) ?

**Comment by mklilley** [comment]
Hi.

I just upgraded to v 1.3.1 and I still have the same problem.

How best should we proceed with this?

Thanks,

Best regards,

Matt

**Comment by omarmeky** [comment]
+1

**Comment by nadeemkhan** [comment]
+1

**Comment by anurag6792** [comment]
+1

**Comment by PhilHuot** [comment]
Adding `overflow-scroll="true"` to` ion-content` does allow scrolling while the textarea is focused (keyboard open), but when unfocused, scrolling directly on the textarea is impossible... You have to scroll on elements outside of the textarea which is hard when you have a big textarea in the page.
Someone else is experiencing this or is it just me?

**Comment by hassanajazch** [comment]
Same issue here @PhilHuot , cant scroll when try to write long text, at-least not working on Android. 
overflow-scroll="true" did not fix anything.
Anyone try to fix it?

**Comment by ruairisdad** [comment]
Not a great solution, but I just added a bit of left padding to the containing element of the textarea.  That way, users can grab that bit of "left border" and use that to scroll the ion-content

**Comment by selknam** [comment]
I was able to fix this issue by overwriting the overflow of my textarea:

`overflow:visible !important;`

Now it works on browser and android (with an up to date ionic v1).
