### ISSUE TITLE
iOS: Page able to be dragged horizontally

### ISSUE THREAD

**Issue by ajoslin** [driftyco/ionic#1285]
Best reproduce case I've found so far is at http://ionicframework.com/demos/collection-repeat.

Drag the header left or right.

Mentioned in #1157

**Comment by abrahamvelazquez** [comment]
I can still reproduce this issue with Beta 14 on iOS. An overflow shift would automatically happen when a `select` was triggered on device/simulator. You could see a white 1px line on the right side.

It's specifically `.bar .title + .buttons { right: 5px; }` that is causing the issue. Changing to right: 6px;` does solve the issue.

The best/simplest fix I could find was just adding `.bar { overflow: hidden; }` to my project. I have not seen any negative impact because of that added rule, so it might be worth adding it to `_bar.scss`.

**Comment by mhartington** [comment]
Can you provide a simple codepen that can replicate this?
