### ISSUE TITLE
Modal with `fade-in` animation pops up again briefly when closing

### ISSUE THREAD

**Issue by robdmoore** [driftyco/ionic#1286]
I've got a replication here: http://plnkr.co/1yPYTl6ulvtV0HMrMts3 - if you open the modal and then click close it flashes up. This happens with Chrome and iOS at the very least.

This is against nightly.

**Comment by Ionitron** [comment]
Greetings @robdmoore!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.

**Comment by jenningsjin** [comment]
I had this issue, but was able to resolve it when it was discovered that one of the html tags was not closed properly on the line calling the function.
