### ISSUE TITLE
header bar align() processed too early

### ISSUE THREAD

**Issue by pberkaloff** [driftyco/ionic#1343]
The calculations done within  header bar align() are executed too early.
 
Even within the callback from requestAnimationFrame, the offsetWidth for the left buttons div might not yet be up to date. 

So If you have a left-buttons div that varies in width between the old and the new view the title will be positioned improperly

**Comment by Ionitron** [comment]
Greetings @pberkaloff!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
