### ISSUE TITLE
Problem with scrollling not working on Samsung S3, Android 4.3, Internet browser, non-wrapped

### ISSUE THREAD

**Issue by robdmoore** [driftyco/ionic#1433]
When I view this plunkr in the above device then scrolling doesn't work at all: http://plnkr.co/edit/NMkBgGRNHsA9NE2rnK5A?p=preview

**Comment by Ionitron** [comment]
Greetings @robdmoore!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.

**Comment by dannyg** [comment]
I have this scrolling issue also.

On my own codebase I am using latest ionic (1.0.0-beta.14), while following codepen uses nightly.
The problem is reproduceable in both.

Here is the codepen:
http://codepen.io/dglenn/pen/xbLWEm

On my physical device (Galaxy S3 running Android 4.3) I cannot scroll the resulting list.
The other physical device I have is iPhone 4s on which it scrolls fine.
On desktops it works fine also.

Using browserstack I have run through a bunch of emulated devices, and they all seem to scroll fine, but the combination of Galaxy S3 running 4.3 is not available, so I am unable to confirm the exact platform versions this is happening on, but it is definitely happening on Galaxy S3 / 4.3 combination.

Note that Chrome on the same S3 scrolls correctly, this issue only affects the native browser.

I hope this is sufficient info, but please let me know if not.
