### ISSUE TITLE
Cannot select text within input inside a scrollable view

### ISSUE THREAD

**Issue by bostondv** [driftyco/ionic#1475]
On a desktop browser (tested Chrome and Firefox latest) the text content of an input or textarea within an <ion-content scroll="true"> cannot be manipulated with the mouse cursor.

This codepen demonstrates: http://cdpn.io/oywDJ

The input can receive focus and using the keyboard text can be added and deleted but text cannot be selected nor can you use the mouse to place the cursor as it instead seems to always put the cursor at the beginning or end of the text.

I would expect the behaviour to allow click and drag to select text within the input as well as the cursor to appear in the position clicked.

Thanks!

**Comment by BrianPurkissClarity** [comment]
I'm having the same problem. 

Text is not selectable on the desktop or on mobile. And not being selectable on mobile is the bigger concern, it means that people cannot copy/paste the text in my app. Which is quite important.

**Comment by Ernestoschiavo** [comment]
After two years I have the same problem, also on mobile!! Is there any solution? Thanks

**Comment by ChrisGibb** [comment]
2018 still a problem. Guys this is a silly bug to have. Ionic works great on desktop but this is a behaviour that's very strange for users who are used to selecting text with the mouse.

I understand "focus" might not be on desktop, but this can't be hard to fix. If you could allow us to to call         
this.slides.lockSwipes(true) to disable what ever drag handlers are there, that would surely do the trick.

Please guys!

**Comment by ChrisGibb** [comment]
@eeschiavo @BrianPurkissClarity @erivan Here's my nasty hack to fix this issue. 

```
ngAfterViewInit(): void {
 setTimeout(() => {
  try {
   (this.slides as any)._unregs[0]();
  } catch (e) {
   console.error(e);
  }
 }, 1000); <---- experiment with this
}
```
This is a very rough fix and I'm in a hurry to fix an issue for a client so still need to check if there's any serious negative side effects from doing this - apart from the obvious that you can't drag the slides anymore, in my case doesn't matter because I have buttons for this.

But anybody else coming here you can try this approach.

@IonicProSupport it would be nice if we had a nice public function for accessing `_unregs`. Then we could disable the ion-slides events properly.
