### ISSUE TITLE
Nav Bar / Back Button / Nav Clear Issues

### ISSUE THREAD

**Issue by niltz** [driftyco/ionic#1525]
I have found a couple issues with the ion-nav-bar/ion-nav-back-button/nav-clear. I'm not sure if they are related or not, so I will describe them both

###### First issue - Sometimes the back button isn't visible when it should be
See this [codepen](http://codepen.io/niltz/pen/DBHoh?editors=101)

And follow these steps:

1. Open menu
1. Click "Account"
1. Click "Account Sub"
1. Notice the "Back" button
1. Click "Back"
1. Open menu
1. Click "One"
1. Open menu
1. Click "Account"
1. Click "Account Sub"
1. Notice the "Back" button is now missing

The "Account Sub" link does not have a nav-clear, so the navigation history should not get cleared.

###### Second issue - Sometimes the back button is visible when it shouldn't be
See this [codepen](http://codepen.io/niltz/pen/xtcvq?editors=101)

And follow these steps:

1. Click "Nav 1"
1. Click "Nav 2"
1. Click "No Nav"
1. Click "Nav 2"
1. Notice the "Back" button is there when I don't think it should be

The "No Nav" has a nav-clear, so shouldn't the nav-bar history be removed? Also, the ion-nav-bar is completey removed when going to "No Nav" so I would expect that the ion-nav-bar history would be cleared.

**Comment by Ionitron** [comment]
Greetings @niltz!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
