### ISSUE TITLE
Side menu back animation done on main view

### ISSUE THREAD

**Issue by Takkuz** [driftyco/ionic#1528]
While using nested views in side menus, back animation don't be done on side menu but on main view.  
Unusual configuration, I take so log to keep it working.  
Thanks to this pen.  
http://codepen.io/anon/pen/iLqka

Maybe it should be an AngularJS issue.

**Comment by Ionitron** [comment]
Greetings @Takkuz!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
