### ISSUE TITLE
Input type="text" does not work in frame on iOS

### ISSUE THREAD

**Issue by stefek99** [driftyco/ionic#1534]
Video: https://www.youtube.com/watch?v=pj1YmMvzAWc (1m 24s)

![input](https://cloud.githubusercontent.com/assets/249703/3134341/b6c80b92-e824-11e3-8f3d-846ec80cd4cc.gif)

Code: http://plnkr.co/edit/uIC1MxxqmS6s5d6gLwEo?p=preview

Preview: http://run.plnkr.co/7eteB3OaVmNDdZt0/
```
<iframe src="iframed-pure.html" height="100px"></iframe>
<iframe src="iframed-ionic.html" height=50% width=100%></iframe>
```

Pure iframe works:
```
<input type="text">
```

Ionic iframe doesn't... But only on iOS (Safari and Chrome). On desktop, Android, Windows Phone it works.

Any ideas?

**Comment by perrygovier** [comment]
Gonna call this closed. Let me know if it pops up again.

**Comment by pugwonk** [comment]
Hi there - I'm experiencing what I think is exactly this issue. If you look at http://mycoast.org/temp/frame.html on a non-iOS device, it shows you a login prompt you can type into.  If you look at it on an iOS device, you can't type anything. If I drop the Ionic JS script, it works fine. I thought from this thread that perhaps it was due to me using an older version of the framework, but I'm also seeing it using /1.0.0-rc.2/js/ionic.bundle.min.js.

And yes, I know loading Ionic in a frame is a terrible idea - I'm planning to change this but right now my site needs to work this way. :)

**Comment by pugwonk** [comment]
If it helps at all, I notice that attaching events to $(document).keypress also stops working if Ionic is loaded in a frame (this is on all browsers, not just iOS).

**Comment by pugwonk** [comment]
Just in case anyone else is fumbling over this... I managed to get it to struggle into life by catching the ng-keypress event and manually adding the key code to the string. Something like:

<pre><code><xmp><input id="inpid" type="text" ng-controller="KeyboardFix" ng-model="inputValue" ng-keypress="getKey($event, \'inpid\')"></xmp></pre></code>

And then...

<pre><code>app.controller("KeyboardFix", function ($scope) {
	$scope.inputValue = '';
	$scope.getKey = function(event, forInput) {
		if (document.getElementById(forInput) != null) {
			$scope.inputValue += String.fromCharCode(event.keyCode);
		}
		event.preventDefault();
	}
});</code></pre>

**Comment by miaotmac** [comment]
any solution on this issue？

**Comment by nil135** [comment]
You need to add one css only to input elements.

```
input {
    -webkit-user-select: text; /* Chrome, Opera, Safari */
    -moz-user-select: text; /* Firefox 2+ */
    -ms-user-select: text; /* IE 10+ */
    user-select: text; /* Standard syntax */
}
```

**Comment by harryizquierdo** [comment]
Thanks nil135, I used the solution
