### ISSUE TITLE
Ionic text field clear button

### ISSUE THREAD

**Issue by ajbraus** [driftyco/ionic#1567]
Sorry if this is a duplicate, but it would be awesome if there were an ionic module for adding a text field clear button. This is a great mobile heuristic and very useful.

example:
http://stackoverflow.com/questions/2803532/how-do-i-put-a-clear-button-inside-my-html-text-input-box-like-the-iphone-does

**Comment by jesseplymale** [comment]
Here's a good discussion that relates to this: http://forum.ionicframework.com/t/cannot-tap-click-a-clear-search-icon-inside-an-input-label/4237/8

Use the same technique: Either rename the enclosing <label class="item-input-wrapper> to be a <div>, or use the "on-touch" directive instead of "ng-click".
