### ISSUE TITLE
[Ionic v4] Theming underline on ion-input activated 

### ISSUE THREAD

**Issue by TakkuzOld** [driftyco/ionic#16495]
Every info is on #16445 

**Describe Preferred Solution**
I think bottom border on ion-input should be themable.

Changing primary color on an entire component I don't think could be a option, and also using `/deep/` is something that could create many side issues.

I understand that create many variable could be overwhelming but this behaviour is defined as a feature. :grin:

**Comment by brandyscarney** [comment]
Thanks for the issue! Just so I understand correctly, you are looking for global CSS variables to customize only the input highlight? For example, something like:

```
--ion-input-highlight-color-valid
--ion-input-highlight-color-invalid
--ion-input-highlight-color-focused
```

Is there a reason you can't target `ion-item` directly without wrapping it in the content? Something like the following:

```
ion-item {
  --highlight-color-focused: red;
}
```

See the codepen here: https://codepen.io/brandyscarney/pen/JemeJR?editors=1100

**Comment by Takkuz** [comment]
Yes... Actually `--highlight-color-focused` is always initialized at `--ion-color-primary`.

I can't target `ion-item` because I created a component that contains many of them and I add many of this components to `ion-content` and I need to change the `--highlight-color-focused` dinamically based on user interaction on `ion-content` but without changing `--ion-color-primary`.
