### ISSUE TITLE
Ion-nav-view animation issues

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#1744]
Issue: Can't apply `animation="slide-in-up"` to ion-nav-view
Version: 9/nightlies

Seems that if you enter `slide-in-up` for an `ion-nav-view` animation style, it doesn't work.

@mlynch or @adamdbradley, any particular reason for this?

http://codepen.io/mhartington/pen/txDnm

**Comment by Ionitron** [comment]
Greetings @mhartington!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
