### ISSUE TITLE
Function inside ionic.Platform.ready() is never fired on android

### ISSUE THREAD

**Issue by ThiagoNP3** [driftyco/ionic#1751]
I have an app that needs to use the cordova plugins in it's initialization process.

So I tried to do the following:

<pre>
ionic.Platform.ready(function(){
  angular.bootstrap(document.getElementsByTagName('body')[0], ['myApp'])
});
</pre>

But the function never gets called and my app does not initialize. On the IOS simulator and on google chrome, this works fine.

Any ideas?

**Comment by slownslower** [comment]
I refer to the post by ThiagoNP above, dated Jul 15, 2014.

I further refer to the code, reproduced here:

    ionic.Platform.ready(function(){
        try{
            angular.bootstrap(document.getElementsByTagName('body')[0], ['starter'])

            if(window.cordova && window.cordova.plugins.Keyboard) {
                cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
            }
            if(window.StatusBar) {
                StatusBar.styleDefault();
            }
        }
       catch(e){
         alert(e)
       }
    })

Look at the first 3 lines of the code.  We have embed an "`angular.bootstrap()`" inside `ionic.Platform.ready()`.

If angular does not bootstrap (assuming no `ng-app="starter"`), will `ionic.Platform.ready()` ever fire?

**Comment by jimthedev** [comment]
@slownslower The code shown would be used instead of having an ng-app="starter" on your body tag. Essentially angular.bootstrap does the same thing as ng-app except it does it using javascript. It is also sometimes referred to as manual bootstrapping. You can read a bit more about it here: http://icelab.com.au/articles/manually-bootstrapping-angularjs-for-asynchronous-loading-in-internet-explorer/
