### ISSUE TITLE
Border issue with ion-list

### ISSUE THREAD

**Issue by mackbrowne** [driftyco/ionic#1786]
Getting a weird thick bottom border when using ion list.  Can't figure out exactly why this is happening.  It seems completely random.

![screen shot 2014-07-14 at 10 33 13 am](https://cloud.githubusercontent.com/assets/1291776/3572037/e72139aa-0b63-11e4-9654-fc21cc742479.png)

I was able to fix the issue by adding a "style="border-bottom:white;" to the upper item surrounding the thick border.  Here you can see how the workaround below.

![screen shot 2014-07-14 at 10 35 23 am](https://cloud.githubusercontent.com/assets/1291776/3572075/2d0965d2-0b64-11e4-8442-a5d0a4f37038.png)

Here is my code before the workaround:

```html
<ion-item class="item-icon-left">
  <i class="icon ion-map"></i>
  <h2></h2>
  from
</ion-item>
<ion-item class="item-icon-left">
  <i class="icon ion-ios7-calendar-outline"></i>
  <h2>undefined</h2>
</ion-item>
<ion-item class="item-icon-left">
  <i class="icon ion-android-data"></i>
  <h2>undefined</h2>
</ion-item>

<div class="row">
  <ion-item class="col item-icon-left">
    <i class="icon ion-log-out"></i>
    <h2 class="timeTab">
      {{formatTime(currentTrip.depart_after)}}
    </h2>
  </ion-item>
  <ion-item class="col item-icon-left">
    <i class="icon ion-log-in"></i>
    <h2 class="timeTab">{{formatTime(currentTrip.arrive_before)}}</h2>
  </ion-item>
</div>

```

**Comment by Ionitron** [comment]
Greetings @mackbrowne!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.

**Comment by fabiomig** [comment]
Im still facing this problem of double border lines

**Comment by fabiomig** [comment]
And im using the lastest version

**Comment by fabiomig** [comment]
![screenshot_2015-07-20-22-44-23](https://cloud.githubusercontent.com/assets/8770466/8788247/eae148b8-2f30-11e5-9eed-2b5052396027.png)

**Comment by dillix** [comment]
@fabiomig, reopen issue and write your device & os version.

**Comment by mhartington** [comment]
@fabiomig please open a new issue and post any relevant information

**Comment by fabiomig** [comment]
Hello @mhartington!

I will do it tomorrow.

**Comment by mandiplimitlines** [comment]
Hello Guys,

I am facing double border issue in ionic app and i am using 

http://drifty.com/
Ionic, v1.0.0-beta.13

Please help if any one solve this problem with this ionic version 

thanks

**Comment by billycomic** [comment]
So, I take it there has been no solution to this issue yet? I'm seeing the same behavior. When I use the following css the items borders are different thicknesses.

.form-container ion-item.item {
    border: none!important;
    border-bottom: 1px solid #cfcfcf!important;
}

Creates This:
![payment-info-1px](https://cloud.githubusercontent.com/assets/13626591/17983726/a8e73ff0-6ad3-11e6-9612-7d9d7ae67c78.png)

.form-container ion-item.item {
    border: none!important;
    border-bottom: 2px solid #cfcfcf!important;
}

Creates This:
![payment-info-2px](https://cloud.githubusercontent.com/assets/13626591/17983741/bcca85d6-6ad3-11e6-85ed-24234d7e8cec.png)

I'm wondering how to handle this as it really isn't usable at this point. I guess I can use <hr> in the form, but that is definitely not optimal.

**Comment by muhammedMoussa** [comment]
```
.item { border-style: none }
```
