### ISSUE TITLE
Textfield doesn't always focus when using overflow-scroll

### ISSUE THREAD

**Issue by raffij** [driftyco/ionic#1797]
Tapping slightly above or below a textfield with ionic scroll off opens keyboard, but doesn't focus on textfield.

http://embed.plnkr.co/BZrnKPlCJt93orQp58H3/preview

**Comment by perrygovier** [comment]
It is only for ios 7, but it is not yet fixed. I'm focusing on this today, but I want to tread lightly because tap/click changes can have wide ranging implications.  A little more info: It's [this line](https://github.com/driftyco/ionic/blob/master/js/utils/tap.js#L351) that's the culprit. I just need to be sure any fix doesn't create new problems.

**Comment by perrygovier** [comment]
Checking in because I have to work on some other things for a week or so. It's more complicated than the line above. It's because tap.js expects a scroll controller for some of it's click optimizations on form elements. This is fixed by adding a native scrollView.js file, which exists in my scrolling WIP branch. The issues isn't fixed there yet, but it's a necessary step to getting there.

**Comment by markusila** [comment]
I've got this problem with my Android. Can i count on You, @perrygovier ?))))

**Comment by mhartington** [comment]
Is this still an issue with 1.0?

**Comment by markusila** [comment]
Yes,  on my Android fields dont focus,  lets say,  every third time.
Please let me know how to fix it)

**Comment by markusila** [comment]
Guys, please, any news?

**Comment by kpfecteau** [comment]
I was having an issue when selecting a text field and having the app scroll to the top and getting stuck.  I found these two lines which were doing the scroll and commented them out (3573-4 ionic.bundle.js) which seems to have fixed my problem.

```javascript
function keyboardBrowserFocusIn(e) {
  if( !e.target || e.target.readOnly || !ionic.tap.isTextInput(e.target) || ionic.tap.isDateInput(e.target) || !keyboardIsWithinScroll(e.target) ) return;

  document.addEventListener('keydown', keyboardOnKeyDown, false);

  // Dont scroll to top on input focus
  //document.body.scrollTop = 0;
  //document.body.querySelector('.scroll-content').scrollTop = 0;

  keyboardActiveElement = e.target;

  keyboardSetShow(e);
}
```

**Comment by markusila** [comment]
Thanks a lot for the response! I think my issue is a bit different. When i
tap the field - keyboard appears,  but as i type -  no letters appear
inside of it. That happens so often,  it majorly happens on password
field,  but on others - sometimes as well.

**Comment by mhartington** [comment]
@markusila could you open a new issues and ping me in it? Closing this for now.
