### ISSUE TITLE
Navigating to pages broken on FirefoxOS

### ISSUE THREAD

**Issue by ath0mas** [driftyco/ionic#1814]
Application (based on ionic-starter-sidemenu for example) can not navigate to other pages than default: error is displayed full screen and app stops.

Devices: Flame (FirefoxOS 1.3), Simulators 1.3 & 1.4

Flame
![ionicoxos](https://cloud.githubusercontent.com/assets/217720/3654228/e6441662-1165-11e4-9664-8bee822bdb2c.png)

Simulator 1.3
![navsim1 3](https://cloud.githubusercontent.com/assets/217720/3654234/03a56d1e-1166-11e4-9963-188b1e07b1ee.png)

Simulator 1.4
![navsim1 4](https://cloud.githubusercontent.com/assets/217720/3654236/113d2318-1166-11e4-85f3-0cd1d7d9756a.png)

**Comment by Ionitron** [comment]
Greetings @ath0mas!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.

**Comment by neoascetic** [comment]
So, will this be added by default?

**Comment by mhartington** [comment]
Probably sometime post 1.0. We're close to wrapping up 1.0 so any features/additions will be revisited after that.
