### ISSUE TITLE
bug: Leaflet initialization problem on tabbed views

### ISSUE THREAD

**Issue by ggalmazor** [driftyco/ionic#1835]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Related to this post in the forum: http://forum.ionicframework.com/t/leaflet-map-and-ion-nav-view/1787/17
Related codepen: http://codepen.io/ggalmazor/pen/HAtwF

When adding a Leaflet map into a tabbed view, Leaflet objects are not correctly initialized and as a result, no eventListeners are registered on the clickable elements of the map.

In the codepen, you can see this happening with the zoom controls, but it is the same with Markers and MarkerClusters.</span>

<span is-issue-template></span>

**Comment by lwestenberg** [comment]
Hey @ggalmazor @perrygovier 
I am facing the same problem. In your codepen above with data-tap-disabled="true" it seems to work, however when you switch between the tabs a few time then it breaks again. Any idea how to fix it?

**Comment by ggalmazor** [comment]
Hi @lwestenberg. Couldn't say... It's ages since I don't work with Ionic. This issue was related to the first beta versions from almost 2! years ago.Maybe @perrygovier can pitch in some wisdom here...

**Comment by lwestenberg** [comment]
@perrygovier would be great if you have some wisdom. I found out that leaflet without directive also has this issue.

**Comment by perrygovier** [comment]
I've found leaflet in particular doesn't work well with Ionic. I'm not sure if it's the same problem you're seeing, but A problem is based around a bug when native browser events fire like `resize`. It seems like leaflet may be built more for traditional static web pages that are loaded on page load and then discarded entirely when you navigate to the next page, instead of single page apps. I haven't found much if anything Ionic can do on its end to remedy the issue. 

At least take solice in knowing that you're not alone and try to pressure leaflet to work better in a single page app environment. 
https://github.com/driftyco/ionic/issues?q=is%3Aissue+leaflet+is%3Aclosed
