### ISSUE TITLE
bug: Collection-repeat item swipe issue

### ISSUE THREAD

**Issue by h4ck3rviv3k** [driftyco/ionic#1842]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In collection-repeat if user swipe on any element then it will reveal some buttons and while these buttons are being shown if user scrolls down then the element at the same position down also get swiped and it keeps repeating as we scroll down.</span>

<span is-issue-template></span>

**Comment by ajoslin** [comment]
Fixed via e90477c10e061fc2b4cc2773e49722748c03dc92

**Comment by ajoslin** [comment]
The fix makes it so when you scroll away from a swiped item, it closes. But it doesn't make the swiped item reopen when you scroll back to it.

This is because it's not possible with collectionRepeat's current implementation to store state on any of the items once they're scrolled away. Eg say, "this item was swiped open".

I could hack it in, but it would be really dirty and really fragile.

I'll wait until collectionRepeat's next iteration to add this functionality.
