### ISSUE TITLE
bug: textarea with focus does not disappear on device when view changes

### ISSUE THREAD

**Issue by zwz** [driftyco/ionic#1857]
I made a very simple example at http://codepen.io/anon/pen/ExsaH
But you have to test it on some device to catch the bug. 
For me, I am using android 4.0.4.

1. click the next button
2. focus on the textarea, and you can also input some text
3. click the prev button

You can see the textarea (the focus border and the text you inputed) remains.

**Comment by Ionitron** [comment]
Greetings @zwz!

I'm sorry, but my sensors indicate that this issue may no longer apply to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen it by creating a new issue and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com). There are many humans there who can offer sage advice.

Thank you for allowing me to assist you.
