### ISSUE TITLE
bug: Data binding problem in select menu

### ISSUE THREAD

**Issue by hailq92** [driftyco/ionic#1869]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The model of select menu does not bind in controller. The model change in the view but when access inside controller it keep the initial value: http://codepen.io/ho_oh/pen/FioIv . In reverse, when changing the model inside the controller, the selected option in the view only changes for the first time. http://codepen.io/ho_oh/pen/DrCvq</span> . 
But after remove the 'ion-content' tag it work well.

<span is-issue-template></span>

**Comment by perrygovier** [comment]
@hailq92 sorry for the delay in replying.  

This isn't a bug really, but part of how Angular handles scope inheritance.  Directives like ionContent create new levels of the scope. The trick is, scope values inherit from each other in the way classes do. So consider the following code
````html
<my-first-directive>
  <my-second-directive>
  </my-second-directive>
</my-first-directive>
````
If `my-first-directive` were to have a controller where i set a value, and I were to output something inside `my-second-directive`, then it would have the right value, because it inherited it from the first directive. Once `my-second-directive` makes changes to that value `my-first-directive`'s original copy of that value will not change.  This is because the second directive's values are a copy of the first directive, not the same thing. 
If you were to move the ng-Controller down a level to be at the level of `ion-content`, then everything would work as expected, unless you add a another directive in between the element that has the controller and the form elements. 

I've expanded on your example, demonstrating the issue. 
http://codepen.io/perrygovier/pen/PweKNL?editors=101
