### ISSUE TITLE
nav bar in modal

### ISSUE THREAD

**Issue by vipulsodha-zz** [driftyco/ionic#1893]
I am trying to implement ion nav bar inside ionic modal ! but it is invisible inside modal ! 
Is it a bug ? or I am doing it wrong?

**Comment by sinedied** [comment]
Any hint on what's the root cause of the issue?
I need this working as I have complex sub-navigation in modals, and I'm willing to propose a PR to fix this. From what I saw each `ion-nav-bar` has its own delegate instance, so the only cause I can think of is wrong DOM selectors for showing/hiding the bars, am I wrong?

**Comment by sinedied** [comment]
Nevermind, I am preparing a PR since I've found the cause for this, I was not that of a great deal to fix but quite challenging to find ^^
