### ISSUE TITLE
support for $locationProvider.html5Mode(true);

### ISSUE THREAD

**Issue by gigablox** [driftyco/ionic#1930]
Without support for `$locationProvider.html5Mode(true);` or `!#` hashbangs it will be impossible for me to get SEO for my web app.

Any work arounds?

**Comment by lucasalmeida92** [comment]
@gigablox 

You will have to create your own web server because 'ionic server' creates a server that don't support modRewrite.

Here what I did:

**1- Web Server for Production ( Nodejs + Express)**

***server.js***

https://gist.github.com/lucasalmeida92/7f67f5183318d44f348b

**2- Web Server for Development ( Nodejs + Gulp + BroswerSync + Connect History Api Fallback)**

***gulpfile.js***

https://gist.github.com/lucasalmeida92/592185d6bfdc5626cf5a

**3- Gulp task for Mobile App build (with gulp-replace package)**

When you put `<base href="/">` inside the head tag in your index.html file, the application will work fine with Html5Mode enabled in a web browser, but in your mobile application you gotta use `<base href=".">` instead.

To automatize this, I created a gulp task with **gulp-replace** node package to do the job for me:

    gulp.task('build:device', ['sass', 'compressJs', 'jade-templates'],function () {
      return gulp.src(paths.jade[1])
      	.pipe(replace('base(href="/")', 'base(href=".")'))
        .pipe(jade())
        .pipe(gulp.dest('./www/'));
    });

So before I run `"ionic build android"` i run `"gulp build:device"` .

**4- Url paths Cautions**

You will have to be careful with url paths.

- **href** urls must start with "/". Ex.: `<a href="/app/list">link</a>`
- **src** urls must start without "/". Ex.: `<img src="img/banner.jpg">`

**Comment by codebymikey** [comment]
FYI, enabling `html5Mode` isn't advised if your app allows you to navigate to external pages outside of index.html. I learnt this the hard way.

After leaving the index.html routed content, once you try going back to it, it ends up falling flat on it's face with a **net:ERR_FILE_NOT_FOUND** error as it tries to load the non-existent file based on the current URL rather via index.html.

**Comment by FabioParigi** [comment]
enabling html5Mode
ERR_FILE_NOT_FOUND
I have change  <base href="/"> to <base href=".">
But the error is the same....
any idea?
Fabio
