### ISSUE TITLE
ionic Scroll broken when form fields are focused in scroll view 

### ISSUE THREAD

**Issue by perqa** [driftyco/ionic#2061]
*Case 1: auto-scroll to programatically focused input field in Chrome web browser for OSX*
I have a scrollview to which I add items dynamically. These items contain input fields. When I add an item, I programatically set focus on the input element. If that element was added below the view, it will automatically scroll to the input field, which is exactly what you want, but that seems to confuse $ionicScrollDelegate. Henceforth, the scrollview container is offset vertically, so that you can't scroll to the top of the list, but you can scroll further down than necessary. If I don't set focus, everything works fine, but I would really like to. 

*Case 2: manually focused input field and virtual keyboard offset in mobile Safari for iOS*
In the mobile, setting focus on an input field will open the virtual keyboard and push the view upwards so that the field is visible, which is fine, but after keyboard dismissal, it remains there. In this case, I found that the height of ion-content is modified by the operation. If I set the height of the ion-content element back to its previous value after keyboard dismissal, everything's fine.

$ionicScrollDelegate.resize(); has no effect on this condition. Using $ionicScrollDelegate.scrollTop(); or $ionicScrollDelegate.scrollBottom(); brings you to the same - incorrect - borders as manual scrolling does.

**Comment by Ionitron** [comment]
Greetings, @perqa!

Due to the age of this issue, and possibility it may have already been fixed or no longer applicable, my sensors indicate that this issue should be closed.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.

**Comment by mohsennayyeri** [comment]
comment two line  in ionic.bundle.js (line 3572)  version 14
document.body.scrollTop = 0;
document.body.querySelector('.scroll-content').scrollTop = 0;

**Comment by mhartington** [comment]
If this is still an issue, please provide a codepen demo for testing on a device

**Comment by johannds** [comment]
I'm still seeing this happen.
