### ISSUE TITLE
bug: Back button incorrectly shown while switching tabs

### ISSUE THREAD

**Issue by salmanm** [driftyco/ionic#2129]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>please see this.

http://forum.ionicframework.com/t/back-button-incorrectly-shown-while-switching-tabs/9041

and this

http://stackoverflow.com/q/25622573/1520671

Looks like I am not the only one that encountered this. :)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @salmanm!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
