### ISSUE TITLE
Vertical scrolling not working on BlackBerry10

### ISSUE THREAD

**Issue by oliversalzburg** [driftyco/ionic#2170]
Occasionally vertical scrolling will no longer work on BlackBerry10. I'm unable to scroll lists or pages in general. Slide to refresh doesn't work either.

However, opening a side navigation menu by sliding horizontally still works.

Restarting the app usually fixes the problem.

**Comment by Ionitron** [comment]
Greetings @oliversalzburg!

I'm sorry, but my sensors indicate that this issue may no longer apply to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen it by creating a new issue and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com). There are many humans there who can offer sage advice.

Thank you for allowing me to assist you.
