### ISSUE TITLE
menu-close combined with ion-nav-view animation creates ugly transition

### ISSUE THREAD

**Issue by oliversalzburg** [driftyco/ionic#2196]
Consider the following setup: 

```html
<ion-side-menus>
	<ion-side-menu side="left">

		<div class="bar bar-header bar-stable">
			<h1 class="title title-left">
				Side Menu
			</h1>
		</div>

		<div class="content has-header">
			<ion-list>
				<ion-item menu-close ng-href="#/home">
					Home
				</ion-item>
				<ion-item menu-close ng-href="#/some-place">
					Some place
				</ion-item>
			</ion-list>
		</div>
	</ion-side-menu>

	<ion-side-menu-content>
		<ion-nav-bar class="nav-title-slide-ios7">
		</ion-nav-bar>
		<ion-nav-view animation="slide-left-right-ios7">
		</ion-nav-view>
	</ion-side-menu-content>

</ion-side-menus>
```

When navigating between the pages, sometimes the page will slide in from the left, sometimes from the right. *Why* that is isn't clear to me.

However, due to `menu-close` the sidebar will close by sliding left. That combined with the content sliding in *from* the left looks really weird.

**Comment by Ionitron** [comment]
Greetings @oliversalzburg!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.

**Comment by gregor-srdic** [comment]
Hi, I believe I am still experiencing some simmilar issues. I have a side menu, that opens from the right side. Clicking on a menu item closes the menu and transits the page to another state. The view transition animation (next page sliding in from the right) starts before the menu close animation finishes, resulting in an unpolished experience :S
video, tested in google chrome with animation slowed down to 0.1x:
https://goo.gl/yJAv2T

**Comment by baltazarqc** [comment]
I still have the same issue as the one descibed by gregor...
