### ISSUE TITLE
Integration of collection-repeat with any custom directive. 

### ISSUE THREAD

**Issue by martingg88** [driftyco/ionic#2197]
what is the better way to integrate collection-repeat with custom directive?

I try to integrate the image directive with collection-repeat. However the image will show flicker a while for scrolling up and down. The issue may be the collection-repeat change the item in viewpoint in turn the relevant item will call the image directive upon changing.

**Comment by Ionitron** [comment]
Greetings, @martingg88!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
