### ISSUE TITLE
ion-nav-back-button not shown on view Clientes

### ISSUE THREAD

**Issue by condepatula** [driftyco/ionic#2202]
![ionic](https://cloud.githubusercontent.com/assets/5973066/4257951/80e09ac8-3aca-11e4-8ca9-5f8aaf8455b0.png)

Hello friends, 
In this case, what would be the navigation rule? 

Thank you!

**Comment by Ionitron** [comment]
Greetings @condepatula!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
