### ISSUE TITLE
No back buttons on navigation between tabs

### ISSUE THREAD

**Issue by sunsus** [driftyco/ionic#2240]
If you are navigation form one one Tab state to an Sub Tab state in an other Tab the back button is not displayed. See
http://forum.ionicframework.com/t/two-states-in-the-same-view-contained-in-a-tab-replace-the-nav-tab-link/9841/10
and
http://forum.ionicframework.com/t/navigation-with-tabs-buggy-in-beta-12/9833

**Comment by jonlil** [comment]
any progress?

**Comment by Ionitron** [comment]
Greetings @sunsus!

I'm sorry, but my sensors indicate that this issue may no longer apply to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen it by creating a new issue and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com). There are many humans there who can offer sage advice.

Thank you for allowing me to assist you.

**Comment by fpoljak** [comment]
I have several tabs, one of them called tab.events. 
I did it the following way:

1.) In the ion-view in template i put: 
<ion-nav-buttons side="primary">
	<button class="button back-button buttons custom-back-btn button-icon button-clear header-item" ng-if="forceBackButton" ng-click="backToParentView()" style=""><i class="icn-back"></i></button>
	</ion-nav-buttons>

2.) in controller:

a) in the child view:

$scope.forceBackButton = $ionicHistory.backView().stateId.indexOf('events') < 0; //we navigated from another tab
			  
			  $scope.backToParentView = function() {
			  $state.go('tab.events', {}, {location: 'repalce', inherit: 'false'});
			  };

b) in the main view:

$ionicNavBarDelegate.showBackButton(false);

$scope.$on('$ionicView.beforeEnter', function() {
		$ionicNavBarDelegate.showBackButton(false);
	});
			   
	$scope.$on('$ionicView.leave', function() {
		$ionicNavBarDelegate.showBackButton(true);
	});
