### ISSUE TITLE
default ion-nav-view css

### ISSUE THREAD

**Issue by josx** [driftyco/ionic#2246]
My app was just working pretty well, until upgrade to alpha.12 (background goes from white to black)

Is there a reason to change default background cololor for ion-nav-view?

Check it on this commit
https://github.com/driftyco/ionic/commit/853fad19b1f5d74f878fd4e25c52f7f23770011c

**Comment by Ionitron** [comment]
Greetings @josx!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.

**Comment by jgomezme** [comment]
The issue is with the RGBA colors, if you use HEX color, all works ok.
