### ISSUE TITLE
Bug: Entire app moves on input focus on iOS 8

### ISSUE THREAD

**Issue by lukechilds** [driftyco/ionic#2256]
When I selected an input in iOS 7 the keyboard would pop up and the input would scroll to be just above the keyboard. In iOS 8 it looks like the entire webview jumps down before animating up and temporarily showing a black bar at the top, it looks pretty awful.

![iOS8 input focus](http://i.imgur.com/QDX0tWQ.gif)

The example uses the ionic tabs starter template with some inputs dropped into the 'Dash' page.

**Comment by ulesta** [comment]
In my case, disabling Keyboard Scroll was not a viable solution since I wanted to scroll on input focus. 

I experimented and figured that if I changed the `ion-content` to an `ion-scroll` the issue would disappear. I took it once step further an applied the attribute `overflow-scroll="true"` to the `ion-content` and voila, issue was fixed.

I noticed that the would be a pain to apply all over the place so I just disabled jsScrolling by default by doing this in my angular config block:
`$ionicConfigProvider.scrolling.jsScrolling(false);`
