### ISSUE TITLE
Bower defaults to wrong version due to faulty semver notation

### ISSUE THREAD

**Issue by gruppjo** [driftyco/ionic#2276]
Hi there, I'm setting up a project and I want to include the latest  ionic beta as a dependency via bower.

    "dependencies": {
        "ionic": "~1.0.0-beta.12"
    }

However this defaults to `v1.0.0-beta.5b` since this tag it's not a proper semver version as far as i know. I guess this is not the intended behaviour. Can you please fix this?

**Comment by Ionitron** [comment]
Greetings @gruppjo!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
