### ISSUE TITLE
bug: Pull To Refresh, use more than on time while spinning

### ISSUE THREAD

**Issue by maleeb** [driftyco/ionic#2299]
Hello,
if you use Pull To Refresh, and use the swipe down gesture again while the spinner is rotating (2 x Pull To Refresh). It will fire 2 times. If you are fast enough you can do it 3-4 times and it will fire 3-4 times.

You can test it in your code here on codepen: http://codepen.io/perrygovier/pen/nqIrC

**Comment by Ionitron** [comment]
Greetings @maleeb!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen it and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
