### ISSUE TITLE
$ionicNavBarDelegate.showBackButton() always returns false

### ISSUE THREAD

**Issue by SpenceDiNicolantonio** [driftyco/ionic#2353]
The `showBackButton()` function in the ionNavBar directive controller returns `!!($scope.hasBackButton && $scope.backButtonShown)`. From what i can see `$scope.hasBackButton` is no longer used, and as such is always undefined. This results in `false` being returned from `$ionicNavBarDelegate.showBackButton()` regardless of actual back button state.

See this CodePen:
http://codepen.io/SpenceDiNicolantonio/pen/zracD

**Comment by Ionitron** [comment]
Greetings @SpenceDiNicolantonio!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
