### ISSUE TITLE
"Unfortanately, app has stopped" for android after 1.2.7 update

### ISSUE THREAD

**Issue by fals** [driftyco/ionic#2356]
I can't run my app on any Android version after the update to 1.2.7. The project builds and installs, but can't lauch the app.

**Comment by jbavari** [comment]
@fals @jeroenverfallie - are you still having these issues with the latest version of the CLI?

**Comment by Ionitron** [comment]
Greetings @fals!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
