### ISSUE TITLE
Proper way to initialize an Ionic project from existing sources

### ISSUE THREAD

**Issue by ebrehault** [driftyco/ionic#2361]
Let's say I have an existing Ionic project in a Git repository.
If I clone this rep and try `ionic start myapp blank`, it will offer to override all the existing folder content or cancel.
If I do not use the `start` command and try `ionic platform add android` from the existing sources, I get:

```
Error: ENOENT, no such file or directory '/__the__path__/plugins/android.json'
```

Is there a correct way to initialize a project from existing sources?

**Comment by gortok** [comment]
It seems like it'd need to be done for every time a new developer is added to an existing ionic project. I'd definitely vote for a command line option that allows a user to pull in an existing project and get started without having to resort to git trickery.

**Comment by lmk123** [comment]
+1

**Comment by jgillard** [comment]
+1

**Comment by fskirschbaum** [comment]
+1

**Comment by xezpeleta** [comment]
+1

**Comment by fskirschbaum** [comment]
I have to say, @drewrygh, I think you're last response before closing this was a touch too cavalier. I suspect this is a far more common issue than you might think. 

I have needed to work around this situation more than once for projects because I have to work between OS X and Windows regularly, I've also had to walk interns and new devs through the process of starting work with existing projects.

For my team the pain point really comes from the fact that we, for reasons that aren't worth arguing about here, use SVN and not Git for version control, which throws your argument more or less out the window since Git cannot be our answer in this case and the corresponding SVN commands 

Regardless, however, it seems like there needs a better way of initializing existing projects using the Ionic CLI. I feel like I should be able to commit my project root with configuration files as well as my www/ and merges/ and then use Ionic's CLI to initialize my project from there... 

As @ebrehault mentioned above, a good workflow could be: 

    $ git clone my_app_repo
    $ cd my_app_repo
    $ ionic start . --no-overwriting

Though in our case we'd use, for example, something like this:

    > svn checkout [URL] my_app/
    > cd my_app/
    > ionic start . --no-overwriting

Perhaps that's introducing too much 'package management' into things, but it really feels like the logical way to handle projects. We should be able to spin up existing Ionic projects as easily as we can start a new one without a lot of copying files, git flags, or anything else!

&lt;/twocents&gt; :smile:

**Comment by jbdemonte** [comment]
+1

**Comment by geekuillaume** [comment]
+1

**Comment by ebrehault** [comment]
As I am the one who initiated this discussion one year ago, I want to mention that now with the **current version of Ionic**, you can create a Ionic project, work on it, put it into a git repo, and then clone it somewhere else and just do:
```
$ ionic platform add android
```
and everything is setup properly and works fine.

So I think this issue is really resolved now.

**Comment by shamil707** [comment]
Still the question got unanswered which everybody wants to know

**Comment by Crare** [comment]
I pulled the remote repository, go into the Ionic-app root-folder and do in bash `npm install` worked for me. After that just did in bash `ionic serve` and it started running like it should.

**Comment by adriandia** [comment]
That works too.  if you still get a blank screen you need to install the bower dependencies `bower install`.  if you don't have bower you need to install it `npm install -g bower`.  The you can `ionic serve` and it should work
