### ISSUE TITLE
Style discrepancy on the back-button

### ISSUE THREAD

**Issue by TimmyCarbone** [driftyco/ionic#2386]
Looks like there is a difference between the opacity when the back-button appears and the usual opacity of the element. 

When ?
Screen A loads B with a slide animation : The back button appears on Screen B with opacity set to 1.
Screen B links to C without animation : The back button stays in place but the opacity changes to 0.8.

opacity 0.8 : 
https://github.com/driftyco/ionic/blob/master/scss/_bar.scss#L209

opacity 1 : 
https://github.com/driftyco/ionic/blob/master/scss/_animations.scss#L783
https://github.com/driftyco/ionic/blob/master/scss/_animations.scss#L854
https://github.com/driftyco/ionic/blob/master/scss/_animations.scss#L922

I'm still learning how to use angularJS and Ionic so I'm surely doing things the wrong way but if we put this on the side, I think the opacity values should be the same anyway.

I didn't present a pull request because I have no idea how you guys would handle it, as lowering the 1 to 0.8 makes it weird to me (state looks unfinished) and increasing the 0.8 to 1 destroys the :activated animation ... also because I'm definetely not a designer :D

**Comment by Ionitron** [comment]
Greetings @TimmyCarbone!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
