### ISSUE TITLE
$ionicScrollDelegate rememberScrollPosition may be wrong

### ISSUE THREAD

**Issue by Belelros** [driftyco/ionic#2387]
So, I was trying to implement a piece of functionality today and I was going to use `rememberScrollPosition` from the `$ionicScrollDelegate` and I think I've discovered an issue here.

So, `rememberScrollPosition` needs an ID which then is used to store the current position under the `$$scrollValueCache`.  That does work fine.

However, if I want to go restore the position with `scrollToRememberedPosition`, then I start to get out of luck. A new scroll delegate is created (apparently) whenever I create a new view that has a scroll container, such `ionScroll` or `ionContent` thus the delegate's ID which is being saved on `rememberScrollPosition` is lost and fallbacks to the `$scope.id` or history's one. 

So, when I try to use `scrollToRememberedPosition` I can't since the ID it's trying to use is not the one it should be. 

If the `$ionicScrollDelegate` should create a new delegate each time the view is created, then the solution may be something like `delegate.setId('foo');` so that could work.

However, if it's not supposed to create a new delegate each time, then you will have to revisit that logic, since something seems to be going on.

Right now I can solve this by using the `$$scrollValueCache`.

**Comment by Ionitron** [comment]
Greetings @Belelros!

I'm sorry, but my sensors indicate that this issue may no longer apply to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen it by creating a new issue and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com). There are many humans there who can offer sage advice.

Thank you for allowing me to assist you.
