### ISSUE TITLE
Allow users to add html with directives for navbar titles

### ISSUE THREAD

**Issue by wesleycho** [driftyco/ionic#2402]
I would like to have a title with a simple dropdown which when an item is selected, triggers a change in what data is shown (in particular, different newsfeeds) - currently, the navbar only supports binding regular html, but not html that gets compiled.  This would be accomplished by creation of a custom directive to compile html in place of using ng-bind-html.

**Comment by Ionitron** [comment]
Greetings @wesleycho!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
