### ISSUE TITLE
collection-repeat with dynamic width items in ion-side-menu-content uses an out of date version of scrollview client width if using expose-aside-when="large"

### ISSUE THREAD

**Issue by hafezash** [driftyco/ionic#2405]
Noticed this when developing a list component that expands to 2 or 3 columns on iPad (dynamic width % for each list item based on $window.innerWidth). When this was in the side menu content, and expose-aside-when="large" was showing the side menu, the item left positions wouldn't be calculated correctly.

Had a dig through the framework code, and found that the 'x' coord of the translate3d being used to position the items was operating on an outdated value. Tracing this up to the widthGetter() function using an outdate scrollView.__clientWidth value (specifically, looks to be the previously cached value before a window resize or orientation change).

Managed to work around the problem with the following code to force the resize() function on the scroll view, but unfortunately it only fixes the issue when running in the iPad emulator, or ionic serve. The issue still occurs when running with an installed app on the device.

        $scope.$on('$ionicExposeAside', function(evt, isAsideExposed) {

			$ionicScrollDelegate.resize();
        });

I'm running a non-standard setup (angular 1.3.0 with ionic 1.0.0-beta.13), so not sure if anyone else is hitting this, but thought I'd share my findings in any case.

**Comment by Ionitron** [comment]
Greetings @hafezash!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen it and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
