### ISSUE TITLE
ionic modal dialog css bottom gets set to 0 on dialog hide even when using a custom custom animation 

### ISSUE THREAD

**Issue by hafezash** [driftyco/ionic#2406]
somewhat conflicts with the custom animation being used, as it causes the dialog to appear to stretch/transition down on hide, irrespective of what animation effect you're actually trying to achieve (only on wide devices). e.g. I had a fadeOut animation to exit, so didn't want any transition/stretch effect

seems to be due to this segment of the css

@media (min-width: 680px) {
 ....
  .modal.ng-leave-active {
    bottom: 0; }
....
}

worked around it by overriding the property in the app css file back to the default 20% for that media

@media (min-width: 680px) {
	.modal.ng-leave-active {
	    /*bottom: 0;*/ 
	    bottom: 20% !important; 
	}
}

**Comment by Ionitron** [comment]
Greetings @hafezash!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen it and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
