### ISSUE TITLE
Scrolling issues when using overflow-scroll="true"

### ISSUE THREAD

**Issue by nokturnal** [driftyco/ionic#2411]
A full thread on the Ionic forum as discussed this issue: http://forum.ionicframework.com/t/bug-overflow-scroll-not-working-in-beta-12-beta13/9514/18

Test projects and suggestions have also been suggested in that thread as well.

As a summary, overflow-scroll="true" on ion-content has stopped working in newer versions of the framework.  The native scrolling will not work with a single finger, but works with two fingers.

@mhartington : Can you chime in with your experience with this issue?

Cheers

**Comment by rahul54784** [comment]
after add this line in config.xml solve problem in ios 
 < preference name="DisallowOverscroll" value="false" />

**Comment by Oregand** [comment]
rahul54784, You're the man.

**Comment by dioxmio** [comment]
is that solved??? I have tried with 1.2.4 and I can see that when I use `overflow-scroll="true"` some nodes get lost whereas if I remove it no nodes are lost (I'm just switching over two screen, super simple scenario). I have tried `v1.2.4-nightly-2998` and whereas it seems to be a bit better the leak is still there. I would like to reduce as much as possible since we developing for mobile.

many thanks,

jose

**Comment by kelvin4incubit** [comment]
still not working, i have been trying to fix this for a long time but still haven't figured it out, why ionic has too much bugs on their code?

**Comment by kelvin4incubit** [comment]
my own problem is on android, i cant be able to overscroll but i can scroll on ios even without this code you reference @rahul54784
