### ISSUE TITLE
bug: Textarea is being resized as the page is scrolled

### ISSUE THREAD

**Issue by pattyok** [driftyco/ionic#2425]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I am using a directive to dynamically size a textarea as you type. When you open the keyboard, the page scrolls up to the textarea. When you scroll with the keyboard open, the read-only clone of the textarea does not match the height of the resized text box so you get some flashing/resizing of the textarea.

http://codepen.io/pattyok/pen/aExmf</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @pattyok!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen it and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
