### ISSUE TITLE
e.preventDefault() doesn't work in ionic.on() callback;

### ISSUE THREAD

**Issue by Qvatra** [driftyco/ionic#2429]
In the code below e.preventDefault(); doesn't prevent navigating of <a href='...'></a> elements:

ionic.on('tap', function(e) {
      e.preventDefault();
}, element);

I expect ionioc.on() to work the same way as Jquery but it doesn't.
Jquery code works well:

element.on("click", "a", function (e) {
            e.preventDefault();
});

Am I missing something? I thought there should be 'options' in ionic.on() but I didn't find any.

**Comment by Ionitron** [comment]
Greetings @Qvatra!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen it and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by shelter** [comment]
Hi, 

I'm using the version: "1.0.0-rc.1", and I still met the same issue, as my code below:

ionic.on('tap', function (ev) {
  ev.preventDefault() // not working
}, document.getElementById('id'));

In addition to way, as below:

<button on-tap="touchMe()" type="button">点我</button>

How to get the Event object and then do 'preventDefaut' as in angularjs 

<button ng-click="touchMe($event)" type="button">点我</button>
 
the I can do it.
