### ISSUE TITLE
Why ion-list creates a large right padding on its items? 

### ISSUE THREAD

**Issue by moroshko** [driftyco/ionic#2430]
See: http://forum.ionicframework.com/t/why-ion-list-creates-a-large-right-padding-on-its-items/11505

**Comment by Ionitron** [comment]
Greetings @moroshko!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen it and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
