### ISSUE TITLE
Side menu closes on input focus

### ISSUE THREAD

**Issue by BrackCurly** [driftyco/ionic#2434]
I have a side menu which contains an input field. When the input field is selected the keyboard opens and then the side menu closes. This happens only if expose-aside-when is set on the side menu.

I've tested this with a galaxy nexus phone (Android 4.4.4) inside the webview as well as Chrome 38.0.2124.102

Here is the link to the example
http://codepen.io/anon/pen/igtsB

**Comment by mhartington** [comment]
Not seeing this in the nightly builds, are you still seeing this @BrackCurly ?

**Comment by Ionitron** [comment]
Greetings @BrackCurly!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by mogusbi** [comment]
I'm having this issue with ionic 1.0.1 and Android 5.1.1 (Nexus 4)

**Comment by mhartington** [comment]
@mogusbi are you seeing this using the example codepen? 
http://codepen.io/anon/pen/igtsB

Or different markup

**Comment by edehlinger** [comment]
Hi,

I'm having the same issue with ionic 1.1.0 and android 4.4.4.

Tried using the code from http://codepen.io/anon/pen/igtsB with ionic 1.1.0, focus on input opens keyboard and closes side-menu. Removing expose-aside-when solves the issue.

**Comment by fifafu** [comment]
Is there a workaround for this? As pointed out by @edehlinger this only seems to happen when "expose-aside-when" is used.

**Comment by Souras** [comment]
Thanks, Solution is fine

**Comment by yjukaku** [comment]
This is still happening. The workaround is obviously not a valid one since the only reason someone would specify `expose-aside-when` is if they needed it.

It looks like the `exposeAsideWhen` directive is listening to 'resize' events:

```javascript
ionic.on('resize', function() {
        if (prevInnerWidth === $window.innerWidth && prevInnerHeight === $window.innerHeight) {
          return;
        }
        prevInnerWidth = $window.innerWidth;
        prevInnerHeight = $window.innerHeight;
        onResize();
      }, $window);

```

The keyboard showing on the screen triggers this event. What I did was add a check to prevent calling `onResize()` if `window.cordova.plugins.Keyboard.isVisible` is true, but it's pretty hacky. It might be the only way to prevent this though.  A cleaner version might be adding a `ignore-keyboard-resizing` option to the `ion-side-menu` directive?
