### ISSUE TITLE
router-ui sticky states with ionic

### ISSUE THREAD

**Issue by bogomips** [driftyco/ionic#2438]
Hi,
I read about "sticky states" but i didn't find examples with ionic.
Everything seems working fine from the debugger (	$stickyStateProvider.enableDebug(true);)
but when i return into a page it reload from beginning.

I use ionic side menu to change routes, please can someone provide a working examples with ionic and side menu ?

thanks

**Comment by Ionitron** [comment]
Greetings @bogomips!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
