### ISSUE TITLE
bug: 500 error when singing into Ionic View on iOS.

### ISSUE THREAD

**Issue by brettof86** [driftyco/ionic#2444]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>When I try to log in on iOS 8 Ionic View I get a 500 error</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @brettof86!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.

**Comment by brettof86** [comment]
You're right it's fixed in the latest version. Thanks. Sent using CloudMagicOn Sun, Jan 25, 2015 at 1:25 AM,  driftyco/ionic <reply@reply.github.com> wrote:            Closed #2444.
