### ISSUE TITLE
[VERY BAD] android live reload removes random files and www/lib folder plus all plugins

### ISSUE THREAD

**Issue by gabrielmuresan** [driftyco/ionic#2446]
i was running live reload on android and using chrome as a second screen for the same app.

first 3 times livereload corrupted my git and "git status" gave me 128 error, now the last time it removed some (random) templates from my project and the whole lib folder plus plugins folder; happened in version 1.2.8

downgrading to 1.2.7 and checking if this happens again

**Comment by Ionitron** [comment]
Greetings, @gabrielmuresan!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.

**Comment by tslater** [comment]
I have noticed that plugins don't work with live reload...is that the same issue? Should I open a new one?

**Comment by jbavari** [comment]
@tslater - what happens with live reload and emulation, it is just running those files off of your ionic serve, not the files on the device. So if you're having issues with native plugins changing, they might not work as intended.

**Comment by tslater** [comment]
I'm not changing plugins...I'm using the same ones. I just keep getting “deviceready has not fired after 5 seconds”--but only when I use live reload. Is there a way to increase the timeout? I've tried looking through the cordova docs and google but no luck.
