### ISSUE TITLE
ion-tabs background

### ISSUE THREAD

**Issue by vitorsgomes** [driftyco/ionic#2448]
When using ion-tabs as shown in the documentation here http://ionicframework.com/docs/api/directive/ionTabs/, the background and icon colors works fine, but when I generate the application and test in my galaxy S3 the color of the background changes to white and the color of the icons change to blue.

**Comment by Ionitron** [comment]
Greetings @vitorsgomes!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
