### ISSUE TITLE
Retain scroll position when using collection-repeat 

### ISSUE THREAD

**Issue by seme1** [driftyco/ionic#2452]
I am using collection-repeat to display a large list of items of variable heights. When clicking on an item, a new page is rendered to display the details of that item. When hitting the back button, the page containing the long list is re-rendered and the old scroll position is not retained. Instead, the user sees the top item in the list.

The expected behaviour is that the user should see the old clicked item which caused the detail view page to appear.

This issue may be related:
https://github.com/driftyco/ionic/issues/719

However, I am using collection-repeat and there is no ion-scroll generated by 'collection-repeat' in the html of the page.

**Comment by Ionitron** [comment]
Greetings @seme1!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
