### ISSUE TITLE
v1.0.0-beta.13: directive 'collectionRepeat' doesn't clear the 'scroll.resize' event handler. Will cause memory leak when re-create the directive

### ISSUE THREAD

**Issue by dreamershl** [driftyco/ionic#2455]
It registered the event handler 'rerenderOnResize'. But when the scope is destroyed, the handler doesn't cleared, should add the following code into the clear block

      if(scrollCtrl.$element)
        scrollCtrl.$element.off('scroll.resize', rerenderOnResize);
       
Original Code:
      
      scrollCtrl.$element.on('scroll.resize', rerenderOnResize);
      ionic.on('resize', rerenderOnResize, window);

      $scope.$on('$destroy', function() {
        collectionRepeatManager.destroy();
        dataSource.destroy();
        ionic.off('resize', rerenderOnResize, window);
      });

**Comment by Ionitron** [comment]
Greetings @dreamershl!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen it and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
