### ISSUE TITLE
v1.0.0-beta.13: $collectionRepeatManager doesn't restore the original scrollView attributes. Cause not be able to create 'collection-repeat' directive dynamically, for example, can't use ng-if on 'collection-repeat' 

### ISSUE THREAD

**Issue by dreamershl** [driftyco/ionic#2456]
In its constructor, it modifies the scrollView.__callback & content width/height functions as the following. When it is destroyed, it should recover those functions. Otherwise, the original scrollView can't work properly.

       this.scrollView.__callback = this.scrollView.__$callback;
       this.scrollView.__callback = angular.bind(this, this.renderScroll);

       this.scrollView.options.getContentHeight = getViewportSize;
       this.scrollView.options.getContentWidth = getViewportSize;

**Comment by Ionitron** [comment]
Greetings @dreamershl!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen it and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
