### ISSUE TITLE
bug: Individual ion-nav-bar not working

### ISSUE THREAD

**Issue by weeman1337** [driftyco/ionic#2458]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The ion-nav-bar documentation sais, that it's possible to set individual ion-nav-bars for ion-views. See "Alternative Usage" here: http://ionicframework.com/docs/api/directive/ionNavBar/

This doesn't seem to be working.

CodePen here:
http://codepen.io/anon/pen/suzly</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @weeman1337!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
