### ISSUE TITLE
bug: Range input do not slide after use of text Input

### ISSUE THREAD

**Issue by caupetit** [driftyco/ionic#2459]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>Native</span>

<span ionic-description>When i use a text input on a template, it breaks slide for all range inputs in the same page. Only tap event seems to be detected.

Before focus on text input, range input works fine.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @caupetit!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by ciokan** [comment]
Problem still exists. Create a form with an input, focus the input and then try to play with the range slider. It won't work.

**Comment by artzstudio** [comment]
This is currently a launch blocking issue for me, reopened here: https://github.com/driftyco/ionic/issues/5346

**Comment by Cycododge** [comment]
My solution to this issue is to blur the problem input when the on-tap and on-drag events are triggered on the range slider.

> function sliderFix(){
> 	//config
> 	var el = document.querySelector('.target-weight input');
> 
> 	//check if target weight is the focused input
> 	if(document.activeElement !== el){ return; }
> 
> 	//if the input does have focus, blur it
> 	el.blur();
> }
