### ISSUE TITLE
bug($ionicViewService): Incorrect determination of current nav state

### ISSUE THREAD

**Issue by wesleycho** [driftyco/ionic#2471]
When using the ionTabs & ionTab directives, the state returned by the $ionicTab controller via the `navNameMatchesState` method [here](https://github.com/driftyco/ionic/blob/master/js/angular/controller/tabController.js#L20-L22) is incorrect when you are using a parent state with `{ views: { 'state-tab': ... } }` and a child without `{ views: { 'state-tab': ... } }`.

Currently one can work around the bug by defining the child state like this:
<pre>
$stateProvider.state('foo.bar', {
  views: {
    '': {
      ...
    },
    'foo-tab': {}
  }
});
</pre>

However, the correct modification in Ionic to address this issue is [here](https://github.com/driftyco/ionic/blob/master/js/angular/service/viewService.js#L337-L342) - this function is only used by the $ionicTab controller and needs to recursively check the state tree until it reaches the state with the tabs.

**Comment by Ionitron** [comment]
Greetings @wesleycho!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen it and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
