### ISSUE TITLE
bug: Third-level state doesn't show

### ISSUE THREAD

**Issue by Froelund** [driftyco/ionic#2472]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am trying to make three-level navigation and i'm structuring it as this:

First level is a sidemenu
Second level is tabs
Third level is tabs.

The "Initial" state of the app is in the third level as such: "home/tab1/tab3", but when I start the app, the view-area is blank. When I navigation, just once, and back the view-area is as designed.

I have made a codepen to demonstrate the bug.

http://codepen.io/Froelund/pen/oiHcK/</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Froelund!

I'm sorry, but my sensors indicate that this issue may no longer apply to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen it and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com). There are many humans there who can offer sage advice.

Thank you for allowing me to assist you.
