### ISSUE TITLE
Destroying a Modal belonging to a directive causes "'TypeError: Cannot read property '__cleanup' of null"

### ISSUE THREAD

**Issue by sloops77** [driftyco/ionic#2477]
In certain circumstances destroying a modal from a directive is causing the above javascript error on the $ionicScroll controller (looks like it's being destroyed twice?). 

This has been reported on the forums and a few people are affected including me. See this original codepen of Bruno Albano: https://codepen.io/brunoalbano/pen/LAwsv/

**Comment by Ionitron** [comment]
Greetings @sloops77!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen it and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
