### ISSUE TITLE
Drop-down list issue

### ISSUE THREAD

**Issue by camtera** [driftyco/ionic#2485]
When multiple drop down selectors are on a page, the wrong list is sometimes shown when tapping the drop down.  

We are using iOS 8 with Ionic beta 13. 

Following the pictures below: User taps 'Hillview' (pic 1), and instead of the expected store listing, the Aisle items appear (pic 2).

This issue was originally reported by another user: http://forum.ionicframework.com/t/ios-8-1-0-drop-down-list-issue/11599

We are unable to duplicate this issue in desktop Chrome or Android -- this is only happening in iOS.   

Pic 1:
![](http://forum.ionicframework.com/uploads/default/6986/9e6270d7146d8396.png)

Pic 2:
![](http://forum.ionicframework.com/uploads/default/6987/ab7df108e5d86f11.png)

**Comment by Ionitron** [comment]
Greetings @camtera!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen it and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
