### ISSUE TITLE
Button size in Nav Bar

### ISSUE THREAD

**Issue by thiagof** [driftyco/ionic#2488]
Currently (beta-13) setting `button-small` has no effect on nav-bar buttons.

    <ion-nav-bar class="bar-positive nav-title-slide-ios7">
      <a class="button-icon button-small icon  ion-more">
      </a>
    </ion-nav-bar>

That would be desirable designing header with multiple buttons

**Comment by Ionitron** [comment]
Greetings @thiagof!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen it and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
