### ISSUE TITLE
ion-nav-view does not fully support controllerAs syntax

### ISSUE THREAD

**Issue by thaiat** [driftyco/ionic#2499]
There are 2 flavours of controllerAs syntax for the ui-router.

This first one works with `ion-nav-view`:
```js
$stateProvider
                .state('login', {
                    url: '/login',
                    templateUrl: 'login.html',
                    controller: 'loginCtrl as vm'
                })
```

but this second one does not work
```js
$stateProvider
                .state('login', {
                    url: '/login',
                    templateUrl: 'login.html',
                    controller: 'loginCtrl',
                    controllerAs: 'vm'   <---- HERE 
                })
```

When switching back to ui-view both syntaxes work.

**Comment by Ionitron** [comment]
Greetings @thaiat!

I'm sorry, but my sensors indicate that this issue may no longer apply to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen it by creating a new issue and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com). There are many humans there who can offer sage advice.

Thank you for allowing me to assist you.

**Comment by thaiat** [comment]
this issue is still happening
here is a repro codepen: http://codepen.io/thaiat/pen/zxPMbL

if you change line 16 to the commented part, it's working
The issue is related to `views` in `state`

**Comment by SiddharthaRRamesh** [comment]
@Ionitron @perrygovier This issue still torments in Ionic RC 3.

**Comment by rffaguiar** [comment]
@Ionitron @perrygovier yep, issue still exists in Ionic 1.3.22

**Comment by henry74** [comment]
+1

**Comment by diegognt** [comment]
+1

**Comment by aldo-roman** [comment]
+1, still experiencing this same problem

**Comment by mhartington** [comment]
This was added in 1.1 via https://github.com/driftyco/ionic/commit/a665d1d2091bde55f7b3bdc765f1e79b5b515e1d
