### ISSUE TITLE
freeze on simulator ios 8

### ISSUE THREAD

**Issue by hone5t** [driftyco/ionic#2513]
Hi i have a problem with ios 8 simulator when i click on the location 
the app get freeze
thank for the awesome work BTW

**Comment by Ionitron** [comment]
Greetings @hone5t!

My sensors indicate that more information is required so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
