### ISSUE TITLE
v1.0.0-beta.13: Tap&Click module doesn't allow click when scrolling & has wrong focus change handling

### ISSUE THREAD

**Issue by dreamershl** [driftyco/ionic#2526]
# Click issue when scrolling 
When it is scrolling, can't click the the input box because of the following check in tapTouchStart()/tapTouchEnd()

          if( tapIgnoreEvent(e) ) return;

The tapIgnoreEvent() will be true when ionic.scroll.isScrolling is true. The issue will be arise when user want to input something after scrolling a list. For example, the long list is with the search input box. UI should always respond to the user input. 

Is it better to give the application choice to decide whether to stop the scrolling immediately or just ignore the click?

# Wrong focus sequence 
Focus handling has 3 related functions tapClick(),tapFocusIn(),tapFocusOut(). 

The issue here is tapClick() will call "tapHandleFocus(ele);" after the simulated click event "triggerMouseEvent('click', ele, c.x, c.y);" . 

If my understanding is right, it means the click event will be triggered before the focus/blur event. This is wrong. And in "tapHandleFocus(ele);", 

when it finds the current active element is not the same element as the "ele". it has one "tapFocusOutActive()" case. This "tapFocusOutActive" will just move the focus out of the current active element without checking. The issue here is when "button" is clicked, it will forcibly move out the current active element focus because "isContentEditable" of button is false! 

Because of the above issues, the focus switch in click event can't work properly as the following, move the focus to the password input box when click the button login through the "focus-on" plugin http://stackoverflow.com/questions/14833326/how-to-set-focus-in-angularjs 

![image](https://cloud.githubusercontent.com/assets/1271739/4986804/9c233cce-6940-11e4-964f-ccdb3daab128.png)

**Comment by Ionitron** [comment]
Greetings @dreamershl!

I'm sorry, but my sensors indicate that this issue may no longer apply to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen it by creating a new issue and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com). There are many humans there who can offer sage advice.

Thank you for allowing me to assist you.
