### ISSUE TITLE
Nav history manipulation

### ISSUE THREAD

**Issue by AMar4enko** [driftyco/ionic#2531]
Consider example:

```
App is in background and user received push notification about instant message.
It can tap on it and app would be opened at the dialog view.
But in this case he wouldnt be able to navigate back as view hierarchy supposed to.
I.e. from dialog view it can't get back to dialogs list.
```

Is it possible to manually add neccessary states into history to handle this situation?
It's mostly the one unclear behavior of ionic framework for me.
I noticed $ionicViewService, but can't figure out how use it properly to solve this.

**Comment by stevenmyhre** [comment]
I ended up solving this by forcing going to the parent state first, in order to maintain the history and make everything work.  i.e. in your situation:

```
$state.go('im.dialogs').then(function() {
    $state.go('im.dialogs.view', {dialogId: pushMsg.payload.dialogId})
});
```

Seems like there should still be a way to setup your states such that one is always a parent of the other, and ionic force ads a history crumb when you "deep navigate"

It's unfortunate because this, as you stated @AlexYankee, is a large use case for receiving push notifications while the app isn't running... take me directly to the page I want to see!

**Comment by petervojtek** [comment]
it is also possible to use $location instead of $state this way:
```
          $location.path('/main')
          $timeout(function(){
            $location.path('/post/' + postID);
          }, 0);
```

**Comment by rogeriotakejame** [comment]
@stevenmyhre, I tried your workaround ($state.go(...).then(function(){$state.go(...)});) but $ionicHistory ignored the first state. Calling $ionicHistory.viewHistory() will return in histories object only im.dialogs.view. The state im.dialogs doesn't exist even in views object.

**Comment by all43** [comment]
@rogeriotakejame it's too late but..
$timeout(function() {
   $state.go('parent.state.name',$stateParams);
}, 100);
$state.go('final.state.name');
}
But there is another problem - if parent state loading data, or requesting permission, it's hard to avoid it.
Requested $ionicHistory.pushState('state.name'); still actual, especially if app uses deeplinks or push notifications. Thousands of developers still using ionic 1, and routing/history problems is weakest side of v1 :-(
