### ISSUE TITLE
suggest renaming ionSideMenuContent element directive 

### ISSUE THREAD

**Issue by abcd-ca** [driftyco/ionic#2551]
`<ion-side-menu-content>` is nested inside `<ion-side-menus>`. Functionally this is logical (especially since the docs are helpful in explaining it) because `<ion-side-menu-content>` is paired with a sibling `<ion-side-menu>` element. In my opinion coming from someone who has just finished going through the guide on building the ToDo app, the naming of `ionSideMenuContent` is confusing because it implies that it would contain the content of a side menu when in fact it does not – it contains the content for the *foreground* container which can be slid to the side to reveal the side menu. I propose renaming `ionSideMenuContent` to `ionForegroundContent`.

**Comment by Ionitron** [comment]
Greetings @abcd-ca!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
