### ISSUE TITLE
bug: Tabs-icon-top label is left-aligned on Rarz

### ISSUE THREAD

**Issue by creativemobil** [driftyco/ionic#2565]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.1</span>  <span ionic-webview>webview</span>

<span ionic-description>I have similar issue like this: 
http://forum.ionicframework.com/t/tabs-icon-top-label-is-left-aligned-after-tap/9766
but whithout tap event. 
Versions that I´m using:
- Motorola Razr XT890
- Android 4.1.2
- Cordova 3.6.3
- Ionic 1.0.0-beta.13

Screenshots:
http://www.creativemobil.com/alerta-concurso-app/Screenshot_2014-11-13-12-49-15.png

http://www.creativemobil.com/alerta-concurso-app/Screenshot_2014-11-13-12-49-38.png

Is there a solution???

Thanks</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @creativemobil!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>
