### ISSUE TITLE
ion-tab: being able to pass parameter through ui-sref

### ISSUE THREAD

**Issue by QuentinFchx** [driftyco/ionic#2575]
I try to display some tabs
```html
<ion-tabs>
    <ion-tab ui-sref="home.state1({param1: 'current'})">
        <ion-nav-view name="view1"></ion-nav-view>
    </ion-tab>
    <ion-tab ui-sref="home.state2">
        <ion-nav-view name="view2"></ion-nav-view>
    </ion-tab>
</ion-tabs>
```
with this router
```coffee
$stateProvider
.state 'home',
    url: ''
    abstract: true
    templateUrl: 'templates/home.html'
.state 'home.state1',
    url: '/state1/{param1:\\w+}'
    views:
        view1:
            templateUrl: 'templates/view1.html'
            controller: 'View1Ctrl'
```
But it seems that `ui-sref` is not evaluated with its parameters
It pass `home.state1({param1: 'current'})`  to `$state.href` (from ui-router), instead of `home.state1`, and thus does not find a matching state.

Am I missing something ?

**Comment by QuentinFchx** [comment]
@drewrygh Can we discuss how to fix this ?
`ui-sref` is not parsed when passed to `ion-tab`.

**Comment by Ionitron** [comment]
Greetings @QuentinFchx!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
