### ISSUE TITLE
target attr in ion-item for html5mode

### ISSUE THREAD

**Issue by abdurrachman-habibi** [driftyco/ionic#2582]
I think it would be good if target attr can be made optional. I can't navigate properly when I use html5Mode

**Comment by Ionitron** [comment]
Greetings, @abdurrachman-habibi!

Due to the age of this issue, and possibility it may have already been fixed or no longer applicable, my sensors indicate that this issue should be closed.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
