### ISSUE TITLE
bug: tabs always on top on android (nightly)

### ISSUE THREAD

**Issue by GNSPS** [driftyco/ionic#2584]
Can't post a codepen with the problem as it is device specific but **on the nightly release the tabs always stay on top on android**.

Already tried exactly the same code but with ionic's beta 13 and tabs are on the bottom of the screen, no problem detected.

**Comment by zoucaitou** [comment]
thanks

**Comment by hazourano** [comment]
angular
  .module('Whatsapp')
  .config(config);
 
function config($stateProvider, $urlRouterProvider,$ionicConfigProvider) {
  $stateProvider
    .state('tab', {
      url: '/tab',
      abstract: true,
      templateUrl: 'client/templates/tabs.ng.html'
    })
    .state('tab.chats', {
      url: '/chats',
      views: {
        'tab-chats': {
          templateUrl: 'client/templates/chats.ng.html',
          controller: 'ChatsCtrl'
        }
      }
    })
   .state('tab.chat-detail', {
      url: '/chats/:chatId',
      views: {
        'tab-chats': {
          templateUrl: 'client/templates/chat-detail.ng.html',
          controller: 'ChatDetailCtrl'
        }
      }
    });
 
  $urlRouterProvider.otherwise('tab/chats');
  $ionicConfigProvider.tabs.position('bottom');
}


it worked in browser but with android 5.0 tabs still on top. this happened in the android app itself and also when viewing in mobile chome

**Comment by cesar-oyarzun-m** [comment]
@shfaizanali what if I want to have in one screen tabs top and in other screen tab in bottom? Do I just need to call this dynamically
