### ISSUE TITLE
ion-slide-box height goes to 0px

### ISSUE THREAD

**Issue by naavis** [driftyco/ionic#2592]
I had a working slide-box with beta-13, but I got the latest nightly to test out the improved performance. With beta-13 I could set the slide-box width to be some percentage of the screen and the images showed just fine. The nightly build broke the slide-box. Now the slide-box apparently tries to fill the parent container. I added a `div` element around the `ion-slide-box` to act as a parent.
I have the following HTML:

```
<ion-content class="padding">
    <div class="slide-container" ng-if="data.imageURLs">
        <ion-slide-box>
            <ion-slide ng-repeat="imageURL in data.imageURLs">
                <img ng-src="{{ imageURL }}">
            </ion-slide>
        </ion-slide-box>
    </div>
    <p>Text here</p>
</ion-content>
```

The CSS is now as follows:

```
.slide-container {
    position: relative;
}
```

With this CSS the `ion-slide-box` height goes to 0px regardless of the `img` height. The only way I could get the images to show was to explicitely set the `.slide-container` size to some fixed number of pixels. However, the size of the images vary and I want to specify a size relative to the screen size and retain the image aspect ratio. I also don't want to resize the images to larger than 100%.

**Comment by tiaanroelofswart** [comment]
Hi!

Ok I had a look at the two bug reports about this issue and my slidebox goes to 0px as well.

However it only seems to do it once a modal is launched...

For instance on a iPhone the slidebox has an inline width of 1125px:

`<div class="slider-slides" ng-transclude="" style="width: 1125px;"></div>`

and once a mobal is launced is changes to:

`<div class="slider-slides" ng-transclude="" style="width: 0px;"></div>`

the action that changed the element came from `ionic.bundle.js` but I can't see exactly what it did.

I tried setting a fixed width for both `.slider` and `.slider-slide` but that didn't work and setting a fixed with for `.slider-slides` just messes up the slider and makes it display all the slides at once.

The modal I use is the Cool select modal ( http://codepen.io/mhartington/pen/CImqy )(awesome modal btw :dancer:) and I tried forking it and updating it with a slider ( http://codepen.io/anon/pen/jEzqPY ) but that is not giving me the same result as I am seeing?

I guess that it might also have something to do that I have a slide-out menu and different states/pages... The page that the modal is on is affecting other "states"?

Any help would greatly be appreciated :smile:

**Comment by djabif** [comment]
adding cache-view="false" to my ion-view solved this issue

**Comment by severedsea** [comment]
@tiaanroelofswart I'm experiencing the same thing. When I move to another state and open a modal, my state that has the slidebox sets the .slide-slides to 
`<div class="slider-slides" ng-transclude="" style="width: 0px;"></div>`

@djabif I have problems with how my dynamically populated slidebox is displaying when I set cache-view to false. Some times they stack on top of each other. I notice this issue when I was using beta-11. But with cache-view set to true, it shows properly other than when you open a modal in a different state.

**Comment by severedsea** [comment]
Actually, I think this is already fixed. https://github.com/driftyco/ionic/issues/2978

**Comment by maqjav** [comment]
I'm trying with the last ionic version (1.3.0) and I'm finding the same error:
Example: http://plnkr.co/edit/IArABuwbiNwlMT0JJXhm?p=preview

As soon as you change the slide the height goes 0px so you can't see the content.

**Comment by almothafar** [comment]
@maqjav I have same issue with ionic 1.3.2 as well

**Comment by F1LT3R** [comment]
I also have this issue with Ionic 1.3.2

**Comment by hix41** [comment]
I also have same issue with ionic 2.1.17
