### ISSUE TITLE
bug: popups / keyboard problem w/ disableScroll

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#2594]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>When a popup is opened while disableScroll is configured, the popup will not properly move up to accomodate the keyboard.

If disableScroll is false, the popup will properly detect the keyboard and move into view.

Using the Ionic CLI, make an app from this Codepen.  Then, run it on a device.  Strangely, the keyboard does not open on the simulator:

http://codepen.io/calendee/pen/emNOqb?editors=101</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @calendee!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
