### ISSUE TITLE
Non tabs pages to tabs pages does not does not have animation 

### ISSUE THREAD

**Issue by SiddharthaRRamesh** [driftyco/ionic#2613]
Have a look at this codepen : http://codepen.io/ionic/pen/CbBsA

Navigating to tabs page, does not have slide animation on view change.

**Comment by drewrygh** [comment]
Hey @SiddharthaRRamesh - sorry about the delay, I'd check out [this demo](http://codepen.io/ionic/pen/odqCz) to get an idea on how navigation works, and how it can be integrated with tabs.

**Comment by SiddharthaRRamesh** [comment]
I know that. Please check out my question again.

**Comment by pulakb** [comment]
@SiddharthaRRamesh i was going through https://github.com/driftyco/ionic/issues/2725 and found that @mpostma solution is working. Are you looking for some better solution?

**Comment by pulakb** [comment]
@SiddharthaRRamesh Also I have tried the following and it's working:

<ion-nav-view nav-transition="slide-left"></ion-nav-view>

**Comment by pulakb** [comment]
'<ion-nav-view nav-transition="slide-left"></ion-nav-view>'

**Comment by pulakb** [comment]
`<ion-nav-view nav-transition="slide-left"></ion-nav-view>`

**Comment by michahell** [comment]
I am running into the same issue, and the navigation sample does not solve that issue since it does not seem to animate when going from one tabbed page to another. I think that is what @SiddharthaRRamesh is looking for, and so am I. Is there any way to do this currently?

In [this thread](http://forum.ionicframework.com/t/tabs-animations/3884/16), @mhartington speaks of 'a new animation system'. Can I maybe find documentation about that new system anywhere yet?

I would say that [this issue](http://forum.ionicframework.com/t/setting-the-transition-direction-animation/541) is related to this as well, as going from a non-tabbed page to a tabbed section shows no animation and there is no default way to add that, or is there?
