### ISSUE TITLE
Improve the "activated" class delay

### ISSUE THREAD

**Issue by arcanis** [driftyco/ionic#2618]
[Related forum discussion](http://forum.ionicframework.com/t/unresponsive-laggy-ui-on-android-and-on-linux-compared-to-the-ionic-docs/8977)

The Ionic activator sets a [delay](https://github.com/driftyco/ionic/blob/5d6a33c1db978d7318456405f83181a906f05b6c/js/utils/activator.js#L48) before adding / removing the "activated" class. It induces a feeling of lag, since when fast-touching a button, its classes won't change and the user won't have any visual feedback (despite the ng-click actions being actually triggered).

I'm not sure why this delay is used, but at the very least I think it should be configurable in the service provider.

*(For what it worth, it seems to work well by using a 0-delay timeout, except that the class is also added when the element is touch during a scroll event .. maybe a cleaner solution would be to hook upon the ng-click directive ?)*

**Comment by Ionitron** [comment]
Greetings @arcanis!

I'm sorry, but my sensors indicate that this issue may no longer apply to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen it and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com). There are many humans there who can offer sage advice.

Thank you for allowing me to assist you.
