### ISSUE TITLE
bug: Setting css height on <input type="text">

### ISSUE THREAD

**Issue by anri-asaturov** [driftyco/ionic#2620]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>6,7,8</span>  <span ionic-webview>webview</span>

<span ionic-description>When i set the height of text input with css(i need big input), this input becomes uneditable in iOS6,7,8. It gets focus but typing does not produce any result. Removing height setting from it in safari dev tools - immediately fixes it.</span>

<span is-issue-template></span>

Little demonstration:
![demo](https://cloud.githubusercontent.com/assets/1479005/5221201/ea1c147a-767c-11e4-82c6-8244d12064b8.gif)

**Comment by Ionitron** [comment]
Greetings @anri-asaturov!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
