### ISSUE TITLE
ionic modal CSS issue, title overlapping status bar on keyboard open

### ISSUE THREAD

**Issue by islahul** [driftyco/ionic#2624]
Device: iPhone 5s, OS: 8.1.1
This happens when the default keyboard opens on a password field
![img_0835](https://cloud.githubusercontent.com/assets/4123296/5214356/fcdb95c2-7640-11e4-8eba-9f98cdea3817.PNG)

**Comment by Ionitron** [comment]
Greetings @islahul!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
