### ISSUE TITLE
Autocomplete dropdown list selection when key board is open 

### ISSUE THREAD

**Issue by SiddharthaRRamesh** [driftyco/ionic#2626]
Once the input field is focused a dropdown list appears. Once the user selects or tapsOne of the list item in the , it wont get selected because the keyboard closes first and hence the dropdown also vanishes. But my input field is not populated. But if i long press any of the list items it Is selected and my input field is populated

**Comment by Ionitron** [comment]
Greetings @SiddharthaRRamesh!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by Ionitron** [comment]
Greetings @SiddharthaRRamesh!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
