### ISSUE TITLE
Anchor tag with button style causes text to be to high

### ISSUE THREAD

**Issue by sean-hill** [driftyco/ionic#2649]
The images below show it all.
![screen shot 2014-12-01 at 10 54 22 am](https://cloud.githubusercontent.com/assets/1205866/5250386/9dc0f720-7948-11e4-8480-1a9fa12bc911.png)
![screen shot 2014-12-01 at 10 54 34 am](https://cloud.githubusercontent.com/assets/1205866/5250387/9dc2db12-7948-11e4-9dee-088947f5ca73.png)

**Comment by Ionitron** [comment]
Greetings @sean-hill!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
