### ISSUE TITLE
ng-modal in ionic Modal view binding breaks when input changes

### ISSUE THREAD

**Issue by flavordaaave** [driftyco/ionic#2711]
See this codepen example:
http://codepen.io/flavordaaave/pen/pvyaZg

- Open the Modal (click on the edit button in the header)
- the 3 inputs are each binded to a string in the scope
- When clicking on "create", the strings are set to an empty string.

This works only as long as the input is not changed. As soon as you change the input (e.g. the first input field) and then click on the "create" button, only the untouched input fields are cleared.

NOTE: As soon an object is used like
newUser{
    firstName: '',
    lastName: '',
    email: ''
}
Everything is working fine.

**Comment by renanmzmendes** [comment]
@PureSpider setting the scope property of `$ionicModal` to the same scope as the parent shouldn't eliminate issues like these?

**Comment by PureSpider** [comment]
My link was an explanation as to why things started working once he switched to using an object.
But yes, setting the scope property is there for exactly that issue, as long as prototypical inheritance is not a problem, as shown in the link :+1:

**Comment by Ionitron** [comment]
Greetings @flavordaaave!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
