### ISSUE TITLE
bug: track by $index breaks options button in ion-list

### ISSUE THREAD

**Issue by gregorypratt** [driftyco/ionic#2722]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I added `track by $index` to an ng-repeat on an ion-item directive.

I then added an options button of "Delete" that when clicked should remove the item from the list. That works however the next item in the list then has it's options buttons visible.

Please see the following CodePen.

http://codepen.io/gregorypratt/pen/LENBJo

Slide the item to reveal the Delete button, press it and you'll see the problem. Remove "track by $index" from the repeater and you'll see the desired behaviour.</span>

<span is-issue-template></span>

**Comment by ds8k** [comment]
Experiencing the same issue. No fix yet?

**Comment by pcheek** [comment]
+1

**Comment by casoninabox** [comment]
+1

**Comment by Ionitron** [comment]
Greetings @gregorypratt!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
