### ISSUE TITLE
Slidebox distorts after opening a modal in a separate tab

### ISSUE THREAD

**Issue by SiddharthaRRamesh** [driftyco/ionic#2756]
Type : Bug

Use Case: 
<ul>
  <li>Open the codepen link : http://codepen.io/anon/pen/JoKNZJ </li>
  <li>Go to the second tab. i,e the "About" tab </li>
  <li>Click on "geolocatio"n button </li>
  <li>Modal opens and map appears </li>
 <li>Now go back to the "home" tab</li>
<li>You will see that the slidebox is distorted</li>
</ul>

**Comment by Ionitron** [comment]
Greetings, @SiddharthaRRamesh!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
