### ISSUE TITLE
bug: Popup open with keyboard open no keyboard-open cla

### ISSUE THREAD

**Issue by pattyok** [driftyco/ionic#2763]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a popup with and input in it. On opening the popup I have a focus set on the input box so that the keyboard is open. The popup box is covered by the keyboard. 
I had previously solved this by tapping into the keyboard-open class. It appears that that class is no longer set on the body if the input is in a popup. I am fairly certain that it used to get set as I have a style set up for it...</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @pattyok!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
