### ISSUE TITLE
Nav-direction w/ ion-items

### ISSUE THREAD

**Issue by arcanis** [driftyco/ionic#2775]
The following [codepen](http://codepen.io/arcanis/pen/yyJqea?editors=101) does not trigger animation when clicking on the ion-item element, despite having a `nav-direction` directive. This directive has the indented effect when clicking on the 'test' link (despite targeting the exact same route).

**Comment by AbraaoAlves** [comment]
Here [codeped-fixed](http://codepen.io/AbraaoAlves/pen/vExwdO)

**Comment by Ionitron** [comment]
Greetings @arcanis!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
