### ISSUE TITLE
bug: modal.hidden when scope is destroyed

### ISSUE THREAD

**Issue by sean-hill** [driftyco/ionic#2777]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When `$scope.$on('$destroy')` is fired, it also calls `$scope.$on('modal.hidden')` even if my modal is not displayed. This is unexpected functionality.</span>

<span is-issue-template></span>

**Comment by alvaromb** [comment]
Same here. Do you need an example project or something?

**Comment by alvaromb** [comment]
Well, the thing in my case is that every time I put a modal I have this piece of code in my controller:

    $scope.$on('$destroy', function() {
        $scope.modal.remove();
    });

And ``$scope.modal.remove();`` always calls to the ``'modal.hidden'`` event. Not sure if it's a bug or a feature.

**Comment by alvaromb** [comment]
Well, the thing is that ``modal.hidden`` is called when the modal is removed. Here's the source code for the remove event:

```js
remove: function() {
  var self = this;
  self.scope.$parent && self.scope.$parent.$broadcast(self.viewType + '.removed', self);

  return self.hide().then(function() {
    self.scope.$destroy();
    self.$el.remove();
  });
},
```

This is a bit annoying when you trigger some action after the modal has been removed because if you navigate to another view the destroy ``modal.hidden`` will be triggered and there is no way to differentiate if it has been called through remove or only hidden event.

**Comment by Ionitron** [comment]
Greetings @sean-hill!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
