### ISSUE TITLE
expose-aside-when not working for ion-side-menu="right" (nightly build)

### ISSUE THREAD

**Issue by EduceHealth** [driftyco/ionic#2784]
Demo code here: https://codepen.io/Grokling/pen/WbxYxv

Swipe to the right to reveal the left menu.
Swipe to the left to reveal the right menu.
(On desktop click and drag  left or right)

Now, resize your browser either side of 1182px - both sidebars should appear and disappear. Only the left one actually does.

Also, notice that when the left sidebar is exposed due to expose-aside-when, it is not possible to manually expose the right sidebar.

**Comment by Ionitron** [comment]
Greetings @EduceHealth!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
