### ISSUE TITLE
ionic-beta14 tabs style issue

### ISSUE THREAD

**Issue by php-engineer** [driftyco/ionic#2785]
I have the following issue after the update from beta13 to beta14. It only occurs on my Samsung Galaxy Tab 4 (SM-T335) with android 4.4.2. On my Samsung Galaxy S3 and also in the web browser it looks fine. See the screenshot below:

![image](https://cloud.githubusercontent.com/assets/5982785/5515844/f490eb0c-887d-11e4-839c-510e8a7c27cd.png)

**Comment by php-engineer** [comment]
I will come back to you soon. Currently I have a lot of other things to do but I don't forget to answer the ticket.

**Comment by Ionitron** [comment]
Greetings @php-engineer!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you for allowing me to assist you.
