### ISSUE TITLE
Unchecking a required <ion-checkbox> does not make the form $invalid

### ISSUE THREAD

**Issue by imgx64** [driftyco/ionic#2786]
Plunkr: http://plnkr.co/edit/NZAg38SAjgSQzbRTl9WY?p=preview

I'm using [Angular form validation](https://docs.angularjs.org/guide/forms). An unchecked `<ion-checkbox>` with `required` attribute correctly makes the form `$invalid`. However, if I **check it then uncheck it**, the form does not become `$invalid` again.

This problem does not happen with a plain `<input type="checkbox">`, as demonstrated in the plunkr.

**Comment by Ionitron** [comment]
Greetings @imgx64!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by zhouhao27** [comment]
I got the same problem. What should I do?

**Comment by badpenguin** [comment]
+1

**Comment by hiagodotme** [comment]
I got the same problem =/
