### ISSUE TITLE
"ion-nav-back-button" most left even than "ion-nav-buttons side='left'"

### ISSUE THREAD

**Issue by chezih** [driftyco/ionic#2794]
First of all, this is awesome framework.
Thank you!

This is my "ion-nav-bar":
```
<ion-nav-bar class="bar-positive">
 <ion-nav-buttons side="left">
        <button class="button button-icon button-clear ion-navicon" ng-click="toggleLeft()"></button>
 </ion-nav-buttons>

  <ion-nav-back-button class="button-icon ion-arrow-left-c">
  </ion-nav-back-button>
</ion-nav-bar>
```
My problem is:
The "back" button is the most left (left than "ion-navicon" button)
I look at few native apps and the navicon is always the most left.

How can I switch the navicon position (to the most left)?

Thank you!

**Comment by Ionitron** [comment]
Greetings @chezih!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
