### ISSUE TITLE
Ability to force back button visibility

### ISSUE THREAD

**Issue by AlexYankee** [driftyco/ionic#2811]
In documentation we have an example implementing custom back button behavior via ngClick.
But while we can customize bb click behavior we can't manage it's visibility.
Issue related to #2531. 
Since beta 14 is released i have ability to control history stack and transition direction via $ionicHistory and $ionicViewSwitcher.
When app opened on state items.view, which involves some history stack behind (items <- items.view(id)) i can mimic back button functionality using 
```
$ionicViewSwitcher.nextDirection('back');  
$ionicHistory.nextViewOptions({historyRoot: true});
$state.go('items');
```
Everything is almost great, but while no history stack actually present, back button stays hidden, even if i call $ionicNavBarDelegate.showBackButton(true);
I've found workaround by directly patching $ionicNavBar controller instances, but i feel it can be useful to have ability to force back button visibility.

**Comment by AlexYankee** [comment]
@mhartington because ion-nav-back-button has it's own unique style and transitions.
I started with ion-nav-buttons, but when i found what they looks very different to ion-nav-back-button i switched to ion-nav-back-button.
I'll provide example codepen as soon as possible.

**Comment by mhartington** [comment]
Well the style is just an icon, and the transitions can be controlled with the new [`nav-direction`](http://ionicframework.com/docs/api/directive/navDirection/) attribute.

http://codepen.io/mhartington/pen/yyVoOX

**Comment by TimothyKrell** [comment]
@mhartington For me, I desire to customize `<ion-nav-back-button>` because I want the ability to dynamically display the previous title and control when the back button appears. Sometimes, I programmatically navigate to a state that *should* have a back view but doesn't yet because it didn't start from that back view and drill down.

I know I can add a manual back button to each view, but I'd rather automate it to go automatically to it's parent state if a back view isn't present. Also, I want to keep all the nice back title transitions that come with the `<ion-nav-back-button>`.

I'm trying to implement my own custom back button currently, but I'm lacking some apis necessary to make it work the way I want. I tried this on a previous beta:
http://forum.ionicframework.com/t/custom-back-button-to-navigate-up-a-state-tree/10720

I hope this makes some kind of sense! I'm having trouble laying out my goal clearly.

**Comment by TimothyKrell** [comment]
To sum up, I want to be able to:

* Change what the back button does with my own click handler :heavy_check_mark: 
* Change what direction the next transition will be :heavy_check_mark: 
    * Thanks so much for adding this! :+1: 
* Change the logic for whether the back button is displayed or not :x:

**Comment by mhartington** [comment]
Again it comes down to browser history. While we can change the direction of the transitions (left or right), we can't create browser history from nothing, which is what the  ionBackButton is tied to. 

If you are programmatically changing view, you can pass parameters in which could help you automate the process of showing an ion-nav-button. 

Closing this.

**Comment by TimothyKrell** [comment]
@mhartington Thanks for looking at this! I really appreciate all the work you all put into Ionic. It's an amazing framework. 

I was just curious, if I wanted to get the same kind of title-to-back-button animation in the nav bar, could I do that with an ion-nav-button somehow?

**Comment by mohamed-ahmed** [comment]
@TimothyKrell, I'm having the same issue. Were you able to solve this?

**Comment by TimothyKrell** [comment]
@mohamed-ahmed I don't think I did. It's been almost a year since I messed around with this. My hackings led me to this solution I think: https://forum.ionicframework.com/t/custom-back-button-to-navigate-up-a-state-tree/10720/5

The last example was what I ended up settling on. I've been out of Ionic for a while so all of that may be broken now! Good luck! :+1:
