### ISSUE TITLE
v1.0.0-beta.14: class “hide” to ion-nav-bar if there’s more than one

### ISSUE THREAD

**Issue by xAlien95** [driftyco/ionic#2816]
Hi, in Ionic 1.0.0-beta.14, if you have more than a `ion-nav-bar` for state, only one of them will be displayed. The others'll receive the `hide` class.

http://codepen.io/xAlien95/embed/XJKLLY/3

Thank you.

**Comment by Ionitron** [comment]
Greetings @xAlien95!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
