### ISSUE TITLE
Routing page, controller destroy bug

### ISSUE THREAD

**Issue by derozgurg** [driftyco/ionic#2832]
Controller isn't destroyed which belongs to template view. On older version of ionic when a view is changed it's controller should be automatically destroyed and if you reenter into that view, his controller should be automatically reinitialized. But on the new version of ionic this mechanism doesn't work correctly(stage.go(""")),  it works only after "back" triggered.

**Comment by PipStyles** [comment]
Just been having a problem with with exactly this, I think: http://youtu.be/mOh-Y2my-cQ
$ionicView.enter will help for now, but having a controller forward to another without bothering with a view at all is a pretty standard MVC pattern and this kinda breaks it.

**Comment by derozgurg** [comment]
@mhartington i tried that method it is useful but the problem is when i navigate with "back" function (back tabbing android)  it always destroyed the controller which belongs to leaving view and it is always reinitialized as reentering, i can't decide when it will be destroyed because it is only destroyed with "back" not as navigating with "$state.go(state_name)"

**Comment by mhartington** [comment]
That is because of the forward view caching. 

http://ionicframework.com/docs/api/provider/$ionicConfigProvider/#views.forwardCache

So views that are considered forward view are not cached by default. So their controller is destroyed and reinitialized.

**Comment by Ionitron** [comment]
Greetings @derozgurg!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>
