### ISSUE TITLE
Android Hardware back button does not work after modal and only if "focusFirstInput: true"

### ISSUE THREAD

**Issue by apavillet** [driftyco/ionic#2834]
Title said it all :)

After showing a popup, the input is focused and things are fine.
But when I close, the popup ( whatever the way : button or hardware button ), go to another page I cannot use the hardware button ( back button in header works fine ) to go back.

Meanwhile, adblogcat is reporting this while pressing the hardware button so something is happenning ( this is the same log that when i do no use 'focusFirstInput', except that it does go back):
<code>
D/CordovaWebView( 9377): The current URL is: http://192.168.0.14:8100/#/app/search
D/CordovaWebView( 9377): The URL at item 0 is: http://192.168.0.14:8100/#/app/search
</code>  

I'm also using crosswalk, if that's any help.

Thanks

**Comment by apavillet** [comment]
Am i the only one seeing This?

**Comment by apavillet** [comment]
More on this : only happens if you open the modal with an ng-focus on a text input. Does work with ng-click on a button.

**Comment by vamsibolloju** [comment]
I also faced the same problem , when closing the ionic modal i can not user the hardware back button.

**Comment by Ionitron** [comment]
Greetings @apavillet!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
