### ISSUE TITLE
x-scroll on input focus , view wont fit in small devices

### ISSUE THREAD

**Issue by bleuscyther** [driftyco/ionic#2845]
in 5'' devices the '.loading-container' is taking an extra width causing the view to be x-scrollable on input focus .

Putting .loading-container to fixed instead of absolute seems to fix the issue.

+ will try to include some screenshots 
+ only happens in a real devices

**Comment by Ionitron** [comment]
Greetings @bleuscyther!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.
