### ISSUE TITLE
Add subtitle, not subheader, support.

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic#2851]
It would be nice if Ionic supported a subtitle, like described here: http://stackoverflow.com/questions/27756298/ionic-view-subtitle

See the nice screenshot too: http://i.stack.imgur.com/xsepF.png

**Comment by jeroenvanhaeverbeke** [comment]
At the very moment I'm using a little workaround to become this effect. View-title can be injected with html markup, so that is what I do. Don't forget to add a little bit of css to get both spans on 2 lines underneath each other.

Controller:
`$scope.viewtitle = '<span class="view-title">' + 'Title' + '</span><span class="view-subtitle"> - ' + 'Subtitle' + '</span>';`

Template:
`<ion-view view-title="{{viewtitle}}"><ion-content></ion-content></ion-view>`

It would be nice for the future if there was support for a 'view-subtitle' attribute on the ion-view tag.

**Comment by xAlien95** [comment]
A similar issue: it would be nice if there was support for [button-bars](http://ionicframework.com/docs/components/#button-bar) as it's for `ion-nav-buttons`.

**Comment by DominikVogt** [comment]
Any progress on this? For now i fixed the issue, but the text is not shrinking. Any fix to add shirinking feature for title and subtitle?

**Comment by arieljake** [comment]
Agree...this is standard ios ui.

I was able to accomplish this with:

html
------
<h1 class="title withSubtitle">
New Item
<span class="isSubtitle">Select a group</span>
</h1>

css
-----
ion-header-bar h1.withSubtitle {
	top: -.5rem !important;
	overflow: visible !important;
}

ion-header-bar span.isSubtitle {
	position: absolute;
	left: 0;
	right: 0;
	top: 1rem;
	font-size: .9rem;
	font-weight: normal;
}

**Comment by Ionitron** [comment]
Greetings @cfjedimaster!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by cfjedimaster** [comment]
Ugh - no - it isn't inactive. It isn't high priority, but it is a valid request. This needs to be reopened instead of me just copying and pasting it into a new issue.

**Comment by EnSabanNur** [comment]
+1, would be useful to do this out of the box. Although, admittedly, the css fix is pretty trivial if you're manually adding headers in as markup.

**Comment by wal-nadeem** [comment]
+1

**Comment by AnselmeR** [comment]
+1

**Comment by jgw96** [comment]
@cfjedimaster Reopening so that we can take a look at this again. (:

**Comment by MatanYed** [comment]
This reaction fits material design?

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us. As we are not planning on adding this feature to Ionic 1, but are considering it for Ionic 2 i will be closing this issue in favor of https://github.com/driftyco/ionic/issues/5940 which is focused on Ionic 2. Please feel free to put any comments, suggestions or questions about this issue on that issue. Thanks for using Ionic!
