### ISSUE TITLE
bug: Modal and Popover z-order

### ISSUE THREAD

**Issue by rajatrocks** [driftyco/ionic#2860]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When modals are created, their z-order is permanently set. This causes problems if Modal A can be opened from either a tab view or from Modal B. Depending on the order things are created, Modal A might show up behind Modal B even though it's being launched from Modal B. 

More detailed description here: http://forum.ionicframework.com/t/multiple-modals-issue/7930/11

Ideally the z-order would get recomputed/reset every time the modal is shown, to make sure it appears on top. 

This issue also applies to popovers.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Would you be able to put together a codepen to replicate the issue?

**Comment by rajatrocks** [comment]
Codepen here: http://codepen.io/rajatrocks/pen/YPpJPy - let me know if you have any questions.

**Comment by raffael** [comment]
I'm suffering from this as well. :)

**Comment by pniraula** [comment]
has anything updated to fix this issue. I m facing same problem

**Comment by Ionitron** [comment]
Greetings @rajatrocks!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by BestPig** [comment]
The codepen posted by @rajatrocks use the 1.2.4 version of ionic (latest release) and still has the problem and I also face the problem in my app.
So @Ionitron, you can reopen this issue I think.
