### ISSUE TITLE
Scroll position is lost when dealing with collection-repeat + modal opening 

### ISSUE THREAD

**Issue by mica16** [driftyco/ionic#2864]
Let's suppose a tab presenting the view MyList: a list of item using a collection-repeat.
Click on an item, its detail is shown. 
Now, go back and...cool the scroll has kept the position ! Everything Ok, since MyList is a cached view .

Now this scenario: 
Click on an item, and in its detail page, open a modal (assuming there's button/link opening a modal).
Now, close the modal and go back to the list (through the back button too).
Wow! The scroll has lost the previous position, it's at the top ! => issue

It doesn't happen when using classic ng-repeat.

Is it possible to fix it? It's very annoying regarding UX ;)

Thanks a lot

**Comment by Ionitron** [comment]
Greetings, @mica16!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2864)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Closed
