### ISSUE TITLE
bug: Scroll is lost with collection-repeat

### ISSUE THREAD

**Issue by mica16** [driftyco/ionic#2865]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Let's suppose a tab presenting the view MyList: a list of item using a collection-repeat.
Click on an item, its detail is shown. 
Now, go back and...cool the scroll has kept the position ! Everything Ok, since MyList is a cached view .

Now this scenario: 
Click on an item, and in its detail page, open a modal (assuming there's button/link opening a modal).
Now, close the modal and go back to the list (through the back button too).
Wow! The scroll has lost the previous position, it's at the top ! => issue

It doesn't happen when using classic ng-repeat.

Here's a codepen: http://codepen.io/mica16/pen/EaygJa?editors=101

</span>

<span is-issue-template></span>

**Comment by fafk** [comment]
It doesn't need to be a modal, even showing keyboard causes the same issue.

**Comment by felquis** [comment]
This issue is fixed in the v1.0.0-beta.14-nightly-1011 or newer, was fixed from this issue #2935 

@fafk I suggest you to try again with the last beta, if it still happen, create another issue with [this](http://ionicframework.com/submit-issue/ ) and include a codepen and describe how to simulate the problem :D

**Comment by mica16** [comment]
Indeed, tried it and I confirm it's fixed ! Well done ;)

**Comment by ajoslin** [comment]
Fixed .
