### ISSUE TITLE
bug: hardcoded interpolation symbols

### ISSUE THREAD

**Issue by ndevr** [driftyco/ionic#2873]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello,

currently I'am using meteor + angular + ionic. Meteor is using an own templating system called "Blaze+Handlbars" where they are using the same interpolation symbols "{{" "}}" as angular. To work together I need to change the interpolation symbols with the interpolation provider from angular (https://docs.angularjs.org/api/ng/provider/$interpolateProvider). Now the problem is that some ionic directives has hardcodes interpolation symbols "{{" "}}" which makes the directives impossible to use.
If there is a getter from angular's interpolation provider you should get it from there or it is configurable for the whole module.

Example: ion-item directive</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @ndevr!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2873)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by drewrygh** [comment]
Thanks, this has been brought up before and we removed a few of them, but it looks like a few slipped through.

**Comment by gkalpak** [comment]
BTW, Angular is normalizing directive templates (i.e. replacing `{{`/`}}` with the actual interpolation symbols), so directive templates do not need extra work.

**Comment by ndevr** [comment]
If I'am looking into the sources there are the hardcoded symbols.  Could you show me that on the angular sources?

**Comment by lance-anderson** [comment]
+1

**Comment by jgw96** [comment]
Hello! Are you all still experiencing this issue in the latest version of ionic?

**Comment by jgw96** [comment]
Hello! Thanks for opening this issue with us! As it has been a little while since there was any activity on this issue I will be closing it for now, please feel free to reply if you are still experiencing this issue though!
