### ISSUE TITLE
Wrong side-menu-content width on imbricated side-menus

### ISSUE THREAD

**Issue by groblochon** [driftyco/ionic#2876]
Type: bug

Platform: all

Codepen: http://codepen.io/anon/pen/emBoge

Wrong side-menu-content width on imbricated side-menus, we must substrate first menu width to correct this, please see this exemple :
http://codepen.io/anon/pen/emBoge

**Comment by Ionitron** [comment]
Greetings @groblochon!

My sensors indicate that more information is required so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.

**Comment by groblochon** [comment]
Updated.

**Comment by mhartington** [comment]
In general this over all layout isn't advised. As you're seeing it comes with errors, and the overall structure isn't something that is common in any native apps.
