### ISSUE TITLE
feat: Slidebox option to dont allow swipe

### ISSUE THREAD

**Issue by danielfpedro** [driftyco/ionic#2877]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm using the ion-slide-box and I'm changing the boxes in a button for the purpose of my app. I need an option to disallow users swipe the boxes. I dont find this on documentation and I think could be an intersting feature.</span>

<span is-issue-template></span>

**Comment by drewrygh** [comment]
Hey @danielfpedro, good idea. You can actually do this by enabling slide only when your button is clicked, changing the slide, and then disabling it again.

Example: [codepen](http://codepen.io/drewrygh/full/raWgmR)

**Comment by danielfpedro** [comment]
Nice but I can't disabled from controller because I think the ion-slide-box take a little to be completely rendered. Do you have any solution about it?

**Comment by danielfpedro** [comment]
I got the full solution for the issue.
I dit exactly what you did on codepen but rather then do this `$ionicSlideBoxDelegate.enableSlide(false);` at the beginnig of the controller, i did this `disable-scroll="true"` on `<ion-slide-box>` at the view. The rest is exactly what you did on codepen.
I read a time ago someone talk about the disabled-scroll will be decrepted, so I dont know if my approach could be the best.

**Comment by drewrygh** [comment]
Glad you got it working. Another option would be to wrap the initialization in a timeout:

```
  $timeout(function(){
    $ionicSlideBoxDelegate.enableSlide(false); 
  });
```

The problem is the controller might initialize itself and execute the `$ionicSlideBoxDelegate.enableSlide` call before the slide box directive is loaded. Wrapping it in a timeout will force the call to be delayed until the next digest cycle, if there is one.

Anyway, I think this pattern is clean enough to not require a new feature.
