### ISSUE TITLE
bug: tab badge will jump when badge number goes to 0 an

### ISSUE THREAD

**Issue by pencilcheck** [driftyco/ionic#2883]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Set badge from a non zero value to zero and watch it jump. But if you include the css I included in the issue

https://github.com/driftyco/ionic/issues/2882#issuecomment-68963862

```
.tab-item {
  position: relative;
}
```

Will prevent badge on transition jumps.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @pencilcheck!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
