### ISSUE TITLE
docs: bower.json file

### ISSUE THREAD

**Issue by brunyan** [driftyco/ionic#2888]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Why bower.json have dependencies in "angular", "angular-animate", "angular-sanitize" and "angular-ui-router"?
Ionic works great without these packages.
Thank you</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @brunyan!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2888)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by pulakb** [comment]
I think in project files we include ionic.bundle.min.js or ionic.bundle.js. Now this file is a concatenation of:
 * ionic.js, angular.js, angular-animate.js,
 * angular-sanitize.js, angular-ui-router.js,
 * and ionic-angular.js

**Comment by ajoslin** [comment]
As @pulakb said, ionic.bundle.js bundles all of these dependencies together.

But if you don't use ionic.bundle.js, all of these dependencies are needed. 

That's why they're listed in bower.json.
