### ISSUE TITLE
bug: Ion-tabs is not working with v.1.0.0 beta 14 and sidemenu

### ISSUE THREAD

**Issue by danicomas** [driftyco/ionic#2889]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>
```
<ion-view title="Tab Bar"> 
	<ion-nav-buttons side="left">
		<button menu-toggle="left" class="button button-icon icon ion-navicon"></button>
	  </ion-nav-buttons>
	  <ion-pane>
		<ion-tabs class="secondarytab" tabs-positive tabs-icon-only">

		  <ion-tab title="Home" icon-on="ion-ios7-filing" icon-off="ion-ios7-filing-outline">
			1
		  </ion-tab>

		  <ion-tab title="About" icon-on="ion-ios7-clock" icon-off="ion-ios7-clock-outline">
			2
		  </ion-tab>

		  <ion-tab title="Settings" icon-on="ion-ios7-gear" icon-off="ion-ios7-gear-outline">
			3
		  </ion-tab>

		</ion-tabs>
	</ion-pane>
		
  
</ion-view>
```

```
controller('TabbarCtrl',function($scope, $stateParams, $ionicTabsDelegate) {
	var param = $stateParams.cat;
	
	if (param) {
		 $scope.$on('$viewContentLoaded', function(){
			$ionicTabsDelegate.select(parseInt(param));
		});
	}
	
})
```

Never select any tab and not works viewContentLoaded too. With beta 13 I could do it.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @danicomas!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2889)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by pulakb** [comment]
Can you please create a codepen of this?

**Comment by danicomas** [comment]
http://forum.ionicframework.com/t/ion-tabs-is-not-working-with-v-1-0-0-beta-14-and-sidemenu/15249

**Comment by danicomas** [comment]
Solved
