### ISSUE TITLE
improvement: $ionicNavBarDelegate - access html element

### ISSUE THREAD

**Issue by panurge-ws** [driftyco/ionic#2891]
Is there a way to access the nav bar DOM element (eg. to toggle classes) directly from the delegate?

**Comment by Ionitron** [comment]
Greetings, @panurge-ws!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2891)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @panurge-ws!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
