### ISSUE TITLE
bug: ion-tabs is always in the top of the app

### ISSUE THREAD

**Issue by pantao** [driftyco/ionic#2892]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Use 

    ionic start TabsAppDemo tabs

start a new ionic app. and the ion-tabs is always in the top of the app.

It looks like any XiaoMi Mobile or MIUI Mobile have this problem.

![http://xingzhewujiang.org/usr/uploads/2015/01/3668034758.png](http://xingzhewujiang.org/usr/uploads/2015/01/3668034758.png)

![http://xingzhewujiang.org/usr/uploads/2015/01/97057662.png](http://xingzhewujiang.org/usr/uploads/2015/01/97057662.png)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @pantao!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2892)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by kylethielk** [comment]
I believe this duplicates #2584 and should be closed. Looks like this is as designed.

**Comment by pantao** [comment]
Thanks

**Comment by Ionitron** [comment]
Greetings @pantao!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
