### ISSUE TITLE
bug: sidemenu doesn't close with swipeleft - v.1.0.0 beta 14

### ISSUE THREAD

**Issue by danicomas** [driftyco/ionic#2893]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I can open with swiperight but I can't close with swipeleft. I can only close menu with header button. If you create a new sidemenu project with basics you will see it.

Android v.4.4.4 Nexus 4</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @danicomas!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2893)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by adamdbradley** [comment]
This should be fixed as of: https://github.com/driftyco/ionic/commit/a5881eaeba7d12d016fe3712c77261e75e863cf3
