### ISSUE TITLE
Support for "Web Notifications"

### ISSUE THREAD

**Issue by chrisvella** [driftyco/ionic#2898]
I'm wondering if ionic has support for web notifications?
I'm looking to wrap an application which uses this api feature. It would be a lot quicker than reimplementing some sort of push notification system.

This may be a cordova feature so sorry if this is in the wrong place.

https://developer.mozilla.org/en-US/docs/Web/API/Notification/Using_Web_Notifications
http://www.w3.org/TR/notifications

**Comment by Ionitron** [comment]
Greetings, @chrisvella!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2898)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @chrisvella!

My sensors indicate that you have created an issue on our tracker that is more asking for usage help than an actual error with Ionic framework.

This Github issue tracker is used to track features, problems, and development of the framework.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
