### ISSUE TITLE
bug: Consecutive Buttons with ng-click, second button uses first buttons' ng-click

### ISSUE THREAD

**Issue by kylethielk** [driftyco/ionic#2899]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm having the exact same issue found here: http://forum.ionicframework.com/t/ng-click-not-working-with-two-consecutive-buttons/8123

Just creating an issue here for it. I'm using  v1.0.0-beta.14

http://codepen.io/anon/pen/cqKkI

Copied text from linked forum post:

> I'm using two buttons with ng-click calling separate functions.

> The first button works as expected, but when I click the second button, the first function is called. If you keep the second button clicked, you can see that both are down. Am I doing something wrong? I'm tested in both Chrome and Mozilla, both show this behaviour.

> UPDATE: If you change to ng-mouseup it works. It appears ng-click is bound to the parent div. I'm actually using it inside a item-button so this might mess up (intentionally or not) with the events. Anyway, it would be nice to have ng-click working in this case but I'm glad ng-mouseup works (both in desktop and mobile).
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @kylethielk!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2899)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by kylethielk** [comment]
Just an update. I was able to work around this by wrapping each button in a <label></label>

**Comment by pulakb** [comment]
@kylethielk Don't keep the buttons inside the label for GENDER. label should be closed before the div which contains your buttons. This will cause the buttons to come in the next row, not side by side of the label. But putting the buttons div in the same row can be done using CSS.

**Comment by kylethielk** [comment]
@pulakb  They are not inside Gender's label. See here: http://codepen.io/anon/pen/rajJjQ

**Comment by Ionitron** [comment]
Greetings @kylethielk!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by dufrenb** [comment]
Hello! I'm getting the same issue as reported using IONIC 1.
This is the html template causing the issue:
` <label>
      <button type="submit" class="button button-positive" ng-click="takePicture()">Take Picture</button>
      <img ng-show="uploadPicture" class="image-circular" src="data:image/jpeg;base64," + {{picture}}>
      <button type="submit" class="button button-positive" ng-click="browsePicture()">Open Gallery</button>
    </label>`

In fact the second button fire the same function as th first.
I managed to debug this and thank's to this post this is the solution: putting the two ng-click into two differents scopes.
`<label>
      <button type="submit" class="button button-positive" ng-click="takePicture()">Take Picture</button>
    </label>
      <img ng-show="uploadPicture" class="image-circular" src="data:image/jpeg;base64," + {{picture}}>
    <label>
      <button type="submit" class="button button-positive" ng-click="browsePicture()">Open Gallery</button>
    </label>`
