### ISSUE TITLE
bug: ionicScrollDelegate scrollTo triggers digest cycle

### ISSUE THREAD

**Issue by alextrs** [driftyco/ionic#2902]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

Digest cycle kicks every time scrollTo (pretty much any method in ionicScrollDelegate) is used. I need to keep the same scroll position for two ion-scroll panels, but this causes huge amount of digests. Please, see codepen:
http://codepen.io/alextrs/pen/NPdgLZ

Apparently the following $timeout creates this issue, do we really need to kick digest cycle every time resize is called?
```javascript
  .controller('$ionicScroll', [
  ...
  self.resize = function() {
    return $timeout(resize).then(function() {
      $element && $element.triggerHandler('scroll.resize');
    });
  };
```

If there is better way to keep two ion-scroll panels in sync, please, let me know.

Regards,
Aliaks</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @alextrs!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2902)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by ajoslin** [comment]
It definitely shouldn't trigger a digest.
