### ISSUE TITLE
feat: Lock orientation for a single Page (ion-view)

### ISSUE THREAD

**Issue by AndreasHo** [driftyco/ionic#2905]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello guys,

i search a solution for my problem, i want to lock the orientation of the screen in "portrait". So that the user can't go into "landscape". 

That i can lock it complete in config.xml i know, but i want to lock it for a single Page (ion-view) ...</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @AndreasHo!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2905)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by jbasinger** [comment]
We are using a plugin for this functionality https://github.com/cogitor/PhoneGap-OrientationLock
It works well for our Android devices.

**Comment by Ionitron** [comment]
Greetings @AndreasHo!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
