### ISSUE TITLE
perf: collection-repeat: Slow performance when changing view

### ISSUE THREAD

**Issue by rotorgames** [driftyco/ionic#2908]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Galaxy Tab 2
Android 4.1.2
Ionic 1.0.0-beta.14

Why the change of view from the collection-repeat slow ? View is located in the cache, and collection-repeat should not draw again.

http://youtu.be/a5cYqktbVtU</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @rotorgames!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2908)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by fifafu** [comment]
I have the same problem, switching tabs is unbelievably slow (up to 30 seconds) when using collection-repeat (if one tab has a list with many list items). For me this happens on all platforms. Is this a known issue or are we doing something wrong?

**Comment by jjimenezlopez** [comment]
Same problem here, my problem is going back from a detail view to the collection-repeat view with a few elements, transition is so slow.

**Comment by ajoslin** [comment]
Fixed with the latest nightly - full dimension recalculation isn't done anymore. 142a22b124e5af644414faa8611957aeebb8aeb4
