### ISSUE TITLE
bug: Styles change when using Google map

### ISSUE THREAD

**Issue by psimondk** [driftyco/ionic#2909]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>When invoking a simple lat/lon centered google map from a list as eg. a list of shops the visual style of the list is changed when navigating back from google map.

I am using the angular router as in eg. ng-href="#app/showmap/{{shop.id}}

It happens with beta 14 but not with earlier betas - i.e. beta 10.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @psimondk!

My sensors indicate that more information is required so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
