### ISSUE TITLE
bug: $ionicModal backdrop click causes modal to close

### ISSUE THREAD

**Issue by pencilcheck** [driftyco/ionic#2912]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Create a button in a $ionicModal that opens a $ionicPopup.alert. While the popup alert is on, click on the backdrop, expecting the popup to dismiss but instead it closes the modal.</span>

<span is-issue-template></span>

**Comment by pulakb** [comment]
@pencilcheck can you please share it as a codepen example?

**Comment by pencilcheck** [comment]
http://codepen.io/anon/pen/OPmRYL

**Comment by Ionitron** [comment]
Greetings @pencilcheck!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
