### ISSUE TITLE
bug: cordova plugin hooks are not called. Needs to upgrade Cordova

### ISSUE THREAD

**Issue by mkliu** [driftyco/ionic#2913]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>I'm on version 1.3.0. For example, the hooks from this plugin
   cordova plugin add com.wordsbaking.cordova.wechat --variable APP_ID=test
I had to manually upgrade cordova standalone. Then it worked.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @mkliu!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2913)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @mkliu!

My sensors indicate that more information is required so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
