### ISSUE TITLE
bug: ion-nav-bar won't change classes on stateChange

### ISSUE THREAD

**Issue by CoenWarmer** [driftyco/ionic#2916]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When using a sidemenu based project, the ion-nav-bar directive won't pick up on rootScope variables set through ng-class.

See http://codepen.io/squrler/pen/BypeaL for an illustration of this problem.

When using ion-nav-bar in a non sidemenu based project, this approach does work. See http://codepen.io/prettyGoodPancakes/pen/myOJrm for how that works.

It would be great if the ion-nav-bar directive would work the same way in both cases, or an alternative solution is devised.</span>

<span is-issue-template></span>

**Comment by MMrko** [comment]
Subscribing.

**Comment by NickSchlax** [comment]
Would love to see a solution to this.  Setting a new nav-bar in each template cause some flashing on transitions with beta 14, so I would much rather use a solution like this.

**Comment by CoenWarmer** [comment]
Any traction?

**Comment by Ionitron** [comment]
Greetings @CoenWarmer!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
