### ISSUE TITLE
bug: collection-repeat is limited to 1000 items

### ISSUE THREAD

**Issue by jamm** [driftyco/ionic#2918]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Just discovered that collection repeat render only up to 1000 items. I have 1100 items but only first 1000 are rendered.
Code is simple:
```html
<a class="item item-icon-right"
                collection-repeat="account in accounts | filter:searchText | orderBy:'id':true"
                collection-item-height="53"
                href="#/app/account/{{account.id}}"
                style="width: 100%">{{ account.name }}<i class="icon ion-chevron-right"></i>
</a>
```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @jamm!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2918)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by ajoslin** [comment]
Could you create a plunkr?

**Comment by jamm** [comment]
Thanks for the idea :)
While writing plunkr, I found reason of bug: 
http://plnkr.co/edit/Y3vueTtQxOmpJ5GJ8UJQ?p=preview
field "id" is string so orderBy filter sort values as strings.
So bug is in my dataset. Sorry for taking your time.
