### ISSUE TITLE
bug: Input within item-input-inset couldn't be updated

### ISSUE THREAD

**Issue by johnsonqu** [driftyco/ionic#2922]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Just as displayed in below codepen. http://codepen.io/mhartington/pen/oBwln

1. Click 'Get my code'.
2. Update code in input control to 'aaa' for example.
3. Re-click 'Get my code'.
4. Code should be '123', but it still is 'aaa'.

Full thread is as below

http://forum.ionicframework.com/t/button-next-to-an-input-not-clickable/4142/13</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @johnsonqu!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
