### ISSUE TITLE
bug: Content overlapse nav-bar when keyboard is open

### ISSUE THREAD

**Issue by kurtommy** [driftyco/ionic#2924]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>view this post

http://forum.ionicframework.com/t/content-overlaps-header-after-keyboard-show-in-ios-and-ionic-beta14/15580</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @kurtommy!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2924)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @kurtommy!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
