### ISSUE TITLE
bug: Need to mock http call to view in unit tests

### ISSUE THREAD

**Issue by hypery2k** [driftyco/ionic#2927]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I have a strange issue. I updated the ionic framework to beta14, now a lot of my unit tests fail like this:
```
PhantomJS 1.9.7 (Mac OS X) Controller: xxxxCtrl should list books FAILED
	Error: Unexpected request: GET views/xxx/yyyy/booksView.html
	Expected GET @@API_URL/xxx/yyy/endpoint
	    at $httpBackend (/.../bower_components/angular-mocks/angular-mocks.js:1181)
```
Is this related to the templateCache?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @hypery2k!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2927)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @hypery2k!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
