### ISSUE TITLE
bug: Scroll position lost after state then orientation change on Android

### ISSUE THREAD

**Issue by jbasinger** [driftyco/ionic#2928]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>On my list view I'm using collection-repeat. If I scroll far down, then select an item my app brings me to another view.

Now, if I go back immediately, my scroll position is right where I left it. But if I'm on the detail view and change the orientation from portrait to landscape and back *then* go back to the list view, my scroll position is lost.

I haven't tried this on an iOS device, but I have on different Android devices. I also tried this on a freshly created throw-away app to confirm it wasn't something silly I'm doing in my specific application. The behavior is still the same.

I'd offer a codepen example if I knew a way to cause an orientation change event.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @jbasinger!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2928)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by mhartington** [comment]
Can you give the nightly build a try

**Comment by ajoslin** [comment]
This is fixed now.
