### ISSUE TITLE
bug: ng-controller on body tag loaded multiple times

### ISSUE THREAD

**Issue by sean-hill** [driftyco/ionic#2929]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Having `<body ng-controller="AppCtrl">` with a child `<ion-nav-view>` and `$ionicView.loaded` listener causes the `loaded` event to fire multiple times when you navigate the app.

Check out this codepen for an example.

http://codepen.io/anon/pen/emvZQx</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @sean-hill!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
