### ISSUE TITLE
bug: 1.3.0-beta1 with crosswalk compile error

### ISSUE THREAD

**Issue by do-web** [driftyco/ionic#2931]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>webview</span>

<span ionic-description>I use the com.phonegap.plugins.facebookconnect plugin in my project, but when i compile for android i get these error:

UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersion.....

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @do-web!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2931)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by do-web** [comment]
If i delete android-support-v13.jar from the android libs folder then the compiling works. It seams the facebook plugin used android-support-v4.jar

**Comment by willadamskeane** [comment]
I'm also having this issue. Can this be re-opened?
