### ISSUE TITLE
bug: Subfooter hidden if bottom tabs are used

### ISSUE THREAD

**Issue by tkem** [driftyco/ionic#2932]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>My project uses tabs (with `$ionicConfigProvider.tabs.position('bottom');` if that matters). On one of my views, I additionally have both a footer and a subfooter (whether that's a good idea is debatable, but that's not the subject of this issue). Now, it looks like the subfooter gets hidden "behind" the footer (or vice versa), even when I add `class="has-subfooter"` to my content element.

Adding the following SCSS seems to fix this, but I'm new to Ionic and SCSS, so I'm wary about possible side effects:
```
.bar-subfooter.has-tabs {
  bottom: $tabs-height + $bar-footer-height;
}
.has-subfooter.has-tabs {
  bottom: $tabs-height + $bar-footer-height + $bar-subfooter-height;
}
```
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @tkem!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2932)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by mikemintz** [comment]
I have this issue too. I've reproduced it here: http://codepen.io/mikemintz/pen/QwgOYV

**Comment by mhartington** [comment]
For this, you should use your css fix. We don't want to add anything that could possibly introduce a new css bug. Down the road, we will be switching everything over to flex box so this won't be an issue.

**Comment by alphapilgrim** [comment]
@mhartington Has the flex box implementation been pushed to latest version, would also like to use a "sub-footer". Unless there is some we can use out of the box for something like this?
