### ISSUE TITLE
bug: $ionicHistory.clearHistory() not working on Android

### ISSUE THREAD

**Issue by msalman** [driftyco/ionic#2934]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>$ionicHistory.clearHistory() doesn't seems to remove the view from the stack history on Android as I have been able to go back to previous views using hardware back button.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @msalman!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2934)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by ygotthilf** [comment]
+1

Version : 1b14
Android : 4.4

I try the following code but the hardware back button goes back to the view A : 

View A
----------

   $ionicHistory.nextViewOptions({
            disableBack: true,
            historyRoot: true
   });
   $state.go(path);

View B
---------

$ionicHistory.clearHistory();

**Comment by techntrails** [comment]
Is the controller in which you're executing clearHistory() cached? If so, it may not be executing.

You may want to try adding  cache: false to your state depiction for that view/controller.

**Comment by Ionitron** [comment]
Greetings @msalman!

I'm sorry, but my sensors indicate that this issue may no longer apply to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen it by creating a new issue and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com). There are many humans there who can offer sage advice.

Thank you for allowing me to assist you.

**Comment by msalman** [comment]
Hi techtrails, thanks for the input, below is my use case

I have a simple login based application in which user can access About menu with or without login, issue came with android hardware back button,

Login screen > About page > From Menu go to Login > Press hardware back button > Application Should get closed rather go to About page.

Below is the code for navigation to login screen.

```javascript
$scope.login = function() {
            $ionicHistory.nextViewOptions({
                disableBack: true,
                disableAnimate: true,
                historyRoot: true
            });
            $ionicHistory.clearCache();
            $ionicHistory.clearHistory();
            $ionicSideMenuDelegate.toggleLeft();
            $state.go('login');
        };
```

I am using ionic rc release 4 currently.
