### ISSUE TITLE
ion-nav-title is not inherited

### ISSUE THREAD

**Issue by brunogonncalves** [driftyco/ionic#2936]
Hi,
I have a standard  ion-nav-bar that works well, but the ion-nav-title, does not work

```html
<body ng-app="starter">
<!-- My default nav bar -->  
  <ion-nav-bar class="bar bar-dark" >
        <!-- My defualt nav title -->
       <ion-nav-title>
            <img height="80%" class="title-image" src="img/logo.png" />
        </ion-nav-title>
    </ion-nav-bar>
    <ion-nav-view>
    </ion-nav-view>

</body>
```

I creating others views, but only ion-nav-bar is inherited
```html
<ion-view>
  <ion-content>
    <h1>Browse</h1>
  </ion-content>
</ion-view>
```

**Comment by Ionitron** [comment]
Greetings, @brunogonncalves!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2936)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by pulakb** [comment]
@brunogonncalves codepen please

**Comment by bogoroh** [comment]
Are you running at least beta 14?
