### ISSUE TITLE
bug: iOS toggle doesn't allow dragging nub

### ISSUE THREAD

**Issue by linagee** [driftyco/ionic#2937]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I did:
'''
ionic start ionic-tabs tabs
ionic platform add ios
ionic run ios
'''
(And after getting all the certificates and such set up, have it running on an iPad Air 2, iOS 8.1.2.)

I've been trying out the controls and such. According to http://ionicframework.com/docs/api/directive/ionToggle/ it says "Allows dragging of the switch's nub."
I am on the "Account" tab in the demo tabs app. I can tap the toggle for "Enable Friends" and it changes state. I try to slide it and nothing happens. I've tried to tap/slide this same sort of toggle/nub in native controls like in settings and it does allow both actions.

Is it because the list is bouncing slightly? (I try to go very very horizontal with my swipe of the nub and it still doesn't change state.)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @linagee!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2937)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @linagee!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
