### ISSUE TITLE
bug: CLI "ionic info" shows incorrect information

### ISSUE THREAD

**Issue by docherty** [driftyco/ionic#2938]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Not a major issue but on OSX, I typed "ionic info" into the terminal and it returned the OS as "OS: Mac OS X Yosemite". I've not taken the Yosemite plunge yet so I'm still running 10.9.5 . Here's the full output:
```
$ ionic info

Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.33
Cordova CLI: 4.1.2
Ionic Version: 1.0.0-beta.14
Ionic CLI Version: 1.3.1
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: 3.1.1 

```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @docherty!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2938)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by jbavari** [comment]
@docherty - moving this issue to the [CLI issues here](https://github.com/driftyco/ionic-cli/issues/230)
