### ISSUE TITLE
perf: resize is too slow when ion-content size changes for scrolling

### ISSUE THREAD

**Issue by mikey0000** [driftyco/ionic#2940]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>When I add more content to ion-content it takes too long to resize and when I scroll it bounces back before reaching the end of the content.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @mikey0000!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2940)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by grahamj** [comment]
Yep I see this too, looking for workaround. Tried

~~~javascript
$scope.$broadcast('scroll.resize');
~~~

(when switching on content via a toogle in my case) to no avail. Tried ng-if and ng-show for the content switching, same thing either way.

**Comment by Ionitron** [comment]
Greetings @mikey0000!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

**Comment by cnd5041** [comment]
Was there ever an update/fix for this? I'm having the same issue with scrolling when using ng-show in an ion-content.
Here's a basic plunker showing the general idea: http://plnkr.co/edit/xIEVmffOuZPkjlWdjS5k?p=preview

**Comment by devstu** [comment]
I am having the same problem.  Does the work around work?

**Comment by cnd5041** [comment]
The $ionicScrollDelegate.resize() did work well for me. Never went back to look for better alternatives.

**Comment by devstu** [comment]
Awesome thanks!  Maybe we need an ion-show and ion-hide directive that
would automatically call the $ionicScrollDelegate.resize.  But for now I
can fix on my own, thanks!
