### ISSUE TITLE
bug: Card and ion-list in the same view

### ISSUE THREAD

**Issue by danicomas** [driftyco/ionic#2941]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>If you emulate with mobile (iphone 4 / nexus 4), the last ion-list-item has less height. What is wrong?

http://codepen.io/danicomas/pen/gbmvEm</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @danicomas!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2941)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by danicomas** [comment]
http://forum.ionicframework.com/t/ion-scroll-you-can-scroll-down-too-much/2764
