### ISSUE TITLE
bug: ion-tabs + header issue

### ISSUE THREAD

**Issue by nokturnal** [driftyco/ionic#2942]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hey,

I noticed some strange behaviour that involves ion-tabs (more specifically ion-tab) and a required header element.  Please see the following CodePen:

http://codepen.io/nokturnal/pen/pveKvw

Notice how everything works as expected.

If you comment out lines 58 to 60 things go a bit buggy:

- Top view padding is not applied rendering part of the view behind the nav header.
- Bottom view padding is not applied rendering part of the content behind the tab footer
- Scrolling is disabled

Note: if you substitute the <header> with a <ion-header-bar> the above scenario still applies.

Is a header element (or ion-header-bar) mandatory now for ion-tab elements?

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @nokturnal!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2942)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by perrygovier** [comment]
Hey @nokturnal, I'm getting a lot of JS errors on the codepen. Did you do some debugging since posting this?

**Comment by saurabhgupta050890** [comment]
Having same problem.

**Comment by Ionitron** [comment]
Greetings @nokturnal!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @nokturnal!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
