### ISSUE TITLE
Transitions and Back button goes away on Airplane Mode when the app is running.

### ISSUE THREAD

**Issue by raphagodoi** [driftyco/ionic#2943]

**Comment by Ionitron** [comment]
Greetings, @raphagodoi!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2943)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @raphagodoi!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you for allowing me to assist you.
