### ISSUE TITLE
docs: Testing $ionicPopup used in a controller

### ISSUE THREAD

**Issue by wrousseau** [driftyco/ionic#2946]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>First of all, I'm not sure I've categorized this right... Sorry if it's not the case...
I have fully read the documentation of $ionicPopup as well as the service unit tests, but I am unable to locate or to find out a proper way to unit test a controller which uses its `show` method, especially the case where several buttons are present, one of which simply cancels and hides the popup. 

For instance, how would one test the controller given on https://github.com/driftyco/ionic/blob/master/test/html/popup.html

If I'm missing something in your unit tests, it would be great to give me some pointers on where to find the info ! Cheers !</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @wrousseau!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
