### ISSUE TITLE
NOT_FOUND_ERR: DOM IDBDatabase Exception

### ISSUE THREAD

**Issue by Thomsen** [driftyco/ionic#2947]
i use ionic v1.0.0-beta.14 and indexeddb storage. 

__question:__
file:///android_asset/www/lib/ionic/js/ionic.bundle.js: Line 19387 : Error: NOT_FOUND_ERR: DOM IDBDatabase Exception 3 (in the samsung note2 android 4.1.2)

**Comment by Ionitron** [comment]
Greetings, @Thomsen!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2947)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by Thomsen** [comment]
@Ionitron Thanks for your reply!

It's solved. The indexeddb db is not opened.
