### ISSUE TITLE
bug: Fast switch between tabs breaks the DOM completely When view cache 0 (OFF)

### ISSUE THREAD

**Issue by jianbo** [driftyco/ionic#2951]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>When view cache is disabled, the default tab example breaks when fast switch between tabs.
![screen shot 2015-01-17 at 10 52 17 am](https://cloud.githubusercontent.com/assets/209831/5784994/87f03ee8-9e36-11e4-9515-f3caaa8976c0.png)

![mmexport1421444716418](https://cloud.githubusercontent.com/assets/209831/5784986/75ed0c4e-9e36-11e4-8015-c72655b2dea3.jpg)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @jianbo!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2951)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by jianbo** [comment]
Hello anyone there? :S
