### ISSUE TITLE
bug: [ionic: 1.0.0-beta.14] ion-infinite-scroll: view never update 

### ISSUE THREAD

**Issue by blacksmith77** [driftyco/ionic#2956]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>ion-infinite-scroll fires function to update model but never update view.
$scope.$broadcast('scroll.infiniteScrollComplete'); seems to never be fired.

ionic version: 
gitpulled today with npm install -g ionic

	OS: Windows XP
	Node Version: v0.10.35
	Cordova CLI: 4.2.0
	Ionic Version: 1.0.0-beta.14
	Ionic CLI Version: 1.3.2

project created with ionic start myAppBlank blank

This in my test code:

FILE: index.html

	 <ion-content ng-controller="ContentController">
	  <ion-refresher pulling-text="Pull to refresh..." on-refresh="doRefresh()"></ion-refresher>
	  
		<ion-list>
		  <ion-item ng-repeat="item in items">
			{{item}}
		  </ion-item>
		</ion-list>
		
		<ion-infinite-scroll on-infinite="loadMore()" ></ion-infinite-scroll>
 
	</ion-content>

FILE: app.js
	 app.controller('ContentController', function($scope){

	if( !$scope.items )
		$scope.items = ['init Post 1', 'init Post 2', 'init Post 3', 'init Post 4', 'init Post 5' ];
	
	$scope.doRefresh = function() {
		// [..] ... this is working weel
	};
	
	$scope.loadMore = function() {
		$scope.items.push('Loaded POST (' + ($scope.items.length + 1) + ') by IS');
		$scope.$broadcast('scroll.infiniteScrollComplete');
		console.log( 'loadMore(): ' + $scope.items.length );
	};

	
	$scope.$on('$stateChangeSuccess', function() {
		console.log( 'STATE CHANGED!' );  // this is never reached!!!
	});
	
	 });

Thanks in advance</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @blacksmith77!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2956)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by blacksmith77** [comment]
<ion-infinite-scroll> element work well in nightly version.
Closing issue.
