### ISSUE TITLE
bug: bug: Problems with Windows and Windows Phone

### ISSUE THREAD

**Issue by CKGrafico** [driftyco/ionic#2959]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>One of your dependencies has a problem, https://github.com/angular/angular.js/issues/10796#issuecomment-70425893 but they think different..

How can we fix this to work with ionic?</span>

<span is-issue-template></span>
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @CKGrafico!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2959)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by dkarzon** [comment]
For Windows 8.1 make sure you include the winstore-compat.js from MSOpenTech https://github.com/MsopenTech/winstore-jscompat 

This allows you to use DOM properties such as `innerHTML` and `outerHTML` which angular uses internally.

**Comment by CKGrafico** [comment]
Ok, It can be a great temporary solution thanks!
Inject text as HTML is worst solution that I see ever but the won't change it.
