### ISSUE TITLE
Access to restricted URI denied

### ISSUE THREAD

**Issue by svanetten1976** [driftyco/ionic#2962]
Hi all,
  I'm building an iOS app with this lovely framework and I recently just upgraded to the newest version of the ionic.bundle.js (v1.0.0-beta.14) in order to get some of the features of the Angular Bootstrap directive working. The problem is, since I updated I'm getting an error in my Firebug console that reads "Access to restricted URI denied createHttpBackend..." The error is not actually effecting anything in the app, but I don't like the error. Note: I am working off of local files and viewing the pages / states in a browser as I develop the app. Any ideas? Thanks -- Steve

**Comment by stianjensen** [comment]
Are you using `ionic serve` to run the app?

**Comment by svanetten1976** [comment]
HI Stian,
  Thanks for getting back to me. Nope, I'm not running the virtual
server. I'm just viewing the files directly from a local folder on my
hard drive, from the main index.html file. Is that the whole issue? --
Steve

**Comment by stianjensen** [comment]
It could be the issue. Viewing files from a local folder in your browser may lead to all sorts of problems with file access issues and the like. I would recommend using ionic serve, or possibly some other local development server.

**Comment by gouegd** [comment]
+1, using local files leads to several problems due to security restrictions on browsers.
I favour the python embedded webserver (python -m SimpleHTTPServer) or the http-server npm module.

**Comment by Ionitron** [comment]
Greetings @svanetten1976!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
