### ISSUE TITLE
Add autoprefixer support?

### ISSUE THREAD

**Issue by hollingberry** [driftyco/ionic#297]
Have you seen https://github.com/nDmitry/grunt-autoprefixer? It might save a lot of trouble in transitioning to other OSes, like Firefox OS.

**Comment by gregblass** [comment]
I'd really recommend you reconsider this. I'm coming from rails and autoprefixer is amazing. Instead of writing all the prefix code for every device when you're writing your sass, just write the one generic version and forget about everything else. It really is an amazing tool that I've come to take for granted. Writing -webkit- and -moz- in addition to the generic css in Ionic is really painful.
