### ISSUE TITLE
Right Side Menu Expose-aside bug

### ISSUE THREAD

**Issue by snblackout** [driftyco/ionic#2981]
When you have a right side menu and have the <code>expose-aside-when="large"</code> the side menu will show upon loading the app but when you click on any menu item in the side menu, the menu shifts to the left and doesn't display any content.

Here is codepen:

http://codepen.io/ScottN/pen/LELYMZ

**Comment by kyleellman** [comment]
+1

**Comment by Ionitron** [comment]
Greetings @snblackout!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
