### ISSUE TITLE
nav-bar-container class

### ISSUE THREAD

**Issue by aunz** [driftyco/ionic#2987]
I am learning the framework. I noticed that the class  'nav-bar-container' is added to an element (js/angular/controller/navBarController.js)
However, 'nav-bar-container' is not defined in the scss or css file. Is 'nav-bar-container' not needed?

**Comment by Ionitron** [comment]
Greetings @aunz!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
