### ISSUE TITLE
bug: Bower version issue - Earlier version is seen at newer than current release

### ISSUE THREAD

**Issue by darrynten** [driftyco/ionic#2996]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Doing a `bower list` or an `update` when version is set to `ionic#>=1.0.0-beta.14` shows that latest is `1.0.0-beta.9-nightly-279`, which is an older release.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @darrynten!

We are now requiring all issues to be submitted through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=2996) so that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=2996)**

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic-cli#245
