### ISSUE TITLE
bug: collection-repeat does not work with directives

### ISSUE THREAD

**Issue by davidpfahler** [driftyco/ionic#2998]
This has been discussed on the forums and - I think - deserves some attention: http://forum.ionicframework.com/t/v1-0-0-beta-11-collection-repeat-doesnt-work-with-directives/8267

**Comment by Ionitron** [comment]
Greetings @davidpfahler!

We are now requiring all issues to be submitted through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=2998) so that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=2998)**

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.
