### ISSUE TITLE
bug: ion-tabs above keyboard

### ISSUE THREAD

**Issue by Klapsa2503** [driftyco/ionic#3000]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi I have a problem with < ion-tabs > moving up when opening keyboard. 

This can be fixed by using:
< preference name="Fullscreen" value="true"  />

Is there any other way to solve this issue?

Here is the photo of the issue:

![screenshot_2015-01-28-19-23-20](https://cloud.githubusercontent.com/assets/6784771/5944048/419db1e0-a724-11e4-88a0-a1cb2eb8b6a0.png)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Klapsa2503!

We are now requiring all issues to be submitted through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3000) so that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3000)**

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by mhartington** [comment]
This is one of the quirks that android has. 

http://ionicframework.com/docs/api/page/keyboard/

You could adjust the `android.manefest` file in the `platform/android/` directory and change the keyboard activity to this.

```
 <activity android:windowSoftInputMode="adjustResize">
```

The other option is to let the tabs sit on top, as per their paltform design, and pass a input in the nav-title.

http://ionicframework.com/docs/api/directive/ionNavTitle/
