### ISSUE TITLE
bug: Strange scroll bar apppears on ion-tabs

### ISSUE THREAD

**Issue by Klapsa2503** [driftyco/ionic#3001]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Strange scroll bar appears on ion-tabs, you can see this on the photo below:

![aaaaa](https://cloud.githubusercontent.com/assets/6784771/5944051/45f771c2-a724-11e4-8083-4a79c2061cd7.jpg)

It happens only from time to time when I navigate in app using default navigation.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Klapsa2503!

We are now requiring all issues to be submitted through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3001) so that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3001)**

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by Klapsa2503** [comment]
Application complexity seems to be the problem.
