### ISSUE TITLE
semantically incorrect/incomplete documentation code

### ISSUE THREAD

**Issue by EddyF** [driftyco/ionic#3002]
Missing closing div on http://ionicframework.com/docs/components/#striped-style-tabs
Should I submit a PR for that?

**Comment by Ionitron** [comment]
Greetings @EddyF!

We are now requiring all issues to be submitted through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3002) so that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3002)**

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by mhartington** [comment]
Looks good to me

```html
<div class="tabs-striped tabs-top tabs-background-positive tabs-color-light">  
  <div class="tabs">
      <a class="tab-item active" href="#">
        <i class="icon ion-home"></i>
        Test
      </a>
      <a class="tab-item" href="#">
        <i class="icon ion-star"></i>
        Favorites
      </a>
      <a class="tab-item" href="#">
        <i class="icon ion-gear-a"></i>
        Settings
      </a>
    </div>
  </div>

  <div class="tabs-striped tabs-color-assertive">
    <div class="tabs">
      <a class="tab-item active" href="#">
        <i class="icon ion-home"></i>
        Test
      </a>
      <a class="tab-item" href="#">
        <i class="icon ion-star"></i>
        Favorites
      </a>
      <a class="tab-item" href="#">
        <i class="icon ion-gear-a"></i>
        Settings
      </a>
    </div>
  </div>
```

**Comment by EddyF** [comment]
Mmm strange, looks fine now!
perhaps I overlooked (even tho I checked 100times before posting)
whichever case I'm closing this, cheers.
