### ISSUE TITLE
bug: $ionicModal show/hide causes event handler leak

### ISSUE THREAD

**Issue by hravnx** [driftyco/ionic#3004]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In `ModalView.show()` an anonymous `resize` event handler is registered. 

Later on, in `ModalView.hide()`, the `resize` event is removed, using `null` as the callback argument to `ionic.off()`. 

This does _not_ remove the event handler, causing the `resize` handler to be called a growing amount of times as the modal is shown/hidden.

The correct way of doing this is to use a named function as the callback argument.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @hravnx!

We are now requiring all issues to be submitted through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3004) so that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3004)**

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @hravnx!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
