### ISSUE TITLE
$ionicView.loaded inside ionicModal

### ISSUE THREAD

**Issue by alvaromb** [driftyco/ionic#3009]
Does ``ion-modal-view`` have a method to listen like ``ion-view``'s ``$ionicView.loaded``?

Do we have to use ``modal.shown`` instead?

Thanks.

**Comment by Ionitron** [comment]
Greetings @alvaromb!

We are now requiring all issues to be submitted through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3009) so that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3009)**

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @alvaromb!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
