### ISSUE TITLE
bug: I can't use ion-slide directive with ng-repeat

### ISSUE THREAD

**Issue by zeev-storemaven** [driftyco/ionic#3016]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>If I use ng-repeat inside "ion-slide-box" I got an js error:

>> Controller 'ionSlideBox', required by directive 'ionSlide', can't be found!

In order to temporary fix this issue we forked an ionic to:
https://github.com/StoreMaven/ionic/tree/storemaven-fix

In this branch we just removed the "require: '^ionSlideBox'" statement in "ionSlide" directive

Of course it is not a proper solution. Can you help us with the issue?</span>

<span is-issue-template></span>

**Comment by wodka** [comment]
Hi, 

it is working for me - at least if you are not trying to have the "loop" functionality working.

```
<ion-slide-box slide-interval="500" auto-play="true" show-pager="false">
    <ion-slide ng-repeat="article in latestArticles">
      {{article.name}}
    </ion-slide>
</ion-slide-box>
```

I found out that this commit never made it to master -> https://github.com/driftyco/ionic/commit/2ab776023d571d57d9b8a1d7878904b24b1364f8

**Comment by Ionitron** [comment]
Greetings @zeev-storemaven!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
