### ISSUE TITLE
perf: Seed projects take foreover due to extremely slow speed of github.com pull, push outside USA

### ISSUE THREAD

**Issue by vikrantrathore** [driftyco/ionic#3019]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Trying to use ionic from Singapore with a extremely fast 100 mbps fibre connection. When try to initiate a ionic project using either:
ionic start project_name blank
ionic start project_name tabs
ionic start project_name sidemenu
It takes foreover to initialize the project and its always stuck at:

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=                            ]  6%  1994.4s

I complained about the speeds to github.com support staff and they mentioned they cannot do anything about it since their target market is USA and its only optimized for that market. For other markets they need to rely on their own services.

I wanted to use ionic outside of USA and the speeds are very very slow to a point that seed projects are unusable. 

Needed to wait for 3-4 hours for one seed project to initialize due to slow github.com speeds. Indeed other sides are working very well that includes watching HD quality videos, which are much bigger bandwidth hungary then source code.

**Is it possible if ionic cli can have option or configuration option to use some other service either local github repository or kiln or bitbucket.org for seed projects?**

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vikrantrathore!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3019). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3019)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic-cli#239
