### ISSUE TITLE
tabs bug

### ISSUE THREAD

**Issue by Jaware** [driftyco/ionic#3020]
on pc,the tabs stay  below,however when browsed on android 4.4 chrome brower,it run on the top,why?i m very confused
![s50203-201129-001_](https://cloud.githubusercontent.com/assets/3970304/6019980/2bc1e15e-abe1-11e4-9328-960f7714e027.jpg)

**Comment by Ionitron** [comment]
Greetings @Jaware!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3020). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3020)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This is part of our platform specific configurations. On iOS, tabs will appear at the bottom and on Android, tabs will appear below the nav-bar.

http://ionicframework.com/docs/nightly/api/provider/$ionicConfigProvider/

This can be configured though.
Added to the docs via https://github.com/driftyco/ionic/commit/a7b894447912c03274625942cab4c4bdf345a7e0

**Comment by Jaware** [comment]
ok，but can the line behind the title be removed? the android chrome show the line(pc show too),but the android system browser not(this is what i want)


![qq 20150204165834](https://cloud.githubusercontent.com/assets/3970304/6037493/0b2c246e-ac8f-11e4-93e5-9de621b769a1.jpg)
