### ISSUE TITLE
bug: Loading getting stuck when `hideOnStateChange` and delay are both used

### ISSUE THREAD

**Issue by vladipus** [driftyco/ionic#3022]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Fix here: https://github.com/driftyco/ionic/pull/3021</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vladipus!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3022). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3022)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by vladipus** [comment]
Demo: http://codepen.io/vladius/pen/bNoZyW
