### ISSUE TITLE
Programmatically visiting a new sidemenu item embeds view in nav hierarchy

### ISSUE THREAD

**Issue by listrophy** [driftyco/ionic#3024]
This one is hard to explain, so here's a [codepen](http://codepen.io/anon/pen/gbGOma?editors=101). Basically, I'm using a pretty stock version of the side-menu starting template. I add an icon to the side menu navbar that creates a sidebar item, then immediately shows it in the main content area. The problem is that this new main content is pushed onto the current navigation stack, rather than replacing the current root navigation view.

To view the behavior:

1. Tap the Burger menu
2. Tap the "+" (normally, you might be asked to name the new thing. To simplify bug-reporting, that's omitted here)
3. Notice that, in the main content area, there is now a back button to "Playlist." This should not happen.

**Comment by Ionitron** [comment]
Greetings @listrophy!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3024). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3024)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by beauby** [comment]
The behavior you're witnessing is the "normal" behavior of links, that is somehow prevented in the case of links inside a side-menu. I investigated this for a bit but could not find what makes the side-menu links replace the view instead of pushing it onto the nav stack. Understanding this would be a good start, and I'd appreciate any pointers.

**Comment by listrophy** [comment]
@beauby I'm kinda new to the platform, so pardon my ignorance on this particular point, but....

I would think that pushing onto the navigation stack would result in a URL path that looks like this: `/rootModel/:rootModelId/secondaryModel/:secondaryModelId`. That's my intuition, at least. In my case, I'm very specifically going to just a different `/rootModel/:otherRootModelId`. That's what makes me think that this is a bug rather than PEBKAC.

**Comment by beauby** [comment]
@listrophy This is not how angular.js works. Angular itself has no actual history service, as it is expected to be handled by the browser. In angular, there are just states that you can transition between. This is where ionic comes into play with its own history service, mimicking the browser's.

**Comment by mhartington** [comment]
Similar to https://github.com/driftyco/ionic/issues/3025

Closing.
