### ISSUE TITLE
bug: `menu-close` doesn't work, when the state transition is delayed

### ISSUE THREAD

**Issue by vladipus** [driftyco/ionic#3027]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The `menu-close` attribute doesn't work, when the state transition is delayed due to `resolve`.

# Demo
http://codepen.io/vladius/pen/VYMVNw
The back button should be hidden when transitioning to attendees, but it's not. The menu button should be shown, but it's not.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vladipus!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3027). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3027)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by anjum121** [comment]
Any luck on this bug

**Comment by ackerdev** [comment]
@adamdbradley Can you possibly give an explanation of the reasoning behind the changes in bba9e79?

I'd like to help get this resolved as it's a fairly large issue to using the ionic sidemenu, but without some context for why those changes exist in the first place I'm not sure what we can do to solve this and not break whatever that fixed.

**Comment by vladipus** [comment]
Updated my previous fix for current Ionic: https://github.com/driftyco/ionic/pull/3892

**Comment by mhartington** [comment]
Looking into this.

**Comment by mhartington** [comment]
Just merged a fix into our 1.0.1 branch. Would you be able to pull that down and it it out.

**Comment by vladipus** [comment]
If you're talking to me on this, I'm already using this in a production beta-testing stage environment.
