### ISSUE TITLE
Uncaught ReferenceError: extend is not defined ionic.js

### ISSUE THREAD

**Issue by jonlil** [driftyco/ionic#3028]
https://github.com/driftyco/ionic/blob/658d539e1699f3ce351df0de7f82b6053cbd5e6d/js/views/listView.js#L176

The error exists in your demo from the docs
http://ionicframework.com/docs/nightly/api/directive/ionList/

**Comment by Ionitron** [comment]
Greetings @jonlil!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3028). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3028)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jonlil** [comment]
I don't want to connect my github account and share my organization data so you have to live with it

**Comment by jonlil** [comment]
easy solution for anybody also having this trouble

```js
window.extend = angular.extend;
```
