### ISSUE TITLE
problem in install plugin in ios 

### ISSUE THREAD

**Issue by roysG** [driftyco/ionic#3031]
Hi,
no matter which plugin i am trying to install, the installation can not create folder on the ios.
The only one solution i found , is to download the project of the plugin from github repsitory and copy it manually.

please assist.
I can׳t install facebook sdk because of that problem.
https://github.com/Wizcorp/phonegap-facebook-plugin

i type:
cordova -d plugin add /Users/Admin/Downloads/phonegap-facebook-plugin-master22 --variable APP_ID="some_app_id" --variable APP_NAME="picktags"

and i get error:
Command finished with error code 0: /Users/Admin/www/picktags.com/public_html/pickApp/hooks/after_plugin_add/010_register_plugin.js /Users/Admin/www/picktags.com/public_html/pickApp

**Comment by Ionitron** [comment]
Greetings @roysG!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3031). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3031)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @roysG!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
