### ISSUE TITLE
bug: update a project not updating angular-ui-router

### ISSUE THREAD

**Issue by kno** [driftyco/ionic#3032]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>After updating a project I've this situation:

$ionic lib
Local Ionic version: 1.0.0-beta.14 ./www/lib/ionic/version.json)
Latest Ionic version: 1.0.0-beta.14 (released 2014-12-15)

Local version up to date 

$ head ./www/lib/ionic/js/angular-ui/angular-ui-router.js /**
State-based routing for AngularJS
@version v0.2.10
@link http://angular-ui.github.com/
@license MIT License, http://www.opensource.org/licenses/MIT */
/* commonjs package manager support (eg componentjs) */
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @kno!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3032). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3032)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic-cli#232
