### ISSUE TITLE
bug: $ionicHistory.clearCache(); with collection-repeat and ng-repeat

### ISSUE THREAD

**Issue by cyprusglobe** [driftyco/ionic#3033]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When using $ionicHistory.clearCache(); with collection-repeat
when clicking on an item and going to detail view then hitting the back button i get a black screen im using $ionicHistory.clearCache();
like this
```
  $scope.$on('$ionicView.afterLeave', function(){
    $ionicHistory.clearCache();
  });
  $scope.$on('$ionicView.beforeEnter', function(){
    $ionicHistory.clearCache();
  });
  $scope.$on('$ionicView.beforeLeave', function(){
    $ionicHistory.clearCache();
  });
  $scope.$on('$ionicView.afterEnter', function(){
    $ionicHistory.clearCache();
  });
```

in my mainCtrl

if i need to provide a codepen i can do that</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @cyprusglobe!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

**Comment by cyprusglobe** [comment]
Codepen here

http://codepen.io/anon/pen/azVvRQ

Steps to reproduce the issue

click on an item in the collection-repeat then hit the back button and you will get a black screen.

**Comment by cyprusglobe** [comment]
@ajoslin any word on this?

**Comment by adamdbradley** [comment]
I wouldn't recommend clearing the before you enter, but rather after you leave.

**Comment by cyprusglobe** [comment]
@adamdbradley Thanks, for the suggestion :)
