### ISSUE TITLE
bug: $state.go(to [, toParams] [, options]) dropping toParams

### ISSUE THREAD

**Issue by matthieubulte** [driftyco/ionic#3039]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

I'm trying to implement in my application a login mechanism based on an `authenticationService` that let me check the current authentication status (`authenticated`, `unauthenticated`).

The idea is then that on each `$stateChangeStart` I want to check what is the current authentication status, and if the user is not `authenticated` he should be redirected to the login page to login. But what I want is that once the login is confirmed, the user should be redirected to the page we initially intended to visit.

To keep track of the page the user wanted to visit, I wanted to make a state transition to `login` with the `desiredState` as a parameter, implemented as following:

```
$rootScope.$on('$stateChangeStart', function (event, toState, toParams, fromState, fromParams) {
    var status = authService.getState();
    var to = toState.name;

    if(to !== 'login' && status === 'unauthenticated') {
        $state.go('login', { desiredState: to });
        event.preventDefault();
        return;
    }
});
```

So what I want is:

user tries to access state `xxx` -> user is not logged in, user redirected to 'login' with `toParams = { desiredState: 'xxx' }` -> user logs in -> server confirms -> loginController reads from `$stateParams` the `desiredState` and redirects to it -> user is on `xxx`

Now the problem is that in the next `$stateChangeStart` (the one to go to the `login` state), the `toParams` parameter is empty.

I tried to track down the reason, and it seems to come from:
`$state.transitionTo()` at `toParams = toState.params.$$values(toParams);`
because `$$values` seems to use `$$keys` which returns in my case an empty array. But I think this isn't the correct behaviour.

Now unfortunately I don't have time to dive deeper and fix this bug, but I hope you will find the time to fix it or to indicate my misuse of the framework.

Thanks</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @matthieubulte!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3039). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3039)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Sorry but this is how ui-router has been designed, and is what Ionic uses for its routing.
