### ISSUE TITLE
bug: Modal CSS bug with WKWebView

### ISSUE THREAD

**Issue by kas84** [driftyco/ionic#3040]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>When using the new WKWebView on iOS 8 modals in landscape show up like this:
![ionic css bug](https://cloud.githubusercontent.com/assets/5584/6079347/5b58a34c-ae04-11e4-8630-3571381caa10.PNG)

I'm using the following plugin: https://github.com/Telerik-Verified-Plugins/WKWebView . Any ideas?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @kas84!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3040). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3040)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ajoslin** [comment]
iOS, whyyyyyy?!

**Comment by Ionitron** [comment]
Greetings @kas84!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
