### ISSUE TITLE
feat: ionic-ion-autoListDivider

### ISSUE THREAD

**Issue by andrewmcgivery** [driftyco/ionic#3044]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>https://github.com/andrewmcgivery/ionic-ion-autoListDivider

Any interest in merging this ion into core or does it make sense to leave it as a separate module?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @andrewmcgivery!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3044). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3044)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by cyprusglobe** [comment]
+1

**Comment by mhartington** [comment]
Probably best at the moment to keep this as a separate ion.
