### ISSUE TITLE
perf: ionic setup sass

### ISSUE THREAD

**Issue by mifama** [driftyco/ionic#3049]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I updated the ionic version to last version, and now when I do 'ionic setup sass' it's return 
![npm install](https://cloud.githubusercontent.com/assets/9626717/6089152/91687b1a-ae5e-11e4-819c-47f96ecdb2d4.PNG)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mifama!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3049). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3049)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic-cli#234
