### ISSUE TITLE
feat: `hideOnStateChange` should also hide on state change error

### ISSUE THREAD

**Issue by vladipus** [driftyco/ionic#3051]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Not exactly a bug maybe, but when the state change fails, the loading screen remains on screen and so the app gets stuck. The `$stateChangeError` should also be listened to, to hide the Loading, when the `hideOnStateChange` flag is used.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vladipus!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3051). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3051)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Can you provide an example of this in a codepen?

**Comment by vladipus** [comment]
here you go http://codepen.io/vladius/pen/ByxdYa

**Comment by mhartington** [comment]
You can use the `duration` option

http://ionicframework.com/docs/api/service/$ionicLoading/

http://codepen.io/mhartington/pen/KwRvLm

**Comment by vladipus** [comment]
Thank you for your advice. However, I can't accept is as a solution for two reasons: 1) if the natural non-error delay will be greater than this value, the loading screen will mistakenly be hidden. 2) if the error happens a lot earlier than the delay value, the user will have to wait unreasonably.

I've already fixed the issue in my local ionic modification. it is as easy as handling an error like this, in parallel to `$stateChangeSuccess` handler: `deregisterStateErrorListener = $rootScope.$on('$stateChangeError', hideLoader);`

I can't really see any argument against hiding the loading screen on errors, when the `hideOnStateChange` is set, can you?
