### ISSUE TITLE
bug: unable to properly install cordova 4.2.0 on OSX 10.9.5

### ISSUE THREAD

**Issue by gtick** [driftyco/ionic#3052]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>command: sudo npm install -g cordova
cordova ver# 4.2.0
OSX ver# 10.9.5

ERRORS:

npm WARN engine npm@1.4.28: wanted: {"node":">=0.8","npm":"1"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine cordova-js@3.7.3: wanted: {"node":"~0.10.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
/usr/local/bin/cordova -> /usr/local/lib/node_modules/cordova/bin/cordova
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/unzip/node_modules/pullstream requires readable-stream@'~1.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/unzip/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.0.27-1
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/unzip/node_modules/match-stream requires readable-stream@'~1.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/unzip/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.0.27-1</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @gtick!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3052). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3052)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic-cli#240
