### ISSUE TITLE
bug: Platform not being detected on Android

### ISSUE THREAD

**Issue by kaumac** [driftyco/ionic#3056]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi! First of all, I've read the contributing guidelines and I know that I should make a codepen or similar demonstrating the problem, but since this is a platform issue, I can't demonstrate the problem there.

Basically, when running my app on my Android (a 1st gen Moto X), the platform doesn't seem to be recognized as Android. The splash screen doesn't show up, the tabs show on top instead of the bottom, and so on.

There is a repo with my code, but it's pretty much the Tabs scaffold app, I basically changed text and color on tabs.
https://bitbucket.org/hospedou/guest_app

I'm using Phonegap Build service to build the apk and download it on my Android, if it makes any difference.

Also, when testing on iOS it seems to work just fine (splash screen works just fine, the tabs are on top as expected).

Thanks!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @kaumac!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3056). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3056)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Just tested this on a motoX in genymotion, seems to be working for if I build locally.
I think the issue with the tabs not getting applied correctly is that PGB doesn't have hooks that you can have access to, if you upload a build to the site. 

So `hooks/after_prepare/01_add_platform_class.js` doesn't execute, which is where we're getting the platform specific classes. Can you build locally and confirm this?

**Comment by kaumac** [comment]
Hey @mhartington thx for checking on that. I just tried building it locally and in fact it works perfectly.
I'm gonna stop using PGB then, thx for the help!
