### ISSUE TITLE
bug: Bug: Ionic-1.0.0-beta14 - Parse error for lines with $attr.class on Android 2.3

### ISSUE THREAD

**Issue by revie** [driftyco/ionic#3062]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>2.x</span>  <span ionic-webview>webview</span>

<span ionic-description>Running the latest Beta 14, I ran into the following error when running on Android 2.3:

D/CordovaLog(  349): file:///android_asset/www/lib/ionic/js/ionic.bundle.js: Line 46718 : SyntaxError: Parse error
E/Web Console(  349): SyntaxError: Parse error at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:46718

which appears to be this line:

    var headerBarEle = jqLite('<ion-header-bar>').addClass($attrs.class).attr('align-title', alignTitle);

and first reported by akhil in the Forum at:

http://forum.ionicframework.com/t/ionic-beta-14-gives-js-error-in-android-emulator/15474/5

Apparently, older versions of Android don't like "$attrs.class", as first identified last year:

https://github.com/driftyco/ionic/issues/1228

Changing "$attrs.class" to "$attrs['class']" in the Ionic bundle seems to have fixed the problem for me, with no side effects in the other versions of Android and iOS I'm testing in.  Should this same change be integrated back into the source tree for others who may be experiencing the same problems?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @revie!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3062). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3062)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
