### ISSUE TITLE
bug: No Backdrop Shades In Modals Anymore

### ISSUE THREAD

**Issue by vladipus** [driftyco/ionic#3067]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I can't really understand, why this change was made:
https://github.com/driftyco/ionic/commit/5de1c1266d734d9fd904401d2509853a4a762101

My 1080p device won't show the backdrop, even in a landscape orientation!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vladipus!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3067). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3067)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by vladipus** [comment]
I know understand why this happened. On small, non-tablet displays the dialog just occupies the whole space. However, I'm more interested in this to work correctly (with the backdrop): http://codepen.io/anandvj/pen/KwmMGY
If you minify the viewport during the image view, the backdrop is just gone.

**Comment by vladipus** [comment]
I suggest adding an option to add specific class to the backdrop, something like `backdropClass` 
For now, I'm adding a specific class like this:

    $ionicModal.fromTemplateUrl('template.html', {
        scope: $scope,
        animation: 'slide-in-up',
        // I suggest this: backdropClass: 'showcase'
    }).then(function(imageModal) {
        $scope.imageModal = imageModal;
        // For now doing this:
        angular.element($scope.imageModal.el).addClass('showcase');
    });

**Comment by Ionitron** [comment]
Greetings @vladipus!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
