### ISSUE TITLE
feat: Installing cordova

### ISSUE THREAD

**Issue by awomtm** [driftyco/ionic#3068]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>$ npm install -g cordova
npm WARN engine cordova-js@3.7.3: wanted: {"node":"~0.10.x"} (current: {"node":"
0.12.0","npm":"2.5.1"})
npm WARN engine npm@1.4.28: wanted: {"node":">=0.8","npm":"1"} (current: {"node"
:"0.12.0","npm":"2.5.1"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"0.12.0","npm":"2.5.1"})
C:\Users\MTM\AppData\Roaming\npm\cordova -> C:\Users\MTM\AppData\Roaming\npm\nod
e_modules\cordova\bin\cordova
cordova@4.2.0 C:\Users\MTM\AppData\Roaming\npm\node_modules\cordova
├── underscore@1.7.0
├── q@1.0.1
├── nopt@3.0.1 (abbrev@1.0.5)
└── cordova-lib@4.2.0 (valid-identifier@0.0.1, osenv@0.1.0, properties-parser@0.
2.3, bplist-parser@0.0.6, mime@1.2.11, unorm@1.3.3, semver@2.0.11, shelljs@0.3.0
, dep-graph@1.1.0, rc@0.5.2, through2@0.6.3, npmconf@0.1.16, xcode@0.6.7, glob@4
.0.6, d8@0.4.4, elementtree@0.1.5, tar@1.0.2, request@2.47.0, plist@1.1.0, cordo
va-js@3.7.3, npm@1.4.28)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @awomtm!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
