### ISSUE TITLE
bug: Mouse-scrolling does not work on Microsoft Surface Tablet and Microsoft PPI devices

### ISSUE THREAD

**Issue by wkleinheerenbrink** [driftyco/ionic#3069]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Knowing Microsoft-devices aren't supported, I did find a bug on the Surface Tablet / PPI device. After connecting a mouse to the devices, it is not possible to scroll using the mousewheel or using a 'drag'-method.

We did find the cause in [scrollView.js#L807](https://github.com/driftyco/ionic/blob/e8a70f3701f5676837d5b48397eaa539b5ee61a7/js/views/scrollView.js#L807). This check (`'ontouchstart' in window`) evaluates to `true` on Surface Tablets and PPI-devices. In this case the script will only bind touch events, ignoring `mousewheel`, `mousedown` etc.

I guess this is also an issue on Android tablets that support an external mouse, like the Asus Transformer.

We are working on a patch already.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @wkleinheerenbrink!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3069). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3069)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @wkleinheerenbrink!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
