### ISSUE TITLE
bug: JS SyntaxError on v1-0-0-beta-14-nightly-998

### ISSUE THREAD

**Issue by luchusnet** [driftyco/ionic#3070]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>2.x</span>  <span ionic-webview>webview</span>

<span ionic-description>02-05 16:22:26.445: D/CordovaLog(14066): file:///android_asset/www/js/libs/ionic/js/ionic.bundle.js: Line 23905 : Uncaught SyntaxError: Unexpected token finally

on android version 2.3x</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @luchusnet!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3070). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3070)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adamdbradley** [comment]
I'm unable to get this error on Android 2.3. Could you fork one of these [codepens](http://codepen.io/ionic/public-list/) and describe how to get the error to show up? Thanks

**Comment by luchusnet** [comment]
Use codepens its complicated because our project ( a social network ) uses several " plugins" and depends on several http services that should be mocked.

But looking the line with the error, noticed that ".finally" is reserved sentence. Then I found this post:

https://github.com/kriskowal/q/issues/200

Then I changed the original line of ionic.bundle.js 23919: .finally (function () by ["finally"] (function () and it worked!

I guess "finally" is a reserved name can not be used as a method in some android browsers.

The phone I used is:

Samsung GT-S5360L
Android version: 2.3.6

So, this is a bug?

**Comment by adamdbradley** [comment]
I'm not finding a `.finally` anywhere in this file: http://code.ionicframework.com/1.0.0-beta.14/js/ionic.bundle.js

It sounds like it was original within Angular, and angular recently fixed it. Would you be able to find the line you're having the problem with using one of our versions on the CDN? Thanks

**Comment by luchusnet** [comment]
Sorry, its in nightly: 1-0-0-beta-14-nightly-998

**Comment by adamdbradley** [comment]
Great catch! I'll take a look, thanks!

**Comment by adamdbradley** [comment]
I added a temporary fix until angular fixes it: https://github.com/driftyco/ionic/commit/1f2d900e3c3e0845a6a7a03db9e5652a29dea7bd

thanks
