### ISSUE TITLE
bug: Popover and Tall Collection Repeat Items

### ISSUE THREAD

**Issue by uofmmike** [driftyco/ionic#3074]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>
http://codepen.io/mmullins/pen/LEOJPo/
To repeat, click the "open flag" button a few times, and scroll around a bit if it doesn't error out right away.

If i have a tall collection repeat item, it appears popover does not know where to place the popover?

I've taken a boilerplate collection repeat, made the heights taller, and see it in any view, fullscreen, or otherwise.

(basic idea is to have a popover to flag content inside collection-repeat style cards)

Also, keeping it positive here - thank you guys for your work on this awesome framework!

Links:
Similar, but not the same: 
https://github.com/driftyco/ionic/issues/3047

Ionic Forum Link:
http://forum.ionicframework.com/t/popover-and-tall-collection-repeat-items-bug/17325
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @uofmmike!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3074). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3074)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ajoslin** [comment]
The codepen URL doesn't work for me.

**Comment by uofmmike** [comment]
http://codepen.io/mmullins/pen/LEOJPo/

missing a trailing slash, sorry about that! (I updated the initial post as well)

**Comment by uofmmike** [comment]
http://codepen.io/mmullins/pen/LEOJPo/
Sorry about that, was missing a trailing slash

Mike Mullins
m.v.mullins@gmail.com

**Comment by ajoslin** [comment]
OK, not able to get any bugs to happen besides what's in #3047. Were you talking about that?

**Comment by ajoslin** [comment]
Just left a comment on #3047.

**Comment by uofmmike** [comment]
Didn't realize it was just a popup problem, only noticed it in collection-repeat, thank you for the fix!
