### ISSUE TITLE
bug: Incorrect Event target on virtual events

### ISSUE THREAD

**Issue by Tomino2112** [driftyco/ionic#3078]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>There is problem with events such as drag, swipe etc. that they do not update their event target, instead they hold the initial target. 

Thankfully there seems to be quite straight forward solution that helped me:
http://stackoverflow.com/questions/3918842/how-to-find-out-the-actual-event-target-of-touchmove-javascript-event

my implementation: 
document.elementFromPoint(e.gesture.center.pageX,e.gesture.center.pageY);

Maybe you might consider implementing this by default into the target of e.gesture object? I wouldn't change the e.target since its browser default, but gesture is added by you or hammer, so I think it would be good place to implement this fix so we devs dont have to worry about it.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Tomino2112!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3078). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3078)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @Tomino2112!

Thank you for the feature request. The humans and I will review this further and possibly add it to our [Feature Request](https://trello.com/b/nNk2Yq1k/ionic-framework) board, if we feel it is appropriate for Ionic.

Thank you for allowing me to assist you.
