### ISSUE TITLE
bug: start-y="" attribute not working at all

### ISSUE THREAD

**Issue by maketroli** [driftyco/ionic#3079]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>As per request of one of your guys on Ionic Forum I am opening this issue:

I want to achieve [this behavior](http://codepen.io/ionic/pen/sDdpG), the search box hidden in the header until you scroll up at the top, I just apply that on my html but I do not know why is not working
Ionic version: ```"ionic": "driftyco/ionic-bower#1.0.0-beta.14"```
```html
<ion-view title="Sports" cache-view="false" hide-back-button="true">
  <ion-nav-buttons side="left">
    <button menu-toggle="left"
                 class="button button-icon icon ion-navicon"></button>
  </ion-nav-buttons>
  <ion-nav-buttons side="right">
    <button class="button button-icon icon ion-more"
                 ng-click="displaySportSelectionModal()"></button>
  </ion-nav-buttons>

  <!--Here is the start-y I am talking about-->
  <ion-content start-y="55" class="has-footer" has-footer="true">
      <div id="search-box" class="bar bar-header item-input-inset">
        <div class="item-input-wrapper">
          <i class="icon ion-ios7-search placeholder-icon"></i>
          <input type="search" placeholder="Search"
                     ng-model="data.searchQuery">
          <i class="clear-search icon ion-ios7-close-empty"
              ng-click="clearSearch()"></i>
        </div>
        <button class="button button-clear">
          Cancel
        </button>
      </div>
```

[here is the question I did on your Forum](http://forum.ionicframework.com/t/why-my-start-y-55-is-not-working/17391)
hope you guys can help</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @maketroli!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3079). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3079)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by paishin** [comment]
I have the exact same problem trying to implement the exact same layout :) What I have found is that if the containing element's height in ion-content are grater than its height (a scroll bar would be visible) then start-y does work but if there is not enough content then start-y is ignored.

**Comment by paishin** [comment]
As a temporary workaround I have added a div inside ion-content that has the same height as ion-content+start-y in order to ensure start-y works.

Doing so does solve the problem but I now face another problem where content is loaded at 0,0 position and then jumps to 0,y making the search field visible for a second before jumping to the right position.

**Comment by mattchue** [comment]
I too am having this issue. Just chiming in so it's known that this should be fixed.

**Comment by perrygovier** [comment]
This is working fine for me. The odd behaviour of the codepen was from an unused `ion-nav-bar`
http://codepen.io/perrygovier/pen/LErQGX?editors=101

**Comment by maketroli** [comment]
@perrygovier it depends on which version of Ionic you are working on. Also, your example is very different, where are the ```ion-nav-button```s and all that stuff ? could be because of the ```ion-view``` ? your example is so lazy, you are taking into consideration many many other possibilities

**Comment by perrygovier** [comment]
The codepen was from your example.

Here's a more intricate example. 
http://codepen.io/perrygovier/pen/LErQGX

If it's not a problem in the nightlies, the issue can be closed.
Let me know if you can reproduce the issue in the nightly version.
