### ISSUE TITLE
bug: Google places autocomplete does not work in current beta14

### ISSUE THREAD

**Issue by softBarbarian** [driftyco/ionic#3086]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>It seems that @mhartington's  solution in issue #1798 does not work anymore. I wonder if it is due to the fact that current version of angular does not recreate scopes and the directive that @mhartington has suggested does not add a needed `data-tap-disabled` attribute to google's dynamically genarated `pac-container` div.

Did someone figure out a solution?

Thanks .</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @softBarbarian!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3086). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3086)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by loomtronic** [comment]
@softBarbarian did you figure out a solution?

**Comment by softBarbarian** [comment]
Yes, sorry, should have adds some details. I used https://github.com/israelidanny/ion-google-place , just make sure to include both css file and js
