### ISSUE TITLE
perf: Put woff first

### ISSUE THREAD

**Issue by arcanis** [driftyco/ionic#3088]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

The woff format seems to be supported by every browser implementing the AppCache specification. Could it be possible to put this format first in the list of fonts, so that we are able to remove the other formats from the cache?

In the current state, since the eot format is the first one, there is two options : either cache the eot file (which would be useless for most browsers), or not cache the eot file (which would then delay the loading of the actual font in an IE browser, since the browser has to wait for the connection to timeout).
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @arcanis!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3088). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3088)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adamdbradley** [comment]
Yeah that's a good idea. We'll do some research and hopefully get that in. Thanks

**Comment by mhartington** [comment]
@arcanis do you have any resources for this? Been digging around and haven't been able to find some info on the subject, but haven't found anything that supports this.

**Comment by arcanis** [comment]
According to caniuse, the only browsers that [support appcache](http://caniuse.com/#search=appcache) but [do not support woff](http://caniuse.com/#search=woff) are the stock Android browser, 4.1 and 4.3. TTF is [also a good candidate](http://caniuse.com/#search=ttf), if the font is flagged as installable.

**Comment by adamdbradley** [comment]
I've been reading through this more and starting to wonder what the clear benefits are. Does the app or fonts load faster? I'd be afraid to change this around and have unexpected broken fonts, when what we have has proven to work across all devices. Do you have any benchmarks or data as to what the benefits are? For now I'd recommend just overriding our declaration.
