### ISSUE TITLE
Multi-theme colors?

### ISSUE THREAD

**Issue by machei** [driftyco/ionic#3091]
```html
<head>
    <link data-ng-href="css/main.css" rel="stylesheet" />    <!-- all usefull ex: padding, margin, text-align  -->
    <link data-ng-href="css/themes/darker.css" rel="stylesheet" />  <!-- Only dark colors -->
    <link data-ng-href="css/themes/lighter.css" rel="stylesheet" />    <!-- Only light colors -->
</head>
<body class='darker'>
```
I am using SCSS and trying to import stylesheets ionic.

```css
$light:                           #fff !default;
$stable:                          #f8f8f8 !default;
$positive:                        #387ef5 !default;
$calm:                            #11c1f3 !default;
$balanced:                        #33cd5f !default;
$energized:                       #ffc900 !default;
$assertive:                       #ef473a !default;
$royal:                           #886aea !default;
$dark:                            #444 !default;
@import "lib/ionic/scss/ionic";
```

And file has been compiled and imported more double sheets with two colors. Any Idea for cutting all collors?

**Comment by Ionitron** [comment]
Greetings @machei!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3091). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3091)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @machei!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
