### ISSUE TITLE
Doc: $ionicConfigProvider.navBar.alignTitle(value) wrong

### ISSUE THREAD

**Issue by piffie** [driftyco/ionic#3092]
Hi,

the doc states, that on android it defaults to center, but on our build it defaults to left on Android devices (easily testable with crome debugger)

cheers,
Christoph

**Comment by Ionitron** [comment]
Greetings @piffie!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3092). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3092)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Taken for the docs source,

 >`platform`: Dynamically choose the correct title style depending on the platform the app is running from. If the platform is `ios`, it will default to `center`. If the platform is `android`, it will default to `left`. If the platform is not `ios` or `android`, it will default to `center`.

It does state that android will default to left.
