### ISSUE TITLE
bug: Bug when going in a subview of a tab having an url name contained in another tab url.

### ISSUE THREAD

**Issue by mvidailhet** [driftyco/ionic#3093]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Here is a codepen describing the bug: http://codepen.io/mvidailhet/pen/azEjWL

I have 3 states:
- tabs.home: url = "/home"
- tabs.subview: url = "/addlist"
- tabs.add: url = "/add"

tabs.home and tabs.add are both tabs roots. tabs.subview is a subview of tabs.home.
If I click on the "Add list" button on the home tab, the app will select the Add tab and go to the add list subview without showing the content of the add list view. If you click on the home tab, it will "go back" to the add list view.

The problem comes from the url "/addlist" that contains the url of the tabs.add state. If you rename the url to "test" for example, it works as expected.

I also tested with the nightly build and the bug is still here.

Hope this helped.

Love your work</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mvidailhet!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3093). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3093)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @mvidailhet!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
