### ISSUE TITLE
Bug: $ionicNavBarDelegate.showBackButton() allways sets it to false

### ISSUE THREAD

**Issue by piffie** [driftyco/ionic#3096]
Hi,

Whenever i call that, it sets the state to false.... 
therefore i never can get the current state.
I needed to make my whole own handling to have a workaround on this.

the method https://github.com/driftyco/ionic/blob/master/js/angular/controller/navBarController.js#L375 sets it per default. the title method makes it correct.
https://github.com/driftyco/ionic/blob/master/js/angular/controller/navBarController.js#L395

pls fix this. thanks.

**Comment by Ionitron** [comment]
Greetings @piffie!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3096). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3096)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adamdbradley** [comment]
Would you be able to put together a codepen that replicates the issue and describes your problem better? Thanks

**Comment by piffie** [comment]
http://codepen.io/anon/pen/wByoPj

its from your demo. click on scientific facts and then there is a button "back button bug". When you click it, the button disappears... its explained in the line 75 of the js.

We want to make a release today, and i have to fix quite some weird behaviour since 14, so i'm sorry that its not a nice demo.

**Comment by hardywu** [comment]
same bug here.  + 1

**Comment by calendee** [comment]
This is definitely still happening even on RC2 and nightly.  

http://codepen.io/calendee/pen/MYRGLv

**Comment by calendee** [comment]
So more explanation:

The `$ionicNavBarDelegate.showBackButton()` method is supposed to either SET or GET the back button status.  If an optional argument is passed, it should set the back button status.  If not argument is passed, it should RETURN the back button status.

Right now, calling the method with no argument is setting the show property to false.

**Comment by calendee** [comment]
Here's my semi-working fix.  Instead of asking `$ionicNavBarDelegate` if the back button is showing,  I'm checking to see if there is a history view. 

```
return (! $ionicHistory.backView() ) ? true : false;
```

For my needs, it works.  However, there might be some scenarios where having a backview or not is not the same thing as showing a back button

**Comment by adamdbradley** [comment]
https://github.com/driftyco/ionic/commit/0936f78c307e284da9525a56634d5b5bb416d746

**Comment by calendee** [comment]
@adamdbradley I still don't think this is right.  Calling `$ionicNavBarDelegate.showBackButton()` is returning `undefined` instead of whether or not the back button is displayed.

Sample : http://codepen.io/calendee/pen/KpWeaJ

Open the console.  Tap the "Go To Checkin" button on the home page.  You'll see that we never get a valid result from the query.
