### ISSUE TITLE
bug: ng-click is firing twice on IE 11 (wp8)

### ISSUE THREAD

**Issue by MartinMa** [driftyco/ionic#3102]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>ng-click is firing twice on Internet Explorer 11 (Win 8.1).

See this [CodePen](http://codepen.io/anon/pen/ZYrpmj) to reproduce the issue.

With Windows Phone support on the horizon, this might become an issue.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @MartinMa!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3102). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3102)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by vjrantal** [comment]
This could potentially be merged with #2885?

**Comment by perrygovier** [comment]
Yeah, closing as a duplicate
