### ISSUE TITLE
bug: Disable multi-touch while dragging side-menu

### ISSUE THREAD

**Issue by thiphariel** [driftyco/ionic#3105]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi.

I think you should disable multi-touch while dragging a side menu to avoid changing tab while side menu is dragging.
You can try on this codepen : http://codepen.io/ionic/pen/vEdOVe
Keep your finger on the screen while dragging the side menu and you'll see you are able to change active tab.

Can you change this behavior ?
Thanks </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @thco!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3105). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3105)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Have you tested the nightly builds? 
This should be fixed.

**Comment by thco** [comment]
Hi @mhartington !

I'm sorry for the long delay. The ionic version used on this codepen is already took from nightlies ("//code.ionicframework.com/nightly/js/ionic.bundle.js") and I was able to reproduce this behavior.

Could you investigate a bit or tell me if I did something wrong ?

Thanks !

**Comment by mhartington** [comment]
Okay, seeing this too in my tests. Passing this to @adamdbradley.

**Comment by mhartington** [comment]
Okay, seeing this too in my tests. 

http://codepen.io/mhartington/pen/wBdORX

Passing this to @adamdbradley.

**Comment by wbhob** [comment]
Is this still an issue? If not, please close.
