### ISSUE TITLE
Swipe on item-list is not working not showing option button.

### ISSUE THREAD

**Issue by jariwalabhavesh** [driftyco/ionic#3106]
hi there,

I am developing application using ionic on windows phone 8.
First  issue that i face was scrolling, i was unable to scroll ion-list. I fixed it by putting overflow-scroll="true" attribute in "ion-content" tag, and list started to scroll. There is ion-list in my <ion-content> and each item has option buttons. 

By fixing my scrolling issue  i am not able to swipe list item. list-item is not swipping.

but when i remove overflow-scroll="true" from "ion-content" tag, then swipe start working for list item but scrolling stop working.

**Comment by Ionitron** [comment]
Greetings @jariwalabhavesh!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3106). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3106)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
We will not be supporting WP8X with ionic v1.
