### ISSUE TITLE
feat: Ionic releases should always use current Ionicons

### ISSUE THREAD

**Issue by DavidFrahm** [driftyco/ionic#3110]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Following on from #2679, I would like to see an intentional decision on whether or not to always use the latest Ionicons for Ionic releases.

For features that are baked into Ionic, such as back button and side menu, this seems necessary if we want developers to keep their apps' UI current, i.e., in sync with OS standards.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @DavidFrahm!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3110). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3110)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
