### ISSUE TITLE
feat: Need a Reset Password link for Ionic View app

### ISSUE THREAD

**Issue by lugotm** [driftyco/ionic#3111]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I recently created an Ionic View account via the app. After uploading several builds, the app suddenly logged me out and I could not remember what password I used and there isn't a link to reset a password.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @lugotm!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3111). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3111)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by lugotm** [comment]
I'll use the issue form instead.
