### ISSUE TITLE
bug: Keyboard Accessory Bar

### ISSUE THREAD

**Issue by ionixjunior** [driftyco/ionic#3113]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>
When **cordova.plugins.Keyboard.hideKeyboardAccessoryBar(false);** configuration is disabled, the nav buttons of the keyboard are shown when a input focused.

**The problem:** only on first time, when you change the input by nav button of the keyboard accessory without typing anything on this field, the nav button puts the focus on the same field. On the second click on nav button of the keyboard accessory the operation works perfectly.

I tested it with a Ionic Blank project. This behavior can be visualized on **Ionic View with App ID 3240667d**

Tested on simulator and device.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ionixjunior!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3113). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3113)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
