### ISSUE TITLE
feat: Popup body CSS overflow property

### ISSUE THREAD

**Issue by TheCodeDestroyer** [driftyco/ionic#3115]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi!

I was just wondering why does the `.popup-body` class have
the `overflow` property set to `scroll` and not to `auto`?
If there are some use cases it would be better if we can manually set the overflow,
via some property (if it's not already possible and I am just missing it)?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @TheCodeDestroyer!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3115). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3115)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
I'd recommend overriding the CSS if you have a use case where overscroll auto is better.

**Comment by isherwood** [comment]
I'm willing to override CSS as suggested, but I'm also curious about this decision. Do I risk breaking some obscure functionality if I do?
