### ISSUE TITLE
bug: Multiple scrolling in ion-slide-box with ion-conte

### ISSUE THREAD

**Issue by luclanet** [driftyco/ionic#3117]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>There is a problem using ion-scroll-box with a ion-content inside a slide.

http://codepen.io/anon/pen/VYQVNE

As you can test, the scroll moves also the vertical slide of the content creating a bad effect (it scrolls horizontally and vertically at the same time).

From beta 1 to beta 13 there wasn't this problem
Beta 1: http://codepen.io/anon/pen/ZYrmNe
Beta 13: http://codepen.io/anon/pen/pvaqzN

Thanks
Claudio</span>

<span is-issue-template></span>

**Comment by vlad-bezden** [comment]
I just checked and this issue still exists in v1 rc2. Any updates when is it scheduled to be fixed?

**Comment by bradlund** [comment]
Try RC3 - this commit fixed a similar issue i encountered:
https://github.com/driftyco/ionic/commit/db7f0eee0196c4108cbe37ef2351bd98889a3429

**Comment by Ionitron** [comment]
Greetings @luclanet!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
