### ISSUE TITLE
bug: Unable to enter text with hardware keyboard

### ISSUE THREAD

**Issue by oliversalzburg** [driftyco/ionic#3118]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a simple form with two text input fields. When I focus a field to enter text, no text will appear in the input when I type anything on the keyboard.

This is due to the fact that `ionic.scroll.isScrolling` is set to `true` and input will be ignored https://github.com/driftyco/ionic/blob/master/js/utils/keyboard.js#L241

I noticed this on a BlackBerry Q10, but I don't see why other devices with hardware keyboard wouldn't be affected as well.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @oliversalzburg!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by oliversalzburg** [comment]
@Ionitron I'm pretty sure that your sensor require re-calibrating.

**Comment by oliversalzburg** [comment]
The main issue here is in [`keyboardGetHeight`](https://github.com/driftyco/ionic/blob/master/js/utils/keyboard.js#L283), which assumes by default that keyboards are 275 units high.

What makes it even worse are all the places that check the `keyboardGetHeight` return value for falseyness, so using `0` doesn't even work :P

I've now resorted to setting `ionic.keyboard.height = 1;` in our code, which works around the issue for now.

**Comment by oliversalzburg** [comment]
Because I couldn't yet find a way to determine if a hardware keyboard is present, we're now setting `ionic.keyboard.height = 1;` on all platforms.

I wasn't able to detect any issues on Android, BlackBerry10, iOS and WindowsPhone8. So, I'm not quite sure where the return value of `keyboardGetHeight` has any relevance.

**Comment by Ionitron** [comment]
Providing a codepen and explaining in detail how to replicate the issue drastically helps.
