### ISSUE TITLE
bug: Reordering data pushes content off screen.

### ISSUE THREAD

**Issue by paulking00** [driftyco/ionic#3120]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have an ion-list with ion-items. Each ion-item has a checkbox attached.

Codepen: http://codepen.io/paulking00/pen/EaQMgg

Working Scenario:
=============
When a checkbox from an item is clicked, the item is moved to the end of the list programatically. For a working example, scroll down to the bottom (item 46 for example) and check the checkbox.

It only works correctly when the last item in the list is also on the screen.

Bug Condition:
==========
If the last item in the list is currently off the screen, the ion-list scrolls to the new position of the checked item (the bottom) and the rest of the content moves off the screen and cannot be scrolled to.

Bug Example:
==========
Check the checkbox of an item higher up on the list, where the bottom of the list cannot be seen (example item 3).</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @paulking00!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
