### ISSUE TITLE
bug: ui-view controller never called after first app installation/push

### ISSUE THREAD

**Issue by sp4ke** [driftyco/ionic#3122]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Currently working on a quite big app. I have a very strange problem on both platforms iOS and Android.

I have a login service that calls  `state.go` once the user is logged in, then redirects to the landing ui-view. Everything works fine with the app only for one particular scenario:

- If I uninstall the APP
- Then push a fresh package (iOS or APK)
- Then Login with facebook (Login works fine, then state.go is called)
- The controller of my landing view is never called, no logging works and no debugger stops inside. But when I inspect the ui-view and check the scope I find scope methods and empty scope objects, like scope objects were bound bet never initialized ! 

I tried setting a debugger on the `resolve` of the state, the resolve is called properly, but the controller is never called.

This problem only occurs the first time the package is installed, if I push the app again on the phone (without uninstalling), everything works as expected.

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @sp4ke!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3122). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3122)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Hmm, could you post some relevant code? 
Also, when you say ui-views, you mean `<ion-view>`?

**Comment by sp4ke** [comment]
I resolved this bug today. It am not sure it is a bug from ionic or ui-router. This was a special case where the controller was called then a redirection to an other state happening just after. The next time the view was visited the controller was already initiallized. I suppose this is related to some sort of caching happening in Ionic ? 

Here is a representation of the steps to reproduce the problem:

- We define two separate states A(login) and B(main view)
- When we launch the app it is automatically redirected to state B
- State B controller is initialized
- A $http interceptor catches some API errors and redirects to state A. 
- If we go go back to state B (after login) the state B controller is not initialized, since it already has when we launched the app. 


Is this a bug or a normal behavior of states and controllers ?

**Comment by mhartington** [comment]
Ahh alright, yeah so starting with beta 14, controllers are no long destroyed, but rather disconnected. So instead, we've provided some view-events that you can use.

http://ionicframework.com/docs/api/directive/ionView/

So in your case, you would want to use something like this.

```javascript
$scope.$on("$ionicView.enter", function(){
  // Anything that needs to happen
  // When the view becomes the active view
} 
```

With that, your situation would look like this.

 - We define two separate states A(login) and B(main view)
 - When we launch the app it is automatically redirected to state B
 - State B controller is initialized
 - A $http interceptor catches some API errors and redirects to state A.
 - We go back to state B (after login) and catch the functions inside the view-event.

Going to close this since as it wasn't an actual issue and has been resolved.

**Comment by sp4ke** [comment]
:+1:  Thanks for the explanation, it makes sense now since it was working before I made the upgrade. I should start reading the changelog before making upgrades
