### ISSUE TITLE
bug: InAppBrowser/Auth0 login getting stuck at window

### ISSUE THREAD

**Issue by KidA001** [driftyco/ionic#3123]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>6</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm using Auth0 for login. When I use ionic serve in the broswer, the login functions work just fine. When I'm emulating, I'm able to successfully login (checked auth0 logs) but the InAppBrowser is just a white page with 'OK' at the top right . See here: http://imgur.com/bniGKZM

My guess is that the inAppBrowser is not closing, would appreciate any help on this one.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @KidA001!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.

**Comment by KidA001** [comment]
Holy shit, the robot is right. Thank you
