### ISSUE TITLE
bug: Unsubscribe ionic listeners on angular init 

### ISSUE THREAD

**Issue by kirrg001** [driftyco/ionic#3128]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hey Ionic Team,

we ran into a problem while testing.

#### Requirements:
Ionic Beta 14
Karma 0.12.25
Karma Mocha 0.1.9

#### The Problem:
We register device ready event in our services:

````
app.service('ExampleSrvc', function(....) {
  $ionicPlatform.on('deviceready', function() {
    ...
  })
```


In my Test the following happens:


````
describe('test', function() {
  beforeEach(function() {
    module('example');
  })

  it('iteration1', function() {
     ...
     document.dispatchEvent(new Event('deviceready'));
  })

  it('iteration2', function() {
     ...
     document.dispatchEvent(new Event('deviceready'));
  })

  it('iteration3', function() {
     ...
     document.dispatchEvent(new Event('deviceready'));
  })
})
````


After each Iteration the angular module is re-bootstrapped, but the ionic listener (deviceready) is registered multiple times in the service. 

Why does ionic platform not unsubscribe if the angular module is bootstrapped/initialized?

do i need to unsubscribe the "deviceready" event on my own? 
(for example call ionic.off('deviceready', callback) on custom "app-destroy" event)?

should i rather report this issue to angular-mocks?

If i trigger events via $rootScope, angular automatically unsubscribe events. ($on, $broadcast)

Feel free to close the issue if its a duplicate.

Regards,
Kate</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @kirrg001!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3128). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3128)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @kirrg001!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
