### ISSUE TITLE
feat: Cache Should Be Turned Off By Default

### ISSUE THREAD

**Issue by vladipus** [driftyco/ionic#3129]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The cache functionality breaks a lot of controller's logic, including officially documented clean-up like this (http://ionicframework.com/docs/api/service/$ionicModal/ ):

    //Cleanup the modal when we're done with it!
    $scope.$on('$destroy', function() {
      $scope.modal.remove();
    });

The cache functionality may be useful for some offline apps, but it should not be on by default for sure. Otherwise, there is too much misunderstanding on how the app works especially for those, who just start to develop with Ionic.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vladipus!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3129). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3129)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
It is configurable and proven to increase performance.
