### ISSUE TITLE
feat: Enable tab viewes for swiping

### ISSUE THREAD

**Issue by hiquest** [driftyco/ionic#3134]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>This is like a way popular patter at least in android apps when you swipe view to the left/right and you get the tab switched. That would be a very nice feature. 

With something like 

```javascript 
<ion-tabs swipable='true' >
``` 

to activate it.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @hiquest!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3134). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3134)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by dylanvdmerwe** [comment]
Great suggestion! +1

**Comment by mhartington** [comment]
Moving this to our our trello board.
https://trello.com/c/dnCyi4wI/85-scrollable-tabs

**Comment by gustavodemari** [comment]
+1

**Comment by beauby** [comment]
+1

**Comment by jclalala** [comment]
+1

**Comment by TheJetlag** [comment]
+1

**Comment by hiquest** [comment]
I guess guys, since [this moved to trello](https://trello.com/c/dnCyi4wI/85-scrollable-tabs) there's no reason +1 this here, instead go to the trello board and upvote there
