### ISSUE TITLE
docs: Why does bower install angular although its already there in ionic-angular.js

### ISSUE THREAD

**Issue by ibewugb** [driftyco/ionic#3137]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi, I started a fresh ionic project. In this project I have angular in my www/lib/ folder named ionic-angular.js

Now I made a bower install and all the dependencies where installed: 
 "angular": "1.3.6",
 "angular-animate": "1.3.6",
 "angular-sanitize": "1.3.6",
 "angular-ui-router": "0.2.13"

My question is: why are there this dependencies? I dont need it, all I need is just my ionic-angular.js file to keep angular running.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ibewugb!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3137). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3137)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ajoslin** [comment]
Angular is **not** included in ionic-angular.js.

ionic-angular.js is just Ionic's angular code. We separated it back in the day when Ionic was not so coupled to Angular (now it is).

**Comment by beebase** [comment]
This is confusing. I installed lodash and suddenly also angular , animate, sanitize , ui-router appear as modules in the lib dir.
I assume ionic works without any dependencies on these angular modules, since these aren't there after a clean install. So why would these be added when installing  something like lodash, that has not dependencies on angular?

**Comment by mhartington** [comment]
No, these are dependencies ionic does use and are included in a fresh install.

https://github.com/driftyco/ionic-app-base/tree/master/www/lib/ionic/js

This is how bower works, it will take every package you want to install and have installed, and try to work out the dependencies between them. While lodash may not require anything, Ionic does, as [noted in our bower.json](https://github.com/driftyco/ionic-bower/blob/master/bower.json#L31), and since bower can't find those packages in the lib directory, bower will attempt to download them as well.

**Comment by beebase** [comment]
thanks. But what I still don't understand, is why these angular modules aren't in the www/lib dir after running 'ionic start app'. I would expect 'ionic start app'   to trigger bower and place the dependencies in the lib dir.

**Comment by mhartington** [comment]
True, but not everyone has bower installed or needs to. If we were to do that and people didn't have bower already installed, they would get an error :disappointed:

**Comment by beebase** [comment]
ah of course. I'm so used to bower. Thanks for clarifying.

**Comment by jdnichollsc** [comment]
See the following example @ibewugb http://blog.jonathanargentiero.com/avoid-angular-dependencies-download-on-bower-install-ionic/
