### ISSUE TITLE
$ionicBackdrop Holds and $ionicLoading

### ISSUE THREAD

**Issue by spectravp** [driftyco/ionic#3139]
$ionicBackdrop should add the following functionality:

1) It is possible to have -50 holds. This can make it impossible to get the backdrop to show. Should check to make sure that the hold count is never below zero. 
2) Should have a handler to force it close no matter how many holds their may be, resetting holds to zero.

$ionicLoading should have an optional callback handler to use with duration property that is called when the $ionicLoading instance auto-hides itself. At the very least, it should emit an event.

**Comment by Ionitron** [comment]
Greetings @spectravp!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3139). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3139)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @spectravp!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
