### ISSUE TITLE
[beta-14] ion-nav-bar bug

### ISSUE THREAD

**Issue by djhr** [driftyco/ionic#3145]
Hi guys,

After update ionic to beta-14, I notice that ion-nav-bar is not behaving correctly when has content inside (like buttons, inputs, etc...). 

See here an example:
http://codepen.io/anon/pen/wBmrze

Look at the following ionic css lines:
6968: [nav-bar-transition="ios"] [nav-bar="cached"] { display: block; }
7001: [nav-view="cached"], [nav-bar="cached"] { display: none; }

Both rules will be applied to the element <div class="nav-bar-block" nav-bar="cached"></div>, and since "display: block" is defined first, it will be applied.

Browser: Chrome v40, Safari
OS: OSX 10.10.2

Cheers,
Daniel

**Comment by Ionitron** [comment]
Greetings @djhr!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3145). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3145)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by djhr** [comment]
Ok, no problem, didn't knew about the issue form.
Thanks
