### ISSUE TITLE
bug: $ionicScrollDelegate Methods cause keyboard to close immediately

### ISSUE THREAD

**Issue by jfspencer** [driftyco/ionic#3148]
using scrollTo and scrollTop with $ionicScrollDelegate, and then focusing on a text input causes the native keyboard to open then immediately close. This may be related to #2902 digest cycle, or it could be caused by the very long animation decay that is occurring. Since reproduction is limited to emulators/devices I have linked a video showing the issue and the applicable code is below

video reproducing the issue
https://drive.google.com/file/d/0B0-I41uSyatNMXRja3dxa2tpUm8/view?usp=sharing

    <ion-content direction="y" on-scroll="scrollChange()" scroll-event-interval="100" start-y="56">...

    //function being called by on-scroll
    $scope.scrollChange = function(){
                var position = $ionicScrollDelegate.$getByHandle("boardListScroll").getScrollPosition();
                if(position.top < 40)
                    $ionicScrollDelegate.$getByHandle("boardListScroll").scrollTop(true);
                if(position.top >= 40 && position.top < 70) {
                    $ionicScrollDelegate.$getByHandle("boardListScroll").scrollTo(null, 56, true);
                }
    };

**Comment by Ionitron** [comment]
Greetings @jfspencer!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3148). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3148)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jfspencer** [comment]
closing. replaced by #3149
