### ISSUE TITLE
bug: Javascript in ionic template can't working

### ISSUE THREAD

**Issue by jues** [driftyco/ionic#3150]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>

I have no idea why the script tag can't working, here is the reproduce step: (ionic cli 1.3.10)

1.ionic start mytab

2.add following to templates/chat-detail.htm in ion-content

<p id="demo"></p>

<script>
var txt="ABCDEFGHIJKLMNOPQRSTUVWXYZ";
document.getElementById("demo").innerHTML = txt.length;
</script>

3.ionic serve --lab

4.navigate to chat detail page,the script couldn't work

why is that happened?
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jues!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3150). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3150)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
