### ISSUE TITLE
bug: "Does Continue" causes duplicate views when working with backdrops

### ISSUE THREAD

**Issue by sunny-mittal** [driftyco/ionic#3155]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I have the following structure in one of my templates:

```
<ion-view>
  <ion-content has-bouncing='false' scroll='false'>
    <ion-slide-box auto-play='false' does-continue='true' show-pager='true'>
      <ion-slide>
        <upcoming-events></upcoming-events>
      </ion-slide>
      <ion-slide>
        <checkin-events></checkin-events>
      </ion-slide>
    </ion-slide-box>
  </ion-content>
</ion-view>
```

When I look at the DOM, I see four ion-slides (each is duplicated) presumably because of the 'does-continue' flag. Now, my header for this has an overflow button, and as soon as I trigger the backdrop, I see my pager at the bottom increase from two to four pages, and when swiping views, I see the duplicated views but without the rendered content (they are distinctly different views, being rendered improperly). Is this a bug with ionic or am I structuring my mark-up incorrectly? Thanks in advance!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @sunny-mittal!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3155). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3155)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @sunny-mittal!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
