### ISSUE TITLE
bug: Disable view cache according to variable's value

### ISSUE THREAD

**Issue by hyyan** [driftyco/ionic#3160]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>webview</span>

<span ionic-description>I am trying to disable the view cache depending on a variable's value like this : 

```
<ion-view view-title="Stuff" cache-view="{{booleanVar}}">
````

But it is not working , any idea ? thanks in adnvance</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @hyyan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3160). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3160)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jsalhani** [comment]
Are you sure the scope of your controller wraps the ion-view so that it has the value of the expression?

**Comment by hyyan** [comment]
@jsalhani Yes I am sure , because I am using the ui-router to call my controller and bind it to the view

**Comment by jsalhani** [comment]
@hyyan  I think the ion-view attributes take expressions directly: try cache-view="booleanVar" (without the curly braces)

**Comment by hyyan** [comment]
@jsalhani  I have tired that but with not luck

**Comment by adamdbradley** [comment]
The cache-view attribute only uses `true` and `false` strings.
