### ISSUE TITLE
Collection-repeat add multiple css classes to element in beta 14

### ISSUE THREAD

**Issue by kristianbenoit** [driftyco/ionic#3166]
I use collection repeat with a filter. I styled the items with colors using CSS. When the view is resized (keyboard show/hide) or a browser windows resized, some items get random classes from some other item. Like if the item div is reused to show another item without clearing the classes that was there.

The problem is not present in beta 13.

Here's a snippet from the template:

    <div class="item collection-item {{item.type}}" ng-class="{'item-divider': item.isDivider}" ... >

      <div class="category-marker {{item.type}}"></div>
      ...
    </div>

`item.type` are color names. In css:

    .item-divider.brown {
      background-color: #765200;
      color: white; }

    .item-divider.blue {
      background-color: #0a577b;
      color: white; } 

    ...

    .category-marker {
      position: absolute;
      height: 100%;
      width: 5px;
      left: 0px; }

    .category-marker.brown {
      background-color: #c28900; }

    .category-marker.blue {
      background-color: #0f89c2; }

    ...

Searching break the DOM then closing the search breaks it even more : 

<img src="http://ionic-forum-uploads.s3.amazonaws.com/9246ac826c7db81d11ebbd716237da994b9a64e5434e.png" width="281" height="500">

Looking at the DOM, I get the following for the blue1 item. **see, the the `{{item.type}}` is expanded to blue and green ???** Plus item-divider is added while the data behind this says it is not:
    
    <div class="item collection-item green item-divider blue"  ...>
        <div class="category-marker brown"></div>
              blue1
              ...
    </div>

Here's the value of item for blue1:

    {
      isDivider: false,
      name: "blue1",
      type: "blue"
    }

See a sample app showing the bug here:
https://github.com/kristianbenoit/collection-repeat-css-bug

I can see the bug in chromium and firefox on desktop by resizing the window / filtering, but it's harder to trigger.

```
ionic info :

OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.1 LTS 
Node Version: v0.10.25
Cordova CLI: 4.2.0
Ionic CLI Version: 1.3.10 
```

**Comment by Ionitron** [comment]
Greetings @kristianbenoit!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3166). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3166)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
