### ISSUE TITLE
bug: Issue with JS Scrolling and previous (<) iOS key

### ISSUE THREAD

**Issue by jeremyrussell** [driftyco/ionic#3169]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>The implementation of automatic scrolling of focused input fields into view is incomplete as it ignores fields that are above the visible part of the screen

I initially raised this as a question in the forum (http://forum.ionicframework.com/t/automatic-scroll-on-element-focus-potential-to-extend-to-include-focused-elements-that-are-above-the-visible-part-of-a-scrollable-region/16652).  However as it got limited attention and as it seems an easy fix I have raised this as a bug.

I forked the ionic repo and made some minor changes to get the desired functionality. https://github.com/jeremyrussell/ionic/compare/js-auto-scroll-fix</span>

<span is-issue-template></span>

**Comment by clawish** [comment]
:+1: This issue might be related to the one I am describing [here](http://forum.ionicframework.com/t/keyboard-problem-in-form-very-nasty-one/18390). Implementing the fix you linked, seems to partly solve this problem. Could you reproduce this as well?

**Comment by Ionitron** [comment]
Greetings @jeremyrussell!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by jeremyrussell** [comment]
Oh no... bad call ionitron, this issue is not fixed.
