### ISSUE TITLE
bug: Bug : ion-side-menu-content drag-content - v1.0.0-beta.14

### ISSUE THREAD

**Issue by vnabet** [driftyco/ionic#3172]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have an app with views with & without menus

- The first page is without side menu
- Others pages have a side menu which cannot be dragged (`drag-content = false`)

Here I forked this excellent codepen:
http://codepen.io/vnabet/pen/VYxdoj

When I tap "go to menu view" I can't drag my menu ... it's OK... But it's with the Ionic beta.4

Now replace Ionic beta.4 references with beta.14. 
Il doesn't work, and the content menu can be dragged.

I have the same issue if I try to deactivate it with `canDragContent(false)` from `$ionicSideMenuDelegate`</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vnabet!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3172). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3172)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Appears to be fixed in the nightly builds.

http://codepen.io/mhartington/pen/Byxqmp
