### ISSUE TITLE
bug: Uncaught TypeError: Cannot read property 'freeze'

### ISSUE THREAD

**Issue by RangerRick** [driftyco/ionic#3174]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm getting this error in my console:

```
Uncaught TypeError: Cannot read property 'freeze' of null http://localhost:8100/lib/ionic/js/ionic.bundle.js Line: 6982
    console.(anonymous function) (index):34
    window.onerror (index):18
    triggerEvent ionic.bundle.js:802
    releaseGesture ionic.bundle.js:2008
    detect ionic.bundle.js:1380
    bindDomOnTouch ionic.bundle.js:929
```

The relevant line is: `self.isScrollFreeze = self.scrollView.freeze(false);` inside `_handleEndDrag`.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @RangerRick!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by RangerRick** [comment]
> Can you provide a detailed description of this issue?

It appears to happen when I toggle a button I have inside a modal with scroll="false"

> How would a robot go about replicating this issue?

I have created a codepen that reproduces the error: http://codepen.io/RangerRick/full/azKozj

Steps to reproduce:
1. Open that codepen
2. Click the "Filter" button
3. Toggle one of the toggle buttons

> On which platform does this happen occur? (iOS, Android, all, etc.)

All platforms, as far as I can tell.  I see it in Chrome as well as the iOS emulator.

> On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)

* Chrome 41.0.2272.64
* iOS 7 (emulated)
* iOS 8 (emulated)

> Is this an issue with the Ionic Framework or Ionic CLI?

Ionic Framework.

**Comment by mhartington** [comment]
Okay, so we need to check if the user has disabled scrolling first before freezing anything. Thanks for catching that @RangerRick 

https://github.com/driftyco/ionic/blob/51ed1824d5320ac788c9d27561338a61cbf844bc/js/angular/controller/scrollController.js#L163

**Comment by nantunes** [comment]
Shouldn't we do the same on _startDrag (https://github.com/driftyco/ionic/blob/811cc2725a8d87e9fd9c649e708e9145deec769a/js/views/listView.js#L567)?

**Comment by josdewitte** [comment]
This issue also occurs when swiping left for option buttons on the ion-list; And then the buttons do not auto-close anymore; resulting in multiple rows being swiped left due to this bug. Please fix?

**Comment by mhartington** [comment]
@nantunes and @josdewitte, could you open a new issue pointing to that PR and provide a codepen demo?

**Comment by EffEPi** [comment]
I am not sure if a new issue was open with what @josdewitte reported, but I am having the same issues and I cannot find a workaround...

**Comment by mhartington** [comment]
@EffEPi could you open a new issue please
