### ISSUE TITLE
bug: ion-side-menu and range input

### ISSUE THREAD

**Issue by vnabet** [driftyco/ionic#3178]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>This bug is related to #3172 issue

An application with views with and without menus.

Codepen: http://codepen.io/vnabet/pen/VYxdoj

If you nagivate to the "menu view" (tap "Go to Menu View") from the simple view, you cannot drag a range input.Indeed, this is the menu that opens</span>

<span is-issue-template></span>

**Comment by vnabet** [comment]
Up. Same issue with RC1

http://codepen.io/vnabet/pen/VYxdoj

"Go to Menu View" -> Unable to slide the range input without opening the menu.

Otherwiser congratulation for this rc ! ;)

Thanks

**Comment by ariera** [comment]
i also had this problem with RC5

**Comment by ArTiSTiX** [comment]
See also:
https://github.com/driftyco/ionic/issues/3215
https://github.com/driftyco/ionic/issues/318

**Comment by michalsnik** [comment]
I made pull request for this issue right here #4062

**Comment by Ionitron** [comment]
Greetings @vnabet!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
