### ISSUE TITLE
perf: Ionic modal performance with CSS transition

### ISSUE THREAD

**Issue by jabyrd3** [driftyco/ionic#3180]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hey,

I'm noticing some serious slowdown on android tablets when using the Ionic Modal. Apparently the css is trying to animate an RGBA background, which is not performant at all. This would be a simple fix, except that the .modal-backdrop div is wrapping the entire modal div so you can't use opacity .5 as the transitionable property.

If the markup were restructured so that the modal backdrop wasn't also wrapping everything you could animate the opacity instead of the rgba background and it smoothes out the fadein/fadeout of the backdrop and keeps the app from skipping frames on my test devices.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jabyrd3!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3180). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3180)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
