### ISSUE TITLE
bug: bug: hiding individual tab switches place when re-shown

### ISSUE THREAD

**Issue by dhcar** [driftyco/ionic#3181]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I had an issue where I wanted to display a single tab selectively when a media player was playing but have the tab hidden until then.

A simple ng-if="player.track" worked. BUT when it became visible again, the tab switched places with the one to the right. Thats the bug.

Controller:

    .state('tab', {
      url: "/tab",
      abstract: true,
      templateUrl: "tabs/tabs.html",
      controller: function($scope, Player){
        $scope.player = Player;
      }
    })

tabs.html

    <ion-tab title="Now Playing" icon="icon ion-ios7-pulse-strong" href="#/player/" ng-if="player.track"
    </ion-tab>
      <ion-tab title="Account" icon="icon ion-gear-b" href="#/tab/account" ng-if="true">
             <ion-nav-view name="tab-account"></ion-nav-view>
      </ion-tab>

To fix this I put an ng-if="true" on the second tab. But it would be nice if that weren't necessary :)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @dhcar!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3181). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3181)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @dhcar!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
