### ISSUE TITLE
bug: Ionic View Android cannot login or load an app

### ISSUE THREAD

**Issue by bostondv** [driftyco/ionic#3183]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Environment: Ionic View 0.0.2, Android 5.0.1

Login issue: Open app, enter username and password and hit submit. App does not log me in nor provide any error or feedback whatsoever. 

Load app issue: Manually enter an app ID or scan QR code, app returns "Invalid app id or no connection to server".

Sorry if this is the wrong place to report, I couldn't find any issue tracker for the app.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @bostondv!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3183). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3183)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tlancina** [comment]
Hey sorry to hear you're having issues, that is a really old version of View, try updating to 1.0.0.

**Comment by bostondv** [comment]
Just grabbed 1.0.0 when it was released the other day. Works great!

**Comment by tlancina** [comment]
Awesome! Glad it's working.

**Comment by deepak229** [comment]
I am facing the same issue.
I have view 1.0.0. When I install the app through ioninc run android, it opens the app fine. But when I upload and view the app from view, it does not view from there. Any suggestions?

**Comment by gechichure** [comment]
I've just installe the 1.0.5 versión and the same password problem. At the same time I login in ionic dashbord web so I coudt be a password problem.

Please help,

regards !!!!
