### ISSUE TITLE
feat: List and detail item ionic

### ISSUE THREAD

**Issue by breth84** [driftyco/ionic#3187]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a problem , I can not load the data of the item called because the database queries defined in services.js runs after and so my array is empty when called by $scope , someone has a solution I have to run the query inside the controller itself?

thanks in advance

         controller('SchedaProdottoCtrl', function(ProductService, $cordovaSQLite, $scope ) {
              $scope.item = ProductService.get($stateParams.productID);
         });

And in the services.js have:

    .factory('ProductService', function($cordovaSQLite) {

         var items = [];
    $cordovaSQLite.execute(db, "SELECT * FROM prodotti").then(function(res) {
        if (res.rows.length) {
            for (var i = 0; i < res.rows.length; i++) {
            var row = res.rows.item(i);
                 items.push({
                     IdProdotti:row.idProdotti,
                     nomeProdotto:row.Nome,
                     dataScadenza:row.DataScadenza
                });
            }
        } else {
            console.log('No result found');
        return false;
        }
      });

    return {
      all: function() {
          return items;
       },
           get: function(productID) {
              // Simple index lookup
          return items[productID];
              }
       }
    })</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @breth84!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3187). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3187)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This isn't an issue with ionic, but how the data is being loaded.
You need to use `$q` when working with data to make sure promises get resolved.

https://docs.angularjs.org/api/ng/service/$q
