### ISSUE TITLE
bug: ionic collection-repeat doesn`t work when attributes prefixed with 'data-'

### ISSUE THREAD

**Issue by caiiiycuk** [driftyco/ionic#3190]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi. I try to use colletion-repeat component to show list of 100 items. And it doesn`t work when i use prefixes 'data-' for attributes, like this:
```html
<ion-content>
	  <div class="list">
	  	<div class="item my-item"
	  		data-collection-repeat="organization in controller.organizations"
	  		data-collection-item-width="'100%'"
	  		data-collection-item-height="controller.getItemHeight(item, $index)"
	  		data-ng-style="{height: controller.getItemHeight(organization, $index)}">
	  	{{organization.name}}, {{organization.comment}}
	  	</div>
	  </div>
  </ion-content>
```

When i remove data prefix then all works fine. But without data prefixes html will not pass validation on http://validator.w3.org/. I want to work with valid html.

Also, x- prefixes works fine.

As i know, angular should works fine with x and data prefixes, it should removes it in normalization process. But in my case this does not work.

'data-':
![1](https://cloud.githubusercontent.com/assets/1727152/6407949/bb59f0c2-be74-11e4-94dc-ce4d89226750.png)

without 'data-':
![2](https://cloud.githubusercontent.com/assets/1727152/6407952/c39103de-be74-11e4-8bbc-3dae2e2ba10b.png)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @caiiiycuk!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3190). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3190)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ajoslin** [comment]
We're not going to address this. `data-` prefixes and valid HTML5 are not a goal for us with Ionic.

Lose the data- prefixes and it will work.
