### ISSUE TITLE
bug: Sidemenu unit test failing

### ISSUE THREAD

**Issue by jabyrd3** [driftyco/ionic#3191]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Line 81, sidemenu.unit.js is failing as of 68800e35f51e7458fe9a0e5f2bbce0ecb7ad0114</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jabyrd3!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3191). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3191)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jabyrd3** [comment]
Rebuilt, wasn't able to recreate?
