### ISSUE TITLE
feat: all vendor prefixe

### ISSUE THREAD

**Issue by AliMD** [driftyco/ionic#3196]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Could you please remove your vendor prefixes and use some think like autoprefixer in gulp compile process.
And also add feature to ionic-cli setup sass to do same for end user
If you want/approve i can create a pull request
Thank you in advance.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @AliMD!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3196). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3196)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adamdbradley** [comment]
We will be doing this in future versions.

**Comment by AliMD** [comment]
do you accept any contributing/pull request in this time ? (befor next rc)
