### ISSUE TITLE
bug: $state.go() doesn't work inside a resolve

### ISSUE THREAD

**Issue by ProLoser** [driftyco/ionic#3198]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It just doesn't. It should, but it doesn't. I've tried returning a rejected promise but this does not allow the state to redirect. No, I don't think I should be putting this logic into the $stateChangeStart event because it would mean strewing resolve logic i normally disperse through each state all lumped together in one place. It's just bad juju. You can't simply have everything fall on the floor just because a resolve is going to reject.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ProLoser!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3198). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3198)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by saniyusuf** [comment]
@ProLoser  im not sure this is an Ionic bug and Im not sure the behaviour is supported in angular because the routing has not yet completed by error or success. Normally when you return a promise in the resolve, and if this promise fails a $routeChangeError event is fired. You can catch this event with the $rootScope service and do a new $state.go.

**Comment by ProLoser** [comment]
@saniyusuf as someone who has contributed to the router's development, I can assure you this behavior does in fact work, and the currently required design is quite poor (catching things in the error event). This would mean I would have to catch all my different resolve errors across the board for all sorts of different reasons in one unified location, vs in the location they were originally created in.

If it's not a direct fault of ionic, then the default build of ionic may be shipping with a dated version of the router (that would be my first guess).

**Comment by jdgeier** [comment]
Is there any update on this? I had my controller for route change working before but now my login controller and interceptors no longer work for $ionicHistory.goBack()

**Comment by Ionitron** [comment]
Greetings @ProLoser!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
