### ISSUE TITLE
docs: Task 'build' is not in your gulpfile

### ISSUE THREAD

**Issue by ibewugb** [driftyco/ionic#3202]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi, I followed the instructions with:
"gulp build --release to build with minification & strip debugs"

But I get the error:
gulp build --release
[19:41:34] Using gulpfile ~/Code/App/gulpfile.js
[19:41:34] Task 'build' is not in your gulpfile
[19:41:34] Please check the documentation for proper gulpfile formatting

I use the default tabs app template.

Do I have to write it on my own to the gulpfile?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ibewugb!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3202). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3202)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @ibewugb!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
