### ISSUE TITLE
feat: ionSpinner customization in refresher and infinite scroll

### ISSUE THREAD

**Issue by danda1man** [driftyco/ionic#3203]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It would be nice to be able to add the color class to the spinner from the refresher and infinite scroll directives.  Looks like right now we can only change what the icon type is.  Natural follow up to #3077</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @danda1man!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3203). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3203)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by felquis** [comment]
+1 :+1: 

I think something like this would be nice!

```html
<ion-infinite-scroll
  on-infinite="loadMore()"
  distance="10%"
  spinner-class="spinner-light or-something-else">
</ion-infinite-scroll>
```

I also noticed that when using infinite-scroll with ng-repeat, the spinner appears where I put the `ion-infinite-scroll` directive, so may be useful to use the content of this directive to show a completely different loading, to let developers use whatever they want to, like:

```html
<ion-infinite-scroll
  on-infinite="loadMore()"
  distance="10%"
  use-content="true">

  <p>
    <ion-spinner class="spinner-light"></ion-spinner>
  </p>

  Loading
</ion-infinite-scroll>
```

**Comment by felquis** [comment]
I bit related to #3343

**Comment by mhartington** [comment]
Closing this as a feature request and moving to our trello board 
https://trello.com/c/pedEiFm5/93-allow-classes-for-ion-refresher-and-ion-infinite-scroll
