### ISSUE TITLE
bug: wrong $index in slider when does-continue=true

### ISSUE THREAD

**Issue by konsultaner** [driftyco/ionic#3209]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I used the slider with two images like this:

    <ion-slide-box on-slide-changed="currentSlide=$index" auto-play="true" does-continue="true" show-pager="false">
        <ion-slide ng-repeat="image in images">
            <img ng-src="{{image.src}}" width="100%"/>
       </ion-slide>
    </ion-slide-box>

when outputting the ```currentSlide``` value, it turns out to show 0,1,2,3,0,1,... instead of only 0,1,0,1,... I helped myself with 

    (currentSlide || 0) % images.length

I needed to add the ```|| 0``` because the change event does not fire before any rotation happened.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @richidd!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3209). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3209)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @konsultaner!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by konsultaner** [comment]
has anyone ever reviewed this bug? seems to be a very simple one?
