### ISSUE TITLE
feat: Ionicon 2.0

### ISSUE THREAD

**Issue by thomaschaaf** [driftyco/ionic#3210]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I saw that ionicon 2.0 was out and tried using it with the latest ionic and discovered that beta14 is only bundled with ionicon 1.5.2.

When will the new version of ionic be released?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @thomaschaaf!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3210). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3210)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by zhouyixiang** [comment]
You could give nightly build a try. Ionicon 2.0 is available in it now.

**Comment by mhartington** [comment]
ionicons 2.0 are in the nightly build.
