### ISSUE TITLE
bug: $ionicPopup cssClass is not merged into the popup

### ISSUE THREAD

**Issue by toxus** [driftyco/ionic#3213]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

Using the cssClass for the $ionicPopup the cssClass is not merged into the definition of the popup. In the file ionic-angular.js the variable POPUP_TPL should be 

```javascript
var POPUP_TPL =
  '<div class="popup-container" ng-class="{{cssClass}}">' +
    '<div class="popup">' +
      '<div class="popup-head">' +
        '<h3 class="popup-title" ng-bind-html="title"></h3>' +
        '<h5 class="popup-sub-title" ng-bind-html="subTitle" ng-if="subTitle"></h5>' +
      '</div>' +
      '<div class="popup-body">' +
      '</div>' +
      '<div class="popup-buttons" ng-show="buttons.length">' +
        '<button ng-repeat="button in buttons" ng-click="$buttonTapped(button, $event)" class="button" ng-class="button.type || \'button-default\'" ng-bind-html="button.text"></button>' +
      '</div>' +
    '</div>' +
  '</div>';
```

(ths cssClass should be surrounded by {{ }}</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @toxus!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3213). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3213)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by toxus** [comment]
Sorry error, my code change is wrong. There should be no change!
