### ISSUE TITLE
bug: Nested view link doesn't trigger animation or back button when navigating the parent view

### ISSUE THREAD

**Issue by meetshawn** [driftyco/ionic#3214]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have tabs inside one of my side menu states. If I click a ui-sref to another menu state (menu.state) from a tab state (menu.tabs.state) it works but there's no transition or back button in the navbar. The navbar is in menu-content where the nav-view I'm trying to navigate is and the menu button shows up after navigating, but it should be (or at least I want) a back button with a transition. Is this a limitation or am I just doing something wrong?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @meetshawn!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3214). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3214)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @meetshawn!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
