### ISSUE TITLE
bug: Range Sliders not working together with side-menu (compare closed issue #318)

### ISSUE THREAD

**Issue by tobias74** [driftyco/ionic#3215]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello :-)

This is what I have observed:

Using a Range-Slider on a view together with the S(l)ide-Menu is impossible, except in case the Side-Menu is operated with   ion-pane ion-side-menu-content drag-content="false"

When the user drags a slider on a view containing a side-menu, the following scenarios are possible:

* In a Browser (web-view) the Side-Menu becomes visible when the user slides the range-slider to the right.

* On a device nothing happens: no menu, no slider-movement. The App would sometimes freeze up though.

Maybe reopening bug #318 might be an option here?

Thank you :-)

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @tobias74!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3215). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3215)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Pijuli** [comment]
As I said in issue #318, the workarround doesn't fix taht behaviour to me... It's really frustrating :(
Hope you fix it.
Congrats for the work anyway :)

**Comment by Ionitron** [comment]
Greetings @tobias74!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by ArTiSTiX** [comment]
This issue is not supposed to be closed.
I suggest to take a look at this issue, since it can be blocking for some projects.

**Comment by michalsnik** [comment]
I just made pull request for this issue #4062
