### ISSUE TITLE
Sidemenu breaks after some navigation

### ISSUE THREAD

**Issue by mariohmol** [driftyco/ionic#3217]
Hy,
 I have a partial view

		.state('interna', {
		      url: "/interna",
		      abstract: true,
		      templateUrl: "templates/sidemenu.html"
		    })
		    
			.state('interna.aliancas', {
		        url: '/aliancas',
		        views: {
			        'menuContent' :{
			          templateUrl: "templates/aliancas.html",
			          controller: 'aliancasCtrl'
			        }
			     }
		    })

			.state('politico', {
		        url: '/politico/:politicoid',
		        templateUrl: 'templates/politico.html',
		        controller: 'politicoCtrl'
		    }) 

Then in mercado.html i have this sidemenu and i click in a link that goes to politico/1. In this politico/1 have a back() that goes to mercado.html again.

Doing mercado -> politico/1 -> back() -> politico/1 -> back() , it returns to mercado.html and sidemenu shows, but when i click it does not open sidemenu.

I'm using:
* Ionic bundle Ionic, v1.0.0-beta.13 
* MacOS emulating iOS Iphone 5

I have others views that works going to one view to another, but this in particular is crashing.

I I use beta14 , it breaks after first back:
mercado.html -> politico/1 -> back() -> keeps loading , gives timeout and does not open all screen

In log does not me show any error message.

Any tips??

**Comment by Ionitron** [comment]
Greetings @mariohmol!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3217). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3217)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mariohmol** [comment]
I have a code that shows me a error message in case that a url could not be retrieved:


var interceptor = function ($q, $location,$rootScope) {
    return {
        responseError: function (rejection) {
        	$rootScope.$broadcast('loading:hide'); 
            if (rejection.status == 403) {
                $location.url('/login');
            }else{
            	 $rootScope.$broadcast('alert:seminternet'); 
            }

            return $q.reject(rejection);
        }
    };
};


app.run(function($rootScope, $ionicLoading,$ionicPopup) {
  
 $rootScope.$on('alert:seminternet', function() {
   $ionicPopup.alert({
		title : 'Sem Internet',
		template : 'Não conseguimos conectar. Verifique se sua internet está funcionando corretamente!'
	});
  });

So in some times it was creating 2 ionicpopup.alert in the same return and then it breaks the sidemenu.

In past days i had a problem when making more than 1 alert at once it locked all the app. Is any way to make ionic prevent this errors?
