### ISSUE TITLE
bug: History not triggered when navigating to a view

### ISSUE THREAD

**Issue by mattlewis92** [driftyco/ionic#3221]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When navigating to a view without an ion-nav-title or an ion-content (I am using view-title and ion-tabs instead) the history doesn't trigger and it treats the new state as the root of the next history. I can workaround it for now by using the ion-nav-title directive instead of the view-title attribute, or by adding an empty ion-content before the tabs.

http://codepen.io/anon/pen/MYByQE</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mattlewis92!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
