### ISSUE TITLE
bug: Livereload via "ionic serve" does not work properly (loosing back button, state etc.)

### ISSUE THREAD

**Issue by ibuziuk** [driftyco/ionic#3222]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hey, guys.
I have faced an issue coupled with LiveReload via "ionic serve". Apparently, this is ionic refresh side-effect (seems that ionic looses state on refresh). Here is the one of many scenarios of how one can repro it.

Steps to reproduce:
1. Create the default tabs app (ionic start myApp tabs)
2. Start the app with LiveReload server (ionic serve)
3. Navigate to "Friends" -> "Scruff McGruff"
4. Open 'www/templates/friend-detail.html' in some editor
5. Add something inside <ion-content> tag (e.g. Livereload breakage) and save changes
ERROR - "Back button" lost. "Friends" tab is broken (showing Scruff McGruff only)

Here is a short demo video - http://screencast.com/t/MibRQci9y

  </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ibuziuk!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3222). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3222)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
If the entire app is refresh, it'll no longer have a history of previous views, which is why the back button no longer shows.

**Comment by ibuziuk** [comment]
@Ionitron I see. But is there are any way to perform 'smart' refresh (with history saving)?

**Comment by mtpultz** [comment]
A useful feature would involve being able to set a config variable that resets to specific state on livereload.  Depending on what you are trying to achieve when working through the application.  Sometimes I'm just working on a single page and the loss of history doesn't matter, but in other cases this function defeats the purpose of livereload since I have to go and change the URL back to my base domain, or to a specific state.

**Comment by holographix** [comment]
+1
it would be very useful to have this addressed

**Comment by mhartington** [comment]
This would be an issue bring up on the cli repo, not the framework.

**Comment by digeff** [comment]
+1

**Comment by burisk** [comment]
+1
