### ISSUE TITLE
bug: collection-repeat doesn't work properly when data is loaded asynchronously

### ISSUE THREAD

**Issue by vlad-bezden** [driftyco/ionic#3226]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I just got nightly - 1.0.0-beta. 14-nightly-1102 build and did some testing with collection-repeat. 
It calculates properly height of the item in case if data is loaded on initial controller load, however, when data is loaded dynamically or asynchronously collection-repeat will not calculate properly height, and will only use height of the first item in the list.

I created sample code, so you can see the issue.

http://codepen.io/anon/pen/KwBarr?editors=101
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vlad-bezden!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3226). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3226)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
