### ISSUE TITLE
bug: scrollbars in firefox

### ISSUE THREAD

**Issue by dcsan** [driftyco/ionic#3227]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>when looking at our app on a desktop browser, firefox shows double scrollbars around ionic content.
chrome is ok

i assume this is because the "ionic view" puts all content inside a div with overflow or scroll behavior
but its a bit worrying this only shows up in one browser.
is this something ionic will fix?

![e4a4095a-c198-11e4-8206-b413037b7112](https://cloud.githubusercontent.com/assets/514002/6470835/4edd1026-c19b-11e4-9f1a-26129b43d8b5.png)

related
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @dcsan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3227). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3227)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by cyprusglobe** [comment]
seemed to happen with this commit 0ea40a7e68ae986b4a40d6826a93d02b48b08aef

**Comment by gine** [comment]
I use <ion-scroll> scrollbar-y="false" leave the bars visible. I fixed with:

.scroll-view::-webkit-scrollbar {
  display:none;
}

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Are you still experiencing this issue?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!
