### ISSUE TITLE
bug: side menu doesn't scroll in Android using overflow-scroll="true"

### ISSUE THREAD

**Issue by vgmcglaughlin** [driftyco/ionic#3228]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>On Android, using `overflow-scroll="true"` on an `ion-side-menu` element's `ion-content` child doesn't allow the contents of the side menu to scroll.

This issue does not appear in the base beta14 release, but can be seen using the nightly build.

[This project](https://github.com/vgmcglaughlin/ionic-sidemenu-scrolling-issue) shows the side menu scrolling properly using base beta14, failing using the nightly build, and working again when you remove `overflow-scroll="true"`.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vgmcglaughlin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3228). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3228)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by vgmcglaughlin** [comment]
Looks like nightly build 1017 is the first build where this fails, so seems related to [commit a5881ea](https://github.com/driftyco/ionic/commit/a5881eaeba7d12d016fe3712c77261e75e863cf3).

**Comment by cciszak** [comment]
Experiencing exactly the same problem. This is a show stopper.

**Comment by cciszak** [comment]
overflow-scroll="true" works fine for me on ion-content in ion-side-menu on android 4.4 webview. However, what's not working is overflow-scroll="true" on ion-content within a view when you have side-menu as well. To repeat:

1. Ionic start myApp sidemenu
2. Add overflow-scroll="true" in ion-content for one of the views ie 'Browse'. Add more content.
3. Run on android 4.4, bum scrolling not working in 'Browse' view.

**Comment by vgmcglaughlin** [comment]
@perrygovier, no comment/label/assignee yet on this issue, same resolution as #3298?

**Comment by Ionitron** [comment]
Greetings @vgmcglaughlin!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
