### ISSUE TITLE
feat: Connect to API when behind proxy server

### ISSUE THREAD

**Issue by samithaf** [driftyco/ionic#3229]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi guys,
Thanks for adding proxy request feature which allows to connect to external API. However when we are working behind a (company) proxy this won't work. After reading the source I figured it out that Ionic is using proxy-middleware plugin to do the proxying. 

Do you have any plan to support this feature in a upcoming release?

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @samithaf!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3229). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3229)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#281
