### ISSUE TITLE
$http.get in factory service

### ISSUE THREAD

**Issue by sams46** [driftyco/ionic#3231]
I can use $http.get('test.php') to get json through .controller but unable to do the same through .service or .factory. I can see the results in console log but it doesn't bring any result and if i put json manually in .factory or .service it works fine so it seems some issue in $http.get.

**Comment by Ionitron** [comment]
Greetings @sams46!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3231). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3231)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by saniyusuf** [comment]
@sams46  $http.get is an angular feature not an Ionic one. Can you put up a code pen and are you sure you are passing the results correctly in the controller?

**Comment by Ionitron** [comment]
Greetings @sams46!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.

**Comment by sams46** [comment]
It doesn't work in service or factory when you use $http.get alone like you can do in controller. I sorted out by sending promise. Sorry to post this issue here. Already posted on forum few days back but didn't get any reply. 

myfunc: function() {
 promise = $http.get('url.php').then(function (response) {
   return response.data;		
      })
  	  return promise;
    }

Thanks for your assistance.
