### ISSUE TITLE
bug: View title dissappearing between views / routes

### ISSUE THREAD

**Issue by CedNet** [driftyco/ionic#3232]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi! I'm using the most current nighly via bower #master and for a while now when going between states the view title is not showing up as it should. Something as simple as this: <ion-view view-title="{{ event.name }}"> will not display when going back and forth between views.  If I reload the app (in browser during test) the view title is there. But going to another view and then back, the title is no longer there. This does occur in other situations too where the view as the view-title attribute set. 

Is this a bug? 

If I use the <ion-nav-title> element to set the title, the title persists. 
I can also set a global viewTitle variable in the rootScope that does the job of persisting if I use it in the <ion-view> element.

Maybe something to look at.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @CedNet!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3232). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3232)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adamdbradley** [comment]
Would you be able to put together a codepen that replicates the issue? Have you been using the life cycle events to set the title? http://ionicframework.com/docs/api/directive/ionView/

There's also the nav-title directive you could use: http://ionicframework.com/docs/api/directive/ionNavTitle/

**Comment by CedNet** [comment]
I don't know why my html did not show, but in my text I did not that I can get around it by using the ionNavTitle directive. So for now, this is solved.

If I find the time, I'll create a full codepen app and see if I can repeat the problem for you to have a look at.

**Comment by reviyou** [comment]
I think I might have created a duplicated issue here: https://github.com/driftyco/ionic/issues/3250

hopefully ionic team can fix it without further additional details, issue seems to cause very bad User experience and a fairly easy to reproduce.
