### ISSUE TITLE
bug: issue: ion-content

### ISSUE THREAD

**Issue by masr** [driftyco/ionic#3242]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Data binding of overflow-scroll does not work in 1.0.0-beta.14.
A bug or purpose of design?

<ion-content overflow-scroll="{{value}}" > is not valid because the directive code directly use the value of attr.overflowScroll rather than $scope.$eval(attr.overflowScroll).

The correspond code is:
if ($attr.scroll === "false") {
          //do nothing
        } else if(attr.overflowScroll==="true") {
          $element.addClass('overflow-scroll');
        }</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @masr!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3242). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3242)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Ionic does not support toggling between native and JS on a given page after the page has loaded. We should update the docs mentioning this.

**Comment by masr** [comment]
And I found another issue, overflow-scroll="true" is not valid in chrome and ok in FF. I need to show a page in web browser, so traditional scroll is a must for users who do not have mouse wheel.
Any way, overflow-scroll do not act the same way for chrome and FF.

**Comment by mhartington** [comment]
`overflow-scroll="true"` should work. 
Could you please provide an example of where you are not seeing it work?

**Comment by Ionitron** [comment]
Greetings @masr!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @masr!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
