### ISSUE TITLE
bug: No arrow icon in rc.0

### ISSUE THREAD

**Issue by jalpedersen** [driftyco/ionic#3247]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>After upgrading to rc.0 I've lost the left-arrow on the back button as well as the right-arrow on list items. The problem exists on both iOS and Android</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jalpedersen!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3247). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3247)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
@jalpedersen how did you update? Do you have the new ionicons as well? If so, could you provide a code sample or codepen example?

**Comment by Koosmann** [comment]
Try double checking $ionicons-font-path declared in your 'ionic.app.scss' file.  In my case, I had to add the 'release' directory into the path.

**Comment by jalpedersen** [comment]
@perrygovier I forgot to replace my ion-ios7-back classes with ion-ios-back, etc.  as per ionicons 2.0. So, no issue after all.
