### ISSUE TITLE
bug: Terminating app due to uncaught exception

### ISSUE THREAD

**Issue by ziobudda** [driftyco/ionic#3249]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi all, when I try to "run" my app for my iphone4/ios7 via XCODE6/Yosemite I get this:

2015-03-04 01:18:43.879 FindYourItaly[512:60b] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIApplication 0x15672c90> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key view.'
*** First throw call stack:
(0x2e21cf4b 0x3865d6af 0x2e21cc61 0x2eb5c18b 0x2eb6ddd5 0x2e18ce6f 0x30ceef87 0x30cf07eb 0x30c0894b 0x309fa265 0x3099541f 0x30994721 0x309f9b3d 0x32e7870d 0x32e782f7 0x2e1e79df 0x2e1e797b 0x2e1e614f 0x2e150c27 0x2e150a0b 0x309f8dd9 0x309f4049 0xf3c9b 0x38b65ab7)
libc++abi.dylib: terminating with uncaught exception of type NSException

What is this ? Where is my error?

On Android I have no problem.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ziobudda!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3249). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3249)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#292
