### ISSUE TITLE
use ionic without angularjs

### ISSUE THREAD

**Issue by Lancezh** [driftyco/ionic#325]
I like your design, but I do not use angularjs, does this mean that can not be good to show the animation, or other features?

P.S.  Do you consider adding emberjs expansion

**Comment by jhabdas** [comment]
:+1: for use with React. It'd be nice to see the Angular dependency removed regardless. Keep up the great work!

**Comment by rustanacexd** [comment]
+1 for react. angular is the only thing that holds us back( me and my colleagues) from using ionic

**Comment by misbach** [comment]
+1 for getting rid of angular. I'd kinda like to see it plain vanilla. If you have to do something how about a standard such as web components?

**Comment by Matt2012** [comment]
+1 I think it's crazy that there should be a javascript framework dependency. If Ionic wants to use Angular behind the scenes that's fine but why should the end user.

**Comment by moscartong** [comment]
+1 I think Ionic could totally separate the user interface apart from AngularJS. We should be free for choosing which framework to use together with Ionic, for example Polymer.

**Comment by estraschnov** [comment]
+ 1 on that one.

**Comment by appeality** [comment]
+1 - Not interested in Angular JS. Ionic looks awesome, but forcing devs to use AngularJS is not ideal.

**Comment by webberig** [comment]
+1 with a new argument:
In our company we have different profiles working in our projects. First, we have a graphical designer who is also skilled in HTML and CSS, but with limited JS knowledge - let alone Angular JS. Second we have frontend developers (like me!) who are capable in JS and other technical aspects such as CLI tools, Cordova and XCode.

Ionic doesn't allow us to give the designer a head start with prototypes using the ionic framework because of the steep learning curve: having to install Cordova which in turn requires the XCode build tools, learning Angular, etc...

It seems logical to me that the visual aspect (CSS, JS controls) can be used separately (such as JQuery Mobile, Bootstrap, Ratchet, ...) from Angular and Cordova so a graphical designer can work with those and let developers do the rest...

**Comment by mardraze** [comment]
+1
What is a problem to create a script to handle the controls? At the moment I can't use ionic css, because I must use angular, only then controls works properly.
I can't use angular because then I can't use many others frameworks.

**Comment by Robert-W** [comment]
Big ol +1 here.  Going all in on Angular is probably not a great idea, My startup and the place I currently work have decided not to use Ionic for this specific reason.  Its still on our radar as we would love to use something like Ionic but it depends on Angular, so for now we will not.

**Comment by Robert-W** [comment]
Also, if you decide to start actually working on something like a React or a vanilla JS version of Ionic, I would be more then willing to contribute :)

**Comment by EffEPi** [comment]
+1, forcing angular is not the best approach.  I would suggest to support it, but not forcing it

**Comment by jhabdas** [comment]
Moderators please lock
