### ISSUE TITLE
feat: switching to nativescript

### ISSUE THREAD

**Issue by jonathanobino** [driftyco/ionic#3258]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>are you planning to switch from cordova to nativescript ? https://www.nativescript.org/</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jonathanobino!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3258). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3258)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#294
