### ISSUE TITLE
bug: Sidemenu starter with tabs issue

### ISSUE THREAD

**Issue by ag-secret** [driftyco/ionic#3261]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>**Version**: v1.0.0-rc.0 "neodymium-newt

I have an app generate with `ionic start myapp sidemenu`.
So I have a view that I want use tab, so I just did it:

    <ion-view title="Checkin Balada das crianças" class="">	
	 		<ion-tabs class="tabs-positive">
	 			<ion-tab title="Checkin">
	 				<ion-content>
	 					Line 1
	 					<br>
	 					Line 2
	 					<br>
	 					Line 3
	 					<br>
	 					Line 4
	 					<br>
	 					Line 5
	 					<br>
	 					Line 6
	 					<br>
	 					Line 7
	 					<br>
	 				</ion-content>
	 			</ion-tab>
	 		</ion-tabs>
    </ion-view>

Result:

![print](https://cloud.githubusercontent.com/assets/10434389/6561359/6c7328e0-c66f-11e4-8a60-4b0a79df181a.jpg)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ag-secret!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3261). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3261)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
