### ISSUE TITLE
docs: ion-spinner not documented

### ISSUE THREAD

**Issue by TheBosZ** [driftyco/ionic#3262]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The new directive is great, but the docs don't have an entry for it. It looks like the docs are there, but not pulled into the main directory yet.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @TheBosZ!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3262). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3262)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by cyprusglobe** [comment]
isn't this the link?
http://ionicframework.com/docs/api/directive/ionSpinner/

**Comment by TheBosZ** [comment]
That is absolutely the link! It's not coming up when I type 'ion-spinner' in the search box so I couldn't find it.

I guess the bug is actually that it's hard to find.

**Comment by Ionitron** [comment]
Spinner is in the left menu of the docs. We'll look into why the search isn't working. Thanks
