### ISSUE TITLE
bug: Scroll stops short of the top of the page.

### ISSUE THREAD

**Issue by freitagk** [driftyco/ionic#3263]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Type: bug

Platform: Android 4.4.4 (Oneplus One and nexus 5)

Hi I believe I have found a major bug with the scrolling. I have just read this previous issue:

#482

With my project I have a scrollable page with several comment text boxes. If I scroll down the page and open a text box, type some text in and exit out of the input, there is a high chance that when I try to scroll back to the top of the page, the scroll will get stuck just short of the top of the page. If I repeat these steps, the effect will continue and I will not be able to get as far up to the top of the page as before. I am still able to force the scroll to get a bit above where it stops but will get immediately pulled back to that position short of the top of the page. On this page it also has a pull to refresh feature but I do not know if that matters here.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @freitagk!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3263). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3263)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by freitagk** [comment]
I made a video of this happening. 
https://www.youtube.com/watch?v=dH12ZBtQZnY&feature=youtu.be

Issue occurs at 1:05.

**Comment by freitagk** [comment]
I also attempted to update the issue as per bot instructions and got a Update Failed message multiple times after filling all fields.

**Comment by jgw96** [comment]
Hello! Are you still experiencing this  issue with the latest version of ionic(ionic 1.2.4)? Thanks!

**Comment by jgw96** [comment]
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue!
