### ISSUE TITLE
$ionicPopup  click an item in popup template

### ISSUE THREAD

**Issue by Jaware** [driftyco/ionic#3268]
template code:
	             
 
                         <a  class="input-label" ng-bind="shop.des"></a>	            
	              <i class="button icon button-icon ion-plus" ng-click="shop.add()"></i>
	        

controller code:       $scope.shop.add= function() {	 alert(123);	 }
 the method can not work, "ng-bind=shop.des" binds normal,however the ng-click not work,  is this a bug ?or ionic does not support method in $ionicPopup .

**Comment by Ionitron** [comment]
Greetings @Jaware!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3268). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3268)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
You should use a button element instead. I'd also recommend asking on the forum.

**Comment by Jaware** [comment]
thanks
