### ISSUE TITLE
bug: Cordova app with angularjs

### ISSUE THREAD

**Issue by NavneetNile** [driftyco/ionic#3270]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>webview</span>

<span ionic-description>I am trying to make android mobile app using ionic. I have created an application in MEAN.js framework and it is working properly and now i am trying to convert this application into an android mobile application so i tried a lot but could not find a proper solution. Please help me to find the way for creating android mobile app using ionic. Thankyou.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @NavneetNile!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3270). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3270)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @NavneetNile!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
