### ISSUE TITLE
bug: content resize after ionic.Platform.fullScreen

### ISSUE THREAD

**Issue by schnti** [driftyco/ionic#3271]
The content isn't resizing after `ionic.Platform.fullScreen` is toggled....

```
            function orientation() {
                if (ionic.Platform.isIOS() && !ionic.Platform.isIPad()) {

                    if ($window.orientation == -90 || $window.orientation == 90) {
                        ionic.Platform.fullScreen(true, false);
                    }
                    else {
                        ionic.Platform.fullScreen(false, true);
                    }
                }
            }

            window.addEventListener('orientationchange', function () {
                orientation();
            }, false);
```

Fix:
change `panes[i].style.height = panes[i].offsetHeight + "px";`to `panes[i].style.height = window.offsetHeight + "px";`

![ios simulator screen shot 10 mar 2015 15 03 41](https://cloud.githubusercontent.com/assets/1868482/6576312/9b566d26-c736-11e4-8d74-678ddbed87d9.png)

**Comment by Ionitron** [comment]
Greetings @schnti!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3271). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3271)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by schnti** [comment]
#3279

**Comment by adamdbradley** [comment]
Duplicate: https://github.com/driftyco/ionic/issues/3279
