### ISSUE TITLE
collection-repeat 1.0.0-rc.0 - asynchronous array

### ISSUE THREAD

**Issue by rickyk586** [driftyco/ionic#3276]
Receiving this error when the result depends on an ajax call, and the view is navigated to and away from quickly:

`Error: collection-repeat tried to compute the height of repeated elements ..., but was unable to. Please provide the "item-height" attribute.`

Try switching to the Contact tab and then off of it quickly to see the error in the console:

http://codepen.io/ionic/pen/odqCz?editors=101

**Comment by Ionitron** [comment]
Greetings @rickyk586!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3276). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3276)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ajoslin** [comment]
Fixed in nightly.
