### ISSUE TITLE
feat: implement ng-model-options to allowInvalid

### ISSUE THREAD

**Issue by eislasq** [driftyco/ionic#3278]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Writing a filter that capitalice inputs, it doesn't work when it has validations, because when validation fails the model value becomes undefined.

Please do something like this https://github.com/angular/angular.js/commit/b2e146370f9c5d182f2500e637ba46edebeeb1cd</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @eislasq!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3278). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3278)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by eislasq** [comment]
Hi. I have found an alternative solution, and easy 
using "unshift" instead "push" in the line
    <code>
 modelCtrl.$parsers.unshift(capitalize);
</code>
of my <code>.directive('capitalize',...</code>
With this my directive will be executed before other directives like validations.

**Comment by ajoslin** [comment]
I don't understand what you want here. Why don't you just use ng-model-options as normal?

**Comment by eislasq** [comment]
I am trying to set allowInvalid to true whith ng-model-options but it doesnt work in ionic.

But dont worry, As I said above I have found other solution for my feature.
