### ISSUE TITLE
bug: Collection-Repeat and option/delete buttons

### ISSUE THREAD

**Issue by anwaramoon** [driftyco/ionic#3280]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>@mhartington @ajoslin

Just creating new issue as original issue is closed but it is broken. if you want to open original issue than you can close this one. But i have updated original issue too.

"
When using collection repeat and option/delete features, things get pretty funky.

http://codepen.io/anwaramoon/pen/emLbGO

Effected Version: Nightly builds.

Option Button: When you swipe on a ion-item to reveal the option buttons, as you scroll down, you will see different items also have their option buttons revealed.

Delect Button: If you attempt to delete and item, you will end up deleting two items.
"

Original issue: https://github.com/driftyco/ionic/issues/1811</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @anwaramoon!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3280). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3280)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by anwaramoon** [comment]
Thanks guys. just tested this on master and its working fine now.

**Comment by DrakenZA** [comment]
Seems broken again !

**Comment by Subodh-Garg** [comment]
Any Update please !!
When using collection-repeat, delete operation does not work on ion-item(tried both with on-swipe-left attribute and ion-delete-button directive).
FYI: It works fine with ng-repeat.
ionic --version : 1.7.14

**Comment by tskweres** [comment]
Any update? Is there a way to animate the deletion of an item in collection-repeat?
