### ISSUE TITLE
two button ng-click only click the first button

### ISSUE THREAD

**Issue by Jaware** [driftyco/ionic#3282]
<divb class="list">
  <label class="item"
           <Buttonb class=" icon  ion-plus" ng-click="add()"></Button>	       
	    <Button class="icon  ion-minus" ng-click="minus()"></Button>

when press the minus button the add button press too。。。。a bug or  ?   $scope.minus can not be called 。
![Uploading QQ截图20150311173320.jpg . . .]()

**Comment by Ionitron** [comment]
Greetings @Jaware!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3282). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3282)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @Jaware!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.

**Comment by Jaware** [comment]
the forum is  a little complicated,can you help me again?the problem is very strange,angular supports this ,however in  ionic  only one button can be bind to the controller method in a list .
