### ISSUE TITLE
bug: OLD view-title is evaluated with the NEW $state value on transition

### ISSUE THREAD

**Issue by mixersoft** [driftyco/ionic#3283]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm getting the wrong title value on a `ui-sref` state change.  I get something like this `OLD VIEW: view.NEW`

It looks like the `view-title` is being evaluated BEFORE the new view is loaded and with the new state value.

Here is a codepen: http://codepen.io/anon/pen/raqeJy?editors=101

click 'Check-in', 'Attendees', 'Check-in' and you will see the mismatch in the title: `Event Check-in - eventmenu.attendees`</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mixersoft!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3283). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3283)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mnewmedia** [comment]
Wanted to change the View Title with `$ionicNavBarDelegate.title("quak");` but it also changed the title from the view that im leaving. Should i put in a timeout 3 sec ;)

**Comment by mlynch** [comment]
Try putting it in a timeout for now, will be fixed in v2

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
