### ISSUE TITLE
bug: History Back Button can be clicked while menu is open

### ISSUE THREAD

**Issue by paulking00** [driftyco/ionic#3284]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Situation:
=======

Navigation history is enabled, and the open menu button is also visible. When the menu is opened, the user can click on the menu icon again to close the menu. The navigation back button, however is right next to the menu button, and when acidentally clicked, will both close the menu and navigate to the previous page.

Codepen:

http://codepen.io/gnomeontherun/pen/tbvdH

Steps:
====

1. Click on Scientific Facts
2. Open left slide menu
3. While menu is open, click the navigation history back button

This issue is most apparent on a phone where the menu takes up 80% of the screen.

Opinion:
=====

All buttons on the main page including the back button should be disabled while the menu isopen.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @paulking00!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3284). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3284)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adamdbradley** [comment]
Follow this codepen:
http://codepen.io/ionic/pen/QwamEW

The ion-side-menus should add `enable-menu-with-back-views="false"`:
`<ion-side-menus enable-menu-with-back-views="false">`

The back button should use the `menu-toggle="left"` attribute:
`<button class="button button-icon button-clear ion-navicon" menu-toggle="left">`

**Comment by paulking00** [comment]
Hi Adam

Thanks for the initial reply, however I think i may not have sufficiently described the issue.

I want the menu to be able to be opened from all states, thus `enable-menu-with-back-views="true"`


When you have navigated to a few different pages, and have some navigation history, the `ion-nav-back-button` is available to navigate back to the previous state.

At this point, if the side menu is opened, all buttons on the page are disabled/non-clickable EXCEPT the `ion-nav-back-button`. To close the menu, you can click anywhere on the main page and the menu will close. HOWEVER if you click on the `ion-nav-back-button`, the menu will close AND the app will navigate back to the previous page.


I am of the opinion that also the `ion-nav-back-button` should be disable/non-clickable when the menu is open.


Hopefully I have better described myself.
