### ISSUE TITLE
animated ionicons no more working

### ISSUE THREAD

**Issue by Jeff86** [driftyco/ionic#3285]
Hi there!

Just upgraded from beta-14 to rc.0 and all my animated icons are not working anymore. There is two problems:

First: when you insert animated icon (ion-load-b/a/d ie) it's no more "rolling", it's stable now
Second: I used to combine button disable + showing a loading ionicon inside it but now the icon is no more shown

Please see the codepen: http://codepen.io/anon/pen/ZYqWZy

You can see that inserting loading ionicons are just showing them stable and when you click on the button it adds the space from the span for the dedicated icon but it's not showing it. I don't know how to do it on codepen but if you use beta14 code it's working perfectly.

Do you guys have any idea?

**Comment by Ionitron** [comment]
Greetings @Jeff86!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3285). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3285)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
