### ISSUE TITLE
bug: why the window.device is undefined on android ?

### ISSUE THREAD

**Issue by striver-x** [driftyco/ionic#3287]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>The test app run successfully with 'cordova emulate android'.But i got undefined with window.device and the deviceready event doesn't happen. But ios platform don't any problems.
~~~javascript
var timer = setInterval(test, 500)

        function test() {
            if ( window.device ) {
                $('#info').html(JSON.stringify(device))
                clearInterval(timer)
            } else {
                $('#info').html(typeof window.device)
            }
        }
~~~

**Comment by Ionitron** [comment]
Greetings @striver-x!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3287). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3287)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @striver-x!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
