### ISSUE TITLE
bug: Can't start scrolling when click inside iframe

### ISSUE THREAD

**Issue by zckrs** [driftyco/ionic#3290]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Situation:
=======

Can't start scrolling when click originates of inside iframe.

Codepen:
http://codepen.io/zckrs/pen/dPgpNX

Steps:
====

1. Open left slide menu
2. Select Youtube or Twitter 
3. Try to scroll with first touch on top of iframe ==> no scroll
4. Try to scroll with first touch to outside of iframe ==> scroll

This issue is most apparent on a phone when many iframes are present and takes up 80% of the screen's width.

Opinion:
=====

A lot of issues and messages exist about this bug.

https://github.com/driftyco/ionic/issues/306
https://github.com/driftyco/ionic/issues/1151
http://forum.ionicframework.com/t/iframe-scroll-bug/196
http://forum.ionicframework.com/t/iframe-scrolling-problem/17709

I think there have been misunderstandings on the bug description between team's Ionic and reporters. 

A fix was pushed but it only corrects the navigation inside iframe. 
https://github.com/driftyco/ionic/commit/b7cd6cb1ca7cdfc245827b4c460ae67810824841

Video:
=====
https://vid.me/sPQD</span>

<span is-issue-template></span>

**Comment by uofmmike** [comment]
Agreed!

**Comment by zckrs** [comment]
Any workarounds ?

**Comment by romanrast** [comment]
same here, any solution?

**Comment by Fateicha** [comment]
Same problem here, with youtube iframe.

**Comment by MrGorki** [comment]
+1

**Comment by zckrs** [comment]
@perrygovier sorry to ping you but do you have a comment or an opinion on this issue ? :anguished:

**Comment by nickh364** [comment]
+1

**Comment by perrygovier** [comment]
This is a tricky problem to solve. The best solution is to use `overflow-scroll="true"` which has new and improved support for other Ionic features like pull to refresh and infinite scrolling. 

I'm going to spend some time looking for a way to get it to work with JS scrolling though. 

What prevents you from using native scrolling in this event?

**Comment by perrygovier** [comment]
So I've been playing with this for a while now, and the results are mixed. 

With native scrolling, scroll events bubble up from the iframe to the parent DOM. Eventually, one scrollable area says "I got this" and the scroll event stops climbing up. In javascript scrolling, unless they're on the same domain, a parent does not have access to a child iframe. It can't add event listeners or fire events on the child iframe. This prevents javascript scroll events from communicating between iframes.

So here's a few "solutions" in preferred order.

1) Use native scrolling. 
Done, yay. Grab a beer. Scrolling with iframes works.

2) Create an invisible div on top of the iframe 
Yeah, these "fixes" get ugly quick. [I created a directive called casper](https://gist.github.com/perrygovier/64f58cb7c1518ba241c4) that will add an invisible div on top of the iframe and block click events and allow scrolling. The downside is that is blocks click events. I kinda got around this by getting rid of this for 1000ms after the `touchend` event. This means that if you double click, a single click event will be let through. I was hoping I could take advantage of ghost clicks so single click events would get through, but that doesn't seem to work. 
[Here's an example.](http://codepen.io/perrygovier/pen/WvQgqj) Note that this will only work on a touch device, Chrome, even with touch events emulated will not work. (tip, start a project based on this codepen with `ionic start scrollTest http://codepen.io/perrygovier/pen/WvQgqj`)

3) Parse the html of the iframe on a server or using a cordova plugin, feed it to the app as a string and add the iframe content asynchronously. This is the enterprise solution (which would also give you great usage analytics). It's ugly, and takes a lot of work to prevent one dom from interfering with the other. Loading the content in to a web component might help prevent conflicts, otherwise the server/script that grabs the html would have to modify the markup to play nicely with the app. This works well enough if your iframe content is only coming from one place like twitter or youtube, but if it's coming from many places... it gets to be a pain quickly. 

Sorry I don't have better news, but this is a difficult problem to solve. One idea that could be worth investigating further is an iframe replacement directive that loads html asynchronously and puts it in a web component... Similar to option 3, but doing it all on the client as a directive. Might work...

**Comment by Fateicha** [comment]
Hello,

I have some questions related to your investigation in this issue.

1) Use native scrolling? Which are the counterparts on that? How did you implement it with ionic? Is this only for emulated apps? I'm using Ionic in browser without Cordova.

2) That was one of my first thoughts, for YouTube we could even try to emulate play/pause through the API, hope this works. I will extend your directive with that.

**Comment by zckrs** [comment]
@perrygovier thank you very much for your investigation

Native scroll will be my solution.

**Comment by Fateicha** [comment]
Never mind native scrolling is working i was setting it at wrong directive.

**Comment by perrygovier** [comment]
Great to hear! Sounds like this can be closed then.
I'd still like to investigate the web component idea, but it'd currently require a polyfill like polymer which unacceptably large.

**Comment by j0k3r** [comment]
Hi there, I'm working with @zckrs and since we have enable native scroll :

```js
$ionicConfigProvider.ConfigProvider.scrolling.jsScrolling(false);
```

The position isn't kept when we come back to a list, using:

```js
$ionicHistory.goBack();
```

If we use JS scrolling (just comment the first line I pasted), the position is kept.

And after some research, it seems that I'm not the only one with this problem: http://forum.ionicframework.com/t/the-ion-content-with-overflow-scroll-doesnt-maintain-scroll-position/18734/2

Any workaround about that?

**Comment by j0k3r** [comment]
Just a follow up, I've updated to the fresh 1.1.0 and it seems to work now.

**Comment by LuisOliveiraAlves** [comment]
@perrygovier Hey, thanks for writting that directive. I think it will be really useful for a lot of people. However, I've failed to understand how that directive will work with the tweets you showed on your codepen example since the tweets are only a blockquote element with a twitter-tweet class. I also noticed you didn't even use the directive on the tweet partial view there. Did you do that on purpose? 

Can you explain to me how that directive will help on allowing scrolling on those elements (embedded tweets)? 

Does the widget.js from twitter transforms those blockquotes into iframes? I tried that directive on my project (using my phone to test it) and the tweet elements are still not scrollable. I'm using the ionic scrolling, not the native one. Thanks.

**Comment by moisesnarvaez** [comment]
native scrolling works perfectly, thanks for the help :+1:
