### ISSUE TITLE
bug: Ionic-1.0.0-rc.0 - Cannot call method "contains" of undefined

### ISSUE THREAD

**Issue by revie** [driftyco/ionic#3295]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.0</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm getting a javascript error when testing some animation code on an Android 4.0.3 tablet, which says:

Uncaught TypeError: Cannot call method 'contains' of undefined at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:3162

which points to the following line in ionic.requestAnimationFrame():

   if (ele.classList.contains('button')) {

Line needs to be changed to the following, to avoid the error:

   if (ele.classList && ele.classList.contains('button')) {

Also recommend making the same changes to the classList checks a few lines before and a few lines after the line mentioned to avoid running into the error when checking for class entries of "item" or "pane" as well.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @revie!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3295). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3295)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by brayancastrop** [comment]
Hi guys, i think this issue is still there, though it's fixed for a different line to the reported.

I'm having the same issue with this line
file:///android_asset/www/lib/ionic/js/ionic.bundle.js: Line 3177 : Uncaught TypeError: Cannot call method contains' of undefined

`if (ele.classList.contains('button')) {`

 and as @revie mentioned, just need a small change to

`if (ele.classList && ele.classList.contains('button')) {`

not sure why was fixed for the other line as suggested and not for the reported one.

**Comment by rajavijin** [comment]
Guys i also get the error. In our ionic version 1.0.0 unanium. change as brayancastrop suggests can fix the issue.

**Comment by dpaloucva** [comment]
Hi,

This error happens sometimes in our app using Ionic 1.0.1. It happens at the line 23 of the minified version. I looked at it and I found 2 possible candidates:

1- Line 3179 of ionic.bundle.js version 1.1.0
```javascript
if (ele.classList.contains('button')) {  
```
2- Line 5046 of ionic.bundle.js version 1.1.0
```javascript
var isModal = container.parentNode.classList.contains('modal');
```

Hope this helps!

**Comment by revie** [comment]
Thanks @dpaloucva.  In addition to your two, it looks like there's another one that is just like your #2, but on line 7189 in ionic.bundle.js v1.1.0:

   var isModal = container.parentNode.classList.contains('modal');
