### ISSUE TITLE
Reopening #3250: bug: rc-0 version: swipe left to go back doesn't work properly

### ISSUE THREAD

**Issue by reviyou** [driftyco/ionic#3296]
Can you please reopen 3250 which is not closed looks like? I want to keep conversation going with an open ticket at least till we find a proper workaround....

**Comment by Ionitron** [comment]
Greetings @reviyou!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3296). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3296)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
