### ISSUE TITLE
docs: Debug ionic application 

### ISSUE THREAD

**Issue by tal1234l** [driftyco/ionic#3297]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello could you please refer me to a guide 
on how i can debug the ionic app and mostly the core phone capabilities like camera and accelerator
If you have some guide i would love reading it :)

Thank you and keep up the Gooood work </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @tal1234l!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3297). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3297)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Hello, I believe http://ionicframework.com/docs/guide/testing.html and https://developer.chrome.com/devtools/docs/remote-debugging might be useful for you.
