### ISSUE TITLE
bug: ng-class not working on ion-tab

### ISSUE THREAD

**Issue by revie** [driftyco/ionic#3305]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I've noticed that the &lt;ion-tab&gt; directive is stripping out the "ng-class" directive when building the tabs.  Codepen:

http://codepen.io/revie/pen/azRGBo

Visiting any tabs for the second time is supposed to turn the tab's icon green, but as you can see in the resulting HTML, the ng-class is stripped out of the rebuilt &lt;a class="tab-item"&gt; replacements and not being applied to the tabs.  "ng-class" seems to work on the &lt;ion-tabs&gt; directive, just not the individual &lt;ion-tab&gt; items themselves.

Looks like this has been an issue for a while.  There are a few mentions of the problem in the forums, such as:

http://forum.ionicframework.com/t/ng-class-with-ion-tab/13101
http://forum.ionicframework.com/t/badge-tabs/2326

and seems to still be the case with the latest nightly.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @revie!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3305). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3305)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @revie!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by revie** [comment]
Sorry Ionitron.  Seems to still be an issue.

**Comment by mhartington** [comment]
This would

**Comment by Ionitron** [comment]
Greetings @revie!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
