### ISSUE TITLE
feat: [feat] Collection repeat gutter

### ISSUE THREAD

**Issue by GistCode** [driftyco/ionic#3309]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi guys, I'd like to ask for a feature to add a gutter directive to collection-repeat similar to the functions of the material gridlist

https://material.angularjs.org/#/api/material.components.gridList/directive/mdGridList

Justification of this request

While it is entirely possible to add css rules to implement this feature it is definitely better to have it built upon the directive for more control, in addition to IE compatibilities

Thanks

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @GistCode!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3309). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3309)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Moving this to our trello board and closing the issue.

https://trello.com/c/Koo6Vlsr/95-gutters-for-collection-repeat
