### ISSUE TITLE
bug: Dark overlay in popup breaks when chaining with $q

### ISSUE THREAD

**Issue by armed10** [driftyco/ionic#3310]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I couldn't find this on the forum or in issues, though it may have been reported under another name.

The dark overlay surrounding a popup breaks if you chain 2 popups together with $q, as per example here: http://codepen.io/armed10/pen/OPBrpx/

I've tested this with Beta-14, rc0 and nightly builds, in browser as well as on iPad 2. The dark overlay disappears and does not reappear anywhere in the app (when calling another popup or loading screen).

Right now I'm looking into alternatives to work around this, using the promise returned by the popup itself does work.

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @armed10!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3310). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3310)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by armed10** [comment]
I've been able to work around this by using the promise returned by the popup in combination with a $q.defer() promise.

The issue was that I don't always show a popup. For instance, if an item isn't saved, show a popup. if not, don't.
If I show the popup -> use the popup promise, else -> create a promise with $q and resolve it, the overlay does not break. 

I could provide another codepen with the workaround if requested.

**Comment by Ionitron** [comment]
Greetings @armed10!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
