### ISSUE TITLE
bug: Constant repainting seems to affect performance

### ISSUE THREAD

**Issue by ryanricig** [driftyco/ionic#3313]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi - there seems to be a constant repainting happening in the latest version of Ionic.

This wasn't present in earlier versions of Ionic, and our performance/memory issues seem to be exacerbated by this.

Some details:

-We are using the latest rc version of Ionic (we have also tried the nightly)
-We are using collection-repeat to scroll a facebook-like timeline of images
---Note that this constant layout invalidation and repainting seems to be associated with the zynga scroller code, but it happens even when we are not on a screen containing collection-repeat.  
-It happens regardless of whether the user is interacting with the app, so even when the app is left idle, this constant repainting is going on.

Any guidance would be appreciated.

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ryanricig!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3313). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3313)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ryanricig** [comment]
Here is a screenshot of the timeline.  Nothing is happening on the screen, interaction wise.  This continues regardless of which screen I'm on in the app:

![web_inspector_ _sarah_sachs s_iphone_ _chanelinspire_ _index_html](https://cloud.githubusercontent.com/assets/1425113/6656544/06185b12-cb04-11e4-9548-2db3f7048467.png)

**Comment by ryanricig** [comment]
Determined this was the new loading spinner.

**Comment by jabyrd3** [comment]
I'm seeing this issue as well. I am going to raise a new issue.
