### ISSUE TITLE
docs: Clarification: Steps for App Store acceptance

### ISSUE THREAD

**Issue by irthos** [driftyco/ionic#3314]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm building an angular/firebase ionic app and intend to offer iOS version on App Store. Is there anything I should keep in mind considering all the data is on firebase or best practices discovered?

Thanks!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @irthos!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3314). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3314)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Each platform and distribution method has their own guidelines. For Apple, the biggies in your case would be that the app still function when offline, even if there's no data to display. 

Here's the full list
https://developer.apple.com/app-store/review/guidelines/

**Comment by irthos** [comment]
Cheers Perry
