### ISSUE TITLE
bug: ion-nav-bar

### ISSUE THREAD

**Issue by emps** [driftyco/ionic#3315]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span>  

<span ionic-description>ion-nav-bar get reloads while moving from state to other state
while ion-nav-bar is not inside the ion-nav-view

    <ion-side-menu-content  drag-content="false">
        <ion-nav-bar class="color-wet-asphalt">
            
            <ion-nav-buttons side="left">
                <button side="left" class="button button-icon button-clear ion-navicon pull-left" menu-toggle="left"></button>
            </ion-nav-buttons>
            <ion-nav-buttons side="right">
                <button side="right" class="button button-icon button-clear ion-navicon pull-right" menu-toggle="right"></button>
            </ion-nav-buttons>
        </ion-nav-bar>
        <ion-nav-view name="menuContent"></ion-nav-view>
    </ion-side-menu-content>
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @emps!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3315). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3315)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by emps** [comment]
seems happening with android only ... as i see in debug of chrome

**Comment by Ionitron** [comment]
Greetings @emps!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
