### ISSUE TITLE
swipe to go back doesn't work if previous page is not cached

### ISSUE THREAD

**Issue by reviyou** [driftyco/ionic#3316]
you have <ion-view  cache-view="false"> on page A and go to the nested page and swipe left to go back to page A:

expected - invoke stateProvider for state A(hit controller etc)
actual - it goes to a blank page since it doesn't use stateProvider and jus trying to return to the previously cached page

**Comment by Ionitron** [comment]
Greetings @reviyou!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3316). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3316)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by reviyou** [comment]
issue is there: https://github.com/driftyco/ionic/issues/3317
