### ISSUE TITLE
feat: suggestion : created a demo purpose android chat application

### ISSUE THREAD

**Issue by melvin0008** [driftyco/ionic#3320]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Created a chat application using ionic and socket.io  at [https://github.com/melvin0008/ionic-socketio-chat-client/](https://github.com/melvin0008/ionic-socketio-chat-client/) . How can i contribute this to the ionic community</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @melvin0008!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3320). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3320)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Nice! Send an email to katie@drifty.com. I think this would make a great guest blog post. Tell her I recommended it be a guest blog post.

**Comment by melvin0008** [comment]
Thanks. :)
