### ISSUE TITLE
bug: ActionSheet buttons left margin

### ISSUE THREAD

**Issue by anwaramoon** [driftyco/ionic#3321]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>ActionSheet buttons left margin is not correct on android devices. Please see attached screen shot. Margins are fine in chrome and ios perhaps due to different design. 

Also is there any way to show icons in the action sheet for each button?

![screenshot_2015-03-14-22-00-01](https://cloud.githubusercontent.com/assets/1743538/6653796/05b99996-ca97-11e4-9f99-2f7c571971ff.png)

Thanks
Anwar</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @anwaramoon!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3321). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3321)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @anwaramoon!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
