### ISSUE TITLE
bug: tabs-item-hide not working

### ISSUE THREAD

**Issue by vchav73** [driftyco/ionic#3322]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When setting the tabs-item-hide class for an ion-view inside a tab bar the tab bar still shows. See http://codepen.io/anon/pen/MYzwEa. The first "Facts" view has the tabs-item-hide class set but the tab bar is still showing.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vchav73!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
