### ISSUE TITLE
bug: Problem with inputs in a x-direction ion-scroll

### ISSUE THREAD

**Issue by tsurrel** [driftyco/ionic#3323]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>When having some inputs inside a x-direction ion-scroll (no y scrolling) itself inside a standard ion-content, that scroll-view gets resized when the focus gets in one input. This is an incorrect behavior.

It seems the problem comes because ionic is trying to make sure, on iOS, that the keyboard doesn't cover the input we are in and do some resizing of the view for this. But the resizing is done to the direct container of the input without checking that this scroll-view is the "main" one (i.e. the scroll-view linked to the whole page, not the x-direction scroll-view).

Note that you can reproduce the problem in Chrome using the "device mode" set on a iPhone.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @tsurrel!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
