### ISSUE TITLE
What is the best way not to repeat ion-nav-buttons actions across controllers?

### ISSUE THREAD

**Issue by vasconcelloslf** [driftyco/ionic#3325]
Hi.

In this line https://github.com/driftyco/ionic/blob/master/js/angular/directive/navButtons.js#L38 I learn that I can define inside the current <ion-view> which buttons will appear on the <ion-nav-bar>, and that's great. But my question is, what's the best way to avoid defining a ```doSomething()``` function across all my controllers? Is it ok to put create a parent controller just for that, or there are better solutions?

Thank you.

**Comment by Ionitron** [comment]
Greetings @vasconcelloslf!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3325). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3325)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
