### ISSUE TITLE
bug: [with solution] iOS header bar bar-positive background overlaps the system top bar

### ISSUE THREAD

**Issue by Zorgatone** [driftyco/ionic#3329]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I've been trying to use different header bars for my modals with ionic.
From what I've seen on iOS (need testing on other devices) the header bar is behind the system top bar, which is transparent. That means that if I have header bar with a different background I will see the system top bar with a color different from the system one (which imo shouldn't be changed).

I made a quick-fix including a conditional css just for iOS, which sets a filler background-image with repeat-x to force the system bar default color, and allowing the ionic header-bar to be with a different background color.

my bad JS (should be possible to add it when building the app):
```
(function (d, s) {
    var css, link = d.getElementsByTagName(s);
    link = link[link.length - 1];
    if(window.device && window.device.platform && window.device.platform === 'iOS') {
        console.log('^_^');
        css = d.createElement(s);
        css.href = "css/iOS.css";
        css.rel = "stylesheet";
        link.parentNode.insertBefore(css, link.nextSibling);
    }
}(document, 'link'));
```

CSS:
```
.bar.bar-header {
    background-image: url("../img/filler.gif") !important;
    background-repeat: repeat-x !important;
    background-position: right top !important;
}
```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Zorgatone!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3329). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3329)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Zorgatone** [comment]
Solved using using this: http://learn.ionicframework.com/formulas/customizing-the-status-bar/
