### ISSUE TITLE
Bug: states navigation

### ISSUE THREAD

**Issue by alanschlindvein** [driftyco/ionic#3331]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In project, I have de following states and its transitions:
1 -> 2
1 -> 3
2 -> 1
2 -> 3
3 -> 1
3 -> 2

2 is the main state, I can go to any state in my app from it. So, after I reach this state the back button no longer exist on the screen and I have buttons e list elements to others states.
Well, the bug happens when I'm on state 1, go to state 3 and after that I go to state 2. Once on this state, I have no Back Button, then I go to state 3 with $state.go(...), but when I tap on back button the app goes to state 1 and not to state 2 as it should.

I have no idea what is happening.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @alanschlindvein!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3331). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3331)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Hey @alanschlindvein, there's a couple of edge cases with navigation that we're trying to nail down. Could you provide us with a codepen or sample project? How these events fire can change depending on how a project is set up.

**Comment by Ionitron** [comment]
Greetings @alanschlindvein!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
