### ISSUE TITLE
bug: ion-nav-buttons in abstract view not working

### ISSUE THREAD

**Issue by mortenbock** [driftyco/ionic#3332]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When adding a ion-nav-buttons in an abstract view, the buttons are not included in the header. If the ion-nav-buttons is included in a regular view, then it is.

This behavious seems to have changed from beta13 to beta14/rc0.

Codepen with example:

http://codepen.io/anon/pen/XJxoLb

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mortenbock!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3332). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3332)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Which makes sense, since you're not actually navigating to that abstract view, but the view that gets rendered inside of it. 

This changed in beta 14, where navigation was restructured.

**Comment by martin-kral** [comment]
Hi Mike,
It doesn’t make much sense when using abstract view with simple `ui-view` directive - i.e when I’d like to change only part of the abstract view depending on the concrete inner state (without navigation to another view).

```
<!-- Abstract view -->
<ion-view>
	<ion-nav-buttons>
		<!-- Nav buttons -->
	</ion-nav-buttons>
	<ion-content>
		<!-- Common part of the abstract view -->
		<!-- ... -->

		<!-- Part of the view which differs according to the concrete state -->
		<div ui-view></div>
	</ion-content>
</ion-view>
```
