### ISSUE TITLE
feat: Ionic components as .svg or .ai for mockups?

### ISSUE THREAD

**Issue by danielzzz** [driftyco/ionic#3333]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi, 

I was wondering if it's possible to get ionic components as svg or ai elements.
Something like this http://www.sketchappsources.com/resources/source-image/Ionic-iOS-Wireframe.png
but in svg or ai format.

We need this to create mockup designs for our projects.

thanks, dan</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @danielzzz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3333). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3333)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Maybe @bensperry would like to chime in on this?

**Comment by simo2409** [comment]
:+1:

**Comment by perrygovier** [comment]
At this point, most of our designs have been modified from their original designs, and the illustrator files no longer match up. We'd gladly share them if anyone was so inclined to make designs that match our current version.

**Comment by mathiasburton** [comment]
I'd be up for helping if you share them out
