### ISSUE TITLE
bug: Possible bug with nav-direction="back"

### ISSUE THREAD

**Issue by dyegonery** [driftyco/ionic#3335]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I'm using a nav-button that mannually send user to a page.
The problematic code is in this codepen: http://codepen.io/anon/pen/JoeyNP

The problem is with the button that send me to other page with "back" direction. When i use the button, this error is shown to me: "ctrlB is null".

Tracking the error, i find out his origin, in the leave function of ionic.bundle.js, at line 43277.
Here's the original function:
function leave(ctrlA, ctrlB, step) {
      if (!ctrlA) return;
      var titleX = (-(ctrlA.titleTextX() - ctrlB.backButtonTextLeft()) - (ctrlA.titleLeftRight())) * step;
      setStyles(ctrlA, 1 - step, titleX, 0);
    }

To solve my problem, i added the ctrlB to first condition. This way, the function now is this way:
function leave(ctrlA, ctrlB, step) {
      if (!ctrlA || !ctrlB) return;
      var titleX = (-(ctrlA.titleTextX() - ctrlB.backButtonTextLeft()) - (ctrlA.titleLeftRight())) * step;
      setStyles(ctrlA, 1 - step, titleX, 0);
    }

This seems to have solved the problem. Someone else has experienced the same problem?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @dyegonery!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3335). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3335)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
It looks like your codepen has changed. It no longer matches your description. Could you revert it?

**Comment by Ionitron** [comment]
Greetings @dyegonery!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
