### ISSUE TITLE
Popup graphic damaged?

### ISSUE THREAD

**Issue by Animion** [driftyco/ionic#3336]
Popup look like damaged css... Check it here http://ionicframework.com/docs/api/service/$ionicPopup/

![snimka obrazovky 2015-03-16 o 21 00 46](https://cloud.githubusercontent.com/assets/93915/6675285/ad0acff6-cc1f-11e4-871b-668e4391e75c.png)

**Comment by Ionitron** [comment]
Greetings @Animion!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3336). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3336)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by spyjo** [comment]
Bug already reported here: https://github.com/driftyco/ionic/issues/3204

**Comment by perrygovier** [comment]
Closing as a duplicate
