### ISSUE TITLE
bug: ionToggle switch on android in rc0 and rc1 styled as material

### ISSUE THREAD

**Issue by alexkb** [driftyco/ionic#3339]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Since the last ionic update from v1.0.0-beta.14 to v1.0.0-rc.0/rc.1 the <a href="http://ionicframework.com/docs/api/directive/ionToggle/">ionic toggle</a> widgets on Android has changed from the expected iOS7 style:
![ios7 toggle](http://www.ellak.ca/wp-content/uploads/2013/06/iOS7-toggle.png)

To the new [material design](http://www.google.com/design/spec/components/switches.html#switches-switch) style:
![material toggles](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7NDg4aGIzVXYxVEE/components_switches_switch1.png)

I've tested the issue by going back to beta.14 and after compiling the issue is gone.

Note: I was testing on a Nexus 5 with Android 5.0.1 so this might be the issue.</span>
<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @alexkb!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3339). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3339)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Android style toggles on Android, for shame!
You can force iOS style by giving the toggle a `class="toggle-large"` class, or you can set it globally with the config provider: `$ionicConfigProvider.form.toggle('large');`.

Here's an example of it being set with the configProvider: http://codepen.io/perrygovier/pen/bNOLyJ?editors=101
