### ISSUE TITLE
Installing crosswalk - cordova plugins getting removed

### ISSUE THREAD

**Issue by do-web** [driftyco/ionic#3341]
If i install crosswalk i must reinstall all cordova plugins

**Comment by Ionitron** [comment]
Greetings @do-web!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3341). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3341)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
