### ISSUE TITLE
Orientation change doesn't update cached collection-repeat views

### ISSUE THREAD

**Issue by netalico** [driftyco/ionic#3344]
I've found that if you use collection-repeat and you rotate your device while on another tab then when you go back to the original tab its stuck assuming the width of the previous orientation so it looks weird. For now I just put in place this workaround that clears my view cache whenever the device rotates.
```
window.addEventListener("orientationchange", function() {
    $ionicHistory.clearCache();
  }, false);
```

**Comment by Ionitron** [comment]
Greetings @netalico!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3344). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3344)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
