### ISSUE TITLE
docs: Material Design implementation

### ISSUE THREAD

**Issue by Kinnonii** [driftyco/ionic#3351]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi there,

There is a ionicmaterial implementation but I'd like to use AngularJS Material implementation. Would it work nicely?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Kinnonii!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3351). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3351)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Ionic Material is pretty cool. Ionic is moving towards making Material Design naturally part of Ionic, but we've still a ways to go. We actually worked on the Angular Material project, but the codebases are substantially different. I don't think they'd intermingle very well. You'd have to migrate things component by component, at which point, you'd have Ionic Material anyway. 

Since it's not really a bug, I'm going to close the issue, but you may want to check out this conversation in the forums: 
http://forum.ionicframework.com/t/is-there-a-tutorial-for-using-ionic-and-angular-material/14662
