### ISSUE TITLE
bug: Side menu autoclosing when expose-aside-when

### ISSUE THREAD

**Issue by grillorafael** [driftyco/ionic#3353]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi guys!

I'm using RC0 and my sidemenu is autoclosing when I open in a small device.

I have ```expose-aside-when="large"``` on meu ion-side-menu.

When I'm using in a large device works properly but when I'm on a cellphone the menu closes right after I open it.

I fixed editing the exposeAsideWhen directive but I don't know if this is the correct approach. If its ok I will create a pull request for it.

```javascript
function checkAsideExpose() {
        var mq = $attr.exposeAsideWhen == 'large' ? '(min-width:768px)' : $attr.exposeAsideWhen;
        var matched = $window.matchMedia(mq).matches;
        if(matched) {
            sideMenuCtrl.exposeAside(true);
            sideMenuCtrl.activeAsideResizing(false);
        }
      }
```

I just run the exposeAside when I match the media query.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @grillorafael!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3353). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3353)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by JoeKomputer** [comment]
+1 I'm running into the same problem.

**Comment by ohh2ahh** [comment]
This is fixed via 4f35d8e in 1.0.0-rc.1.

**Comment by mhartington** [comment]
@grillorafael and @JoeKomputer can please test out RC1 and confirm this fixes your issue

**Comment by grillorafael** [comment]
@mhartington 

rc1 is working correctly!

Thank!
