### ISSUE TITLE
bug: ios-sim 2.0.1

### ISSUE THREAD

**Issue by piclez** [driftyco/ionic#3354]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello,

Hi I'm still running non Yosemite OS so only Xcode 5.1 instead of 6 so I can't get ionic emulate ios to work:

Cordova needs ios-sim version 3.0.0 or greater, you have version 2.0.1

I can't update ios-sim to 3.0 since it only works with Xcode 6.

Any other ideas please?

cordova -v
4.3.0

ionic -v
1.3.16

Thanks,

Peter
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @piclez!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3354). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3354)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
You'll need to downgrade your version of cordova or upgrade your OS.
Closing as this is not an issue with ionic.

**Comment by piclez** [comment]
Hi Mike,

I downgraded cordova to 4.1.2 and still same message. What version shall I downgrade to have it working with OS 10.8.5 and XCode 5? I can't find it.

Thanks again.

**Comment by mhartington** [comment]
http://cordova.apache.org/announcements/2014/11/06/cordova-ios-3.7.0.html
