### ISSUE TITLE
bug: Unable to paste on iOS, after upgraded to rc0 and rc1

### ISSUE THREAD

**Issue by kinhunt** [driftyco/ionic#3358]
Input[text] and Input[textarea] are not able to be pasted (also to select) on iPhone 5 and iPhone 6 (both iOS 8.2). Works fine on Android.

**Comment by Ionitron** [comment]
Greetings @kinhunt!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3358). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3358)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
We're not having this issue. Are you able to share any more info?

**Comment by kinhunt** [comment]
Cannot reproduce.
