### ISSUE TITLE
bug: SASS StringScanner::Error: regexp buffer overflow

### ISSUE THREAD

**Issue by jadjoubran** [driftyco/ionic#3361]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I tracked the error and it turned out to be caused by the selector in this file https://github.com/driftyco/ionic/blob/master/scss/ionicons/_ionicons-icons.scss from line 1 to 737

Ruby version: ruby 1.9.3p551 (2014-11-13) [i386-mingw32]

Sass version: Sass 3.4.13 (Selective Steve)

Ionic version: 1rc0 and/or 1rc1

I suggest breaking down the selector for it to work

P.S.: Even sublime's regular expression does not treat this as a valid css selector (I know this is not important but it's inline with what happened with SASS compiler)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jadjoubran!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3361). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3361)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jadjoubran** [comment]
It turned out we had an internal issue:
we included ionicons and ionic so the fonts css was included twice which caused the following error because of the 700 lines css selector
