### ISSUE TITLE
feat: Add spinner-small for all spinners

### ISSUE THREAD

**Issue by felquis** [driftyco/ionic#3366]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Today only `ios` has a `ios-small` version, would be great a small version of all spinners.

To use the default icon of each platform and small.
```html
<ion-spinner class="spinner-small"></ion-spinner>
```

**Comment by perrygovier** [comment]
You can use regular CSS to change spinner dimensions:
http://codepen.io/perrygovier/pen/WbPOGq

We added the ios-small because it's pretty common in native UIs. I think the others are rare enough that it's best to let CSS do any custom sizing. 

If more people chime in saying there's a demand for it, we can reconsider. 

Thanks

**Comment by felquis** [comment]
Thank you @perrygovier,

I think this is something nice to have as a utility class.

Thanks for the quickly response.
