### ISSUE TITLE
bug: $ionicActionSheet from ionic 1.0.0-rc1 not rendering properly on android

### ISSUE THREAD

**Issue by vlad-bezden** [driftyco/ionic#3368]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>In Ionic 1.0.0-rc1, Action Sheet works fine in Chrome, but doesn't render properly on Samsung S5 Android 5.0. It used to work fine with v1.0.0-beta14.

Here is how it looks like on device
![image](https://cloud.githubusercontent.com/assets/10314673/6765553/eac587a2-cfba-11e4-90cd-be2c91672e8d.png)

And here is how it looks like in Chrome:
![image](https://cloud.githubusercontent.com/assets/10314673/6765560/6af0ce6e-cfbb-11e4-9f6f-7a37d9726b7d.png)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vlad-bezden!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3368). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3368)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by anwaramoon** [comment]
https://github.com/driftyco/ionic/issues/3321

**Comment by perrygovier** [comment]
Ionic automatically applies platform specific styles. With the `ionic serve` command, it will default to iOS styles. If you want to see both iOS and Android styles, use the lab flag: `ionic serve --lab` to see both styles. The left margin on the android style should be fixed though.  That's covered by #3321

**Comment by stianjensen** [comment]
Is there some way to force the iOS look on android devices?

**Comment by JoeyHoutenbos** [comment]
Can the iOS look be forced? And indeed the margins should be fixed...
