### ISSUE TITLE
input type="tel" hides nav-bar

### ISSUE THREAD

**Issue by ikkentim** [driftyco/ionic#3369]
When using `input type="tel"`, the nav-bar scrolls up and out of sight.
`type="input"` (Test 1)
![](http://imgur.com/1TfJIty.jpg)

`type="tel"` (Test 2)
![](http://i.imgur.com/Yp2KM51.jpg)

**Comment by Ionitron** [comment]
Greetings @ikkentim!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3369). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3369)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ikkentim** [comment]
Aparently it is an issue on my end; while making a codepen it didn't happen.
