### ISSUE TITLE
Cannot triger click event on a button next to an input element

### ISSUE THREAD

**Issue by zwz** [driftyco/ionic#3370]
The issue exists for a long time (http://forum.ionicframework.com/t/button-next-to-an-input-not-clickable/4142/12).

You may check this codepen out in your browser:
http://codepen.io/mhartington/pen/oBwln
or 
http://plnkr.co/edit/rDBxTQDLz9pnKocqNqSd?p=preview

**Comment by Ionitron** [comment]
Greetings @zwz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3370). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3370)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by zwz** [comment]
Yes, I had already tried to submit the issue through the form.
But I am behind the Great Fire Wall.
As a result, the form is not usable at all.
I hope somebody can submit the issue for me. 
It is not related to the device or OS. 
And it is reproducible in a browser with the codepen above.

**Comment by perrygovier** [comment]
It's working fine for me now. I believe this issue is resolved.
