### ISSUE TITLE
bug: Empty area when "spinner='none'" for ion-refresher

### ISSUE THREAD

**Issue by sikron** [driftyco/ionic#3372]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,
i am implementing my own loading overlay, so i want no spinner displayed at all for pull-to-refresh. When i now use "spinner='none'" as attribute of the ion-refresher, no spinner is displayed (good), but the area where the spinner used to be is still there as empty area (bad), as long as the refreshing takes.
In my opinion, for "spinner='none'", also the area should not be displayed.

Maybe related to #2926 </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @sikron!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3372). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3372)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Well, the wrapping element needs to exist to contain the pulling icons, but are you saying it shouldn't pause at 50 or so px until the `complete` event fires?

**Comment by sikron** [comment]
Hi, thx for answering!
You are right. I made a picture, though, to be absolutely clear: 
The green arrow points to my loading animation (because of which i don't want the pull-to-refresh spinner). The read rectangle is, where the empty spinner area is. After pulling, the area stays until the 'scroll.refreshComplete' event is broadcasted. Afterwards it goes aways and my content begins at the very top of the page.
![empty-spinner-area](https://cloud.githubusercontent.com/assets/2979076/6810970/d1490ba8-d264-11e4-89e3-9b29d71f9a00.png)

**Comment by khfayzullaev** [comment]
@sikron, thanks for pointing out this issue. I have the same problem. Moreover, @perrygovier, this [issue](http://forum.ionicframework.com/t/ion-refresher-animation-bug/19747) is also related to this category of problems.

**Comment by grrrian** [comment]
+1

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by zookz** [comment]
+1

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
