### ISSUE TITLE
bug: Collection : last item not visible (RC version)

### ISSUE THREAD

**Issue by Alkashi** [driftyco/ionic#3373]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

I just updated the ionic version on my project and now have this bug : 
I have a collection with items that having dynamic and different height. With the last version of ionic, the last item is not entirely visible. It just cut on the bottom. I can see it if I over scroll but not when I release the mouse.

note : the datas are loaded from a sqlite database = asynchronously 

Thanks guys.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Alkashi!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3373). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3373)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Can you provide a demo of this?

**Comment by Alkashi** [comment]
Well, I have to extract a part of my huge app for this.
I'll try to make it quickly to provide it here as soon as it's done.
Thx.

**Comment by Alkashi** [comment]
Hi,
Sorry for the delay. 
You can see what I mean in the chats tab here : http://houcin1.free.fr/dev/ionic/#/tab/chats
Each item has a different height
If you you scroll at the bottom you'll see that sometimes, its not entirely visible.

The ionic version used here is the 1.0.0-rc.2

Thanks in advance for your feedback

**Comment by Zozos** [comment]
I have a similar problem. The last element of collection-repeat gets clipped.

**Comment by mhartington** [comment]
Hmm, just tested this with the nightly builds and wasn't able to reproduce it. Could you verify that it was fixed there?

**Comment by Ionitron** [comment]
Greetings @Alkashi!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
