### ISSUE TITLE
bug: Ionic View showing only old version

### ISSUE THREAD

**Issue by fakiolinho** [driftyco/ionic#3380]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi, i can upload the app quite successfully with `ionic upload` but have some issues in viewing the latest uploaded app copy. The very first time i ve tested the app with my iphone everything was fine. After done some further development and testing on ios emulator, i pushed again with `ionic upload` the app and followed => sync to latest => view app without success. Unfortunately the old version was shown while its meta data were updated (date/time etc). I retried by erasing the app and uploading a new copy without success too. Also i forgot to mention that i did clear app data too. Every time i can only view the very first copy i ve uploaded, no matter what procedure i follow and what copy i upload. I ve checked that every time the id is the same even if i erase the uploaded app copy and try to upload a new one.

Thanks in advance for your time.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @fakiolinho!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3380). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3380)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by fakiolinho** [comment]
After typing `ionic link --reset` and then `ionic upload` the new copy was uploaded successfully and i could test it on my iPhone. Is this the way this should work?

**Comment by ParitoshVaidya** [comment]
Did you try following commands?

ionic build ios
ionic run ios

**Comment by fakiolinho** [comment]
Yes i missed `ionic run ios` just tested and works fine.

Thanks for your great job
