### ISSUE TITLE
bug: Collection Repeat Broken On RC V1

### ISSUE THREAD

**Issue by saniyusuf** [driftyco/ionic#3382]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I Just upgraded to v1.0.0-rc.1. I was on beta 14 previously before that. I have a collection repeat which was working fine. After the upgrade, it seems the collection repeat is now broken because after I scroll around 10 items, I start seeing items that were already there before and then empty entires before
 I start scrolling into a blank space. 

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @saniyusuf!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3382). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3382)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by toddhalfpenny** [comment]
Is it possible to see this in a CodePen (or similar)?
I have working collection-repeats (with 100s of items) in RC-0, so it would be good to spot what could be up.

**Comment by ajoslin** [comment]
Yes, please post a codepen. I'm not seeing any problems.

**Comment by saniyusuf** [comment]
A code pen is going to be thought because the collection repeat is working with a custom component of mine. I am trying to upload a video to demonstrate the behaviour.

**Comment by saniyusuf** [comment]
Here we go for a video @ajoslin  @toddhalfpenny  https://www.youtube.com/watch?v=s8oZnzKFuko&feature=youtu.be

**Comment by stellasoft-will** [comment]
the problem you might find is that you need to recompile your sass files in order to get the css needed for the collection repeat to work.

**Comment by Fayozjon** [comment]
stellasoft-will

http://workservis.ru/pribyl

24.03.2015, 19:24, "stellasoft-will" <notifications@github.com>:the problem you might find is that you need to recompile your sass files in order to get the css needed for the collection repeat to work.

**Comment by perrygovier** [comment]
That's definitely a problem. Is collection-repeat necessary? Perhaps native scrolling will work better and not have the updating/watch cycle issues we're seeing.  Is anyone else seeing this?  It'll be difficult to fix without being able to reproduce it.

**Comment by saniyusuf** [comment]
I am currently investigating to ensure that this error has nothing to do with my setup 100% and also trying some of your feedback. After this is done, I will try and work on a demo to reproduce this on a code pen

**Comment by saniyusuf** [comment]
Sorry guys, I have found the problem. School boy error on my side. I did not recompile my SASS so the new collection repeat styles were not present. All solved now
