### ISSUE TITLE
bug:  ion-content insite $ionicPopup with input elements - scroll bug

### ISSUE THREAD

**Issue by do-web** [driftyco/ionic#3386]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>If a input got the focus the ion-content scrolls always to the bottom.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @do-web!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3386). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3386)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Thanks @do-web, I understand your description, but could you put together an example we can test a fix against?

**Comment by Fayozjon** [comment]
Dominik

http://wondrew.net/kacestvo

24.03.2015, 00:39, "Dominik Weber" <notifications@github.com>:If a input got the focus the ion-content scrolls always to the bottom.

**Comment by Ionitron** [comment]
Greetings @do-web!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
