### ISSUE TITLE
bug: feat: Disable inherit item height in collection-repeat with grid view.

### ISSUE THREAD

**Issue by Fulkman** [driftyco/ionic#3387]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Is there any way to make this work? (workaround?)
http://jsfiddle.net/npb8omsz/1/

I want to item which 'item-height' set to a value to obey that height.
Now items in a 'row' inherit 'item-height' from item in first column and ignore it's own height.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Fulkman!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3387). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3387)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
It's not really that items are not being sized correctly, but that rows are taking the height of the first item in the row, and the items are being covered up by subsequent rows.

@ajoslin is going to take a look and see if we can get rows to take the height of the tallest item in that row without too much of a performance hit. 

Note, this will mean that each row will take the height of the tallest item in that row.  They wont gravitate upwards like in [masonry](http://isotope.metafizzy.co/layout-modes/masonry.html).

**Comment by Fulkman** [comment]
Thank you for the quick reply.

It is exactly as you say. Solution that you propose is the most acceptable.
I'm fully aware of masonry and i didn't expect that kind of behavior.

**Comment by Fayozjon** [comment]
Tomasz

http://control-intern-managerial.ro/utrader-instaforex

24.03.2015, 13:23, "Tomasz Pietrzak" <notifications@github.com>:Is there any way to make this work? (workaround?)


I want to item which 'item-height' set to a value to obey that height.
Now items in a 'row' inherit 'item-height' from item in first column and ignore it's own height.
