### ISSUE TITLE
bug: $ionicConfigProvider.scrolling.jsScrolling(false) cause scroll not working with opened keyboard

### ISSUE THREAD

**Issue by loicfavory** [driftyco/ionic#3393]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I installed com.ionic.keyboard.
When I user $ionicConfigProvider.scrolling.jsScrolling(false); to use native scroll, scroll is not working when keyboard is opened</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @loicfavory!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3393). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3393)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by iceman3000** [comment]
Same issue for me. Samsung S4.

**Comment by jandouwevonk** [comment]
Problem also on Samsung Galaxy Tab 4 10.1 (Ionic v1.0.0-rc.2)

**Comment by superandrew** [comment]
I have this problem on Samsung Core android 4.4

**Comment by mlynch** [comment]
Should be fixed here in 1.2 Please reopen if not the case.
