### ISSUE TITLE
bug: Background disappears when open a popup from another popup

### ISSUE THREAD

**Issue by goncaloSemedo** [driftyco/ionic#3394]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello,

I am having a little problem and I hope you can help me.

Everytime that I open a popup from another popup, the black background disappears, and only appears again if I refresh the page.

Here is an example:
http://codepen.io/semedo/pen/EarmdP

Thanks in advance.
Gonçalo Semedo</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @goncaloSemedo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3394). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3394)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
This is due to some necessary async in backdrop logic. Opening the second popup in a `$timeout` resolves the issue. Here's an example. 
http://codepen.io/perrygovier/pen/vEozrW?editors=101
