### ISSUE TITLE
More abstraction for the CSS framework

### ISSUE THREAD

**Issue by manuelro** [driftyco/ionic#3395]
Guys, I think this project rocks. It's amazing how easy it is to create a new project and build it for multiple platforms. But I do also think the CSS framework you created needs to reach the next level of abstraction.

Today I was developing an app that required a text input inside a list, aligned to the right inside the item, but found out that putting a form that way required a lot of CSS for something that can be done simply when using Bootstrap, for instance.

One thing I noticed is that the ionic's CSS framework doesn't have a `.form-control` to clean and pre-format the form elements, this is especially handy to avoid conflicts between looks and feels for form elements. 

Another thing I also noticed is that there are some behaviors that can be abstracted event more, for example, the `.item-icon-left` and `.item-icon-right` list classes, the thing here is that not everything you'll put in there will be an icon, it can be an input field (text, checkbox, radio) or simple and plain text, but the common characteristic is that all of them, no matter what they'll be placed at, will behave as an inline-block element aligned to the left or right of the item text.

Again, this is just an usability thought. I will be messing around this tool, creating cool stuff.

![ionic-css](https://cloud.githubusercontent.com/assets/4284074/6808864/42815d50-d21c-11e4-9ac6-27c4f9b44269.jpg)

**Comment by Ionitron** [comment]
Greetings @manuelro!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3395). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3395)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adamdbradley** [comment]
Thanks for the feedback. As we're building out Ionic v2 we'll keep this in mind. One thing that we're able to take advantage of more is flexbox, so a lot of this will become easier. Thanks
