### ISSUE TITLE
bug: Problem with animation when deleting multiline list item

### ISSUE THREAD

**Issue by TejasQ** [driftyco/ionic#3398]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In an `ng-repeat`ed `<ion-list>` (without `white-space: nowrap`),  when items are removed, the animation messes up.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @TejasQ!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3398). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3398)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Can you please provide a codepen demo?

**Comment by TejasQ** [comment]
No, but I can provide a screengrab video of the problem: http://v8.tinypic.com/player.swf?file=ff7s6c&s=8

**Comment by Ionitron** [comment]
Greetings @TejasQ!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
