### ISSUE TITLE
Issue with Ionic under MobileFirst involving self.platforms

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic#3400]
I'm not sure I can make a codepen out of this, nor am I sure this is an Ionic issue versus MobileFirst, but I figured I'd log it and let yall make the call.

Sometimes (not sure of the exact repro case) when running an Ionic app in the Mobile Browser Simulator (think of it like MobileFirst's version of Ripple), I will see this in the console:

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('platform-ios - iphone') contains HTML space characters, which are not valid in tokens.

This is coming from ionic.bundle.js line 2136. Which is:

requestAnimationFrame(function() {
        // only add to the body class if we got platform info
        for (var i = 0; i < self.platforms.length; i++) {
          document.body.classList.add('platform-' + self.platforms[i]);
        }
      });

And when debugging, I can see that one value of self.platforms is "ios - iphone". I'm not sure how that got set, and maybe it is MobileFirst sending a 'bad' value to Ionic, but maybe it is something Ionic could handle?

**Comment by Ionitron** [comment]
Greetings @cfjedimaster!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3400). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3400)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by cfjedimaster** [comment]
This was another issue- unrelated.

**Comment by humbertosanchezlara** [comment]
@cfjedimaster how did you solve this? We just encountered this at our side.

We appreciate your comments.

**Comment by cfjedimaster** [comment]
Um, I don't exactly remember, I just know it isn't an issue if I use the MFP Ionic templates (I linked to it from my blog).
