### ISSUE TITLE
bug: bug: keyboardhide event hanlder hide should not close keyboard

### ISSUE THREAD

**Issue by dingguijin** [driftyco/ionic#3405]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Since native.keyboardhide is come from keyboard hide behaviour, "cordova.plugins.Keyboard.close()" should not called.

Keyboard plugins implement the keyboard.close function is set webview end editing, actually there are some scenarios when the keyboard hide but the editing is not end, for instance pick a candidate for Chinese/Japanese input method.

To compliant with the code, change the code to 
if (cordova.plugins.Keyboard.isVisible) {
        cordova.plugins.Keyboard.close();
}
Before close check the keyboard is visible or not.

Thanks,
Guijin

 </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @dingguijin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3405). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3405)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tlancina** [comment]
Should be fixed with https://github.com/driftyco/ionic/commit/70576d9ac20e764446ce808ae330e929535050c4.
