### ISSUE TITLE
bug: How can I install plugins on add platform?

### ISSUE THREAD

**Issue by umbrella-anton-kramazin** [driftyco/ionic#3407]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>After update ionic-cli (ver 1.3.18) was been removed hook 'after_platform_add', who added 'cordovaPlugin' from package.json. How can I install plugins on add platform now?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @umbrella-anton-kramazin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3407). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3407)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by walski** [comment]
:+1:

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#334

**Comment by perrygovier** [comment]
Moved to the CLI repo
