### ISSUE TITLE
bug: Android swipe animation

### ISSUE THREAD

**Issue by ildarkayumov** [driftyco/ionic#3410]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi, i'm using Ionic Version: 1.0.0-rc.0. It's good working on web, but when i run on real device app didn't show swipe animation, but swipe is working. Maybe i didn't understand the swipe animation process on Android and it must not show that animation on Android?

For example, http://codepen.io/dellingsworth/full/rawNBq/
No swipe/default state - ![default](http://dl1.joxi.net/drive/0006/3397/445765/150325/391b813a65.jpg)
With swipe animation - ![with swipe](http://dl1.joxi.net/drive/0006/3397/445765/150325/4a0a226d33.jpg)

You can repeat that using only browser Google Chrome:
1. open http://codepen.io/dellingsworth/full/rawNBq/
2. open development tools - Shift+Ctrl+I
3. click on mobile icon on top left corner - 
![icon](http://dl2.joxi.net/drive/0006/3397/445765/150325/8091be93d3.jpg)
4. select any Android device, for example: nexus 5
5. reload page
Then i can't see swipe animation. It didn't repeats with WP or iOs - they are working normal. The same bug on real Android device. Do any have the same problem?

Thank you.</span>

<span is-issue-template></span>
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ildarkayumov!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3410). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3410)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ildarkayumov** [comment]
My fail...works with refresher - http://ionicframework.com/docs/api/directive/ionRefresher/
