### ISSUE TITLE
bug: CSS3 transition flicker

### ISSUE THREAD

**Issue by sandersoeteman** [driftyco/ionic#3413]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I built my app using beta1. When I updated the Ionic stylesheets recently, I noticed a my css3 transitions were flickering when scrolling. This happened somewhere between beta1 and beta2 and is still present in the latest rc1 release. Any suggestions?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @sandersoeteman!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3413). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3413)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Can you provide some code samples we can use to debug the issue?

**Comment by Ionitron** [comment]
Greetings @sandersoeteman!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
