### ISSUE TITLE
bug: inappbrowser options not working (toolbar missing)

### ISSUE THREAD

**Issue by Trexology** [driftyco/ionic#3414]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>I was trying to make toolbar appear in the inappbrowser so that i can "close" that view. although toolbar=yes should be the default behaviour but that is not the case in ionic (toolbar shown in onsenUI)

As mentioned in this link http://forum.ionicframework.com/t/inappbrowser-options-not-working/16896
apparent the options field does not seem to work. 

tried with "window.open('http://pururu.moe/vy/chocolator', '_self ','toolbar=yes,location=no'); " but the result is still the same. therefore i am assuming is the ionic issue rather than ngCordova

using ngCordova 0.1.14-alpha

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Trexology!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3414). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3414)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Unfortunately, bugs with the inappbrowser are beyond our direct control. I would encourage you file a bug on [Apache's Jira repo](https://issues.apache.org/jira/browse/CB/component/12320641), and encourage those on the forum to chime in there.
