### ISSUE TITLE
iOS view transition animation broken

### ISSUE THREAD

**Issue by realityfilter** [driftyco/ionic#3415]
With introduction of 8ebde73d0b8afac1bf1c1787c90a72a28a88bc3a "iOS Swipe to Go Back" feature the animation of view transitions is broken in our app. During the transition there is a graphical glitch in the 'forward' animation. The new view does not slide in from the right and the old view is left partially visible for a short moment in the middle of the screen after the translated out to the left.

I could narrow it down to https://github.com/driftyco/ionic/commit/8ebde73d0b8afac1bf1c1787c90a72a28a88bc3a#diff-b1d18c92a01dbbcc0712f8ab85525838R362

**Comment by Ionitron** [comment]
Greetings @realityfilter!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3415). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3415)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by realityfilter** [comment]
Bot duplicated this issue #3416.
