### ISSUE TITLE
bug: iOS view transition animation broken

### ISSUE THREAD

**Issue by realityfilter** [driftyco/ionic#3416]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>With introduction of 8ebde73d0b8afac1bf1c1787c90a72a28a88bc3a "iOS Swipe to Go Back" feature the animation of view transitions is broken in our app. During the transition there is a graphical glitch in the 'forward' animation. The new view does not slide in from the right and the old view is left partially visible for a short moment in the middle of the screen after the translated out to the left.

I could narrow it down to https://github.com/driftyco/ionic/commit/8ebde73d0b8afac1bf1c1787c90a72a28a88bc3a#diff-b1d18c92a01dbbcc0712f8ab85525838R362</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @realityfilter!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by perrygovier** [comment]
To expand on what Ionitron said, can you provide a codepen example that recreates the issue so we're sure we're looking at the same thing.

**Comment by realityfilter** [comment]
I have tried to compile an example showing this bug. By now without any success.
But I can provide some more details:

- This glitch can be seen in Safari on iOS, too. So it is not WebView specific.
- Removing our app specific css in the debugger does not prevent this bug to happen.

Can the introduction of boxShadow be guarded with whether the feature swipeBackEnabled is enabled or not?

```
if (boxShadowOpacity > -1) {
        css.boxShadow = '0 0 10px rgba(0,0,0,' + (d.shouldAnimate ? boxShadowOpacity * 0.45 : 0.3) + ')';
}
````

**Comment by realityfilter** [comment]
I can workaround this problem with css alone:

```
[nav-view-transition="ios"] {

  [nav-view] {
    box-shadow: none !important;
  }

  [nav-view="entering"],
  [nav-view="leaving"] {
    -webkit-transition-property: opacity, -webkit-transform;
    transition-property: opacity, transform;
  }
}
```

**Comment by perrygovier** [comment]
I'm going to mark this as resolved then. Feel free to re-open if you can reproduce it in something we can inspect.

**Comment by rideosoftware** [comment]
Hi, we have a similar issue, tried this css solution but didn't work. 
Here's a video of the problem (password: bounce): https://vimeo.com/207952315
Any ideas? Thanks in advance.
