### ISSUE TITLE
noHistory Feature

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#3417]
There are quite a few issues related to overcoming the back view in some apps.  Most of the have been closed. I'll try to make a use case as clear as possible.

## Scenario 1:

- App opens
- User tries to view something
- They aren't authorized
- Transition to a Login state
- User logs in
- Transition to originally requested state
- User Happy
- User goes back
- User sees login again

## Scenario 2;

- Registered and logged in user opens app
- Goes to "Contacts" page
- Realized his BFF is missing from the list
- Taps "+"
- Transitions to and Add Contact page
- Enters the person's name and number
- Next Button takes to an Addresses page
- Enters the contacts address info.
- Saves new contact
- Goes "back"
- Is unfortunately seeing the add contact pages again

Scenario # 2 is especially contrived - but it happens.  Now, you may be thinking, just do the forms in a modal!  Good idea.  But in some cases, designers/UX/client doesn't want a modal.

## Feature Request:
In the router, be able to add a property like `avoidHistory` or `noHistory`.  This would indicate that the view in question should never be added to the history stack.  This way, after login in, the user will simply go back to the home page. 

Right now, people are trying all kinds of ways to prevent the previous view being in their history stack.  This feature would solve many of those problems. 

FYI : Tried adding this to Trello but doesn't seem possible.

**Comment by Ionitron** [comment]
Greetings @calendee!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3417). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3417)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by calendee** [comment]
Reopened as #3418
