### ISSUE TITLE
feat: Feature Request : Swipe Tabs

### ISSUE THREAD

**Issue by programming-kid** [driftyco/ionic#3419]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>You have got everything thats needed to built a great native app , there is this one feature missing which is seen in lot of android apps these days including Google Play Store , Swipeable tabs .

there is [thread](http://forum.ionicframework.com/t/i-need-a-new-component-challenge/5018) created on forum which has done a lot of work on this feature, it looks really nicely done.

i wish ionic team builds this feature in core ionic , this would be a great tool to have in ionic toolbox and will save a lot of time to lot of people who  are trying to implement it themselves

thanks 
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @programming-kid!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3419). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3419)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Purus** [comment]
+1

**Comment by dylanvdmerwe** [comment]
+100000

**Comment by clawish** [comment]
This would be such an awesome addition! :+1:  +1

**Comment by perrygovier** [comment]
We wont be adding new features like this to Ionic before the 1.0.0 release, but we're collecting input on what to add for 1.1. I've bumped it up to "under consideration" in our trello board. Vote for it and comment on it [here](https://trello.com/c/dnCyi4wI/85-scrollable-tabs)
