### ISSUE TITLE
bug: Ionic slideview data come in list format if i am navigating from other page

### ISSUE THREAD

**Issue by nikhil1746** [driftyco/ionic#3421]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am using Ionic Slidebox in that i am having some data that i am showing on swipe event that is working fine for first time but when i navigate to other page and come back to same page then it will shows all the data in list format. Thanks for reading, Please Help!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @nikhil1746!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3421). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3421)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 backend read error</title>
  </head>
  <body>
    <h1>Error 503 backend read error</h1>
    <p>backend read error</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-jfk1023-JFK 1427473956 1156931451</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

**Comment by Ionitron** [comment]
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 backend read error</title>
  </head>
  <body>
    <h1>Error 503 backend read error</h1>
    <p>backend read error</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-jfk1023-JFK 1427473956 1156931451</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

**Comment by perrygovier** [comment]
This is a better question for the [Forums](http://forum.ionicframework.com/) or #ionic channel on IRC
