### ISSUE TITLE
feat: Feature Request : adding dynamic styling to $ionicPopupService

### ISSUE THREAD

**Issue by sattarab** [driftyco/ionic#3422]
Type: feat

Platform: all

Can we add support for dynamic styling on the buttons in the ionicPopupService. I think this would be the last piece of the service which would make pretty much complete.

I can submit a PR if you wish.
Thanks

**Comment by Ionitron** [comment]
Greetings @sattarab!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3422). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3422)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
I believe this is the same thing as #3423
