### ISSUE TITLE
bug:  item-avatar and collection-repeat not spacing correctly

### ISSUE THREAD

**Issue by loomtronic** [driftyco/ionic#3425]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>There is no gap between the cards (where there is if I use ng-repeat) and also the ng-click does not register.  This is in rc1

```                
 <ion-scroll direction="y" ng-style="ionscrollheight">
                 <div class="list card" ng-class="{'selected':item.id == selectedRow}" collection-repeat="item in place_results | orderObjectBy:'index'">          
                   <div class="item item-avatar" ng-click="inspectPlace('{{item.id}}')">
                     <img src="{{item.image_url}}" width="60px" style="border-radius: 0%">
                     <h2>{{item.name}}</h2>
                     <p>{{item.categories[0][0]}}</p>
                   </div>
                    <div class="item item-body" style="padding-top:0px" ng-click="inspectPlace('{{item.id}}')">
                   
                   <p>{{item.location.display_address[0]}} {{item.location.display_address[1]}} {{item.location.display_address[2]}}<br>
                   <img src="{{item.rating_img_url_large}}" width="75px" style="vertical-align:middle"> ({{item.review_count}} reviews)</p>
                    </div>
                    
                   <div class="item tabs tabs-secondary tabs-icon-top" ng-show="showDetails" style="padding-top:2px">
                     <a class="tab-item" ng-click="loadMap()" >
                       <i class="icon ion-map"></i>
                       Directions
                     </a>
                   </div>
                 </div>
 <ion-scroll>
```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @loomtronic!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3425). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3425)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by loomtronic** [comment]
![image](https://cloud.githubusercontent.com/assets/1706404/6881508/1a8c0862-d51f-11e4-9f27-b3b1bbe81e4f.png)

**Comment by perrygovier** [comment]
By default, collection-repeat will use the height of the first item. In your case, this is not idea because they can vary depending on what information is available.

You may want to use [`item-height`](http://ionicframework.com/docs/api/directive/collectionRepeat/). Something like `item-height="getHeight(item)` and then in your `getHeight()` scope method, you would look at whether an image, text, address, reviews, whatever are available. 

The one trick is wrapping text, because that's difficult to measure without a delay that negates the benefit of collection-repeat. If your list has wrapping text, you want to either give it extra room by default and risk unnecessary white space or just use regular JS or native scrolling. 

We've run a ton of tests on different approaches, and checking the rendered height of items as we add them negates the benefit of collection-repeat.
