### ISSUE TITLE
bug: Capitalise icon resources generated for iOS

### ISSUE THREAD

**Issue by romainfrancez** [driftyco/ionic#3428]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>cli</span>

<span ionic-description>When generating the resources with the command `ionic resources` iOS icons names are generated with a lowercase `i`. However iOS apps expect the name to be with an uppercase `i` e.g `Icon.png`.

I can take care of the fix as it seems small.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @romainfrancez!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3428). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3428)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#339

**Comment by perrygovier** [comment]
Thanks @romainfrancez, I moved this over to the CLI repo for josh to look at
