### ISSUE TITLE
while typing in textInput using keyboard on iOS, does not show input content

### ISSUE THREAD

**Issue by yishu4geek** [driftyco/ionic#3429]
Hi Ionic Team, 

I am using the latest Ionic to build my app, I found that it does not show input content in the textinput field while I am typing on the keyboard. I only can see the actual text I input after I hit enter key. The keyboard input works fine before I updated to the latest version.

Thanks,
Yishu

**Comment by Ionitron** [comment]
Greetings @yishu4geek!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3429). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3429)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by lexon** [comment]
I have similar behavior, if I remove ionic, then its working fine.
If I tap slightly above a textfield, the keyboard would appear but there is no cursor within the text box and also querying for :focus will result in an empty list.

This has been tracked down by using simple <input /> elements.

**Comment by perrygovier** [comment]
Thanks,
Can you provide a codepen that reproduces the issue just so we're looking at the same thing?

**Comment by Ionitron** [comment]
Greetings @yishu4geek!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @yishu4geek!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by ireade** [comment]
Adding this worked for me:

```css
ion-input {
  -webkit-transform: translateZ(0) !important;
}
```

See https://forum.ionicframework.com/t/ion-input-shows-only-the-first-entered-character-on-ios/73107/5?u=iaderinokun
