### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#343]
http://forum.ionicframework.com/t/how-to-mask-an-input-field-for-mobile-number/274/2

**Comment by luisrudge** [comment]
Any news on the validation stuff?

**Comment by georgschlenkhoff** [comment]
see this excellent post: https://calendee.com/2014/12/26/validation-in-ionic-framework-apps-with-ngmessages/

**Comment by malixsys** [comment]
I love it! Great adaptation of my original validation!!

**Comment by guillermo-varela** [comment]
Hi, as an alternative I would like to suggest using Angular-auto-validate: http://jonsamwell.github.io/angular-auto-validate/

The error messages are dynamic, so for example for max/min length the message replaces the numeric values, without having to declare each message on every field, in fact the HTML template would be clean for any validation/error markups, just the form fields. Additionally the controller no longer requires to validate the form's state, because the library won't let the form to be submitted.

It even supports i18n, message customization and validation onBlur or onChange (default).

Although this library was developed to be use with Bootstrap or Fundation, I have a working example with Ionic here: http://codepen.io/gvarela/pen/KwJdEN

Hope it helps :smile:

**Comment by Fayozjon** [comment]
guillermo-varela

http://wenxuebu.com/robot-instaforex

24.03.2015, 01:36, "guillermo-varela" <notifications@github.com>:Hi, as an alternative I would like to suggest using Angular-auto-validate: 

The error messages are dynamic, so for example for max/min length the message replaces the numeric values, without having to declare each message on every field, in fact the HTML template would be clean for any validation/error markups, just the form fields. Additionally the controller no longer requires to validate the form's state, because the library won't let the form to be submitted.

It even supports i18n, message customization and validation onBlur or onChange (default).

Although this library was developed to be use with Bootstrap or Fundation, I have a working example with Ionic here: 

Hope it helps

**Comment by davidpatrick** [comment]
@adamdbradley looks like you guys have some spam in this issue.  ^
