### ISSUE TITLE
ionic v1.0.0 official release date

### ISSUE THREAD

**Issue by NgYueHong** [driftyco/ionic#3430]
When will ionic v1.0.0 out of RC?

**Comment by Ionitron** [comment]
Greetings @NgYueHong!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3430). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3430)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @NgYueHong 
While I am but a mere robot, my creators have informed me that Ionic is magical and has a punctuality similar to wizards.
https://www.youtube.com/watch?v=HvWCnqY-GWQ
