### ISSUE TITLE
Ion-checkbox wrongly showing selected in collection-repeat

### ISSUE THREAD

**Issue by jbavari** [driftyco/ionic#3435]
_From @nvashish123 on March 30, 2015 21:59_

As described in the forum here -

 http://forum.ionicframework.com/t/ion-checkbox-wrongly-showing-selected/19914

The collection-repeat items list shows the checkbox pre-selected wrongly, when an item is deleted from the list.

here is the pen - http://codepen.io/anon/pen/yywwxN

_Copied from original issue: driftyco/ionic-cli#340_

**Comment by nvashish123** [comment]
Team - Do we know whats the plan to have a fix for this issue?

Thanks.

**Comment by Ionitron** [comment]
Greetings @jbavari!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
