### ISSUE TITLE
feat: Back button on popup show not disabled in android re. issue #1222

### ISSUE THREAD

**Issue by moth002** [driftyco/ionic#3436]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi there,

Regards this particular issue with the Android back button closing the popup, wouldn't it be easier to have flag such as hardwareBackButtonClose to the popup similar to what is done with the modal?

could you please help?
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @moth002!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3436). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3436)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Closing this and moving it to our trello board as it is a feature request.

https://trello.com/c/tnCUmo12/98-add-option-to-toggle-if-the-hardware-back-button-will-close-a-popup
