### ISSUE TITLE
bug: Bower - Can't update to ionic rc2

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic#3438]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I can't update ionic to rc2 from rc1 - wrong angular version</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @piernik!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3438). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3438)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by piernik** [comment]
I've tried also `ionic lib update` no luck - rc1

**Comment by perrygovier** [comment]
Are you using the Ionic bundle? Use your own version of angular at your own risk.

**Comment by piernik** [comment]
Yes I started with Ionic bundle

**Comment by piernik** [comment]
In bower I have 
```
"devDependencies": {
    "ionic": "driftyco/ionic-bower#1.0.0-rc.1"
  },
```
switching to rc.2  (now rc.3) updates library
