### ISSUE TITLE
bug: Collection Repeat giving error on using function on item-height 

### ISSUE THREAD

**Issue by Dbms** [driftyco/ionic#3440]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>When the array which feeds the collection repeat is empty, it throws an error on console -

http://codepen.io/Dbms/pen/azPymP

The thing is that my array is empty in the beginning. Then it is filled by data with an AJAX request.
But, before the data comes, error comes on the console.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Dbms!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3440). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3440)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
