### ISSUE TITLE
bug: Input element in popup receives click on backdrop when keyboard moves out after blur

### ISSUE THREAD

**Issue by stefanmdt** [driftyco/ionic#3442]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I created a sample app that shows the bug: https://github.com/stefanmdt/ionic-popup-bug
You can run it on the iOS simulator or on an iPhone. To reproduce: 
* click on a list item to open the popup
* click on the "value" input field, so that it receives focus and keyboard is shown
* click on the backdrop between popup and keyboard

I guess, while keyboard is moving away, the popup moves downwards, so that the input element moves "under the finger" and receives the previous tap/click event. 

I think the issue is related to this one: https://github.com/driftyco/ionic/issues/3411

The bug does not appear on mobile browsers: http://plnkr.co/edit/vNbSccMlGSGgfczWrZdV

Here is the corresponding forum post: http://forum.ionicframework.com/t/keyboard-reopens-when-closing-popup/18857

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @stefanmdt!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3442). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3442)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Looks like a ghost click is firing 300ms later at the same coordinates. Here's a video
![image](https://cloud.githubusercontent.com/assets/571056/6945199/9ea9cd3c-d85d-11e4-9a0b-cfd973d2ec89.png)

**Comment by jtomaszewski** [comment]
We have the similar problem when we click on a link with `menu-close` in a sidemenu - the sidemenu closes, and a keyboard opens up, because in the `ion-sidemenu-content` we have a text field at the similar coordinates. Here's a video: https://www.dropbox.com/s/1ts19gcst3ufwtq/My_fest_keyboard.mov?dl=0

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
