### ISSUE TITLE
bug: Collection Repeat with scroll bottom not working as desired

### ISSUE THREAD

**Issue by Dbms** [driftyco/ionic#3443]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>When we use scrollBottom on a collection-repeat it does not go to the last element as desired (unless all items are of the same height).

http://codepen.io/Dbms/pen/yywmdP

I have not tested with scrollTo or scrollBy but the same issue may be there, probably owing to the fact that all calculations were done based on the height of the first item. Not sure about this though.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Dbms!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3443). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3443)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
When you dynamically specify height, collection repeat has to guess at what the total height will be when scrolling to the bottom. Calling scrollBottom a second time resolves this nicely. 
http://codepen.io/perrygovier/pen/EaJVmP?editors=101
