### ISSUE TITLE
bug: ionic commands gives current working directory is not a Cordova-based project

### ISSUE THREAD

**Issue by aelx311** [driftyco/ionic#3446]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi,

I updated ionicCLI to 1.3.18 and I am having issues building and running my app.

I tried ionic start myapp blank, a new directory was created but I got this:
![capture](https://cloud.githubusercontent.com/assets/3267257/6930774/dd9c36f2-d7cb-11e4-8463-d7eec6fa103a.PNG)
I am pretty sure that my Cordova is the latest version.

I did cordova create . as suggested in http://ionicframework.com/docs/ionic-cli-faq/#plugins but no luck.
![capture2](https://cloud.githubusercontent.com/assets/3267257/6930793/14dfc4c6-d7cc-11e4-9957-faa6640df79d.PNG)

As you can see, config.xml does exists in the directory.
![capture3](https://cloud.githubusercontent.com/assets/3267257/6930817/64eb7f1e-d7cc-11e4-8521-eafbab392c9c.PNG)

All are working fine until I updated ionicCLI to 1.3.18.

Any advice is very much appreciated.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @aelx311!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3446). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3446)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#346

**Comment by perrygovier** [comment]
Thanks @aelx311, I moved this issue over to the CLI so josh can help you out
