### ISSUE TITLE
perf: Ion-spinner constantly repaints causing performance issues. 

### ISSUE THREAD

**Issue by jabyrd3** [driftyco/ionic#3454]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Our team has implemented a few of the ion-spinner directives in our application. We're noticing that if the spinner is toggled via ng-show vs. ng-if it is constantly animating the SVG and causing costly repaints / css recalcs. This might not be noticeable on modern devices but we're targeting a slightly lower-spec'd device and it is making our app completely unusable. We are going to use the ng-if workaround for now but I think it might be wise to investigate the issue further.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jabyrd3!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3454). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3454)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Unfortunately, this is an issue with webkit itself. It can be helpful in some cases because showing the spinner then can be cheaper. What we do under the hood in some cases is to `ng-if` the element just a little bit before we need to show it. say for example in the loading directive, we add it to the DOM right away, but `ng-hide` it until the loading screen has transitioned in.

Unfortunately, the only fix we cold implement is to have ng-show/hide actually do an ng-if under the hood, but that prevents the cases where you might want that behavior. Sorry, our hands are tied here.

**Comment by rsweny** [comment]
I believe it is even worse than described originally. The first time a loading spinner is shown anywhere in the app it will be animated forever after using large amounts of CPU. This bug affects both Android and iOS. 

See the thread here: http://forum.ionicframework.com/t/rc0-1-high-idle-cpu-usage-on-ios-7-iphone-4/19705/4

I don't know of a way to remove $ionicLoading from DOM but that could help here.

**Comment by jabyrd3** [comment]
rsweny: This is an unsolvable problem with the SVG spinners. If you're seeing slow framerates on lower spec devices you might have to write your own CSS3 spinner. That's what I did to get around the problem. 

Look for spinner that uses css3 transforms/transitions and only animates rotation. I was able to achieve 60fps on a lowend tablet from 2013 by making sure the animation was only being done by the compositor (which happens on the GPU thread, giving us the added benefit of not blocking our main UI thread). It is also only using system resources when it's visible.

**Comment by rsweny** [comment]
Thanks for the advice, I will certainly do something along those lines before release. I guess I would go as far as to say the Ionic team should pull the svg's out of the spinner library and use gif's or css instead. It isn't really acceptable to have people releasing apps that unknowingly use so much CPU and drain the battery.

**Comment by jabyrd3** [comment]
I agree with you but I can't really see that happening at this point. A possible option would be to have a switch attribute on the ion-loading to use a CSS spinner instead of the SVG to minimize CPU churn on low-spec devices, similar to the overflow-scrolling attribute on ion-scroll.

**Comment by rastographics** [comment]
@jabyrd3 Can you link to a resource that explains some more about how you did your animation?

> I was able to achieve 60fps on a lowend tablet from 2013 by making sure the animation was only being done by the compositor

**Comment by rsweny** [comment]
My concern was primarily with killing the battery so I didn't benchmark this spinner, but at least it stops sucking CPU after 45 seconds.

.spinner1 {
  min-width: 28px;
  min-height: 28px;
  content: "";
  display: inline-block;
  border: solid 10px;
  border-radius: 50%;
  border-color: #eeeeee transparent #eeeeee transparent;
  -webkit-animation: spin 1.5s ease infinite;
  animation: spin 1.5s ease infinite;
  /* important to stop the animation - on android it still takes up 30% CPU even when hidden */
  -webkit-animation-iteration-count: 30;
  animation-iteration-count: 30; }

Also, it looks like Ionic is trying to fix it properly by removing from DOM:
https://github.com/driftyco/ionic/issues/3583

**Comment by perrygovier** [comment]
Note, this was fixed in f62281760fc4dfd83b96fa50e6d67b63490f3aba

**Comment by mlynch** [comment]
Should be fixed for certain edge cases by recent commit: 9f341a8ccb3829ccb5a02797bd44ec301f6bb14f
