### ISSUE TITLE
bug: ion-nav-bar out-of-sync using nested tabs

### ISSUE THREAD

**Issue by jeremyalan** [driftyco/ionic#3455]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>See an example in the following plunker (using RC2):
http://plnkr.co/edit/mR41D2plb796LXcXFl5E?p=preview

The tab views are broken down as:
```
- Home
  - Home Tab 1
  - Home Tab 2
- About
  - About Tab 1
  - About Tab 2
```

Perform the following steps:
* Select "About" tab (bottom-right)
* Select "Learn" tab (top-right)
* Select "Home" tab (bottom-left)

Notice that the header title is now showing "About Tab 1", but the content displayed is "This is Home Tab 1"

Now, continue with the following steps:
* Select "Analytics" tab (top-right)
* Select "Dashboard" tab (top-left)

Notice that the header title correctly matches the content.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jeremyalan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3455). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3455)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Tabs within tabs! 
Tabs expects the parent state to be abstract. This means you'll need to update your links dynamically through a service or something, but I think that's an acceptable complication as nested tabs isn't something we officially support (I'm actually pretty amazed it works as well as it does). 

This should set you on the right path, but I assume you want to add some conditional logic regarding what page the bottom tab links to
http://plnkr.co/edit/hhi31o9T2J84172Ug4wq?p=preview

**Comment by jeremyalan** [comment]
Thanks for the info, @perrygovier. Is that an official stance for Ionic 1.0 on whether nested tabs are supported? It makes sense, I just haven't heard anyone from the team make that sort of blanket statement on other similar issues. 

Luckily, we have re-designed the navigation in our app, so this is no longer a show stopper for us. :-)

Thanks again!
