### ISSUE TITLE
bug: Stretched splashscreen on Moto X when using resources generator

### ISSUE THREAD

**Issue by kaumac** [driftyco/ionic#3456]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi there! I'm using the cli tool to generate both splashscreens and icons for my app. I followed every instruction for the dimensions of the images and everything is working perfectly, except for the splashscreen specifically on Moto X. On moto x the splashscreen is stretched to the sides (the icon works just fine tough). On iOS emulator, Android Emulator em Galaxy S4, both splashscreen and icons works just fine.

The image as you can see in the screenshot is 2208x2208 and the main content centered inside it has a 1200x1200 area. I really don't know what it can be. Can anyone confirm this?

![captura de tela 2015-04-02 as 01 21 48](https://cloud.githubusercontent.com/assets/1170740/6957736/b998ca3e-d8d6-11e4-8059-9ec9d2b1c01d.png)

</span>

<span is-issue-template></span>

Edit: I tested it on android 4.4 and 5.0.2

**Comment by Ionitron** [comment]
Greetings @kaumac!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3456). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3456)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-cli#350
