### ISSUE TITLE
bug: beforeLeave doesn't get fired for nested views

### ISSUE THREAD

**Issue by michael8090** [driftyco/ionic#3457]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>say we have a nested state 'a.b.c' and another state 'a.d', when we transition from 'a.b.c' to 'a.d', the scope connected with 'a.b.c' doesn't receive '$ionicView.beforeLeave' or '$ionicView.leave', instead, it's the parent node (ie 'a.b') who gets notified.

reproduce link: http://codepen.io/anon/pen/jERZqL

In the code open above, click 'Scientific Facts' and you can see there are two dialogs popped up(which seem another issue), and when click on the back nav button, there is no alert message.

  </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @michael8090!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3457). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3457)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Thanks for the great example @michael8090!

**Comment by adamdbradley** [comment]
Note: The alert pops up twice because you didn't close the `<ion-nav-vew>` in the `tabs.facts` state.

**Comment by adamdbradley** [comment]
So in the `tabs.facts` you're creating a new history, but both states are going to the same url. I would recommend a different architecture for your navigation.

**Comment by michael8090** [comment]
@adamdbradley thanks for the rely. Sorry for the un-closed `<ion-nav-view>` tag.

But I still could not get a working sample for the 'beforeLeave' event in the the nested views. Adding a url for `tab.facts` doesn't help(the codepan is updated). Could you help to take a look at the codepan?
