### ISSUE TITLE
Apostrophe problem in the <name> balise of config.xml

### ISSUE THREAD

**Issue by lakano** [driftyco/ionic#3459]
Hello,

When we put an apostrophe in the "name" XML balise, the compilation fails with Android ( but works with iOS ).

And if I backslash the apostrophe, this compile correctly under Android, but the compilation fails under iOS.

````
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Found modified input file
     [aapt] Generating resource IDs...
     [aapt] /www/app/platforms/android/res/values/strings.xml:3: error: Apostrophe not preceded by \ (in Test ' Apostrophe)
     [aapt] 

BUILD FAILED
/opt/android/tools/ant/build.xml:653: The following error occurred while executing this line:
/opt/android/tools/ant/build.xml:698: null returned: 1

Total time: 1 second

/www/app/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: debug,-f,/www/app/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
ERROR running one or more of the platforms: Error: /www/app/platforms/android/cordova/run: Command failed with exit code 8
You may not have the required environment or OS to run this project
````

Regards,

**Comment by Ionitron** [comment]
Greetings @lakano!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3459). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3459)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by lakano** [comment]
![capture d ecran de 2015-04-02 14 37 31](https://cloud.githubusercontent.com/assets/731955/6964049/e0dfa094-d945-11e4-9142-dcc6d22a2261.png)

So... how to report bug if the "custom issue form" bug too ?

**Comment by mhartington** [comment]
So this is an issue on the cordova side of things, not ionic.
Each platform has little quirks about what it will take for a valid name.

Close as it is not an issue with ionic.

**Comment by lakano** [comment]
So, could you please tell me where I can report the bug ?

On the cordova-android, there is no way to create an issue.
https://github.com/apache/cordova-android

Regards

**Comment by mhartington** [comment]
https://issues.apache.org/jira/browse/CB/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel

**Comment by lakano** [comment]
Thanks !
