### ISSUE TITLE
bug: Ionic-toggle /ion-checkbox state issue

### ISSUE THREAD

**Issue by thilahavanan** [driftyco/ionic#3460]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>ionic-toggle and ionic-checkbox both the element are not working properly.my implementation here 

    <li class="item item-toggle">
         Tip of the Day
         <label class="toggle toggle-balanced">
           <input type="checkbox" ng-change="tipOftheDay()" ng-model="usersettings.checked" ng-checked="usersettings.checked" >
           <div class="track">
             <div class="handle"></div>
           </div>
         </label>

on ng-change call back function am getting the true/false value and then storing those value in localstorage.So when I am going to next state and coming to this state the values true/false getting properly but the checkbox state is always showing true,if the settings was set to false also.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @thilahavanan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3460). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3460)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Would you be able  to throw this into a quick codepen?

**Comment by Ionitron** [comment]
Greetings @thilahavanan!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
