### ISSUE TITLE
bug: Side Menu navigation with $state

### ISSUE THREAD

**Issue by pedroabreu** [driftyco/ionic#3461]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

Ionic version: 1.0.0-rc2

Codepen: http://codepen.io/canihazcookienow/pen/rabJKo

I've spotted an issue with the side menu. If I try to navigate to the second menu, I can't access the side menu again after the state is loaded.
On codepen you can't swipe for the side menu but on the iOS emulator it swipes to the previous view and then to the side menu.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @pedroabreu!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3461). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3461)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by brandyshea** [comment]
Note that this happens when calling a function that uses $state.go, but not when using anchor tags. 

http://codepen.io/brandyshea/pen/YPMLQJ?editors=101

**Comment by mhartington** [comment]
Soo two things are going on here.

1) enable-menu-with-back-views 

http://codepen.io/mhartington/pen/azxMrp

>**enable-menu-with-back-views**
>Determines whether the side menu is enabled when the back button is showing. When set to false, any menuToggle will be hidden, and the user cannot swipe to open the menu. When going back to the root page of the side menu (the page without a back button visible), then any menuToggle buttons will show again, and menus will be enabled again.

http://ionicframework.com/docs/api/directive/ionSideMenus/

By default, this is set to false so we can do things like swipe-to-go-back. 

2) Using menu-close and hrefs, the next view resets the history, allowing the menu to be swiped open

So for your original example @pedroabreu, you could use `$ionicHistory.nextViewOptions` to recreate the same thing.

```
  $scope.ItemClick = function(tab){
    $state.go('tab.'+tab.displayName);
    $ionicHistory.nextViewOptions({
      disableAnimate: true,
      disableBack: true
    });
  }
```

http://codepen.io/mhartington/pen/YPMgoe

**Comment by brandyshea** [comment]
I don't know why I didn't think of this. Thanks Mike!
