### ISSUE TITLE
Popover memory leak ?

### ISSUE THREAD

**Issue by szuzul** [driftyco/ionic#3462]
Hi,

I try to repeatedly click on a simple popover  (over 20 times) and it seams that number of event listeners in time line are increasing. I assume that this is the leak. The simple app that I made is on rc2 but this behaviour happens on 14. also. 
I also assume this behavior increase the leak if I put more logic around popup what happens in my other app, this is only isolated case with popover only. 

This is the link to my app
JS heap size after garbage collecting slowly increasing in steps. 
1st drop 5115528 , 2nd drop 5174500, 3rd drop 5251920, 4th drop 5311048

Source  
https://github.com/szuzul/popoverApp

![image](https://cloud.githubusercontent.com/assets/1090963/6968124/78232a98-d964-11e4-8058-a9d74f05c037.png)

Thanks

**Comment by Ionitron** [comment]
Greetings @szuzul!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3462). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3462)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
