### ISSUE TITLE
bug: text of buttons in a ion-nav-bar tag are below the screen for iphone6

### ISSUE THREAD

**Issue by mzarella** [driftyco/ionic#3465]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Put this in a view:
```html
<div class="ion-view">
  <ion-nav-bar class="bar bar-footer">
    <ion-nav-buttons side="left">
      <button ng-click="previous()" class="button button-clear">Previous</button>
    </ion-nav-buttons>
    <ion-nav-buttons side="right">
      <button ng-click="next()" ng-show="slideIndex != 2" class="button button-clear">Next</button>
    </ion-nav-buttons>
  </ion-nav-bar>
</div>
```

Run `ionic emulate ios`

Notice the text of buttons are below the screen. I am emulating an iPhone 6, version 8.2(12D508). Confirmed this is the same on my iPhone6.</span>

<span is-issue-template></span>
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mzarella!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3465). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3465)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Would you be able to throw this into a codepen?

**Comment by Ionitron** [comment]
Greetings @mzarella!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
