### ISSUE TITLE
feat: Ion tabs without history

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic#3466]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Now iontabs controll history of Your app which is great for tabbased app.
But I want to use iontabs on specific views (I have normal side menu for navigation). Problem is that iontabs messes with history. Can You add option to turn off history handling by iontabs?

PS. I know You can use tab classes but iontabs have few great options like os positioning or transcluded views...</span>

<span is-issue-template></span>

**Comment by sid132** [comment]
how do i go to dash from a click on a popup window from another tab?

**Comment by perrygovier** [comment]
Hey @piernik, we're not going to be adding new features like this to Ionic while we work towards a stable 1.0 release. I'm not sure there's enough demand for something in between `ion-tabs` as is, and just using CSS classes directly, but I'm happy to be proven wrong.  [I've added this to our feature request Trello board](https://trello.com/c/bF6DeJls/91-ion-tabs-without-history).  If it gets enough upvotes we'll consider it for post 1.0.

**Comment by fhofer** [comment]
for me this is some kind of mandatory since I don't even know when you really wanted to have navigation history of tabbing rather than not having it. history inside the tab yes but I'd guess for many people the history of the tabbing is more annoying than if you would not have any history of the tab browsing.
or in other words: i think it's more annoying for many people that tab browsing creates history than they would miss it if you couldn't have this. Since I guess most of you or really many are apple people, you won't even have noticed this issue because of the lack of a back button on apple devices and because ionic hides the back button in the nav bar and unfortunately gives no option to show it again.
So for apple it just doesn't matter because you cannot use it or in other words don't have to worry about it but in android the wohle navigation stack is very annoying some times (had trouble that you can't go back to login again after login or to the app overview after login through the hw back button)
