### ISSUE TITLE
bug: ion-nav-buttons not working in new Google Chrome Canary

### ISSUE THREAD

**Issue by matiastucci** [driftyco/ionic#3467]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I was working on an app, and just after apply the nightly updates (version 43.0.2355.0 canary), all my `ion-nav-buttons` stop working (including the back button). Just to be sure I created a new project and it was the same. In regular Chrome and Firefox, the buttons are working fine. Of course I can test the app in another browser and it's OK, but just FYI.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @matiastucci!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3467). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3467)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by neilgoldman305** [comment]
I experienced this issue today as well, and made some codepens to test it.

The issue seems ng-click breaks on any button with class="button". Any other element with class="button" still works, and any button without class="button" also works. It does not enter the attached method at all.

Here is a codepen with various styles of elements/classes with an ng-click on them. It works in the stable branch of chrome, but not Canary.
http://codepen.io/squeaky-clean/pen/rabRbx?editors=101

Here is the same test using only angularjs 1.3.13, everything works across both browsers.
http://codepen.io/squeaky-clean/pen/yyrwdy

**Comment by neilgoldman305** [comment]
It seems to be the ionic.css file.

Here is my earlier ionic ng-click test, without ionic.css. Now it works.
http://codepen.io/squeaky-clean/pen/RNOObJ

Here is the earlier angular only test, with ionic.css. Now it doesn't work.
http://codepen.io/squeaky-clean/pen/dPLLbJ

**Comment by matiastucci** [comment]
@neilgoldman305 Yep, you are right. Angular 1.3.13 seems to fix it.

**Comment by neilgoldman305** [comment]
It seems to be the button:after psuedo-element blocking the click. Overriding the content property is a working temporary fix. I don't know what the purpose of those styles are, but I don't see any noticeable difference in my app in either Chrome or Canary.

    .button:after {
        content: none !important;
    }

Commenting out the :after rule in the _buttons.scss file also works

    &:after {
      // used to create a larger button "hit" area
      position: absolute;
      top: -6px;
      right: -6px;
      bottom: -6px;
      left: -6px;
      content: ' ';
    }

But there must be a cleaner fix than that. It seems like it's just a bug in Canary and nothing to do with Ionic?

**Comment by martinjbaker** [comment]
Seeing same thing here with rc2 and Canary. Am using Angular 1.3.13. The override of content worked for me.

**Comment by mlegenhausen** [comment]
Same Problem angular 1.3.15 and Canary.

**Comment by JanPeCol** [comment]
Same on ionic.rc2 angular 1.3.15 and Chrome 43.0.2357.2 dev (64-bit)
neilgoldman305 workaround, fix the issue. Thanks!

**Comment by neilgoldman305** [comment]
This is definitely a Chrome/Canary bug. I just noticed today that the Spotify Web Player has this same issue. Here is a minimal codepen to prove it:
http://codepen.io/squeaky-clean/pen/gbJdqJ

The ::after are shaded in red/blue/green. In Canary (*44.0.2358.0 - 64bit*), the ::after pseudo-element will not trigger click events, and will block clicks from reaching elements behind them as well.

**Comment by martinjbaker** [comment]
Fixed in Canary 44.0.2360.0 which is available now.

**Comment by DavidFrahm** [comment]
Confirming fixed in latest Canary

**Comment by perrygovier** [comment]
Closing since it seems to have been fixed by the Chrome teams. Thanks for the update
