### ISSUE TITLE
bug: $ionicConfig.views.swipeBackEnabled can't be changed

### ISSUE THREAD

**Issue by yankustefan** [driftyco/ionic#3470]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Is it possible to disable "swipe to go back" on specific views?

I would like to disable it on forms, where I have implemented a confirmation before closing/moving away from the view.

See also Ionic forum thread: [#18808](http://forum.ionicframework.com/t/disable-ios-swipe-to-go-back-for-specific-views/18808)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @yankustefan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3470). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3470)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by felquis** [comment]
Do you tried using `$ionicHistory.nextViewOptions`? http://ionicframework.com/docs/api/service/$ionicHistory/
```js
$ionicHistory.nextViewOptions({
  disableBack: true
});
```

I'm sure that with `historyRoot: true`  swipe to go back doesn't works, but with `disableBack: true` I'm not sure.

**Comment by samu** [comment]
:+1:
I tried what @felquis suggested, but didn't work.

**Comment by perrygovier** [comment]
You should be able to disable it in the state's controller. Something like:
```
.controller('MyCtrl', function($scope, $ionicConfig) {
  $scope.$on('$ionicView.enter', function(){
  	$ionicConfig.views.swipeBackEnabled(false);
  })
  $scope.$on('$ionicView.leave', function(){
  	$ionicConfig.views.swipeBackEnabled(true);
  })
});
```

**Comment by yankustefan** [comment]
@perrygovier Thank your for your feedback.

I added to the controller of the according state/view.
Both functions are firing, either on enter and leave as expected.

However I still can swipe to leave the state/view.

I tested on 1.0.0-rc.0 and 1.0.0-rc.3

**Comment by mhartington** [comment]
@perrygovier This maybe along the same lines as https://github.com/driftyco/ionic/issues/3281, where change the config value in the controller did nothing.

If thats the case, this would be a bug and not a feature. Passing this to @adamdbradley

**Comment by yankustefan** [comment]
Hi @adamdbradley 

Thank you for your work on this issue.
I upgraded to 1.0.0-rc.4 and the code below still does not prevent me to "swipe to go back". 
(tested in Ionic View)

´´
.controller('MyCtrl', function($scope, $ionicConfig) {
  $scope.$on('$ionicView.enter', function(){
    $ionicConfig.views.swipeBackEnabled(false);
  })
  $scope.$on('$ionicView.leave', function(){
    $ionicConfig.views.swipeBackEnabled(true);
  })
});

´´

**Comment by seb0zz** [comment]
@yankustefan neither works in rc.5 :-(

**Comment by seb0zz** [comment]
Ah @yankustefan simply use `can-swipe-back="false"` on your `ion-view` element

**Comment by marcelfalliere** [comment]
+1 @yankustefan

I have the following code (that I believe should be the default on iOS, but whatever) :

    $scope.$watch(function () { return $ionicSideMenuDelegate.isOpenRight(); }, function (isOpen) {
      if (isOpen){
        $ionicConfig.views.swipeBackEnabled(false);
      } else {
        $ionicConfig.views.swipeBackEnabled(true);
      }
    });


Not working :'(

The problem I have is the following :
  - platform : iOS 
  - ionic app with a `ion-side-menu side="right"` and a `ion-nav-view` 
  - users navigate to a sub route (let's say from route "foo" to route "foo.bar" in the `ion-nav-view`)
  - users opens the right side-menu
  - users swipes from left ro right
  - **Bug** : the right menu closes **AND** the view navigates back

Is that clear enough ? I can make a video since it's pretty specific, if necessary.

Regards

Also pinging @adamdbradley

**Comment by fengsong97** [comment]
following  is not work

.controller('MyCtrl', function($scope, $ionicConfig) {
  $scope.$on('$ionicView.enter', function(){
    $ionicConfig.views.swipeBackEnabled(false);
  })
  $scope.$on('$ionicView.leave', function(){
    $ionicConfig.views.swipeBackEnabled(true);
  })
});

**Comment by camilobaezcamba** [comment]
@seb0zz Have you tried programmatically?
Like this: can-swipe-back="canSwipe()"
`$scope.canSwipe = function(){
   return true;
}`
