### ISSUE TITLE
bug: ng-view and ion-nav-view only work on IBM MobileFirst when using beta.1 version of ionic.css

### ISSUE THREAD

**Issue by bbkoay** [driftyco/ionic#3475]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Both ng-view and ion-nav-view only work on MobileFirst when using the ionic.css file v1.0.0-beta.1, they do not work when using other versions of ionic.css.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @bbkoay!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3475). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3475)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Hey @bbkoay, we don't have IBM MobileFirst set up here. Do you get any console errors? Note, the JS and CSS versions must match. Are you able to narrow it down to a specific commit that broke it?

**Comment by bbkoay** [comment]
Hi @perrygovier, thank you for your reply. There are no console errors. The ionic JS and CSS versions that I'm using on IBM MobileFirst right now is v1.0.0-rc.3 "radium-raccoon". I'm not sure what exactly is the issue, but I found out that if I exclude the declaration of <!DOCTYPE html> from index.html, the views worked perfectly. The other alternative is to remain the declaration of <!DOCTYPE html>, but using the beta.1 version of ionic.css instead of other latest versions.

**Comment by perrygovier** [comment]
What do you mean by not work? like they wont load templates at all? if you inspect the dom, do the pages exist but just aren't displayed?

**Comment by bbkoay** [comment]
@perrygovier yes, you are right. The pages exist but just aren't displayed.

**Comment by Ionitron** [comment]
Greetings @bbkoay!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
