### ISSUE TITLE
bug: bug: Ionic Range button not showing in WP 8.1

### ISSUE THREAD

**Issue by VeldMuijz** [driftyco/ionic#3479]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

I'm developing an application for iOS, android and Windows phone 8.1.

I use a range input to manipulate a $scope value. The button of the range input doesn't show in the Windows Phone 8.1 application but does in the other two.

[Codepen.io example](http://codepen.io/VeldMuijz/pen/KwLROg)</span>

Example of wp8.1 view:
![image](https://cloud.githubusercontent.com/assets/1394439/7025893/cda30548-dd46-11e4-862a-814e9449fe0b.png)

Example of android view: 
![image](https://cloud.githubusercontent.com/assets/1394439/7025915/ebf9d3a0-dd46-11e4-910b-268b77f799cc.png)

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @VeldMuijz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3479). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3479)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Thanks @VeldMuijz
