### ISSUE TITLE
Dynamically create list dividers

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#348]
http://forum.ionicframework.com/t/generating-list-with-dividers-dynamically/341/2

**Comment by thomasjonas** [comment]
I have the feeling this is still not completely solved. Maybe it's just an edge case when using ion-list, ion-item and collection-repeat? I made a codepen to illustrate my problem: http://codepen.io/anon/pen/bdBWMG

The problem is that dividers are not style properly and their content is being wrapped by 'a' tags.

**Comment by gslender** [comment]
+1 would love to see this resolve and/or at least opened again as it isn't 100% fixed

**Comment by gslender** [comment]
This is a solution I think might solve the problem.... http://codepen.io/anon/pen/wMdMqv
