### ISSUE TITLE
different build versions for x86 and arm when using crosswalk

### ISSUE THREAD

**Issue by Maddis1337** [driftyco/ionic#3481]
Hey there,
some of you may know that the two .apk files generated by ``ìonic build -release android``` do need separate version numbers so that both can be published to play store. I thought about solving this via a after_prepare hook, but that only fires once for both builds. 
Right now I have to manually build both, upload one, change version, build both again and upload the second one.

Another workaround would be to have an argument for the build command which allows that each apk can be build separately.

**Comment by Ionitron** [comment]
Greetings @Maddis1337!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3481). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3481)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
The latest CLI (1.13.19) does this be default.

http://blog.ionic.io/crosswalk-comes-to-ionic/

**Comment by Maddis1337** [comment]
I know that it creates two at once,  but I want to generate them one after another with two commands

**Comment by mhartington** [comment]
I'm not sure I see the point of this? 
You may want to open an issue over on the CLI repo, that would be the proper place.
https://github.com/driftyco/ionic-cli
