### ISSUE TITLE
feat: $ionicLoading should have isShowing()

### ISSUE THREAD

**Issue by sikron** [driftyco/ionic#3490]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,
i use the $ionicLoading to show a rotating spinner as long as requests are ongoing. Now if during an ongoing request, where the loading animation is shown, another request is started, i just call $ionicLoading.show() again. This causes the loading animation (the spinning spinner) to start all over, which kind of looks like a stuttering spinner sometimes.

If the $ionicLoading would have a `isShowing()`, i could check, whether there is already a loading animation before i call show() again. This would result in a smooth spinning spinner.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @sikron!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3490). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3490)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Will mark this as a feature for post 1.0

**Comment by mhartington** [comment]
Will close this for now and move to our trello board.

https://trello.com/c/0AcK2qIu/99-ionicloading-should-have-isshowing

**Comment by fentas** [comment]
Sorry resurfacing this topic.
But this is the only usefull topic i found on google.

Since this feature is still under considuration(?) I poked around and found following solution for this.
```js
$ionicLoading._getLoader().$$state.value.isShown
```

**Comment by jlstr** [comment]
@fentas Superb! Works great, thank you.

**Comment by easygoing1** [comment]
I would recommend this to check for visibility:

       `$ionicLoading._getLoader().then(function(state){`
            console.log(state.isShown);
        `});`
