### ISSUE TITLE
bug: does not render properly

### ISSUE THREAD

**Issue by hunikim** [driftyco/ionic#3492]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I tried to chat application with firebase.

The received application does not render messages properly as below images.
https://s3-ap-northeast-1.amazonaws.com/helpme2/Screenshot_2015-04-09-14-21-52.png (receive view)

should be:
https://s3-ap-northeast-1.amazonaws.com/helpme2/Screenshot_2015-04-09-14-24-29.png (sender view)

my code is :

 var ref = new Firebase("https://siu-push.firebaseio.com/messages");
  $scope.messages = $firebaseArray(ref);

 $scope.$watch('messages', function(newValue, oldValue) {
    $ionicScrollDelegate.scrollBottom(true);
  }, true);</span>

I tried as well: 
 $scope.$watch('messages', function(newValue, oldValue) {
    $ionicScrollDelegate.scrollBottom(true);
    $scope.$apply();
  }, true);

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Hey @hunikim, can you put together an example in firebase we can test against?

**Comment by hunikim** [comment]
If I put ng-repeat inside ion-list directive, It works fine.

Can you explain about ion-list directive please?

**Comment by Ionitron** [comment]
Greetings @hunikim!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
