### ISSUE TITLE
feat: in ionic.js, ionicSlideBoxDelegate.next does not take speed parameter

### ISSUE THREAD

**Issue by mikesol** [driftyco/ionic#3493]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It would be nice if next and back functioned like the slide function so that the speed can be controlled.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mikesol!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3493). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3493)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ajoslin** [comment]
Added, thanks for the suggest.

**Comment by diegodotta** [comment]
Has anyone using this parameter? I'm trying here, but apparently nothing happens. :(
