### ISSUE TITLE
bug: SELECT element in modal clicks

### ISSUE THREAD

**Issue by liujinxing** [driftyco/ionic#3494]
find bug like #2308 on iPhone 6(iOS 8.2) using ionic-1.0.0-rc.2.

**Comment by Ionitron** [comment]
Greetings @liujinxing!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3494). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3494)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
