### ISSUE TITLE
perf: ionic Angulajs routing is not working in phonegap.

### ISSUE THREAD

**Issue by jeniferXavier** [driftyco/ionic#3496]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>i created sample app using ionic framework. In that i am using angular routing for url mapping.That is working in browser.After bulid my app in phonegap it is showing blank page. My local application url is like this 
"http://localhost:55456/www/index.html#/app/login". i dont know why it is not working. Please help me to fix this issue.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jeniferXavier!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
