### ISSUE TITLE
bug: ion-item a-tag rendering issue

### ISSUE THREAD

**Issue by frkris** [driftyco/ionic#3497]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I believe there is in an issue with using ng-href on ion-item together with angular html5 mode.

target="_self" in angular will cause a postback, rather than the intended SPA behavior.

Considering the below:

 $scope.$target = function() {
          return $attrs.target || '_self';
        };

Target will always be set to self. There is no way to cause this item to be omitted.

Someone correct me if I am wrong, but it seems the correct behavior should be not to set it at all if it is not set on ion-item?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @frkris!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3497). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3497)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Would you be able to provide a codepen showing this?

**Comment by frkris** [comment]
http://codepen.io/frkris/full/yydrOW/

Notice the difference in output between ng-repeat on an ion-item vs. a standard <a> tag.

**Comment by mhartington** [comment]
Hmm seeing this too. Will pass this to @adamdbradley

**Comment by adamdbradley** [comment]
When I correct the the demo to have two `{` the `ion-item` example I'm not seeing a difference in the output.

**Comment by adamdbradley** [comment]
Ahh ok, I see the issue now, fixing....

**Comment by frkris** [comment]
Thanks for the quick response guys! Much obliged!
