### ISSUE TITLE
bug: Windows Phone ng-hide/show doesn't work

### ISSUE THREAD

**Issue by VeldMuijz** [driftyco/ionic#3498]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,
When using ng-hide and ng-show on Windows Phone 8.1 it doesn't work.

When I add this css to the css file it does work:
```
[ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak,
.x-ng-cloak, .ng-hide:not(.ng-hide-animate) {
     display: none !important;
}
```

All credits go out to  [Tobias H&ouml;ßels post](https://www.hoessl.eu/2014/12/on-using-the-ionic-framework-for-windows-phone-8-1-apps/)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @VeldMuijz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3498). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3498)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
