### ISSUE TITLE
feat: Remove plugin/platform information from package.json

### ISSUE THREAD

**Issue by lewistaylor** [driftyco/ionic#3500]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>package.json is associated with npm, and having data related to cordova/ionic could be seen as polluting that. Suggestion to move this into a separate cordova/ionic json file.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @lewistaylor!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3500). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3500)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-cli#368
