### ISSUE TITLE
feat: Ionic plugin/platform auto updating of package.json

### ISSUE THREAD

**Issue by lewistaylor** [driftyco/ionic#3501]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>We are having a lot of issues with the auto plugin/platform feature that seems to happen with ionic (and not cordova?). 

* crosswalk added a conflicting version of in-app browser to one we had already added. 
* variables aren't automatically added either when creating a plugin

I realise the second is a tough problem to solve given that different argument could be passed, so instead it would be great to turn off this functionality. We are perfectly happy keeping track of our own list including vars, and using a gulp task to install them.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @lewistaylor!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3501). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3501)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-cli#367
