### ISSUE TITLE
feat: Add method to trigger ion-refresher manually

### ISSUE THREAD

**Issue by kageurufu** [driftyco/ionic#3504]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Use case:

I have several "index" views that show remotely loaded content, with filtering available. I would like to use a consistent indicator for refreshing, so I would like to be able to do something like 

    $scope.$broadcast('scroll.refreshStarted');

which, per my thinking, would cause the following:

```javascript
// js/angular/controller/refresherController.js
$element[0].classList.add('refreshing');
scrollTo(ptrThreshold, scrollTime); //with an animation
```

If requested, I can attempt to write this myself, and send in a PR.

If there is another way to handle this that I missed already in place, please let me know</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @kageurufu!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3504). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3504)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by clawish** [comment]
absolutely desirable feature! :+1: +1

**Comment by perrygovier** [comment]
@kageurufu, we're going to hold off on adding new features to Ionic until after the 1.0, [but I've added this to our new features trello board](https://trello.com/c/pofJCc7s/90-add-method-to-trigger-ion-refresher-manually). Please vote and comment on it to improve it's consideration for post 1.0.
