### ISSUE TITLE
bug: Range item color class doesn't immediately update

### ISSUE THREAD

**Issue by J4G-** [driftyco/ionic#3510]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have a set-up in which a toggle item is used to determine whether or not a range slider is disabled. To indicate that the range slider is disabled, I change its class between range-positive and range-stable, like so:
```
	<ion-toggle ng-model='state'>On/off</ion-toggle>
	<div class="item range" ng-class="{'range-positive': state, 'range-stable': !state}">
		{{ state}}
		<input ng-disabled='!state' type="range" min="0" max="100" value="33">
	</div>
```
While the disabled attribute correctly updates with every toggle click, the range class updates but does not display as updated until the next click (at which point it is incorrect).</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @J4G-!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3510). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3510)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Hey @J4G-, can you put this in a codepen so we can have something to quickly test against?

**Comment by J4G-** [comment]
Here you go!
http://codepen.io/anon/pen/GgVoEx

**Comment by mhartington** [comment]
Hmm, unless I'm missing something, it seems to work fine for me using the nightly builds.

http://codepen.io/mhartington/pen/XJvxdp

@J4G- can you confirm this for me?

**Comment by J4G-** [comment]
On Chrome (Windows 8.1 64 bit) they are still reversed for me, but on Chrome for Android they aren't... What's going on here?

**Comment by mhartington** [comment]
Hmm, thats interesting. What version of chrome is it? I just tested this on an android 4.4 and it seems to work fine. Are you having this issue on a device as well?

**Comment by J4G-** [comment]
Version 42.0.2311.90 m on my Desktop is broken, while version 42 on my Android 5 Nexus tablet works. I have no clue where the discrepancy would be.

**Comment by mhartington** [comment]
All good :+1:
