### ISSUE TITLE
bug: ionic view on iOS does not show latest app uploaded

### ISSUE THREAD

**Issue by bertramn** [driftyco/ionic#3512]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi there,

I created a simple example app and used `ionic upload` a few times to send updates I made to the app to my account. After sending updates I can see the newly uploaded app in the ionic view on iOS but when I download the app to the iPhone its still the old original app (as the app on the phone does not contain all changes made locally on my desktop pc). Any suggestions of what might be amiss?

Cheers,
Niels</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @bertramn!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3512). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3512)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tlancina** [comment]
Moved to View issues repo (also I think this is probably https://github.com/driftyco/ionic-view-issues/issues/10).
