### ISSUE TITLE
bug: cursor / pointer in textarea does not work properly

### ISSUE THREAD

**Issue by benziane** [driftyco/ionic#3513]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>In Ionic application (v1.0.0-rc.2) tested on ios (8.2 device and simulator) 

When keyboard is up and cover a part of the textarea. it's impossible to move properly the cursor in the textarea's text.

"<textarea name="comment" ng-model="data.comment" placeholder="Comment"></textarea>"

![unnamed](https://cloud.githubusercontent.com/assets/2342053/7107869/af918134-e173-11e4-9468-0987fda2233d.png)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @benziane!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3513). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3513)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment]
Hello! Are you still experiencing this issue with the latest version of ionic(ionic 1.2.4)? Thanks (:

**Comment by benziane** [comment]
This issue is corrected with the latest version.
Thanks.
