### ISSUE TITLE
bug: Memory usage grows really fast when making a lot of calls to a plugin

### ISSUE THREAD

**Issue by jmaylin** [driftyco/ionic#3522]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

When I try to make a lot of calls to a Cordova plugin, the memory usage grows really fast. And for some reason, it seems to be limited to about 1000 calls:

![enter image description here][1]

But the memory usage keeps growing afterwards:
![enter image description here][2]

It looks like the problem comes from Cordova, but when I run the same code on a pure Cordova app, the memory usage grows very slowly, and the app can make way more than 1000 calls (I manually stopped after 120000 calls).

So, a couple of questions come to my mind:
* While making a bunch of calls, why does the memory usage keeps growing?
* Why does Ionic+Cordova seems to use way more memory than Cordova alone?

Here is a [codepen](http://codepen.io/jmaylin/pen/vEoXzR) to illustrate. The only relevant part is in MyCtrl. It doesn't do anything because Cordova is not usable in here, but it would work on a phone.

[1]: http://i.stack.imgur.com/6MXqY.png
[2]: http://i.stack.imgur.com/G4IML.png</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jmaylin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3522). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3522)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tlancina** [comment]
Probably this: https://issues.apache.org/jira/browse/CB-8002.

**Comment by jmaylin** [comment]
Probably, but it doesn't explain why Cordova with Ionic uses way much more memory than Cordova alone

**Comment by MyBoon** [comment]
@jmaylin ... I guess Angular.JS is not helping.
