### ISSUE TITLE
bug: Nested popups do not release backdrop

### ISSUE THREAD

**Issue by jbollacke** [driftyco/ionic#3524]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Once one opens a nested popup (see http://codepen.io/anon/pen/ZYgLVw) the backdrop is not fully released and screen will stay dimmed.

1. Click on button "Open Popup" => backdrop dims the screen, popup no 1 opens
2. In the popup no. 1 click on "OK" => popup no1 closes, popup no2 opens
3. In the popup no. 2 click on "OK" => popup no2 closes

I expect the backdrop to be released and "un-dim" the screen again.

Note: IIRC this issue already popped up once upon a time. Take a look at my comment on  5658a4df0c2221f867ec3e0f6484f58094d516b4. Looks like popup/backdrop component really needs some more test coverage.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jbollacke!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3524). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3524)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
