### ISSUE TITLE
bug: SideMenu getOpenRatio equals 1 or 0 when toggled

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic#3525]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I want to add black opacity for side menu when it's partially opened.
I'm using for that
```
$scope.$watch(function () {
    return $ionicSideMenuDelegate.getOpenRatio();
}, function (newValue, oldValue) {
    opacityElement.style.opacity = 1 - newValue;
});
```
If I swipe the content it works great. But when I press menu toggle button getOpenRatio gets 1 || 0 without values between.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @piernik!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.

**Comment by piernik** [comment]
@Ionitron You are wrong - I don't need help - all is clear - Your feature works not as it should! It's a bug
