### ISSUE TITLE
feat: crosswalk 14

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic#3529]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>browser</span>

<span ionic-description>I want to use crosswalk browser with Google maps plugin.
Problem is that google maps needs crosswalk ver 14 - https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-CrossWalk-(Android)
ionic cli gives only 13
```
Available - Crosswalk - ionic browser add crosswalk
         Version 8.37.189.14 Published Fri Oct 10 2014 03:26:00 GMT+0200 (Środkowoeuropejski czas letni)
         Version 9.38.208.10 Published Tue Nov 25 2014 11:45:00 GMT+0100 (Środkowoeuropejski czas stand.)
         Version 10.39.235.15 Published Wed Dec 31 2014 13:16:00 GMT+0100 (Środkowoeuropejski czas stand.)
         Version 11.40.277.7 Published Thu Feb 26 2015 07:03:00 GMT+0100 (Środkowoeuropejski czas stand.)
         Version 12.41.296.5 Published Thu Mar 05 2015 13:19:00 GMT+0100 (Środkowoeuropejski czas stand.)
(canary) Version 13.41.318.0 Published Wed Mar 11 2015 09:22:00 GMT+0100 (Środkowoeuropejski czas stand.)
```
Can You update?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @piernik!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3529). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3529)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#380
