### ISSUE TITLE
bug: Menu doesn’t work in simulator/ios

### ISSUE THREAD

**Issue by khwerhahn** [driftyco/ionic#3532]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi,

I used the sidemenu starter to get me started. In the browser everything works fine, but not on ios and the simulator. The sidemenu still opens, but when you click on a link, nothing happens. How is this possible?

[ionic forum](http://forum.ionicframework.com/t/menu-doesnt-work-in-simulator-ios/20818/2)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @khwerhahn!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3532). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3532)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ajoslin** [comment]
If you take ngMaterial out, what happens?

**Comment by Ionitron** [comment]
Greetings @khwerhahn!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
