### ISSUE TITLE
replace the angularjs to react native

### ISSUE THREAD

**Issue by wozzup** [driftyco/ionic#3534]
`ionic` awesome!
but `angularjs` is sucks and meaningless. poor performance make developers pain.
replace the `angularjs` go forward to `react native` 
get better performance, make users and developers happy! winwin

**Comment by Ionitron** [comment]
Greetings @wozzup!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3534). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3534)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Thank you for the complement! However, Ionic2 is already under heavy development with Angular2 and we will not be switching to React or React Native anytime soon.
