### ISSUE TITLE
bug: min-width: initial not supported by IE/WP

### ISSUE THREAD

**Issue by Vargash** [driftyco/ionic#3535]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It looks like the `min-width: initial;` CSS property is not managed by Internet Explorer (and thus Windows Phone).

I've found that adding `min-width: auto;` before assure compatibility by fallbacking if "initial" is not supported.
Still trying to find if this breaks anything on other platforms.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Vargash!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3535). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3535)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Thanks, will look into this post 1.0

**Comment by Ionitron** [comment]
Greetings @Vargash!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
