### ISSUE TITLE
feat: Select text and image inside a div

### ISSUE THREAD

**Issue by buunguyen** [driftyco/ionic#3540]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm building an app where user can receive messages and images. I want these to be selectable for copy/paste. So far, the workarounds I read from old posts or forums don't work. Is there any way to select text/image without having to modify Ionic source?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @buunguyen!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3540). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3540)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @buunguyen!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
