### ISSUE TITLE
bug: Cannot set caret in contenteditable child elements

### ISSUE THREAD

**Issue by jhdrn** [driftyco/ionic#3542]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When using `contenteditable="true"` on an element, it is impossible to set the caret inside child elements. If the child is a text node, it works though.

This bug makes rich text editors unusable :/

It worked for us in rc0 but not in rc3. 

Se example http://codepen.io/anon/pen/rVBOMv

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jonathanhedren!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3542). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3542)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by kmturley** [comment]
I'm getting this issue on iOS device emulator using my Rich Text Editor:
http://kmturley.github.io/angular-sir-trevor/ionic-src/www/

The issue doesn't occur when only angular is used:
http://kmturley.github.io/angular-sir-trevor/

So it must be an ionic issue

**Comment by jgw96** [comment]
Hello! Are you guys still experiencing this issue with the latest version of ionic (ionic 1.2.4)? Thanks!

**Comment by kmturley** [comment]
@jgw96 nope, looks worse than before, the caret doesn't even appear in nested elements:
http://codepen.io/anon/pen/xVWdPP

Versus the previous version:
http://codepen.io/anon/pen/rVBOMv

**Comment by johannds** [comment]
This is a issue for me as well. It looks like clicking is also not functioning as it should. The caret position seems to be set randomly within the element. Is there a definitive answer on whether contentEditable officially works with Ionic?

**Comment by jgw96** [comment]
@johannds @kmturley does this issue only happen on mobile for you all?

**Comment by kmturley** [comment]
@jgw96 Nope you can replicate in Chrome (latest) using the links above

**Comment by jgw96** [comment]
@kmturley and this does not happen with just a plain angular project?

**Comment by kmturley** [comment]
@jgw96 yes if you compare my two examples with Angular vs Ionic:
http://kmturley.github.io/angular-sir-trevor/src/
http://kmturley.github.io/angular-sir-trevor/ionic-src/www/

Using Chrome, Inspect and emulate as a mobile device, one works, the other doesn't

**Comment by MayankLogiciel** [comment]
I am facing similar issue with ionic. Earlier i thought it is  due to ionic-scroll or ion-content issue then i  made a simple div contenteditable without ionic-scroll/ion-content with only text in it as below

```
<div contenteditable="true">
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum
</div>
```

When i edit this text and hit enter, it generates nested div structure without contenteditable and the second portion of text i.e the text inside nested div is now not editable anymore

Below is the html structure gets generated after hitting enter anywhere in the Lorem Ipsum text.

```
<div contenteditable="true">
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in th
    <div>
        e 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum
    </div>
</div>
```

With further experiments i found contenteditable doesn't work with nested html tags structure with ionic. I have tried nested html structure with different html tags (span, p, div, br, i, u) and it didn't work with anyone.

if i dynamically add contenteditable attribute to all tags then nested tags started working as editable.

**Comment by q769073309** [comment]
it is works in my project after change the code in ionic.js:
`  if (ele && ((/^(input|textarea|select)$/i).test(ele.tagName) || ele.isContentEditable ||ele.parentNode.isContentEditable )) {

  }`

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#6
