### ISSUE TITLE
perf: Input field for nested pages is not working(is seizing) on BB10 Device

### ISSUE THREAD

**Issue by litunny** [driftyco/ionic#3543]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi all , first and foremost Kudos to Ionic Team, you guys are surprising with designs and concepts, nice work!
I've been working on an app and...I made a deployment for Android , iPad (iPad Air) and BB10 (Blackberry Q5 Device), it works perfectly, rendered as expected, but one thing i took note later on BB10 Device. Inside some nested Pages, the Input field is seizing, if I try typing some texts it would not appear, untill I click on another object on the screen and drag the page, then it would start typing. I've try all my best to fix this out...I need HELP, ANY SOLUTION. Kudos Once again to Ionic Team and the forks at large, looking forward to hearing from you guys.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @litunny!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3543). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3543)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @litunny!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
