### ISSUE TITLE
bug: Navbar hides content when sidemenu + tab bar

### ISSUE THREAD

**Issue by basvdijk** [driftyco/ionic#3544]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>This bug has been closed but is still a problem in RC3:
https://github.com/driftyco/ionic/issues/3288#event-282662110

Type: bug
Platform: all

I am running into issues when I try to combine sidemenu + tab bar. The tab bar contents' are hidden underneath the sidemenu navbar.

Check this: http://codepen.io/anon/pen/jEerJZ

When I change version to 1.0.0-beta.14 then pen works. So is there any different implementation with 1.0.0-rc.0?

As stated earlier on line 2750 in ionic.css I have disabled top: 0 for the .pane, .view selector. Now everything works fine with tabs and side menu. I don't know if changing this value affects other setups. 

.pane, .view {
position: absolute;
/* top: 0;*/
right: 0;
bottom: 0;
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @basvdijk!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3544). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3544)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Investigating, it looks like it broke in this commit. Still trying to figure it out though. 
https://github.com/driftyco/ionic/commit/8ebde73d0b8afac1bf1c1787c90a72a28a88bc3a

**Comment by perrygovier** [comment]
This is a particularly nasty bug and will be difficult to solve without many costly DOM hits or a refactor of the navbar lifecycle. 
Unfortunately, I think the "fix" for now is to add the `has-header` class to ion-content like so: 
http://codepen.io/perrygovier/pen/OVLXBW?editors=101

**Comment by basvdijk** [comment]
@perrygovier What kind of problems do you run into when removing the top: 0 in the css? I work with this line removed since one of the latest beta's and still no problems regarding this removal.

**Comment by samuelcastro** [comment]
I have the same issue, take a look:
![bug-tabs-sidemenus-navbar](https://cloud.githubusercontent.com/assets/5281701/7213828/c8c15a64-e563-11e4-89b0-c6c3ea242d44.png)

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
