### ISSUE TITLE
bug: anchorScroll with collection-repeat

### ISSUE THREAD

**Issue by andiCR** [driftyco/ionic#3547]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Forum post reference:
http://forum.ionicframework.com/t/indexed-list-and-collection-repeat/21146
There is no support for collection-repeat using anchors. I understand that this was scratched because of performance decisions (according to this post https://github.com/driftyco/ionic/issues/3474), but I do not understand how we're supposed to use collection-repeat for large lists but can't scroll quickly on them (hence making the large list inconvenient as well. Is there a workaround for creating an indexed list?</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
You can still jump to a certain scroll position. If your items are 50px tall and you want to jump to the 100th item, simply jump to 5000px. 

This isn't really any different than issue #3474, and the conclusion is the same. I know that's probably not what you wanted to hear, but it's not worth the inherent slowdown anchor scrolling in collection-repeat would introduce. 

A more technical explanation: in order to allow anchor scrolling, we would have to parse the dom of every element in the list ahead of time, index, and cache it. As a list grows, that scales poorly.  In fact, at that point it'd be faster to let the browser use its native built in efficiencies with regular scrolling. 

If jumping to a px value isn't a feasible option, the most efficient way to anchor scroll that we can think of is native scrolling.
