### ISSUE TITLE
docs: Steps to start the sample web application

### ISSUE THREAD

**Issue by user1020** [driftyco/ionic#3549]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.3</span>  <span ionic-webview>browser</span>

<span ionic-description>New to ionic here.  I just want to get a sample web application running.  But don't see where the web server (I guess it's node.js based) can be started.  By the way, I have a Ubuntu 12.04 laptop. 

Here are the steps I followed:

```
ionic start myApp tabs   <---- works ok, created the directory structure
cd myApp               <--- works ok
sudo ionic build ios  <--- this failed, probably Ubuntu is not the target 
ionic login  <---this step works fine
```

Don't know how the sample application can start, so I can point my android phone to it.

Thanks.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @user1020!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3549). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3549)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Hey @user1020, a few things. 
First, you need Xcode installed to compile for iOS, which can only be done on a mac.
Secondly, you should not need to sudo the build command. In fact, I would expect it to ruin the permissions of your project and compiled app. 
Lastly, if you're trying to run your app on your Android phone, you'll need to build for android, not ios. 

If you're still having trouble, "how do I" questions are better asked on the forums.
