### ISSUE TITLE
bug: bug: Css not work vs html style="max-width:100%"

### ISSUE THREAD

**Issue by obcdnico** [driftyco/ionic#3552]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Css not work vs html style="max-width:100%"

all is in in title...

in html : 
```
<!

<  ion-slide-box on-slide-changed="slideChanged(index)" show-pager="true" active-slide="activeSlide">
< ion-slide ng-repeat="image in allImages">
< img ng-src="{{image.src}}" class="fullscreen-image"/ style="	max-width:100%;max-height: 80%;">
< /ion-slide>
</ ion-slide-box>

!>
```
in the style.css, is not working.. (all library and cli is up to date .-)
.master_img1 {
	max-width:100%;
	max-height: 80%;
}

very great framework :). i contribute..
</span>

<span is-issue-template></span>
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @obcdnico!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3552). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3552)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Could you please provide a codepen demo
