### ISSUE TITLE
bug: Ionic View doesn’t display local images

### ISSUE THREAD

**Issue by maketroli** [driftyco/ionic#3553]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>That's my issue now, I am working on my app, when I do ```$ ionic serve``` everything display properly in the browser, but once I build the app and then do ```$ ionic upload```, I go to the Ionic View app, and I have 2 issues, non of the images are displaying, and also I have an Audio tag which is for a Live Streaming, and it is no working also.

So, what is going on here ?

![img_1593](https://cloud.githubusercontent.com/assets/8395866/7216119/b8f2d8ea-e5b0-11e4-9163-8c9d5de8247a.PNG)

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @maketroli!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3553). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3553)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-view-issues#82
