### ISSUE TITLE
bug: bug: button after textarea won't show up

### ISSUE THREAD

**Issue by itgoujie2** [driftyco/ionic#3556]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>I tried putting button in any other place will be shown fine. Only after I put after a textarea, it won't show up.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @itgoujie2!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3556). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3556)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by itgoujie2** [comment]
Sorry, it turns out the problem is textarea tag. I used <textarea/> but after I changed to <textarea></textarea> the button shows up
