### ISSUE TITLE
bug: Nested slideboxes don't work as they should.

### ISSUE THREAD

**Issue by Maistho** [driftyco/ionic#3558]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Created a codepen to show the problem.
The last slide contains another slidebox, which will "double-slide" when scrolled.

http://codepen.io/Maistho/pen/pJzrOB</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Maistho!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3558). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3558)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
This is beyond the scope of what Ionic Framework intends to support
