### ISSUE TITLE
docs: Getting time out error on creating an ionic project

### ISSUE THREAD

**Issue by GSPriya** [driftyco/ionic#3565]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>
$ ionic start todo blank
Creating Ionic app in folder /Users/priti/todo based on blank project

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
 ✗ Error fetching: https://github.com/driftyco/ionic-app-base/archive/master.zip Error: connect ETIMEDOUT
 ✗ Error: Unable to initalize app: Error: connect ETIMEDOUT
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @GSPriya!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3565). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3565)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by GSPriya** [comment]
It is fixed with the command PROXY=http://myproxy.com:8081 ionic start myApp as I was behind a proxy.

**Comment by GSPriya** [comment]
Now i'm getting a time out error after this

Update config.xml
Initializing cordova project
running cordova plugin add org.apache.cordova.device
Fetching plugin "org.apache.cordova.device" via plugin registry
npm http GET http://registry.cordova.io/org.apache.cordova.device
npm http GET http://registry.cordova.io/org.apache.cordova.device

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#385
