### ISSUE TITLE
bug: Ionic lists with ui-sref and remove-animation causes that ui-sref action is triggered on a delete action

### ISSUE THREAD

**Issue by jdsampayo** [driftyco/ionic#3570]
@mhartington Here it is the github issue.

Have three cases:

1.- If I use item-remove-animate (it animates the delete action) and ui-sref (it makes the item clickable to send the user to another view), when I delete an item, it gets deleted but also, the ui-sref redirect is triggered.

2.- If I remove the animation class 'item-remove-animate", it works as I expect, the item is deleted and I'm still on the same view. The problem is that the items are deleted instantly, I would like to conserve the animation.

3.- If I remove the ui-sref, the animation works as expected but I lose the redirect.

Example:
http://codepen.io/jdsampayo/pen/QbLggv

There is a workaround preventing the propagation of the $event on delete:
http://stackoverflow.com/questions/29682405/ionic-lists-using-animation-on-remove-item-and-ui-sref-causes-that-both-are-tri

**Comment by Ionitron** [comment]
Greetings @jdsampayo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3570). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3570)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Already fixed via https://github.com/driftyco/ionic/commit/0421596b8147bb787e4988d1d64927a51dcd45c1
