### ISSUE TITLE
bug: Flicker When opening android lollipop keyboard

### ISSUE THREAD

**Issue by snowscripter** [driftyco/ionic#3572]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>There is a flicker of screen when I try to open my keyboard. And its very annoying as it defeats the whole purpose of nice UI. Please Look into this. Its happening on both of my devices --> Android 5.0.1 MotoG and Nexus 7 1st gen Android 5.1.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @snowscripter!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3572). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3572)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by snowscripter** [comment]
Even tried the RC4 version of IONIC. No help with that.

**Comment by perrygovier** [comment]
Is it any time the keyboard opens?  This isn't something we normally see.  Do you have a custom keyboard installed?  Can you provide a code sample or something we can use to reproduce the issue?

**Comment by snowscripter** [comment]
I am using the starter template. Side menu template. I have created a screen recorder. you can see the flicker on keyboard change focus and modal open and close. https://youtu.be/JCtEuMWTQFM

**Comment by tlancina** [comment]
Are you using Crosswalk? Looks an awful lot like https://crosswalk-project.org/jira/browse/XWALK-3547.

**Comment by snowscripter** [comment]
Yes I am Using CrossWalk. If I don't then the app is extremely slow, slow transition of simple slide. .

**Comment by tlancina** [comment]
Yeah unfortunately this is a Crosswalk bug, not an Ionic one. I'd encourage you to take a look at the issue I posted, which has links to other people with the same problem, maybe they can help.

**Comment by rahul4819** [comment]
We are building a hybrid application (jQuery Mobile and Cordova) and I am facing the same issue of keyboard flickering with number inputs as above, on Nexus 5(Android OS 5.1.1 with Webview version: 42.0.2311.138).
I have tested the same application on Nexus 5(Android OS 5.1.1 with Webview version: 39.0). and it works perfectly without any flicker.
Please let me know if you found fix for this issue.

**Comment by maverix** [comment]
I followed the instructions from https://crosswalk-project.org/jira/browse/XWALK-2958
Which was a one line edit changing the options to a straight false on this line:
https://github.com/infil00p/cordova-crosswalk-engine/blob/master/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java#L37
