### ISSUE TITLE
bug: Back Button is going too far on double taps

### ISSUE THREAD

**Issue by EMCP** [driftyco/ionic#3573]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a back button in my Ionic app, that when double tapped goes too far back and completely logs out of the application.  Is there a scheme or best practices for getting my app to notice that two clicks have been done, but not to go back twice?  I think this issue has to do with the millisecond delay getting removed in iOS 

Thanks</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @EMCP!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3573). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3573)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @EMCP!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.

**Comment by EMCP** [comment]
Roger that.
