### ISSUE TITLE
 Slidebox not show with ng-controller

### ISSUE THREAD

**Issue by QwertyPong** [driftyco/ionic#3577]
I make an ios project with ionic-angularjs
I wanna show data with ng-controller in slidebox but cannot show.
I added $ionicSlideBoxDelegate.update on my controller but still have a blank white screen.
Do you all have a solution?

**Comment by Ionitron** [comment]
Greetings @QwertyPong!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3577). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3577)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Slidebox assumed it is living inside an Ionic app with an `ion-content`. Could you demonstrate your problem in a codepen?

**Comment by Ionitron** [comment]
Greetings @QwertyPong!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
