### ISSUE TITLE
bug: conditional ng-class bug when placed on ion-header-bar

### ISSUE THREAD

**Issue by jason-engage** [driftyco/ionic#3578]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I didn't set up a codepen, but this seems like a bug.

1) Try adding a conditional ng-class like below:
   ```
 <ion-header-bar class="bar bar-header bar-light" ng-class="eventDetail.isPrivate ? 'bar-calm' : 'bar-royal'">
```
2) Also have a second ```<ion-header-bar>``` below it with ```class="bar bar-subheader"```

3) In the ```<ion-content>``` below add ```class="has-header has-subheader"```

4) The ion-content element will show up in the DOM without the ```has-subheader``` class. It will appear to go underneath the subheader.

5) However if you remove the ng-class from the ion-header-bar, the ion-content will keep both has-header and has-subheader and show correctly. 

6) I also have 'has-footer' in my code, maybe thats part of it. idk.

Good luck.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jason-engage!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3578). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3578)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by MyBoon** [comment]
Do you mind setting up a codepen? Will be easier for everyone to figure it out :)

**Comment by Ionitron** [comment]
Greetings @jason-engage!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
