### ISSUE TITLE
feat: broadcast an event on side menu open/close

### ISSUE THREAD

**Issue by raibutera** [driftyco/ionic#3579]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>as issue title states, I intend to create a PR which adds a `$broadcast` event for side menus being opened/closed. At the moment creating a custom function that wraps menu-toggle functionality doesn't quite work, because it won't be fired (obviously) when the menu is closed via tap/drag.

some questions:

- does ionic have its own event system I should be aware of?
- what should I name the event? I was thinking `$ionicMenuOpen` and `$ionicMenuClose`
- where's best to add this behaviour?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @raibutera!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3579). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3579)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Thanks for creating the PR, lets continue the discussion there.
