### ISSUE TITLE
docs: The last changelog in the Readme file contains duplicate previous changelog

### ISSUE THREAD

**Issue by 5im0n** [driftyco/ionic#3580]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Problem with last changelog 1.0.0-rc.4 "sulfur-suricate" (2015-04-20) in the Readme file</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @5im0n!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3580). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3580)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Fixed https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#100-rc4-sulfur-suricate-2015-04-20
