### ISSUE TITLE
Sidemenu links not working in simulator

### ISSUE THREAD

**Issue by chrisschaub** [driftyco/ionic#3582]
When I use the ionic start with the sidemenu template, the left links don't go anywhere when clicked in the simulator on osx. I think there is a whitelist bug with ion-item and href. If the href is moved out to a simple anchor tag then the links work. This fixes it
```
.config(function($stateProvider, $urlRouterProvider, $compileProvider) {
  $compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|ftp|mailto|file|geo|tel|local):/);
```
The fix came from the forums here
http://forum.ionicframework.com/t/ion-item-href-doesnt-work-on-blackberry10/1281/6

Hope it helps.

**Comment by Ionitron** [comment]
Greetings @chrisschaub!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3582). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3582)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
