### ISSUE TITLE
bug: cordova: cordova 4.3.0 bug in config.xml while the name has special characters (&amp;)

### ISSUE THREAD

**Issue by gabrielmuresan** [driftyco/ionic#3584]
I have no idea where to post this for apache cordova to see, but in the latest version of cordova (4.3.0) installed via sudo npm install -g cordova having a name in the config.xml that includes a & character written as &amp; gives a very weird error that says that config.xml and info.plist are missing.

to duplicate this:
npm install -g cordova
write config.xml name as "Foo &amp; Bar"
ionic platform rm ios
ionic platform add ios

error!

P.S. only appearing for iOS platform

**Comment by Ionitron** [comment]
Greetings @gabrielmuresan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3584). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3584)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Cordova specific issues can be found here.

https://issues.apache.org/jira/browse/CB-8250?jql=text%20~%20%22special%20characters%22

Closing this since it is related to cordova and not ionic
