### ISSUE TITLE
Wikipedia Page

### ISSUE THREAD

**Issue by superallen** [driftyco/ionic#3585]
I'm surprised that Ionic Framework does not have a Wikipedia page.

**Comment by Ionitron** [comment]
Greetings @superallen!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3585). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3585)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Already on there. http://en.wikipedia.org/wiki/Ionic_%28mobile_app_framework%29
