### ISSUE TITLE
bug: ionSlidePager not included in build

### ISSUE THREAD

**Issue by QuentinFchx** [driftyco/ionic#3587]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I just updated to the last version `rc-4` and it seems that the `ionSlidePager` (introduced [here](https://github.com/driftyco/ionic/commit/7ef9ad74#diff-d45ecdc2c45e0176a107c19428a3c752) is not included in the bower package.</span>

EDIT: The commit was done on Sep 25
It has been reverted in [this commit](https://github.com/driftyco/ionic/commit/2910f508a9c3a877efede5923a84f36ef22f7bba)

Why does it appear in thie `rc-4` changelog and in the doc ??????

Linked with #3580 

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @QuentinFchx!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3587). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3587)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
The ion-slide-pager was from a different version slide-box. This should be delete from the ionic-site.

**Comment by QuentinFchx** [comment]
Thanks for the quick answer. I noticed you updated the website but could you please fix that `rc-4` changelog ?
It makes the upgrade almost impossible todo because we don't know what's really changed...
