### ISSUE TITLE
bug: Unable to open an app in ionic view

### ISSUE THREAD

**Issue by deepak229** [driftyco/ionic#3590]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I have view 1.0.0. When I install the app through ionic run android, it opens the app fine. But when I upload and view the app from view, it does not open up the app from there. Seems that it is not making any backend calls. Any suggestions?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @deepak229!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3590). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3590)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This is most likely an issue with view and not ionic, please open your issue here.
https://github.com/driftyco/ionic-view-issues
