### ISSUE TITLE
bug: When showing items, sometimes ion-content doesn't update height so new items are off the bottom of the view

### ISSUE THREAD

**Issue by tomchiverton** [driftyco/ionic#3591]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Demo : http://codepen.io/tomchiverton/pen/GJRQBY/ 
Load in the Chrome phone simulator and select iPhone 5. The 'can you' button should be just on the bottom of the screen.
Click the last checkbox, then quicky try to scroll up. The view bounces, and the newly shown text and buttons are cut off.
It works as expected if you wait a few seconds before scrolling up.

If you compile the app with PhoneGap / Cordova and deploy to real Android 4.x or iOS7 and iOS8 phones the exact same issue occurs, so it's not a simulator issue.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @tomchiverton!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3591). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3591)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by promactkaran** [comment]
Possible Hack: try calling this function on your check box click function "todoList.updateAnyYes()". 

 $ionicScrollDelegate.scrollTo(0,$ionicScrollDelegate.getScrollPosition().top,true);

this will recalculate the height and you will be able to scroll down. Let us know it it worked.

**Comment by tomchiverton** [comment]
Updated Pen: http://s.codepen.io/tomchiverton/debug/aObYVK?

Yes, that does seem to work in Chrome simulator, and doesn't seem to move the scroll visibly, despite the call to scrollTo(). Seems to work the same on a real Android device to.

**Comment by mhartington** [comment]
Since scrolling is a js-component, you need to update the scroll-view if you add/remove elements.

http://codepen.io/mhartington/pen/mJdjZJ

http://ionicframework.com/docs/api/service/$ionicScrollDelegate/#resize

**Comment by tomchiverton** [comment]
Shouldn't this be documented somewhere ? Like the ion-content page ?

**Comment by mhartington** [comment]
Added via dcd042e849ed1cbdea8d61ba728e791cb712b2f6
