### ISSUE TITLE
bug: Bug: swipe to go back doesn't work in some cases

### ISSUE THREAD

**Issue by deiucanta** [driftyco/ionic#3595]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I created two codepen links to showcase a case where swipe to go back doesn't work. The example has two screens a.html and b.html with a simple button in screen a that link to screen b.

1. The first implementation has only two states but no abstract parent.
  - codepen: http://codepen.io/pen/ZGEoaV
  - preview: 759f9a66
2. The second implementation has two states plus an abstract parent.
  - codepen: http://codepen.io/pen/XbWqZw
  - preview: a1ee60fc

Both of them work fine in the simulator but only the second one works in Ionic View.

Any ideas why?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @deiucanta!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3595). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3595)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Hmm, this may just be an issue with ionic-view. Not sure why this isn't working, but it does work on the device. You may want to make an issue over here

https://github.com/driftyco/ionic-view-issues
