### ISSUE TITLE
docs: $ionicScrollDelegate still around - Misleading changelog

### ISSUE THREAD

**Issue by NoelLH** [driftyco/ionic#3596]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I was excited and a little terrified to see the long [list of changes in rc4](https://github.com/driftyco/ionic/blob/v1.0.0-rc.4/CHANGELOG.md).

One which looked like it would affect my app is

    $ionicScrollDelegate, $ionicSlideBoxDelegate, and $ionicSideMenuDelegate have been removed.

But upon following the advice given it appears that in 1.0.0-rc4 this has not actually happened. My old code works. The suggested changes break everything. Am I missing something?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @NoelLH!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3596). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3596)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
There was an error in our release process, and the change log was effect :disappointed: 

All updated now. 
https://github.com/driftyco/ionic/blob/master/CHANGELOG.md
