### ISSUE TITLE
bug: bug: slide-box does not work in list-card

### ISSUE THREAD

**Issue by psimondk** [driftyco/ionic#3599]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If you place a slide-box in a list card it does not work (does not show). If you just use an ordinary list item it works:

```
<!-- Does not show -->
<div class="list card">
	<div class="item item-divider item-light"><h3>Example</h3></div>
	<div class="item">
		<ion-slide-box>
	    	<ion-slide>
				slide 1
	    	</ion-slide>
	    	<ion-slide>
				slide 2
	    	</ion-slide>
	    	<ion-slide>
				slide 3
	    	</ion-slide>
		</ion-slide-box>
	</div>
</div>
```

```
<!-- Does show -->
	<div class="item">
		<ion-slide-box>
	    	<ion-slide>
				slide 1
	    	</ion-slide>
	    	<ion-slide>
				slide 2
	    	</ion-slide>
	    	<ion-slide>
				slide 3
	    	</ion-slide>
		</ion-slide-box>
	</div>

```</span>

<span is-issue-template></span>
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @psimondk!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3599). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3599)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by psimondk** [comment]
There are many issues with the current slide-box. For instance if you have this combination. Nothing happens and ng-repeat slides will not work:

    <ion-slide-box delegate-handle="my-delegate" on-slide-changed="slideHasChanged($index)">

You need to do like this:

    <ion-slide-box delegate-handle="my-delegate" on-slide-changed="slideHasChanged($index)">

So please give slide-box a little attention before you issue 1.0 :-)

**Comment by psimondk** [comment]
And this:

    $scope.$on('$ionicView.beforeEnter' 

does not work if you use does-continue and auto-play on your slide-box in which case the auto-play is not resumed when you re-enter the view.

For that to work the only solution right now is to not cache the view and even then doea-continue only work sporadically. So the real title of the issue should be 'issues with slide-box'.

**Comment by Ionitron** [comment]
Greetings @psimondk!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
