### ISSUE TITLE
bug: Side menu left closes when popover show

### ISSUE THREAD

**Issue by sgg90** [driftyco/ionic#3600]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I have expose-aside-when on the left menu and it works great. But when it's on portrait mode, if I click on the side left popover, the menu content will be shown without expect it. I have done a codepen to show it. To check, it:

Put it on portrait mode.
Click the button who shows the left menu.
Click the popover which is on the footer.
(the left menu will be closed)

How can I solve it? I want my menu opened when I see the popover.

http://codepen.io/sgg90/pen/bdGgwV

Thank you so much!!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @sgg90!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3600). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3600)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by AlexYankee** [comment]
This behaviour forced by expose-aside-when directive. Try to temprorary remove it.

**Comment by sgg90** [comment]
Temporary "solved" with a timer:
```
    function openPopover( event, isAside ) 
	{
		$scope.sourcesPopover.show( event );
		if (!isAside)
		{
			$timeout(
				function ()
				{
				    $ionicSideMenuDelegate.toggleLeft(true);
				}, 1000
			);
		}
	}

**Comment by Ionitron** [comment]
Greetings @sgg90!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
