### ISSUE TITLE
bug: Unchecking a required <ion-checkbox> does not make the form $invalid

### ISSUE THREAD

**Issue by imgx64** [driftyco/ionic#3603]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Issue #2786 was closed by Ionitron as inactive, but it's still present so I'm reopening it. The plunkr link below uses nightly builds.

== Original bug ==

Plunkr: http://plnkr.co/edit/NZAg38SAjgSQzbRTl9WY?p=preview

I'm using [Angular form validation](https://docs.angularjs.org/guide/forms). An unchecked `<ion-checkbox>` with `required` attribute correctly makes the form `$invalid`. However, if I **check it then uncheck it**, the form does not become `$invalid` again.

This problem does not happen with a plain `<input type="checkbox">`, as demonstrated in the plunkr.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @imgx64!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3603). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3603)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by imgx64** [comment]
This doesn't seem to be fixed, the plunkr still exhibits the same behavior with the latest nightly:  http://plnkr.co/edit/NZAg38SAjgSQzbRTl9WY?p=preview

**Comment by badpenguin** [comment]
+1

**Comment by jlstr** [comment]
+1

**Comment by herman1vdb** [comment]
had the same issue, use `ng-required="true"` of `required="true"`
Works like a charm, so it is fixed :)

**Comment by crazypigs** [comment]
+1
