### ISSUE TITLE
bug: keyboard overlays input if scroll=false

### ISSUE THREAD

**Issue by ctaepper** [driftyco/ionic#3605]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>in my iPad app, i open a modal, which has inputs in it
the view is a ion-modal-view with ion-content inside
however, i set scroll=false to this ion-content

when i focus a input at the bottom, the keyboard slides up and covers the focused input. only when i start to type, the scrollview slides up and reveals the input

all is working fine with scroll=true.

additional, but maybe unrelated info: i set $modal-inset-mode-break-point to a very high value in order to get fullscreen modals on ipad</span>

<span is-issue-template></span>

**Comment by tlancina** [comment]
I believe this is expected behavior, if your content is not scrollable, then the input cannot be scrolled into view.  I would suggest disabling the keyboard code using `ionic.keyboard.disable()`, since you are relying on the native browser scroll to bring the input into view, but this will mean your header (if you have one) will be pushed off screen.

**Comment by ctaepper** [comment]
there is no disable() method in ionic.keyboard in RC4...
so what to to?

**Comment by tlancina** [comment]
Ah sorry @ctaepper, I added it just after rc4 was released.  So you can either use the latest code in nightly, or wait for rc5, which should be out this week.
