### ISSUE TITLE
bug: sidemenu stop appearing on swipe & page not scroll

### ISSUE THREAD

**Issue by igorizr1** [driftyco/ionic#3607]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Menu stop appearing with swipe. And all page stop scrolling.

When I click from one page with side menu to another page - that other page stop scrolling and side menu is not appearing via swipe</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Hey @igorizr1, can you put together a codepen related to this bug?

**Comment by codestack123** [comment]
http://codepen.io/anon/pen/rVVEMe

**Comment by igorizr1** [comment]
@perrygovier i put it together. It doesn't scroll on one of the screens. 

http://codepen.io/anon/pen/rVVEMe

**Comment by perrygovier** [comment]
Thanks, It looks like there's some places where you mix different structures and approaches. 

First off, the `<ion-nav-bar>` is meant to be in the parent, abstract, template in side menus. Then you can override what's in it using `<ion-nav-buttons>`.  You're welcome to use raw `<div>`s and CSS, but you'll loose pretty page transition animations. 

Next up, your default route goes directly to `/home`. This loads that page directly and not the parent sidemenu architecture, so the side menu wont display because it doesn't exist. The correct default route would be `/event/home`

On one of your templates, the opening `<ion-content>` was missing, which is what probably broke scrolling. 

For nested states, like in sidemenus and tabs, the child view has to be defined in the `$state` deffininition to associate the child page with the proper `<ion-nav-view>`. 

I've gone and updated the codepen to what I think you're trying to do and it's working well for me. 
http://codepen.io/perrygovier/pen/NqGQax?editors=101
