### ISSUE TITLE
bug: doesn't ionic view  include crosswalk - chromium?

### ISSUE THREAD

**Issue by isaldarriaga** [driftyco/ionic#3608]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When webview is not an option, you probably use crosswalk either for performance or functional reasons.

After uploading my app to ionic view, I see it's not working at all. The app is using angular material.

2 questions:

- If i set my app to use crosswalk, it will load the engine in ionic view?
- Is it possible to debug the app running in ionic view with chrome remote debugging?

Thanks,

Ivan.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @isaldarriaga!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3608). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3608)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-view#55

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-view-issues#88
