### ISSUE TITLE
bug: ion-slide-box with two slides and does-continue does not work correctly

### ISSUE THREAD

**Issue by KillerCodeMonkey** [driftyco/ionic#3609]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>hey guys in the rc4 and last nightly i use an ion-slide-box with the does-continue attribute and two slides.

http://codepen.io/bengtweisse/pen/PqYyvM

you can scroll to the second slide, but not back and not forward.
If you swipe back from the first slide the pager is not correct.
In the dom you can see more than two ion-slides.

If you resize the window there are suddenly four pager-"points".

If you add a third slide everything works fine.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @KillerCodeMonkey!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3609). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3609)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by b0jan** [comment]
+1

**Comment by ronaldcurtis** [comment]
+1

**Comment by fileupload** [comment]
I have met the same problem recently, and when checking the ioinc souce code of "ionic.bundle.js", I found this souce as below:

      special case if two slides
      if (browser.transitions && options.continuous && slides.length < 3) {
        element.appendChild(slides[0].cloneNode(true));
        element.appendChild(element.children[1].cloneNode(true));
        slides = element.children;
      }

It seems like that If and only if the slide count is 2, ionic will double the count while setting up.
I don't quite understand why the author added this special case, and how to fix it properly,
but after commenting them out, the problem seems like get resolved.

May this be helpful.
Cheers.

**Comment by yu521088** [comment]
I am having the same problem now, +1

**Comment by FME-nstokoe** [comment]
Same here. +1

**Comment by djangojack** [comment]
Same problem. +1

**Comment by diegoeduardorios** [comment]
+1

**Comment by Xalio08** [comment]
+1

**Comment by tflavin** [comment]
Also having this issue (+1).

**Comment by tflavin** [comment]
I was able to find a temporary fix for my issue.

My issue was slightly different than the original post in that the pager was showing two pager icons but actually had four slides. When you got to slides 3 and 4 (which were duplicates of 1 and 2), no pager icon was selected. 
So, whenever I only have two slides and the slide changes (using on-slide-changed), I check the current index via $ionicSlideBoxDelegate.currentIndex(). I have an ng-class applied if the index is 2 (ex: first-slide) and one when it is 3 (ex: last-slide). I also overrode the css for the .first-slide .slider-pager span:first_child and .last-slide .slider-pager span:last_child to have opacity: 1.

This change makes it appear that there are only 2 slides, even though there are really 4. This wouldn't work if the issue didn't let me slide through like in the original post, but for my issue it was good enough until there is a fix.

**Comment by marcocaimi** [comment]
have the same issue as tflavin, 4 slides and only two slides, but if i open a modal over the page when the modal is closed the sliders became 4.

**Comment by JerryBels** [comment]
@tflavin +1 two slides should definitely not be changed into 4 slides. It's counter intuitive. Or at least it should be in the docs !

**Comment by Stefferp** [comment]
Having the same problem. Any proper fix yet?

**Comment by cheesezhe** [comment]
same issue...+1

**Comment by mrtomrichy** [comment]
+1

**Comment by sebrojas14** [comment]
Same here with 1.1.0

**Comment by mesca** [comment]
+1

**Comment by meticoeus** [comment]
Another work around is to special case your model to explicitly duplicate your array in the pattern [0, 1, 0, 1] if it has 2 elements.

**Comment by cheesezhe** [comment]
Hey,guys, I add the following code to my controller script, and it seems that that bug disappeared.
function loadIds() is to get json data from server and store data into $scope.ids
'''javascript'''
$scope.$on('$ionicView.beforeEnter', function(){
        if($scope.ids.length == 0){
          $scope.loadIds();
        }else{
          $ionicSlideBoxDelegate.update();
          $ionicSlideBoxDelegate.loop(true);
        }
      });

**Comment by Tiagojdferreira** [comment]
It seems the copied objects don't inherit the data in their scope, causing the following code to not work:
````
ng-click="goTo(post)"
````

**Comment by tipstrade** [comment]
I've had some the same issue and fixed it using the following hack:

Make sure you have an *ng-if* directive on the *ion-slide-box* (*ng-show* does **not** work) so that it's not rendered unless there are items

Second, when updating the *ng-repeat* source, swap it out with null (or an empty array), and then update in a $timeout:

```javascript
    // HACK: Because of the annoying bug with the slider pager dots being duplicated
    var temp = $scope.transaction.Vehicle.Photos;
    $scope.transaction.Vehicle.Photos = [];
    
    $timeout(function() {
      $scope.transaction.Vehicle.Photos = temp;
      
      $timeout(function() {
        var del = $ionicSlideBoxDelegate.$getByHandle("details-thumbnails");
        del.update();
        del.slide(0);
      });
    });


The two sets of timeouts are required

**Comment by visormatt** [comment]
+1

**Comment by DezDing** [comment]
+1

**Comment by Clawg** [comment]
This is still an issue in 1.1.1.  I have created a pen (http://codepen.io/clawg/pen/ojKQQm) where the number of dots jumps form 2 to 4 when you resize the window.  This only happens with 2 items and its not even http data that populates the ion-slide.  Also worth noting is the active state of the dot, before resize where there are 2 the dots get out of sync as they are working off 4 slides not 2.

**Comment by mlynch** [comment]
Fixed in master and landing in 1.2:

Hey everyone, can you try the new slidebox just pushed to master (available in upcoming 1.2):

```html
<ion-slides options="options">
  <ion-slide-page>
  </ion-slide-page>
</ion-slides>
```

Handles the < 3 slide and looping case a lot better! Specify options in the options scope variable:

```javascript
controller('MyCtrl', function($scope) {
  $scope.options = {
    loop: true
  };
});
```

**Comment by kormic** [comment]
I still have this issue in 1.2.4

**Comment by fareesh** [comment]
Still in 1.2.4 for me as well

**Comment by omma2289** [comment]
I'm on version 1.2.4 and have the same issue described by tflavin

**Comment by fengsong97** [comment]
+1

**Comment by andreluizbellon** [comment]
+1

**Comment by jgw96** [comment]
Hey @fengsong97  and @andredublin are you guys using ionic 1.3.1?

**Comment by RohitDhamal** [comment]
@fileupload  thanx, since your rply gave me idea. Facing same type of problem. But was able to do some changes and they are working fine as of now so far... I dnt know whether that is correct way or not completely but following changes in ionic.bundle.js helped me solve my issue though. Just commented following lines:-

//special case if two slides
  if (browser.transitions && options.continuous && slides.length < 3) {
    element.appendChild(slides[0].cloneNode(true));
    element.appendChild(element.children[1].cloneNode(true));
    slides = element.children;
  }

with these everything is working fine so far.

**Comment by wkoeter** [comment]
@RohitDhamal 

Your solution only makes the slide transition awkward. My guess is that the programmer did this for transition animations.

slide 1 | **slide 2** 

If you swipe left from slide 2 there is no slide to its right which makes it look like there is NO sliding done while in fact the slide DID change. With 3 slides there is always a slide to the right so the transition can occur smoothly.

slide 1 | **slide 2** | duplicateslide 1 


looking forward to a fix :/

**Comment by wkoeter** [comment]
If you update to ionic Latest Version: 1.3.1 "el salvador" you can use another directive which is not ion-slide-box but ion-slides. This appearently does not have these issues.

**Comment by happysiva** [comment]
+1
