### ISSUE TITLE
bug: Wrong title displayed when mixing image and text in view titles

### ISSUE THREAD

**Issue by heidgert** [driftyco/ionic#3614]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Codepen: http://codepen.io/heidgert/pen/YXPXXV

The "Home" and "Page 1" pages uses an image in the title bar. "Page 2" uses a text.

Description of how to replicate the problem:

1. Notice the ionic image in the title bar on the first page.
2. Click on "Go to page 1"
3. Notice the image in the title bar.
4. Click on "Go to page 2".
5. Notice the "Page 2" title in the title bar.
6. Click "< Back"
7. Notice the image in the title bar.
8. Click "< Back"

Notice the text that shows in the title bar, which is taken from "Page 2", while it should show the image instead.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @heidgert!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3614). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3614)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by GuyPie** [comment]
+1

**Comment by mhartington** [comment]
Hmm, alright thanks for pointing this out.
Seems that when you go to view 2, it replaces the cached nav-title from the home view with the title from page 2. Being close to 1.0, we may not be able to push a permanent fix for this, but a temporary work around would be to use ion-nav-title's like this.

http://codepen.io/mhartington/pen/ZGYwRE

Will revisit this post 1.0.0

**Comment by danbucholtz** [comment]
Hi @heidgert,

Thanks for submitting this issue.  Per the documentation, this functionality must be used within an ion-view.  I have looked into your example and what it would take to get it to work the way you'd like, and it is non-trivial 😄 

http://ionicframework.com/docs/api/directive/ionNavTitle/

```
The nav title directive replaces an ionNavBar title text with custom HTML from within an ionView template
```


I was able to resolve your issue by placing the `ion-nav-title` within the template.

```
<script id="templates/home.html" type="text/ng-template">
	<ion-view>
    <ion-nav-title>
        <img src="http://ionicframework.com/img/ionic-logo-white.svg" style="max-height: 90%;">
  	</ion-nav-title>
		<ion-content>
			<h1>Home</h1>
			<p>This page should inherit the image title</p>
			<a ui-sref="page1" class="button button-block">Go to page 1</a>

		</ion-content>
	</ion-view>
  </script>
```

I am hesitant to make a change here and introduce a bug that breaks a bunch of other apps.  The header will be more flexible and better designed in V2.

Thanks for contributing - we appreciate it!

Thanks,
Dan
