### ISSUE TITLE
bug:can't install ionic

### ISSUE THREAD

**Issue by xjinza** [driftyco/ionic#3616]
Type: bug

Platform: window 64 os
version :nodejs  v0.10.26
              npm     v1.4.3
when I use the command $npm install -g ionic,some errors happened.or sometime it will stop a long long time.
![44](https://cloud.githubusercontent.com/assets/3285701/7332922/4c19c3a0-eb8c-11e4-8839-258c79f0de32.png)

![567](https://cloud.githubusercontent.com/assets/3285701/7332918/1f802690-eb8c-11e4-831b-30aaffb27210.png)

**Comment by Ionitron** [comment]
Greetings @xjinza!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3616). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3616)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by xjinza** [comment]
ps:I am so sorry, I can't update issue from your custom issue form,
because I am from China ,I have to go through the great Wall.and  service of google is forbidden
 to visit .
I update the issue from github is okay?

**Comment by perrygovier** [comment]
Hey @xjinza, that's ok. Since this is related to the CLI, I'm going to pass this on to that repo. 
Josh can help more, but it looks to me like you may have some permissions issues.

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#398

**Comment by xjinza** [comment]
thanks very much
