### ISSUE TITLE
bug: keyboardActiveElement is undefined if keyboard started from an input inside a popup

### ISSUE THREAD

**Issue by gabrielmuresan** [driftyco/ionic#3618]
![screen shot 2015-04-25 at 18 55 19](https://cloud.githubusercontent.com/assets/6017306/7333805/cac8e07e-eb7c-11e4-9981-055d3b97c2ab.png)

**Comment by Ionitron** [comment]
Greetings @gabrielmuresan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3618). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3618)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tlancina** [comment]
Dup of https://github.com/driftyco/ionic/issues/3586.
