### ISSUE TITLE
bug: Nest redundant  ion-nav-view in ionTabs, state name format issue.

### ISSUE THREAD

**Issue by janckerchen** [driftyco/ionic#3621]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>There is a nest redundant  ion-nav-view  when I debug ion-tabs.

```
<ion-nav-view name="game" ...>
  <ion-nav-view ..>
     <ion-view>
```

After a deep dive,  I found a wired name composition in navViewController.js:42

    if (navViewName.indexOf('@') < 0) navViewName  = navViewName + '@' + parentViewName;

I  traced $state.$current.locals at navView.js:185,  it has different statename format 

    $state.$current.locals = 
     .....
    '@app.game': Object

Obviously,  game@app dont match @app.game,  if I fix statename format,  nest  ion-nav-view is gone

```
<ion-nav-view name="game" ...>
     <ion-view>
```

Is it bug?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @janckerchen!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3621). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3621)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Hey @janckerchen, thanks for the research. Can you put together an example codepen that demonstrates the issue?

**Comment by janckerchen** [comment]
I wakeup and calm down, go back the issue.  I must  apologize, there is abstract state with inline template in my states define which add ion-nav-view. so just forget it.
