### ISSUE TITLE
The official website of ionicframework is auto redirect to http://wpkg.org/

### ISSUE THREAD

**Issue by yangheng** [driftyco/ionic#3622]
please !

**Comment by Ionitron** [comment]
Greetings @yangheng!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3622). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3622)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by zheng1** [comment]
same problem

**Comment by KLVN** [comment]
@yangheng @zheng1 Take a look at this thread: http://www.reddit.com/r/China/comments/33wpk3/anyone_else_almost_all_websites_in_both_chrome/cqp8kqu

**Comment by tlancina** [comment]
@KLVN thanks for looking into this! Closing this as it's not an Ionic issue.

**Comment by zengsn** [comment]
why and how, the issue still there! @_@
