### ISSUE TITLE
bug: Method anchorScroll() from $ionicScrollDelegate with ion-scroll xy and zoom

### ISSUE THREAD

**Issue by Lesac76** [driftyco/ionic#3629]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>AnchorScroll on a ion-scroll with scrolling in both directions and zoom enabled seem only to be working when zoom is exact 1. Larger Zoom results in unexspected behaviour as the anchor Id is not going to the top.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Lesac76!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3629). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3629)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Could you demonstrate this in a codepen?

**Comment by Ionitron** [comment]
Greetings @Lesac76!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
