### ISSUE TITLE
bug: Some files must be cached when ionic upload is run on existing project

### ISSUE THREAD

**Issue by PhilAndrew** [driftyco/ionic#3632]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>I downloaded Ionic Material example project and started from there.
ionic upload
Then added a new controller, view, then ionic upload again.

It didn't work.

When I went to ionic.project file and deleted the app_id's value, then upload, it worked.

I use the Ionic preview app.

see
http://stackoverflow.com/questions/29867007/ionic-framework-uploading-to-ionic-view-app-not-getting-latest-javascript-fil</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @PhilAndrew!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3632). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3632)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tlancina** [comment]
Hey thanks for the report, this is a known issue: https://github.com/driftyco/ionic-view-issues/issues/10, and is fixed in the latest ionic-cli beta I believe, so should be out in the next release.
