### ISSUE TITLE
bug: The debounced keyboard event handlers should be invoked on trailing edge of the timeout

### ISSUE THREAD

**Issue by cpylua** [driftyco/ionic#3633]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Some 3rd party IMEs(e.g. Sogou Keyboard) on iOS will trigger multiple `native.keyboardshow`  events when opening keyboard. These events have increasing `keyboardHeight` value, it causes keyboard covering input boxes because of incorrect keyboard height used by Ionic. 

We should invoke the event handlers on the trailing edge of the timeout, I think this is the correct behaviour.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @cpylua!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3633). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3633)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment]
Hello! Are you still having this issue with the latest version of ionic 1? (1.3.0)

**Comment by cpylua** [comment]
I'm sorry, but I haven't worked on the Ionic project for nearly ten months now. You may close the issue if no one else is having the issue now.

**Comment by jgw96** [comment]
@cpylua No problem! Im gonna close this for now.
