### ISSUE TITLE
bug: Error runing ionic build for crosswalk 

### ISSUE THREAD

**Issue by jacargentina** [driftyco/ionic#3635]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I've added crosswalk browser to my project, and when i try to build i get this.

````
ionic build
running cordova build
Running command: /home/my_user/javascript/mobile-ionic/hooks/after_prepare/010_add_platform_class.js /home/my_user/javascript/mobile-ionic
Running command: /home/my_user/javascript/mobile-ionic/platforms/android/cordova/build 
ANDROID_HOME=/opt/android-sdk-linux
JAVA_HOME=/usr/java/jdk1.8.0_05/
Running: /home/my_user/javascript/mobile-ionic/platforms/android/gradlew cdvBuildDebug -b /home/my_user/javascript/mobile-ionic/platforms/android/build.gradle -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* What went wrong:
Could not dispatch a message to the daemon.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

/home/my_user/javascript/mobile-ionic/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /home/my_user/javascript/mobile-ionic/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/my_user/javascript/mobile-ionic/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /home/my_user/javascript/mobile-ionic/platforms/android/cordova/build: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: /home/my_user/javascript/mobile-ionic/platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
````

**But**, if i do 

    cordova build android

it first downloaded all the "gradle" things, and everything builds just fine.

Maybe its something about "paths" when running from inside **ionic build** ?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jacargentina!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3635). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3635)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Stiveknx** [comment]
Try with the last version of ionic-cli, for me it works fine.
Also, removing crosswalk and crosswalk plugin, then adding it again may solve the problem too (once it happened to me.

Also you my try to report this issue to:
https://github.com/driftyco/ionic-cli

Since it's more specific to the cli ...

**Comment by jacargentina** [comment]
@Stiveknx I 've tried updating ionic-cli to latest (CLI v1.3.21) and then:

    ionic browser rm crosswalk
    ionic browser add crosswalk
    ionic build

I get the very same error. Also i dont understand the part you wrote "crosswalk plugin". May be there is something missing on my "delete and reinstall crosswalk" sequence?

**Comment by jacargentina** [comment]
More info about this: It is somehow related to IPv6/IPv4. I've found the error from gradle when it doesnt work (running **ionic build**):

    09:38:30.718 [ERROR] [org.gradle.messaging.remote.internal.inet.TcpIncomingConnector] Cannot accept connection from remote address /192.168.1.5.

But launching with cordova (running **cordova build**):

    09:42:22.620 [DEBUG] [org.gradle.messaging.remote.internal.inet.TcpIncomingConnector] Accepted connection from /0:0:0:0:0:0:0:1:46102 to /0:0:0:0:0:0:0:1:55250.

So, when running from ionic, it tries to connect to gradle via IPv4, but when doing via plain cordova, somehow it uses an IPv6.... Any advice?

**Comment by perrygovier** [comment]
I'm going to hand this off to the CLI Repo

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#431
