### ISSUE TITLE
bug: Application elements are not properly aragned if Device Font is changed

### ISSUE THREAD

**Issue by vlados** [driftyco/ionic#3637]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>If you change the device font size (Android 5.0.2 > System Settings > Personalize > Font size) the application is making every element with the coresponding font size but it's not changing the position of the element. I am attaching screen shots

![1](https://cloud.githubusercontent.com/assets/46914/7372174/0c5b1572-edce-11e4-9ccd-853f41a06f1c.png)
![2](https://cloud.githubusercontent.com/assets/46914/7372175/0c74790e-edce-11e4-90ad-e1670c8a18f0.png)

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vlados!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3637). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3637)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Are you see this if the app current runs in the background? 
I wasn't able to replicate this with android 5.1.

**Comment by vlados** [comment]
What you mean?

**Comment by mhartington** [comment]
See here.

https://youtu.be/pLyNRgK3ioY

When I change the system font size, the forces a whole app refresh.

**Comment by Ionitron** [comment]
Greetings @vlados!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @vlados!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
