### ISSUE TITLE
bug: crosswalk build: black and white screens shown for few seconds after splash screen and before ionic app is shown

### ISSUE THREAD

**Issue by bymodude** [driftyco/ionic#3638]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Crosswalk Android Build: Black and white screens are shown each for about 1-2 seconds after the splash screen image and before the actual ionic app is showing. The user experience is hence not optimal. 

So to clarify: user clicks icon -> ionic splash screen image is shown instantly and remains for about 2 or 3 seconds -> now first a black page is shown for about 1-2 seoncds -> now a white page is shown for 1-2 seconds -> finally ionic app is shown. 

I would like to just show the splash screen for the whole duration and get rid of the black/white screens if possible. 

Could it possibly be controlled using these crosswalk options: https://crosswalk-project.org/documentation/manifest/launch_screen.html

But I don't know where to add this in an Ionic project, I tried adding manifest.json to the www root of the ionic app, but its not being picked up by the crosswalk webview it seems</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @bymodude!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3638). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3638)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#408
