### ISSUE TITLE
feat: Windows Phone - Disable Shade on Click

### ISSUE THREAD

**Issue by baltazaroliveira** [driftyco/ionic#3641]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Windows Phone 8

Can you add in next versions this meta in Windows Phone to disable shade on click.

 `<meta name="msapplication-tap-highlight" content="no" />`
Thanks</span>

<span is-issue-template></span>

**Comment by jbollacke** [comment]
I think there's something missing in this issue.

**Comment by baltazaroliveira** [comment]
Sorry. Yes.

**Comment by Ionitron** [comment]
Greetings @baltazaroliveira!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
