### ISSUE TITLE
bug: Windows Phone - IonList lost position

### ISSUE THREAD

**Issue by baltazaroliveira** [driftyco/ionic#3643]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>When this issue will be resolved?

Thanks
Baltazar

'Ion-list on Windows Phone

If you tested the starter tab example app from the ionic team on your Windows Phone, you may have noticed some strange behaviour when you click on an ion-list item. Go back to the list and click on the same item again. You'll notice that the view doesn't change but when you click on an other item the view does change.

When I asked the ionic team about this issue they said "You'll just have to wait" because they currently don't support Windows Phone. But they promised to do this as soon as possible'</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @baltazaroliveira!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
