### ISSUE TITLE
feat: allow highlighting of ion-item

### ISSUE THREAD

**Issue by awebdeveloper** [driftyco/ionic#3644]
Allow functionality of ui-sref-active="current" on ion-item

**Comment by Ionitron** [comment]
Greetings @awebdeveloper!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3644). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3644)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Stiveknx** [comment]
If can write your own logic to "activated" the item ..
Just add the class: activated to item.

Example:
``
<ion-item ng-repeat="item in itens" ng-class="{'activated': (item.current)}"> </ion-tem>
``

**Comment by mhartington** [comment]
This is already possible.

http://codepen.io/mhartington/pen/YXyZKR

**Comment by awebdeveloper** [comment]
Thanks. This is missing in docs. Plz update it.
