### ISSUE TITLE
bug: Blob urls for images in 1.0.0-rc5

### ISSUE THREAD

**Issue by hasandogu** [driftyco/ionic#3645]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Just updated to 1.0.0-rc5 and it seems like "blob" urls in images were removed in order to be able to provide add support for Windows Phone due to this blog post

    // Fix for URLs in Cordova apps on Windows Phone
    // http://blogs.msdn.com/b/msdn_answers/archive/2015/02/10/running-cordova-apps-on-windows-and-windows-phone-8-1-using-ionic-angularjs-and-other-frameworks.aspx
    .config(['$compileProvider', function($compileProvider) {
      $compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|ftp|mailto|file|ghttps?|ms-appx|x-wmapp0):/);
      $compileProvider.imgSrcSanitizationWhitelist(/^\s*(https?|ftp|file|ms-appx|x-wmapp0):|data:image\//);
    }]);

[Current Angular implementation](https://github.com/angular/angular.js/blob/master/src/ng/sanitizeUri.js) is allowing "blob" urls for images and Ripple is depending on these when using the camera plugin. Is there a particular reason for why "blob" was removed?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @hasandogu!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3645). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3645)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Thanks @hasandogu, great catch
