### ISSUE TITLE
bug:  1.0.0-rc5 break tel: link

### ISSUE THREAD

**Issue by henryavila** [driftyco/ionic#3647]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>When I update ionic to RC5 my `tel:` simply stop to work on mobile (tested on Android).
I checked my config.xml, its ok. roollbak the ionic to RC4 and it back to work. Updated again to RC5 and it stop to work again. For some reason this update just broke the `tel:` links.

My code is this

    <a class="button button-assertive" ng-if="item.phone" ng-href="tel:{{item.phone}}">
    <i class="icon ion-ios-telephone-outline light"></i>
    </a>

I'm using it for about four months without any problem. The problem came just when I updated the lib</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @henryavila!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3647). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3647)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jeanmatthieud** [comment]
I saw it too.

**Comment by joshbuchea** [comment]
Incase it's helpful for anyone, in an Ionic project with RC5 that I'm currently working on I use a function to call the tel link and that still works. 
````javascript
document.location.href = 'tel:' + phone;
````

**Comment by jeanmatthieud** [comment]
It would be great to add "geo:" links and all supported links with the new "cordova-plugin-whitelist"

**Comment by olach** [comment]
Thanks for this fix. But do you really need to also add "tel:" to imgSrcSanitizationWhitelist? "Tel:" is only used on links, not images. :)

**Comment by henryavila** [comment]
Angular make images linkable too. It can be uses on images

Em qua, 13 de mai de 2015 05:42, Ola Christensson <notifications@github.com>
escreveu:
