### ISSUE TITLE
bug: tab view change causes ion-side-menu-content automatic scroll to top with overflow-scroll activated

### ISSUE THREAD

**Issue by marcelscheuch** [driftyco/ionic#3653]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Platform: Desktop
Browser: Chrome / FF

I'm using a standard ion side menu with a nested ion-content object which has overflow-scroll activated. Every time I open a view in the tab bar it scrolls the scrollview in the side-menu-content element to the top.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @marcelscheuch!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3653). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3653)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Can you replicate this in a codepen

**Comment by Ionitron** [comment]
Greetings @marcelscheuch!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @marcelscheuch!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
