### ISSUE TITLE
bug: Forms in modals can modify underlying state forms

### ISSUE THREAD

**Issue by jasperkuperus** [driftyco/ionic#3656]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>
I have a state with a form in it, which opens a modal containing another form. Navigating through the modal form by pressing (shift +) tab suddenly makes the form of the underlying state accessible. In a simulator or on a device you can access these elements just by using the form controls:

![screen shot 2015-05-04 at 10 48 25](https://cloud.githubusercontent.com/assets/1655683/7450992/988f38bc-f24b-11e4-8841-e5027f785f6a.png)

You'll get a cursor in weird places, being able to type, see your cursor move, but don't see what and where you're typing:

![screen shot 2015-05-04 at 10 48 16](https://cloud.githubusercontent.com/assets/1655683/7450997/a97f48a6-f24b-11e4-99e7-24d812efbfe6.png)

If you have a look at what happens with a wider viewport, you'll see that you're editing elements in the form of the state below:

![screen shot 2015-05-04 at 10 38 54](https://cloud.githubusercontent.com/assets/1655683/7451006/ba0b6af6-f24b-11e4-80b6-44e4fd621d8c.png)

I've isolated this behaviour into a small jsfiddle. Although you won't see how a simulator responds in this fiddle, you can see the behaviour of the last screenshot if you make your viewport wide enough: http://jsfiddle.net/jasperkuperus/et1vz1sh/

**edit:** Updated fiddle to RC-5, same behaviour
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jasperkuperus!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3656). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3656)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Unfortunately, what DOM elements the keyboard accessory bar can navigate to is controlled by whether the element is `display:none` or not. In order to behave more like a native app, we advise developers to use the [Keyboard plugin to hide the accessory bar](https://github.com/driftyco/ionic-plugin-keyboard#keyboardhidekeyboardaccessorybar), and we do so by default in most of our starter projects for this very reason.

**Comment by jasperkuperus** [comment]
Ah, now I understand why you remove the accessory bar in the starter projects. Is it an idea to put this information in a small comment above the line that removes it in the starter projects? Perhaps referencing this or a similar issue? I never saw why it was necessary and thought the app worked perfectly without removing the accessory bar.
