### ISSUE TITLE
bug: SCSS: Hardcoded color in _items.scss

### ISSUE THREAD

**Issue by demianh** [driftyco/ionic#3659]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am using a dark theme using a custom _variables.scss file to compile my design. It works fine, but there is one change i had to make to the ionic source to make it work (and redo it every update):

There is a hardcoded color "white" in _items.scss:
https://github.com/driftyco/ionic/blob/master/scss/_items.scss#L204

Would be nice if that could be changed to a variable which can be configured in _variables.scss
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @demianh!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3659). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3659)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
You are correct. Good catch, thanks.

**Comment by perrygovier** [comment]
fixed in 5aaa94a461ded1b1dca874d9c2e1224db724d660
