### ISSUE TITLE
perf: ion-infinitive-scroll, unnecessary waste of cpu

### ISSUE THREAD

**Issue by huttarichard** [driftyco/ionic#3662]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi guys,

since you do really great job with ionic, I feel a need to report this, even if I don't have all "guidelines for contributing" stuff ...
 
from some reason, the svg spinner (used in ion-infinitive-scroll) in safari take about 20% of cpu of iPhone 6 (real device, android not tested)... If you actually do some ng / collection repeat and start scrolling you got 50%. 

Solution for this would be removing the spinner from DOM when its actually hidden.
https://github.com/driftyco/ionic/blob/master/js/angular/controller/infiniteScrollController.js#L35?

I used ionic vanilla rc5.
angular 1.3.15

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @huttarichard!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3662). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3662)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
I played with that but wasn't happy with the flicker that happens on older devices when adding it back in. In v2 we'll be dropping support for older Android and iOS devices and we can be more heavy handed in actually removing elements from the DOM instead of just hiding them. 

That's a crazy amount of processor time for a simple animation though... 
I believe #3554 more directly addresses that issue.  Lets continue the discussion there.
