### ISSUE TITLE
bug: delay between keyboard shown and scrolling to bottom

### ISSUE THREAD

**Issue by buunguyen** [driftyco/ionic#3664]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>In my app, I want the view to scroll to bottom when the keyboard is shown. That way, contents at the bottom of the screen are visible to users when the keyboard shows up. Up to Ionic RC3, I've been able to do this:

```js
window.addEventListener('native.keyboardshow', () => this.$ionicScrollDelegate.scrollBottom(false), false)
```

As the keyboard shows, the bottom contents immediately scroll into view and there's no flickering at all. But when I upgraded to RC4, there is a very noticeable delay between when the keyboard shows and the scrolling happens. The problem persists in RC5. I had to revert to RC3 since the flickering is very annoying. I can reliably reproduce the issue simply by doing a `bower install` between Ionic RC3 and RC4/5.

Can someone look at this?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @buunguyen!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3664). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3664)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tlancina** [comment]
Hey this appears to work fine for me in both RC2 and latest.  RC2 -> RC3 introduced some major keyboard changes, but I don't believe there was any change from RC3 to RC4 that would cause this behavior.  

If this is still an issue, could you post a minimal test case reproducing it?

**Comment by Ionitron** [comment]
Greetings @buunguyen!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
