### ISSUE TITLE
docs: Use English names for Node types

### ISSUE THREAD

**Issue by Zajn** [driftyco/ionic#3666]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In many places throughout the ionic codebase, integers are used to represent their respective `nodeType` (see the list of Node types on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType)). Examples of this can be found, for example, in the `navBackButton` directive:

```javascript
     for (var x = 0; x < tElement[0].childNodes.length; x++) {
        childNode = tElement[0].childNodes[x];
        if (childNode.nodeType === 1) {
          if (hasIconClass(childNode)) {
            hasIcon = true;
          } else if (childNode.classList.contains('default-title')) {
            hasButtonText = true;
          } else if (childNode.classList.contains('previous-title')) {
            hasPreviousTitle = true;
          }
        } else if (!hasInnerText && childNode.nodeType === 3) {
          hasInnerText = !!childNode.nodeValue.trim();
        }
      }
```
[Source](https://github.com/driftyco/ionic/blob/d684d62a2418a57db9fc9ce44520114243a2daa5/js/angular/directive/navBackButton.js#L83-L96)

Using the integer representation of the node type is confusing for anyone who does not know which integer represents which node type. I think it would be beneficial to use the English names, such as `Node.TEXT_NODE`, in place of the integers.

I am currently working on a PR to do just this.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Zajn!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3666). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3666)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Hey @Zajn,
You're right, english names would be easier to read. Hold off on the PR though. 
Thing is, that's part of the Ionic internals and not intended to be read.
