### ISSUE TITLE
bug: scroll creates white screen on scroll y

### ISSUE THREAD

**Issue by orona** [driftyco/ionic#3667]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>there are these functions: on ionic.bundle.js
function onDragX(e) {
          if (!sideMenuCtrl.isDraggableTarget(e)) return;

          if (getPrimaryScrollAxis(e) == 'x') {
            sideMenuCtrl._handleDrag(e);
            e.gesture.srcEvent.preventDefault();
          }
        }

        function onDragY(e) {
          if (getPrimaryScrollAxis(e) == 'x') {
            e.gesture.srcEvent.preventDefault();
          }
        }

it should be changed to "if (getPrimaryScrollAxis(e) == 'y') {" on the OnDragY function</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @orona!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3667). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3667)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Nope, that's to prevent other actions in the sidemenu, but still allow scrolling. Are you seeing a bug related to this area of code?

**Comment by orona** [comment]
actually yes, whenever it happens to get inside the statement:
e.gesture.srcEvent.preventDefault();
it shows white screen on the webview(the scroll is set to 0 on both x and y)

**Comment by perrygovier** [comment]
Odd, I'm not seeing this in a plain side menu app. Could you put this in a codepen?

**Comment by Ionitron** [comment]
Greetings @orona!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @orona!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
