### ISSUE TITLE
bug: bug: Back button Android doesn't work.

### ISSUE THREAD

**Issue by iRaul** [driftyco/ionic#3668]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span>

<span ionic-description>Hello there,

I have a problem with the back button on an Android device.
When I'm in a modal and hit the Android back button it should close the curent modal. But it doesn't.
It should work by default, right?
Or maybe there is a problem with Ionic View, maybe it doesn't render correctly.

What should I do?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @iRaul!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3668). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3668)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Well, lets start with a codepen so we're sure we're looking at the same thing. Next up, are you only seeing this in the view app or also when you put it on a device directly? What about through the web?

**Comment by mhartington** [comment]
@perrygovier just tested this out on a device and in the view app. It's an issue with the view app.

**Comment by Ionitron** [comment]
Greetings @iRaul!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
