### ISSUE TITLE
bug: Animations in collection repeat items.

### ISSUE THREAD

**Issue by voliva** [driftyco/ionic#3669]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>As stated in #2447, that was closed by @Ionitron when it wasn't yet fixed, there's a visually weird issue with animated stuff in the items in collection repeat.

Take for example checkboxes. As the same checkbox is reused when scrolling, if it was unchecked and in the new item attached should be checked, the user will see the animation from unchecked to checked, and viceversa.
Here is an example: http://plnkr.co/edit/ik2pPYA4qusjpe3cNAmJ?p=preview

In the old issue report I suggested adding a class when the item is changing the scope, so we can disable the CSS animation, but now I can't find where is the scope attached....

Also, for the next time... How can I reopen an issue closed by Ionitron? I asked via twitter, then via forum without any luck ;P
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @voliva!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3669). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3669)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by voliva** [comment]
Gotta hate @Ionitron....

**Comment by perrygovier** [comment]
Adding a class would work in this case, but I believe it's too specific of a situation to slow down `collection-repeat` with extra DOM hits for everyone. If there's a larger demand for it, I'd consider adding in an optional parameter. 

A different approach would be to simply increase the buffer so the transition is over before the user can possibly scroll to the item. Here's an example
http://plnkr.co/edit/LfFaMeB1lGLLF7WR2dhQ?p=preview

**Comment by voliva** [comment]
That approach is not good enough... If you scroll fast enough you will always see those artifacts.
Plus, isn't adding 20 more elements in the DOM and changing the style attribute every time the user scrolls more expensive than adding and removing a class for the elements that go in the screen?

I get your point. Adding and removing a class will make the collection repeat slower for lists that don't need it, and as a workaround for now, i might just increase the number of elements.

**Comment by perrygovier** [comment]
Thanks for understanding. We have to draw a line of what to support and not support in collection-repeat and still maintain the performance benefits.  Unless we can think of a new/better approach, we have to mark this a "wontfix".
