### ISSUE TITLE
Deploying to iOS device stuck

### ISSUE THREAD

**Issue by freak4pc** [driftyco/ionic#3671]
Hey All. Newcomer here :) 

Ran `ionic run ios --device -l` a couple of times, in which it worked fine and deployed to my iPhone 6+. 

But now when I try it gets stuck here:
`[ 47%] Copying /Users/freak4pc/Work/tests/ionic/first/platforms/ios/build/device/first.app/www/plugins/com.ionic.keyboard/www/ to device
[ 47%] Copying /Users/freak4pc/Work/tests/ionic/first/platforms/ios/build/device/first.app/www/plugins/com.ionic.keyboard/www/keyboard.js to device
[ 47%] Copying /Users/freak4pc/Work/tests/ionic/(lldb) command source -s 1 '/tmp/fruitstrap-lldb-prep-cmds-cbfe9f42899c73e55d5f7800fa5636c54f4ae185'`

I've tried removing , rebuilding etc...
```
ionic platform remove ios
ionic platform add ios
ionic build ios
```

but that doesnt seem to do the trick. Not sure what I'm missing :)

Thanks!
Shai.

**Comment by Ionitron** [comment]
Greetings @freak4pc!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3671). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3671)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by freak4pc** [comment]
Nevermind, removing the app from the device and reconnecting fixed it. Thanks.
