### ISSUE TITLE
I have no idea how Git works haha

### ISSUE THREAD

**Issue by TheAwesomeGuy** [driftyco/ionic#3672]
Hey Kyle, I have no idea how Git works, so I will contact you like this.

I need help with your Twitter project, so do you mind helping me out please?

**Comment by Ionitron** [comment]
Greetings @TheAwesomeGuy!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3672). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3672)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
