### ISSUE TITLE
bug: Slidebox in a modal and container.offsetWidth

### ISSUE THREAD

**Issue by mellinas** [driftyco/ionic#3674]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>
Hi,

I post here an issue I got since this commit with a slidebox in a modal :
https://github.com/driftyco/ionic/commit/040dabf2

I used the new Ionic tool (congrats for play, it's very useful to submit issues :) ) to show rapidly the issue : http://play.ionic.io/app/e1935c0d427b

I try to directly slide to the second image at load and it doesn't work, we can see in the console : 'Cannot read property 'length' of undefined'

Because the modal container offsetWidth is undefined. Before the commit, it was working fine.

Any way to prevent that ?

Thanks</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mellinas!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3674). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3674)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Not 100% sure that that commit has to do with the issue, since dropping the version to rc-3 still produces it.
http://play.ionic.io/app/90e9a52df435

Also, removing the ion-modal-view did not remove the issue so I don't believe it has to do with that.

Seems to do with making sure the slidebox is ready to be interacted with.
http://play.ionic.io/app/078b2c71ef78

Another way would be to use the ionic view events.
http://codepen.io/mhartington/pen/EjVqze

**Comment by mellinas** [comment]
Yea, you are right, It's not working on rc3 in my example.

I put the complete example (except design) from my project : 

The use case : a grid of clickage images that open a modal viewer (like Facebook)

Here rc3 (works) : http://codepen.io/melina34/pen/QbyjBX

Here rc5(don't work) : http://codepen.io/melina34/pen/waMKxN

**Comment by perrygovier** [comment]
It's just a change of some things moving to be asyncronous and others opting to be syncronous when possible. Here's a new working version.
http://codepen.io/perrygovier/pen/yNeJxy?editors=101

Note, this is well beyond the intended use of the slidebox, so while it works, it'll be prone to breaking between versions and might one day not work at all.

**Comment by mellinas** [comment]
Thanks a lot for the new working version :)

Yea I understand it's a specific usecase. But I wanted to create something similar to Facebook gallery/modals and it was the component which seems the most close to it :)
