### ISSUE TITLE
bug: Slide box assigning to read only property not fixed

### ISSUE THREAD

**Issue by realityfilter** [driftyco/ionic#3675]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Please reopen #3589
See: https://github.com/driftyco/ionic/commit/08956b29b0ccf93203681a83f6ae6c5c9c28375f
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @realityfilter!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3675). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3675)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
thanks
