### ISSUE TITLE
[This is some thought about ionic, not bug] Will ionic support a Server---Client struct?

### ISSUE THREAD

**Issue by Alexniver** [driftyco/ionic#3676]
Hi all , I already use ionic build a app, but when I want update, users must download new apk and install. this is really annoying. Think about what a web app like, you do some change on server, then client auto get update, so convenient.

I want to know is there some way I can use ionic like a web app? I just do update things on server, then all my app user get new version app when they reopen app, never download apk.

**Comment by Ionitron** [comment]
Greetings @Alexniver!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3676). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3676)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Ionic can be served as a website today. Also, during development, you can get a live preview on device using `ionic run ios/android -l`. At that point, any device with the app loaded through that command and on the same network as the computer that ran the command will get automatic updates.

This is more of a forum discussion though.

**Comment by Alexniver** [comment]
Thank you very much for your reply and sorry to put this question here.
