### ISSUE TITLE
bug: How to make multiline form fixed to top with list

### ISSUE THREAD

**Issue by vlados** [driftyco/ionic#3677]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I cannot find a way to make ionic to have header, multiline subheader and ionic list to work together. How I can make it?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vlados!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
