### ISSUE TITLE
bug: The words in the select dropdowns are reversed

### ISSUE THREAD

**Issue by matlads** [driftyco/ionic#3678]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The words in options are reversed. For example, if you select "This is cool" (which shows up right in the pick list), the selected value is "cool is This"

The issue is mentioned in this forum post: http://forum.ionicframework.com/t/input-item-layout-issues/3171/3 and is demonstrated by this codepen: http://codepen.io/mhartington/pen/prwit

I fixed this by removing the
    `direction: rtl`
that is specified for class
`.item-select select`</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @matlads!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3678). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3678)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Is this still an issue with 1.0?

**Comment by matlads** [comment]
yes.

See this codepen: http://codepen.io/anon/pen/PqNXWx

**Comment by mhartington** [comment]
Unfortunately I"m not seeing this with the nightly builds.
http://codepen.io/mhartington/pen/XbgEbb

Can you confirm this has been fixed?

**Comment by matlads** [comment]
Still shows up in Firefox, fixed on chrome, and safari.

**Comment by mhartington** [comment]
It looks fine in safari and chrome. 
![screen shot 2015-06-23 at 10 24 56 am](https://cloud.githubusercontent.com/assets/2835826/8308370/500aa73e-1992-11e5-8e49-7b5f77b8e486.png)
![screen shot 2015-06-23 at 10 25 27 am](https://cloud.githubusercontent.com/assets/2835826/8308369/50070b7e-1992-11e5-86ee-21442b715529.png)

But not firefox, which we don't support.

**Comment by matlads** [comment]
Just tried it on a throw away app, and its fixed :)

**Comment by loomtronic** [comment]
I get this in Firefox still

**Comment by mhartington** [comment]
We're not supporting Firefox.
