### ISSUE TITLE
bug: Bug - InfiniteScroll broken in native scroll

### ISSUE THREAD

**Issue by melnikov77** [driftyco/ionic#3682]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>After updating to rc5 the InfiniteScroll get broken if is used in native scroll.
Here is error:
TypeError: Cannot read property '__container' of undefined
    at ionic.bundle.js:47148
    at ionic.bundle.js:24859
    at completeOutstandingRequest (ionic.bundle.js:13541)
    at ionic.bundle.js:13921

The problem is in the commit "fix(infiniteScroll): prevent checkbounds when infinitescroll completes when page is cached. Fixes #2694".

-      self.checkBounds();
+      // only check bounds again immediately if the page isn't cached (scroll el has height)
+      if (self.scrollView.__container && self.scrollView.__container.offsetHeight > 0) {
+        self.checkBounds();
+      }

In native scroll mode the scrollView is undefined.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @melnikov77!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3682). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3682)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Thanks!
