### ISSUE TITLE
docs: RFC3339 date and time in ionic

### ISSUE THREAD

**Issue by vadimk-design** [driftyco/ionic#3690]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>What is the best way to parse date and time like "2014-09-18T11:00:42" in ionic to "2014-09-18" and "11:00:42" separately?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vadimk-design!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3690). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3690)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Angular's docs cover this.

https://docs.angularjs.org/api/ng/filter/date
