### ISSUE TITLE
feat: vendor prefixe free

### ISSUE THREAD

**Issue by AliMD** [driftyco/ionic#3691]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>To continue of #3196
Could you accept pull request for it now ?
Clean css prefixes and use a gulp module for prefixing ? (my recommendation: gulp-autoprefixer)
Thank you in advance</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @AliMD!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3691). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3691)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
We wont be adding any autoprefixer to v1.  It'd add a step to the build process that we want to keep as simple as possible. For v2, we'll probably need to do device specific gulp builds, and it'd be a great feature to add in that case. We'd probably be open to a PR for that, but for v1, no, sorry.
