### ISSUE TITLE
feat: Angular 2 Migration

### ISSUE THREAD

**Issue by AliMD** [driftyco/ionic#3692]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Whats you plan for migrate to angular2 ?
Do you accept any contributing ?
Please define/public your road map and guild line to contributors.
Thank you in advance</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @AliMD!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3692). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3692)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Ionic with angular2 is currently in development/experimentation. Once we have things finalized and figured out, we will post code.
