### ISSUE TITLE
bug: Ionic serve should listen on all addresses on linux

### ISSUE THREAD

**Issue by MichaelBitard** [driftyco/ionic#3693]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When using ```ionic serve``` for the developments, It prompts for an interface selection: 

```bash
Multiple addresses available.
Please select which address to use by entering its number from the list below:
 1) 192.168.0.20 (wlan0)
 2) localhost
```

Why not listen by default on 0.0.0.0 so it will be available both locally and remotely?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @MichaelBitard!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3693). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3693)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#416

**Comment by perrygovier** [comment]
Moving this to the CLI repo
