### ISSUE TITLE
docs: Device Name

### ISSUE THREAD

**Issue by musician2000** [driftyco/ionic#3694]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi could you tell me if it is possible to get the mobile phone device name in Ionic? when I say device name I mean the name you call your device, when on android you go to device name in settings. 

I have read lots of articles trying device.name, device.model, installed plugins but no luck... just wondered if there was a limitation trying to get this .

Thanks
Chris</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @musician2000!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3694). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3694)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
This was removed by Cordova to better reflect inconsistencies across platforms. 
I'm not thrilled about it either. 

For iOS, this patch works well and is quick and clean to implement
http://stackoverflow.com/questions/26573944/how-to-get-ios-user-set-device-name-with-cordova
