### ISSUE TITLE
bug: ion-infinite-scroll throws error and stops responding

### ISSUE THREAD

**Issue by markharding** [driftyco/ionic#3697]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>The $parent.$apply function can cause '$rootScope.$digest in progress errors' on large pages. It is awkward to try and reproduce but wrapping the function inside a $timeout (ie. run in next digest) https://github.com/driftyco/ionic/blob/master/js/angular/controller/infiniteScrollController.js#L38 seems to prevent the issue from occurring. 

Steps to reproduce:
1) Set iOS data speed to 3G
2) Aggressively scroll and keep swiping up when spinner is loading. 
3) Error is thrown on occasions (possibly when memory is low?)

Unable to reproduce on android. 

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @markharding!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3697). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3697)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
We haven't seen this in our tests, can you share some code that reproduces this?

**Comment by markharding** [comment]
I'll try and create a test for it. It's tricky to replicate and requires poor connection and high memory overhead.

**Comment by perrygovier** [comment]
Thanks, I know it can be tricky but we can't fix what we can't see

**Comment by Ionitron** [comment]
Greetings @markharding!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @markharding!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
