### ISSUE TITLE
bug: Animations and other visual changes don't work properly when ion-content has attribute scroll="false"

### ISSUE THREAD

**Issue by eightfivezero** [driftyco/ionic#3700]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

I wanted to use the ionSpinner directive in a view that has the scroll="false" attribute set in the ion-content element. The animations are really jagged to the point that they're unusable and I had to revert back to not use scroll="false" in the ion-content directive. If anybody knows a solution to this minor grievance of mine that'd be amazing. Thanks!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @eightfivezero!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3700). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3700)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
They appear to work fine for me, could you share a codepen that reproduces the problem? 
http://codepen.io/perrygovier/pen/vOGYWJ

**Comment by eightfivezero** [comment]
Hi and thanks for reading! The problem only exists when building and running the app on iOS devices so it's a bit difficult to recreate the issue in a codepen.

**Comment by perrygovier** [comment]
You can start a project based on a codepen URL with `ionic start appName http://codepen.io/....` Even on a device I'm not seeing an issue with that codepen. A zip of a project works too, just need some way to reproduce it to fix it.

**Comment by Ionitron** [comment]
Greetings @eightfivezero!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
