### ISSUE TITLE
bug: Can create and build cordova but ionic troughs hooks error 

### ISSUE THREAD

**Issue by super-coder** [driftyco/ionic#3701]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>cordova build

Running command: C:\Windows\system32\node C:\_Learn\ionic\firstIonicApp\hooks\after_prepare\010_add_platform_class.js C:\_Learn\ionic\firstIonicApp
Error: Hook failed with error code ENOENT: C:\_Learn\ionic\firstIonicApp\hooks\after_prepare\010_add_platform_class.js

![1431395914399](https://cloud.githubusercontent.com/assets/2155554/7578884/42a82a50-f88e-11e4-90d5-9d407a5b669f.jpg)
![1431395947983](https://cloud.githubusercontent.com/assets/2155554/7578885/42acebd0-f88e-11e4-9c1c-c0f86cab2798.jpg)
![untitled](https://cloud.githubusercontent.com/assets/2155554/7578886/42b06170-f88e-11e4-89c2-7541b0942998.png)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @super-coder!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3701). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3701)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by super-coder** [comment]
if i rename after_prepare folder everything works. So looks like the problem is with 010_add_platform_class.js

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#417
