### ISSUE TITLE
bug: bug: $scope

### ISSUE THREAD

**Issue by iRaul** [driftyco/ionic#3702]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>browser</span>

<span ionic-description>**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi all,

I have the same problem,
I'm running into this issue with a ```form``` within a ```content``` within a view(modal).
I can't access the form from the ```$scope```.

What should I do?</span>

<span is-issue-template></span>
</span>

<span is-issue-template></span>
</span>

<span is-issue-template></span></span>

<span is-issue-template></span>
</span>

<span is-issue-template></span></span>

<span is-issue-template></span>
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @iRaul!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3702). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3702)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
