### ISSUE TITLE
bug: $scope issue

### ISSUE THREAD

**Issue by iRaul** [driftyco/ionic#3703]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi all,

I have the same problem,
I'm running into this issue with a ```form``` within a ```content``` within a view(modal).
I can't access the form from the ```$scope```.

What should I do?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @iRaul!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3703). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3703)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
The modal has its own scope. 
Here's an example of how to interact with it. If you check your console after creating a new user, you'll see that in `$scope.modal.scope.newUser` is the information entered in the modal.
http://codepen.io/perrygovier/pen/VLawKm?editors=101

"How do I" questions are better for the forum.

**Comment by iRaul** [comment]
Ok, so I added form and names to form and inputs.
Then I console.log it and get undefined.
http://codepen.io/anon/pen/jPqMrO?editors=101
