### ISSUE TITLE
bug: back button in Windows taking to pages back instead of one

### ISSUE THREAD

**Issue by AniketAman** [driftyco/ionic#3704]
**Type**: <span ionic-type>bug</span>

**Platform**:  <span ionic-platform>Windows Phone,</span>  <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>The default back button in Windows Phone takes two pages back instead of one. I tried adding a custom method by adding a ngClick event and then explicitly called $ionicHistory.goBack(-1) still it goes two pages back instead of one. Basically the method is getting called twice.. I am using the latest version of ionic  1.0.0-rc.5 "tungsten-turkey". Have tested in IE 11. The default back button of the browser works fine.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @AniketAman!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3704). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3704)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
I believe this is related to #2885. Lets solve that first and if the problem still exists, reopen this.
