### ISSUE TITLE
bug: ng-click not working within a label

### ISSUE THREAD

**Issue by mark-veenstra** [driftyco/ionic#3706]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>See next plunker that illustrates the issue: http://plnkr.co/edit/D9HD1AaTz2dIwRyfMUmP?p=preview

ng-click will not work when inside a <label> element, outside a <label> element it works perfectly</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mark-veenstra!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3706). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3706)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
This is part of Ionic's fastbuttons implementation, necessary for speedy ionic form directives. In your case, you'd want to use `data-tap-dsiabled="true"` like so:
http://plnkr.co/edit/9dqT2JUWv6RzzQlqvUzD?p=preview
