### ISSUE TITLE
bug: ionic-starter-slidemenu 404

### ISSUE THREAD

**Issue by heldrida** [driftyco/ionic#3707]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi,

I'm running ionic on windows (conEmu / Git Bash)

After running ionic start [APP NAME] slidemenu, I'm getting:

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================] 100% 0.0s

Downloading: https://github.com/driftyco/ionic-starter-slidemenu/archive/master.zip
✗ Not found: https://github.com/driftyco/ionic-starter-slidemenu/archive/master.zip (404)
✗ Please verify the url and try again.
✗ More info available at:
http://ionicframework.com/getting-started/
https://github.com/driftyco/ionic-cli</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @heldrida!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3707). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3707)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by heldrida** [comment]
sorry typo
