### ISSUE TITLE
bug: Cannot read property 'off' of null when navigating from leaflet-directive tabbed page

### ISSUE THREAD

**Issue by gdl276s** [driftyco/ionic#3710]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>This seems related to #2332, but was not fixed by it.

I'm using leaflet-directive, which I believe is using a scrolling view.  When navigating away from the tabbed screen, I'm getting ...

Cannot read property 'off' of null
    at ionic.bundle.js:48897

The below line seems to be the root cause:

scrollController.js
```javascript
$element.off('scroll', scrollFunc);
```
In my case, $element is null and should be surrounded by an if check ...
```javascript
if ($element) {
    $element.off('scroll', scrollFunc);
}
```
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @gdl276s!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3710). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3710)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Can you put together an example in codepen? I'm having difficulty understanding why leaflet you have any impact on Ionic's scroll controller.

**Comment by gdl276s** [comment]
working on it now

**Comment by gdl276s** [comment]
Looks like this was an issue created by leaflet-directive broadcasting a destroy event.  This issue is no longer happening in leaflet-directive version 0.7.15.  Closing ticket.
