### ISSUE TITLE
bug: Having a hidden subheader causes the main header to overlap the conten

### ISSUE THREAD

**Issue by ptarjan** [driftyco/ionic#3711]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In `headerFooterBarDirective` the `prelink` looks like:

```
        $scope.$watch(function() { return $element[0].className; }, function(value) {
          var isShown = value.indexOf('ng-hide') === -1;
          var isSubheader = value.indexOf('bar-subheader') !== -1;
          $scope.$hasHeader = isShown && !isSubheader;
          $scope.$hasSubheader = isShown && isSubheader;
        });
```

If you have two `<ion-header-bar>`s one with `class=bar-subheader`, but second one has `ng-show=false` this will get called twice. The first time `$hasHeader` is nicely `true` but the second time both `$hasHeader` and `$hasSubheader` will be false causing the content to be overlapped.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ptarjan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3711). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3711)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Thanks, could you demonstrate this in a codepen?

**Comment by ptarjan** [comment]
@perrygovier http://codepen.io/anon/pen/waGEVB

**Comment by perrygovier** [comment]
Great, thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#12
