### ISSUE TITLE
bug: Remote Audio File Not Playing

### ISSUE THREAD

**Issue by romaelz** [driftyco/ionic#3712]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

I'm trying to play a remote audio mp3 from server with the below code, the URL is fine and it displays full correct URL but when i read it {{item.filelocation}}, it doesn't play in the audio player and nothing happens when I click the play button. Even tried the data-tap-disabled="yes", but no joy.

Any help will be much appreciated.

Thanks
<ion-view view-title="Detail">
  <ion-content ng-controller="ListController" class="padding">
        
    <div ng-repeat="item in artists | filter: {id: whichprog }" class="item-text-wrap">
        <h4>{{item.title}}</h4>
        <p>{{item.studyintro}}</p>
        <p>{{item.filelocation}}</p>
   
        <div data-tap-disabled="true" >
        <audio controls autoplay="true">                                        
                <source src="{{item.filelocation}}" type="audio/mpeg">                                                        
        </audio>
        </div>
        
      </div>

  </ion-content>
</ion-view>

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @romaelz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3712). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3712)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Angular has to parse what `{{item.filelocation}}` means first. So my bet is that it first tries to play an audio file called `{{item.filelocation}}` and fails before the proper `src` is set. Inspect the element too, if you're getting the `item.filelocation` from an API, you'll have to explicitly trust the URL.

Could you put together an example in a codepen?  This looks like more of a question of how to do something in Angular than a bug in Ionic.

**Comment by Ionitron** [comment]
Greetings @romaelz!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
