### ISSUE TITLE
bug: bug: Found in iOS, ion content able to swipe/drag left side,  

### ISSUE THREAD

**Issue by basavakmatha** [driftyco/ionic#3718]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>![nav bar](https://cloud.githubusercontent.com/assets/12427625/7609330/8da1bac4-f98f-11e4-8e62-3ad5050981b6.PNG)
Able to drag/swipe the view (Swipe from left edge), attached image describes in details which is observed in iOS simulator and IPhone devices as well, the same issue was not found in android devices and chrome browser,
Issue found in: both 'tungsten turkey' and 'uranium-unicorn'</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @basavakmatha!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3718). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3718)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This is on purpose. 

http://blog.ionic.io/rc0-swipe-to-go-back/
