### ISSUE TITLE
feat: Windows Phone Support

### ISSUE THREAD

**Issue by NgYueHong** [driftyco/ionic#3720]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>It's great to see ionic version 1.0.0 is now officially released. May I know when will Windows Phone planned to be officially supported?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @NgYueHong!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3720). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3720)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
>Windows Phone support will be 100% when it reaches 100%

We’ll be expanding our Windows Phone support. There are a number of issues around tap/click/activator behavior, because Windows uses pointer events, instead of touch events. We’ll be setting up a complete Windows testing environment at Ionic HQ and working closely with some Microsoft team members to address Windows Phone issues more directly.

So no date is set in stone. When its done, it will be done.
