### ISSUE TITLE
ionic resources does NOT update old icon

### ISSUE THREAD

**Issue by sclearion** [driftyco/ionic#3723]
ionic resources does not work as documented. It keeps loading from "cache". how can i remove this stupid caching as it is driving the graphic designers crazy. I have followed docs to a T and the only way I can update the icon is by removing android platform and re-installing.

**Comment by Ionitron** [comment]
Greetings @sclearion!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3723). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3723)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by cesarvega** [comment]
I think this issue was not posted by me

On Wed, May 13, 2015 at 4:30 PM, Ionitron <notifications@github.com> wrote:

> Greetings @sclearion <https://github.com/sclearion>!
>
> My sensors indicate that you need to update your issue through our custom
> issue form <http://ionicframework.com/submit-issue/#/?iid=3723>. We are
> now requiring all issues to be submitted this way, to ensure that we have
> all of the information necessary to fix them as quickly as possible.
>
> *Click Here To Update Your Issue
> <http://ionicframework.com/submit-issue/#/?iid=3723>*
>
> I will have no choice but to close this issue if it is not resubmitted
> through the form. Please fill out the rest of the form, so that I may use
> my friendly robot powers to assist you.
>
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic/issues/3723#issuecomment-101806195>.
>



-- 
Cesar Vega

Software Engineer

Where Great Brands Begin®

<http://www.brandinstitute.com/images/logo.jpg>
<http://www.brandinstitute.com/images/logo.jpg>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#420
