### ISSUE TITLE
bug: Incorrect tab icon placement in internet explorer

### ISSUE THREAD

**Issue by Jarek300** [driftyco/ionic#3725]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Please load Ionic Codepen example http://codepen.io/ionic/pen/odqCz. Tab icons look correctly only if the browser window is narrow. If you make the browser window wide enough the first and second icon are pulled right and the third icon 'Contact' disappears. </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Jarek300!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3725). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3725)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @Jarek300!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by Jarek300** [comment]
Icons still look incorrectly. I'm afraid that closing and reopening the issue will not fix it no matter how many times we do it.

**Comment by mhartington** [comment]
Right now we're not focusing on IE.
