### ISSUE TITLE
feat: Support to ng-include in collection-repeat

### ISSUE THREAD

**Issue by danicomas** [driftyco/ionic#3726]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>See the forum for more information: http://forum.ionicframework.com/t/collection-repeat-and-ng-include/8635</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @danicomas!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3726). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3726)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by danicomas** [comment]
More information I haven't tried it:
http://www.bennadel.com/blog/2740-replacing-nginclude-with-component-directives-in-angularjs.htm

http://www.bennadel.com/blog/2738-using-ngrepeat-with-nginclude-hurts-performance-in-angularjs.htm

**Comment by danicomas** [comment]
More information I haven't tried it:
http://www.bennadel.com/blog/2740-replacing-nginclude-with-component-directives-in-angularjs.htm

http://www.bennadel.com/blog/2738-using-ngrepeat-with-nginclude-hurts-performance-in-angularjs.htm

**Comment by danicomas** [comment]
I let open this issue because I want to know what you think about it.

**Comment by perrygovier** [comment]
There's a few things in collection-repeat that _should_ work, but do not because of the way we optimize how elements are reused. 

This may qualify as one of those cases. We certainly could add this support, but it'd come with an, albeit small, performance sacrifice for everyone who uses collection-repeat.  Since actually using ng-include on repeated elements kill performance in the first place, it's a bit counterintuitive to use them together. Either you care about snappy performance or you _really_ want to use ng-includes in a repeated element. 

If a lot of people ask for it, we'll consider it, but since we advise people not to do it, we wont go out of our way to support it unless there's a big demand. 

Thanks for brining it up though and for adding the extra research.

**Comment by danicomas** [comment]
OK @perrygovier Other question. In ng-repeat the elements are readjusted but in collection-repeat we need to create a height function to filled. Of course, this is a big problem. My first idea was to create a function measuring the text of each text inside repeater but I found a lot of problems to do a good algorythm. My second idea was to add ng-include in collection repeat and in height function calculate the template rendered and return its height. I don't want to use ng-repeat but I need to do it :S
