### ISSUE TITLE
bug: Hardware menu button detection stopped working

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic#3728]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>webview</span>

<span ionic-description>I used `document.addEventListener("menubutton", onMenuKeyDown, false);` to detect hardware menu button but now it's broken. I've also tried `$ionicPlatform.on("menubutton", onMenuKeyDown);`

```
OS: Windows 8.1
Node Version: v0.12.2
Cordova CLI: 5.0.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.0-beta.9
Ionic App Lib Version: 0.0.11
```
I'm using crosswalk 14
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @piernik!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3728). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3728)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
This is an upstream issue with Cordova. Related issues:

https://issues.apache.org/jira/browse/CB-8921

As soon as they fix it, it will automatically work in Ionic after updating the Cordova lib.

**Comment by piernik** [comment]
ok - thanks
