### ISSUE TITLE
bug: Enabling native scroll buggy on mobile browsers

### ISSUE THREAD

**Issue by GuyPie** [driftyco/ionic#3729]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Using version 1.0.0, enabling native scroll works fine when compiled to app on Android, but occasionally causes content to disappear on mobile browsers when clicking header to scroll to top of page. This happens more often on iOS 8 Safari than on Lollipop Chrome 42.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @GuyPie!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3729). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3729)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Native scrolling is not officially supported on iOS yet. Cordova on iOS is still forced to used UIWebView which doesn't fire the scroll events native scrolling functionality depends on. 

It's a big issue in the hybrid community, and we hope Apple resolves this soon because our hands are kind of tied until they do.
