### ISSUE TITLE
bug: Data size is increasing with crosswalk

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic#3730]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>webview</span>

<span ionic-description>I used `browser add crosswalk`. In my app I'm downloading many images and data over internet.
I can see that my app data is increasing when navigating - from 50 MB to 80 MB and probably more if I navigate more.
I think that crosswalk is caching recieved data. How to disable it?
Or maybe it's a bug?</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Wekbit is pretty bad about garbage collection when the inspector is open, but that's by design.  If you use device developer tools to watch the actual used ram instead of Chrome tools, is it still a problem? Also, modern Chrome tends to take take up more memory if a lot is available. Is it forcing other apps in to virtual memory? If the app looses focus, does it free up a lot of memory? It should be pretty difficult to actually get the app to the point of a memory warning or crash. 

I suspect it's Chrome trying to optimize performance or the inspector holding on to things. Does that fit with what you're seeing?

**Comment by piernik** [comment]
I'm not talking about memory. I mean storage data (on android home screen - menu button -> manage apps -> downloaded -> myApp -> storage -> data). It is growing and growing.

**Comment by piernik** [comment]
any ideas on this?

**Comment by berndartmueller** [comment]
I have the exact same problem with crosswalk and still looking for a solution! For more information see my forum post -> http://forum.ionicframework.com/t/increasing-memory-with-crosswalk-and-tinder-cards/22730

**Comment by perrygovier** [comment]
I don't believe @berndartmueller's issue is related. This is regarding disk usage, even when the app is closed. The tinder cards memory usage sounds like a memory leak to me.

**Comment by perrygovier** [comment]
@piernik, do you have any way of telling what's taking up the space? Do you see anything in local storage or application cache?

**Comment by piernik** [comment]
I'm not an android guru. I think that this is standard browser (chromium) cache.
Ex in details view I'm using `img ng-src` with url from my website. I suppose that this image is cached by chromium webview.
But I can be wrong. All I know for sure is that at beggining my app has eg 6MB storage data and after using app it has 15 MB

**Comment by perrygovier** [comment]
You can inspect Android apps the same way you would web pages in chrome when the phone is connected by going to `about:inspect` in your desktop's Chrome. 

Could you put together an example in Codepen.io? Note, you can create an app based on a codepen with something like: `ionic start myapp http://codepen.io/ionic/pen/odqCz`

**Comment by piernik** [comment]
I'm confused - only I have that problem? I thought that this is common issue.
I posted the same question at stackoverflow: http://stackoverflow.com/questions/30231485/disabling-caching-in-crosswalk and had some suggestion but I cannot put then in live because I'm green when it comes to java.
@perrygovier Have You installed such app (grabbing data on Internet with crosswalk)? If yes, please look at storage data - it should be increasing.

PS. Now my storage data is 21 MB :/

**Comment by berndartmueller** [comment]
I've put together a codepen demo -> http://codepen.io/anon/pen/RPrJaN

It simply downloads images but when built on android and crosswalk you can clearly see that the memory is increasing and not freed after app is closed.

**Comment by piernik** [comment]
@berndartmueller thanks for help.

**Comment by piernik** [comment]
@perrygovier Can You give us a hint? Is there a workaround? Or You will fix it? Any timeframe?

I have to say it's very important issue. Ionic app without crosswalk is 3-5 MB. With crosswalk it's 20-30 MB and it's is already very big. But with storage issue my app is now 50-80 MB - that's way too much for such app.

**Comment by piernik** [comment]
@perrygovier any news??

**Comment by Critical-Impact** [comment]
If you have the ability to create an ADB connection to your phone you could browse your application's data directory and see what is taking up all the space. 

Something like
adb shell
run-as yourappPackageName
cd /data/data/youappPackageName
ls -all

I have used this method in the past to check where files were being saved in my app.
That said, I have no idea what crosswalk would be saving into your app or where it would be saving it.

**Comment by tasosno1** [comment]
The Problem is Cache i.e images, Databases, Local storage etc goes in Data instead of  Cache. If you take a look on Android the Cache size is about 120k or so and Data increases to 100's of Megabytes and this is a big problem. 

Why was this overlooked and not  implemented is everyone's question.  

I would be happy if crosswalk had a setting to wipe out just the images or set a Max Cache size so the users don't find out eventually that the App has over 1Gig in data stored and get a heart attack.

I appreciate and like the Project but how comes all these new versions come out and the most important thing with this <strong>Data - Cache</strong> issue hasn't been fixed yet.

What exactly is the problem and why on android all Cache goes in Data?

**Comment by baleboy** [comment]
The Chrome/Crosswalk command line option --disk-cache-size should help you here. However it only works starting with Crosswalk 14.

To enable Crosswalk command line switches in the Crosswalk Cordova plugin: https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview#configure

**Comment by mhartington** [comment]
```
<preference name="xwalkCommandLine" value="--disable-cache-size=1024'" />
```

**Comment by zwacky** [comment]
I tested it, it's `<preference name="xwalkCommandLine" value="--disk-cache-size=1024'" />` (xwalk15)

also reference: http://peter.sh/experiments/chromium-command-line-switches/

**Comment by mhartington** [comment]
Thank @zwacky
