### ISSUE TITLE
feat: Add onReorderStart callback to ionReorderButton

### ISSUE THREAD

**Issue by adamduren** [driftyco/ionic#3731]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>**Summary:**
Adding an `onReorderStart()` callback would enable more advanced use cases when starting to reorder an `ionItem` in an `ionList`.

**Example use case:**

Imagine you have a list of tasks in which some tasks are dependent on another task while some tasks are independent. The user should be able to customize the ordering of the list with the exception that no task can be moved above it's dependent task. 

Currently I don't believe this functionality is possible.

My proposal is to add an`onReorderStart(item, itemList)` callback to the `ionReorderButton` directive. In the use case mentioned above the callback would check the item being dragged for tasks it is dependent on. If they exist then set a disabled attribute on it and all items above it to let the user know it cannot be dragged past a certain point.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @adamduren!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3731). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3731)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
I'm open to a PR that does this cleanly with unit and html tests, but it's beyond the scope of what we intend to built out ourselves. 

Where I'd start is add the method to listController (so it'd be on `ion-list` not individual items), and pass it in to the listView from there.  In listView.js, you could fire and respond to that method in `_startDrag`, currently on line 510.

**Comment by perrygovier** [comment]
Closing the issue since it's not something we intend to do, but seriously still open to the PR
