### ISSUE TITLE
bug: Potential DOM leak on floating labels

### ISSUE THREAD

**Issue by gvhuyssteen** [driftyco/ionic#3733]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>**Steps to recreate:**

**Step 1**: http://codepen.io/gvhuyssteen/pen/yNOqzZ
**Step 2**: Click on the input field (First Name)
**Step 3**: Type "test"
**Step 4**: Press backspace until the input field is empty
**Step 5**: Repeat 3 and 4

![screen shot 2015-05-14 at 5 03 01 pm](https://cloud.githubusercontent.com/assets/1265536/7634513/a86bd0b6-fa5b-11e4-8305-b64107b38b25.png)

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @gvhuyssteen!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3733). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3733)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by gvhuyssteen** [comment]
Maybe this is not even an Ionic issue.

I added a single blank textfield to an empty html page and ran the same tests as mentioned above.

I get the same DOM leak as a result.

Could someone comment on this issue please, I am a bit confused around this whole issue.

**Comment by perrygovier** [comment]
Chrome inspector itself can be a bit leaky itself that way. I ran a script to automate entering and exiting focus and typing a few hundred times and I don't see any memory change on actual devices. A better test is to compare heap snapshots when in Chomre's icognito mode (to prevent leaky chrome plugins from messing with the test).

This is all the code around the input, so afaik it'd be impossible for this to cause a leak unless webkit itself was leaky. 
```js
      var onInput = function() {
        if (input.value) {
          inputLabel.classList.add('has-input');
        } else {
          inputLabel.classList.remove('has-input');
        }
      };

      input.addEventListener('input', onInput);
```
I'm going to close this, believing it's a false positive, but let me know if you have more information to the contrary.
