### ISSUE TITLE
bug: App moves incorrectly when form field is focused (not using cordova)

### ISSUE THREAD

**Issue by javacado** [driftyco/ionic#3734]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>browser</span>

<span ionic-description>Pls see video for example (sorry about the dark box overlay). Video is taken from an iPhone emulator (via Browserstack)

When I click into a form field, and that field is lower than the center of the screen, the whole page jumps up and then scrolls down quickly - not far enough though - so that you cannot see the form field behind the keyboard. Additionally the page was zooming in (again the form field would dissapear behind the keyboard) - and then NOT zooming back out. For the time being I have disabled zooming or scaling in the meta viewport tag

I have seen other posts where they recommend the keyboard plugin for cordova. I am not using Cordova. This happens in iOS 8 and Windows, not andriod

This view is directly in safari, however the finished product will be in an application wrapper

Is there anyway to fix this when NOT using Cordova?

https://www.youtube.com/watch?v=KXhwCewI76I</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @javacado!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3734). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3734)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Hm, I don't think this is something we can at the moment. This isn't an issue with cordova because we can use the keyboard plugin and disable scrolling on the webview.  

@tlancina, care to chime in?

**Comment by javacado** [comment]
Thanks for answering. What is happening? Is it an Ionic feature, or a safari behavior? I need some clue as to why it's happening so I can work around it.

**Comment by mhartington** [comment]
Its a mixture of native and ionic. You could try to disable js scrolling and just use the navtive-overflow scroll

**Comment by javacado** [comment]
I tried this code but didn't notice any change:

.config(['$ionicConfigProvider',
function appConfig($ionicConfigProvider) {
       $ionicConfigProvider.scrolling.jsScrolling(false);

...

Is there a different/better way to disable js scrolling?
I am also concerned that disabling js scrolling will compromise the UX in other views. Is it hindering me that I am not using cordova?

I am really enjoying Ionic but this kind of behavior is making me consider using a different UI - I would rather get an elegant solution for this first.

**Comment by perrygovier** [comment]
You can disable scrolling per page using `overflow-scroll="true"` on the `ion-content`. Native scrolling on iOS breaks some things like pull to refresh and infinite scrolling because iOS in Cordova doesn't fire real native scrolling events. 

On pages without those features, it should work fine. With native scrolling enabled, what you see regarding how form fields focus when not in Cordova is the native webkit behavior, so any other framework would have the same issue. 

It's not perfect, so we use the keyboard plugin to fix some issues inherent in webkit. In the browser, some people are forced to set `scrollTop` values on `ng-click`. It's a lot better than it used to be, but still not 100%. 

Does setting `overflow-scroll="true"` on `ion-content` help?

**Comment by javacado** [comment]
Thanks Perry. I added overflow-scroll="true" to <ion content>  and it didn't seem to make a difference. For a sanity check, I removed ionic and used a different bootstrap based ui, and after testing, it appears the scrolling issue vanished. When I click into a text field the page scrolls correctly. As much as I love the product (ionic), this was a deal killer for me. I suspect my inexperience is part of the problem...

**Comment by javacado** [comment]
Not giving up yet. I created a basic page with a form. All input elements worked as they should - when needed the page scrolled up to place the focused element aobve the keyboard (no overflow-scroll property needed). I then realized that this page didn't have the ionic view OR ionic content tags. I went back to my troubled form page and removed those 2 tags - the scrolling issue went away.

**Comment by javacado** [comment]
ok. So in the end I removed the ion-content directive from this one page. I will probably remove it from any page that has form elements (there are only a couple). It seems that (other than the form-field-focus issue being fixed)  the page acts the same (so far) without the ion-content tag.

I am happy that i can stay with ionic - but do you see any long term detriment from omitting that directive (ion-content) on select pages? I won' t be needing infinite scroll or refresher on those pages.

**Comment by javacado** [comment]
and again - THANK you IONIC team for producing a fantastic FREE product that is very useful.

**Comment by javacado** [comment]
More info. I came across the ionic.keyboard.disable() method in another git issue. I had tried that before but it didn't seem to work, and I think it's probably because I had an older version of ionic installed. I ran a bower update ionic and then tried this method on the problem pages - viola! There is a slight oddity in that clicking on a form element will move (not animate) the page to top, then scroll down, BUT the form element rests above the keyboard and I am a happy developer once more.

ISSUE FIXED.

**Comment by NeRo2pt0** [comment]
Were you able to use ion-content and found another way to solve this?

**Comment by javacado** [comment]
Yes, I am using ion-content. 
To be sure, I havent' actually tried it out in the native container. I am not using cordova and my app 
developer doesn't have the container ready yet. 

I might find out later that I actually didn't fix the issue once I get all the views integrated. However, testing in safari on the iphone went like this:
- initially the form-field focus was all over the place and not in view when editing the form field. 
- I removed ion-content to fix it
- that messed up other scrolling so I put it back
- then I added the ionic.keyboard.disable() method into the controller I use for my form view.
- that seemed to fix everything

Code is something like this:

.controller('myCtrl', 
    ['$scope', '$rootScope', 
    function($scope, $rootScope) {
          ionic.keyboard.disable();

...
