### ISSUE TITLE
bug: Second nested tab does not get selected when change URL

### ISSUE THREAD

**Issue by sanmaozhao** [driftyco/ionic#3739]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Please, look at this example: http://codepen.io/sanmao/pen/mJPgbX

Click first link(#/tab/home/first) on About tab, all fine.
Go back to About tab, click second link(#/tab/home/second), don't work.

But if you goto Home tab first, then click the link(#/tab/home/second), all fine too. </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @sanmaozhao!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3739). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3739)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Tabs within tabs approaches the boundaries of what we support with Ionic. We want to fix any errors, but this is acceptable behavior. 

That doesn't mean it's not possible though. Here's an example of how to achieve what you're looking to do.
http://codepen.io/perrygovier/pen/JdXgzp?editors=101
