### ISSUE TITLE
feat: Need to Create Same UI for both ios and android

### ISSUE THREAD

**Issue by sanmaozhao** [driftyco/ionic#3742]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Similar to this forum post( http://forum.ionicframework.com/t/need-to-create-same-ui-for-both-ios-and-android/20000 ) discussed, compliance the platform-specific interactive specification is good, but in some scenarios we need to build a unified interactive mode.
So I hope there are components for UI differences between platforms, can be configured through the $ionicConfigProvider, for example, change actionSheet style to iOS like:
```javascript
$ionicConfigProvider.actionSheet.style("standard");
```
Thanks!</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
This is something we're actively doing piece by piece as we update each component.  In v2, it will be the default for every component from the start. For v1, it's something many components already allow. Others can be tricked by setting the appropriate body class. 

I'm going to close this since it's a pretty broad issue that we're working on in several ways.
