### ISSUE TITLE
bug: Controllers are not firing in the starter ionic project 

### ISSUE THREAD

**Issue by super-coder** [driftyco/ionic#3744]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I found out that controllers are not actually firing in ionic project
How to reproduce: 
1) uninstall cordova and ionic, delete folders 
2) npm install cordova -g
3) npm install ionic -g
4) ionic start ExampleApp
5) cd ExampleApp
6) ionic serve 
7) add alert() inside controller

**Expected result:** alerts should show every time I change url to this controllers
**Actual result:** alerts are shown only first time. When swtched between controllers alerts are not shown, means controllers are not actually firing. 
I tested with Angular seed and alerts are firing every time

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @super-coder!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3744). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3744)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by super-coder** [comment]
http://joxi.ru/krD7vbkso3pXAp.jpg
http://joxi.ru/l2Z3wZYHGagxAJ.jpg
http://joxi.ru/ZrJEwbjfoNY9Aj.jpg

**Comment by ClemMakesApps** [comment]
I'm not a 100% sure on this but I think this could be an ionic feature - caching the controllers and view such that they do not have to be reloaded each time a tab is changed.

**Comment by super-coder** [comment]
yep http://ionicframework.com/docs/api/directive/ionNavView/
