### ISSUE TITLE
Bug: Ionic v1.0.0 : $ionicGoBack($event) throws an error

### ISSUE THREAD

**Issue by palkush** [driftyco/ionic#3748]
TypeError: Cannot read property 'viewId' of undefined
    at Object.goBack (vendors.js:52298)
    at Scope.$rootScope.$ionicGoBack (vendors.js:52535)
    at $parseFunctionCall (vendors.js:30250)
    at vendors.js:60979
    at Scope.$eval (vendors.js:32306)
    at Scope.$apply (vendors.js:32405)
    at HTMLButtonElement.listener (vendors.js:60978)
    at Object.triggerEvent [as trigger] (vendors.js:10017)
    at Object.tapGesture [as handler] (vendors.js:10913)
    at Object.detect (vendors.js:10595)

Code excerpt:

goBack: function(backCount) {
      if (isDefined(backCount) && backCount !== -1) {
        if (backCount > -1) return;

        var currentHistory = viewHistory.histories[this.currentHistoryId()];
        var newCursor = currentHistory.cursor + backCount + 1;
        if (newCursor < 1) {
          newCursor = 1;
        }

        currentHistory.cursor = newCursor;
-----> setNavViews(currentHistory.stack[newCursor].viewId);

        var cursor = newCursor - 1;
        var clearStateIds = [];
        var fwdView = getViewById(currentHistory.stack[cursor].forwardViewId);
        while (fwdView) {
          clearStateIds.push(fwdView.stateId || fwdView.viewId);
          cursor++;
          if (cursor >= currentHistory.stack.length) break;
          fwdView = getViewById(currentHistory.stack[cursor].forwardViewId);
        }

        var self = this;
        if (clearStateIds.length) {
          $timeout(function() {
            self.clearCache(clearStateIds);
          }, 600);
        }
      }

      viewHistory.backView && viewHistory.backView.go();
    },

**Comment by Ionitron** [comment]
Greetings @palkush!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3748). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3748)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Deminetix** [comment]
Are you calling $ionicGoBack from within your app? The param shouldn't be an $event anymore

**Comment by Ionitron** [comment]
Greetings @palkush!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
