### ISSUE TITLE
Template URL Slashes Breaking Router

### ISSUE THREAD

**Issue by cScarlson** [driftyco/ionic#3749]
Within child-modules, adding a beginning slash (/) will break $stateProvider's routing. Inside of /lists/lists.js (app depends on lists [ .module('app', ['ionic', 'app.controllers', 'lists']) ]) -- 

    .state('app.lists', {
        url: '/lists',
        views: {
            'menuContent@app': {
                templateUrl: 'lists/lists-view.html',
                controller: 'ListsController'
            }
        }
    })
-- works. However, for some reason -- 

    .state('app.lists', {
        url: '/lists',
        views: {
            'menuContent@app': {
                templateUrl: '/lists/lists-view.html',
                controller: 'ListsController'
            }
        }
    })
-- will break (notice the templateUrl begins with "/"). $stateProvider will keep bouncing the route to the $urlRouterProvider's otherwise.

This may cause a white screen if there is no other route to redirect to -- i.e: not hash-value is on the url.

**Comment by Ionitron** [comment]
Greetings @cScarlson!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3749). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3749)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @cScarlson!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
