### ISSUE TITLE
feat: remove a particular view from the history

### ISSUE THREAD

**Issue by Deminetix** [driftyco/ionic#3750]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Say i have traversed 3 views and i have a history that looks like this: `A -> B -> C` and i am now on `C`:

Is there currently a way that i can remove `B` completely from the history - including the cached elements and scope? This would mean going back goes to A

The `goBack([amount])` method works perfectly in some situations, but it doesn't work with iOS swipe to go back. A better solution would be a method to remove a specific item in the current history.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Deminetix!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3750). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3750)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Deminetix** [comment]
I added this method under `goBack` in $ionicHistory and it seems to be working perfectly, but would be good to get some feedback from the ionic team...

```js
/**
 * @ngdoc method
 * @name $ionicHistory#removeBackView
 * @description Remove the previous view from the history completely, including the 
 * cached element and scope (if they exist).
 */
removeBackView: function () {
  var self = this;
  var currentHistory = viewHistory.histories[this.currentHistoryId()];
  var currentCursor = currentHistory.cursor;

  var currentView = currentHistory.stack[currentCursor];
  var backView = currentHistory.stack[currentCursor - 1];
  var replacementView = currentHistory.stack[currentCursor - 2];

  // fail if we dont have enough views in the history
  if (!backView || !replacementView) {
    return;
  }

  // remove the old backView and the cached element/scope
  currentHistory.stack.splice(currentCursor - 1, 1);
  self.clearCache([backView.viewId]);
  // make the replacementView and currentView point to each other (bypass the old backView)
  currentView.backViewId = replacementView.viewId;
  currentView.index = currentView.index - 1;
  replacementView.forwardViewId = currentView.viewId;
  // update the cursor and set new backView
  viewHistory.backView = replacementView;
  currentHistory.currentCursor += -1;
},
```

**Comment by Deminetix** [comment]
Probably going to make this a bit more generic like `removeFromHistory(stateName)`

Eg: `removeFromHistory('app.main.createPost')` to remove any previous history entries and cached views with that state name.

Anybody interested?

**Comment by perrygovier** [comment]
I'd like to see a PR where you can remove previous states by state name and possibly also by ID. 

This is a very sensitive area though and would need lots of unit tests and a few HTML tests. If anyone wants to start a PR, I can get it up to snuff  so it's ready to be submitted to the core. 

Is there any more demand for this?

**Comment by Deminetix** [comment]
If you google "ionic location replace" and similar there are quite a lot of people having this issue. PR is coming tonight...

**Comment by Ionitron** [comment]
Greetings @Deminetix!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by pesimeao** [comment]
Hi,

I think this is related to #1287 and can be used to fix that problem instead of using any kind of "hack".

**Comment by MoPHL** [comment]
Has this been integrated in the core yet or are work-a-rounds still required?

**Comment by jakemulley** [comment]
@MoPHL Workarounds are still required, unfortunately.

**Comment by piotrowski** [comment]
Would be great if this would make it to core - playing around with these workarounds and there is always something broken :/

**Comment by jtomaszewski** [comment]
+1

**Comment by carlosjunior** [comment]
+1

**Comment by danicomas** [comment]
+1

**Comment by ChristopheDaVinci** [comment]
+1

**Comment by headchen** [comment]
+1

**Comment by fesor** [comment]
+1, this is very major problem.

**Comment by Rondeus** [comment]
+1

**Comment by jeremyross** [comment]
+1

**Comment by abeniwal** [comment]
+1

**Comment by lucasbeef** [comment]
+1

**Comment by alwayrun** [comment]
+1

**Comment by lucasbeef** [comment]
If you want to prevent the user to nav back to the last state you can always use $ionicHistory.goBack() before navigating to an other state.

Something like :
$ionicHistory.goBack();
$state.go('app.home');

It is not as flexible as being able to remove a particular page though, but in my case it was enough.

**Comment by MarioGallegos** [comment]
+1

**Comment by longsangstan** [comment]
+1

**Comment by t0mm13b** [comment]
+1

**Comment by rafaelcoutinho** [comment]
+1

**Comment by 05bca054** [comment]
+1

**Comment by agustinjlopez** [comment]
+1

**Comment by macno** [comment]
+1

**Comment by VinceOPS** [comment]
+1

**Comment by erikakinga** [comment]
+1

**Comment by flynt7111** [comment]
I think it is necessary.
+1

**Comment by hossam9995** [comment]
+1

**Comment by theambitious** [comment]
+2

**Comment by danbucholtz** [comment]
This will be a part of tonight's nightly build.  No further +1s needed 👍 

Thanks,
Dan

**Comment by MartinFreire** [comment]
I had the issue of deleting a portion of the backviews
e.g. I navigate to an application  and want to delete the history of the application, but not how I get there. 
So if I do A -> B -> C ->C1->C2->C1->C2->C3->C1->C4->C , I want the backview of "C" to be "B" (and of "B" to be "A") instead of C4.
So I found this post
https://calendee.com/2015/04/09/replacing-the-backview-in-ionic-framework/
And by my search of how to accomplish the goal, I came out with this code that so far works great. I hope it's usefull
```
function ReturnToState( state ){
	for( var viewObj in $ionicHistory.viewHistory().views )
		{
		if( $ionicHistory.viewHistory().views[viewObj].stateName == state ){
			console.log( 'Reverted to state: ', state , $ionicHistory.viewHistory().views[viewObj] );
			$ionicHistory.backView($ionicHistory.viewHistory().views[viewObj]);
		}
	}
};
```

**Comment by swaheed2** [comment]
Is this feature added ?

Can I do this?

My stack A->B->C

then I want to go to Z but not include it in the stack. 

From Z, I will go back to C on a button click. Z should be completely removed from history and I should be back to A->B->C.

**Comment by cjlucani** [comment]
Calling removeBackView() twice returns error:

`TypeError: Cannot set property 'backViewId' of undefined`

Ah, I think this line:

`currentHistory.currentCursor += -1;`

should be...

`currentHistory.cursor += -1;`

**Comment by stelioschar** [comment]
Have the same issue with @cjlucani, is there any update on this? did you find another proper way to solve this?

**Comment by loolooii** [comment]
Basically if we would have something like the `finish()` method in Android Activity, it would be perfect.

**Comment by guillermogfer** [comment]
I think I have a related issue because I need to remove a particular view from the history, specifically the forwardView.
My situation/navigation is this:
ion1 -> ion3 -> (stateParam A sent to the view) ion5 -> ion3 -> (stateParam B sent to the view) ion5 -> ion7 -> ion5, where I end with the previous ion5 view (with stateParam A) from the history.
I know that if I use a cached view on ion5 this problem doesn't appear, but I can't use cached view here for some other reasons.
What I want to do is to remove the forwardView (ion5) from the histories stack first time I go back to ion3, so a new ion5 (it will get other number, but for reference) view with the correct stateParam is saved in history.

Any thought about achieve that? The other workarounds commented here don't apply to this need because I don't want to remove any backView.

**Comment by spixy** [comment]
+1
