### ISSUE TITLE
bug: Issues on refresh input

### ISSUE THREAD

**Issue by meron1122** [driftyco/ionic#3752]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>View:
```html
<ion-view cache-view="false" view-title="Ustawienia" >
    <ion-content ng-controller="AccountCtrl">
        <div class="list">
            <label class="item item-input item-floating-label">
                <span class="input-label">Adres serwera</span>
                <input type="text" placeholder="Adres serwera">
            </label>
            <label class="item item-input item-floating-label">
                <span class="input-label">Klucz API</span>
                <input type="text" ng-model="apikey"  placeholder="Klucz API">
            </label>
        </div>
        <div class="padding">
            <button ng-click="scan()" class="button button-block button-energized">
                Skanuj Kod
            </button>
            <button class="button button-block button-positive">Zapisz</button>
        </div>
    </ion-content>
</ion-view>
```

Controller:
```javascript
.controller('AccountCtrl', function($scope) {
/*    $scope.settings = {
        enableFriends: true
    };*/
    $scope.apikey = '';
    //scan
    $scope.scan = function () {
        //$scope.apikey.value = "test";
        cordova.plugins.barcodeScanner.scan(
         function (result) {
             $scope.apikey= result.text;
             
         },
         function (error) {
             alert("Błąd podczas skanowania!");
         }
      );
    };
    console.log($scope.apikey);
});
```

Input value doesn't change after scanning.
If i change tab in menu input value change.
Any refresh problem or what?
I want after scanning change input value.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @meron1122!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3752). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3752)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
