### ISSUE TITLE
bug: Right padding incorrect in ion-item with button and ion-option-button

### ISSUE THREAD

**Issue by filimon-danopoulos** [driftyco/ionic#3753]
Type: bug

Platform: android 4.4 webview

The right padding of an `ion-item` is not correct  when an `ion-option-button` and a `button` are both included in the `ion-item`. The issue is demonstrated [here](http://codepen.io/anon/pen/RPRrQB?editors=101) (does not seem to work in firefox).

**Edit**: Added random stuff so that the issue might not be deleted.

**Comment by Ionitron** [comment]
Greetings @filimon-danopoulos!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3753). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3753)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by filimon-danopoulos** [comment]
Go ahead and close the issue, I will not connect my GitHub account to ionic under the currently required permissions.

**Comment by perrygovier** [comment]
ok

fwiw, the JS on the page isn't compressed and you can see that your GH info is never sent to us. We just use the form to format issues and attach meta data to help us organize them since we get _tons_ of issues by people who simply aren't building their apps right.

**Comment by filimon-danopoulos** [comment]
I did not mean to come across as rude, sorry if I did. I enjoy working with ionic and I think you are doing a great job.

I do not question your motives, it is a matter of principle. The issue at hand is that the required permissions are to broad (nothing you can do about it, since GitHub is configured that way).

What bothers me a bit is that I spend the time, reading the docs on GitHub about how to file bugs. Go through the effort of reproducing my issue. Try to formulate it correctly and get rejected by automation.
