### ISSUE TITLE
bug: Bug google maps plugin on ionic?

### ISSUE THREAD

**Issue by devtosystems** [driftyco/ionic#3755]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello guys!
I has a problema with google maps api with ionic app.

Please, look my app on github.
https://github.com/devtosystems/ionic-app-blank

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @devtosystems!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3755). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3755)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
So this project uses OpenStreetMap and it looks great! I would advise adding `detectRetina:true,` somewhere around  line 56 of `controllers.js` to get a nice retina display. Icons will need updating too. Otherwise I don't see an issue.  What's up?

**Comment by devtosystems** [comment]
Hi Perry, 
I do not run the app in my device Motorola Moto G - Lolipop 5.0.2.

**Comment by perrygovier** [comment]
I see. it works fine for me. Maybe try using crosswalk? Do you get any console errors?

**Comment by devtosystems** [comment]
See, after running on my phone, I do not get console errors because I performed with:

```
$ ionic run android --device
```

**Comment by perrygovier** [comment]
with the phone plugged in you can [debug in chrome](https://github.com/phonegap/phonegap/wiki/Debugging-in-PhoneGap#chrome-remote-debugging) by going to the URL `about:inspect` in the desktop browser. Does that help?

**Comment by devtosystems** [comment]
But in chrome is run perfectly.
The problem is in device android motorola g.

**Comment by devtosystems** [comment]
Oh thankyou perrygovier!!
Detected bug a access google url:

Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:24 Uncaught TypeError: Cannot read property 'Keyboard' of undefined

https://maps.googleapis.com/maps/api/js?sensor=true
or
file://maps.googleapis.com/maps/api/js?sensor=true

I do not understand.

**Comment by devtosystems** [comment]
Hi perrygovier, now is error in my device in key from Google Api key:

<script src='https://maps.googleapis.com/maps/api/js?v=3.exp&key=xxxxxxxxx&sensor=true'></script>

InvalidKeyOrUnauthorizedURLMapError: https://developers.google.com/maps/documentation/javascript/tutorial#api_key

**Comment by devtosystems** [comment]
Thanks, perrygovier, I resolved! o/
