### ISSUE TITLE
bug: $scope issue

### ISSUE THREAD

**Issue by iRaul** [driftyco/ionic#3760]
**Type**: <span ionic-type>bug</span>

<span ionic-description>@perrygovier 
Ok, so I added form and names to form and inputs.
Then I console.log it and get undefined.
http://codepen.io/anon/pen/jPqMrO?editors=101</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @iRaul!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3760). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3760)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
That's because it is undefined at that point. Setting the object in JS instead of just implicitly in HTML helps it persist in JS as that scope is loaded and transitions through different stages of activation. It's an Angular quirk. 
http://codepen.io/perrygovier/pen/zGBWag?editors=101

**Comment by deiucanta** [comment]
@perrygovier I just tested your solution and it doesn't solve the issue. The object is logged as an empty object. Then I tried using a timeout function to make sure it has time to initialize everything that it needs to, but no luck.

I think that the form is connected to some other scope. Do you have any clue where should I begin researching this?

P.S. I used ng-inspector extension and I saw that the actual form is in a deeper scope (made by ngTransclude)

**Comment by bodinaren** [comment]
Here's a working example: http://codepen.io/bodinaren/pen/eNdbpa?editors=101

**Comment by Ionitron** [comment]
Greetings @iRaul!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
