### ISSUE TITLE
feat: Double tap zoom on ion-scroll

### ISSUE THREAD

**Issue by Tomino2112** [driftyco/ionic#3762]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It would be great to add double tap zoom behavior to ion-scroll with zoom=true set.

Also, I ahve been asked to implement default zoom in our web app (where I used iscroll for scrolling and zooming). What it does, it zooms the content so it is all visible. 

Now some data:

Double tap zoom behavior: 
http://unitid.nl/androidpatterns/uap_pattern/double-tap-to-zoom

Initial zoom (my implementation - not perfect):

    // Zoom content to fit the viewport width
    var zoomWrap = document.getElementById('zoomWrap');
    var scroller = document.getElementById('scroller');

    if (scroller.offsetWidth > zoomWrap.offsetWidth){
        var zoom = zoomWrap.offsetWidth/scroller.offsetWidth;
        fullWidthZoom = zoom;
        myScroll.zoom(zoom);
    }

You can see the init zoom here: https://test.ipushpull.com/pages/#/domains/tomas_domain/pages/init_zoom_ionic (open on mobile)

Obviously both, double tap and autozoom, should be optional</span>

<span is-issue-template></span>
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Tomino2112!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3762). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3762)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
That functionality is baked in to the webview. We go to great length to disable that functionality so apps feel like apps instead of websites. If you want it back, just remove the meta tags and CSS that prevent it. The viewport is one part. I'd have to dig for a bit to find out what other actions prevent it. An app-wide `data-tap-disabled` might be necessary.

**Comment by Tomino2112** [comment]
Sorry i dont think i was clear enough.  What i described above is meant to be for ion-scroll directove,  not the whole app/webview. In my example i have normal app bit then there is table onside of the content that is rendered inside  extra ion-scroll.  So when you double tap at it,  tje whole app shouldnt zoom,  only the corresponding ion-scroll content should

**Comment by perrygovier** [comment]
Ah, gp. I don't think we'll be adding that to the core, but it'd make a great entry to our soon coming add-ons site.  What I'd like to see is one that works with JS and native scrolling.
