### ISSUE TITLE
bug: Getting a 401 Unauthorized Response for $http call during ionic run iOS

### ISSUE THREAD

**Issue by vincentdu101** [driftyco/ionic#3770]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi guys,

When I'm trying to make any $http call or external URL request in the code I get a 401 Unauthorized error as a response. I am currently running ionic run ios on my emulator and device and both show the same problem.

[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (Handshake, line 0)
http://localhost:8080/slc/Handshake?learnerId=f3f8b4f010e38602d839ece556d6dca4

I tried my IP address, but the same problem occurred. Additionally when I try to load an external file the same error occurs. I have currently allow access to localhost in my config.xml, but not sure if this plays a role in the problem.

<content src="index.html"/>
<access origin="http://localhost:8080"/>

Additionally, I also added to the $httpProvider headers to allow access, but again no progress was made. 

$httpProvider.defaults.useXDomain = true;
$httpProvider.defaults.withCredentials = true;
$httpProvider.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded; charset=UTF-8';
$httpProvider.defaults.headers.common['Access-Control-Allow-Origin'] = '*';
delete $httpProvider.defaults.headers.common['X-Requested-With'];

Any help would be wonderful, as I've looked through a number of forums, but I have not seen a similar issue. I am also on Ionic 1.4.3

Thank you again!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vincentdu101!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3770). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3770)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Note that Cordova uses the `file://` protocol so requests must include `http://` or `https://`.

If that doesn't work, could you share some code that reproduces the issue?

**Comment by Ionitron** [comment]
Greetings @vincentdu101!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
