### ISSUE TITLE
bug: ionic 1.0.0 model ion-modal-view does not work with back button

### ISSUE THREAD

**Issue by Poordeveloper** [driftyco/ionic#3771]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>webview</span>

<span ionic-description>After I upgraded to 1.0.0, the modal view does not hide after pressing back button (Android), instead the view which shows modal view goes back</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Poordeveloper!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3771). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3771)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
@mhartington, can you confirm this?

**Comment by mhartington** [comment]
Was not able to replicate this. 
I can close the modal with the hardware back button.
