### ISSUE TITLE
bug: $ionicView.enter not working 

### ISSUE THREAD

**Issue by rohitsahai** [driftyco/ionic#3772]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi Team , 
   I am trying to use $ionicView.enter in my application . But it seems the event is not getting fired up . As per the definition "This event will fire, whether it was the first load or a cached view.".
But it is not getting fired up 
Below is the code snippet :
	$scope.$on('$ionicView.enter', function () {
		                //Code
            });
My exact requirement is to refresh a view with latest data as soon as it is navigated to
Needs help to solve it .</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @rohitsahai!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3772). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3772)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Could you demonstrate this in a codepen?

**Comment by dakna** [comment]
I had a similar issue in my app. I had to make sure that the controller where the event should be picked up is defined like this:

- added to ui router state for this view
- in the view template defined on the ```<ion-view>``` element

I had a child node inside the view with a nested controller and it didn't receive any $ionicView events.

**Comment by Ionitron** [comment]
Greetings @rohitsahai!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by yu521088** [comment]
I am still have this problem, in some of my views, the $ionicView events fires, but in some of my view, they don't fire as expected, i am not sure why and can't find the way to reproduce the scenario.
