### ISSUE TITLE
bug: Install button not working on permissions screen

### ISSUE THREAD

**Issue by pratikm23** [driftyco/ionic#3776]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>1) There is no folder such as platform/android/bin found in my ionic project. 
2) I have the debug apks in the platforms/android/build/outputs/apk folder. 
3) I signed the apk using th instructions given on th site but the install button on the permission screen does not work. 

Please help me. Am i doing anything incorrectly?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @pratikm23!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3776). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3776)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
If you search your project, do you see any other `apk` files? Which instructions are you following?

**Comment by Ionitron** [comment]
Greetings @pratikm23!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
