### ISSUE TITLE
docs: App Store Rejected my app

### ISSUE THREAD

**Issue by irthos** [driftyco/ionic#3778]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm attempting to upload my app to the app-store. Repo is here: [https://github.com/irthos/rogo-app][1] and is live here: [https://irthos.github.io/rogo-app/][2]

The email from apple said they tried it on a iPhone 4s:

> May 17, 2015 at 4:06 PM From Apple
> 
>     2.1 - Apps that crash will be rejected
> 
> 2.1 Details
> 
> We were unable to review your app, as it crashed on launch on the
> following device(s):
> 
> - iPhone 5S running iOS 8.3
> 
> We have attached detailed crash logs to help troubleshoot this issue.

Finally, here's the ips log from Apple: [http://a1837.phobos.apple.com/us/r30/Purple7/v4/30/c5/04/30c50456-c2c0-1148-8d60-f36fbb11ae26/temp..jwnucdaf.ips?downloadKey3=1432258092_57a71add8c408ca7ec7a907881e7a613][3]

Thanks for any insight to this.

  [1]: https://github.com/irthos/rogo-app
  [2]: https://irthos.github.io/rogo-app/
  [3]: http://a1837.phobos.apple.com/us/r30/Purple7/v4/30/c5/04/30c50456-c2c0-1148-8d60-f36fbb11ae26/temp..jwnucdaf.ips?downloadKey3=1432258092_57a71add8c408ca7ec7a907881e7a613</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @irthos!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3778). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3778)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Are you by change using Cordova App Loader? Ionic apps by themselves with unmodified native code aren't capable of producing this error. Did you by chance edit your project's .xib file? You may want to remove/add the ios platform from your project and try again.

**Comment by irthos** [comment]
Apple let it thru on appeal. very odd to me. 

@perrygovier, thanks! as suggested, i made a fresh ionic install, copied over the /www dir, and ran ionic platform ios. then i noticed also had to update xcode, incidentally. 

all seems well now so i'll close this. feel free to open it up if worth further inquiry. thanks again!
