### ISSUE TITLE
Customize setTimeout delays

### ISSUE THREAD

**Issue by brauliobo** [driftyco/ionic#3779]
There are many different `setTimeout` delays used on `ionic.js`, for example: 80, 250, 40, 400, 500, etc.

All of these should be in a configuration hash for the app to change, and not hardcoded on the code.

**Comment by Ionitron** [comment]
Greetings @brauliobo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3779). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3779)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
These timeouts have been painstakingly chosen after testing a variety of apps on many different devices. I strongly advise against changing them. It may work on your phone, but there's a good chance it wont work on another. 

I'd like to see each setTimeout length declared in a common area component by component and document why they are what they are so it's easier to modify them as we change what platforms we support, but not one single place for the entire framework. We don't want to go out of our way to make it easier for people to break their app.

**Comment by brauliobo** [comment]
@perrygovier yeah, that's the problem, the way they are used now it is not clear nor documented why values were chosen. if it was clear, I would just move to a big hash of timeouts with each key documented.
