### ISSUE TITLE
bug: <ion-toggle> drag does not work with margins or an offset.

### ISSUE THREAD

**Issue by mike1e** [driftyco/ionic#3780]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

**Codepen**: <span>http://codepen.io/anon/pen/OVXeEj</span>

<span ionic-description>I'm trying to get the toggle buttons to slide on drag, and they work perfectly until I then put them in a container with an offset or with margins.

In order to get the slider to drag, you need to drag all the way to the left before it registers.

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mike1e!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3780). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3780)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by noopihc** [comment]
Experiencing the same issue.
Put toggles inside a multi column grid and dragging fails to register.

**Comment by asemoon** [comment]
Experiencing the same problem here.

**Comment by jgw96** [comment]
Hello! Are you all still experiencing this issue?

**Comment by mike1e** [comment]
Yes as of 1.2.4.

**Comment by olivermuc** [comment]
Same here even with v1.3.2
I've looked at the code and the offset calc is off, pun intended.
It can't calc the absolute .left position of the label element, which is the case in a popup shown on an tablet where widths/margins of the popup container shift the offset.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#13
