### ISSUE TITLE
300ms delay on sidemenu swipe?

### ISSUE THREAD

**Issue by brauliobo** [driftyco/ionic#3781]
I have to swipe quite slowly to make the sidemenu appear. So the question is, is there a 300ms delay on this drag? I'm testing on Android 2.3.

**Comment by Ionitron** [comment]
Greetings @brauliobo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3781). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3781)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Android 2.3 is no longer supported. There is no 300ms delay, but we require two touchmove events to determine gesture direction before we can know if the user is scrolling or opening the side menu, which happen pretty infrequently on 2.3.

**Comment by brauliobo** [comment]
@perrygovier but the strange thing is that with slider I can do very fast movements and it works. could you please indicate where in the code I can patch? I've tried without success.
cc @viniciuscb
