### ISSUE TITLE
feat: How to use ionic with reactjs and react-router

### ISSUE THREAD

**Issue by abhilashsajeev** [driftyco/ionic#3782]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi, I really like the design , But I am using react I want to use ion-nav-view in my reactjs application. How should I implement It?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @abhilashsajeev!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3782). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3782)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Ionic and React have fundamentally different approaches to structuring an app, managing the runtime, and manipulating the DOM. If you must use the two together, I'd suggest using iframes to completely separate the DOMs. 

You can try to get the two to play well together in the same DOM, but it's not pretty. At that point it'd be easier to recreate Ionic components as first class React components. Unfortunately, by the time you did that Angular 2 would be out, React would be focusing on React Native, and the point would be moot. 

Sorry there's not a better answer, but Angular and React are pretty incompatible for the time being.
