### ISSUE TITLE
bug: ion-content's on-scroll triggers with mouseup (without scrolling) on regular browser

### ISSUE THREAD

**Issue by jclalala** [driftyco/ionic#3785]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Please refer to plunker below. I'm using Chrome browser, Version 42.0.2311.60 beta (64-bit). Simply clicking on the list without scrolling will trigger on-scroll.

http://plnkr.co/edit/Rlu0p2ANISirHvHochJw?p=preview</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jclalala!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3785). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3785)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Right you are

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#14
