### ISSUE TITLE
bug: Can´t show a DetailPage

### ISSUE THREAD

**Issue by Domtaholic** [driftyco/ionic#3786]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi Community,

I have a ion-list with ng-hrefs="#/detail/:id"

I use the $stateProvider to handle the stateParams and show the detailPage for that item.

That works well on Android and Ios, on WP it won´t change to the Detailpage.

I tried with $routeProvider, same result.

Someone have any help here?

Would need help as fast as possible, the Customer waits for that Version - so a lot of pressure right now, but i´m not able to Fix this.

Domtaholic</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Domtaholic!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3786). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3786)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Could you demonstrate this in a codepen?

**Comment by Ionitron** [comment]
Greetings @Domtaholic!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
