### ISSUE TITLE
docs: Is It possible to edit introduction docs #bar-inputs

### ISSUE THREAD

**Issue by a9261** [driftyco/ionic#3788]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>According this chapter
http://ionicframework.com/docs/components/#bar-inputs
I use [header input] example in my ionic app . but when i try bind ng-click on the search icon
it can't be trigger . And i find the issue  commented 
https://github.com/driftyco/ionic/issues/2311#issuecomment-74161442
so i replace <label> to <div> let ng-click can work right  

i think the introduction docs  maybe can attach a note let user know this issue and how to fix it 
Thank you so much :)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @a9261!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3788). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3788)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Could you demonstrate this in a codepen? I think I can get this working for you.

**Comment by bodinaren** [comment]
@perrygovier: http://codepen.io/bodinaren/pen/vOXvym?editors=101
Clicking the ion-search inside the label (grey area) will not trigger the ng-click. The ion-search will.

**Comment by Ionitron** [comment]
Greetings @a9261!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
