### ISSUE TITLE
perf: Infinite Scroll janky when used inside a nested ion-nav-view

### ISSUE THREAD

**Issue by maverix** [driftyco/ionic#3796]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Anyone else encountered bad performance (high levels of jank) in the infinite scroller when used inside a nested ion-nav-view?

The issue resolved when I pulled the content outside of the named nested ion-nav-view.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @maverix!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3796). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3796)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
How is it nested? Could you demonstrate this in a codepen?

**Comment by maverix** [comment]
I narrowed it down further to just the presence of the ion-Nav-bar. If I
swap it for a ion-bar scrolling works as expected (nice and smooth).

I will get a repro together asap.

On Saturday, 23 May 2015, Perry Govier <notifications@github.com> wrote:

> How is it nested? Could you demonstrate this in a codepen?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic/issues/3796#issuecomment-104740832>.
>


-- 
This email has been sent to you...
I offer no guarantee that any attached documents are virus free – so at own
risk!

Love your guts!

**Comment by Ionitron** [comment]
Greetings @maverix!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
