### ISSUE TITLE
ng-file-upload with ionic file  dialog open twice

### ISSUE THREAD

**Issue by Jaware** [driftyco/ionic#3797]
http://embed.plnkr.co/xrQXOuFncBBA7c1R5t0W/preview

**Comment by Ionitron** [comment]
Greetings @Jaware!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3797). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3797)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Jaware** [comment]
it is ok on pc while both android and ios open file dialog twice,the first dialog can not work,only the second dialog can upload file

**Comment by Ionitron** [comment]
Greetings @Jaware!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
