### ISSUE TITLE
bug: Launch two modals, one after the other, the first modal doesn't close

### ISSUE THREAD

**Issue by EricDosReis** [driftyco/ionic#3802]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have tried launch a modal by another modal, but when I try close the last modal, the first modal doesn't close. Has a solution for it? Sorry by my english.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @EricDosReis!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3802). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3802)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by NeRo2pt0** [comment]
What's happening here is that you are losing your first modal reference after assigning your second modal reference.  If you have to launch another modal within a modal I would suggest assigning the second modal to a different $scope.modal variable instead of re-using that.  I assume that's what is going on.  Hard to say without any code.

**Comment by EricDosReis** [comment]
Yes, I know I'm losing modal reference. Thank you, but your solution does not fit in that case, I did a modal service and I need to find a way to make it dynamically.

**Comment by EricDosReis** [comment]
Okay, I solved my problem creating an array with modals in my modal service, and passing modal that I want to open and close as parameter.
