### ISSUE TITLE
docs: Sugestion to support streming protocols 

### ISSUE THREAD

**Issue by DiegoZurita** [driftyco/ionic#3803]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>In my current project, i am working in a streaming app, like spotify, but i not found any support to cordova or ionic, to support, for example to RTMP protocol or something like that, could you have any ideia how i fix it ?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @DiegoZurita!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3803). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3803)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Being a web technology, your best options is to use socket connections which Ionic already supports. 

If you want to do something more nuanced than that, you'll need to use a cordova plugin. Many exist. I'm not aware of a plugin that supports RTMP video or audio especially, but worst case scenario, you'd have to build your own. 

This is beyond the current scope of Ionic though, so any functionality would be through a plugin or addon.

**Comment by DiegoZurita** [comment]
Really thanks!
