### ISSUE TITLE
bug: ion-infinite-scroll stops free-scrolling when load operation finished

### ISSUE THREAD

**Issue by vgrafe** [driftyco/ionic#3805]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>All the data I want to display is already locally accessible, so the load operation is instantaneous. The problem is, when the user starts scrolling and lets the screen scroll like a free wheel, the scroll will stop as soon as the load operation completes.

Before you ask : 

* I use infiniteScroll to dilute the performance hit when loading a big list (30 items or more) with a few bindings on each item.
* Why not using collection-repeat will you ask? =) good question : simply because all the bindings mix up when scrolling fast with that directive. I still want to do more tests on this before opening an issue.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vgrafe!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3805). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3805)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
The break in scrolling is because the scrollable area must be resized and calculated. Rather than allow very janky scrolling, scrolling is stopped. It was a design call and we believe it's the better option.
