### ISSUE TITLE
bug: CLI doesn't set exit code properly

### ISSUE THREAD

**Issue by fahhem** [driftyco/ionic#3806]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If I have some invalid Android code and I run "ionic build", the exit code is set to 0 despite red build errors littering the screen. With it set to 0, I can't do something like this:

ionic build && notify-send Build worked || notify-send Build failed</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @fahhem!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3806). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3806)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#438

**Comment by perrygovier** [comment]
Moving to the CLI repo
