### ISSUE TITLE
bug: bug: Collection-repeat windows

### ISSUE THREAD

**Issue by CKGrafico** [driftyco/ionic#3808]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Not working on my App and when I check your example :S http://codepen.io/ionic/pen/0c2c35a34a8b18ad4d793fef0b081693 not workimg too.

Platforms: 
Internet Explorer 11
Windows phone 8.1</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @CKGrafico!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3808). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3808)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Does the fix described in #3399 help?

**Comment by CKGrafico** [comment]
Yes on my tests :)
