### ISSUE TITLE
bug: 'ionic upload' adds "ZERO WIDTH NO-BREAK"

### ISSUE THREAD

**Issue by tobbbe** [driftyco/ionic#3809]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When doing 'ionic upload' while 'ionic serve' is running a "ZERO WIDTH NO-BREAK"-character (&#65279) is added at the top of index.html. This causes the view to be to high</span>

<span is-issue-template></span>

**Comment by bodinaren** [comment]
I believe this would better fit in the Ionic CLI repo, no?
https://github.com/driftyco/ionic-cli/issues

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#439

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#440

**Comment by perrygovier** [comment]
Moved to the CLI repo

**Comment by Ionitron** [comment]
Greetings @tobbbe!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
