### ISSUE TITLE
feat: Ion Nav View should allow to specify which history stack to use

### ISSUE THREAD

**Issue by Tlvenn** [driftyco/ionic#3810]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Common use case is to let a nested view use the same history stack as its parent but I am guessing it would lead to other interesting behaviour as well.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Tlvenn!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3810). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3810)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
I'm pretty trepidatious about this. Nesting nav views is pretty buggy as is. Could you put together a demo and detail what you'd like to see. All the examples I can think of, should just be architected around.

**Comment by Tlvenn** [comment]
Hi @perrygovier ,

My grip with Ionic is that it is pretty opinionated about how history should work.

Having something like that out of the box is nice but the developper should ultimately be able to control its behaviour and right now, the only way is to work around it by not using ionic directive when you need a different history behaviour.

We should be able to guide directive that will create an history stack to either tell them to use their parent's one or a named one.

As for a simple use case, consider a main app page which can have 2 states. Each state is handled using a nested view so we can factor everything they have in common upstream. Those 2 sub view can link to new pages having a navigation bar with a back button.

Right now, because the nested view will have its own history stack by default with ionic, the back button will not show and there is no transition between the pages. I can force the transition but there is not much I can do about the history stack beside implementing a back button directive which would navigate the stacks and return back to where I want...

If I could tell the nested view to use its parent history stack, everything would work out of the box.

**Comment by Ionitron** [comment]
Greetings @Tlvenn!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
