### ISSUE TITLE
bug: `ionic run android` does not install the application on the device/emulator

### ISSUE THREAD

**Issue by keval5531** [driftyco/ionic#3813]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>2.x</span>  <span ionic-webview>webview</span>

<span ionic-description>I recently updated my CLI and it seems like the `ionic run android` command won't install the apk on my device. The build is successful, the CLI even tells that the apk was installed and launch was Successful, which is untrue; there is no apk installed. 
It requires me to install it manually using `adb install`. On my other machine I have `v1.3.16` of Ionic and there it turns out to be absolutely fine. I tested this on Android 2.3.3 phone as well as emulator with 4.3.

So is it to be done differently with the update? Or there's an issue with it?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @keval5531!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3813). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3813)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#441
