### ISSUE TITLE
bug: Layout glitches on Android on keyboard transitions

### ISSUE THREAD

**Issue by timuric** [driftyco/ionic#3814]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.x</span>  <span ionic-webview>webview</span>

<span ionic-description>Opening or closing keyboard on android produces visual glitches. However Ionic View app does not have such issue, thus it is seems to be solvable. My device is Nexus 4, Android 5.1. However I noticed similar behaviour on other devices.

Link to the video: http://d.pr/v/16ErH
Test app : http://d.pr/f/V56v</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @timuric!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3814). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3814)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @timuric!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
