### ISSUE TITLE
bug: White background shows when keyboard closes on Android

### ISSUE THREAD

**Issue by allenakinkunle** [driftyco/ionic#3817]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>I am testing my app on HTC One M8 running Android version 5.0.2. When an input field in the app loses focus, a white background is shown after the keyboard closes. The issue was recorded and the link is below:

http://imgur.com/ca2cNZv

My background image is set on .scroll-content so I don't understand why it acts like this on Android.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @superallen!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3817). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3817)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by amazaud** [comment]
Try to set your background image on the corresponding ion-view element instead, it should solve your problem.

**Comment by Ionitron** [comment]
Greetings @allenakinkunle!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
