### ISSUE TITLE
ionic 1.0.0-beta.6 spinner, popover does not function

### ISSUE THREAD

**Issue by dracula359** [driftyco/ionic#3818]
I have a serious problem in my Ionic project when I use the version 1.0.0-beta.6 the application works well but (spinner, popover) does not function and when I switch to version 1.0.0 (spinner, popover) works but I have a list when I selected an item the controller not charge

**Comment by Ionitron** [comment]
Greetings @dracula359!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3818). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3818)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @dracula359!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
