### ISSUE TITLE
feat: Dynamic load template and controller

### ISSUE THREAD

**Issue by echizen** [driftyco/ionic#3819]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>ionic load all template and controller after router config at once. While I need to make a big project, load all things at once will let it show slowly. I find angularAMD can figure out this problem base on angular and angular-ui-router, but when i use ionic.bundle.js, it only can load controller on demand , but load template all at once. Is this problem link to what ionic do to ion-nav-view?

How to load template on demand? that means when I click a <a> tag, it load the relative template and controller.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @echizen!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3819). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3819)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ewnd9** [comment]
+1

**Comment by Ionitron** [comment]
Greetings @echizen!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
