### ISSUE TITLE
bug: ionic cli1.4.5 don't work on iOS simulator and iOS device, but works on ionic view

### ISSUE THREAD

**Issue by Gabriel0402** [driftyco/ionic#3821]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm building an app with ionic. And I'm running ionic build on iOS and run the app on emulator and iOS device but both shows the white blank page. There's no errors and I cannot debug. And I upload it to ionic view and I can see my app in ionic view normally. And it works in browser, so it's not the problem of the program. Is there any security settings that I have to do with this version of ionic? Or I missed some steps? Or should I change the configure file?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Gabriel0402!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3821). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3821)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @Gabriel0402!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
