### ISSUE TITLE
bug: Collection-repeat  - Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by OSSDeveloper** [driftyco/ionic#3822]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi,
     Am using collection-repeat to iterate around 1800 records and am getting the maximum call stack reached error. Am pasting the HTML code here & attaching the screenshot below.

![screenshot-1](https://cloud.githubusercontent.com/assets/5099615/7787777/9cc3c0c4-023b-11e5-88ef-31ed223396d4.png)

![screenshot](https://cloud.githubusercontent.com/assets/5099615/7787771/4068925a-023b-11e5-8add-582c57f8c549.png)
 
</span>

<span is-issue-template></span>

NOTE: I tried to iterate only through collection-repeat by converting entire dataset into an array and, search filter was not working properly.

**Comment by Ionitron** [comment]
Greetings @OSSDeveloper!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3822). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3822)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by OSSDeveloper** [comment]
Hi,
      Problem solved. I converted entire dataset into array and applied custom filter. Its working fine now. Thanks.

**Comment by Ionitron** [comment]
Greetings @OSSDeveloper!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
