### ISSUE TITLE
bug: Font-families not loaded on iOs

### ISSUE THREAD

**Issue by ozgeek** [driftyco/ionic#3823]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>After testing an ionic based app, I noticed texts are not propertly showing on iOs plateform.
None of Open sans, or helvetica neue are loaded and the app, it is rendered with sans-serif font-family.
This makes typos look realy ugly on iOs, do you suggest any solution or a quick fix ?
Thanks</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ozgeek!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3823). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3823)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by sclearion** [comment]
having same issue. Developing 3 apps at the same time, however one app is not showing the google font import. Code bases are the same, just the UI is different. Really maddening

**Comment by Ionitron** [comment]
Greetings @ozgeek!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
