### ISSUE TITLE
bug: <ion-scroll> has-bouncing has disabled on iOS by default

### ISSUE THREAD

**Issue by veekungx** [driftyco/ionic#3824]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I used <ion-scroll> directive and test on iOS simulator (not on real device).

from documents.

> Whether to allow scrolling to bounce past the edges of the content. Defaults to true on iOS, false on Android.

but has-bouncing disabled on iOS by default.

sorry. for my bad english I tried to explain in simple.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @veekungx!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3824). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3824)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by veekungx** [comment]
Here my structure

    <ion-view>
        <ion-header-bar>
              ...
        </ion-header-bar>
        <ion-content scroll="false" class="padding has-tabs">
              <ion-slide>
                    ....
              <ion-slide>
             <ion-scroll scrollbar-y="false">  <----- HERE iOS has-bouncing has disabled by default
                    ....
             </ion-scroll>
        </ion-content>
        <div class="tabs">
               ...
        </div>
    </ion-view>

I still can enabled has-bouncing with directive's attribute but it affect on Android too.

**Comment by Ionitron** [comment]
Greetings @veekungx!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
