### ISSUE TITLE
docs: Can i add a header when i requesting an audio?

### ISSUE THREAD

**Issue by DiegoZurita** [driftyco/ionic#3826]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Supose that i have this HTML:
```
<audio controls>
  <source src="http://my.audio.repository/sameGreatAudio.mp3" >
  Your browser does not support the audio tag.
</audio>
```
When i request this audio, have a way to add a header like "X-Sec-Token:123456789" ?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @DiegoZurita!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3826). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3826)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This is not an issue with ionic, but should be asked on stackoverflow.
