### ISSUE TITLE
bug: Side Menu expose-aside-when on right Menu will not work

### ISSUE THREAD

**Issue by JanPeCol** [driftyco/ionic#3828]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>
If you provide a left and  a right slide-menu "expose-aside when" will not work for the right side.
It will always open the left-slide-menu. 

http://codepen.io/anon/pen/bdEEZw
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @JanPeCol!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3828). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3828)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @JanPeCol!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
