### ISSUE TITLE
bug: 'ionic upload' replaces single quotes in my index.html with &apos;

### ISSUE THREAD

**Issue by jorisw** [driftyco/ionic#3829]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

Everytime I do `ionic upload`, single quotes in my `index.html` file, particularly ones in a `value=""` attribute of a `<meta>` tag, get replaced with `&apos;`. I can see it happen live if I have my editor open and I do `ionic upload` in my Terminal.

Seems like a sanitizer doing overtime. Doesn't look right to me. Could be doing it in other files too, though I haven't noticed.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jorisw!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3829). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3829)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by devicezero** [comment]
same here :(

**Comment by Ionitron** [comment]
Greetings @jorisw!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by mediastuttgart** [comment]
hey,

still experiencing this issue

````
Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.1
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.3
ios-sim version: 5.0.4
OS: Mac OS X El Capitan
Node Version: v0.12.0
Xcode version: Xcode 7.1.1 Build version 7B1005
````
