### ISSUE TITLE
bug: ionlist items don't href or ui-sref when reorder is showing

### ISSUE THREAD

**Issue by MichaelJCole** [driftyco/ionic#3831]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi, I'm having trouble with my ionic list.  href and ui-sref don't fire when 'reorder' buttons are shown.  They do fire when 'delete' buttons are enabled, and when both are disabled.

It's natural for my list to be reordered often, so I'd like to switch between delete and reorder, with reorder as the default.  This doesn't work because the ui-sref's don't fire when reorder is active.

How to?  Thanks!

```
  <ion-content class="ion-subheader">

    <ion-list show-delete="showDelete"  show-reorder="!showDelete">
      <ion-item ng-repeat="(id, suggestion) in user.suggestions" 
        href="#/app/suggestion/{{id}}"
        class="">
        <ion-delete-button class="ion-minus-circled"
          ng-click="user.suggestions.splice($index, 1)">
        </ion-delete-button>
        <ion-reorder-button class="ion-navicon"
          on-reorder="moveItem(suggestion, $fromIndex, $toIndex)">
        </ion-reorder-button>

        <button
          class="button button-small button-positive"
          ng-click="play(suggestion)">
          <i class="icon ion-volume-medium"></i>
        </button>

        {{suggestion.title}}
      </ion-item>
```

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17 Qiana 
Node Version: v0.12.0
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @MichaelJCole!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3831). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3831)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @MichaelJCole!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
