### ISSUE TITLE
bug: Tabs dissapear with delay when keyboard is open ionic 1.0.0 

### ISSUE THREAD

**Issue by Yuripetusko** [driftyco/ionic#3832]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>When keyboard is open there's around 1second delay before tabs disappear. Initially they are attached to the top of keyboard. But if I set my app to Fullscreen mode, then tabs disappear much quicker.

Same issue with body.keyboard-open class. It is added with delay after keyboard is open</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Yuripetusko!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3832). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3832)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @Yuripetusko!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
