### ISSUE TITLE
bug: ionic run android no longer installs or runs the app

### ISSUE THREAD

**Issue by jorisw** [driftyco/ionic#3833]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi.

An `ionic run android` with my device connected, ends in:

```
BUILD SUCCESSFUL

Total time: 3.264 secs
Built the following apk(s):
    /Users/jorisw/Projects/myProject/my-app/platforms/android/build/outputs/apk/android-debug.apk
Using apk: /Users/jorisw/Projects/myProject/my-app/platforms/android/build/outputs/apk/android-debug.apk
Installing app on device...
Launching application...
LAUNCH SUCCESS
```

However, no app shows up on the phone, nor does it run. My wallpaper chooser opens instead.

If I then take the .apk file path and do:

`adb -d install /path/to/file.apk`, the app installs fine. It even connects to my Mac's console and livereload, if I launch it from the phone.

I suspect (but don't know for sure) that this issue popped up after the latest CLI release.

```
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:  
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.3
Xcode version: Xcode 6.3.2 Build version 6D2105 
Android version (on the phone): 4.1.1
```
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jorisw!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3833). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3833)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jorisw** [comment]
Another user on IRC just reported the same, also on an Android 4.1 phone.

**Comment by jorisw** [comment]
My emulator, running 4.4.2, does install and run the apk with an `ionic run android --emulator`.

**Comment by jorisw** [comment]
Sorry, this appears to be a dupe of https://github.com/driftyco/ionic-cli/issues/441 .
