### ISSUE TITLE
bug: Item tabs on card inside tabbed interface inherit styles from tabs interface

### ISSUE THREAD

**Issue by jonathancod** [driftyco/ionic#3836]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I put a codepen:
<p data-height="296" data-theme-id="0" data-slug-hash="jPVZRr" data-default-tab="result" data-user="jonathancod" class='codepen'>See the Pen <a href='http://codepen.io/jonathancod/pen/jPVZRr/'>Ionic Starter - Sidemenu and Tabs</a> by Jonathan Corredor (<a href='http://codepen.io/jonathancod'>@jonathancod</a>) on <a href='http://codepen.io'>CodePen</a>.</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

Steps:

- Click on sing in
- Click on tabs in the left menu.

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jonathancod!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3836). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3836)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @jonathancod!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by coachmedia** [comment]
Hi, 
I have this problem too these days. How to avoid inheriting tabs style from main tabs? maybe you should change style definition to something like this:

.tabs-color-royal > .tab-item

So that only first .tab-item children will adopt it.

**Comment by matuskopo** [comment]
Hi, 
I have this problem too these days. How to avoid inheriting tabs style from main tabs? maybe you should change style definition to something like this:

.tabs-color-royal > .tab-item

So that only first .tab-item children will adopt it.
