### ISSUE TITLE
popver drag issue.

### ISSUE THREAD

**Issue by xierenyuan** [driftyco/ionic#3838]
hi. I found that $ionicPopover  backdrop content as the drag to scroll.Don't know you please modify, let will not scroll the contents of after the Popover.
![image](https://cloud.githubusercontent.com/assets/7599351/7827118/c1cf0c40-0455-11e5-8a21-463a20c8301f.png)->
![image](https://cloud.githubusercontent.com/assets/7599351/7827121/c84c5aa0-0455-11e5-8682-3c59dd871817.png)  
![image](https://cloud.githubusercontent.com/assets/7599351/7827123/ce520bfc-0455-11e5-8a51-ead4c0096b82.png)

**Comment by Ionitron** [comment]
Greetings @xierenyuan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3838). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3838)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @xierenyuan!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
