### ISSUE TITLE
bug: Title doesn't show in ion-header-bar with bar-subh

### ISSUE THREAD

**Issue by MichaelJCole** [driftyco/ionic#3839]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'd like a subheader with two buttons and a title.  When I try this, the h1 doesn't appear.

```
    <ion-header-bar class="bar-positive bar-subheader">
      <div class="buttons">
        <button class="button button-icon icon ion-ios-minus-outline"
          ng-click="showDelete = !showDelete">
        </button>
      </div>
      <h1 class="title">Help!  I'm nowhere to be found!</h1>
      <div class="buttons">
        <button class="button" ui-sref="app.tips">
          Tips
        </button>
      </div>
    </ion-header-bar>

    <ion-content class="ion-subheader">

      <ion-list show-delete="showDelete"  show-reorder="!showDelete">
     ...
```
Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17 Qiana 
Node Version: v0.12.0

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @MichaelJCole!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
