### ISSUE TITLE
bug: View Caching breaks Angular-Cache localStorage

### ISSUE THREAD

**Issue by danielcha** [driftyco/ionic#3843]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When using Angular-Cache with localStorage updates to the cache don't get updated to the view when view caching is enabled (which is default):

http://codepen.io/anon/pen/jPVppG

Each time you switch tabs/views one item is added to the cache. This happens successfully as they are logged to the console and also the 'resolve' in the router is called. However, although the model changes... the view with the ng-repeat doesn't if view caching is turned on. When I turn off view caching (on line 5) everything works as expected.

To reproduce:

1) switch tabs a couple of times and see the list in the view grow.
2) go to line 5 and turn on view caching and refresh
3) switch tabs a couple of times and nothing happens
4) if we check the console we find that the cache is updating and the resolve function is being called

Alternatively, turning view caching on, and localStorage caching off, also resolves the issue. View caching and localStorage are clearly not playing nice together.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @danielcha!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
