### ISSUE TITLE
bug: has-header class and list – gets out of screen

### ISSUE THREAD

**Issue by hryamzik** [driftyco/ionic#3844]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>1. Start with a tabs template.
2. Add a sub-header or resize the header with css
3. Add ```has-header``` class to ```ion-nav-view```:

    ```js
    <ion-nav-view class="has-header"></ion-nav-view>
    ```
4. Find the list view moved down, but not resized, so last item should be outside the screen.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @hryamzik!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3844). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3844)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by delta98** [comment]
Could you provide a plunkr? If you are re-sizing the header with css the has-header will not be able to apply the correct offset to top. It's default value is currently `top:44px;` 

Without seeing your code my suggestion would be to apply a bottom padding of 44px to the allow for the sub-header.

**Comment by Ionitron** [comment]
Greetings @hryamzik!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
