### ISSUE TITLE
bug: Windows, cant add platforms via ionic platform add

### ISSUE THREAD

**Issue by csakai** [driftyco/ionic#3847]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I try to run "ionic platform add ios" or "ionic platform add android", the process fails. I believe this has to do with the fact that since I'm on windows, I can have spaces in my folder names.</span>

EDIT: I've changed it so my user folder no longer has spaces in the name and I still get the same errors. Here's the log:

![2015-05-27 even after i changed the folder name](https://cloud.githubusercontent.com/assets/3250676/7849760/f72af254-04a6-11e5-9dbe-d9cbe9dedeaf.PNG)

EDIT: I was able to get around this issue by manually making the "platforms" and "plugins" directories in my project before running ionic platform android and ionic build android. Shouldn't that be done automatically by the command though?
<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @csakai!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
