### ISSUE TITLE
bug: how can I handle a redirect without html5Mode ?

### ISSUE THREAD

**Issue by parliament718** [driftyco/ionic#3855]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm trying to implement OAuth flow for my app and [lack of html5Mode support](https://github.com/driftyco/ionic/issues/1930) means I cannot bootstrap the app from a url like example.com/myReturnUrl it must be example.com/#/myReturnUrl

However, when doing the authentication flow I get redirected to

example.com/myReturnUrl#access_token=...

I seriously cannot find any way to change this as I believe it as to do with the OAuth spec (if I try to pass "#/myReturnUrl" instead of "/myReturnUrl" to OAuth's ```redirect_uri```, param it immediately fails with ```invalid_parameters``` error.

But how can I handle this redirect? 
1. user opens in-app-browser via "_blank"
2. after login that same browser window's url gets changed to the redirect_uri
3. my app should bootstrap, save the access token to localStorage, then close the window (showing the app that was underneath)

I cannot do step 3 because the app cannot bootstrap from the redirect url which does not contain a hashbang.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @parliament718!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3855). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3855)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Well you should still be able to use HTML5Mode with ionic, there shouldn't be anything preventing that.
That particular issue was more about SEO on mobile websites.

Even if html5Mode doesn't work, you should still be able to use hashbang mode to handle redirects.
https://github.com/oauth-io/oauthd/issues/30#issuecomment-33185168

**Comment by MichaelMcClenaghan** [comment]
Check out ng-cordova-oath, we're using it in our app for oauth stuff and it works pretty well :)
https://github.com/nraboy/ng-cordova-oauth

**Comment by Ionitron** [comment]
Greetings @parliament718!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by lucasalmeida92** [comment]
@parliament718 If you wanna try with html5mode enabled, here what I did:

You will have to create your own web server because 'ionic server' creates a server that don't support modRewrite.

Here what I did:

**1- Web Server for Production ( Nodejs + Express)**

***server.js***

https://gist.github.com/lucasalmeida92/7f67f5183318d44f348b

**2- Web Server for Development ( Nodejs + Gulp + BroswerSync + Connect History Api Fallback)**

***gulpfile.js***

https://gist.github.com/lucasalmeida92/592185d6bfdc5626cf5a

**3- Gulp task for Mobile App build (with gulp-replace package)**

When you put `<base href="/">` inside the head tag in your index.html file, the application will work fine with Html5Mode enabled in a web browser, but in your mobile application you gotta use `<base href=".">` instead.

To automatize this, I created a gulp task with **gulp-replace** node package to do the job for me:

    gulp.task('build:device', ['sass', 'compressJs', 'jade-templates'],function () {
      return gulp.src(paths.jade[1])
      	.pipe(replace('base(href="/")', 'base(href=".")'))
        .pipe(jade())
        .pipe(gulp.dest('./www/'));
    });

So before I run `"ionic build android"` i run `"gulp build:device"` .

**4- Url paths Cautions**

You will have to be careful with url paths.

- **href** urls must start with "/". Ex.: `<a href="/app/list">link</a>`
- **src** urls must start without "/". Ex.: `<img src="img/banner.jpg">`
