### ISSUE TITLE
npm install -g ionic failed

### ISSUE THREAD

**Issue by RobertLibe** [driftyco/ionic#3857]
Our proxy is blocking https://registry.npmjs.org/archiver/-/archiver-0.5.1.tgz as malware.
There are no problems with versions higher than 0.9.x.
Is it possible to change the archiver version manually?
Are there any issues for using the newer versions of archiver?

Thank you.

Edit: Its more an ionic-cli issue.

**Comment by Ionitron** [comment]
Greetings @RobertLibe!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3857). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3857)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
