### ISSUE TITLE
bug: UI Issues when running on Android Device.

### ISSUE THREAD

**Issue by zeeshanjan82** [driftyco/ionic#3858]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Today I tried to start using Cordova and AngularJS Material Design and have just started with a single page by following the tutorial but I am surprised with the results.

When I tested the app this I am doing using the command cordova serve or ionic serve and view the application in the browser then it looks as expected (I have attached the screenshot)

When I tested the app on the android emulator it works like it was working in the browser as expected.

Till now everything seems OK, but when I deploy the app using ionic run android or cordova run android I see that the UI is distorted and looks not that good(I have attached the screenshot)

I am not sure about whats causing the issue in the android phone when it is working as expected in the browser and emulator. 
![screenshot_2015-05-29-18-19-25](https://cloud.githubusercontent.com/assets/8342604/7883005/aefece66-0630-11e5-9046-1ff917bdafca.png)
![screen shot 2015-05-29 at 6 21 57 pm](https://cloud.githubusercontent.com/assets/8342604/7883008/b6b0e086-0630-11e5-8e05-1e606b2dd3ea.png)

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @zeeshanjan82!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3858). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3858)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
There could be a few things going on here, so I'll need some more info. 
What version of android are you testing on?
Can you remote debug on the device and see if there are any 404s? 
Can you make sure that the paths are 100% correct?
I need as much information as you can provide.

**Comment by zeeshanjan82** [comment]
Hi @mhartington  I tried to debug and analyze the issue and here is what I have found. I had configured the emulator to run on latest Android OS i.e Lollipop which is API Level 22 and I was trying to test it on my physical android phone which is Jelly Beans API Level 17 and that was the issue. Because later when I tried to run it on a physical device with Lollipop it worked as expected. 

Then when I used Jelly Beans API Level 17 in the emulator it did not work. So as per this post: https://www.addthis.com/blog/2014/10/27/7-things-to-consider-when-making-ios-and-android-apps-with-cordova-or-phonegap/#.VWkm9WSqqko
The Ionic Framework CSS will only be supported from version 4.4.x above and for anything which is lower than that version, developer needs to really work hard to make it look the same.

I just wanted to confirm is it true. Will Ionic only work form version 4.4.x and above and not for version 4.4.x below like Jelly Beans e.t.c?

**Comment by mhartington** [comment]
Right now we support Android 4.1+, so that includes jelly bean, which makes this issue a bit more strange. I've tested Ionic on a 4.1 device and it worked without any issues. Are you trying to run it on the device with livereload enabled?

**Comment by zeeshanjan82** [comment]
Sorry for the late response. When I tried to run the application on the latest android version it worked as expected, the issue only comes when running the application in the android version jelly beans. Now I am using angular material instead of ionic also I am using Cordova. In cordova I use the crosswalk plugin and things work as expected. Angular Material seems to be a better option than the ionic framework.

**Comment by AntonioCunha** [comment]
So we are also using angular material and cordova to build our android apps and we had such behaviour in our first attempts.  In our case the problem was that we were inclunding our css files as  /node_modules/angular-material/angular-material.min.css. and that works fine serving on a normal webserver because node modules was under webserver root. But in Android your app is not under root so we need to remove the first /. So our css files are like this node_modules/angular-material/angular-material.min.css.

For us this did the job. Hope it helps.
