### ISSUE TITLE
bug: Splash and Icon generator not working.

### ISSUE THREAD

**Issue by martinuho** [driftyco/ionic#3859]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I tried to use the ionic splash and icon generator from the blog/website tutorial. It would not read my png files, even though I placed them in the root. I converted them to ai files and they would return an error saying the files could not be read (although they would open in preview and in Adobe Illustrator). 
I then used the cordova generator instructions and got this error:

{ [Error: Command failed: convert: unable to open image `platforms/ios/splash/Resources/icons/icon-72@2x.png': No such file or directory @ error/blob.c/OpenBlob/2675.
convert: WriteBlob Failed `platforms/ios/splash/Resources/icons/icon-72@2x.png' @ error/png.c/MagickPNGErrorHandler/1630.
] timedOut: false, killed: false, code: 1, signal: null }

Sent you guys a tweet- any help would be appreciated.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Hm, I just gave it shot and it seemed to work fine. Could just be hiccup on the server side. Would you be able to give it another try?

**Comment by martinuho** [comment]
Hi - I had to use the Cordova Splash Tool to get it working but I did figure it out eventually. 
Many Thanks

**Comment by Ionitron** [comment]
Greetings @martinuho!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
