### ISSUE TITLE
bug: Issue with installation of cordova-whitelist-plugin

### ISSUE THREAD

**Issue by julienwikart** [driftyco/ionic#3862]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

I updated the version of cordova-android, and i triedto include the cordova-whitelist-plugin :
https://github.com/apache/cordova-mobile-spec/tree/master/cordova-plugin-whitelist

This plugin requires cordova ios 4.0.0 but i can only find cordova ios 3.8.0
How can I do ?

Thank you for your help</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @julienwikart!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3862). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3862)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by julienwikart** [comment]
I found the solution : 

cordova platform add ios@4.0.x --usegit

**Comment by mhartington** [comment]
So as far as I know, the whitelist plugin shouldn't cause any issues with cordova ios-3.8.0. So you don't need to use cordova-ios 4.0

**Comment by rakelblujeans** [comment]
@julienwikart i just tried that and am getting errors running my fresh build on ios. something about a bash script no longer compiling. were there any other tweaks you had to make?

**Comment by HelloYu** [comment]
I add cordova-whitelist-plugin to handle 404 error in android device , when I use $http.get .

**Comment by mhartington** [comment]
@rakelblujeans Never seen this before, are you seeing this a stock cordova project (without ionic)?

**Comment by rakelblujeans** [comment]
No, not stock cordova. I'm using it in an Ionic project. :\


look.away@gmail.com

347.614.1148
<http://www.linkedin.com/profile/view?id=7743709&trk=tab_pro>
<http://facebook.com/raquel.bujans>

**Comment by mhartington** [comment]
Can you do `ionic project ls` and list the version of the platforms you are using?

**Comment by rakelblujeans** [comment]
'ionic project ls' doesn't work for me, but here is the output from 'ionic
info':

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.6.1
Ionic App Lib Version: 0.3.3
ios-deploy version: Not installed
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.12.5
Xcode version: Xcode 6.4 Build version 6E35b


​

**Comment by mhartington** [comment]
Sorry, `ionic platform ls`

**Comment by rakelblujeans** [comment]
Here's my output:

$ ionic platform ls
Updated the hooks directory to have execute permissions
Installed platforms: android 4.0.2, ios
Available platforms: amazon-fireos, blackberry10, browser, firefoxos
​
