### ISSUE TITLE
docs: How to create a validation multi-type with ng-messages

### ISSUE THREAD

**Issue by devtosystems** [driftyco/ionic#3864]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Inspired by the facebook registration form, would create a field that was possible to insert e-mail or phone and my validation messages were personalized, brought the controller, for example.

```html
<label class="item item-input item-stacked-label">
    <span class="input-label">Email</span>
    <input type="text" name="email_tel" placeholder="john@suhr.com ou 4199776565" />
</label>

<div class="form-errors" ng-show="signupForm.email_tel.$error && signupForm.$submitted" ng-messages="signupForm.email_tel.$error" ng-messages-include="templates/validations/signup-email_tel.html">

    <div class="form-error" ng-messages="signupForm.email_tel.$error" ng-messages-multiple>
        <div ng-message="required">
	    {{ ::validations.required }}
        </div>
        <div ng-message="minlength">
	    {{ ::validations.minlength }}
        </div>
        <div ng-message="maxlength">
	    {{ ::validations.maxlength }}
        </div>
    </div>

</div>
```

References:

Validation in Ionic Framework Apps with ngMessages
https://calendee.com/2014/12/26/validation-in-ionic-framework-apps-with-ngmessages/
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @devtosystems!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3864). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3864)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This is not an issue with the framework, but a general question. Please use the forum instead. 

If you need any examples for handling forms, I personally am a fan of angular-formly (which has ionic-templates). They have examples to create the form you are describing. 

http://angular-formly.com/#/example/integrations/angular-wizard

**Comment by devtosystems** [comment]
Humm, interesting mhartington!
Thanks! :D
