### ISSUE TITLE
docs: How do you create MVC structure with AngularJs and Ionic app?

### ISSUE THREAD

**Issue by devtosystems** [driftyco/ionic#3866]
**Type**: <span ionic-type>docs, bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>How do you create MVC structure with AngularJs and Ionic app?
https://github.com/devtosystems/ionicapp-styleguide/issues/1
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @devtosystems!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3866). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3866)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by delta98** [comment]
AngularJS isn't a conventual MVC framework as there isn't any real separation between the Controller and the Model. $scope acts as your model and application state. 

Can I suggest you read this document here regarding key concepts within AngularJS https://docs.angularjs.org/guide/concepts

**Comment by devtosystems** [comment]
Thanks for your contribuition, Jason!
What's a sugestion in my case?
Em 02/06/2015 06:50, "Jason Brown" <notifications@github.com> escreveu:

**Comment by Ionitron** [comment]
Closing this as this is not an issue with the framework, but a general question. Please use the forum instead.
