### ISSUE TITLE
bug: Collection-Repeat Swipe Option Delete

### ISSUE THREAD

**Issue by davidpatrick** [driftyco/ionic#3867]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>While using ng-repeat, if you add a delete button as one of the ion-option-buttons, when you splice that item from the array it properly removes the element from the array and removes the swiped options.

However using collection-repeat it will leave the options open and you have to manually close them, which gives the appearance at first glance that it didn't remove the item and only closed the options.  Is there anyway other way to accomplish this with collection-repeat?

With collection-repeat: http://codepen.io/davidpatrick/pen/VLPXVJ
With ng-repeat: http://codepen.io/davidpatrick/pen/NqdYed</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @davidpatrick!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3867). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3867)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Alright, thanks for the codepens.

**Comment by kreck** [comment]
any update on this issue? I'm experiencing the same problem in my lists with collection repeat.

**Comment by mhartington** [comment]
Still in progress, but PRs are always welcomed.

**Comment by tskweres** [comment]
Did this ever get fixed?

**Comment by imajneer** [comment]
Apparently not.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#15
