### ISSUE TITLE
bug: Can not start my app on my OS X.

### ISSUE THREAD

**Issue by bigscorpions** [driftyco/ionic#3868]
**Type**: bug
**Platform**: OSX

Hello everyone, I need help, I just can not create an app with ionic cli on osx.

Error from my console:
```
 $ ionic start myapp
Creating Ionic app in folder /Users/Woody/Test/myapp based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Error updating config.xml file: Error: ENOENT, no such file or directory '/MyHome/myapp/config.xml'
 ✗ Unable to save settings file: Error: ENOENT, no such file or directory '/MyHome//myapp/ionic.project'
```
ionic info output:
```
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:  
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v0.10.32
Xcode version: Xcode 6.3.2 Build version 6D2105 
```

My OS is OSX Yosemite 10.10.3.
I tried ionic with cygwin on my windows and also my archlinux, it's just ok. But now on my OSX, it can not create my app directory(or it rolls back because of the error). I tried with 'sudo' too.  
Does anybody  know how to debug this?  I want to find out what's wrong with my enviroment but I don't known how to debug the cli.

**Comment by Ionitron** [comment]
Greetings @bigscorpions!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3868). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3868)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by bigscorpions** [comment]
I'm not sure what's the problem. Maybe it's my network or something else. I have tried to reinstall cordova and ionic, and restart my system(I forgot if I did it or not), when I come back from work, it's just fine to start the project. I think it's my network problem cause the downloading speed from github is too slow.
