### ISSUE TITLE
feat: Removing watchers from cached views

### ISSUE THREAD

**Issue by shprink** [driftyco/ionic#3870]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Type: feat

Platform: all

I have noticed that watchers are not removed from cached views. There is no need to keep watchers from views your are not currently using. It just make the digest cycle slower for no purpose.

I have done something similar in the past I could give it a try if you think it is worth trying. I think it will give a great performance enhancement. 

Cheers,
Julien</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @shprink!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3870). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3870)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by prashantpalikhe** [comment]
Scope of the cached view is disconnected from the hierarchy. So, $rootScope.$digest() won't iterate through the disconnected scope's watchers. So, the digest cycle timing is not affected.

**Comment by Ionitron** [comment]
Greetings @shprink!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
