### ISSUE TITLE
bug: IonInfiniteScroll bug on non-JS scrolling 

### ISSUE THREAD

**Issue by prashantpalikhe** [driftyco/ionic#3871]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I noticed that my app running on Android (with native scrolling) infinitely triggers _on-infinite_ callback function when a state is changed before the first on-infinite callback is complete.

This codepen http://codepen.io/felquis/pen/vEbBpJ can be used to reproduce the issue. Just make sure, the JS scrolling is disabled. 

The codepen was initially used on this thread http://forum.ionicframework.com/t/ion-infinite-scroll-is-looping-after-state-change-before-infinitescrollcomplete/19609 which also discusses the same issue.

Now after debugging, I found the buggy section of code which is in the function IonInfiniteScrollController::finishInfiniteScroll() 

The code in there only check bounds again immediately if the page isn't cached but does so ONLY if JS scrolling is enabled. For non JS scrolling it always checks bound and since the cached view is display: none -ed, the check to see if we've scrolled far enough to trigger an infinite scroll always returns true.

The result, on-infinite is called infinitely. 
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @prashantpalikhe!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3871). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3871)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Cool, thanks for the detailed description. 
Can confirm that I see this happening as well.
Passing this to @perrygovier

**Comment by prashantpalikhe** [comment]
@mhartington What is the status of this? Or should I create a PR?

**Comment by mhartington** [comment]
You can if you want. PRs are always welcomed.

**Comment by Ionitron** [comment]
Greetings @prashantpalikhe!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by zanemcca** [comment]
This is still an issue for me. 
Have you found a solution @prashantpalikhe?

**Comment by zanemcca** [comment]
@mhartington @prashantpalikhe I found a simple fix for the issue. The max and current scroll height were both 0 and there was no checking for it. I added the condition in #4667
