### ISSUE TITLE
bug: Ionic Swipe Cards won't work properly on tabs view

### ISSUE THREAD

**Issue by nikoTM** [driftyco/ionic#3872]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span>  <span ionic-webview>webview</span>

<span ionic-description>So the next swipe card pops in after the swipe and disappears after the animation, but it is there, so if you swipe the visibly empty area, the card will get swiped or if you pull it up it will appear again. To reproduce this you need to take ionic tabs template , add ionic swipe cards to it and make sure it adds cards with the method in the pen http://codepen.io/anon/pen/NqdYGq 
Or you can download this project, emulate and check accounts tab https://github.com/nikoTM/swipebug</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @nikoTM!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
