### ISSUE TITLE
bug: Pull to refresh (ion-refresher) can trigger multiple pull to refresh requests

### ISSUE THREAD

**Issue by FMCorz** [driftyco/ionic#3874]
**Type:** bug

**Platform:** all 

@dpaloucva brought to my attention that ion-refresher could be called multiple times.

Demo: http://play.ionic.io/app/c1d3b5e71b34

To replicate:

1. Pull to refresh
2. During the refresh, click on the screen

Expected:
- Nothing happens

Actual:
- The refresh function is called again

**Comment by Ionitron** [comment]
Greetings @FMCorz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3874). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3874)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by FMCorz** [comment]
I am not keen on giving permission the following permission to your bot, so I'll leave the issue as is.

```
This application will be able to read and write all public repository data. This includes the following:

    Code
    Issues
    Pull requests
    Wikis
    Settings
    Webhooks and services
    Deploy keys
```

**Comment by sclearion** [comment]
Okay I see what you mean. Thas IS a bug. Maybe as a workaround you could trigger 
```javascript
$ionicLoading.show({
      template: 'waiting on server...'
    });
```
after you pull refresh. This will show a input-blocking modal and prevent someone from clicking the screen

**Comment by giorgiofellipe** [comment]
+1

**Comment by Ionitron** [comment]
Greetings @FMCorz!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by FMCorz** [comment]
As far as I know, this is still an issue. There is an example above, and the necessary documentation. You'll excuse me if I don't go and create the exact same issue again.

Here is the same example as above using the nightly version of Ionic:
http://play.ionic.io/app/64563c8dc1b1
