### ISSUE TITLE
bug: Still No Backdrop Shades In Modals

### ISSUE THREAD

**Issue by vladipus** [driftyco/ionic#3875]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>My previous submission https://github.com/driftyco/ionic/issues/3067 was closed due to inactiviy, but the bug is still there... 

On small, non-tablet displays the dialog just occupies the whole space. However, I'm more interested in this to work correctly (with the backdrop): http://codepen.io/anandvj/pen/KwmMGY
If you minify the viewport during the image view, the backdrop is just gone.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vladipus!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3875). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3875)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
You just need to target the backdrop with some css, which is whats being done on larger screens. 

```css
.active .modal-backdrop-bg {
  opacity: .5;
}
```
http://codepen.io/mhartington/pen/OVpNEa
