### ISSUE TITLE
perf: Problem in USB Debugging

### ISSUE THREAD

**Issue by rizvanhaider** [driftyco/ionic#3876]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi! you are working great! 
I am getting a problem after my new installation of window and up-gradation of ionic+cordova. When I run the command [ionic run android] to debug the app directly with device it does not installs the app on the device but the command prompt shows the message that launch successful but actually the app is not installed.
I can only test the app by manually copying and installing of .apk file from the platforms\android\build\outputs\apk directory to my phone.
![screenshot 9](https://cloud.githubusercontent.com/assets/9403438/7939384/4225619c-0964-11e5-97f6-28e1b9ddc7cf.png)
. </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @rizvanhaider!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3876). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3876)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Can you try `ionic run android --device`

**Comment by rizvanhaider** [comment]
having still same issu... :(

**Comment by mhartington** [comment]
Could you provide the output of `ionic info`

**Comment by rizvanhaider** [comment]
Following is the ionic info



![screenshot 10](https://cloud.githubusercontent.com/assets/9403438/7958616/611341ea-0a0a-11e5-9a50-35a785c71d0e.png)

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-cli#457

**Comment by mhartington** [comment]
Moving this to the cli since it is related to that. Please continue the conversation over there.
