### ISSUE TITLE
Asset serving needs to be consistent with capitalization between platforms

### ISSUE THREAD

**Issue by bwheeler96** [driftyco/ionic#3881]
Let's say you have a file at `wwww/js/controllers/Main.js` and then you have a link to it in your `index.html`
```
<script src="js/controllers/main.js"></script>
```

For some reason, the asset without capitalization loads fine in the browser, and on the simulator, but fails **miserably** and **silently** on any iOS device.

After spending hours trying to find the silent culprit, I think Ionic should either incorporate better logging when assets can't be found, or require strict capitalization from the server. Seeing as the browser is my only real method of digging deep with debugging, I feel it needs to be treated exactly like my device

**Comment by Ionitron** [comment]
Greetings @bwheeler96!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3881). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3881)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @bwheeler96!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
