### ISSUE TITLE
bug: expose-aside-when side rt doesnt display correcly

### ISSUE THREAD

**Issue by KevinAble** [driftyco/ionic#3882]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When the expose-aside-when directive is used with the side right menu, the menu will display correctly on initial load, but after a menu item is clicked,  the right side will not display and a white box (menu size) will display on the left.   
here is a codepen example 
http://codepen.io/Slick6262/pen/YXZEOg
click on one for the right menu items</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @KevinAble!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
