### ISSUE TITLE
bug: nav-direction not working with ng-repeat

### ISSUE THREAD

**Issue by jonathanherdt** [driftyco/ionic#3886]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I want to use [nav-direction](http://ionicframework.com/docs/api/directive/navDirection/) in the way it's documented in the docs but unfortunately it just doesn't do anything at all.

I tried using it like this:
```<a nav-direction="forward" data-ng-href="#/main/tabs/{{tabItem.path}}" data-ng-repeat="tabItem in tabItems track by $index">```
but it doesn't work. I have a tabbed interface and the href points to a different tab than the current one. [Here](http://codepen.io/anon/pen/PqpBmv) is a codepen with the issue. Everything works smoothly until I add ng-repeat. In the codepen, I am talking about the buttons on the home-tab. The first two work as expected since they are in the same tab but as soon as you click on 'about' you can see the problem.
Thankfully, someone in the forum found out about the ```$ionicViewSwitcher.nextDirection``` function which I am using now. If this would be officially supported / documented, my problem would be solved. Since this is undocumented, my concern right now is that it might vanish at any time and then I would have to find out how to do this again.

You can find the forum discussion [here](http://forum.ionicframework.com/t/setting-the-transition-direction-animation/541/30).</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jonathanherdt!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3886). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3886)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @jonathanherdt!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by xiaody** [comment]
Seems a priority issue similar to #2741
A workaround is to move `nav-direction` and `href` to a child element in `ng-repeat`
