### ISSUE TITLE
bug: on-double-tap is not working

### ISSUE THREAD

**Issue by do-web** [driftyco/ionic#3887]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>If i use this on rootscope:
```
<div class="prev col" on-double-tap="playPrev(currentTrack)" on-tab="playAgain()"><i class="ion-skip-backward"></i></div>
```
on-double-tap is called on single tab. playAgain is not called and without on-tab, on-double-tap is also called on single tab.
        </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @do-web!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3887). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3887)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by do-web** [comment]
I use crosswalk

**Comment by mhartington** [comment]
Can you provide a codepen?

**Comment by Ionitron** [comment]
Greetings @do-web!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @do-web!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by SagarBhalodia** [comment]
bug: on-double-tap is not working
