### ISSUE TITLE
bug: `$ionicView.enter` event not called when 'swipe back transition' is cancelled

### ISSUE THREAD

**Issue by janakerman** [driftyco/ionic#3890]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Firstly - I'm unsure as to whether this should be raised here or the forum, I'd be happy to repost this on the forum if it isn't the right place. I'm also not sure if this qualifies as a bug report or a feature request - I went for bug as it seems to me as though the view __is re-entering__ but I suppose that's subject to debate.

If you begin dragging right on the left edge of a view to transition to the previous view, you get the event `$ionicView.beforeLeave`. However, if you cancel that gesture before it has has passed the threshold to trigger a back transition you __don't__ get any events letting you know this was the case. I would expect to see the event `$ionicView.enter` to indicate that the view has finished animating back to its original state.

A little bit of context - my use case for this is that I need to disable my full screen `ion-slide-box` `beforeLeave` as the slide box is animating its contents, along with the entire view (the slide box also animates as you drag creating a effect). I re-enable the slide box when the `leave` event fires:
    
    $scope.$on('$ionicView.beforeLeave', function(){
      $ionicSlideBoxDelegate.enableSlide(false);
    });

    $scope.$on('$ionicView.leave', function(){
      $ionicSlideBoxDelegate.enableSlide(true);
    });

The problem is that if the user cancels the gesture I don't have any obvious event to re-enable my slide box. I could be misunderstanding the best way to achieve this, but to me the obvious option seemed to use the transition events. Unfortunately, they don't cover all the events I'm interested in.

Here's a link to a [Plunkr](http://plnkr.co/edit/h4JQjh56YZeedRmkkI7d?p=preview) - It might not be much help as the `beforeLeave` and `leave` events don't fire at all when loading it in Safari on my iPad, but they do with the same `.on` events in my Ionic application. This could be an issue in my Plunkr, or a completely separate issue altogether.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @janakerman!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3890). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3890)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by alexanderwallin** [comment]
I would make good use of this too, plus it seems logical to notify the views of a cancelled navigation.

We change the navbar's background and text colours between views. When hitting the back button, `$ionicView.beforeLeave` works well to tell the navbar to transition back to it's original visual state. When cancelling a swipe to go back we need to know this in order to set the correct colours.

**Comment by Ionitron** [comment]
Greetings @janakerman!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by lordgreg** [comment]
We are still having this issue. Swiping back doesn't trigger the beforeEnter event. Can anyone look into this?

**Comment by wendel841** [comment]
+1, iOS 8.1.3, ionic 1.3, swiping back doesn't trigger the beforeEvent event.
