### ISSUE TITLE
bug: $ionicNavBarDelegate.showBackButton()  Undefined

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#3893]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>`$ionicNavBarDelegate.showBackButton() ` is supposed to return a boolean indicating the status of the back button.  

Instead, the method returns undefined.

Related Issue #3096

Sample : http://codepen.io/calendee/pen/KpWeaJ</span>

<span is-issue-template></span>

**Comment by emiidee** [comment]
Experiencing the same issue. Tried setting it first, before getting it as well - no luck.

**Comment by Ionitron** [comment]
Greetings @calendee!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by simplymoody** [comment]
Still experiencing this issue. Sample codepen still exhibit the bug

**Comment by werdnanoslen** [comment]
+1
