### ISSUE TITLE
bug: Range input prevents vertical scrolling

### ISSUE THREAD

**Issue by dtruel** [driftyco/ionic#3897]
Hello,

I've got an application that has a bunch of sliders repeating vertically.  If I am trying to scroll down the page by swiping up anywhere on any of the sliders ( not just the circle in the sliders), the touch is blocked, and the view will not scroll.  I have to touch somewhere else on the screen where there isn't a slider to slide vertically.

Ideally the slider should be able to detect if you are swiping horizontally or vertically.  If you swipe vertically then it should just scroll the page.  You should also have to touch the actual sliding part as well; a touch anywhere on the slider should not move it.

This is the behavior for native iOS.  To see, go to settings -> sounds, and see how the scrolling works when you swipe up and down on the "ringer and alerts" volume slider.

Looks like it was addressed for some inputs here: https://github.com/driftyco/ionic/issues/1078, but perhaps the slider was not addressed.

Thanks!  Ionic is awesome!

**Comment by Ionitron** [comment]
Greetings @dtruel!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3897). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3897)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by dtruel** [comment]
Well, I found that using a different slider that is angular compatible works.  Looks like the "range" input isn't yet working that great in the iOS browser.  I used the following slider and it works as it should.

https://github.com/rzajac/angularjs-slider

**Comment by riteshjagga** [comment]
The `angularjs-slider` still doesn't fix this. The problem remains the same, when you tap on the slider with an intention to scroll, slider changes value. It doesn't work with `overflow-scroll="true|false"`.
