### ISSUE TITLE
bug: $ionicView lifecycle timing issues

### ISSUE THREAD

**Issue by alvarowolfx** [driftyco/ionic#3899]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When the $ionicView.afterEnter is fired, the inners headers bars are on entering/leaving state yet, it makes more sense to call the event when they are on active/cached state. 

I encountered this problem when I was developing the feature to change navBar color using navBarDelegate (Pull request #3896). 

On the codepen, I show a example that I change the navbar color, of each screen, but on the second screen I have to give a little delay to get the header bars on the state active/cached. The issue of the cached bar being on top of the active bar is already reported on Issue #3898.

http://codepen.io/alvarowolfx/pen/gpWRdJ

I tried to fix this, but I'm trying to understand how all this lifecycle events work to know how to fix this. I hope you guys consider this and I'm willing to help.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @alvarowolfx!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
