### ISSUE TITLE
bug: $ionicPlatform.ready event does not happen when “forge.js” is included in index.html 

### ISSUE THREAD

**Issue by ranjitpandit** [driftyco/ionic#3903]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have been developing my app with ionic1.0-rc.1 and recently I tried upgrading to ionic 1.0. 
Previously, I have never had issues upgrading to newer ionic version but this time my app just wouldn't work with ionic 1.0.
After spending the whole weekend I found out that the problem was that the ionicPlatform.ready event is not occurring when the "forge.js" library is included in the app.

My app uses the forge library for encryption. 
Forge is at: "https://github.com/digitalbazaar/forge.git"

I have created a simple test with the ionic starter app to prove the problem and it's easy to re-create.

ionic start myApp

build the forge package:
git clone https://github.com/digitalbazaar/forge.git3
cd forge
npm install
npm run bundle

That will create a "js/forge.bundle.js" file in the forge source tree.

copy over "js/forge.bundle.js" in the starter apps lib directory "lib/forge/forge.bundle.js"

Now simply include the forge library in the starter app's index.html.

With the file included in the app, the ionicPlatform.event() callback never occurs.
Don't include the forge library and the event happens no problem.

I also found out that this problem started happening with "ionic.1.0-rc.2" onwards. "rc.1" works fine.

Can someone please look into this issue urgently? Util this is resolved my app is DOA beyond ionic 1.0-rc.1
Happy to look into any work around.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ranjitpandit!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3903). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3903)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by pbakondy** [comment]
Trigger.io integration conflits forge cryptography library. The use the same window.forge variable name.

commit:
https://github.com/driftyco/ionic/commit/6665eac870925973bffd704355b09fec824f8085

I have researched this issue and I have found a small difference

for forge cryptography library
typeof window.forge === "function"

for trigger.io forge
typeof window.forge === "object"

**Comment by ranjitpandit** [comment]
I tried the fix in my local ionic.bundle.js and my app runs fine now. :)
Thank you so much for looking into this issue!!

**Comment by Ionitron** [comment]
Greetings @ranjitpandit!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
