### ISSUE TITLE
bug: can't add android

### ISSUE THREAD

**Issue by limerickgds** [driftyco/ionic#3904]
Type: bug

Platform: android

ionic platform add android 
 
npm http get https://registry.npmjs.org/cordova-android/4.0.0
typeError: request path contains unescaped characters

I  try to set npm https-proxy and registry ,but still not work。And i can install others node package.

**Comment by Ionitron** [comment]
Greetings @limerickgds!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3904). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3904)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @limerickgds!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
