### ISSUE TITLE
bug: $ionicLoading chaining

### ISSUE THREAD

**Issue by mattchue** [driftyco/ionic#3910]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>With `$ionicModal` and `$ionicPopover`, you use a constructor function and then call `show()` against the constructed object. With `$ionicLoading`, the constructor and `show()` are the same, making it difficult to do work before the modal view itself is shown. If `$ionicLoading` worked in a similar way to the other modal services, it would alleviate this problem. 

http://codepen.io/anon/pen/XbRLYM</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mattchue!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
