### ISSUE TITLE
feat: Fastlane support

### ISSUE THREAD

**Issue by schurig** [driftyco/ionic#3913]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I would love to use [fastlane](https://fastlane.tools/) to auto-deploy the app.

Unfortunately, there is one XCode Setting set wrong. Fastlane needs to have the `Code Signing Identity` set to "**iOS Distribution**". With Ionic/Cordova it says "**iOS Developer**". Is it possible to implement a way to pass a parameter that fixes that? What about `ionic build ios --release`?

![screen shot 2015-06-10 at 17 55 16](https://cloud.githubusercontent.com/assets/2672413/8087211/e9e8a200-0f99-11e5-9db2-3ce18e691eed.jpg)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @schurig!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3913). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3913)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
building with the release flag will change all the signing identities to ios Distribution. 
So you would need to build with that flag everytime.
Keep in mind, any issues with fastlane would be better directed towards them or StackOverflow. 
Not really an issue with the framework :wink:

**Comment by gridsquare** [comment]
Hi @mhartington 

i built the project with``ionic platform add ios `` and  ``ionic build ios --release`` but the .xcodeproj release code signing identity is still 'iOS Developer'. 

![image](https://cloud.githubusercontent.com/assets/798196/8408674/3b479f5c-1e72-11e5-8487-eddb0337a535.png)

**Comment by mhartington** [comment]
Hmm, it seems that that is a bug with the cordova cli.
http://maruhgar.blogspot.com/2014/05/automating-cordova-ios-build.html

Might want to bring it up to the cordova team on their issue tracker
