### ISSUE TITLE
bug: ng-click + ui-sref not working on tabs directive. 

### ISSUE THREAD

**Issue by otruffer** [driftyco/ionic#3919]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Dear Ionic Developers

Working on ionic framework 1.0.0. Love it so far! :-) Now my issues

ng-click and ui-sref do not work on the tab delegate. On most elements the combination of the two change the state and execute the function stated in the ng-click attribute. But on the Tab directive only the ng-click function is triggered, the state does not change!

The second problem which might be related is: I decorated the $state delegate in order to log something in the console on every state change. Now this worked on any ui-sref click but on tab clicks the state.go does not seem to trigger or the decorator did not take effect. 

Retry here:
http://codepen.io/anon/pen/aOwwKw
Click on Home Tab -> no state change is logged in console even though $state.go is decorated.
Click on Home Tab/Scientific Fact -> state change is logged. Ok!
Click on About Tab -> state change does not happen even though ui-sref attribute on tab element, but ng-click function is triggered.

Cheers!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @otruffer!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3919). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3919)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ClemMakesApps** [comment]
It looks like the ng-click fires before the ui-sref does and that the click event isn't propagating through

**Comment by Ionitron** [comment]
Greetings @otruffer!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by benbabics** [comment]
:+1: This is still an issue. He's provided an adequate description of the issue, and supplied a link. Would you please re-open this issue and provide a solution? Thanks.

**Comment by jmsims2** [comment]
+1

**Comment by Matttaylor8910** [comment]
+1
