### ISSUE TITLE
docs: Documentation on developing for Ionic

### ISSUE THREAD

**Issue by vincpa** [driftyco/ionic#3920]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

I would like to get involved in bug fixing and even working on some compatibility issues with Windows Phone.

There are so many Ionic related repositories that it's almost impossible to know where to start. There's Ionic, Cordova-Lib, Ionic-code, ionic-cli...it's a bit overwhelming.

Is there any documentation for developers on how to get the Ionic dev environment up and running? Tips and tricks for debugging?

Thanks in advance.
Vince</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vincpa!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3920). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3920)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Hey @vincpa, to get up and running helping develop ionic, all you really need is to have npm, gulp, and bower installed. 

We have a page on the framework site that describes how you can contribute

http://ionicframework.com/contribute/

As far as the cordova side of things go, you really only need cordova and the ionic-cli installed, `npm install -g ionic cordova`, and this is just to test on devices.

Hopefully this helps clarify a bit more
