### ISSUE TITLE
bug: Push notifications not being recieved by the iPhone

### ISSUE THREAD

**Issue by hejalsoni** [driftyco/ionic#3925]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I went through the instructions on http://docs.ionic.io/v1.0/docs/push-from-scratch.
The issue is that the push notifications work on Android devices, but not iOS.
This is a link to my repository that I created. https://github.com/hejalsoni/push-tutorial

Thank you!

Please let me know if you need more information.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @hejalsoni!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3925). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3925)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Please ask this in our gitter chat room for the io-services.

https://gitter.im/driftyco/ionic-io-testers
