### ISSUE TITLE
perf: After keyboard open, takes too long to scroll

### ISSUE THREAD

**Issue by Stiveknx** [driftyco/ionic#3930]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>webview</span>

<span ionic-description>After focus on a input, ionic waits for keyboard to show up, after the keyboard it fully open, it scrolls to input again ...

But in almost all devices that  i've tested, it takes too long to do that ..
Sometimes more than 2 seconds.

It's there any way to "speed up" this action?

If we have to wait for keyboard height, we could, in first time, "save"the keyboard height. Then in the second time, we already have the keyboard height so we don't have to "wait", it's that possible?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Stiveknx!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
