### ISSUE TITLE
bug: No more landscape splashscreen on iOs

### ISSUE THREAD

**Issue by loicfavory** [driftyco/ionic#3931]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>I used `ionic resources ios` to generate splash screen.

The command didn't generate landscape splash screens, but it did in the past, is it normal ?
My app has different splash screen in landscape or portrait format.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @loicfavory!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3931). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3931)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ClemMakesApps** [comment]
Can you check to see what your orientation setting is set to in your config.xml?

**Comment by wonderdogone** [comment]
I just used ionic resources and notices the exact same issue. My config.xml shows no orientation setting? What should it be?

**Comment by Ionitron** [comment]
Greetings @loicfavory!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
