### ISSUE TITLE
bug: ios crash on ionic deploy update in airplane mode

### ISSUE THREAD

**Issue by jacksonkr** [driftyco/ionic#3934]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>xcode dies on line 61 of ionicDeploy.m

scenario:
I check for an update on app resume. I added a try/catch but this goes beyond the js level. This works fine in android, only iOS crashes out. I'd submit a fix but I don't know where ionicDeploy.m is coming from :/</span>

<span is-issue-template></span>

**Comment by Deminetix** [comment]
Should we be submitting issues for deploy here? As a workaround you could use the Cordova network status plugin to check if you have connection before calling the update method

**Comment by Ionitron** [comment]
Greetings @jacksonkr!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
