### ISSUE TITLE
bug: Ionic slide pager not updated after refresh

### ISSUE THREAD

**Issue by jbclot** [driftyco/ionic#3936]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm trying to refresh all the slides inside ionic-slide-box (after a push notification).
It works well, but the pager  is keep increasing every time its not refreshing </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jbclot!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3936). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3936)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by delta98** [comment]
Could you provide the code you are using, are you using `ng-repeat`? There is a known issue where `ion-slide-box` directive doesn't watch the element changes when new slides are added by `ng-repeat` and this can be affecting the pager count.

If you use `$ionicSlideBoxDelegate.update()` immediately after receiving the notification and adding the slide does this make a difference?

**Comment by Ionitron** [comment]
Greetings @jbclot!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
