### ISSUE TITLE
feat: Add firefoxos icon generation

### ISSUE THREAD

**Issue by lennycartier** [driftyco/ionic#3943]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Adding firefoxos icon generation might be a handful addition.
Guidelines are here : https://www.mozilla.org/en-US/styleguide/products/firefox-os/icons/</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @lennycartier!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3943). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3943)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by zalun** [comment]
It's implemented in Cordova - no idea why it's not working in FxOS
http://cordova.apache.org/docs/en/edge/config_ref_images.md.html#Icons%20and%20Splash%20Screens

**Comment by lennycartier** [comment]
Hi Zalun,

you are right "ionic resources" will set up a generic manifest for this platform. But on iOS and Android it will also use some image files dropped in a specific directory to automatically resize, crop these images and add it to the manifest.

Everything is detailed here : http://ionicframework.com/docs/cli/icon-splashscreen.html

That's what I was asking as a feature to the Ionic team :-)

lenny

**Comment by mhartington** [comment]
We're a choosing not to support firefox os.

**Comment by lennycartier** [comment]
Thanks for your answer. This is for everything or only for "ionic resources" ?

**Comment by mhartington** [comment]
Everything, including ionic resources

**Comment by khertan** [comment]
:( too bad ...
