### ISSUE TITLE
Can not create google-map

### ISSUE THREAD

**Issue by vladimir050486** [driftyco/ionic#3946]
Hello, I'm trying to create google-map in my app, but that seems to be too hard for me. Can you please look through my code at github and write me please what am I doing wrong...
App works but I can not see map not on the emulator ios and not on my iPhone 5...
This is the link to my git repo: https://github.com/vladimir050486/radars
Best regards, Vladimir.

map template is in -> templates/tab-map
map controller is in -> js/controllers
implemented everything to index.html by instructions -> index.html

Map works with angularjs because I've tryed it with simple MEAN stack app... But not with ionic...

**Comment by Ionitron** [comment]
Greetings @vladimir050486!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3946). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3946)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ClemMakesApps** [comment]
You'll probably be able to get a better answer if you post on the [ionic forums](http://forum.ionicframework.com/)

**Comment by mhartington** [comment]
We also have a maps starter template.

```
ionic start myApp maps
```
https://github.com/driftyco/ionic-starter-maps

As well as a codepen
http://codepen.io/ionic/pen/uzngt

**Comment by vladimir050486** [comment]
Thanks, I'll try to do my best!
