### ISSUE TITLE
bug: How can I combine maps starter wit tabs?

### ISSUE THREAD

**Issue by vladimir050486** [driftyco/ionic#3947]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>browser</span>

<span ionic-description>Tried to maintain everything by changing app.js setting router, controllers, services, templates, etc..
But nothing displays at all.
I've tried to use: ionic start myApp maps + manually set all necessary elements: of ionic start myApp tabs to my project.
But nothing appears on the screen of my emulator and device.
Best regards, Vladimir.
Here is my git link for what I've made:https://github.com/vladimir050486/combine-map.git
Please write me how can I combine two starts of ionic or manually connect one to another.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vladimir050486!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3947). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3947)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @vladimir050486!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic framework.

This GitHub issue tracker is used to track framework features, problems, and development.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
