### ISSUE TITLE
bug: Too small .button width in .button-bar under Android and Chrome

### ISSUE THREAD

**Issue by PSanetra** [driftyco/ionic#3949]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>The buttons in a button-bar have 0 width. If you place the button-bar in a ion-nav-bar the buttons will have only padding and 0 width.

The bug appears only in Chrome, not under Safari.

Here is a codepen with a fix for this issue:

http://codepen.io/anon/pen/KpvLQQ</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @PSanetra!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3949). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3949)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This is something that we don't want to support. Please use you're own css for this.
