### ISSUE TITLE
feat: Update ui-router dependency

### ISSUE THREAD

**Issue by thiagofelix** [driftyco/ionic#3957]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Is it possible to update current ui-router dependency to the next stable version?

Current used: 0.2.13
https://github.com/driftyco/ionic/tree/master/config/lib/js/angular-ui

Latest available: 0.2.15
https://github.com/angular-ui/ui-router

According to ui-router documentation it should not have any breaking change between these versions:
https://github.com/angular-ui/ui-router/blob/master/CHANGELOG.md

Perhaps another thing to consider is how manage these dependencies via NPM peer dependencies.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @thiagofelix!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
