### ISSUE TITLE
bug: collection-repeat w/ ion-reorder-button on object array defect

### ISSUE THREAD

**Issue by ashinw** [driftyco/ionic#3959]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi guys,

I have been trying to work around a defect that I encountered. The defect is evident in the following play pen: http://play.ionic.io/app/001fd457013b

Failing Test Case:
1. change attribute from ng-repeat to collection-repeat in html file
2. drag Stephanie over Janet for DEFECT
3. current ionic release reports reorder's toIndex as 19 

The toIndex is always 19 (based on the list's virtual window size) as reported in ReorderDrag.prototype._getReorderIndex due to el.offsetTop for each siblings being -1. Note, ng-repeat's execution over the same code reports el.offsetTop = 53. 

I dont know why collection-repeat is forcing all siblings offsetsTop to -1.

I hope that this issue make sense and that someone can recommend a work around until fixed.

rgds ash</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ashinw!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3959). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3959)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @ashinw!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
