### ISSUE TITLE
bug: stopPropagation() of 'drag' event is inconsequent

### ISSUE THREAD

**Issue by MartinMa** [driftyco/ionic#3960]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I handle the 'drag' event and call `stopPropagation()`, it doesn't affect the associated events 'drag-up', 'drag-right', 'drag-down' and 'drag-left'. They are still propagated up the DOM tree.

This seems inconsequent to me. When I call stop propagation on the general `drag event`, it should also affect the above mentioned associated events.

What do you think?

Well, right now it is necessary to bind to every single "derived" drag event and explicitly stop the propagation there.</span>

<span is-issue-template></span>

**Comment by Deminetix** [comment]
e.gesture.stopDetect();

**Comment by Ionitron** [comment]
Greetings @MartinMa!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
