### ISSUE TITLE
bug: parent directive + collectionRepeat + child directive = Error: [$compile:ctreq]

### ISSUE THREAD

**Issue by dusty73** [driftyco/ionic#3961]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,
    I found an issue regarding parent + child directive with collectionRepeat.

I defined two directives, parentDirective and childDirective. childDirective requires parentDirective.
ChildDirective is inside a collectionRepeat, while parentDirective is outside.

During compile phase of childDirective it gives this error:

Error: [$compile:ctreq] Controller 'parentDirective', required by directive 'childDirective', can't be found!

If I use these directives with ng-repeat everything is fine.

Check out this codepen: http://codepen.io/dusty73/pen/MwEyRP
Clicking on "Playlist ko" you'll see the error, "Playlist ok" uses ng-repeat instead of collection-repeat.

It seems to be an ionic bug.

Thank you for your help</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @dusty73!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3961). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3961)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @dusty73!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
