### ISSUE TITLE
bug: Ignored edge-threshold param when using option-buttons

### ISSUE THREAD

**Issue by sgg90** [driftyco/ionic#3962]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Ignored edge-threshold param is ignored on ion-side-menu-content if using option-buttons on the content view.

<p data-height="268" data-theme-id="0" data-slug-hash="LVzyJw" data-default-tab="result" data-user="sgg90" class='codepen'>See the Pen <a href='http://codepen.io/sgg90/pen/LVzyJw/'>Ignored edge-threshold param, ion-side-menu-content</a> by Sergio (<a href='http://codepen.io/sgg90'>@sgg90</a>) on <a href='http://codepen.io'>CodePen</a>.</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

http://codepen.io/sgg90/pen/LVzyJw/</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @sgg90!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3962). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3962)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @sgg90!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
