### ISSUE TITLE
bug: absolutly positioned elements are not shown

### ISSUE THREAD

**Issue by Caprisone** [driftyco/ionic#3964]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Elements with style="position:absolute" are not shown on $ionicPopup. But it can become visible if you change landscape.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Caprisone!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
