### ISSUE TITLE
bug: Several issues occurred to after upgrading. 

### ISSUE THREAD

**Issue by rsa408** [driftyco/ionic#3965]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>browser</span>

<span ionic-description>after upgraing cordova and ionic, these are happening to me;

1) ionic add platform android command: 
npm http GET https://registry.npmjs.org/cordova-android
npm http 304 https://registry.npmjs.org/cordova-android

2) this error on build command
:CordovaLib:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

3) in emulate command: application is not lunch on the emulator even in 4.4.2 android

4) build command generate application   but it not installing on 4.X version of android in devices.

5) emulate command also in not even run in connected devices(4.1.2 and 4.2).

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
OS: Windows 7 SP1
Node Version: v0.10.31</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @rsa408!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3965). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3965)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
These changes are not from ionic, but from cordova.

http://cordova.apache.org/#news

Please review the changes in cordova
