### ISSUE TITLE
bug: align-title attribute not working for <ion-footer-bar>

### ISSUE THREAD

**Issue by style-x7** [driftyco/ionic#3966]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi Ionic Team,

Tried the example: http://ionicframework.com/docs/api/directive/ionFooterBar/

The align-title="left" doesn't affect the title alignment. I'm using Ionic version 1.0.0-rc.4</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @style-x7!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3966). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3966)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by radyz** [comment]
Same thing using v 1.6.1, align-title doesn't have any effect over the tex alignment.

**Comment by TheBosZ** [comment]
I'm using 1.0.1 ( @radyz did you mean 1.0.1?) and seeing the same issue.

**Comment by pauljandrew** [comment]
Same. Using v1.0.0

**Comment by biesbjerg** [comment]
Haven't checked if the fix works, but closes this as well: https://github.com/driftyco/ionic/issues/4263

**Comment by zxs731** [comment]
Same issue.
`<!DOCTYPE html>
<html ng-app="ionic">
<head>
	<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no,width=device-width,height=device-height">
	<script src="ionic.bundle.min.js"></script>
	<link rel="stylesheet" type="text/css" href="ionic.min.css">
</head>
<body>
	<ion-footer-bar align-title="right" class="bar-positive">
		<h1 class="title">ion-footer-bar</h1>
	</ion-footer-bar>
</body>
</html>
`
