### ISSUE TITLE
bug: using "item-remove-animate" with ng-repeat filter causes iOS 7.1 to crash.

### ISSUE THREAD

**Issue by mergin** [driftyco/ionic#3968]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>Filtering a list of messages in my app causes iOS 7.1 to crash (in both emulator and device). In iOS 8.3 this problem doesn't happen. Isolating the problem I just find out that is caused by the animation that occurs when filtering the list, given by item-remove-animate. 

Removing this fixes the problem but I have no animation now.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mergin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3968). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3968)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by objectkuan** [comment]
Absolutely... Such bug drives me crazy...

**Comment by Ionitron** [comment]
Greetings @mergin!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by DrakenZA** [comment]
This issue is still present.
