### ISSUE TITLE
bug: ionic cordova angularjs stateprovider open view is

### ISSUE THREAD

**Issue by DHollenbach** [driftyco/ionic#3971]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.3</span>  <span ionic-webview>webview</span>

<span ionic-description>I am having a strange issue. Which is as follows. On android >= 4.4 and ios my app routes properly but on android 4.3, 4.2.1 and 4.1.2 the view just does not load. The main view works and is functional but I cannot get the other views to load. It's almost like the buttons/tabs does nothing. After exiting the app and coming back it just becomes buggy and the ui becomes unstable.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @DHollenbach!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
