### ISSUE TITLE
bug: IE Edge not rendering tabs correctly

### ISSUE THREAD

**Issue by pedroabreu** [driftyco/ionic#3975]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Tabs in IE Edge (version: 11.0.9600.17843) are rendering on the right side of the screen.

Example: http://plnkr.co/edit/qYMCrt?p=preview</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @pedroabreu!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
