### ISSUE TITLE
bug: No ability to keep right side buttons with back button in ion nav

### ISSUE THREAD

**Issue by christomitov** [driftyco/ionic#3977]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi, I'm trying to get the back button to replace the hamburger when navigating, but also keep the right side menus and buttons active. However the default behavior is to hide all buttons in the nav and place the back button in the left. I tried using enable-menu-with-back-views="true" directive on the ion-side-menus but that keeps all buttons. So is it possible to keep the right side buttons with the back view but have the left side hamburger replaced with the back arrow?

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @christomitov!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3977). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3977)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @christomitov!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
