### ISSUE TITLE
docs: Back buttons for ionic sidemenu pages

### ISSUE THREAD

**Issue by Ajeetlakhani** [driftyco/ionic#3978]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I have following items in ionic side menu list.

Home (contains nested states like books, games,etc.)
Profile
About

By default from profile or about pages there is no back button in nav bar and app exits on using androids hardware back button.

I want Profile and About page to go back to Home on tapping hardware back button (which is the standard way in most apps today) and I would also like to have back button in header nav bar that links to home.

How can I achieve this in ionic?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Ajeetlakhani!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3978). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3978)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by godofrayer** [comment]
That is not issue. why dont you ask in ionic forum?

**Comment by Ionitron** [comment]
Greetings @Ajeetlakhani!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
