### ISSUE TITLE
disable ion-refresher

### ISSUE THREAD

**Issue by ericongkc** [driftyco/ionic#3979]
I have 2 ion-list under 1 ion-content, how do i enable ion-refresher for ion-list 1 but disable on ion-list 2

    <ion-content padding="false" style="margin-bottom:94px">
        <ion-refresher
            pulling-icon="ion-camera"
            pulling-text="Pull to Scan"
            disable-pulling-rotation = "true"
            on-refresh="doRefresh()">
        </ion-refresher>
        <ion-list ng-if="showItemList">
        </ion-list>
        <ion-list ng-if="showColorInput">
        </ion-list>
    </ion-content>

**Comment by Ionitron** [comment]
Greetings @ericongkc!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3979). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3979)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @ericongkc!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by yeswecoin** [comment]
Actually I want to do something similar and need to disable the refresher under certain circumstances. Is there a solution?

**Comment by krvajalmiguelangel** [comment]
I also have a similar situation. Is there any way to disable it?
