### ISSUE TITLE
bug: Collection-repeat image recycling while loading

### ISSUE THREAD

**Issue by JerryBels** [driftyco/ionic#3980]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Following this topic https://github.com/driftyco/ionic/issues/1742 that has been closed by the bot, as you can see there is still a big issue on this, like the last comments shows.

As of right now with v1.0.0, I'm still experiencing the same behavior that you can see in the video I provided on the other topic ( link again : https://www.youtube.com/watch?v=0ZaeD2nlKoA )

If any more feedback is needed, please just ask. I hope this issue will be resolved, since for now collection-repeat can't be used for me.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @JerryBels!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3980). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3980)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by JerryBels** [comment]
bump

**Comment by mhartington** [comment]
Please look at the `item-render-buffer` in our docs. This is a buffer rate that tells collection repeat when to request the image needed. 

http://ionicframework.com/docs/api/directive/collectionRepeat/#api

**Comment by JerryBels** [comment]
Hey @mhartington ! I know about this directive as well, and tried with 

    force-refresh-images="true" item-render-buffer="15"

without success. The issue remains the same as demonstrated in my video - so I guess others could still relate. I will continue looking for a solution on my side though, but any help will be highly appreciated !

**Comment by mhartington** [comment]
Can you provide a demo of this not working?

**Comment by Ionitron** [comment]
Greetings @JerryBels!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
