### ISSUE TITLE
bug: Side Menu slide gesture not working.

### ISSUE THREAD

**Issue by lesliechw** [driftyco/ionic#3981]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>The following is my device test.

Android 4.2.2 - Working Fine
Android 4.2.1 - Working Fine
iOS 8.3 - Working Fine
On Device Chrome Browser - Working Fine

Android 4.4.4 - Not Working
Android 4.4.2 - Not Working</span>

<span is-issue-template></span>

**Comment by aorylamballe** [comment]
+1, I also got this issue on the sidemenu startup template when activating native scrolling (it works well with the default javascript scrolling) on Android.

**Comment by Ionitron** [comment]
Greetings @lesliechw!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
