### ISSUE TITLE
bug: Select not working on device

### ISSUE THREAD

**Issue by clluiz** [driftyco/ionic#3982]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>The select element is not showing the options when I run the app on my phone. I have seen some issues where we need to change a line, but I not finding de corresponding line in my ionic.js. I'm using ionic version 1.0.0.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @clluiz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3982). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3982)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by clluiz** [comment]
It was my mistake. I was using data-tap-disabled="true" in my ion-content. After removed this, the select works fine. 

Sorry!
