### ISSUE TITLE
bug: Single touch generates dual Tap events in Windows 8.1 touch enabled desktop specially for HTML buttons

### ISSUE THREAD

**Issue by AbhijeetMajumdar** [driftyco/ionic#3983]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>
 
<span ionic-description>**Issue detail**
Single touch generates dual Tap events in Windows 8.1 touch enabled desktop. It is mostly happening with HTML Buttons.

**Chrome Timeline captured series of events** 
* touchstart
* touchend
* Click
	* **tap**
* release
* mouseout
* mousemove
* mousedown
* mouseup
	* **tap**

**Culprit** -  *It is failing to honour below condition due to touch_triggered which is false in mouseup. It's working fine in Android.*

 Method name : onTouch
 // onmouseup, but when touchend has been fired we do nothing.
        // this is for touchdevices which also fire a mouseup on touchend
        if(sourceEventType.match(/mouse/) && **touch_triggered**) {
          return;
        }

**Quick fix**
 if(sourceEventType.match(/mouse/) && (touch_triggered **|| tapEnabledTouchEvents**) {
          return;
        }

**Environment:**
**Desktop : Touch Enabled** 
Windows :  8.1

Ionic version	:  **1.0.0**
Google Chrome : 43.0.2357.124 (Official Build) m (32-bit)
OS	Windows 
Blink	537.36 (@196519)
JavaScript	V8 4.3.61.27
Flash	18.0.0.160
User Agent	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36

</span>

<span is-issue-template></span>
</span>

<span is-issue-template></span>
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @AbhijeetMajumdar!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3983). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3983)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Is there anyway you could provide a demo or some code on how I could recreate this?

**Comment by AbhijeetMajumdar** [comment]
I am working in a restrictive environment. I will raise a request to my manger to create a WebEx session for you. Please share your time slot for tomorrow 25/Jun.

**Comment by Ionitron** [comment]
Greetings @AbhijeetMajumdar!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
