### ISSUE TITLE
add prefix to custom mixins

### ISSUE THREAD

**Issue by agustinhaller** [driftyco/ionic#3984]
It would be great if you could add prefixes to custom sass mixins.

For example your "placeholder" mixin has conflicts with bourbon "placeholder" mixin. And obviously yours is a custom use case for a placeholder not a generic implementation like bourbon solution. It should be named differently to prevent conflicts.

``` sass
// Placeholder text
// --------------------------------------------------

@mixin placeholder($color: $input-color-placeholder, $text-indent: 0) {
```

**Comment by Ionitron** [comment]
Greetings @agustinhaller!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3984). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3984)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @agustinhaller!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
