### ISSUE TITLE
perf: Wrong removeEventListener on document

### ISSUE THREAD

**Issue by 85lele** [driftyco/ionic#3985]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The [removeEventListener](https://github.com/driftyco/ionic/blob/master/js/views/scrollView.js#L966) on touchcancel of *scrollView.j* should have as second parameter *self.touchEnd*

The function touchEnd, that not is removed, causes the detached DOM of every scroll view to be kept in memory.

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @85lele!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3985). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3985)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
You're right, great catch. Thanks!

**Comment by perrygovier** [comment]
fixed in d6431a7b975995cf8a7b979bd1712ff098da07f8
