### ISSUE TITLE
bug: Click a input field. whole Webapp jumps down and back to the original place and swipe issue again not solve in new version of ionic "uranium-unicorn"

### ISSUE THREAD

**Issue by smamit27** [driftyco/ionic#3986]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>browser</span>

<span ionic-description>Hello Guys.
 I am facing the issue in my registration page with scrolling issue.
I Commented document.body.scrollTop = 0;
  scrollView.scrollTop = 0; 
but again scroll issue not solve yet.Even i have already update ionic which is the latest one.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @smamit27!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3986). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3986)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by AdrianC9** [comment]
I'm also experiencing this issue. If I try to tap a text area in a scrollable list, the whole list scrolls to the top and the view "freezes". You can no longer move your view. 

Its basically this issue: https://github.com/driftyco/ionic/issues/3727

**Comment by AdrianC9** [comment]
Update

I tried the latest nightly build. Here, when tapping a text area, its brought into view. The view is still frozen. You can't scroll up or down, but at lease the keyboard isn't hiding the text area. That said, this doesn't work that well. It kinda shakes into position and isn't very smooth.

It does cause another issue however. It breaks the scrolling on lists that have on-tap or on-hold on their items. These lists simply never scroll anymore.

**Comment by mhartington** [comment]
Would you be able provide a codepen for testing?

**Comment by sean-hill** [comment]
Hey @mhartington, I have this issue also, but it can only be replicated in the emulator. If you start a new `tabs` project and add a few inputs to a page, and load it up in your emulator, you can see all the bounciness. This happens for me for the latest Ionic version.

**Comment by Deminetix** [comment]
Thanks @sean-hill - i started a new project and forgot to add the disableScroll setting like the previous project :)

**Comment by Deminetix** [comment]
Maybe this should be on by default?

**Comment by sean-hill** [comment]
Yeah, I definitely think so, or at least some Ionic solution to it. It's kinda embarrassing when you're demoing Ionic to someone on the fly, and your app is bouncing all over the place. Kinda ruins how cool Hybrid dev is :smile:

**Comment by mhartington** [comment]
on by default now.

https://github.com/driftyco/ionic-app-base/commit/2e11240fd7ee973bfe14a0c6a80231dfdbc957ee
