### ISSUE TITLE
feat: feat: keep image aspect ratio in item-thumbnail

### ISSUE THREAD

**Issue by alvaromb** [driftyco/ionic#3988]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When using a non-squared image in ``item-thumbnail`` class, the image aspect ratio is not maintained.

![screen shot 2015-06-25 at 13 03 30](https://cloud.githubusercontent.com/assets/289640/8353041/9ba3b01a-1b3a-11e5-8bbc-a647e792ebea.png)

Example:

```html
<a collection-repeat="item in items track by item.id"
  class="item item-thumbnail-left"
  href="#/app/item">
  <img src="img/cactus.jpg">
  <h2>{{item.title}}</h2>
  <p>{{item.price}}</p>
  <p>{{item.detail}}</p>
</a>
```

``cactus.jpg`` is 600x380.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @alvaromb!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3988). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3988)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by paulogr** [comment]
+1

**Comment by comapedrosa** [comment]
+1

**Comment by npetro** [comment]
.fit-thumbnail { object-fit: cover; }

and then add the class to your image thumbnail as a temporary fix

**Comment by comapedrosa** [comment]
Hi!
@npetro solution worked like a charm for me! Nevertheless I used a different property because of my aspect ratio. I leave you this website https://css-tricks.com/almanac/properties/o/object-fit/ where you can find and explanation and a demo of all the properties available! 
Hope you like it!

**Comment by Ionitron** [comment]
Greetings @alvaromb!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by shamilovtim** [comment]
This should be the stock behavior of the component. Reopening.
