### ISSUE TITLE
feat: better handling of apple-mobile-web-app-status-bar-style

### ISSUE THREAD

**Issue by imduffy15** [driftyco/ionic#3990]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi All,

On iOS users have the ability to add web pages to the home screen. If the added web page has a metadata tag of `apple-mobile-web-app-capable` the web page will open in full screen i.e. without the browser UI. This can be nice for giving an app-like feel. 

Extending this, the developer is also able to adjust the status bar style using `apple-mobile-web-app-status-bar-style`. If set to black, the status bar has a black background. If set to black-translucent, the status bar is black and translucent, the web content is displayed on the entire screen, partially obscured by the status bar.

When running in black-translucent mode, things like the headers get in the way of the battery, time, network signal, etc. icons. In order to prevent this one must change the height of the header to 66px and add padding-top of 22px.

It would be nice if we could do some build in detection on window.navigator.standalone to detect iOS home screen web apps, check the value for `apple-mobile-web-app-status-bar-style` and apply some CSS classes to the body accordingly to allow for CSS rules to be applied to fix required elements. 

References:
https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @imduffy15!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3990). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3990)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by imduffy15** [comment]
Adding `platform-cordova` to as a class to the body tag adjusts this nicely.

**Comment by Ionitron** [comment]
Greetings @imduffy15!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
