### ISSUE TITLE
bug: Error: Unexpected request: GET No more request expected

### ISSUE THREAD

**Issue by LeoLR** [driftyco/ionic#3991]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi,

I've some problem with ionic for communicate with my API... 
I try this:

` $http({
                url: '/API_Rest/api.php/user',
                method: 'GET',
                params: { name: name, pass: pw }
 }); `

But this error append: 

>Error: Unexpected request: GET /API_Rest/api.php/user?name=ytj&pass=tyk
>No more request expected
>    at $httpBackend (angular-mocks.js:1211)
>    at sendReq (ionic.bundle.js:18327)
>    at $get.serverRequest (ionic.bundle.js:18043)
>   at processQueue (ionic.bundle.js:21888)
>    at ionic.bundle.js:21904
>    at Scope.$get.Scope.$eval (ionic.bundle.js:23100)
>    at Scope.$get.Scope.$digest (ionic.bundle.js:22916)
>    at Scope.$get.Scope.$apply (ionic.bundle.js:23205)
>    at HTMLButtonElement.<anonymous> (ionic.bundle.js:53457)
>    at HTMLButtonElement.eventHandler (ionic.bundle.js:11713)

I've test with a chrome extension for rest, and the url works!... 

So if anyone have a idea! 

Thank's! </span>

<span is-issue-template></span>

EDIT:
I've add this `$httpBackend.whenGET(/.*/).passThrough();` befor my GET and now i've this error: 
>XMLHttpRequest cannot load http://localhost/API_Rest/api.php/user?name=ezf&pass=ezf. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access.

EDIT 2:
I've found the problem it was on my API, i've to specify the header : header('Access-Control-Allow-Origin', '*')

**Comment by Ionitron** [comment]
Greetings @LeoLR!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3991). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3991)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
