### ISSUE TITLE
bug: iOS: enabledRemoteNotificationTypes not supported

### ISSUE THREAD

**Issue by ohh2ahh** [driftyco/ionic#3992]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I've tried to set up Ionic push in my app. It works great in developer mode with iOS and Android and as well over GCM on Android. But unfortunately I didn't get it working on iOS. It seems that the user identification is successful, but the device registration fails with this error (although an iOS token gets returned and saved on ionic.io):

enabledRemoteNotificationTypes is not supported in iOS 8.0 and later.

Deleting and re-adding the iOS platform and the push plugin didn't help.

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
ios-deploy version: 1.7.0
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.12.4
Xcode version: Xcode 6.3.2 Build version 6D2105</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ohh2ahh!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
