### ISSUE TITLE
bug: Ionic run android my app doesn't work

### ISSUE THREAD

**Issue by LeoLR** [driftyco/ionic#3993]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi, 
When i emulate my app on android or run on my device the app have a problem, i've this: 
http://img11.hostingpics.net/pics/570036SubmitanIonicFrameworkIssueGoogleChrome.jpg
But in the browser i've this: 
http://img11.hostingpics.net/pics/381610LoginGoogleChrome2.jpg

The build logs: 
http://img11.hostingpics.net/pics/716026SubmitanIonicFrameworkIssueGoogleChrome2.jpg

If somenone have a idea! 

Thank's!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @LeoLR!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
