### ISSUE TITLE
perf: ion-option-button occupying space and adding padding to ion-content container

### ISSUE THREAD

**Issue by ravishtiwari** [driftyco/ionic#3994]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi, 
I am having an issue with `<ion-option-button>`, if I add option button inside <ion-item>, it reserves some space for itself, even when it is not visible on screen. 

The use case I have is: I am using `<div class="row"></div>` to display my content, and I've couple of buttons that I need to display when user swipes on individual ion-item. 
However, as soon as I add the `<ion-option-button>` it reserves around 50px space for itself and add 49px padding to container on the right. 

please have a look at following pen to understand the problem: http://codepen.io/ravishtiwari/pen/doJopq 
If I remove all option buttons, this is how it looks : http://codepen.io/ravishtiwari/pen/EjojwQ 

I was looking to implement a local fix for this, but, before that wanted to know if this a known issue?

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ravishtiwari!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3994). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3994)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ravishtiwari** [comment]
I've overridden the default padding values that were added when we add ion-option-button to ion-item.
