### ISSUE TITLE
bug: collection-repeat, dynamic height and data reload

### ISSUE THREAD

**Issue by pamo85** [driftyco/ionic#3995]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://forum.ionicframework.com/t/issue-with-collection-repeat-and-list-dividers-while-loading-data/26841

http://codepen.io/anon/pen/GJMdqX

if you reload data on collection-repeat it scrolls by it self.i think it shouldn't scroll as long as you only update and not insert data.
issue only happens if the first item isn't the highest, otherwise everything works okay.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @pamo85!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
