### ISSUE TITLE
bug: Major $IonicModal Bug. Multiple Modals.

### ISSUE THREAD

**Issue by scripterkaran** [driftyco/ionic#3996]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have re-created this bug in this link: http://play.ionic.io/app/57a39564d962

I have 4 modals.  ReadMore, Comments, Replies, Images. 

If you follow these steps you'll see: 

Situation 1) Open ReadMore Modal. Inside Which there is button to open comment modal. Click On it. Comment Modal opens up. Inside which there is another button. Click on it. 

Now close all the modals. and Open Images Modal (3rd Button), Inside which there is a button to open Comments Modal. Click On It ***It dosent open*** , it does, but it opens behind the currently opened Modal.  <---bug

Situation 2) Open images Modal first , then open comment modal from imagesModal, close all. Then try to open readMore Modal, and from readmore modal open comment modal ----> it wont open<----- it will again ope behind the currently opened modal. 

 

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @promactkaran!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3996). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3996)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by promactkaran** [comment]
A more simplified way to understand the bug, I went through the source files and found out that, when modal is called on click, a <div> with backdrop is appends to the $ionicBody, and these appends are chronological. So when we have four modals, it creates problem as stated above. Since all the .backdrop class has z-index: 10, the modal in the above situations get hidden, it took me a while to go figure that out. Now I have created a Pull request.

**Comment by Ionitron** [comment]
Greetings @scripterkaran!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
