### ISSUE TITLE
bug: Two subsequent modal.show() call causes back button to stop working

### ISSUE THREAD

**Issue by jlisicki** [driftyco/ionic#3997]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>webview</span>

<span ionic-description>Back button doesn't work when I call modal.show() 2 times one after another without modal.hide() between them. This is caused by
```javascript 
      self._deregisterBackButton = $ionicPlatform.registerBackButtonAction(
        self.hardwareBackButtonClose ? angular.bind(self, self.hide) : noop,
        IONIC_BACK_PRIORITY.modal
      );
```
in https://github.com/driftyco/ionic/blob/master/js/angular/service/modal.js : show()
Second "show()" call overwrite self._deregisterBackButton and "hide()" deregister only second callback instead of both.
Workaround in controller app:
```javascript 
if (!modal.isShown()) {
  modal.show();
}
```

Ionic version: 1.0.0</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jlisicki!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3997). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3997)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @jlisicki!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
