### ISSUE TITLE
bug: View title does't update with scopeVariable

### ISSUE THREAD

**Issue by derappelt** [driftyco/ionic#3998]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If you set 
`<ion-view view-title="{{some.title}}"> `
and then update
$scope.some.title in the Controller the view title doesn't update.

If you set:
`<ion-view>`
`  <ion-nav-title>{{some.title}}</ion-nav-title>`
`</ion-view>`
It works. 
So this isn't a big problem but I think the first way looks way cleaner.</span>

<span is-issue-template></span>

**Comment by javiercr** [comment]
I had the same problem with the `view-title` attribute, the `<ion-nav-title>` workaround works for me too.

**Comment by Ionitron** [comment]
Greetings @derappelt!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
