### ISSUE TITLE
perf: Collection repeat memory leak

### ISSUE THREAD

**Issue by 85lele** [driftyco/ionic#3999]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In the destroy function of collection-repeat directive, *computedStyleNode* never has a parent.

Moreover using *removeChild* just detach the node, but it doesn't remove events attached on it (or on childs) by other directives (like ng-click).
This causes the detached DOM of the scroll view to be kept in memory.

If I replace it with `angular.element(computedStyleNode).remove();` all works fine.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @85lele!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by timestep** [comment]
Can this issue be reopened? This seems to be a simple solution to a very common problem, and can provide huge value.

**Comment by yossi-shasho** [comment]
+1
