### ISSUE TITLE
bug: Buttons w/ two lines of text wrap issue

### ISSUE THREAD

**Issue by bassettsj** [driftyco/ionic#4000]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>

[Example Codepen][codepen]

Buttons with longer text will wrap to the next line, which is good, but the `line-height` causes the spacing to be very off.  Using `line-height` to vertically center the text seems to cause this issue. Would be good to find a solution to solve this issue, maybe use padding or flexbox instead.

[codepen]: http://codepen.io/bassettsj/full/BNJKJy/

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @bassettsj!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by Trylar** [comment]
This issue still exist, you can see in example codepen.
