### ISSUE TITLE
feat: Allow initial value for `$ionicPopup.prompt`

### ISSUE THREAD

**Issue by davej** [driftyco/ionic#4001]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>`$ionicPopup.prompt` could handle a lot more use-cases if it accepted an initial value. Currently you need to do `$ionicPopup.show` + template + click handler + scope to do something that could easily be achieved with something like:

```javascript
$ionicPopup.prompt({
   title: 'Email',
   template: 'Enter your email address',
   inputType: 'email',
   inputPlaceholder: 'Your email',
   inputInitialValue: 'my.existing.email@gmail.com'
 }).then(function(res) {
   console.log('Your email is', res);
 });
```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @davej!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4001). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4001)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jskrepnek** [comment]
+1

**Comment by Ionitron** [comment]
Greetings @davej!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by gregallensworth** [comment]
This may be of interest:
https://github.com/gregallensworth/ionic/commit/2d1b2e03dbdb2b3d5933fd428cfb3c944e632e6f
https://github.com/driftyco/ionic/issues/1589

**Comment by davej** [comment]
@gregallensworth :+1:, any luck with a PR?

**Comment by gregallensworth** [comment]
I only opened the PR a couple of hours ago:
https://github.com/driftyco/ionic/pull/4705

It covers this issue, plus a few others.
