### ISSUE TITLE
bug: ionnavbar didn't show up

### ISSUE THREAD

**Issue by liujia1** [driftyco/ionic#4002]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>The code is http://codepen.io/anon/pen/LVzjYj. 
The ionnavbar will disappear after swithing between tabs. 
If i click the vicemap then the mainmap tab, the ionnavbar disappears. I guess it is a bug.</span>

<span is-issue-template></span>

**Comment by lichlj** [comment]
well , i guess someone should update the demo js file. I used a new js ion js file and i think the bug has fixed. http://codepen.io/anon/pen/bdagwW

**Comment by Ionitron** [comment]
Greetings @liujia1!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
