### ISSUE TITLE
bug: ion-view empty value problem

### ISSUE THREAD

**Issue by alexnaldo** [driftyco/ionic#4003]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>A ion-view with an empty view-title doesn't work as expected. Its retain the last title from another view.
If "TabA" have one view "ViewA" without title and you navigate to "TabB" view "ViewB" with title "ABC". When you go back to "TabA" its show "ABC" on the title.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @alexnaldo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4003). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4003)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @alexnaldo!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
