### ISSUE TITLE
bug: Error Swipe in Ionic List

### ISSUE THREAD

**Issue by jdnichollsc** [driftyco/ionic#4004]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi guys!

I'm having errors with the swipe effect on the lists, It doesn't always work. See please: http://codepen.io/jdnichollsc/pen/yNPoYm?editors=0011

Thansk in advance,
Nicholls</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jdnichollsc!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4004). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4004)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by lolporer** [comment]
hi,

as I can see if you use the swipe on an input tag it doesn't work, but if you drag the item it works fine :)

**Comment by jdnichollsc** [comment]
If you drag a div inside the item, the swipe not always works (My mobile android for example) :/

Any help is appreciated, Nicholls

**Comment by Ionitron** [comment]
Greetings @jdnichollsc!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
