### ISSUE TITLE
bug: Footer top border hidden ionic

### ISSUE THREAD

**Issue by alfons12** [driftyco/ionic#4005]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>The problem is described here: http://forum.ionicframework.com/t/footer-top-border-hidden/27304

Actually, the border is not shown for ion-footer-bar and ion-tabs on Android devices whith hi-res displays.

This is my summary:

    the border was hidden because I told developer tools in Chrome to behave like an iPhone 5 which has pixel ratio > 1.5 thus the @media was applied
    when I open the page using --lab the border is shown - it is always shown in the browser
    when I open the app on my Galaxy S3 the border is not shown (ratio > 1.5) - bug??

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @alfons12!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
