### ISSUE TITLE
feat: Swipe-to-go-back: on cancel event

### ISSUE THREAD

**Issue by michielvandergeest** [driftyco/ionic#4009]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>It would be really useful if the swipe-to-right functionality would fire an event when the swipe is canceled (i.e. when the user didn't complete the full swipe and it went back to showing the original view).

Right now we can capture the start event by listening for $ionicView.beforeLeave, but in the docs or the source code I wasn't able to find an event that triggers after a swipe to go back has been canceled. Since an uncompleted swipe to go back it doesn't trigger a new  $ionicView.enter event, we have no way of knowing when this event occurs.

Ideally we would have dedicated events for all states of the swipe to go back: on start, on completed, on canceled, maybe even on paused (when a user holds the swipe still).</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @michielvandergeest!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4009). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4009)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @michielvandergeest!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
