### ISSUE TITLE
bug: $ionicScrollDelegate won't work if used with overflow-scroll = "true" in ion-content

### ISSUE THREAD

**Issue by iDeekshith** [driftyco/ionic#4010]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

                 <ion-tabs>
                         <ion-tab>
                         </ion-tab>
                         <ion-tab>
                                     <ion-content class="has-header has-subheader" overflow-scroll="true" delegate-handle="myScroll" >
                                     </ion-content>
                        </ion-tab>
                </ion-tabs>
<span ionic-description>               

in my controller: I have added $ionicScrollDelegate as dependency and I'm using  
                                  $ionicScrollDelegate.$getByHandle('myScroll').scrollTop(); //To scroll to Top

The above scroll handler is working fine with overflow-scroll disabled. 
With overflow-scroll disabled scrolling is jerky.
Please help me with this issue. 
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @iDeekshith!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4010). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4010)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by iDeekshith** [comment]
can connect to the GitHub with the link provided

**Comment by Ionitron** [comment]
Greetings @iDeekshith!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
