### ISSUE TITLE
bug: Trouble installing Ionic via npm

### ISSUE THREAD

**Issue by michaelgu95** [driftyco/ionic#4012]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>after running ' sudo npm install -g ionic ' , I keep getting this error log:

! System Darwin 14.3.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! cwd /Users/michaelgu
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! path /usr/local/lib/node_modules/ionic/node_modules/cross-spawn/node_modules/lru-cache/README.md
npm ERR! fstream_path /usr/local/lib/node_modules/ionic/node_modules/cross-spawn/node_modules/lru-cache/README.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/ionic/node_modules/cheerio/test/api/manipulation.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

Anyone run into this issue/able to help?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @michaelgu95!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4012). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4012)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
