### ISSUE TITLE
bug: ion-nav inherits from the last ion-nav-view event if there are no specifications there

### ISSUE THREAD

**Issue by emiidee** [driftyco/ionic#4018]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have a slide box with ion-nav-view(s) inside of it. The templates for the sub views do not specify view-title or ion-nav-buttons. The title is blank and the left buttons (see below) from the parent state are not getting shown
```
ion-view(view-title="{{ pet.name }} test", hide-back-button="true")

  ion-nav-buttons(side="left")
    button.button.button-icon.icon.ion-ios-home-outline(ng-click="$state.go('app.main')")

  ion-content(ng-class="{'has-notification': ErrorService.errorMessage}", scroll='false')

    //- Sub-pages
    tab-slide-box(tab="0")
      .tsb-icons
        .tsb-ic-wrp
          a.ion-ios-paw(href="javascript:;")
          a.ion-ios-home(href="javascript:;")
          a.ion-ios-people(href="javascript:;")
          a.ion-medkit(href="javascript:;")

      ion-slide-box(show-pager="false", on-slide-changed="slideHasChanged($index)")
        ion-slide
          .slide-title profile
          ion-nav-view.left-text(name='profile')
        ion-slide
          .slide-title timeline
          //- ion-nav-view.left-text(name='timeline')
        ion-slide
          .slide-title friends
          ion-nav-view.left-text(name='friends')
        ion-slide
          .slide-title medical
          ion-nav-view.left-text(name='medical')
```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @emiidee!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4018). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4018)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @emiidee!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
