### ISSUE TITLE
bug: on Windows, "ionic build android" fails saying it does not find Android SDK

### ISSUE THREAD

**Issue by l2fprod** [driftyco/ionic#4020]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I'm on Windows.

Running "ionic build android" gives:

    [Error: Please install Android target: "android-22".

    Hint: Open the SDK manager by running: W:\software\android\sdk\tools\android.BAT
    You will require:
    1. "SDK Platform" for android-22
    2. "Android SDK Platform-tools (latest)
    3. "Android SDK Build-tools" (latest)]

I confirmed I have android-22 by listing all the targets.

Debugging platforms/android/cordova/lib/check_reqs.js, the line

    if (output.split('\n').indexOf(valid_target) == -1) {

seems to be the culprit. Indeed there is "\r\n" in the output of "android list targets --compact", not only "\n"

In the meantime, I changed it to

    if (output.indexOf(valid_target) == -1) {

Is this a real issue or is there something wrongly configured on my machine?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @l2fprod!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4020). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4020)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by szuzul** [comment]
I have the same issue today, and I successfully fix it. Check if you have 2 or more versions of Android SDK on the machine and that ANDROID_HOME variable in path looks on the one that you update it . 
  
If you run update tool in command line and your   ANDROID_HOME is in path where you need administrator privileges, if you didn't run cmd as admin, you will miss all error messages that stands for unauthorised manipulation of that folder. I'm 100% sure that this is not ionic related.

**Comment by Ionitron** [comment]
Greetings @l2fprod!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
