### ISSUE TITLE
bug: ng-repeat refresh severe issue - replicable

### ISSUE THREAD

**Issue by Whitebeard86** [driftyco/ionic#4025]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello,

I'm running ionic for an Android app and I have a chat zone that needs to be refreshed every time a new message is received (yes, I'm doing $apply() on the async method). The problem is that after I receive the 6th message (this happens every time after the 6th message), the view is not refreshed properly (the divs are there but with white overlay). If I go back to another tab for instance (or call the side menu) and then come back the items are displayed normally (ignore the green boxes please):

![Image of Bug](http://wi2play.com/archives/Group.png)

Code (VIEW): 

```html
<div class="chat-item {{msg.class}}" ng-repeat="msg in chatMessages track by $index | limitTo: 512">
   <div class="chat-avatar" style="background-image:url('{{msg.avatar_url}}')"></div>
   <div class="content">
	<b>{{msg.username}}</b> {{msg.text}}
   </div>
</div>
```

Code (CONTROLLER):

```javascript
function onMessageArrived(message) {
  console.log("onMessageArrived:"+message.payloadString);
  var json = JSON.parse(message.payloadString);
  var msg = new Message();
  msg.avatar_url = json.avatar_url;
  msg.text = json.text;
  msg.username = json.username;
  msg.user = json.user;

  if(msg.user == userInfo.id) {
    msg.class = "me";
  }

  $scope.chatMessages.push(msg);

  $scope.$apply();
  $ionicScrollDelegate.scrollBottom();
};
```
**Notes:**

- This issue does not happen on my machine web browser

Thanks!
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Whitebeard86!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4025). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4025)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Whitebeard86** [comment]
I've changed the element from "div" to "ion-item" and now it works correctly : 

```html
<ion-item class="chat-item" ng-class="msg.class" ng-repeat="msg in chatMessages track by $index | limitTo: 512">
   <div class="chat-avatar" style="background-image:url('{{msg.avatar_url}}')"></div>
   <div class="content">
	<b>{{msg.username}}</b> {{msg.text}}
   </div>
</ion-item>
```

ng-repeat doesn't apply correctly when using divs?

Thanks

**Comment by jskrzypek** [comment]
@Whitebeard86 What are you using to contain the `div`s/`ion-item`s? Are you using an `ion-list`? I think `ion-list` expects/depends on you using `ion-item`s to `ng-repeat` over

**Comment by Ionitron** [comment]
Greetings @Whitebeard86!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
