### ISSUE TITLE
bug: TriggerScrollEnd never called :(

### ISSUE THREAD

**Issue by cedriclombardot** [driftyco/ionic#4026]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

I've seen this function `triggerScrollEndEvent ` https://github.com/driftyco/ionic/blob/d6431a7b975995cf8a7b979bd1712ff098da07f8/js/views/scrollView.js#L434

but seems to be never called how can we get `scrollend` event</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @cedriclombardot!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4026). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4026)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @cedriclombardot!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
