### ISSUE TITLE
bug: Tap to scroll should be disabled when view frozen

### ISSUE THREAD

**Issue by michielvandergeest** [driftyco/ionic#4028]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I found some unexpected behaviour in the tap-to-scroll functionality.

When I 'freeze' a scroll view ($ionicScrollDelegate.freezeScroll([shouldFreeze]), you'd expect that the scroll view is fixed in it's position and that no user interaction would allow the scroll view to become scrollable again, except for those interactions that intentionally unfreeze the scroll view.

But it turns out that by tapping the header of a frozen scroll view invokes the scroll to top functionality (which works) and then resets the frozen state of the scroll view.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @michielvandergeest!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by mlynch** [comment]
Thanks, we ended up making some changes to the scroll to top and native doesn't use freeze, so we won't be merging. Thanks for the PR though!
