### ISSUE TITLE
bug: $http error function not getting called on 401 Unauthorized - only in iOS

### ISSUE THREAD

**Issue by saiy2k** [driftyco/ionic#4031]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

Here is the simple HTTP Call:

        var getURL          =   'http://148.251.54.50:8080/a1solar/ws/com.saksham.crm.getPosts?l=Openbravo&p=openbravo';
        console.log(getURL);

        $http.get(getURL)
        .success(function(data, status, header, config) {
                 console.log('success');
                 console.log(data);
        }).error(function(data, status, header, config) {
                 console.log('error');
                 console.log(data);
        });

With the same code (with right username and password parameters), it works fine and log `success` in all Web, iOS and Android.

But when you change to a wrong username / password combination, HTTP 401 Unauthorized is returned by the server and error function is invoked in both Web and Android. But not in iOS.

In iOS, with wrong username / password combination, the error function is not getting invoked.

I dont use any $http interceptors. Created a sample `tabs` project that demonstrates the Issue @ https://github.com/saiy2k/Ionic-HTTP-Bug/

Exact code @ https://github.com/saiy2k/Ionic-HTTP-Bug/blob/master/www/js/controllers.js

Ionic Info:
Cordova CLI: 5.1.1
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v0.12.4
Xcode version: Xcode 6.1.1 Build version 6A2008a

Discussion in the forums regarding the issue @ http://forum.ionicframework.com/t/http-error-function-not-getting-called-on-certain-scenarios-only-in-ios/26732</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @saiy2k!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4031). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4031)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @saiy2k!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by yesnoj** [comment]
I have a quite different problem, i make an http request (GET) ,it works on Android and go in .success function, instead in iOS goes on .error function.This thing is made me crazy...i don't know why this happen.I'm using interceptor, but i don't think that would be the problem.Please help
