### ISSUE TITLE
feat: RepeatController need exports the shown rows info

### ISSUE THREAD

**Issue by dreamershl** [driftyco/ionic#4035]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Once knowing the current visible rows, the application get chance to optimize the data requests only for the visible rows. This will extremely improve the performance.

Just need add the following functions in the  RepeatController. 

    this.getDimensions = function(index)
    {
      return view.getDimensions(index);
    };

    this.getRenderedItem=function(index)
    {
      return itemsShownMap[index];
    };

    this.getRenderedItemRange = function()
    {
      return [renderStartIndex,renderEndIndex];
    };

Then the application will be able to save the data requests and scroll to the specific row accurately.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @dreamershl!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
