### ISSUE TITLE
bug: ion-tab doesn't really follow ui-sref semantics.

### ISSUE THREAD

**Issue by dreamershl** [driftyco/ionic#4036]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When ion-tab ui-sref is set, instead of relying on the ui-sref itself. ion-tab manipulate the location to simulate the state switching. The issue is ui-sref support non-url parameters. If it is intended, should not use 'ui-sref' to avoid confusing.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @dreamershl!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
