### ISSUE TITLE
bug: Side menu - content gets white after slide

### ISSUE THREAD

**Issue by do-web** [driftyco/ionic#4037]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>I use crosswalk - i have a right side menu, first i open the side menu and open a new view from the side menu, after that i go back to the main view and swipe directly from the left border of the screen right, then the content gets removed it only show white. The top bar is visible only the content is removed</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @do-web!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4037). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4037)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by do-web** [comment]
$ionicConfigProvider.views.swipeBackEnabled(false); quick fix is to disable swipe back that solved the problem

**Comment by SeerUK** [comment]
I'm encountering this issue on iOS currently also. The issue occurs for me when I swipe to go back after moving from a state in one ion-nav-view to a state in another ion-nav-view. A `div.pane` is left behind and stays there until the is forced out of the cache.

Also, when swiping back under those conditions it seems to animate twice.

**Comment by jodybrewster** [comment]
+1 issue on iOS

**Comment by mhartington** [comment]
Do you have an example I could test out on a device? Codepen?

**Comment by Ionitron** [comment]
Greetings @do-web!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @do-web!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
