### ISSUE TITLE
bug: ion-slides become list when navigate away then back

### ISSUE THREAD

**Issue by LunarDevelopment** [driftyco/ionic#4039]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello! 

EDIT: Below is not solved yet, however I have found that if I manually call `$ionicSlideBoxDelegate.update()` by a button press whenI return to the view with the bug, this returns the slides to a pagered styling.
I have an issue which I'm not seeing anywhere else on github/ stack overflow. 

Ive made an sliderbox with ng repeat, which works great, however if I click on a slide it intentionally takes me to a new page (which has a back button). 

If I then go back to the previous page which holds the slider box it has broken its styling and has become a list of slides, stretching the page etc. they are still swipable, however they disappear from the page and leave a white block.

heres the code, then below are the screen prints (tested in gulp serve and on device) 

```html
 <ion-slide-box>
    <ion-slide ng-repeat="item in discovery.discoveredCapsules" >
        <div ng-click="discovery.viewCapsule(item)" class="">
        <img ng-src="{{item.icon.iconUrl}}">
        <h2>{{item.title}}</h2>
        <p>{{item.owner}}</p>
        <p>{{item.birthDateTime | date:'medium'}}</p>
      </div>
    </ion-slide>
</ion-slide-box>
```
```javascript
    vm.discoveredCapsules = Capsules.discoveredCapsules;
```
```javascript 
    vm.getCapsules = function () {
      var rawCapsules = Data.discoveries;
      angular.forEach(rawCapsules, function (capsule) {
        vm.discoveredCapsules.push((vm.createCapsule(capsule)));
      });
    };
```

![image](https://cloud.githubusercontent.com/assets/10709555/8511213/b28ce4e0-2305-11e5-9026-ca13cf056aa1.png)

Becomes: 

![image](https://cloud.githubusercontent.com/assets/10709555/8511214/bf035a6a-2305-11e5-86ed-09d70e493f2e.png)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @LunarDevelopment!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4039). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4039)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by LunarDevelopment** [comment]
Not sure what I've dont but this has fixed itself through my tinkering. 

I wish I had time to recreate the issue and report on the fix for anyone else but I dont at the min, if someone has the same issue just send me a message / comment here and I'll look into it for them.
