### ISSUE TITLE
how to force orientation  landscape?

### ISSUE THREAD

**Issue by shikelong** [driftyco/ionic#4040]
what should I do in  android?

**Comment by Ionitron** [comment]
Greetings @shikelong!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4040). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4040)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by shikelong** [comment]
use the plugin `PhoneGap-OrientationLock`
