### ISSUE TITLE
bug: collection-repeat is incompatible with custom async directive

### ISSUE THREAD

**Issue by RobbinHabermehl** [driftyco/ionic#4042]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I've encountered a lot of difficulties combining `collectionRepeat` with my custom caching directive. In short, this directive downloads an image to the file system and then sets the path to this image as `src` attribute. The problem is that the first item gets copied by `collectionRepeat` before the linking phase, i.e. the caching, completes. Therefore the `src` attribute never gets set, leaving the first image blank.

There's no easy way to resolve this due to the isolated nature of `collectionRepeat`. For now I've created a workaround by watching the first item of a collection with a directive, once it changes it applies the `src` manually:

```
angular.module('app').directive('collectionRepeatFirstImageFix', function($compile, $timeout) {
  return {
    link: function(scope, iElement) {
      var renderImage = function() {
        var firstImage = iElement[0].querySelector('[collection-repeat] img');
        if (!firstImage || !window.cordova) {
          return;
        }
        // Put logic here
        firstImage.onerror = function() {
          firstImage.src = '';
          $timeout(renderImage, 100);
        };
        firstImage.src = 'file:///path/to/image.jpg';
      };
      scope.$watch(function() {
        return scope.collection && scope.collection[0] ? scope.collection[0]._id : null;
      }, function() {
        $timeout(renderImage);
      });
    },
    scope: {
      collection: '=collectionRepeatFirstImageFix'
    }
  };
});
```

HTML:

```
<ion-list collection-repeat-first-image-fix="images">
  <ion-item
    collection-repeat="image in images"
    force-refresh-images="true">
    <img cache-src="{{ image.url }}">
  </ion-item>
</ion-list>
```

Due to the complexity it's hard te create an exact replication of this issue on CodePen. I'd be more than willing to help though by testing any suggestions on my own source code or by disclosing the source code privately to the Ionic team.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @RobbinHabermehl!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4042). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4042)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @RobbinHabermehl!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
