### ISSUE TITLE
bug: slidebox doesnt show anything in rtl mode

### ISSUE THREAD

**Issue by shaulhadar** [driftyco/ionic#4043]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi ionic team. I tried to add a slidebox on rtl mode, but i cant see anything.  when changing to ltr it looks fine, so i guess it is something in ttje rtl code, please fix this, i really want to use slide boxes in my new app :)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @shaulhadar!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4043). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4043)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by shaulhadar** [comment]
any update on this perhaps?

**Comment by Ionitron** [comment]
Greetings @shaulhadar!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
