### ISSUE TITLE
bug: Blank template needs to use has-header in content tag

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic#4044]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The layout tags for the blank template look like so:

    <ion-pane>
      <ion-header-bar class="bar-stable">
        <h1 class="title">Ionic Blank Starter</h1>
      </ion-header-bar>
      <ion-content>
      </ion-content>
    </ion-pane>

But if you put any content inside ion-content, it will be hidden beneath the header. If you add class="has-header" to ion-content, it will show up, and that should probably be there by default</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @cfjedimaster!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4044). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4044)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Just started a blank starter, seems to work fine for me. 

http://codepen.io/mhartington/pen/OVvEGY

**Comment by cfjedimaster** [comment]
Yeah, weird. I'm trying to recreate what I saw now.

**Comment by cfjedimaster** [comment]
Well shoot - I pretty much recreated everything from the other app (it was testing Deploy) and now I can't see it anymore. Maybe a Simulator fluke - I've seen it act up before.
