### ISSUE TITLE
bug: High Processor Usage with SVG Spinners on Android

### ISSUE THREAD

**Issue by cannycookie** [driftyco/ionic#4045]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>We've had batteries draining, phones overheating and unable to charge fast enough. Finally identified as SVG Spinner on loader and pull to refresh making processor usage stick around 25-30%

We were hopeful that 1.0.1 had fixed it but seems not.

Currently removing SVG from dom after $ionicLoading.hide() seems to solve it.

Can anyone suggest how to override ionRefresher directive to remove spinner?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @cannycookie!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4045). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4045)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Sionarch** [comment]
I suggest fixing this like I did in pull request https://github.com/driftyco/ionic/pull/4093

**Comment by cannycookie** [comment]
Great, thank you Eric :-)

**Comment by Ionitron** [comment]
Greetings @cannycookie!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by cannycookie** [comment]
Not resolved.

I have tried this fix from Sionarch but the high processor usage continues.  
It appears that an ion-refresher with a spinner is present when the app loads and is running in the background regardless.  My HTC-M8 android has continuous processor usage around 20% with the above fix and with this code:-
```
<ion-refresher
            pulling-text="Pull down to reload"
            on-refresh="vm.doRefresh()"
            spinner="dots">         
         </ion-refresher>
```

If I change that to spinner="none" the processor usage drops down to <5% once the pages have completed loading.

I have created a workaround for ionicLoading directives by removing the element after the hide fn but that doesn't resolve the ion-refresher case.

**Comment by spyjo** [comment]
I think you should open a new issue if you want your issue to be visible again, like ionitron said ("if you are still experiencing this issue, please feel free to reopen this issue by creating a new one")

**Comment by cannycookie** [comment]
yeah, i read that after posting :-(  This is way down the priority list, we have to launch and it's better to go without a spinner than waste more time on something trivial.  I just hope other people don't waste time trying to workout why their phones are burning up and eating batteries.
