### ISSUE TITLE
bug: Not able to get picture/take photos from camera using ionic cordova in Windows Phone 8.1

### ISSUE THREAD

**Issue by rahmanmca** [driftyco/ionic#4046]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>I was trying to access camera to take picture for upload an image to server, I was getting the following error message

Exception was thrown at line 377, column 9 in ms-appx://dc3be3db.isnapper/www/cordova.js
0x800a139e - JavaScript runtime error: Exception thrown and not caught
Exception is about to be caught by JavaScript library code at line 277, column 29 in ms-appx://dc3be3db.isnapper/www/plugins/org.apache.cordova.camera/src/windows/CameraProxy.js
0x800a139e - JavaScript runtime error: NotFoundError
The program '[1924] WWAHOST.EXE' has exited with code 0 (0x0).

My code was

.controller('MoreController', function ($scope, $state, $ionicModal, localStorage, $cordovaCamera) {
      
   document.addEventListener("deviceready", onDeviceReady.bind(this), false);
  function onDeviceReady() {
      document.addEventListener('takephoto', takePhoto.bind(this), false);
  }
  function takePhoto(){
      var options = {
          destinationType: Camera.DestinationType.FILE_URI,
          sourceType: Camera.PictureSourceType.CAMERA,
      };

      $cordovaCamera.getPicture(options).then(function(imageURI) {
          var image = document.getElementById('myImage');
          image.src = imageURI;
      }, function(err) {
          // error
      });
  }

  $scope.takePicture = function() {
      takePhoto();
  }
}

My HTML was

<ion-view>
  <ion-content>
     <div class="list">
          <a class="item item-icon-right" ng-click="takePicture();">
              <div>Take Picture</div>
              <i class="icon ion-chevron-right icon-accessory"></i>
          </a>
      </div>
  </ion-content>
</ion-view>

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @rahmanmca!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4046). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4046)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @rahmanmca!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by ashutosh-akss** [comment]
issue still exists, i get Javascript runtime error NotFoundError when accessing camera in ionic windows phone 8.1 app

**Comment by VincentLemordant** [comment]
Same issue, I can't launch the camera inside ionic components with windows phone 8.1 .
`<ion-content>
   <div class="item item-body" ng-click="takePicture()">
        <img class="full-image" ng-src="{{imgsrc}}">
    </div>
</ion-content>`
