### ISSUE TITLE
How Disable drag on right menu but not the left menu?

### ISSUE THREAD

**Issue by YaroslavG** [driftyco/ionic#4048]
I have 2 menus, left and right. On the start view I want both menus to be swipe/draggable. But on all other views I don't want the right menu to be draggable. Using $ionicSideMenuDelegate Im only able to disable both menus with canDragContent(false);

What's the Ionic way to accomplish this?

If I use this: 
$ionicSideMenuDelegate.$getByHandle('right-menu').canDragContent(false);

I get this message: 
Delegate for handle "right-menu" could not find a corresponding element with delegate-handle="right-menu"! canDragContent() was not called!
Possible cause: If you are calling canDragContent() immediately, and your element with delegate-handle="right-menu" is a child of your controller, then your element may not be compiled yet. Put a $timeout around your call to canDragContent() and try again.

**Comment by Ionitron** [comment]
Greetings @YaroslavG!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4048). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4048)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @YaroslavG!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
