### ISSUE TITLE
bug: Collection-repeat windows scroll

### ISSUE THREAD

**Issue by aasavad** [driftyco/ionic#4050]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I followed the steps mentioned as per the below url to make collection-repeat work on Windows Phone 8.1 .The height/width looks fine and the the view is populated quickly but I am not able to scroll down to see the full list.

https://github.com/driftyco/ionic/issues/3399#issuecomment-87159525

Can you please advise?

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @aasavad!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4050). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4050)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by godofrayer** [comment]
can you make code pen? make sure your ion content scroll true

**Comment by Ionitron** [comment]
Greetings @aasavad!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
