### ISSUE TITLE
bug: Click and drag scroll not working 

### ISSUE THREAD

**Issue by jdmswong** [driftyco/ionic#4051]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Ionic webapps on my browser do not recognize click and drag scrolling, nor allow scrolling at all.  There is no scroll bar.  Not even the "ionic start myApp sidemenu" "Getting Started" example works.

I'm running the server on Ubuntu 14.04, using Ionic CLI v1.4.5 Version  1.0.1
Viewed on Google Chrome Version 43.0.2357.130

Strangely it works on Internet Explorer 11</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jdmswong!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4051). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4051)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jdmswong** [comment]
It also works in firefox, but not on my V5.1 Nexus 4

**Comment by Ionitron** [comment]
Greetings @jdmswong!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
