### ISSUE TITLE
feat: unit test should generate some code coverage feedback

### ISSUE THREAD

**Issue by thaiat** [driftyco/ionic#4055]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I made a small PR that uses istanbul to generate code coverage from karma
The is usefull when you are developping a new feature, just to be able to see if you have enough unit test

The end result is both in the console after a `gulp karma`:
<img width="911" alt="istanbul1" src="https://cloud.githubusercontent.com/assets/4806944/8560852/6e5cc05c-2525-11e5-84ca-cfccc649742b.png">

as well as in the folder `coverage` (ignored in `.gitignore`) where you can see the istanbul web page:

<img width="1144" alt="istanbul2" src="https://cloud.githubusercontent.com/assets/4806944/8560864/84cce9c0-2525-11e5-973f-81858d441dc8.png">

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @thaiat!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4055). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4055)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
