### ISSUE TITLE
bug: Prevent initial tap on scrolling

### ISSUE THREAD

**Issue by szuzul** [driftyco/ionic#4060]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>
 
When you try to scroll over the list  visual tap effect occur but the page doesn't navigate to another page. 

Example: http://codepen.io/mhartington/pen/qEwYMy

Ionic CLI v1.4.5 Version 1.0.1
Viewed on Google Chrome Version 43.0.2357.130</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @szuzul!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4060). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4060)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @szuzul!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
