### ISSUE TITLE
bug: native scroll does not work  after upgraded to V1.0.1

### ISSUE THREAD

**Issue by yiqinglan** [driftyco/ionic#4064]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Description:
   native scroll for none IOS platform does not respond touch scroll event or simulate touch scroll. 
Condition: 
   .config(function($ionicConfigProvider) {
        if (!ionic.Platform.isIOS()) {
             $ionicConfigProvider.scrolling.jsScrolling(false);
         }
     })
Workaround
    downgrade to V1.0.0</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @yiqinglan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4064). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4064)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by yiqinglan** [comment]
thank you. done.

**Comment by animungo** [comment]
+1

I noticed the same on my older test device (also android 4.4 webview).
I just tested it with a downgrade to Ionic version 1.0.0 and then it works again.
With the 1.0.1 version I can start scrolling but once it stops I can not scroll further.

I watched for any errors being raised in the console but there were none.

**Comment by JoeyHoutenbos** [comment]
+1

Downgrading to version 1.0.0 solved the problem..

**Comment by jskrzypek** [comment]
Check out my fix in #4008 and see if it works for you.

**Comment by PaperMonster** [comment]
I had the same issue and the fix in #4008 solved it.

**Comment by skoczen** [comment]
@jskrzypek if we're ever in the same city, I'm buying you a beer.  Your workaround just saved our release.

**Comment by jskrzypek** [comment]
@skoczen :beers: a) what city is that, and b) @ghaiat deserves the credit more than I do since he found the bug, I just made the issue :wink:

**Comment by skoczen** [comment]
@jskrzypek, at the moment, Puerto Escondido, Mexico - but it changes about every three months.  

:beers: to you both, then. :)

**Comment by mhartington** [comment]
This should be fixed in the nightly builds

**Comment by ericmasiello** [comment]
Does anyone know if this bug was ever fixed in a newer release of Ionic?
