### ISSUE TITLE
bug: canvas.addEventListener touchmove doesn't work

### ISSUE THREAD

**Issue by ablegao** [driftyco/ionic#4067]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a ion-view : 

    <ion-view view-title="战斗" can-swipe-back=false >
	<ion-content scroll="false" >
	<canvas  style="min-height:100%;width:100%;"  id="canvas" ></canvas>
	</ion-content>
   </ion-view>

In my contoller . 

     var canvas  = document.getElementById("canvas");
     canvas.addEventListener("touchmove",$scope.touchmove,false);
     canvas.addEventListener("touchstart",$scope.touchmove,false);
     canvas.addEventListener("touchend",$scope.touchmove,false);

     $scope.touchmove=function(){

            console.log("YES")
      }

But , this doesn't work ,</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ablegao!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4067). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4067)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
