### ISSUE TITLE
bug: Having controller scope property called "direction" breaks scrolling.

### ISSUE THREAD

**Issue by nhfruchter** [driftyco/ionic#4068]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Having a `$scope.direction` property in a controller for a view will break vertical scrolling. Reproduced on Codepen with the latest Ionic nightly: http://codepen.io/anon/pen/OVZjZg?editors=101

It seems like any defined value of `$scope.direction` does it. For example, scrolling breaks with `{}`, `""`, `1`, and `"test"`. However, `undefined`, `null`, and `0`, don't break scrolling.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @nhfruchter!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4068). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4068)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @nhfruchter!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
