### ISSUE TITLE
bug: Windows Phone not correctly detected via ionic.Platform.isWindowsPhone()

### ISSUE THREAD

**Issue by PhilHannent** [driftyco/ionic#4070]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I am working on getting my App ported to the wp8. However when trying to debug a Windows Phone specific issue I tried to use the ionic.Platform.isWindowsPhone() function. 

However this returns false, and actually returns true for isAndroid. The Cordova device.platform reports as "android" as well.

Looking at the code:
https://github.com/driftyco/ionic/blob/master/js/utils/platform.js#L247

And the User Agent string the device is reporting:
    Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 735) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537

I see the problem. My Lumia 735 is claiming its ALL three devices. Effectively making it useless. Any chances you could make the "Windows Phone" check the first in the list?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @PhilHannent!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4070). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4070)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Hmm, so even using the raw cordova plugin returns android?

**Comment by PhilHannent** [comment]
On Lumia 735 the `device.platform` returns `Win32NT`

**Comment by Ionitron** [comment]
Greetings @PhilHannent!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
