### ISSUE TITLE
docs: Link to source/docs is broken for $ionicAnimation

### ISSUE THREAD

**Issue by amosrivera** [driftyco/ionic#4071]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://ionicframework.com/docs/api/service/$ionicAnimation/

Broken link: https://github.com/driftyco/ionic/tree/master/js/angular/service/animation.js#L2

I guess it's related to the removal of $ionicAnimation.
https://github.com/driftyco/ionic/issues/1966</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @amosrivera!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4071). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4071)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Closing as it is the same as #1966
