### ISSUE TITLE
bug: ion-nav-view animations not working

### ISSUE THREAD

**Issue by mirata** [driftyco/ionic#4074]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I've noticed that in the latest ionic builds, my ion-nav-view no longer animates. 

I have made a codepen on the issue.
http://codepen.io/anon/pen/waXwpE

When you click sign in, no transition occurs. If you change the version of ionic at the top to beta 13, it works

I resolved this by modifying the javascript.

I modified ionic.bundle.js: 
- provider.transitions.views.ios
- provider.transitions.views.android

The code needs to take the states 'enter' and 'exit' as well as the existing 'forward' and 'back' states. Because the ion-nav-view had an unrecognised state, it was being set to shouldAnimate = false.

I hope this makes sense :) </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mirata!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4074). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4074)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mirata** [comment]
As a followup, I have made a codepen on the issue.
http://codepen.io/anon/pen/waXwpE

When you click sign in, no transition occurs. If you change the version of ionic at the top to beta 13, it works

**Comment by mhartington** [comment]
This was a big change in ionic from beta 13 to beta 14, what happened quite some time ago. The issue in general is a limitation of UI-router at the moment. Please see #2997
