### ISSUE TITLE
Popus showing  on running app on device chrome browser ( processMessage failed: invalid message: "")

### ISSUE THREAD

**Issue by geek-bhuvnesh** [driftyco/ionic#4077]
I am stick with one Issue..my ionic app perfectly working through android.debug.apk in androide device and desktop browser but when i am runing it through device(android) chrome browser..It showing continunous popups during application Launch;

  ": gap_init:2 gap:[0,"StatusBar","_ready","StatusBar1593157203"] gap:[0,"App","show","App1593157204"] gap:[0,"File","requestAllPaths","File1593157205"] gap:[0,"NetworkStatus","getConnectionInfo","NetworkStatus1593157206"] gap:[0,"Device","getDeviceInfo","Device1593157207"]"

  And in terminal(cmd) : log  processMessage failed: invalid message: "" (infite no of times).

I donot want's popups

**Comment by Ionitron** [comment]
Greetings @geek-bhuvnesh!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4077). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4077)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @geek-bhuvnesh!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
