### ISSUE TITLE
bug: bug: slidebox does-continue not works on ios

### ISSUE THREAD

**Issue by Demonlovemoon** [driftyco/ionic#4080]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello, I am Chinese , my  english is poor.  I will try my best to explain my question.
I used ionic to develop a software.

 I used method  $ionicSlideBoxDelegate.update() after setting slides, the 'does-conitnue = true' can not works on ios,  but it can work on android.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Demonlovemoon!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4080). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4080)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @Demonlovemoon!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
