### ISSUE TITLE
collection-repeat $index not correct in nested repeats

### ISSUE THREAD

**Issue by parkotron** [driftyco/ionic#4081]
http://codepen.io/anon/pen/xGzrdX?editors=101

As is this will log:
slide:0, index:0
slide:0, index:1
slide:0, index:2
slide:1, index:0 ... etc

If at line 23 
`<div ng-repeat="source in category_sources" item-height="0">`
you change the ng-repeat to collection-repeat you end up getting the $index from what I would consider to be the parent scope (in this case the indexes will always be 0 or 1)

**Comment by Ionitron** [comment]
Greetings @parkotron!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4081). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4081)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by parkotron** [comment]
Ok well im not doing that so nevermind
