### ISSUE TITLE
bug: ng-model does not work with <input> inside <ion-nav-title>

### ISSUE THREAD

**Issue by 5amfung** [driftyco/ionic#4083]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Here is a snippet where I have an `<input>` inside `<ion-nav-title>`.  Accessing `$scope.query` from the controller doesn't work unless I changed the the `ng-model` below from `"query"` to `"$parent.query"`.

    <ion-view>
        <ion-nav-title>
            <div class="bar item-input-inset">
                <label class="item-input-wrapper">
                    <i class="icon ion-search placeholder-icon"></i>
                    <input type="search" placeholder="Search" ng-model="query">
                </label>
                <button class="button button-clear">
                    Cancel
                </button>
            </div>
        </ion-nav-title>

    <ion-content>...</ion-content>

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @5amfung!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4083). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4083)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by 5amfung** [comment]
Never mind it.

https://github.com/angular/angular.js/wiki/Understanding-Scopes
