### ISSUE TITLE
bug: Freezing $ionicScrollDelegate still has bouncing effect

### ISSUE THREAD

**Issue by aberman** [driftyco/ionic#4085]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>There seems to be an issue whereby if you call freezeScroll() or freezeAllScrolls() on the $ionicScrollDelegate, it still has the bouncing effect.  I'm not sure if this is as designed or not, but if you're freezing the scrolling, you're effectively disabling the scroll altogether, and I would expect the bouncing effect to also be "frozen" until the scroll is unfrozen.  Does that make sense?  Is there a workaround to disable the bouncing dynamically?

Thanks!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @aberman!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4085). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4085)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by aberman** [comment]
I did find a way to disable the bouncing dynamically by using .getScrollView().options.bouncing = [true|false], but, regardless, this seems like a bug to me, as the freeze should do this for me.

**Comment by Ionitron** [comment]
Greetings @aberman!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
