### ISSUE TITLE
bug: History wrongly switches between different history stacks 

### ISSUE THREAD

**Issue by fhoring** [driftyco/ionic#4086]
In the following [codepen](http://codepen.io/anon/pen/GJGXvJ) for the sequence Facts => OtherPage => OtherPage1 => ReturnToTabsHome the back button is not displayed and the $ionicHistory.goBack command wrongly switches to a different history stack.

I am using a root history stack and then 3 history stacks for each tab page.

When one has previously been on the TabHomePage (sequence Facts => Back => OtherPage => OtherPage1 => ReturnToTabsHome) it is working (it goes to special case in history.js line 254)

Issue seems that the backviewId in history.js line 357 is wrongly assigned. 

Can you review the suggested fix ? It is working for my usecase.

**Comment by Ionitron** [comment]
Greetings @fhoring!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4086). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4086)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @fhoring!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by gfox1984** [comment]
This has not be fixed (the guy who logged the bug seems to have given up and forked ionic to solve his pb)! Please reopen!
