### ISSUE TITLE
docs: No Documentation For Publishing iOS Apps

### ISSUE THREAD

**Issue by adriangordon1231** [driftyco/ionic#4090]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>Just noticed that there is no documentation for publishing ios apps ... only Android.

Page: http://ionicframework.com/docs/guide/publishing.html
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @adriangordon1231!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4090). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4090)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by saniyusuf** [comment]
This is not an Ionic problem this is documented on IOS site or on stack overflow. w

**Comment by mhartington** [comment]
There is an open issue for this on the ionic-site repo. Just need to find time to do them. If anyone wants to make a PR, we could speed up the process

**Comment by adriangordon1231** [comment]
Did not know that there was an ionic site repo. Sorry. @mhartington
