### ISSUE TITLE
bug: Ionic doesn't cache tab subviews

### ISSUE THREAD

**Issue by madvas** [driftyco/ionic#4096]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Please see this [CodePen](http://codepen.io/anon/pen/dojOOY?editors=101). It's basic tabs example.
In the first tab I have list of facts. After tapping on a fact it opens a fact detail. I want to cache this fact detail page, but `<ion-view cache-view="true"` doesn't help.

Is this a bug, or am I missing something? 

Thanks
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @madvas!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4096). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4096)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @madvas!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
