### ISSUE TITLE
bug: Cannot load video file URL into view while running on device through ionic command

### ISSUE THREAD

**Issue by reesretuta** [driftyco/ionic#4097]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>1) I run my app using "ionic run ios --device --livereload" on a connected iPhone 6
2) my app uses the cordova camera plugin to open device Photo Library of videos and user selects video
3) I am able to properly console log the video file URL response, however when I try to bind that to my view such as <video><source ng-src="{{video_url}}" type="video/mp4"/></video>
4) I get this error

```
7     313600   error    Error: [$interpolate:interr] Can't interpolate: {{video_url}}
Error: [$sce:insecurl] Blocked loading resource from url not allowed by $sceDelegate policy.  URL: file:///private/var/mobile/Containers/Data/Application/8C38A9CE-2D9C-469F-9A71-80CDC7B30A72/tmp/trim.84D641A6-61B0-47B4-9161-C424E6187FC7.MOV
http://errors.angularjs.org/1.3.13/$sce/insecurl?p0=file%3A%2F%2F%2Fprivate%2Fvar%2Fmobile%2FContainers%2FData%2FApplication%2F8C38A9CE-2D9C-469F-9A71-80CDC7B30A72%2Ftmp%2Ftrim.84D641A6-61B0-47B4-9161-C424E6187FC7.MOV
```

IMPORTANT: This only happens when running the app via the command in #1 above... building and then running the app on the device through Xcode does NOT produce this error.  In fact properly binds and displays the video file to the view</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @reesretuta!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4097). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4097)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @reesretuta!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
