### ISSUE TITLE
bug: Cursor appears over header when keyboard opens.

### ISSUE THREAD

**Issue by castillobg** [driftyco/ionic#4101]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>On a comment view, my app has a large textarea that takes up most of the space of an iPhone 5 screen. When tapped on, it triggers the appearance of the keyboard, and scrolls up automatically. This causes the cursor to appear over the header, as can be seen in the image below, top left.
Note: I have ``cordova.plugins.Keyboard.disableScroll(true);`` in my ``$ionicPlatform.ready()`` callback.
![988b713ef182f577e1445359c01726edfdca96189bb8fe47d0pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/2333119/8755411/5f529e34-2c90-11e5-8bce-a9df8e484363.jpg)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @castillobg!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4101). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4101)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @castillobg!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by dianazzz** [comment]
Still have this issue in IOS

Here is my ionic info

Cordova CLI: 7.1.0
Ionic Framework Version: 1.3.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.2
ios-sim version: 6.1.2
OS: macOS Sierra
Node Version: v6.11.0
Xcode version: Xcode 9.1 Build version 9B55

Installed platforms:
  ios 4.5.4

**Comment by shishirkumarm** [comment]
I am facing similar issue in my application. Do we have a fix for this ?
