### ISSUE TITLE
feat: Slidebox does not allow fine grained control over events

### ISSUE THREAD

**Issue by jasdeepkhalsa** [driftyco/ionic#4104]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>## Problem
As a user of the slidebox I do not have any control over what happens when the slidebox:
* Initializes/loads
* Goes to the next or previous slide via touch or mouse
* Goes to the next or previous slide via the API `$ionicSlideBoxDelegate.next()` or `$ionicSlideBoxDelegate.previous()`

My particular use case is that I am loading a lot of slides, close to 450 in one go. At this scale a number of performance concerns arise:
1. `ng-repeat` no longer works performantly on mobile. Ionic's `ng-collection` could be used, but it's too strongly based around viewport
2. You want to make use of one-time bindings (::) as much as possible if you can
3. You want to feed the data slowly in chunks (but therefore won't be able to use one-time bindings as the data is constantly changing)

In order to achieve this in slidebox, I need to be able to feed in extra data when it's required anytime I go to the next or previous slide. In fact, each time I change the slide I am checking whether I need new data or not. If I need it, the new data should be loaded in by the time the slide transition has completed. For this I require fine-grained control over the events I mentioned.

## Solution
I have implemented a new attribute in slidebox called `on-handlers` (referenced as `onHandlers` inside Angular) which takes an object of event handlers, which include the following along with their parameters:
* $scope.myHandlers = {};
* $scope.myHandlers.onLoadStart = function(index, length, slides) { ... };
* $scope.myHandlers.onTouchStart = function(event, index, length, slides) { ... };
* $scope.myHandlers.onTouchEnd = function(direction, event, index, length, slides) { ... };
* $scope.myHandlers.onPrevStart = function(index, length, slides) { ... };
* $scope.myHandlers.onPrevEnd = function(index, length, slides) { ... };
* $scope.myHandlers.onNextStart = function(index, length, slides) { ... };
* $scope.myHandlers.onNextEnd = function(index, length, slides) { ... };
* $scope.myHandlers.onLoadEnd = function(index, length, slides) { ... };

In the template, the object of event handlers is simply added as the value of the attribute 'on-handlers' e.g.

	<ion-slide-box on-slide-changed="slideHasChanged($index)" show-pager="false" on-handlers="myHandlers">
	  <ion-slide ng-repeat="item in data">
        ...
	  </ion-slide>
	</ion-slide-box>

This way additional event handlers can easily be added over time and the code remains readable, simple and extensible.

I would like some feedback on whether this approach I have taken is the best one for slidebox, as I am only able to consider my particular use case and there may be other advanced use cases for which this feature can be fine-tuned for.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jasdeepkhalsa!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4104). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4104)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @jasdeepkhalsa!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
