### ISSUE TITLE
bug: updating to ionic 1.01 and cli 1.6.1 breaks ionic serve

### ISSUE THREAD

**Issue by alexweber** [driftyco/ionic#4108]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>All of a sudden `ionic serve` stopped working and serves up a blank page.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @alexweber!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4108). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4108)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by alexweber** [comment]
Update: I thought this may be related to the fact that I had switched to iojs using nvm but switching back to 0.12 doesn't fix it...

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-cli#529
