### ISSUE TITLE
bug: $ionicHistory should respect $state.go location: 'replace' option

### ISSUE THREAD

**Issue by artlogic** [driftyco/ionic#4109]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When moving from view to view using `$state.go`, it's possible to add a option to replace the current location with the location we're going to, rather that putting it on the history stack. For example:

```javascript
$state.go('app.logout', null, {location: 'replace'});
```

Ideally, if this option is passed to `$state.go`, `$ionicHistory` should replace as well. As it stands today, it simply pushes the last address onto the stack.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @artlogic!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4109). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4109)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @artlogic!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by zenkalia** [comment]
this is still an issue :crying_cat_face: :+1: :crying_cat_face:

**Comment by artlogic** [comment]
@zenkalia - I wasn't able to verify it was still an issue (I found an alternate solution) after the ticket was auto-closed. I'd love to see this get fixed. If you could submit a new issue (as suggested above), I would appreciate it. Maybe it'll get someone's attention this time around.

**Comment by zenkalia** [comment]
i might just do that if i haven't solved this tomorrow...

what alternative solution did you use? this one?:
https://github.com/driftyco/ionic/issues/1287#issuecomment-63248366

i'm using a side menu and am having trouble pulling in `$ionicHistory` to
use that hack. :\

**Comment by artlogic** [comment]
In my particular case, I was able to get away with simply blowing away all history:

```javascript
$ionicHistory.nextViewOptions({ historyRoot: true });
```

I'm surprised you aren't able to inject `$ionicHistory`. Is there a circular dependency problem?
