### ISSUE TITLE
bug: ion-option-button duplicated by with ng-if

### ISSUE THREAD

**Issue by AGrzes** [driftyco/ionic#4110]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>When I show and hide ion-option-button with ng-if it gets duplicated each time the condition is fulfilled. See
http://codepen.io/AGrzes/pen/eNjbYv

Tested on Firefox 39 and Chromium 43</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Why not instead just disable swiping? 

http://codepen.io/mhartington/pen/OVoVLX

**Comment by AGrzes** [comment]
Disabling swiping only works for whole list but not on the item level. 
See slightly more complicated example
http://codepen.io/AGrzes/pen/zGJzPq
Here the presence or absence of buttons is driven by data (on the item level) and it is changing in response to user actions.

**Comment by macrog** [comment]
you need to get rid of the span element and put the ng-if directly on ion-option-button

http://codepen.io/macrog/pen/LVqKRM

**Comment by Ionitron** [comment]
Greetings @AGrzes!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by Shadowstep33** [comment]
I had this bug occur and found what I was doing wrong. 

```

				<div>
				    <ion-option-button></ion-option-button>
				</div>
```

but removing the div so I now have


```

				<ion-option-button></ion-option-button>
```

fixed it
