### ISSUE TITLE
bug: has-header overwritten by pane

### ISSUE THREAD

**Issue by irthos** [driftyco/ionic#4111]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Looks like the has-header class `top:44px` properties are overwritten by the pane class `top:0`
I've slapped style="top:44px" on all content boxes for now.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @irthos!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4111). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4111)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Where are you seeing this? Please provide a codepen demo

**Comment by Ionitron** [comment]
Greetings @irthos!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
