### ISSUE TITLE
bug: Ionic View App doesn't work with cordovaSocialShare

### ISSUE THREAD

**Issue by JakeSchieber** [driftyco/ionic#4112]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello, I am not sure if this is the right forum to share this issue or if I should submit it to another part of Ionic support, but I have noticed an issue with ngCordova SocialShare plugin when using the ionic view app. The code works perfectly well with the iOS simulator and when using Xcode to install the project on an iPhone directly. But when using the ionic view app on an iPhone the cordovaSocialShare functions seem to give no apparent response. 

As I am hoping to continue using the Ionic View app I am hoping that you will be able to help.

Thanks</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @JakeSchieber!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4112). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4112)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by saniyusuf** [comment]
It is normal for plugins to not work in the view app. Im not sure the social share plugin is suported

**Comment by mhartington** [comment]
Ionic View does not support the social share plugin
http://docs.ionic.io/docs/view-usage

**Comment by JakeSchieber** [comment]
OK awesome thanks. Thanks for telling me. I will make note of that in future testing.

Thanks again,
Jake
