### ISSUE TITLE
feat: Define constants for Ionic events

### ISSUE THREAD

**Issue by gmarziou** [driftyco/ionic#4113]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It would be great to have angular constants defined for all ionic events like '$ionicView.beforeEnter', this way IDEs could auto complete and users would avoid spelling errors.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @gmarziou!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4113). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4113)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
If you're up for making a PR, we could review it and see if it make sense to add it.

**Comment by gmarziou** [comment]
I would prefer that you tell me if it makes sense before I work on the PR or maybe my proposition is not clear enough?

**Comment by mhartington** [comment]
For me, I'm not sure if this is some thing we would **need**. Is this something that only webstorm would be able to benefit from? Or could editors like sublime, atom, or code benefit form this too? 

Other options I'm interested in is ionic v1 typescript definitions, this seems like something could be more beneficial IMO. If you could provide some info about how adding consts would be more beneficial, that would be great.

**Comment by gmarziou** [comment]
Thanks for the explanation.
