### ISSUE TITLE
bug: Slidebox did not display correctly on last build

### ISSUE THREAD

**Issue by thomas-tran** [driftyco/ionic#4114]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I've used slide box with ng-repeat for about 50 records in the sidemenu starter. I usually end up with only 49 records displayed on the screen even though the pager shown as 50. </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @thomas-tran!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4114). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4114)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Please provide a codepen demo.

**Comment by thomas-tran** [comment]
I've fixed the issue, it was the problem with the list filter.
