### ISSUE TITLE
feat: Get the scroll position of an item in collection-repeat

### ISSUE THREAD

**Issue by miguelfermin** [driftyco/ionic#4115]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

We are working on a story reader app which uses a collection-repeat for a dynamic long list of items (stories). A core feature of our app is the ability to swipe through stories within the detail view.

We would like to be able to get the scroll position of the selected item so that when we return to the master list, the scroll position corresponds to the last item accessed by swiping.

Something like the getDimensions(index) https://github.com/driftyco/ionic/blob/master/js/angular/directive/collectionRepeat.js#L475 would be nice.

Thanks!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @miguelfermin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4115). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4115)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
If your up for it, PRs are alway welcomed :grin:

**Comment by Ionitron** [comment]
Greetings @miguelfermin!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
