### ISSUE TITLE
bug: $ionicUser.identify problem. 

### ISSUE THREAD

**Issue by tigrus** [driftyco/ionic#4117]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Doing: 
```
    $ionicUser.identify({ 
        'user_id':$ionicUser.generateUUID(); 
    })
```
Getting 403 error: 
```
   {"detail":"CSRF Failed: CSRF token missing or incorrect."}
```

After setting CSRF from cookies to header X-CSRFToken getting 405 error:
```
   {"detail":"Method \"POST\" not allowed."}
```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @tigrus!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4117). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4117)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-service-core#20
