### ISSUE TITLE
bug: Slidebox view bug with two slides

### ISSUE THREAD

**Issue by nitrotm** [driftyco/ionic#4119]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In the slidebox view in continuous play mode and if there are only two slides, a copy is made around line 59 of js/views/sliderView.js:

    element.appendChild(slides[0].cloneNode(true));
    element.appendChild(element.children[1].cloneNode(true));

It seems that doesn't work if the slide's content is dynamic (ie. based on a custom directive for instance). In my case, I have a custom image loader directive with a spinner during network request. This doesn't work properly as only the html is copied and not the angular logic bound to the html fragment.

I think the slide's content need to be cached before angular compilation and compiled anew for each slide's clones (first/last).</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @nitrotm!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4119). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4119)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by cielz** [comment]
The issue could also be reproduced on my side. And I noticed there's a similar issue https://github.com/driftyco/ionic/issues/2336 submitted long ago.

**Comment by mhartington** [comment]
I just reopened #2336, let's move the discussion over there.
Closing this for now.
