### ISSUE TITLE
How to scroll full page with ionic?

### ISSUE THREAD

**Issue by LuckyKarin** [driftyco/ionic#4126]
Hi, I'd like to know is there any way to scroll full page with ionic like jQuery Scrollify?http://projects.lukehaas.me/scrollify/#home

**Comment by Ionitron** [comment]
Greetings @LuckyKarin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4126). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4126)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by promactkaran** [comment]
look into <ion-slide-box> and <ion-slides> , with width 100% and height 100% you can achieve what you desire.

**Comment by mhartington** [comment]
Not in ionics internal. This would be a question for forum rather than an issue. Closing.
