### ISSUE TITLE
ionic setup sass error

### ISSUE THREAD

**Issue by thonythony** [driftyco/ionic#4130]
When I create a new blank project and I type the command "ionic setup sass"
```
module.js:338
    throw err;
          ^
Error: Cannot find module 'orchestrator'
    ....

Error running gulp sass
```
Exception with  (CLI v1.6.1)

Your system information:

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.1
Ionic CLI Version: 1.6.1
Ionic App Lib Version: 0.3.3
ios-deploy version: 1.4.0 
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.0
Xcode version: Xcode 6.4 Build version 6E35b 

Someone can help me please ?

**Comment by Ionitron** [comment]
Greetings @thonythony!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4130). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4130)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Hmm, it could have been an hiccup on npm's side. Just gave it a try and everything seems to be working fine for me. Could you try again

**Comment by Ionitron** [comment]
Greetings @thonythony!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
