### ISSUE TITLE
perf: Modal is not working

### ISSUE THREAD

**Issue by hojinshin** [driftyco/ionic#4134]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I've used 3 modals in my whole code. but only this modal is not working.
When I press the 'etc' button, it is clicked, but anything is happened. 
What is the problem? I think I've checked 'z-index' as well.
Here is my code. 

![modal](https://cloud.githubusercontent.com/assets/8757013/8845032/35732a14-3156-11e5-9492-c204fae92bca.PNG)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @hojinshin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4134). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4134)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Could provide a codepen showing the issue

**Comment by Ionitron** [comment]
Greetings @hojinshin!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @hojinshin!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
