### ISSUE TITLE
feat: Additional gesture directives

### ISSUE THREAD

**Issue by sebakerckhof** [driftyco/ionic#4135]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The onGesture function in utils/events.js says it supports all hammerjs 1.x event types, including pinch, rotate, etc. This is used by the $ionicGesture service which in its turn is used to define the gesture directives. However, there are no directives for transformations as pinch and rotate.

Is there a reason for this or could I just add these event types to the GESTURE_DIRECTIVES list in directive/gesture.js?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @sebakerckhof!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4135). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4135)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
I think that some of these event were not included because they could cause conflicts with tap.js or our scrolling. Will investigate.

**Comment by mhartington** [comment]
At the moment, some of these gestures would conflict with tap.js , so I'm hesitant to add any more gesture directives. But the api is still available to make your own, so the functionality can still be there.
