### ISSUE TITLE
bug: Activator don't activate items if they're too far to the left

### ISSUE THREAD

**Issue by possan** [driftyco/ionic#4136]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Since the introduction of the iOS Swipe to go back, when clicking on the back button a bit too far to the left, between pixel 1 and 29 (not 0), it will not fire the activation animation on any platform.

See: https://github.com/driftyco/ionic/blame/master/js/utils/activator.js#L13

I'd happily send in a patch but since the configuration for this flag `$ionicConfig.views.swipeBackEnabled()` happens in angular land and - i don't really know how to patch that, maybe a platform check would be good enough to begin with...

Also, why does hitX need to be `> 0` and not `>= 0` is there a reason for the first pixel to be ignored? 
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @possan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4136). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4136)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
@adamdbradley would be able to better explain this.

**Comment by Ionitron** [comment]
Greetings @possan!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
