### ISSUE TITLE
bug: Flex display breaking Header bar buttons

### ISSUE THREAD

**Issue by ravishtiwari** [driftyco/ionic#4137]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

I am using custom SVG icons for displaying navigation buttons in header, such as menu button, or the back button.
I want to vertically align the buttons and I thought of using display flex for same, however, trying to use display flex for header buttons breaks the header bar buttons.

Here is code pane explaining the problem:
http://codepen.io/ravishtiwari/pen/VLGjbz3

I am not sure why it's creating a problem. Why changing a display property is making navigation buttons go haywire?

Regards,
Ravish</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ravishtiwari!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4137). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4137)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
You codepen is 404ing. Could please provide a valid link.

**Comment by ravishtiwari** [comment]
Hi @mhartington sorry for delayed response, I am not sure what happened to has pen, this is the pen illustrating the problem http://codepen.io/ravishtiwari/pen/OVBqzQ 
Click on 'Go to Info page button' to see the problem in action. 
BTW, I was using svg icons, so, I thought problem might be related to using svg icons, but, when I created the pen, I realized that's it has nothing to do with my SVG icons.

**Comment by mhartington** [comment]
Your codepen is referencing ionic 0.9.27, the latest release is 1.0.1.

Please update your codepen.

**Comment by Ionitron** [comment]
Greetings @ravishtiwari!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
