### ISSUE TITLE
bug: Bug in dialog and modal when ones appear after another

### ISSUE THREAD

**Issue by LTroya** [driftyco/ionic#4139]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>

<span ionic-description>Hi. I am having troubles when I have a dialog in the screen and after appear a modal. I click de "Ok" button close of the dialog, but It's still on the screen, doesn't dissapear. 

The modal close if I click on the screen but the dialog never close

Codepen of the issue: http://codepen.io/anon/pen/vOVGyB

Github: https://github.com/LTroya/IonicDialogAndModalBug

I think the dialog shouldn't be in front of the modal and close after I click on the close button</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @LTroya!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4139). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4139)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by sharvit** [comment]
````
    .factory('SecuredPopups', [
        '$ionicPopup',
        '$q',
        function ($ionicPopup, $q) {

            var firstDeferred = $q.defer();
            firstDeferred.resolve();

            var lastPopupPromise = firstDeferred.promise;

            return {
                'show': function (method, object) {
                    var deferred = $q.defer();

                    lastPopupPromise.then(function () {
                        $ionicPopup[method](object).then(function (res) {
                            deferred.resolve(res);
                        });
                    });

                    lastPopupPromise = deferred.promise;

                    return deferred.promise;
                }
            };
        }
    ])
````

**Comment by mhartington** [comment]
So you shouldn't try to show a popup and a modal at the same time. Ionic doesn't know which component is the active component. 

What you should do is show the modal after the popup has been closed

http://codepen.io/mhartington/pen/YXdWpX?editors=001

**Comment by LTroya** [comment]
Ok. But the problem is in my app, sometimes I show a popup to give to the user a succesful or error message. The modal is an asynchronous that fire at certain event. I am working when WebRTC calls, when I receive a call the modal appears. If the popup is shown, that bug happens

**Comment by mhartington** [comment]
You may want to think of a different way to handle that then. Either that, or you can close the popup programmatically.

http://ionicframework.com/docs/api/service/$ionicPopup/

**Comment by LTroya** [comment]
Ok no problem, I will take a look of that
