### ISSUE TITLE
bug: Input set value problems

### ISSUE THREAD

**Issue by LeoLR** [driftyco/ionic#4141]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi,

I've a search bar with a button for clear the search like this:
```
<div class="bar bar-header item-input-inset">
   <form name="search_form" class="item-input-wrapper" ng-submit="clearSearch()">
      <label class="item-input-wrapper">
         <i class="icon ion-ios7-search placeholder-icon"></i>
         <input id="searchKey" type="search" placeholder="Recherche par enseigne, nom ou numéro..." ng-model="searchKey" autocorrect="off" >
         <button class="button-clear icon ion-close-circled" ng-click="clearSearch()"></button>
      </label>
   </form>
   <button class="button button-clear" ng-click="search(searchKey)">Rechercher</button>
</div>
```

And in my controller i've my function clearSearch():
```
$scope.clearSearch = function() {
	$scope.searchKey= "";
	$scope.getHostsWarning();
};
```

But the input value never changed if i write text in the input... 

Anyone can help me? 

Thanks!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @LeoLR!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4141). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4141)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by LeoLR** [comment]
I found a solution i do this:
```
<form name="search_form" class="item-input-wrapper" ng-submit="clearSearch(); searchKey=''">
```
