### ISSUE TITLE
bug: app resources only works with -livereload?

### ISSUE THREAD

**Issue by fkkcloud** [driftyco/ionic#4146]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I guess its related to access local resources with -livereload

Running with..

> ionic emulate ios -livereload -c

Every resource are loaded good.

But when I run without it.. like so.

> ionic emulate ios -c

It shows below errors like below..

> [Error] Failed to load resource: The requested URL was not found on this server. (X_Marker.png, line 0)
> [Error] Failed to load resource: The requested URL was not found on this server. (window.html, line 0)

I am putting the img in www/img and template html for ng-directive in www/templates.

Calling image or html as below.

>  var imagePost = {
>  url: 'img/Default_Marker.png',
>  size: new google.maps.Size(100, 100),
>  origin: new google.maps.Point(0, 0),
>  anchor: new google.maps.Point(17, 34),
>  scaledSize: new google.maps.Size(1, 1)
>  };

or for html,

>  return {
>  restrict: 'A',
>  templateUrl: '/templates/window.html',
>  link: link
>  };

I was looking all over stackflow, google and ionic forums but no answers but lots of same problem posted..

Here goes the link to this issue with pictures.. Please let me know what is to fix it...

http://forum.ionicframework.com/t/is-there-a-specific-way-to-manage-resource-for-ionic-app/29162</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @fkkcloud!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4146). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4146)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by fkkcloud** [comment]
I don't know if this is related with reseting the wifi but, once I went startbucks and set wifi to theirs for both laptop and mobile and came home to my wifi for both. now it started to work again..? please explain me why this is happening..

**Comment by mhartington** [comment]
Responded on the forum. This is not an issue with Ionic.
