### ISSUE TITLE
bug: When keyboard show up, it does not shift the window until input gets any actual typed characters?

### ISSUE THREAD

**Issue by fkkcloud** [driftyco/ionic#4147]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

I've installed ionic keyboard plugin as below.

ionic plugin add com.ionic.keyboard

I had to put scroll='false' for attribute of ion-content since, I wanted to use 100% of height by CSS so that the view is alway 100% using height..

But with that, 

When I run it (ios and android) and give focus to input element by touching on it,
Keyboard comes up but the view is not scrolling upwards at the moment.

Once I start to type something, then the view start to scrolling to the right position.

If I remove scroll='false',
when keyboard comes up it scrolls to right location but it does not have 100% height applied by CSS..

This is input element that I have for it.

    <form ng-controller='PostsCtrl' name='postForm' novalidate>
      <input type='text' 
          ng-model='content' 
          ng-focus='someFunc()'
          maxlength='20' 
          class='postbox'
          id='map-post-input' 
          placeholder='Why its not working?' required>
      <button ng-disabled='postForm.$invalid' 
          ng-click='addPost()' 
          class="postbox button button-small button-assertive" 
          id='map-btn-submit'> {{ timevalue | date:"mm : ss" }} </button>
    </form>
and this elements are added on top of Google Map if that is related information as well..

Is this know issue?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @fkkcloud!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4147). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4147)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by fkkcloud** [comment]
I had scroll='false' on my ion-content to use CSS height:100% for my map,

and that was why it did 2 different sections of scroll when keyboard comes up..

Now, scroll='true' and by adding .scroll like below, fixes all the problem..

   .scroll{ 
        height: 100%;
    }
    #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
    }

**Comment by mhartington** [comment]
Closing this for now, as it seem the issue was not related to anything specific to ionic.
