### ISSUE TITLE
docs: docs: Is it available to make Status bar font white?

### ISSUE THREAD

**Issue by hojinshin** [driftyco/ionic#4149]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm using blue header bar for my native hybrid app.(testing with iPhone6)
I've referenced many docs, but it's not working.
I want to make the font color of status bar to white.
I've installed the status bar plugin for sure,
and there is a code in js as well.
The code is
if(window.StatusBar) {
    StatusBar.styleDefault();
}</span>

And also, I've added this one.

![default](https://cloud.githubusercontent.com/assets/8757013/8930669/c4843514-356a-11e5-99ee-6b2211836547.PNG)

<span is-issue-template></span></span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @hojinshin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4149). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4149)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Please look at the docs to the status bar.

https://github.com/apache/cordova-plugin-statusbar#methods

Use `StatusBar.styleLightContent`
