### ISSUE TITLE
bug: ios cursor missing in contenteditable div 

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [driftyco/ionic#4150]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I put this in my css file

    div[contenteditable=true] {
      -webkit-user-select: auto !important;
      -khtml-user-select: auto !important;
      -moz-user-select: auto !important;
      -ms-user-select: auto !important;
      -o-user-select: auto !important;
      user-select: auto !important;
    }
and I have this in my ion-content:

    <div id='input' contenteditable=true >
        test
    </div>

it works fine in browser and android,but in ios no cursor is shown when click this div,I can edit it's content although.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Nick-The-Uncharted!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4150). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4150)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Primajin** [comment]
@Nick-The-Uncharted What was the solution?

**Comment by sfaizanh** [comment]
```
[contenteditable] {
        -webkit-user-select: text;
        user-select: text;
}
```
