### ISSUE TITLE
bug: Android - Keyboard issue with crosswalk and native scrolling

### ISSUE THREAD

**Issue by mellinas** [driftyco/ionic#4153]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>
Hi,

I wanted te report a strange bug which can be hard to reproduce.

Here are the steps to reproduce it : 

- Create a new project using : https://github.com/driftyco/ionic-starter-sidemenu
- Disabling Javascript Scrolling : 
        if (ionic.Platform.isAndroid()) {
            $ionicConfigProvider.scrolling.jsScrolling(false);
        }
- Adding crosswalk : ionic browser add crosswalk
- Adding a simple popup or modal with an input text or textarea inside

It leads to multiple issues : 
- Crosswalk seems to create issues with keyboard when focus on an input, it's not fluid, it jumps and the animation is bad
- It freeze all scrollers : when focusing an input inside a popup or modal, it freeze scrolling 
=> To reproduce, simply create a list with multiple items or add item directly in the sidemenu

The best I can say to help is that the bug is not here when I comment ele.blur() in tapFocusOutActive() (inside ionic.js)

- With or without the Keyboard plugin, the issue is still here 
- When removing crosswalk, everything is working well, even with native scrolling 

What can cause that? 

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mellinas!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4153). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4153)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mellinas** [comment]
To complete my post and bring a fix to those running in the same trouble.

Here a similar post on ionic : https://github.com/driftyco/ionic-plugin-keyboard/issues/96

And the solution : https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/pull/32
