### ISSUE TITLE
bug: navigation bar doesn't appear on app load...

### ISSUE THREAD

**Issue by tebuevd** [driftyco/ionic#4156]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>... but reappears after switching to a new tab.

This only happens on first app load (after closing the app) on both ios and android, and only on the default tab. After making one tab switch, the behavior reverts to normal and there are no bugs until the app is fully closed and reopen again.</span>

<span is-issue-template></span>
</span></span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @tebuevd!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4156). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4156)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Can you provide a codepen? There is probably a problem with your markup.

**Comment by Ionitron** [comment]
Greetings @tebuevd!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @tebuevd!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
