### ISSUE TITLE
bug: ion-nav-bar animation when transitioning to nested states

### ISSUE THREAD

**Issue by hudsonmd** [driftyco/ionic#4157]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>CodePen at : http://codepen.io/anon/pen/BNGRJK

When navigating to a state multiple levels lower than the current state the navbar does not animate. However, it does animate the page content. It animates the nav bar correctly when going back to a previously cached state.

This issue appeared in rc.5</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @hudsonmd!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4157). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4157)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
So this type of structure isn't going to be supported. There really is not benefit to having this many nested states. This is the recommended structure 

http://codepen.io/mhartington/pen/YXRLJv
