### ISSUE TITLE
$ionicHistory.clearHistory() not working on 1.0.1

### ISSUE THREAD

**Issue by pmmenneg** [driftyco/ionic#4158]
Simple reproduction steps: in our `LoginController`, we write to the console to verify history state:

`console.log($ionicHistory.viewHistory());`

In our `logOut()` method of our `AuthService`, we call `$ionicHistory.clearHistory();`.

When hitting the login state attached to the LoginController after a logout, we can see the whole history printed to the console.

Anyone else seeing something similar?

**Comment by Ionitron** [comment]
Greetings @pmmenneg!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4158). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4158)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by buunguyen** [comment]
Same problem in 1.1. Both `clearCache` and `clearHistory` don't work. In my use case, I invoke both in logout but when logging in as another user, I can see cached data of the logged-out user. Many people also run into [this](http://forum.ionicframework.com/t/ionic-cache-and-history-clean-issue/25985/2) [problem](http://forum.ionicframework.com/t/clearcache-possible-bug/16532/11) and all have to workaround somehow. It would be great if it's fixed in the framework.

**Comment by aliatsis** [comment]
+1

**Comment by jgw96** [comment]
Hello! Are you still having this issue with the latest version of ionic v1?

**Comment by jgw96** [comment]
Hello! Thanks for opening this issue with us! As it has been a little while since there was any activity on this issue I will be closing it for now, please feel free to reply if you are still experiencing this issue though!
