### ISSUE TITLE
How to make the tabs bar fixed to the top when it is scrolled up to the top

### ISSUE THREAD

**Issue by TonyLuo** [driftyco/ionic#4160]
Hi all,

The content has three parts:
part A
tabs bar
part B.

The tabs bar is at on the middle of the content, I would like to make the tabs bar fixed to the top when it is scrolled up to the top,and the rest of the content below tabs bar(part B) is still be scrollable. it should looks like this:

tabs bar
part B.

When the content scrolls down, the part B top content shows, then the tabs bar is scrollable again. it should looks like this again:

part A
tabs bar
part B.

Does somebody has an idea ?

Thanks.

**Comment by Ionitron** [comment]
Greetings @TonyLuo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4160). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4160)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @TonyLuo!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
