### ISSUE TITLE
feat: <ion-subheader-bar> must add class="bar bar-subheader" to directive

### ISSUE THREAD

**Issue by Robinyo** [driftyco/ionic#4165]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

See this post: http://forum.ionicframework.com/t/understanding-ion-content/29322

As per the other view-related directives you shouldn't need to add classes to the 'ion-subheader-bar' directive in order for it to function correctly.  For example:

    ...

    <ion-subheader-bar class="bar bar-subheader">
      <div class="title title-left padding-left">
        <small translate="ALL_POSTS">
        </small>
    </div>
    <button class="button icon-right ion-ios-compose button-clear button-balanced"></button>
    </ion-subheader-bar>

    <ion-content class="has-subheader">

    ...

Cheers
Rob</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Robinyo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4165). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4165)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ajoslin** [comment]
`<ion-subheader-bar>` does not exist.

Use `<ion-header-bar class="bar-subheader">`

**Comment by Robinyo** [comment]
Sorry, I had a custom directive floating around...

I did tag it as a "Type: feat" so it would be nice to just use (where possible) Ionic directives:

    <ion-view>
      <ion-header-bar></ion-header-bar>             
      <ion-subheader-bar></ion-subheader-bar>       
      <ion-content></ion-content>
      <ion-subfooter-bar></ion-subfooter-bar>        
      <ion-footer-bar></ion-footer-bar>             
    </ion-view>

For example:

![create_order](https://cloud.githubusercontent.com/assets/12203540/8973349/53a7e820-36a7-11e5-87cf-ac56f1c26c16.png)

**Comment by perrygovier** [comment]
Thanks @ajoslin!

@Robinyo, we wont be adding it to v1. It fits with a number of other directives that have class based modifiers in v1. It will be similar to how you described in v2 though.

If we change it here for v1, we should change it everywhere and then we've changed some paradigms of v1, which makes it v2 anyway. :stuck_out_tongue:
