### ISSUE TITLE
Pull to refresh slides duplicate of list at bottom of lists

### ISSUE THREAD

**Issue by ssharmass** [driftyco/ionic#4166]
Hi All,
    I am working on Pull to refresh when  I pull to refresh list , it is working but at the bottom it display all list (i.e. duplicate of all list ) slide left (like page transition) , I search about that but there is no such thing available to do.
Please let me know , anybody have something.

Regards
Shivam

**Comment by Ionitron** [comment]
Greetings @ssharmass!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4166). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4166)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Hey @ssharmass, could you demonstrate this in a codepen?

**Comment by ssharmass** [comment]
Hi Perry,

Shivam01 <https://disqus.com/by/shivam01/> Simon Reimler
<https://disqus.com/by/simonreimler/> 3 days ago
<https://disqus.com/home/discussion/devdactic/add_pull_to_refresh_with_toast_message_in_your_ionic_app/#comment-2186180741>

Hi Simon ,
Sorry for delay ,
The code is same as given above
.controller('AppCtrl', function($scope, $cordovaToast) {
    // First time when go to list page
    $http(url).success(function(response) {

            $scope.items = response;
        })
        // for do refresh and in html I

    $scope.doRefresh = function() {
        $http(url).success(function(response) {

            $scope.items = response;
        }).finally(function() {
            $scope.$broadcast('scroll.refreshComplete');
        })
    );
});

Follow following links :-
http://ionicframework.com/docs...
<http://ionicframework.com/docs/api/directive/ionRefresher/>
http://learn.ionicframework.co...
<http://learn.ionicframework.com/formulas/pull-to-refresh/>

When $scope.$broadcast('scroll.refreshComplete'); run , then just below the
list copy of all list swipe left and that is a problem. Please tell me
solution or alternative.

and One more as example telling that I have put ion-refresh just above the
<ion-list> , so why did you put after <ion-list>, pleas e explain this as
well.

Thanks
Shivam

**Comment by Ionitron** [comment]
Greetings @ssharmass!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
