### ISSUE TITLE
docs: Scratchpad doesn't appear in the learn ionic formulas

### ISSUE THREAD

**Issue by mkolodny** [driftyco/ionic#4170]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>As I finished reading the really awesome "[Build an App with Navigation and Routing](http://learn.ionicframework.com/formulas/navigation-and-routing-part-1/)" formula on learn ionic, I noticed that the scratchpad at the bottom of the articles is missing. A demo illustrating the formula would be super helpful. Does one exist?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mkolodny!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4170). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4170)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
The scratch pads have been moved over to the playground and the learnsite will be retired soon. 
All the examples and articles are over here though. 
https://github.com/driftyco/ionic-learn/tree/master/content/formulas
