### ISSUE TITLE
bug: $state.go doesn't update the URL when used in a form ng-submit.

### ISSUE THREAD

**Issue by renesansz** [driftyco/ionic#4171]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I have a form with ng-submit functionality. **The problem is that upon form submit `$state.go` doesn't update the URL of the app but it transitions the page to the next page.**
But when being used by `ng-click` it works properly.

I know `ui-sref ` would do, but I'm kind of exploring other possible approach and another reason why I chose this approach is that I can make use of `required` attribute for form inputs.

Here's my [sample code](https://gist.github.com/renesansz/6e52fd4098771eb9d92d).</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @renesansz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4171). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4171)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Please provide a minimal codepen. A gist does not help.

**Comment by renesansz** [comment]
Hello, I've noticed that this bug was for ui-router not for Ionic.
I apologize for the false report.
