### ISSUE TITLE
bug: Blue border on input box in Android 4.0.4 

### ISSUE THREAD

**Issue by RajMondaz** [driftyco/ionic#4173]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.0</span>  <span ionic-webview>webview</span>

<span ionic-description>

 
![image](https://cloud.githubusercontent.com/assets/10266752/9020735/17e846c8-383b-11e5-8b86-1c20d4d1576c.png)

Using Ionic Version Ionic, v1.0.1
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @RajMondaz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4173). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4173)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Hmm, I'm not able to replicate this. 
Closing for now
