### ISSUE TITLE
docs: Forbidden Image on Tab Bar Controller Page

### ISSUE THREAD

**Issue by samrose3** [driftyco/ionic#4175]
This isn't directly related to ionic, but on you site at this page http://ionicframework.com/docs/angularjs/controllers/tab-bar/
I am getting this error causing a broken image on the page

```
Failed to load resource: the server responded with a status of 403 (Forbidden) http://ionicframework.com.s3.amazonaws.com/docs/controllers/ion-tabs.gif 
```

![tab_bar_controller_-_multi-page_tab_interfaces_-_ionic_framework](https://cloud.githubusercontent.com/assets/11774595/9021815/a8f76c54-3825-11e5-911d-2dfe68a321bb.jpg)

**Comment by Ionitron** [comment]
Greetings @samrose3!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4175). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4175)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by thiagofelix** [comment]
It might sound naive, but how did you get to this page? I didn't find link to it from the documentation.

**Comment by samrose3** [comment]
@thiagofelix ah thank you! good deal :+1:

**Comment by samrose3** [comment]
Sorry, didn't mean to close this issue.

**Comment by mhartington** [comment]
The link in reference is to an old version of the site.
http://ionicframework.com/docs/api/directive/ionTabs/
