### ISSUE TITLE
feat: Make Crosswalk default browser for Android

### ISSUE THREAD

**Issue by csvan** [driftyco/ionic#4176]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>webview</span>

<span ionic-description>Apart from the app size inflation (15-20MB as of current), are there any good reasons for not making Crosswalk the default runtime for Android deployments?

Apart from the obvious boosts to overall performance and rendering, this would make overall development of the core platform easier by eliminating Webview issues specific to different Android versions. It would also make things easier for developers, since potential issues and questions can be discussed w.r.t. only a single browser. </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @csvan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4176). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4176)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-cli#546
