### ISSUE TITLE
feat: Support Crosswalk on IOS

### ISSUE THREAD

**Issue by csvan** [driftyco/ionic#4177]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Crosswalk is now available for IOS (Source: https://crosswalk-project.org/blog/ios-release.html).

It would be helpful if it was made possible to add this to an IOS build, just as it is currently possible for Android. Potentially, it could greatly improve both performance and developer efficiency, since a common runtime would be used for both Android and IOS deployments.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @csvan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4177). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4177)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
There could be some possible issue with this. Specifically how WKWebview still doesn't allow loading of local files like UIWebview does. WKWebview in general is pretty buggy and is not a safe bet ATM, even if the crosswalk folks have decided to use it. Once we have a better picture of whats going on underneath the hoods, we may consider it, but as it stands, it's too risky to add to iOS.
