### ISSUE TITLE
bug: Scroll on list will active the item

### ISSUE THREAD

**Issue by mjason3** [driftyco/ionic#4179]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I am scrolling on a list, the first touch to the screen will active an item(which has ng-click or href registered). It's not buggy, but just not looks like native experience. If I scroll the list, the item should not be highlighted when I touch the screen.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mjason3!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4179). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4179)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This is an on-going battle when dealing with js-scrolling. One option would be to just use native-overflow scrolling instead.

The way things are setup currently, its a happy medium that works well on all devices/os/os-version/etc. It may not be perfect, but it performs well on in all these environments.

**Comment by mjason3** [comment]
wait, i enabled the native scrolling. all the <a> tag has affected by this issue. You know, I manually use div tag and add the related classes as a workaround.
