### ISSUE TITLE
feat: $ionicLoading promise wrapper

### ISSUE THREAD

**Issue by beauby** [driftyco/ionic#4182]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It would be nice to have a function that wraps a promise in a loader, instead of manually showing/hiding the `$ionicLoading`. Something along the lines of:
```
$ionicLoading.wrap = function(promise, opts) {
  $ionicLoading.show(opts);
  return promise.finally($ionicLoading.hide);
}
```
which would then allow to do things like:
```
$ionicLoading.wrap(MyService.doStuffAsync(), { template: 'Doing stuff...' })
  .then(function(res) {
    console.log("Async stuff returned: ", res);
  });
```

**Comment by beauby** [comment]
I'd be happy to issue a PR for this one, but I'd like your advice on which is best between:

1. taking a promise as a parameter (which implies that, technically, the async action gets triggered slightly before the loader shows up
2. taking a function that returns a promise as a parameter

**Comment by Ionitron** [comment]
Greetings @beauby!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
