### ISSUE TITLE
bug: Elements with and ng-show directive appears briefly on view loading even if expression is false 

### ISSUE THREAD

**Issue by carlobonamico** [driftyco/ionic#4183]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Elements with and ng-show directive appears briefly on view loading even if expression is false. 

Happens both on ionic view and on a build.phonegap.com built packge.

Ionic: 1.0.1
Devices: iPhone 5, iPad Air

Example on 
http://codepen.io/anon/pen/yNGZGb</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @carlobonamico!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4183). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4183)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by olliebennett** [comment]
Hi @carlobonamico, you might have success using `ng-if` instead of `ng-hide` / `ng-show` where possible.

Your problem appears to be similar to something I experienced in the past: https://github.com/driftyco/ionic/issues/3495

**Comment by mhartington** [comment]
This sounds exactly the same as #3495
Closing this as it has already been talked about.
