### ISSUE TITLE
bug: ion-tab on-select not working

### ISSUE THREAD

**Issue by pixelfreak** [driftyco/ionic#4184]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I have a pretty simple code:

```html
<ion-tab title="Menu" icon="ion-ios-book" icon-off="ion-ios-book-outline" href="#/tab/menu" on-select="console.log('test')">
```

And for some reason I can't get `on-select` to fire. I've tried putting other code in there (ie: calling a function) and it still won't work. Any idea why?

Thanks</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @pixelfreak!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4184). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4184)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
onSelect expects an expression.
http://ionicframework.com/docs/api/directive/ionTab/ 
Similar to how you can't do `ng-click="alert('hello')"`, but you can do `ng-click="myFunction()"`

So you would do `on-select="log()"`, then define a log method on your scope.

```
$scope.log = function(){
  console.log("here");
}
```

**Comment by lanow72** [comment]
I have the same probleme
my code is 
<ion-tab title="Jouer" 
   " href="#/tab/jouer"
   on-select="log()"
  >
 my js
.state('tab.jouer', {
    url: '/jouer',
      
    cache: false,
    views: {
      'tab-jouer': {
        templateUrl: 'templates/tab-jouer.html',
        controller: '**JouerCtrl**'
      }
    }

then my controle is **JouerCtrl**

.controller('JouerCtrl', function($scope) {
  $scope.log = function(){
  console.log("here");
  alert("kkk");
}

but it doesn't work just the tab is ok but my fct **log**  is never run

**Comment by macarole** [comment]
i did it in the way you recommend ,but it still won't work,why?
