### ISSUE TITLE
bug: when disable jsScrolling, the sideMenu will show vertical scrolling bar always

### ISSUE THREAD

**Issue by jianyi0115** [driftyco/ionic#4185]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>js:  $ionicConfigProvider.scrolling.jsScrolling(false);

when disable jsScrolling, the sideMenu will show vertical scrolling bar always</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jianyi0115!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4185). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4185)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Could you provide a codepen?

**Comment by Kurtz1993** [comment]
Found this, too.
Here's a CodePen:
http://codepen.io/anon/pen/yNraRQ?editors=101

**Comment by mhartington** [comment]
That codepen does not have a sidemenu in it.

**Comment by Ionitron** [comment]
Greetings @jianyi0115!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @jianyi0115!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
