### ISSUE TITLE
bug: Input field with $IonicScrollDelegate: Cursor not moving with input field

### ISSUE THREAD

**Issue by sparsh0611** [driftyco/ionic#4186]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I am scrolling page when a keyboard is shown to show the content hidden behind keyboard. Scrolling works fine but the cursor in the input field (inside a form) doesn't move with it and is shown outside the input element. Here is the code:

```javascript
window.addEventListener('native.keyboardshow', keyboardShowHandler);

function keyboardShowHandler(e) {
   $location.hash('forgotPassword');
   $ionicScrollDelegate.anchorScroll(true);
}
```

Ionic: 1.6.1
Devices: iPhone 5, iPhone 6 - iOS 8.3</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @sparsh0611!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4186). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4186)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Please provide a codepen demoing this.

**Comment by Ionitron** [comment]
Greetings @sparsh0611!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
