### ISSUE TITLE
bug: bug: view-title reloaded

### ISSUE THREAD

**Issue by ste5787** [driftyco/ionic#4187]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.x</span>  <span ionic-webview>webview</span>

<span ionic-description>With ionic 1.0.1 when i change tab there is a little time in which there isn't text label:  If i create two tabs whit the same title (e.g Chats) when i swicth from one to the other i expect that the view title dosen't refresh; instead i can see a refresh ("Chat"  --> no title --> "Chat"). The same thing appen witch nav-bar-title.

Whit ionic 1.0.0 beta 13 it doesn't happen! 

Any idea?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ste5787!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4187). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4187)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Could you provide a codepen?

**Comment by Ionitron** [comment]
Greetings @ste5787!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
