### ISSUE TITLE
docs: Question about config.xml

### ISSUE THREAD

**Issue by talamaska** [driftyco/ionic#4188]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm not sure if this question is for ionic or cordova.
I have noticed that i have a record in config.xml saying
```xml
<engine name="android" spec="4.0.2"/>
```
1. Is it matter if I use crosswalk?
2. Is it matter when android-minSdkVersion and android-targetSdkVersion are set for example to 21.
3. How it is changed?
4. Is it responsible for just saying the cordova-android version?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @talamaska!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4188). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4188)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Hm, I just looked at a blank project and added crosswalk. Wasn't able to get `<engine />` added, so it might be from the older way we added crosswalk.

**Comment by talamaska** [comment]
Actually I didn't get an answer.
I think I have understand from where it comes.
if you have started the app initially with android not crosswalk,
cordova is adding it, my version is 4.02 and i was concerted about it, cause i don't want to build for android 4, but it seems it's the cordova-android version, cause recently was released 4.1
So you are saying that if i delete it, it won't harm my project if it setup already with crosswalk?

**Comment by mhartington** [comment]
Again, I wasn't able to get this added to a new project so I can't say for sure. Give it a try without the reference and see if it does.

**Comment by talamaska** [comment]
I will, thanks
