### ISSUE TITLE
docs: README.md or gulp demos incorrect

### ISSUE THREAD

**Issue by marcneander** [driftyco/ionic#4189]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Trying to spin up the demos but it seems slightly buggy.
```
marc@amedala ~/src/ionic/IonicFramework (master) gulp demos --demo-version=1.0.1
[13:23:37] Using gulpfile ~/src/ionic/IonicFramework/gulpfile.js
[13:23:37] Starting 'demos'...
info: Loading config /Users/marc/src/ionic/IonicFramework/config/demos/demos.config.js
info:    Read config from "/Users/marc/src/ionic/IonicFramework/config/demos/demos.config.js"
info:    Logging set to "info"
info:    Processing docs
info:    running processor: version-data
info:    running processor: read-files
info:    running processor: demos
info:    running processor: render-docs
info:    running processor: unescape-comments
info:    running processor: write-files
info:    Processed 101 docs
[13:23:37] Demos for 1.0.1 generated!
[13:23:37] Building ionic into demo folder...
cd di	[13:23:40] Finished 'demos' after 2.87 s
marc@amedala ~/src/ionic/IonicFramework (master) cd dist/
marc@amedala ~/src/ionic/IonicFramework/dist (master) ls
css          fonts        js           nightly      version.json
```

Why would it create a nightly folder there? And trying to spin up that nightly builld:

```
marc@amedala ~/src/ionic/IonicFramework/dist/nightly (master) python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
```

I get broken relative links in the HTML:

```
<link rel="stylesheet" href="/dist/ionic-demo//ionic/css/ionic.min.css">
<script src="/dist/ionic-demo//ionic/js/ionic.bundle.min.js"></script>
<script src="/dist/ionic-demo//pages-data.js"></script>
<script src="index-ionic-demo-app.js"></script>
```

README.md is outdated or am I doing something wrong?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @marcneander!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4189). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4189)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Make sure you run `gulp build` to generate the nightly builds
