### ISSUE TITLE
bug: bug: scrolling with nested tags

### ISSUE THREAD

**Issue by zbigus** [driftyco/ionic#4190]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

I've found that scrolling of deeply nested tags is not working
http://codepen.io/anon/pen/VLgZxV

The problem here is the mousewheel event handling is using  ionic.DomUtil.getParentOrSelfWithClass(e.target, 'ionic-scroll') without the third parameter, so the default depth is set to 10, which sometimes is not sufficient.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @zbigus!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4190). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4190)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Are you seeing issues once on a device?

**Comment by zbigus** [comment]
I'm not seeing the issue on mobile devices with touch scrolling. The issue is only observable on desktop browsers while using mouse wheel to scroll.

**Comment by mhartington** [comment]
Not sure if this will be something we want to fix for two reasons

1) We will be moving forward with native overflow scrolling in future releases
2) This is meant for mobile device, not really desktop. 

Closing for now.
