### ISSUE TITLE
Make angular* dependencies in bower.json less specific?

### ISSUE THREAD

**Issue by kcivey** [driftyco/ionic#4192]
Could the angular, angular-animate, angular-sanitize, and angular-ui-router dependencies in bower.json have a `^` prefix added, to avoid having bower complain about incompatible versions?

**Comment by Ionitron** [comment]
Greetings @kcivey!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4192). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4192)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Not really, since you can't know for sure if that particular version of angular will work with ionic. We've had instances where we've upgraded or used a different angular version and it breaks Ionic.

**Comment by kcivey** [comment]
I guess, but that defeats a lot of the purpose of dependency management and semantic versioning. If you're installing other things that depend on angular it's unlikely that they're going to happen to require the exact version that ionic does, so you're usually going to be dealing with incompatibilities and having to guess anyway.
