### ISSUE TITLE
bug: select tag does not work on Windows tablet

### ISSUE THREAD

**Issue by VladyslavGoloshchapov** [driftyco/ionic#4194]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello,

I tried to add select tag on ionic app and it does not open list of options when you tap on it.
Reproducible on Windows tablet.
However everything works great if you use special pen.

To make sure it is ionic issue I created HelloWorld ionic project with single select and it didn`t work there.

Can this be fixed please?

Thanks,
Vlad</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @VladyslavGoloshchapov!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4194). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4194)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Where not focusing on windows phone/windows tablet at the moment. Windows platform is a bit in flux so we're waiting until it becomes more stable. Closing this for now

**Comment by martinlingstuyl** [comment]
Hi, 
I see this topic is closed. It's become an issue for us as well. We're having an app in production currently, published to windows store and ios store, specifically targeted at the Surface Pro and iPad. (of which the Surface Pro is being used more and more by busyness users)

Are you still decided on the whole 'in flux' thing?
With 4 million Surface Tablets just sold last year I kind of think it it's important to focus on microsofts product more. 

One thing to note: the SELECT box does open when I tap it with two fingers.

Martin
