### ISSUE TITLE
bug: Android 4.4.4 input artifact

### ISSUE THREAD

**Issue by bjedrzejak** [driftyco/ionic#4195]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I've found strange input behavior on Android 4.4.4. If content of input is longer than input there will appear artifact (whole input will contain colorful background).
![screenshot_2015-07-22-16-37-13](https://cloud.githubusercontent.com/assets/13661282/9087959/ff9890cc-3b8d-11e5-8c8b-22bd1fe1a6df.png)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @bjedrzejak!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4195). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4195)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Hmm, would you be able to share a codepen that I could load on a device?
I wasn't able to recreate this.

**Comment by Ionitron** [comment]
Greetings @bjedrzejak!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
