### ISSUE TITLE
Date / Time / Datetime picker

### ISSUE THREAD

**Issue by nighto** [driftyco/ionic#4202]
When creating a small project with Ionic (which is very nice, by the way, thanks guys!!), one of the things I miss is a datetime picker. A component that could be configured to be date- or time-only, and perhaps emulating native appearance (if it doesn't use tha native <input>) would be gold.

**Comment by Ionitron** [comment]
Greetings @nighto!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4202). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4202)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Google is a good friend here.
https://github.com/rajeshwarpatlolla/ionic-datepicker

We push people to the native input implementation, but this is a pretty good alternative.

**Comment by nighto** [comment]
I did know this component. I meant that it could be native to ionic core, since I don't believe it is supposed to be a component that many people might not use, such as a (say) Google Maps embed or something.

**Comment by mhartington** [comment]
Something like that wouldn't be a good fit for ionic's core. Like I've said, the browsers own native controls off the best options in our opinion.

**Comment by nighto** [comment]
Fair enough. Thanks for your answer!
