### ISSUE TITLE
bug: Bind click doesn't work on dynamic element created inside a directive (if wrapped on label)

### ISSUE THREAD

**Issue by militellovincenzo** [driftyco/ionic#4205]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have created a directive to clear an input text by show an icon (basically same functionality a search box has).
Turns out that the if I wrap the input element inside a label, the bind I create on the "clean icon" doesn't work for the click event  (dblcick and other events work fine)

If I wrap my element with a DIV, everything works

I have created a plunker to show the issue 
http://plnkr.co/OxB9wGZNNV3rRqSJjhgo

Please, notice that the directive works correctly if I use the ionic version 1.0.0-beta.5</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @militellovincenzo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4205). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4205)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This is because we use labels to set focus the the input. 
Any click/taps/touches that happen with a label element will attempt to set focus to a child input.

For what you need, using a div instead of a label will work fine.
