### ISSUE TITLE
bug: Which NodeJS version should I use for Ionic?

### ISSUE THREAD

**Issue by NgYueHong** [driftyco/ionic#4207]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I was using Node version 0.10.40 to run Ionic. It seems running fine, however ionic shows this message every-time I run it:

    ******************************************************
     Upgrade warning - for the CLI to run correctly,
     it is highly suggested to upgrade the following:

     Please update your Node runtime to version  >=0.12.x

    ******************************************************

So, I update my Node to version 0.12.7. But then when I try to reinstall cordova & ionic, I get a series of warning & errors such as:

    npm WARN engine cordova-js@4.0.0: wanted: {"node":"~0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
    npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":"0.12.7","npm":"2.11.3"})
    npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
    npm ERR! node v0.12.7
    npm ERR! npm  v2.11.3

    npm ERR! unexpected eof
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

It end up fail to install. So, what version of NodeJS should I use?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @NgYueHong!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4207). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4207)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-cli#560
