### ISSUE TITLE
Ionic view returns 404 error

### ISSUE THREAD

**Issue by UzielSilva** [driftyco/ionic#4211]
I was trying to sync my Ionic View apps but Ionic view returns error 404.

Are the Ionic view servers ok?

**Comment by Ionitron** [comment]
Greetings @UzielSilva!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4211). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4211)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jmknoll** [comment]
Any idea what was causing the error?

**Comment by UzielSilva** [comment]
Maybe the problem is caused for ionic view server connectivity issue or somewhat.

**Comment by vijaemanlapaz** [comment]
same here im getting 404 when i try to sync

**Comment by allen8300** [comment]
same here...
