### ISSUE TITLE
No back button when switching between tabbed to non-tabbed pages

### ISSUE THREAD

**Issue by leonaburime** [driftyco/ionic#4213]
This is a bug repeatedly mentioned using the Ionic Framework. Theres no back button going to and from a tabbed state.  Ive found out that the Ionic Team said they will update this in Ionic 2.0. The problem is

1.  Angular and Ionic 2.0 release dates are far away(2016?) and most likely will need to run
through several iterations to be stable
2. People need fixes for their app in Ionic 1.0

Searching through the forums Im wondering if anyone has a clean compact solution(or reasonable hack) to the problem of 
1. Having a 'Back' button when going from a tab page to an untabbed page AND
2. Having a 'Back' button when going from a untabbed page to the first tabbed page

**Comment by Ionitron** [comment]
Greetings @leonaburime!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4213). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4213)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
As I have stated in #437, we are aware of this issue. But this is a limitation of the way things are setup at the moment and ui-router. We will address this in 2.0. Until then there is no easy fix.

**Comment by leonaburime** [comment]
Hi @mhartington, thank you for the response.  I intended this as  a community centered post where people can leave their tried and tested workaround solutions. To save others like me hours and even days trying to figure out how to fix the issue for their own app.  I spent  quite a bit of time thinking I was doing something wrong now I am hoping someone found a fix that works for all platforms.

Hopefully in the spirit of collaboration people will still be able to comment and share their solutions for the benefit of the rest of us.

**Comment by mhartington** [comment]
Not really the purpose of github issues. That is what the forum is for. Please post there.

**Comment by nuruddinbadawi** [comment]
really I lost when searching and no solution about this issue it also happens with me how fix that?

**Comment by dujuanxian** [comment]
Hi @mhartington , I don't think it is the "right solution" to close this issue or fix it in 2.0 (which until now is still Beta version). I am struggling for this problem in my project too, if this issue has "limitation of the way", would it be better to open it and get more ideas from other ones?
