### ISSUE TITLE
bug: Ionic Checkboxes height disproportionate with item-text-wrap set

### ISSUE THREAD

**Issue by RonCan** [driftyco/ionic#4214]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm using the following code to render checkboxes in a row

                    <label class="row item item-input ">
                    <span class="item-text-wrap col col-50 input-label">Type Of Inspection</span>
                    <div class="col col-50">
                        <div class="item-text-wrap row responsive-md">
                            <ion-radio  name="typeins" ng-model="form6.type" ng-value="'Monthly'">Monthly</ion-radio>
                            <ion-radio  name="typeins" ng-model="form6.type" ng-value="'Yearly'">Yearly</ion-radio>
                            <ion-radio  name="typeins" ng-model="form6.type" ng-value="'Periodic'">Periodic Discharge</ion-radio></div>
                    </div>
                </label>

My app's background is black and the checkboxes are white. When the device width/height is lowered as can be seen in [this ionic playground link][1]
the checkbox with more text keeps it's height while the others are shorter than it. The behavior can be seen in the attached screenshot[![Checkbox height disproportional][2]][2]. How to make the other's height equal the biggest checkbox?

  [1]: http://play.ionic.io/m/90209eabf06e
  [2]: http://i.stack.imgur.com/LNuFa.png</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @RonCan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4214). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4214)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This would be better asked on the [forum](http://forum.ionicframework.com/) rather than the github issue.
