### ISSUE TITLE
bug: ng-hide/ng-show not working on the device

### ISSUE THREAD

**Issue by nvd-ai** [driftyco/ionic#4217]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I have been trying to get the ng-hide/ng-show to hide an element, which works just fine in the browser but not on the device, being either iOS or Android.

On the browser, .ng-hide seems to be loaded by ionic into the browser together with some other styles, but on the device .ng-hide is not defined. 

What is the solution? If this is by design, what's the proper way to show/hide an element? If not, what am I missing?

Thanks,</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @nvd-ai!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4217). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4217)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Please provide an example to look at.

**Comment by nvd-ai** [comment]
Tried a blank ionic application and it works just fine. The problem is that I am using ionic under cca and in that project, the ng-show/hide directives do not work with the same exact source code that works with pure ionic project. I have not been able to figure out the cause yet. But I am going to close this because the cause seems to be cca.
