### ISSUE TITLE
ionic upload adds malformed UTF-8 BOM to index.html and changes Content-Security-Policy tag.

### ISSUE THREAD

**Issue by waynebloss** [driftyco/ionic#4219]
After I ran `ionic upload` for my project, it changed the top of my `index.html` file from this:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-eval' 'unsafe-inline' *">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title></title>
```

to this:

```html
&#xFEFF;<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Security-Policy" content="default-src &apos;self&apos; &apos;unsafe-eval&apos; &apos;unsafe-inline&apos; *">
    <!-- ... -- >
```

`index.html` is already encoded in UTF-8 without BOM and it didn't change any of the other files which are encoded the same way. So, I have a few questions:

- Should `index.html` or any other html file have a BOM?
- Is the new Content-Security-Policy correct?
- What should I do, if anything?

This is on Windows 10. I can try it on OS X and other various Unixes too, but I'll see what shows up here first. Thanks.

**Comment by Ionitron** [comment]
Greetings @waynebloss!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4219). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4219)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by waynebloss** [comment]
@Ionitron The UX for submitting the issue via the Ionic custom submitter was not good. I'd much prefer to just use GitHub's issue system.
