### ISSUE TITLE
bug: ion-nav-back-button always showing 'Back' instead of previous title

### ISSUE THREAD

**Issue by schellmax** [driftyco/ionic#4224]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>see this fiddle: http://codepen.io/gnomeontherun/pen/EfKgJ?editors=101
everything works as expected here, clicking an item in the list renders a back button title 'Home'.

then this: http://codepen.io/anon/pen/eNoJxa?editors=101
clicking an item in the list, the back button title will always be 'Back' (instead of 'Home', as desired)

single code difference is an empty title attribute in the template for the item view:
original: `<ion-view title="{{item}}">`
modified: `<ion-view title="">`

so, although the home template DOES have a title (only the item view does not), it's always replaced by 'Back' in the back button, so you can't have item views without a title (in a master-detail pattern as this one)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @schellmax!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4224). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4224)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @schellmax!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
