### ISSUE TITLE
feat: How do i used the ionic download

### ISSUE THREAD

**Issue by farcorn71** [driftyco/ionic#4226]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Please after downloading ionic from github, how do i use it</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @farcorn71!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4226). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4226)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
If you are just getting started, please check out docs, forum, or this video.

https://www.youtube.com/watch?v=C-UwOWB9Io4
http://ionicframework.com/docs/guide/
