### ISSUE TITLE
bug: Navigation to tabbed view with state.cache = false breaks history

### ISSUE THREAD

**Issue by israelrios** [driftyco/ionic#4227]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The same view appears twice in history and breaks back button behavior on android when:
Go to a view with tabs whose parent state has "cache: false" and "abstract: true";
Go back;
Go to the same view with tabs again;
Try to go back.

You can reproduce here:
http://codepen.io/anon/pen/JdVKJZ?editors=101

The problems seems to be the detection of 'dupNav' now that the view.historyId is new each time the view is rendered.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @israelrios!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4227). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4227)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Since the view is abstract, you're not really navigating to that state, but it's child, so this a gray area. You really should't need to use `cache: false` here.

**Comment by israelrios** [comment]
Without the cache = false I had problems with stale content in the tabs.

**Comment by mhartington** [comment]
Then you would want to move that to the nested states.

**Comment by israelrios** [comment]
There are other problems with tabs, even when cache=false. Check:

**Comment by mhartington** [comment]
Do you have an example of that?

**Comment by israelrios** [comment]
http://codepen.io/anon/pen/pJBdMW?editors=101

**Comment by mhartington** [comment]
I'm not sure what I should be seeing here? 
It looks to be working fine.

**Comment by israelrios** [comment]
The second time we go to the "About" tab the title should be "About 2" but it is "About 1".

**Comment by danbucholtz** [comment]
Hi @israelrios 😄 ,

Please use the life cycle events to access state parameter data when using cached views.  Controllers are only created once.

```
$scope.$on("$ionicView.enter", function(event, data){
   $scope.id = data.stateParams.id;
});
```

I don't think there is a legit issue here.  Everything seems to be working fine for me.  Please let me know if I am mistaken.

Thanks,
Dan
