### ISSUE TITLE
bug: Clicking on a ion-tab goes to the previous page?!

### ISSUE THREAD

**Issue by VolvoOlympian** [driftyco/ionic#4231]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have 3 different pages, page A, B, and C. Clicking a button in page A goes to the first ion-tab of page B(where it has 2 ion-tabs), clicking on a button in page B goes to page C. Clicking the default back button on the header goes back to page B. The problem is when I now click the second ion-tab at page B, it acts like a back button and goes back to page A, but it should go to the second ion-tab of page B...

Is there any workarounds for this so I can force the click on a ion-tab actually shows the content inside...</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @VolvoOlympian!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4231). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4231)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Please provide a codepen demoing your issue.

**Comment by VolvoOlympian** [comment]
Is it OK if I only retain the minimum code that demonstrates the problem and then upload a zip of my ionic project instead?

**Comment by mhartington** [comment]
Yes

**Comment by VolvoOlympian** [comment]
Thanks very much, I have just emailed you my project and the steps to recreate the problem

**Comment by Ionitron** [comment]
Greetings @VolvoOlympian!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
