### ISSUE TITLE
bug: bug: placeholder vertical alignement

### ISSUE THREAD

**Issue by 5im0n** [driftyco/ionic#4232]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Their is an alignement problem with the placeholder on inline label. The placeholder is too hight compare the label.
I seen this problem on Android, Chrome, iOS, but not on Firefox

![capture](https://cloud.githubusercontent.com/assets/659811/9271929/fdc166ec-427d-11e5-9026-f60385fb6167.PNG)
http://codepen.io/5im0n/pen/KpYGKr

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @5im0n!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4232). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4232)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Hmm tested this in chrome, on a device and wasn't able to get the issue. Though this could be attributed to a visual trick on the eyes.

http://codepen.io/mhartington/pen/QbRvBY?editors=010

**Comment by 5im0n** [comment]
Hey @mhartington 
Indeed in chrome it could be attributed to a visual trick on the :eyes:. But on iOs devices (tested on iPhone 5 - iPhone 6+) it's a little bit more evident. 
I'm enclose you a screenshot from an iPhone 6+
![img_0076](https://cloud.githubusercontent.com/assets/659811/9325711/acd4a892-4594-11e5-97b9-f7f1927a7cdc.jpg)

Compare to a screenshot from Nexus 9
![screenshot_2015-08-18-08-51-17](https://cloud.githubusercontent.com/assets/659811/9325730/cfdb4198-4594-11e5-8fb6-77195b7da118.png)

It's maybe due to the different font size between the label (16px) and the placeholder (14px)

**Comment by mhartington** [comment]
Cool thanks for the screen shots. Will look into this.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by robdog** [comment]
Definitely still running into this issue with text not being vertically aligned within an input box on the latest version of ionic 1.

**Comment by crazybob9** [comment]
Still have this issue

**Comment by crazybob9** [comment]
+1

**Comment by Asterodeia** [comment]
+1
