### ISSUE TITLE
bug:  can-swipe-back="false" not working.

### ISSUE THREAD

**Issue by NorthMcCormick** [driftyco/ionic#4236]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>From pre 1.0 to 1.1.0 the can-swipe-back="false" in ion-view and other methods don't prevent the iOS swipe back. I've had to disable it entirely in the app config to prevent it.

There was an old issue with it on here and that was the resolved answer though I can't get it to work.

http://forum.ionicframework.com/t/can-swipe-back-false-doesnt-work-to-prevent-ios-swipe-back/30035 is also having this issue so it's not just me. Any ideas?

I've tried injecting ionicConfig and disabling it on view enter/leave but that didn't work either.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @NorthMcCormick!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4236). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4236)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Codepen to test against?

**Comment by Ionitron** [comment]
Greetings @NorthMcCormick!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
