### ISSUE TITLE
bug: ion-navbar top padding issue still there on r1.1.0 when not hide statusbar

### ISSUE THREAD

**Issue by Poordeveloper** [driftyco/ionic#4238]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>
Seems only happens with navbar. I did install both cordova-plugin-device and cordova-plugin-statusbar.  It also works fine without statusbar, ionic.Platform.fullScreen(true, false). But I really not want hide status bar.

![image](https://cloud.githubusercontent.com/assets/1399893/9293433/b14d4f2e-445d-11e5-9be9-0d296cea1d97.png)

Without navbar it is ok.
![image](https://cloud.githubusercontent.com/assets/1399893/9293438/d7692c96-445d-11e5-89bb-5b376c4d3d18.png)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Poordeveloper!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4238). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4238)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
