### ISSUE TITLE
bug: Over translated for ionSideMenuContent directive

### ISSUE THREAD

**Issue by suyuz0629** [driftyco/ionic#4240]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I used the expose-aside-when="large" in the menu starter template and chose the right side menu, I found that when I clicked on the menu item, the menu content will be translated right 275px automatically when the screen size is over the "large" size, and therefore left a 275px wide blank area in the left side of the screen.

I think this is because when the menu is already toggled as screen size is over the large size, there is no need for the menu content to be translated anymore.

A sample in codepen

http://codepen.io/suyuz0629/pen/jPorVE

when I click the interview item, the blue content field will be shifted right.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @suyuz0629!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
