### ISSUE TITLE
bug: :CordovaLib:processDebugResourcesERROR: asset dire

### ISSUE THREAD

**Issue by free9ja** [driftyco/ionic#4241]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>:CordovaLib:processDebugResourcesERROR: asset directory 'C:\Windows\System32\myApp\platforms\android\CordovaLib\build\intermediates\bundles\debug\assets' does not exist</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @free9ja!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
