### ISSUE TITLE
bug: Button actions with ng-click gets mixed up

### ISSUE THREAD

**Issue by jimmy-tfp** [driftyco/ionic#4243]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

This bug is somewhat like this closed one:
https://github.com/driftyco/ionic/issues/2899

If you have 3 buttons, and you click them in random order you will *mostly* get a click identifier from the last clicked button.

Only happens on the device, ios or android, not on a desktop browser.

Steps:

1) add this to tab-dash.html of the tabs starter app:

    <pre>
    <ion-content class="padding">
    <button class="button" ng-click="add(4)">4</button>
    <button class="button" ng-click="add(5)">5</button>
    <button class="button" ng-click="add(6)">6</button>
    </pre>

2) add this to controllers.js:

    <pre>
    .controller('DashCtrl', function($scope) {          
            $scope.add = function(x) {
            alert(x);
            };
     </pre>
           
})

3) confirm this works 100% on a desktop browser

4) run on device
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jimmy-tfp!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4243). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4243)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @jimmy-tfp!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by jorisw** [comment]
I'm still having this problem with ionic 1.2. It would appear that having two or more buttons in the same parent container, makes every button trigger the `ng-click` of the first. Example:

```
        <label class="item two-buttons">
          <button class="button button-positive" type="button" ng-click="fillBottle()">Fill Bottle<span ng-show="fillBottles"> ({{fillBottles}})</span></button>
          <button class="button" type="button" ng-click="endPark()">End / Park</button>
        </label>
```

Clicking the second button triggers fillBottle() in my app, running in the iOS simulator with live reload enabled.
