### ISSUE TITLE
feat: Provide support for WKWebView via Crosswalk for iOS

### ISSUE THREAD

**Issue by martinjbaker** [driftyco/ionic#4246]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>https://crosswalk-project.org/documentation/ios.html</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @martinjbaker!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4246). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4246)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by danicomas** [comment]
+1

**Comment by mhartington** [comment]
Pleas see #4177

There are many issues with WKWebview currently and they will always be there for iOS 8. Crosswalk's working around the file loading limitation by running a local server, but that brings up a lot of question and complexity to an app. 

Besides the file loading issue, WKWebview has many other issues underneath it. All of this is on iOS8.

With iOS9 fixing a lot of these issues and making wkwebview much more stable, cordova-ios will have this be default, and fallback to uiwebview for ios8 and below. While crosswalk does provide a fix for now, it still won't be able to fix some underlying issues with wkwebview.
