### ISSUE TITLE
how to completely get rid of splash screen in an ionic application 

### ISSUE THREAD

**Issue by aishakhan1194** [driftyco/ionic#4249]
I have created an application using ionic and i dont want the splash screen or any kind of delay to happen when i open my application 

i went to the config.xml file and changed the code to this

<preference name="SplashScreen" value="none"/>
  <preference name="SplashScreenDelay" value="0"/>

yet when i open my application on the phone it takes a while to load it which is uncomfortable and not a friendly user interface. 

my application is only of 14.7 mb

Thanks!

**Comment by Ionitron** [comment]
Greetings @aishakhan1194!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4249). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4249)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
So this won't be possible. There needs to be splash screen in cordova land until deviceReady has fired. Unfortunately we won't be able to do much about this. A quick 'hack' for this, you could make splash screens that mimic the minimal UI of your app so that it appears to load instantly.
