### ISSUE TITLE
feat: Slidebox option to disallow either swipe left or swipe right

### ISSUE THREAD

**Issue by Duffycola** [driftyco/ionic#4250]
I'm building a questionnaire and would like the user to be able to swipe backward, but disable swipe forward until he answers the question. To that end it would be great to have a way to disable either the left or the right gesture. I'm currently using $ionicSlideBoxDelegate.enableSlide( false ); as a workaround, but this disables both gestures.

**Comment by Ionitron** [comment]
Greetings @Duffycola!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4250). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4250)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by niyando** [comment]
You could use this
https://github.com/arielfaur/ionic-wizard

**Comment by mlynch** [comment]
We just landed a new slider component that solves this issue. It's in master and will be in 1.2 To use it today, do this:

```html
<ion-slides options="options" slider="data.slider">
  <ion-slide-page>
  </ion-slide-page>
</ion-slides>
```
and your JS:

```
controller('MyCtrl', function($scope) {
      $scope.options = {
        loop: true
      }

      $scope.data = {};

      $scope.$watch('data.slider', function(nv, ov) {
        $scope.slider = $scope.data.slider;
      })

      $timeout(function() {
        // Disables swiping next/prev
        $scope.slider.lockSwipeToNext();
      }, 1000)

});
```
