### ISSUE TITLE
bug: Bug: Native scroll break in Android 4.1

### ISSUE THREAD

**Issue by victorAlvarez** [driftyco/ionic#4252]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.1</span>  <span ionic-webview>webview</span>

<span ionic-description>I updated my application to ionic 1.1.0 to use native scroll with ion-infinite-scroll in all views but does not work on Android 4.1 (In IOS 7.1, 8 and Android 4.4, 5 and 5.0.2 it works perfectly) In the documentation you put that works with Android 4.1+ but not so

The bug is: When data is added to the array in the ng-repeat is updated in the content but not the scroll. I tried with $ionicScrollDelegate.resize(); but still does not work.

Only it allows me to scroll down when I have side menus and open and close one.

I need to know if there is any solution because I have to upload my app to markets.

PD: The problem is not ng-repeat , as also happens with reactJS

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @victorAlvarez!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4252). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4252)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
do you have an example/codepen I could test against?

**Comment by victorAlvarez** [comment]
Hey @mhartington thanks for answering.

I created a basic codepen: http://codepen.io/anon/pen/PqrKQP?editors=101

**Comment by yiqinglan** [comment]
I met the same issue,  native scroll  work well at android 4.4, but not work in android 4.1,4.2, 4,3

**Comment by mhartington** [comment]
Totally forgot that you mentioned android 4.1 -4.3.
Yes this is to be expected. Since neither of those version have proper scroll events, native-scrolling doesn't really work here.

http://blog.ionic.io/native-scrolling-in-ionic-a-tale-in-rhyme/

An option would be to use crosswalk. 
Closing since this is a limitation of the webview.
