### ISSUE TITLE
bug: Side Menu overlapped by iframe on Windows Phone

### ISSUE THREAD

**Issue by ruisilva450** [driftyco/ionic#4254]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>Windows</span>  <span ionic-webview> Phone</span>

<span ionic-description>I have a pretty regular app with side menu and on ion-content I have a iframe pointed to an external URL.
When I try to open the side menu after the iframe is open, it's content overlaps the side menu content. If I try to tap one option from side menu it does the navigation to that option but the iframe is always on top and doesn't move to the side like the header.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ruisilva450!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4254). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4254)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
We will not be supporting WP8 with ionic v1.

**Comment by ruisilva450** [comment]
It happens on WP8.1 also

**Comment by mhartington** [comment]
Same thing, with v1, we won't be supporting windows phone. 
With V2, we're looking at Windows 10 support, but no 8X

**Comment by ruisilva450** [comment]
Roger that
