### ISSUE TITLE
Ionic.io is down!!

### ISSUE THREAD

**Issue by paulogr** [driftyco/ionic#4255]
I cant use ionic deploy or even login in ionic.io

Anyone else?

**Comment by Ionitron** [comment]
Greetings @paulogr!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4255). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4255)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Thanks for the heads up, should be good now.
