### ISSUE TITLE
bug: Website constantly reloading in iframe

### ISSUE THREAD

**Issue by gere0018** [driftyco/ionic#4258]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>My app requires loading a webpage in an iframe. I have a list view with multiple items. When each item is clicked it opens a sub page where the ion-view contains an iframe with a webpage.

sample code from subpages:
``` 
<ion-view>
    <ion-content scroll="true" overflow-scroll="true" class="iframe-wrapper padding" 
           ng-repeat= "item in links | filter: {shortname: whichlink}">
               <iframe data-tap-disabled="true" class= 'webPage' name= "{{ item.shortname }}" 
                   src="" dynamic-url dynamic-url-src="{{item.link}}"></iframe>
     </ion-content>
</ion-view>
```

I fixed my iframe to become scrollable, but the webpage inside it keeps reloading non stop, resetting every time and preventing the user from seeing the content as it goes back to the top of the page every few seconds.
I have no idea why this is happening and how to stop it. Please suggest what i can do.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @gere0018!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
