### ISSUE TITLE
Ionic CLI warning

### ISSUE THREAD

**Issue by candidodmv** [driftyco/ionic#4260]
I'm trying to update Apache Cordova CLi as shown in any Ionic command is executed:

******************************************************
 Upgrade warning - for the CLI to run correctly,
 it is highly suggested to upgrade the following:

 Please update your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

but, even after runt the suggest command is not update. 

This issue is know ? How can I proceed to resolve this problem?

Thanks so much.
![issue-apache-cordova-cli](https://cloud.githubusercontent.com/assets/1034797/9417571/cb6895ac-4823-11e5-8939-3ca683a72571.png)

**Comment by Ionitron** [comment]
Greetings @candidodmv!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4260). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4260)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Try quiting the command prompt and starting it again. Sometimes the terminals need a restart

**Comment by candidodmv** [comment]
I'v done this, without success. :(

**Comment by mhartington** [comment]
Have you logged out/in?

**Comment by candidodmv** [comment]
Yes, several times. Clean  npm cache, and temporary files of windows, but not difference.

**Comment by mhartington** [comment]
Hmm, let's try to uninstall ionic and cordova then add them back
Something along the way must have gotten messed up.

**Comment by candidodmv** [comment]
Can I follow the steps as explained bellow:
http://stackoverflow.com/questions/29428929/how-do-you-completely-remove-ionic-and-cordova-installation-from-mac

**Comment by candidodmv** [comment]
1* npm uninstall cordova ionic
2* npm cache clean -f
3* npm install npm -g
4* npm install cordova ionic

Consider that I'm on Windows 8.1

**Comment by mhartington** [comment]
```
npm uninstall -g ionic cordova
npm cache clean -f
npm install -g ionic cordova
```

**Comment by candidodmv** [comment]
Even after to run npm uninstall -g ionic cordova the prompt recognizes the command "cordova". Is it normal behavior?

**Comment by mhartington** [comment]
No that is not normal, that means there is another version of cordova installed somewhere on your machine. Run `where cordova`, paste the output here.

**Comment by candidodmv** [comment]
Thanks so much because of support Mike. The problem was that, there was more then one installation folder. So, I remove another and run the command npm install -g ionic cordova 

Now is working very fine.
