### ISSUE TITLE
play video from external url

### ISSUE THREAD

**Issue by EduardoNE** [driftyco/ionic#4262]
http://xxxxxxxxxxxxxxxxxxx.com.br/project/content/e591d94d7f.MOV

i'm trying to play a video from a url like this in one timeline but nothing happens
all issues or forums are using youtube videos but that isn`t my case 

i`ve deactivated the $sceProvider and after that no one errors are displayed, but the video still blank

someone knows what i need to do to this works?

**Comment by Ionitron** [comment]
Greetings @EduardoNE!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4262). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4262)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @EduardoNE!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
