### ISSUE TITLE
bug: ion-footer-bar, long title overlaps buttons 

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/ionic#4263]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>browser</span>

<span ionic-description>
**Issue:**
When ion-footer-bar has a very long title it ends up overlapping the button. I imagine the same would happen if title was left aligned (that is currently broken as well, see ticket: https://github.com/driftyco/ionic/issues/3966)

ion-header-bar works as expected.

**Screenshot:**
![image](https://cloud.githubusercontent.com/assets/230182/9423957/19d8ae6e-48da-11e5-9044-d8798fd53aae.png)

**Template:**
```
<ion-view view-title="Purchases">
	<ion-content>
		Content
	</ion-content>
	<ion-footer-bar class="bar-stable">
		<div class="buttons">
			<button class="button button-clear">
				<i class="ion-chevron-up"></i>
			</button>
		</div>
		<h1 class="title">This is a very long title right here, which ends up overlapping buttons</h1>
	</ion-footer-bar>
</ion-view>
```
</span>

**Comment by Ionitron** [comment]
Greetings @biesbjerg!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4263). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4263)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @biesbjerg!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by biesbjerg** [comment]
Hi Ionic Team!

Firstly I want to thank you for Ionic Framework.

Secondly, I want to ask you to reconsider your "close ticket after a certain period of inactivity"-policy.

I see a lot of tickets getting closed because of this, and the issue has rarely been fixed when the ticket is being closed by your bot. I find it really frustrating that you ask me to waste time on creating another ticket (that might also be ignored for another 3 months and then closed?) when it will be identical, since the issue hasn't changed. 

I know, on the surface, it seems like a good way to auto-cleanup old/stale tickets, but I've found myself thinking twice about creating bug reports for this project because of the inactivity in tickets from the maintainers and the auto-closing.

My guess is, like I did, that people will find a workaround that works for their app and won't bother re-creating a new issue. That's a lose for you, and that's a lose for the community.

**Comment by inder243** [comment]
hhfg
