### ISSUE TITLE
docs: Ionic's AngularJS Intellisense in Visual Studio 2015 Tools for Apache Cordova Project

### ISSUE THREAD

**Issue by waynebloss** [driftyco/ionic#4264]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I was not getting Intellisense for Angular inside of `*.js` files in a VS2015 [Tools for Apache Cordova](https://www.visualstudio.com/en-us/features/cordova-vs.aspx) project that uses [Ionic](https://github.com/driftyco/ionic), which bundles it's own copy of Angular.

So, I copied the latest [angular.intellisense.js file](https://raw.githubusercontent.com/jmbledsoe/angularjs-visualstudio-intellisense/master/src/Scripts/angular.intellisense.js) from [this repo](https://github.com/jmbledsoe/angularjs-visualstudio-intellisense) and placed it in my project as `~/www/lib/ionic/js/ionic.intellisense.js`. This worked beautifully after restarting VS (*probably not necessary*) and then activating it in one of my `*.js` files (*by typing `$http.` a few times and then waiting about 10 seconds*). It also works for my own internal services, which reside in separate js files in my `~/www/services` folder.

Just wanted to let others know. Thanks for your work!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @waynebloss!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4264). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4264)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Not really an issue with ionic, so going to close this.

**Comment by waynebloss** [comment]
That's fine thanks, googlers can still find it if you don't delete it. I thought you guys had some relationship with Microsoft after seeing this announcement about [Ionic templates for Visual Studio](http://blog.ionic.io/announcing-ionic-templates-for-visual-studio/), so I figured anyone using them might want to know this.
