### ISSUE TITLE
bug: Cannot read property 'enableMenuWithBackViews'

### ISSUE THREAD

**Issue by fabiancarlos** [driftyco/ionic#4265]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>When i click on a link on my app that navigate to another page, this error appears on console, everything is running normal, and the app dont crash, but is annoying, and i dont know what is causing it. Its some bug?

TypeError: Cannot read property 'enableMenuWithBackViews' of undefined.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @fabiancarlos!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4265). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4265)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Codepen that demonstrates this?

**Comment by MoemenMostafa** [comment]
I am facing this exact error too

**Comment by szuzul** [comment]
+1 for this one

**Comment by mhartington** [comment]
>Codepen that demonstrates this?

**Comment by fabiancarlos** [comment]
Sorry for respond to late, but the error is caused by a unitilized menu-toggle="left" on my header button, that before i use a side menu, but now i use buttons on header.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by fabiancarlos** [comment]
my previous comment is the cause of the error, thanks.

**Comment by aleksander351** [comment]
@fabiancarlos How did you solve this? If you remove menu-toggle="left", then your menu does not work anymore?
