### ISSUE TITLE
bug: ion-tabs don't recognize tabs-icon-bottom class

### ISSUE THREAD

**Issue by nicopace** [driftyco/ionic#4266]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Tested on chromium:
http://play.ionic.io/app/6bcc8b4dd1cc</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @nicopace!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4266). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4266)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
`tabs-icon-bottom` doesn't do anything.

http://play.ionic.io/app/6faac739faa2

You had the tabs structure setup incorrectly.

Also, tabs-icon-bottom is not mentioned any where in our docs.
http://ionicframework.com/docs/components/#tabs

**Comment by nicopace** [comment]
@mhartington it appears many times in the repo, and it works in that example!
https://github.com/driftyco/ionic/search?utf8=%E2%9C%93&q=tabs-icon-bottom

**Comment by mhartington** [comment]
Probably something that we won't be adding to ion-tabs.
Not really a typical design for tabs.

**Comment by nicopace** [comment]
Isn't it?
I think that it is not only useful, but also it is orthogonal... almost all elements allow to choose where to put the icons you associate, but the ion-tab (Buttons, list elements, bars,... )... also, it is already there... it just don't work for ion-tabs , it works with it's non-directive cousin, the class 'tab'...

**Comment by mhartington** [comment]
orthogonal .... do you mean having to involve right angles :grin: 

Hmm, fair enough. After playing around with it, seems that there is a decent scss only solution that I could look into. 

http://codepen.io/mhartington/pen/mJNMJa?editors=010

Will look into this during this week.

**Comment by nicopace** [comment]
orthogonal means that you can use icons-bottom to every element, no matter which one, and expect the behaviour that it says it will do.
That helps a language to be easier to use, as it becomes intuitive.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
