### ISSUE TITLE
bug: back using swipe bug on sidemenu app 

### ISSUE THREAD

**Issue by jbdemonte** [driftyco/ionic#4268]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>From this post: http://forum.ionicframework.com/t/white-content-when-scrolling-from-left-side-of-the-screen-only-on-a-side-menu-app-on-ios/30858

back using swipe is available on sidemenu app and give strange behaviour: https://vid.me/Agdn

I also noticed that, in my app, where all view have cache-view="false", the back swipe return on an empty page</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jbdemonte!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4268). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4268)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @jbdemonte!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
