### ISSUE TITLE
perf: scroll: poor scrolling down on wp8

### ISSUE THREAD

**Issue by marcio199226** [driftyco/ionic#4270]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>hi guys our team deployed app for android and ios but now we have to port this app to wp8 too
All features works properly but i notice a poor scroll i have tried js and native scrolling but in the first case i have a poor scrolling up and down in the second case the down scroll i worth than with js scrolling but when i want to scroll up it works like a charm do you know how can i fix it?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @marcio199226!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4270). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4270)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @marcio199226!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
