### ISSUE TITLE
docs: release date is wrong in the release notes for v1.1.0

### ISSUE THREAD

**Issue by ssreekanth** [driftyco/ionic#4273]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Visit https://github.com/driftyco/ionic/releases/tag/v1.1.0. The date was mentioned incorrectly (shown in bold below) in the release notes.

1.1.0 "xenon-xerus" **(2015-06-30)**

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ssreekanth!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4273). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4273)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by stianjensen** [comment]
Seems to be fixed: https://github.com/driftyco/ionic/commit/df589f630283f206bba974bee3b9ccf99d9a3937

**Comment by ssreekanth** [comment]
Still seems to be wrong at the url mentioned above..

**Comment by mhartington** [comment]
Can't really fix that with out un-publishing that release.
Not the end of the world though, so I think we'll be ok.
