### ISSUE TITLE
bug: ionic popover item list click/tap sensitive

### ISSUE THREAD

**Issue by faicalcarvalho** [driftyco/ionic#4277]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>An item list within a popover does not respond when clicked (change backcolor). It does what I want, however I don´t know if I´ve clicked or not.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @faicalcarvalho!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by npasparuhov** [comment]
I have the same issue. I guess only including a button into the popover is ok, but trying to add ng-click or href into items or other type of elements it's not working...
