### ISSUE TITLE
Ionic 1.1.0: breaks navigation

### ISSUE THREAD

**Issue by jyotiraj** [driftyco/ionic#4278]
Adding the ionic.bundle.js for 1.1.0 breaks the following in my project
* Navigation header - loses color and text while switching tabs
* tabs navigation

**Comment by Ionitron** [comment]
Greetings @jyotiraj!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4278). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4278)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
1.1.0's big upgrade was switching to angular 1.4x. 
Do you have an minimal example in a codepen/plunkr/jsbin?

**Comment by Ionitron** [comment]
Greetings @jyotiraj!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
