### ISSUE TITLE
bug: ion-nav-view DOM leaking in WP8

### ISSUE THREAD

**Issue by entr0cks** [driftyco/ionic#4279]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Happens on Windows Phone 8 when navigating between views with states and ion-nav-view element/directive. Did notice it in the sidebar template as well.
I'm aware wp8 is not officially supported, just letting you guys know of an issue and if someone knows how to navigate the source, might be an easy fix which will help out a lot!

Ion-views' are correctly cached and removed as needed, but inside the ion-nav-view the ion-view's child tree is recursively added to ion-nav-view and accumulates over time - with each navigation.

Something like this would be the result after one navigation, later the child trees are just added to the ion-nav-view. 
```
<ion-nav-view...>
   ...
   <div...> // inside scroll
   <scroll...> // inside ion-content
      <div...>
      ...
   <ion-content...> // inside view
      <scroll...>
         <div..>
         ...
   <ion-view...> // new view itself - which is removed correctly
      <ion-content...>
         <scroll...>
            <div...>
            ...
   <ion-view ... cached>
```

**Comment by Ionitron** [comment]
Greetings @entr0cks!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4279). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4279)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by entr0cks** [comment]
Resolved, not associated with ionic.
