### ISSUE TITLE
Android JellyBean support

### ISSUE THREAD

**Issue by uxder** [driftyco/ionic#4280]
What is the state of Ionic's support for 4.3 Jellybean?  The docs say 4.0 and up but it seems like basic things are not working.  

This includes the ionic grid (.row and nested .col) along with the ionicPopup not being positioned in the correct place. It appears it is primarily css related issues.

**Comment by Ionitron** [comment]
Greetings @uxder!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4280). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4280)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by uxder** [comment]
Okay NM.  This seems to be an issue with my gulp autoprefixer settings.
