### ISSUE TITLE
Running "ionic" CLI gives "Cannot find module 'colors'"

### ISSUE THREAD

**Issue by cyraid** [driftyco/ionic#4282]
I've installed Ionic 1.6.4 through NPM, and it seems when I want to run it, it gives the error "Cannot find module 'colors'". Just installed it today. I'm using Node.JS 0.12.7, and NPM 2.11.3

O.S. Is Ubuntu 15.04, 64bit

**Comment by Ionitron** [comment]
Greetings @cyraid!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4282). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4282)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-cli#574
