### ISSUE TITLE
bug: Background toggle is clickable when popup is open

### ISSUE THREAD

**Issue by jason-engage** [driftyco/ionic#4285]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I don't think a user should be able to click a background toggle while popup is open. 

Check out the codepen:

http://codepen.io/jason-engage/pen/zvOPrg</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jason-engage!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4285). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4285)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
https://youtu.be/hou0lU8WMgo

Thanks for pointing this!

**Comment by eSachin** [comment]
Ionic Adds "popup-open" class to body when popup opens. So for this issue we can try 

.popup-open .item-toggle * {
  	pointer-events: none;
  }

So that all the toggles are not clickable.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
