### ISSUE TITLE
bug: Disable Android keyboard suggestion

### ISSUE THREAD

**Issue by woniesong92** [driftyco/ionic#4286]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>When an input is focused, the suggestion bar comes up along with the keyboard. This gives app screen a jitter for 100ms. I looked everywhere to find ways to disable the suggestion bar on a keyboard, and I found

1. `<input autocorrect="off" autocapitalize="off" autocomplete="off">`
2. Setting input type="email"

Unfortunately, neither of them worked. I feel like there must be a way to disable it, as others must have experienced the same issue. Could you provide some insight?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @woniesong92!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4286). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4286)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
I don't think there's anything we can do about this. This is a system setting and we don't really have control over it. Unfortunately there isn't anything we can do here.
