### ISSUE TITLE
Ignore a slide

### ISSUE THREAD

**Issue by kapil019** [driftyco/ionic#4287]
Can i ignore a slide in slide box.

I have a slde that show after login, So i have added condition like
```
<ion-slide ng-if="isUserLoggedin">
----------
SLIDE content
---------
</ion-slide>
```

But this is not working, 
I can not remove this slide, because after login i need to show this. So is there any way to ignore a slide?

**Comment by Ionitron** [comment]
Greetings @kapil019!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4287). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4287)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by clnhll** [comment]
I had this problem, to fix it I made a totally separate slide box with all the same slides, minus the one I wanted to hide.
so like
```
	<ion-slide-box ng-show="showThirdSlide">
		<ion-slide>First</ion-slide>
		<ion-slide>Second</ion-slide>
		<ion-slide>Third</ion-slide>
	</ion-slide-box>
	<ion-slide-box ng-hide="showThirdSlide">
		<ion-slide>First</ion-slide>
		<ion-slide>Second</ion-slide>
	</ion-slide-box>
```
Doing this gives you a console error every time you change slides because of the hidden slide box unfortunately, but it works.
Would love a better fix.

**Comment by mlynch** [comment]
I'm going to close since I don't know if this needs to be backed in, but you should be able to do it by trying something like:

Hey everyone, we just landed a new slider component that solves this issue. It's in master and will be in 1.2 To use it today, do this:

Will be back porting the delegate to work with it soon, but going to close since this should be solved now.

```html
<ion-slides options="options" slider="data.slider">
  <ion-slide-page ng-repeat="slide in slides" ng-hide="slide.hidden">
  </ion-slide-page>
</ion-slides>
```
and your JS:

```
controller('MyCtrl', function($scope) {
      $scope.options = {
        loop: true
      }

      $scope.data = {};

      $scope.$watch('data.slider', function(nv, ov) {
        $scope.slider = $scope.data.slider;
      })

      $timeout(function() {
        $scope.slides[0].hide = true;
        $scope.slider.update();
      })

});
```
