### ISSUE TITLE
bug: Ionic app on tomcat server

### ISSUE THREAD

**Issue by sarbj33t** [driftyco/ionic#4288]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi everyone, 

I have made an ionic app and tried to deploy it on tomcat server. The application works fine in a tablet device but when I run it on google chrome in my desktop, many features of ionic are not working such as the vertical scroll. Please help me out if you guys have any idea.

regards,
Sarbjeet</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @sarbj33t!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4288). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4288)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by lobobobo** [comment]
Please tell me the steps to diploy ionic app on tomcat server

**Comment by mhartington** [comment]
This is beyond the scope of the repo, and not the right place to open an issue. 
You may want to ask on SO or elsewhere.
