### ISSUE TITLE
bug: ion-slide-box doesn't load the relative slide inside a view

### ISSUE THREAD

**Issue by lucapantano** [driftyco/ionic#4289]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,
I'm not expert of Ionic...

I have a problem with the ion-slide-box (maybe it is easy).

I have a ion-tabs and in the first tab (that is hidden) I want to show a ion-slide-box.
I added the relative code for the slide inside a template. The slider is generated but each single slide disappear...

If I move the code of the ion-slide-box inside the tabs, it works...

Do you know why?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @lucapantano!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4289). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4289)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Codepen/Plunkr example?

**Comment by lucapantano** [comment]
Here it works:
http://lucapantano.com/altro/ionic/example-that-works/index.html

The "welcome tab code" is in the "http://lucapantano.com/altro/ionic/example-that-works/templates/tabs-welcome.html"


Here the example that doesn't work:
http://lucapantano.com/altro/ionic/example-not-working/

The "welcome tab code" is in a separate view named "http://lucapantano.com/altro/ionic/example-that-works/templates/welcome.html"

**Comment by mhartington** [comment]
Please try to isolate the issue in a codepen/plunkr/jsbin.
I do not need your whole project.

**Comment by Ionitron** [comment]
Greetings @lucapantano!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
