### ISSUE TITLE
bug: collection-repeat fails to compute the height of repeated elements when not provided.

### ISSUE THREAD

**Issue by Jinoooo** [driftyco/ionic#4290]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>403   169063   error    Error: collection-repeat tried to compute the height of repeated elements "event in events | orderBy: [sortByStatus, sortByName]", but was unable to. Please provide the "item-height" attribute. http://ionicframework.com/docs/api/directive/collectionRepeat/
    at refreshDimensions (http://192.168.0.15:8100/lib/ionic/js/ionic.bundle.js:50464:17)
    at http://192.168.0.15:8100/lib/ionic/js/ionic.bundle.js:50340:62
    at Scope.$digest (http://192.168.0.15:8100/lib/ionic/js/ionic.bundle.js:22985:36)
    at Scope.$apply (http://192.168.0.15:8100/lib/ionic/js/ionic.bundle.js:23198:24)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Jinoooo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4290). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4290)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @Jinoooo!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by cesarin3134** [comment]
@Ionitron I have the same problem with collection-repeat (ionic version 1.7.13)

` <ion-item collection-repeat="item in modalData.searchListItem | filter:search" ng-click="ctrl.doActionOnClick(item.codice)">
                <span ng-if="searchModalType == 'dutyCodes' || searchModalType == 'officeCode'">{{item.codice}}  </span>{{item.desc}}
            </ion-item>`

and I got the same error. is there any way to fix it ??
