### ISSUE TITLE
bug: Kindly update the ionicons repo

### ISSUE THREAD

**Issue by MrHakala** [driftyco/ionic#4291]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Ionic and ionicons repos seem to be out of sync. Chat and chevron icons are missing and font build fails due to missing charset (utf-8) definition(s) in scss file(s).</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @MrHakala!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4291). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4291)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Not sure what you mean, can you explain?
The latests Ionicons are already in ionic and in sync

https://github.com/driftyco/ionicons

**Comment by MrHakala** [comment]
In the ionic repo the ionicons.scss -file has a charset definition 
whereas in the ionicons repo it does not. This lead me to believe their 
out of sync. (My build/clone also seemed to be missing some icons).

You could consider "Antonie's" pull request 
(https://github.com/driftyco/ionicons/pull/216).
Haven't tried it but I'm still plagued by the SASS 3.4.X bug he 
mentions. (CSS files aren't built correctly)

-Miika

**Comment by mhartington** [comment]
No, the ionicons repo and the icons in the ionic repo are in sync. No issue here.

**Comment by MrHakala** [comment]
This file has no charset definition: 
https://github.com/driftyco/ionicons/blob/master/scss/ionicons.scss
where as this has: 
https://github.com/driftyco/ionic/blob/master/scss/ionicons/ionicons.scss
(16 lines vs. 17 lines)

**Comment by mhartington** [comment]
Please look at the issue where this was needed.

https://github.com/driftyco/ionic/commit/d027dfe2e7157da4bd38a39e5e3ff7d2dc1b557d

https://github.com/driftyco/ionic/pull/3241

This was for scss compliation, but has no reference to any difference in icons.
If you want to add the charset to the ionicons file, you'll want to open an issue or PR on the ionicon repo, not here. 

https://github.com/driftyco/ionicons
