### ISSUE TITLE
docs: starting.html docs do not match current blank template starting point

### ISSUE THREAD

**Issue by rearadmiral** [driftyco/ionic#4292]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I was following the tutorial here: http://ionicframework.com/docs/guide/starting.html

When you run:

```
ionic start todo blank
```

In the latest version of ionic, 1.6.4, the blank seed project already contains index.html and loads app.js, and the global ng-app is named "starter"

This doesn't match the instructions given, which tell you to create those files.

I've used angular, so I knew how to change them to match but maybe not everyone will understand, especially if they are new to these technologies.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @rearadmiral!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4292). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4292)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-site#282
