### ISSUE TITLE
bug: Side menu closes on input focus

### ISSUE THREAD

**Issue by edehlinger** [driftyco/ionic#4294]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

When an input is in the side-menu, the focus on the input opens the keyboard and closes the side-menu. It happens only if the side menu has an expose-aside-when directive. Removing expose-aside-when solves the issue.

I'm seeing this on android 4.4.4 using Crosswalk and Ionic 1.1.0.

Here's a codepen based on closed issue #2434 (but the problem still exists) :
http://codepen.io/anon/pen/PPozMa</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @edehlinger!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4294). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4294)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Using the latest version of Ionic, android 4.4, and crosswalk, I wasn't able to replicate this.
Used the exact same codepen as you, but nothing.

Anymore info you could provide?

**Comment by edehlinger** [comment]
It's happening on small viewports. I toggle the left menu, touch the input and when the keyboard shows up the side menu hides. Tried it in ionic view app, same behaviour. I'm also having this problem on another phone with android 4.2.2.

Tried it on iOS : the side menu stays open after focus, it's working perfectly.

I made another test on android : I launched the app on the phone and used Chrome Inspector on my desktop to inspect the app on the android connected phone. Using screencast on my desktop chrome, i open the menu and click on the input. This does not make the keyboard show up and the menu stays open after the input gets focus. But if i touch the input on the phone screen, the keyboard then shows up and the side menu closes.

And if I remove the 'expose-aside-when' directive, it works in all cases.

**Comment by edehlinger** [comment]
I've been investigating a bit with chrome debugger and it seems that when the keyboard shows up it triggers a resize event on $window :
- the onResize callback from 'exposeAsideWhen' directive tests the media query for the expose aside and since the screen is not large enough, it calls sideMenuCtrl.exposeAside() with false.
- the exposeAside method then calls self.close()
- finally the side menu closes.

I've read that the keyboard on iOS does not trigger the same resize, it may explain why it works on my iphone.

In fact, if you try the codepen on your desktop browser and reduce the window size so that the side menu is hidden, then toggle the side menu by clicking on the nav-icon, and then, with the menu opened, you resize your browser window vertically, the side menu closes himself the same way it does when the keyboard appears in android.

**Comment by Ionitron** [comment]
Greetings @edehlinger!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by Nightbr** [comment]
Hey, exactly same problem here with ionic 1.3.1 and crosswalk 2.0.0 (core 20+).
When I have exposeAsideWhen directive on my sideMenu if I have a field which open the keyboard it closed my sideMenu. If remove all exposeAsideWhen directive no problem.
Work fine on iOS
