### ISSUE TITLE
Feature request: Set Small Icon for Android Notifications

### ISSUE THREAD

**Issue by stevenmusumeche** [driftyco/ionic#4295]
As of Android 5.0, notification icons are displayed differently.  It would be nice to have the ability to set a notification icon/small icon separately from the app icon in config.xml.

**Comment by Ionitron** [comment]
Greetings @stevenmusumeche!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4295). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4295)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
You might want to make an issue with the cordova team.

http://cordova.apache.org/

This has nothing to do with the css/js for ionic.
