### ISSUE TITLE
Application Error The connection to the server was unsuccessful.

### ISSUE THREAD

**Issue by candidodmv** [driftyco/ionic#4296]
My Ionic application is not loading and showing the follow message as shown attach image bellow.

![image](https://cloud.githubusercontent.com/assets/1034797/9589605/dc741706-5005-11e5-9194-87a299171c48.png)

The full error message is:

Application Error
The connection to the server was unsuccessful (file:///android_asset/www/index.html)

I reinstall Ionic and update all dependencies, but the problem persist, see my ionic info output :
Your system information:

Cordova CLI: 5.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
OS: Windows 8.1
Node Version: v0.12.7

**Comment by Ionitron** [comment]
Greetings @candidodmv!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4296). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4296)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by dpaniagua0** [comment]
I have the same issue, can you help me with that?

**Comment by candidodmv** [comment]
I solved this problem reinstalling everything in another machine with another emulator [Genymotion](https://www.genymotion.com/) is good choice.

**Comment by Manish905** [comment]
You can also try by adding preference in config.xml file. i use bellow code and my problem has been solved.

<preference name="loadUrlTimeoutValue" value="700000" />

**Comment by raugaral** [comment]
Remove the external scripts.
Change this:
`<script src="http://code.highcharts.com/highcharts-more.js"></script>`
to 
`<script src="project_folder/highcharts-more.js"></script>`
