### ISSUE TITLE
bug: ion-content height not updated after keyboard height changes on iOS8

### ISSUE THREAD

**Issue by Klaster1** [driftyco/ionic#4300]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>It seems that keyboard height change doesn't change ion-content height inline style, even though it probably should. Due to this, the following scenario causes extra space or cropping at the bottom:

1. Add email, tel, date and text inputs on a page. Make sure it has scroll when keyboard's open.
2. Click on text input, scroll view to the bottom.
3. Click click on tel input. The keyboard will change it's height.
4. Scroll down.

I was able to reproduce the issue on iOS emulator running 4s and 6 images, and also live iPhone 6 with iOS8. You don't really need any markup except for a bunch of inputs.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Klaster1!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4300). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4300)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Please provide a codepen for us to test against.

**Comment by Klaster1** [comment]
http://codepen.io/Klaster_1/pen/YyPGeY

**Comment by Ionitron** [comment]
Greetings @Klaster1!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
