### ISSUE TITLE
bug: collection-repeat calculates item-width 1px too short

### ISSUE THREAD

**Issue by ThinklabsGbR** [driftyco/ionic#4301]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>when providing a width for a collection-repeat, even when set to 100%, ionic always calculates the item-width 1px too short, so that a 1px border appears on the left of the list. Here's a pen that helps to visualize the issue:

http://codepen.io/anon/pen/yYLPyE

I was not able to overcome the issue with pure css, as ionic calculates item width on the fly when displaying new items, making any changes disappear when the collection "repeats".</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ThinklabsGbR!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
