### ISSUE TITLE
bug: popup.close() not removing the popup element from DOM

### ISSUE THREAD

**Issue by avainola** [driftyco/ionic#4304]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In ionic 1.1 you have added !$ionicModal.stack.isHighest(self) condition to self.remove function.
if (self.removed) return;  --->  if (self.removed || !$ionicModal.stack.isHighest(self)) return;
I run into a problem when I open a popup from click on another popup.
When first popup is opened:
1) the self.show function is called and object is added to the $ionicModal.stack.
When second popup is opened from click on the first popup:
1) first popup self.hide is called and object is removed from $ionicModal.stack.
2) second popup self.show is called and object is added to the $ionicModal.stack.
When popup.close() is called on the second popup:
1) first popup self.show is called and object is added to the $ionicModal.stack.
2) second popup self.remove is called, but is returned, because $ionicModal.stack.isHighest(self) === false (first popup is the highest object on the stack)

I am not sure if i am somehow misusing it or it is a bug!?
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @avainola!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4304). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4304)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by simplesmiler** [comment]
Sounds like leaving the first popup open would mitigate the issue entirely.

**Comment by avainola** [comment]
@simplesmiler could you please explain what do you mean by leaving the first popup open?
As i wrote in the first post, i'm not explicitly closing the first popup, but opening new popup when user clicks on an element on the first popup. Hiding of the first popup is handled in the ionic library.
