### ISSUE TITLE
bug: Cordova whitelist links

### ISSUE THREAD

**Issue by jeanmatthieud** [driftyco/ionic#4305]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Ionic: 1.1
Platforms: Android / iOs
Related to: #3647

"geo" links are not clickable, event with the new or old whitelist plugin configured.
Could be added as "tel" links : https://github.com/driftyco/ionic/commit/db730f16a723a5c0b51465cda466345aaabb7e07

It would be great to be able to use every link supported by cordova whitelist plugin: 
https://github.com/apache/cordova-plugin-whitelist</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jeanmatthieud!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4305). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4305)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
![](http://img.pandawhale.com/post-49538-you-are-technically-correct-th-Jw0j.jpeg)

Fair enough, should be able to add those in no problem. 
If you want to make a PR to add them in, that would be great! 
Otherwise, I can add that in the Friday.

**Comment by jeanmatthieud** [comment]
Tanks
