### ISSUE TITLE
ion-slide-box 'does-continue' not work

### ISSUE THREAD

**Issue by gary-feng** [driftyco/ionic#4309]
I have an issue which I'm not seeing anywhere else on github/stack overflow.
Ive made an slide box with ng repeat. The source images will be loaded after initialization. So I use $ionicSlideBoxDelegate.update() to update slide box.
However it cannot loop. The slide box auto play from first image to the last image then it stop. Even though I have set does-continue="true".

```javascript
<ion-slide-box delegate-handle="img-viewer" auto-play="true" does-continue="true">
      <ion-slide ng-repeat="i in imgs">
        <img ng-src="{{i.url}}">
      </ion-slide>
</ion-slide-box>
```

```javascript
$http.get('').success(function (data) {
        $scope.imgs = data.imgs;
        $ionicSlideBoxDelegate.$getByHandle('img-viewer').update();
      })
```

**Comment by Ionitron** [comment]
Greetings @gary-feng!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4309). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4309)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by anasbud** [comment]
I had the same problem. I found a nice fix in a post somewhere...

You just have to add an ng-if="imgs" in your ion-slide-box. This way, the slidebox will not be created until data is available.

Hope it will be enough :+1:

**Comment by gary-feng** [comment]
Cool. It works perfectly.
@anasbud Thank you very much for your help.

**Comment by anasbud** [comment]
:)

**Comment by Ben07** [comment]
@anasbud Thank you very much! I use ng-if="imgs.length" and update() function then it works.

**Comment by mlynch** [comment]
Hey everyone, we just landed a new slider component that solves this issue. It's in master and will be in 1.2 To use it today, do this:

```html
<ion-slides options="options" slider="data.slider">
  <ion-slide-page>
  </ion-slide-page>
</ion-slides>
```
and your JS:

```
controller('MyCtrl', function($scope) {
      $scope.options = {
        loop: true
      }

      $scope.data = {};

      $scope.$watch('data.slider', function(nv, ov) {
        $scope.slider = $scope.data.slider;
        // If you need access to the slider
      })
});
```
