### ISSUE TITLE
Microsoft Edge compat

### ISSUE THREAD

**Issue by csuwildcat** [driftyco/ionic#4311]
Hey there Ions,

I am working on assessing, cataloging, and triaging library compat for Microsoft Edge and Windows universal Web apps. I heard there may be issues with Ionic on our new platform/browser, and wanted to see if I could lend a hand (assuming there are indeed outstanding issues). Please let me know if there's anything I can look into for you, or escalate with the product teams. I am here to help, so feel free to drop me a line!

**Comment by Ionitron** [comment]
Greetings @csuwildcat!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4311). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4311)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Sorry for Ionitron, he can be a bit over eager. Let's definitely chat as we wanted to dig in here with v2. I'll email you here in a min

**Comment by ghenry22** [comment]
I am currently trying to port my ionic app over to a Windows 10 universal web app and it has been surprisingly smooth with a few exceptions.  I have only 1 that is ionic specific:

collection-repeat in a windows universal app targeting windows 10.  Just shows a blank white page, if I inspect the dom in visual studio 2015 I can see the data for all of the items in the collection, but nothing is displayed.

If I simply change to ng-repeat instead then everything displays as expected but the performance isn't there.  If there was a quick fix for this it would be brilliant for getting my ported over.

The same code and backend is working perfectly on ios and android.

the app is SubStreamer on the apple and play stores for reference.

**Comment by mlynch** [comment]
Thanks for letting us know, we are targeting 1.2 for this.

**Comment by mlynch** [comment]
Closing and tracking #4728
