### ISSUE TITLE
feat: Can't enable/disable side menu constant expose

### ISSUE THREAD

**Issue by stephencavell** [driftyco/ionic#4312]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://codepen.io/anon/pen/VvYYPz

I would like the option to change whether the side menu persists on the user side and JS.  It seems 'expose-aside-when' is the only way to make it persist, why can't that be set to a boolean? Or why isn't the side menu hidden when 'is-enabled'=false?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @stephencavell!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
