### ISSUE TITLE
perf: Native scroll in collection-repeat

### ISSUE THREAD

**Issue by danicomas** [driftyco/ionic#4313]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Collection repeat should have native scroll enabled :D</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @danicomas!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4313). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4313)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Collection repeat requires scroll events, which not all mobile webview have, so it's not possible at the moment.

**Comment by danicomas** [comment]
@mhartington And is not possible enable it with the device which can do it?

**Comment by mhartington** [comment]
Not at the moment. It would require a lot of refactoring to collection repeat.

**Comment by danicomas** [comment]
Ok but you have to know that the experience is not all fluent that it could be.
