### ISSUE TITLE
docs: add typescript support via d.ts file

### ISSUE THREAD

**Issue by jfspencer** [driftyco/ionic#4315]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am converting my ionic project to typescript for better code management. There are others that have started a d.ts file for ionic but they all are out of date. I am willing to write a d.ts file that is up to date for ionic 1.1. Would there be a place for it in this repo?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jfspencer!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4315). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4315)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
A lot of people use DefinitelyTyped for managing their definition files, so I think that would be a good place.

There's already a conversation over there.

https://github.com/borisyankov/DefinitelyTyped/issues/4337

As well as some work by another dev here, though it looks abandoned.

https://github.com/danibo86/ionic-typescript-definitions/blob/master/beta14/ionic.d.ts

**Comment by jfspencer** [comment]
great! thanks for the issue link. I'll get the ball rolling there.
