### ISSUE TITLE
nav-bar-buttons not working properly sometimes when switching between states

### ISSUE THREAD

**Issue by Freundschaft** [driftyco/ionic#4319]
when I switch between different states, the ng-click actions on the nav-bar-buttons sometimes dont get associated with the respective functions in the state scope.
I am suspecting that this is happening because the ion-nav-bar buttons are outside of the ion-view.
inside the view all the click handlers are associated without problems, but the nav-bar-buttons are dead.
is this a known bug?

**Comment by Ionitron** [comment]
Greetings @Freundschaft!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4319). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4319)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
