### ISSUE TITLE
Support pagination in Tab controller

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic#4320]
Would be cool if you could support pagination in the tab controller. By that I mean supporting a large number of tabs where you would click "More" or some such to see additional tabs. 

See this SO question for why I'm suggesting this: http://stackoverflow.com/questions/32413019/in-ionic-how-can-i-have-10-tabs-as-main-navigation-but-only-show-4-and-a-more

**Comment by GenesioValois** [comment]
+1

**Comment by leonardobazico** [comment]
a good option is turning able to scroll tabs

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#22
