### ISSUE TITLE
bug: cannot install ionic

### ISSUE THREAD

**Issue by Nehme-roumani** [driftyco/ionic#4322]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>npm ERR! tar.unpack untar error /tmp/npm-933-47afcc08/registry.npmjs.org/npm/-/npm-2.1.3.tgz
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "ionic" "--registry" "http://registry.npmjs.org"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.1

npm ERR! unexpected eof
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nehme/npm-debug.log
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Nehme-roumani!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4322). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4322)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Hmm this looks like an error on npms side. 
>npm ERR! /Users/nehme/npm-debug.log

What does that log file say?

**Comment by camabeh** [comment]
Same problem on Linux, Ubuntu 15.04, node installed via NVM.

Here is output from `npm-debug.log`
https://gist.github.com/camabeh/10d99819312d90851c3f

**Comment by bineeshmvarghese** [comment]
Solution

Follow the steps
1. Install all necessary dependencies.
http://ionicframework.com/docs/guide/installation.html
2. Uninstall node.js from PC if already installed
3. Restart PC
4. Download and Install node.js (MSI Installer) from http://nodejs.org/dist/v0.10.38/ for x86 or http://nodejs.org/dist/v0.10.38/x64/ for x64
5. Right-click Command prompt, and then click Run as administrator.
6. Install Cordova using the command: npm install -g cordova
7. Finally install Ionic Framework using the command: npm install -g ionic
8. Reinstall nod.js http://nodejs.org/dist/v0.12.7/ for x86 or http://nodejs.org/dist/v0.12.7/x64/ for x64

Done!

**Comment by mhartington** [comment]
Closing as there has been no reply from the original poster.
