### ISSUE TITLE
bug: Ionic tab display bug?

### ISSUE THREAD

**Issue by NgYueHong** [driftyco/ionic#4324]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am trying to do a hybrid app using ionic with the structure that look like this:

    #/app                 (sidemenu.html)
    #/app/noTabContent1   (notab-content1.html)
    #/app/noTabContent2   (notab-content2.html)
    #/app/tab1            (tab1.html)
    #/app/tab1/content1   (tab1-content1.html)
    #/app/tab1/content2   (tab1-content2.html)
    #/app/tab2            (tab2.html)
    #/app/tab2/content1   (tab2-content1.html)
    #/app/tab2/content2   (tab2-content2.html)

The problem is that, it seems like conflict between the tab page. For example, if I first visit `tab1` content page, then I go visit `tab2` content page later on, it will still display `tab1` content. If I visit `tab2` content page first, it will always display `tab2` page no matter how I try to access `tab1` page.

Why is it like that? Is my structuring wrong? Or, it is ionic bug? How can I overcome it?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @NgYueHong!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4324). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4324)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by NgYueHong** [comment]
I have created a codepen (http://codepen.io/anon/pen/LpVVOr?editors=101) for easier understanding the situation.

**Comment by vamsivarikuti** [comment]
@NgYueHong This is not a problem with ionic. 

    `.state('app.content1', {
        url: '/content1',
        views: {
          'menuContent': {
            templateUrl: 'templates/content1.html'
          }
        }
      })`

    `.state('app.tab.content1', {
       url: '/content1',
       views: {
         'tab-Content': {
           templateUrl: 'templates/content1.html'
         }
       }
     })`

You are using `app.tab.content1`, but there is no `app.tab` abstract state which will act as parent. So this state is not possible.

You have used same url `/content1` for both the states under a single parent `/app`. The final url of both the states is `/app/content1`. Only one state will be mapped to one url.

Please refer to ui-router documentation for more details https://github.com/angular-ui/ui-router/wiki/Nested-States-and-Nested-Views

**Comment by Ionitron** [comment]
Greetings @NgYueHong!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
