### ISSUE TITLE
bug: CSS item class border change doesn't work on device

### ISSUE THREAD

**Issue by edmamerto** [driftyco/ionic#4328]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>My CSS item class border change works fine on emulator and browser but not on the iOS device</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @edmamerto!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4328). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4328)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Codepen, plunkr, jsbin? Need some example

**Comment by edmamerto** [comment]
css:

.type-for-sale{
	border-top: 5px solid #e59859 !important;
}

html:

<div class="item item-avatar type-for-sale">
 <img src="#"></img>
<h2>user</h2>
</div>

**Comment by mhartington** [comment]
This is from an actual device.

![img_3336](https://cloud.githubusercontent.com/assets/2835826/9722288/7c0150f0-5578-11e5-8f34-2f229d48f372.PNG)


Looks fine to me.

**Comment by edmamerto** [comment]
hmm that's so weird thanks!
