### ISSUE TITLE
feat: radio button icon for both unchecked and checked status

### ISSUE THREAD

**Issue by martov1** [driftyco/ionic#4329]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>my project required custom icons on both checked and unchecked radio buttons, ionic seemed to only support icons on checked radio buttons, so i copied the radio button directive into another directive and changed it so that it would allow for both checked-icon and  unchecked-icon attributes, it's working great on my project, so i wanted to contributed it into ionic.

I will review all the required docs about contributing and try to get a pull request up, i could not find any other issue with a similar proposal.

Here is a ionic playground test of the directive
http://play.ionic.io/app/824b61834b3e</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @martov1!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4329). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4329)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by alexweber** [comment]
:+1: This is useful, thanks!

**Comment by Ionitron** [comment]
Greetings @martov1!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
