### ISSUE TITLE
bug: audio not clickable in Firefox and Safari

### ISSUE THREAD

**Issue by tiaozi0912** [driftyco/ionic#4330]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Included the ionic javascript (v1.1.0),  the audio tag became not clickable in desktop Firefox and Safari
http://jsbin.com/fakarihoyu/1/edit?html,output

It works in desktop Chrome</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @tiaozi0912!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4330). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4330)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
You need to add `data-tap-disabled="true"` to the audio Element.
http://jsbin.com/siqozo/2/edit?html,js,output

Chrome will properly handle the right tap events, where as safari and firefox will not

**Comment by Carlosps** [comment]
Thanks a lot
