### ISSUE TITLE
bug: Menu with exposeAsideWhen hides after opening modal

### ISSUE THREAD

**Issue by lewisl9029** [driftyco/ionic#4331]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I noticed in my app that the side menu closes every time a modal is shown. 

Removing expose-aside-when from the menu results in the menu staying open after showing a modal, which is why I believe the menu hiding behavior is in fact a bug (plus I don't think it makes sense in terms of UX).

I made the following codepen to demonstrate issue:
http://codepen.io/lewisl9029/pen/meJwar

Simply resize the browser width to below 768px, open the side menu, and click on the "Show modal" option to open a modal and see the side menu get hidden.

Remove expose-aside-when and repeat to see what I believe is the correct behavior.

This appears to be caused by the following line in the modal show function:

https://github.com/driftyco/ionic/blob/ef1b600087404100e3d91da105c806c71810e6e0/js/angular/service/modal.js#L179

```js
ionic.trigger('resize');
```

I have this line patched out in my local build, and things now work as expected. So far I haven't seen this removal cause any problems, but I'm wondering if the dev team might have an idea as to why triggering a resize event might be necessary on modal open?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @lewisl9029!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
