### ISSUE TITLE
bug: strange navigation error

### ISSUE THREAD

**Issue by appwrx** [driftyco/ionic#4333]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>A picture is worth a thousand words:</span>
![img_0006](https://cloud.githubusercontent.com/assets/5112970/9733212/b75c03fa-5629-11e5-95b2-77692646d472.PNG)

<span is-issue-template></span>

I discovered that transition stocks while the view is leaving.

```html
<div class="pane" nav-view="entering" style="opacity: 1; -webkit-transform: translate3d(0%, 0px, 0px);">
<div class="pane" nav-view="leaving" style="opacity: 0.9; box-shadow: rgba(0, 0, 0, 0) 0px 0px 10px; -webkit-transform: translate3d(-33%, 0px, 0px);">
```

```javascript
$ionicHistory.nextViewOptions({
  historyRoot: true
});
$ionicViewSwitcher.nextDirection('back');
$state.transitionTo('tab.catalog', {
  path: '*****'
});
```

**Comment by Ionitron** [comment]
Greetings @appwrx!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by anandasansol** [comment]
+1 for the problem. I am facing the same issue in the latest ionic code. Any solution or workaroud?
