### ISSUE TITLE
bug: sub-header gets hidden by tabs-top

### ISSUE THREAD

**Issue by paulpatarinski** [driftyco/ionic#4336]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>http://codepen.io/paulpatarinski/pen/MaYVgr</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @paulpatarinski!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
