### ISSUE TITLE
bug: ionic-push.js | notification.payload.payload is undefined

### ISSUE THREAD

**Issue by yazjisuhail** [driftyco/ionic#4337]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>when opening a notification from the notification center on **android 5.1.1**, i get the error:
```
TypeError: Cannot read property '$state' of undefined
at Object.run (http://10.0.1.8:8100/lib/ionic-service-push/ionic-push.js:329:57)
```

here's the implementation:
```
$ionicPlatform.ready(function() {
    $ionicPush.register({
        canShowAlert: true, // show an alert on your screen
        canSetBadge: true, // update app icon badges
        canPlaySound: true, // play a sound
        canRunActionsOnWake: true, // run actions outside the app
        onNotification: function(notification) {
            // Handle push notifications
            if (notification.message) {
                $ionicPopup.alert({
                    title: 'Notification',
                    template: notification.message
                }).then(function(res) {
                    return true;
                });
            }
            return true;
        }
    }).then(function(deviceToken) {
        console.log(deviceToken);
    });
});
```
it's most probably due to notification.payload.payload being undefined.

**fixed it** by modifying *line 328* to become:
`if (ionic.Platform.isAndroid() && notification.payload.payload){`

is that okay? or there is another way around?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @yazjisuhail!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4337). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4337)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-push-issues#14
