### ISSUE TITLE
bug: Keyboard Overlaps Input on iOS/Makes div disappear

### ISSUE THREAD

**Issue by nicholasalanbrown** [driftyco/ionic#4338]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello:

I know Ionic is a bit fraught with keyboard challenges across platforms. Most of the issues I've read about related to Android, but I'm having an issue with iOS. When I tap into the input field, instead of scrolling up to show it, the keyboard overlaps the input entirely.

![image](https://cloud.githubusercontent.com/assets/3259022/9741544/f699f078-5628-11e5-9d64-565d42f96ac5.png)

![image](https://cloud.githubusercontent.com/assets/3259022/9741549/fe4b1e78-5628-11e5-917e-8a1cb46ba87f.png)

As you can see, it also make the div above disappear until I tap it. 

Any guidance would be much appreciated.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @nicholasalanbrown!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4338). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4338)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Need a codepen, plunkr, jsbin to test against.

**Comment by Ionitron** [comment]
Greetings @nicholasalanbrown!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @nicholasalanbrown!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
