### ISSUE TITLE
bug: $ionicNavBarDelegate.title on redirected view

### ISSUE THREAD

**Issue by jbdemonte** [driftyco/ionic#4342]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When a controller redirect to another view before having displayed its own view, the targeted controller is not able to use $ionicNavBarDelegate because of the function $ionicNavBar.getOnScreenHeaderBar which returns the intermediate view.

Here is a codepen to show the problem: http://codepen.io/anon/pen/meJaBM</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jbdemonte!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4342). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4342)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jbdemonte** [comment]
hum, not so sure about the source of the problem, when delaying the redirection with a $timeout, problem is still there:

http://codepen.io/anon/pen/PPqVmV

when redirecting to the result page, we can see a flashing title update with the correct one, and then with the "Home" (a previous one)

**Comment by Ionitron** [comment]
Greetings @jbdemonte!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
