### ISSUE TITLE
feat: How to put the back button to the right ?

### ISSUE THREAD

**Issue by Sshuichi** [driftyco/ionic#4344]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have tried some solutions but it seems that's impossible now to have this: 
``<ion-nav-buttons side="right">
        <ion-nav-back-button class="button-icon ion-arrow-left-c">
        </ion-nav-back-button>
</ion-nav-buttons>``

I get this error : 
[$compile:ctreq] Controller 'ionNavBar', required by directive 'ionNavBackButton', can't be found!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Sshuichi!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4344). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4344)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Hey @Sshuichi, does your project have an `ionNavBar`? Could you share an example project?

**Comment by Sshuichi** [comment]
Hi ! 
Here is the relevant part of index.html.

    <body ng-app="starter">
        
        <ion-nav-bar class="bar-stable bar-positive">
            <ion-nav-back-button></ion-nav-back-button>
        </ion-nav-bar>
        
        <ion-nav-view></ion-nav-view>
      </body>

**Comment by HugoHeneault** [comment]
I have this error too, how do I solve it? :/

**Comment by HugoHeneault** [comment]
Found my issue: I wrote it here for any people who could face the same. 

My nav-bar was set like this: 
```
ion-nav-bar(ng-if="navbar")
```

On my 1st view, `$scope.navbar` was set to false, and in my second, I had defined some `ion-nav-buttons`, which triggered the error.

Using `ion-view(hide-nav-bar="true")`on views where I don't need the navbar is simplier. Don't forget to remove the `ng-if="navbar"` from you navbar. 

Happy coding, and thanks to the Ionic team for their work!
