### ISSUE TITLE
bug: Button sizes not changing in sub-header

### ISSUE THREAD

**Issue by devangmundhra** [driftyco/ionic#4349]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Using different button size classes in sub-header doesn't change its size.
http://codepen.io/anon/pen/Maamva</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @devangmundhra!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4349). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4349)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
In header and footer bars, the bar height dictates the size of the button. This can be forced with CSS, but we didn't want to encourage the use of buttons that don't fill up the bar appropriately or force it to be a different size. 

Here's an example of how to force the size http://codepen.io/perrygovier/pen/RWrErN
