### ISSUE TITLE
bug: IonicPopover gets shunted left when side menu is positioned right

### ISSUE THREAD

**Issue by jnamu** [driftyco/ionic#4350]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>We are currently trying to create a side menu that is positioned right. Within that side menu we are wanting a popover to appear. When the popover is opened it appears initially on the right side menu for a split second, then gets shunted to the left side of the screen. This may possibly be a ionic bug, if anyone has a solution or any ideas that would be great.
Thanks

http://codepen.io/jnamu/pen/qOOjWK</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jnamu!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4350). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4350)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Hmm... we didn't really design the popover to be triggered from a side menu. Sorry about that.
I'm not sure we'll fix this in v1, but here's a workaround http://codepen.io/perrygovier/pen/wKMRaz

**Comment by jnamu** [comment]
Thanks for making the change, unfortunately it looks like it still refreshes the side menu when you click on the popover. Is Ionic 2 going to support tablet apps?
