### ISSUE TITLE
bug: $state.reload() doesn't work if view is cached

### ISSUE THREAD

**Issue by jsalhani** [driftyco/ionic#4351]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello Everyone,

I'm working with a type of Feed component I created, and I cache the view it uses so that the user can return to his previous position in the feed when navigating away by clicking a topic.

I have two types of feed ( mainly two api calls ) and each one loads a type of data. I created a feed switcher to be able to switch between the types and I am calling $state.reload() after switching so that the view and its directives recompile corresponding to the new api call.

Issue is, if 'cache: true' is set in the state provider for this view, $state.reload doesnt work. Removing the caching would complicate a lot of things for me (having to keep the position when returning to the feed, not reloading the data on the back event etc)

Is there a way to work around this or is a fix in mind for this issue?

Appreciate all the help! :)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jsalhani!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4351). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4351)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Well, the state isn't really reloading if it's coming back from a cached state. Try these events instead http://ionicframework.com/docs/api/directive/ionView/

**Comment by jsalhani** [comment]
@perrygovier That's the issue I'm facing. If the state isn't cached, $state.reload() acts as it should. My point is shouldn't $state.reload() still force a state reload even if it's cached? I was assuming that would be the functionality but turns out it gets it from the cache. Any thoughts?

**Comment by z3v0k0d3** [comment]
same bug, help me please

**Comment by Ionitron** [comment]
Greetings @jsalhani!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by tarymee** [comment]
same bug, help me please

**Comment by danbucholtz** [comment]
Hi @tarymee,

At this time we aren't going to make any additional changes to this sort of navigation issue due to risk.  Nav is pretty stable right now 😄 .  Please try using the lifecycle events - hopefully those work.

Thanks,
Dan
