### ISSUE TITLE
bug: ion-list in modal view height is wrong

### ISSUE THREAD

**Issue by fkkcloud** [driftyco/ionic#4352]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I have ion-list that I want it to cover partial amount of modal view which I have set it like below.

![8efb70290b83e67acf901c2a53482fe7eb1e8176_1_281x499](https://cloud.githubusercontent.com/assets/3806802/9830746/a1869ac8-58ee-11e5-8327-80186de8b548.jpg)

but it would not let me and ion-list will just go over bottom part of modal view.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @fkkcloud!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4352). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4352)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Hey @fkkcloud, videos can sometimes have problematic layering issues. Could you provide an example we can look at?

**Comment by Ionitron** [comment]
Greetings @fkkcloud!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
