### ISSUE TITLE
bug: ion-item complex issue with span.item-note

### ISSUE THREAD

**Issue by danielfpedro** [driftyco/ionic#4353]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Code below no issue
```html
<ion-list>
  <ion-item>
    Title
    <span class="item-note">Item note</span>
  </ion-item>
</ion-list>
```
![right](https://cloud.githubusercontent.com/assets/4269083/9832896/b6c7c6c4-595b-11e5-883e-d6ef46965f2d.jpg)

I just set href to `ion-item` and bang:
```html
<ion-list>
  <ion-item href="#">
    Title
    <span class="item-note">Item note</span>
  </ion-item>
</ion-list>
```
![wrong](https://cloud.githubusercontent.com/assets/4269083/9832898/bbb40d00-595b-11e5-8cc4-b5c1151cda87.jpg)

I could notice that the only difference between two is with `href` Ionic add class `item-complex` so probably that's where the issue is coming on.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @danielfpedro!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4353). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4353)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @danielfpedro!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
