### ISSUE TITLE
bug: Textbox, textarea focus is not working in Ionic modal 

### ISSUE THREAD

**Issue by munikumar604** [driftyco/ionic#4356]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi Friends,
Could you please help me on focus with blinking cursor in enter click of each textbox . I tried with document.getElementById("Id").focus() and document.getElementById("Id").select(). But it is not working . I also tried with

  http://forum.ionicframework.com/t/focus-method-doesnt-work-on-input-textarea-etc/5606/7

, is working with only first textbox. I need it in 2 and 3 ones also. It is major in my project. please help me.
Thanks & regards,
Muni Kumar</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @munikumar604!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4356). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4356)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @munikumar604!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
