### ISSUE TITLE
bug: false positive - ionic.Platform.isIOS()

### ISSUE THREAD

**Issue by harangue** [driftyco/ionic#4359]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Ever since I upgraded to hotfix the iOS 9 issues with Ionic, this check `ionic.Platform.isIOS()` returns a false positive in Chrome.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @harangue!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4359). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4359)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Thanks! We'll look in to it.

**Comment by perrygovier** [comment]
Is this desktop Chrome? I'm not seeing it.

**Comment by harangue** [comment]
Yes. Windows 10, 64 bit Chrome.

**Comment by perrygovier** [comment]
Hey @harangue, @mhartington took a look on 64 bit chrome w/ windows 10 and still not seeing it. What does it say your user agent is?

**Comment by harangue** [comment]
> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36

I had 10/10 reproduction yesterday but it hasn't appeared today...

**Comment by perrygovier** [comment]
Were you perhaps in Chrome's emulation mode? (hit escape when in inspector)

**Comment by harangue** [comment]
Wow... that was it. I'm really sorry about that - thanks for helping me out.

**Comment by perrygovier** [comment]
np
