### ISSUE TITLE
bug: Capitalization in development environment needs to be consistent with actual device

### ISSUE THREAD

**Issue by bwheeler96** [driftyco/ionic#4360]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>Let's say you have a file at wwww/js/controllers/Main.js and then you have a link to it in your index.html

```
<script src="js/controllers/main.js"></script>
```

For some reason, the asset without capitalization loads fine in the browser, and on the iOS simulator, but fails miserably and silently on any iOS device.

After spending hours trying to find the silent culprit, I think Ionic should either incorporate better logging when assets can't be found, or require strict capitalization from the server. Seeing as the browser is my only real method of digging deep with debugging, I feel it needs to be treated exactly like my device</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @bwheeler96!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4360). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4360)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by bwheeler96** [comment]
I can make a pull request for this to be fixed.

*This issue does not feel like a personal soapbox*. If the browser "simulation" doesn't run as similarly as possible to the way ionic apps run on iOS, it makes it *much* harder to identify bugs

**Comment by perrygovier** [comment]
This is a platform configuration issue. The best solution is to use a case sensitive file system on your development machine. 

How would you suggest logging it other than tying different capitalization schemes of every outgoing request that fails?

**Comment by bwheeler96** [comment]
I would suggest raising an error if the case of the file found does not match exactly the case of the file requested.

**Comment by bwheeler96** [comment]
It looks like it would be more than possible to check the case of files during lookup by the server. For example
```
fs.readdirSync('/')
[ '.DS_Store',
  '.DocumentRevisions-V100',
  '.PKInstallSandboxManager',
  '.Spotlight-V100',
  '.Trashes',
  '.file',
  '.fseventsd',
  '.vol',
  'Applications',
  'Library',
  'Network',
  'System',
  'Users',
  'Volumes',
  'bin',
  'dev',
  'etc',
  'home',
  'installer.failurerequests',
  'net',
  'opt',
  'private',
  'sbin',
  'tmp',
  'usr',
  'var' ]
```

**Comment by Ionitron** [comment]
Greetings @bwheeler96!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
