### ISSUE TITLE
bug: Ionic spins infinitely if there is a circular symink

### ISSUE THREAD

**Issue by ptarjan** [driftyco/ionic#4361]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If I have a symlink in `www/source` which links to `.` then when I run any `ionic` command it just spins forever. (The symlink was there so that my sourcemaps which refer to node_modules and bower_components are accessible by the browser)

Simple repro steps:

```
$ ionic run
... works great ...
$ ln -s .. www/source
$ ionic run
... hung ...
``
`</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ptarjan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4361). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4361)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Short answer: Don't do that :grin: 

Long answer: `ln -s` is little tricky here, as it does create a symlink, but just not in the way that cordova can handle. It's probably better to use a node based option here, like [gulp-symlink](https://github.com/ben-eb/gulp-symlink)

**Comment by ptarjan** [comment]
Uh, @mhartington you understand that the `gulp-symlink` you sent is just delegating to https://nodejs.org/api/fs.html#fs_fs_symlink_destination_path_type_callback which uses the same syscall `symlink (2)` as `ln` uses? It isn't how the symlink is made, it is the fact that `ionic` is recursively trying to walk the tree and not memorizing what it is has seen in the past.

**Comment by mhartington** [comment]
Hmm, maybe I'm not understanding the problem. 

I don't get why you need to have a symlink when the contents of `www/` gets copied to the platforms folder. Could you explain your process here?

**Comment by ptarjan** [comment]
Sure, thanks. @mhartington during development I use https://www.npmjs.com/package/gulp-sourcemaps which builds a sourcemap of my js (since I'm compiling it via various transpilers, most notably browserify). This sourcemap references all the original files in their correct location (`./www/js/whatever.js`) but for `node_modules` it says they live in (`./source/node_modules/whatever`) so I make the symlink so all the sourcemap magic works.

**Comment by mhartington** [comment]
Hmm, do you see this when running `cordova run`?
