### ISSUE TITLE
bug: should not execute command in non-ionic directory

### ISSUE THREAD

**Issue by ohfang** [driftyco/ionic#4366]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all platforms</span>  <span ionic-webview>cli</span>

<span ionic-description>I accidentally execute this command "ionic platform add adnroid" in the PARENT directory of my ionic project folder, and it continues running, and "Downloading: https://github.com/driftyco/ionic-default-resources/archive/master.zip" , and create a resources directory.
It should have stopped executing immediately.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ohfang!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4366). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4366)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#588

**Comment by perrygovier** [comment]
Moved issue to the CLI repo
