### ISSUE TITLE
bug: .xcodeproj doesn't contain Team field

### ISSUE THREAD

**Issue by ptarjan** [driftyco/ionic#4368]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>To deploy my app, I need to open the `.xcodeproj` and chose from the dropdown my deployment team or else `xcodebuild` will just hang.

![image](https://cloud.githubusercontent.com/assets/40143/9900415/8295dd5c-5c15-11e5-90dc-2723eb0c51a4.png)

It seems that by doing this in the UI it writes out a `TargetAttributes` dictionary in the `PBXProject` section right after `LastUpgradeCheck = 510`. Can you do this automatically when you make the project please?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ptarjan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4368). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4368)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Hey @ptarjan, could you tell me a bit more about your account setup? Are you part of multiple teams? Are they a mix of personal and enterprise?

**Comment by ptarjan** [comment]
@perrygovier I have a single enterprise team.

While I was investigating this, I saw that `ionic build --release --device ios` actually made a `.ipa` in the directory, but if I did

```
xcodebuild -project "$IOS_DIR/${APP_NAME}.xcodeproj" -scheme "$APP_NAME" -configuration Release clean archive -archivePath "$APP_DIR/$APP_NAME"
-rm "$DEST_DIR/$APP_NAME.ipa"
-xcodebuild -exportArchive -exportFormat ipa -archivePath "$APP_DIR/${APP_NAME}.xcarchive" -exportPath "$DEST_DIR/$APP_NAME.ipa" -exportProvisioningProfile "$APP_NAME"
```

then it would just hang.

Is the expected way to push an ionic app to do `cordova build --release --device ios` and then find the .ipa in build/device all signed correctly?

**Comment by mlynch** [comment]
Thanks for the info. Not a framework issue per say so going to close.
