### ISSUE TITLE
bug: Blank page when navigating quickly

### ISSUE THREAD

**Issue by omnight** [driftyco/ionic#4369]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When you navigate between views quickly, and go back more than one step, the caching sometimes seems to break and you get a blank page. 

page1 -> page2 -> page3 -> page1 .. (repeat)

I made a plunker to demonstrate this:
http://embed.plnkr.co/zcCozF/

To get the faulty behaviour, click the buttons to cycle between pages in quick succession. The faulty screen is a bit different depending on if transitions are enabled or not.

This code in $ionicHistory.goBack might have something to do with it

```
        if (clearStateIds.length) {
          $timeout(function() {
            self.clearCache(clearStateIds);
          }, 600);
        }
```

**Comment by Ionitron** [comment]
Greetings @omnight!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4369). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4369)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by javiercr** [comment]
I have the same problem. It seems that disabling transitions even with `nav-transition="none"` causes these blank states. Very weird.

**Comment by petehouston** [comment]
For 600ms, users can easily navigate forward to two pages, clearCache() is called afterward, and destroy the current view, resulting in a blank and black screen. 

I noted about it here.

https://medium.com/@petehouston/what-to-do-when-ionic-shows-a-blank-page-without-any-error-f12a5359cda7#.n2lz44agm

**Comment by 1BJK903** [comment]
@petehouston: how did you solve this? I read your link, but I can't find a solution for it that actually works for me.
