### ISSUE TITLE
Back button does not appear when navigating to nested view

### ISSUE THREAD

**Issue by CoenWarmer** [driftyco/ionic#437]
When navigating to a page with tabs, the header does not display the back button.

Mentioned this on the forum at: 
http://forum.ionicframework.com/t/ui-router-question-related-to-tabs/555/3

Also on StackOverflow at:
http://stackoverflow.com/questions/21218419/trouble-understanding-ui-router-and-nested-views

I've set up this Plunkr to demonstrate the behavior:
http://plnkr.co/edit/jKII2S3uEnEOVDy9WBA2

**Comment by henry74** [comment]
+1

**Comment by steven2y** [comment]
+1

**Comment by piyengar** [comment]
+1

**Comment by CoenWarmer** [comment]
This is basically the same problem as https://github.com/driftyco/ionic/issues/2997

**Comment by dylanvdmerwe** [comment]
+1

**Comment by argyleink** [comment]
+1

**Comment by upwell** [comment]
+1

**Comment by DevTipHub** [comment]
+1

**Comment by PedroJusto** [comment]
@ajoslin if you transition from "STATE1"to "STATE_WITH_TABS" ,it should have 'navigation' and in his tabs the back button should go back to "STATE1".

**Comment by hardywu** [comment]
It seems a bad idea to use `tabs` in ionic framework.

**Comment by basvdijk** [comment]
+1

**Comment by shaharlinial** [comment]
+1, no back button when entering tabs.

**Comment by adamduren** [comment]
:+1:

**Comment by gregor-srdic** [comment]
+1

**Comment by jackyon** [comment]
+10000000000

**Comment by affinionmobile** [comment]
+1 !!

**Comment by jackyon** [comment]
why there is no perfect solution for this? even i add the back button by myself, but how can I add the back transition to the button? it is just normal history go back.

i am sure a lot of people have so much confuse on here. They all like me cost few days to found a perfect solution.

plz help us!

**Comment by argyleink** [comment]
I resolved this by adding an additional state to the route where I was coming from. I had dashboard > friend detail page (no back button), but then I added friend detail state to my tab.dash, and voila, a back button appeared. My resolution to this mentally, is that a nested route must be duplicated and nested into the new base route you with to come from. In my case, I wanted the dashboard to be able to route to a user friend profile page (bypassing the friends list), so I duplicated the friend detail state to my tab.dash, made the route /dash/friend/:friendId, and everything works. 

So my message to everyone is, fiddle with your route definition code, and help the app understand how you want routing to go back and forth. You can utilize the same templates, but you'll need to create new routes to resolve some of you back button issues. Hope this helps. See my code (edited) below:

```


app.config(function($stateProvider, $urlRouterProvider, $ionicConfigProvider) {

  $stateProvider

  .state('tab', {
    url:          "/tab",
    abstract:     true,
    templateUrl:  "templates/tabs.html"
  })

  .state('tab.dash', {
    url: '/dash',
    cache: false,
    views: {
      'tab-dash': {
        templateUrl: 'templates/pulse/index.html',
        controller: 'DashCtrl'
      }
    }
  })
    .state('tab.dash-friend-detail', {
      url: '/dash/friend/:friendId',
      cache: false,
      views: {
        'tab-dash': {
          templateUrl: 'templates/friends/detail.html',
          controller: 'FriendDetailCtrl'
        }
      }
    })

  .state('tab.friends', {
      url: '/friends',
      views: {
        'tab-friends': {
          templateUrl: 'templates/friends/index.html',
          controller: 'FriendsCtrl'
        }
      }
    })
    .state('tab.friend-detail', {
      url: '/friend/:friendId',
      cache: false,
      views: {
        'tab-friends': {
          templateUrl: 'templates/friends/detail.html',
          controller: 'FriendDetailCtrl'
        }
      }
    });

});
```

**Comment by atufkas** [comment]
@argyleink I think your case doesn't cover the problem that is actually discussed here. You're states are already well defined children of a parent tab view, so that means ionic will nicely handle this within an own navigation history stack. 

The problem occurs if you switch between tabbed and non-tabbed view states that relate to each other and explicitly *should* track an own history without switching history contexts ("stacks"). Background: ionic assumes that different tabs mean different navigation contexts what is often undoubtedly the preferred behavior if you present some kind of "main menu entry points" as a button tab bar - that way, you can switch between tabs and restore the last inner state/view that the user opened. 

But in reality tabs may be used in different ways, e.g. for structuring some sub-view to have easy pre-filtered access to the presented content.

**In my eyes this problem still remains unsolved.** And it's kinda serious: How to solve this differently? Building an own tab logic with just using buttons? 

I guess there should be a way to easily hook into the view transition before entering the affected tab view  and do some kind of `$ionicHistory.suppressNewHistoryStack()` or even better: Have some attribute that can be set alongside `ui-sref` like `ionic-history-keepstack="true"` or whatsoever.

**Comment by evertoncorrea88** [comment]
I'm having the same problem. I have a tabbed view and when I use the side menu to go to a non-tabbed view it does not show the back button.

**Comment by craigvl** [comment]
@atufkas  I think that I have the same issue, lets say I have two tabs:

- profile tab
- item list tab

and three views, 

- profile view (on profile tab)
- item list view (on list tab)
- item detail view (on list tab)

From the item list if I click on an item I am taken to the item details view this all works fine as it is all contained in the same item tab and the back button works.

Now if I favourite an item that item then shows up in my profile tab and I would like to be able to click on the item from the profile tab and be taken to the item details view but currently if you click on an item that is on the profile tab you are taken to the item details view but you are moved to the item tab and hence you are unable to get back to the profile tab as no back button is displayed.

Is this the issue that we are describing here? 

If so I would also love to be able to override the back button behaviour from the profile tab.

Thanks.

**Comment by Montrazul** [comment]
I have the exact same problem I love ionic but that is a real weakness that you have no backbutton when you come from a non-tabbed view to a tabbed-view. Im an android user and so i also will never understand the back navigation when calling different tabs. switching between tabs should never build a back stack at least in my opinion.

Please give us a back button for tabs view!

**Comment by ankitgoel1987** [comment]
+1
Just hit this issue. Seems like a serious limitation. Request Ionic to prioritize this.

**Comment by serverdevil** [comment]
+1. Please fix this. It is a very real life use case.

**Comment by leonaburime** [comment]
+1. I am wondering why the Ionic team is simply ignoring this.  Its a very serious problem that requires hacks to get around which further destabilizes and app down the road.  Is there any way to contact them directly? Should be  a simple fix for such a serious bug.

**Comment by mhartington** [comment]
We're not ignoring this, we are well aware of the current limitations. 
It is not a simple fix, because now we're dealing with abstract states and nested navigations.

If you're on view1 and you got to tab1-view1, should a back button be displayed? 
Currently it won't since we're assuming tabs will have their own navigations stacks. 
tab1-view1 is technically the start of that nested views navigation stack, so there shouldn't be back button.

This is why we're working hard on V2 of ionic. Thins like this will be addressed.

**Comment by Montrazul** [comment]
@mhartington

That's maybe true but than i would have one question: Why do you want tabs to have their own navigation stack? For me (android developer) that simply makes no sense to have a back functionality withint tabs. If you still want that feature to exists you will need another tabs view. One with own navigation stack and one without.

**Comment by simplesmiler** [comment]
@Montrazul that's how tabs work in iOS, isn't it?

**Comment by Montrazul** [comment]
I dont know if it works like that on iOS. I only know about android. But it would still be unlogical because why should you implement a immitation of behaviour for iOS but not for Android since there are a huge amount of Android Devices more than iOS devices.

**Comment by mhartington** [comment]
This is how tabs work in iOS, but it's less about an iOS/Android imitation. It's a good UI to have to allow for nested navigations stacks. Again, this is not the place for this, please use the forum.

**Comment by Montrazul** [comment]
I would if i would be allowed to post on the forum. I registered but i cant find any functionallity to post a thread ;)

**Comment by mhartington** [comment]
Whats your user name on the forum?

**Comment by Montrazul** [comment]
Same like here.

**Comment by mhartington** [comment]
can you email me, mike at ionic dot io, your user name isn't coming up on the forum.

**Comment by drochetti** [comment]
IMHO the back button not being shown is the least of the problems here. The real problem is not having a transition between those views.

- I'm in a tabbed view.
- Click on a item in a list inside that tab
- Goes to the detail view which has no tabs (to achieve this I gotta put this view on the tabs parent state and then I lose the transition between a parent-detail view relationship)

This is a very simple use case. Just look at Android's WhatsApp, Telegram, etc...

The back button you can solve using your own button and `ui-sref` forcing the back state. Not the ideal solution I know, but it solves the problem. But what about the transition?

I love Ionic, but no solution for this for over a year... we're building hybrids apps that definitely doesn't look native (transition is the key for this gap IMHO) =/

**Comment by mhartington** [comment]
Again, we know about this issue. As we've stated before, it's a very tricky issue. This is something we are very serious about fixing and making more flexible in 2.0.

**Comment by leonaburime** [comment]
Hey guys, please refrain from commenting on this issue as Im sure the Ionic team is tired of responding to it.  They mentioned previously there is an ionic forum to discuss this.

I did have one question Mike.  Is there a time frame for Ionic 2.0 release or a beta version we can test out or possibly a website link where we can find out more info? Not really in regards to this issue just a general question.

**Comment by fhofer** [comment]
I would be interested in this (solution / time frame) too!

We have the problem that we open a detail object with tabs where no back button is available so I created an own close / back button by overwriting the inoicHistory.backView with the object's previous view on each object's tab and then going back (ionigHistory.goBack() to that view) when closing the object's detail.

Unfortunately, sometimes the back button is just not visible anymore at some places of the navigation stack despite navigation stack/history is still available. You see no back button but you can go back with the HW back button. Then, if you're not on the root level you again see the back button. when you now go forth again to the same view the back button is lost again and you only can go back again with the HW back button where the back button is present again and so on.
