### ISSUE TITLE
bug: window.device is undefined

### ISSUE THREAD

**Issue by aviadhahami** [driftyco/ionic#4370]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hey,
I was going through the source to figure out why `ionic.Platform.device()` returns an empty object (`{}`) on every platform, when I found this declaration: 
`device: function() {
      return window.device || {};
    }`
[ionic/platform.js](https://github.com/driftyco/ionic/blob/master/js/utils/platform.js#L143)
Doesn't matter which platform I was testing this on, `window.device` is not defined hence the condition will yield `{}` every time.

Is it just me or maybe something got deprecated on the way ?

thx</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @aviadhahami!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4370). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4370)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by petarov** [comment]
Do you have the [cordova-plugin-device](https://github.com/apache/cordova-plugin-device) installed?

**Comment by aviadhahami** [comment]
@petarov affirmative

**Comment by perrygovier** [comment]
in the www folder that lives in your platforms directory, do you see a cordova.js file, and does your index.html file link to it? If Cordova is loaded, window.device should be set.

**Comment by Ionitron** [comment]
Greetings @aviadhahami!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
