### ISSUE TITLE
feat: feat: make amount to slide for ionSlideBox customizable

### ISSUE THREAD

**Issue by puurinternet** [driftyco/ionic#4371]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>For a customer we're trying to implement ionic on a kiosk like set-up.

This works on a monitor instead of a phone screen, and because of that having to scroll halfway across the screen to get to the next slide is a bit counter intuitive.

To fix this I changed the 'amt' as you call it (no clue what it stands for) to only 25% of the screen. It would be nice though to make this customizable instead of having to change this in the core.

For some reason I can't run your tests, but here's a untested version of what I'm talking about: https://github.com/puurinternet/ionic/commit/771ebdd11a3843e59c66d20cd0011c1f2a285e47</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @puurinternet!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4371). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4371)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Hey @puurinternet. Thanks! We've refactored this entirely for v2, and probably wont add this to v1, but it'd make a great submission to market.ionic.io
