### ISSUE TITLE
perf: ion-content can't scroll (not response) with large text data

### ISSUE THREAD

**Issue by ajenkul** [driftyco/ionic#4372]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>webview</span>

<span ionic-description>My app work with a large database. The string that I bind into scope is very big (~40k chars).
I don't know how to solve my problem. It works perfect with the string lower than 10k chars.
When I tap on the screen, move the finger, I have to wait a little bit (~10s) to see it scroll. But other content like header button or some thing else out-side the ion-content is work fine.
`Note:` It is easier when I tap on the right side and scroll (near scroll-bar). But moving the finger to middle of screen it is really slow to response (almost can't scroll). When add overflow-scroll="true" it has same problem.
Please help me solve this problem @Ionitron 

UPDATE: I found it can only scroll when tap on the right border of the screen. If begin tap from the middle or somewhere else it won't scroll. But with small amount of text (<10k chars) it can scroll every where I tapped.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ajenkul!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4372). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4372)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ajenkul** [comment]
@Ionitron I've submit it. Thanks for your guide.

**Comment by Ionitron** [comment]
Greetings @ajenkul!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
