### ISSUE TITLE
bug: IOS 9 -  ion-nav-back-button title over view-title

### ISSUE THREAD

**Issue by mvilsaint** [driftyco/ionic#4373]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

Hi,

I'm testing my ionic app on ios 9 and I have a problem with ion-nav-back-button.

When previous view's title is long, ion-nav-back-button title is over view-title.

Do you know if a fix exists for this bug ?

Thanks !
![ionic](https://cloud.githubusercontent.com/assets/12632886/9919526/d466a04a-5ccd-11e5-881c-3a81a6f75794.png)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mvilsaint!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4373). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4373)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mvilsaint** [comment]
After install patch  like said in this article : http://blog.ionic.io/preparing-for-ios-9/ and it works now !

Thnaks for your work :+1:
