### ISSUE TITLE
bug: Conditional ng-src doesn't work with ng-repeat

### ISSUE THREAD

**Issue by ggharry** [driftyco/ionic#4374]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Example:

```html
<div ng-repeat="item in list">
  <img ng-src="{{ item.activated ? item.image1 : item:image2 }}" />
</div>
```

We have tested these kinds of code in several Ionic app, and it doesn't seem to work.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ggharry!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4374). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4374)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @ggharry!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
