### ISSUE TITLE
docs: Process for contributing CodePen examples to docs

### ISSUE THREAD

**Issue by arangas** [driftyco/ionic#4375]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>There are several CodePen examples missing from the Ionic Documentation site. I can see the CodePen ID is inside the source code but all of them appear to be owned by the "Ionic" user. It doesn't look like I should create one and submit a PR referencing a Pen when it would be owned by my user.

What is the process for contributing new examples?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @arangas!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
