### ISSUE TITLE
bug: -webkit-touch-callout: none ignored on ios9

### ISSUE THREAD

**Issue by toostn** [driftyco/ionic#4376]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>After updating to iOS9 final release, the iOS "magnifying glass" is shown when holding (long-pressing) elements in all my Ionic apps. This happens when holding on all elements I've tested, except for links.

I've checked in the iOS 9 simulator, and the elements do have the property -webkit-touch-callout: none set, but it is ignored.

Maybe there is another property to set in iOS 9, or it is simply just a bug in the UIWebView. Anyway, I thought I'd report it for your information.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @toostn!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
