### ISSUE TITLE
bug: ionSlideBox inside ionModal initializes incorrectly when active_slide is non-zero

### ISSUE THREAD

**Issue by mixersoft** [driftyco/ionic#4378]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When using ionSlideBox inside $ionicModal ionSlideBox throws an exception if the `active_slide` attribute is non-zero, i.e. start on slide 1 `ion-slide-box[active_slide="1"]`

```
TypeError: Cannot read property 'length' of undefined
    at circle (ionic.bundle.js:8183)
    at slide (ionic.bundle.js:8212)
    at slide.select (ionic.bundle.js:8565)
    at Object.fn (ionic.bundle.js:58470)
    at Scope.$digest (ionic.bundle.js:24515)
    at Scope.$apply (ionic.bundle.js:24783)
    at HTMLButtonElement.<anonymous> (ionic.bundle.js:57602)
    at HTMLButtonElement.eventHandler (ionic.bundle.js:12103)
    at triggerMouseEvent (ionic.bundle.js:2870)
    at tapClick (ionic.bundle.js:2859)
```

ionSlideBox evaluates `active_slide` watch variable BEFORE` ionic.views.Slider.setup()` is complete, so `slides.length` is invalid. You get an Exception if `active_slide` is anything but 0

http://codepen.io/anon/pen/xwVRMg?editors=101

click `Open Sign-in modal` to trigger, and see the JS in `SignInModalCtrl` 

`vm.slideCtrl.index=1` triggers the bug.
`vm.slideCtrl.index=null` avoids the problem by setting `active_slide` in a `$timeout()`</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mixersoft!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4378). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4378)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by szuzul** [comment]
+1 for that I'm having the same issue..

**Comment by shaoner** [comment]
same issue here, a workaround is to wait for the modal to show (i.e. having all the slides compiled):
```js
modal.show().then(function () {
   $scope.activeSlide = 1;
});
```
