### ISSUE TITLE
bug: $ionicLoading.hide() doesn't work before redirection

### ISSUE THREAD

**Issue by abellion** [driftyco/ionic#4379]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello,

For my promises I use $ionicLoading. In some case after my promise are resolved I hide the loading and then redirect the user in another view.

Sometimes the loading stay and block the app. Here is the code :

```
$ionicLoading.show({'template': 'Chargement...'});

saveVisit().then(function(visitId) {
	$ionicLoading.hide();
	$location.path("showVisit/" + $stateParams['searchId'] + "/" + visitId);
});
```
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @abellion!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4379). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4379)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by r1ckyrockz** [comment]
Maybe you didn't get a promise?
Try:

...
saveVisit().then(function(visitId) {
    $ionicLoading.hide();
    
    window.setTimeout(function() { // or $timeout
        $location.path("showVisit/" + $stateParams['searchId'] + "/" + visitId);
     },10);
    
},function(error){
    $ionicLoading.hide();
    console.log(error); // => show the error
});

**Comment by abellion** [comment]
@r1ckyrockz, yes it's working but it's not clean !

**Comment by abellion** [comment]
With Ionic 1.1.0 the bug is solved :)
