### ISSUE TITLE
bug: XCode T&C causes incorrect error message during a build

### ISSUE THREAD

**Issue by budda** [driftyco/ionic#4380]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>
```
$ ionic build ios
The provided path ".../platforms/ios" is not a Cordova iOS project.
```

I had to agree to the latest XCode update terms to get past this stupid and incorrect error message.

I'm guessing this is a Cordova CLI problem being passed through Ionic?
Can we improve error messages?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @budda!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4380). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4380)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Odd, mind posting here? https://github.com/driftyco/ionic-cli/issues
