### ISSUE TITLE
feat: $ionicScrollDelegate & scrollTo / ionScroll: Scroll Speed

### ISSUE THREAD

**Issue by mrzmyr** [driftyco/ionic#4387]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Would be great to have an API something like `scroll-speed=""` on the `<ion-scroll>` directive. Even on the `$ionicScrollDelegate.scrollTo` a fourth parameter like `scrollSpeed` would be very helpful.</span>

<span is-issue-template></span>

**Comment by ThinklabsGbR** [comment]
meanwhile, use sth. like this?

    var speedFactor = 1.5;
    var list_element_height = ($(window).height()  / 5);
    var speedInPxPerSecond = (list_element_height / intervalInSeconds) * speedFactor;
    var updateIntervalinMS = 42;
    var MillisecondFractions = 1000 / updateIntervalinMS;
    var actualSpeed = speedInPxPerSecond / MillisecondFractions;
    
    $interval.cancel($scope.autoscrollPromise);
    
    if ($("ion-view[nav-view='active'] [delegate-handle='scroll-" + scrollIndex + "']").length > 0) {
        $scope.autoscrollPromise = $interval(function () {
            $ionicScrollDelegate.$getByHandle('scroll-' + scrollIndex).scrollBy(0, actualSpeed, false);
        }, updateIntervalinMS);
    }

**Comment by Ionitron** [comment]
Greetings @mrzmyr!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by RainerFanta** [comment]
+1
