### ISSUE TITLE
bug: Collection-repeat not refreshing on changing data

### ISSUE THREAD

**Issue by DharmendraVaishnav91** [driftyco/ionic#4388]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have list of students on which collection repea is applied but on changing students list dynamically, list data exist but collection-repeat does not refresh UI</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @DharmendraVaishnav91!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4388). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4388)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @DharmendraVaishnav91!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
