### ISSUE TITLE
bug: Btn text overflow-ellipsis not working on Android

### ISSUE THREAD

**Issue by ghchia** [driftyco/ionic#4389]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>The button text of 1st button is hidden behind 2nd button in a button bar. This occurred when tested on Samsung Android 4.4 phone. The text-overflow:ellipsis doesn't seem to be working properly. 

However, when tested on Chrome browser, the button text worked correctly i.e. with ... appended to the text when the browser size was reduced. 

I tried to add a custom CSS to the button but it didn't work on the Android phone. Please refer to code pen http://codepen.io/anon/pen/PPzYbK for HTML and custom CSS. 

I will appreciate any thoughts on this. Thank you.

**Comment by Ionitron** [comment]
Greetings @ghchia!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
