### ISSUE TITLE
bug: Unable to build IOS app after upgrade to xcode 7

### ISSUE THREAD

**Issue by tomandhisjones** [driftyco/ionic#4391]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Am trying to build my app after upgrading to xcode 7, and it no longer works. I receive the following error: 

** BUILD FAILED **

The following build commands failed:
	Ld build/emulator/Ninja\ Scan.app/Ninja\ Scan normal i386
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/cordova/build-debug.xcconfig,-project,Ninja Scan.xcodeproj,ARCHS=i386,-target,Ninja Scan,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @tomandhisjones!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4391). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4391)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by dhyegofernando** [comment]
:+1:

**Comment by Ionitron** [comment]
Greetings @tomandhisjones!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
