### ISSUE TITLE
bug: Tabs clicks looks bad on IOS 9

### ISSUE THREAD

**Issue by hadar111** [driftyco/ionic#4395]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>When you clicking the tabs icons, it's looks like something bad append in the HTML classes :(
take a look at this video :
https://www.youtube.com/watch?v=GLXIJXwgokk

take same build work smoothly on IOS 8.X </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @hadar111!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4395). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4395)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by simplesmiler** [comment]
Experiencing the same issue.
@hadar111 your link is broken, correct link is https://www.youtube.com/watch?v=GLXIJXwgokk

**Comment by hadar111** [comment]
@simplesmiler Thanks, fixed :)

**Comment by mattalco** [comment]
I am also having this issue.

**Comment by mhartington** [comment]
Please apply the ios9 patch described here in this blog post
http://blog.ionic.io/preparing-for-ios-9/

**Comment by simplesmiler** [comment]
@mhartington thanks, the patch seems to have fixed the issue for me!

**Comment by ychow** [comment]
@mhartington  In wechat(ios9), also having this issue. having the solutions ?

**Comment by mhartington** [comment]
Have you applied the patch to your app?

**Comment by thaihau** [comment]
i solve by using master version using following command
`bower install driftyco/ionic-bower#master`

**Comment by a81584944** [comment]
i also have this issue 2...
and i use the Tabs template it looks bad in my iphone6(IOS9)

**Comment by spyjo** [comment]
@mhartington why don't you make an officiel update for Ionic including this ios9 patch so it would fixed for every one easily without patching manually ? It's 2 months since no new release for Ionic. Thanks

**Comment by a81584944** [comment]
+1

**Comment by merktassel** [comment]
Any idea as to when this patch will be included with Ionic by default?

**Comment by mhartington** [comment]
This patch is already included in ionics nightly builds.
