### ISSUE TITLE
bug: Hide last item in avatar list

### ISSUE THREAD

**Issue by z3v0** [driftyco/ionic#4396]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://codepen.io/anon/pen/EVyKbx</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @z3v0!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4396). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4396)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by richardsun29** [comment]
This can be fixed by using `<ion-footer-bar>` instead of `<div>` for the tabs.

http://codepen.io/anon/pen/OMNYLa

**Comment by jgw96** [comment]
Hello! Are you still experiencing this issue?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
