### ISSUE TITLE
feat: after click on swiped item, swipe back automaticly

### ISSUE THREAD

**Issue by mnewmedia** [driftyco/ionic#4398]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In a list with swipable items. It would be very nice if the item swipes automaticly back, after the click on an option button.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mnewmedia!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
