### ISSUE TITLE
bug: Ionic CLI requests upgrade to node v0.12 but throws node-sass error after node v0.10

### ISSUE THREAD

**Issue by calebfaruki** [driftyco/ionic#4399]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>
    /Users/.../node_modules/gulp-sass/node_modules/node-sass/sass.js:22
      throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?
    Error: `libsass` bindings not found. Try reinstalling `node-sass`?
        at requireBinding (/Users/.../node_modules/gulp-sass/node_modules/node-sass/sass.js:22:9)
        at Object.<anonymous> (/Users/.../node_modules/gulp-sass/node_modules/node-sass/sass.js:25:15)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/Users/calebfaruki/Documents/Motorino/motorino/node_modules/gulp-sass/index.js:3:13)
        at Module._compile (module.js:460:26)

Previously, I was running node v0.10, but every time I would run `ionic serve`, it would throw a warning that I should upgrade to v0.12. So, using `nvm`, I upgraded to v0.12.7, but now every time I initialize my localhost, I get the error above.

I have tried `npm install node-sass` to update `node-sass` and the related `libsass`, then tried removing the folder entirely and reinstalling it. Also did `npm install -g node-sass`. Still the same error.

I am using the following versions:
`node-sass` v3.3.3
`libsass` v3.2.5

Is there a specific version of `node-sass` I need to use with Node 0.12?

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @calebfaruki!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4399). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4399)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by petarov** [comment]
That looks more like a [gulp-sass](https://github.com/dlmanning/gulp-sass/issues/343) issue.

Make sure you've got the latest version in your package.json.

```javascript
    "gulp-sass": "^2.0.4",
```

**Comment by calebfaruki** [comment]
That worked. Thanks!
