### ISSUE TITLE
bug: ng-hide class attached even though `hide-back-button=false`

### ISSUE THREAD

**Issue by mzarella** [driftyco/ionic#4403]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I have an app that I'm working on, and the goal is to show information about a game. Sometimes, I start the app in state /games/:game_id, and the back button isn't present as a result, so I've started to work on a solution for this. You can see in the linked code that showCustomBackButton is set to true in the generated html (l17), but it isn't being shown because there's a class of ng-hide set as well. 

`hide-back-button=fase` is set to false, so this isn't an expected correct behavior.

https://gist.github.com/mzarella/e59ede2d28c9f921fefc#file-ionic-generated-index-html-L17</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mzarella!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4403). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4403)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @mzarella!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
