### ISSUE TITLE
bug: I can't inject $element from controller (using ui-router)

### ISSUE THREAD

**Issue by machei** [driftyco/ionic#4405]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Simple code with injecting $element based on Controller. 
```
angular.module('xyz')
.controller('ArticlesCtrl', function ($element) {
console.log($element);
});
```
But here cause error:
```
Error: [$injector:unpr] Unknown provider: $elementProvider <- $element <- ArticlesCtrl
http://errors.angularjs.org/1.3.13/$injector/unpr?p0=%24elementProvider%20%3C-%20%24element%20%3C-%20ArticlesCtrl
    at REGEX_STRING_REGEXP (file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:8890:12)
    at file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:12824:19
    at Object.getService [as get] (file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:12971:39)
    at file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:12829:45
    at getService (file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:12971:39)
    at invoke (file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:13003:13)
    at Object.instantiate (file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:13020:27)
    at file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:17289:28
    at IonicModule.controller.self.appendViewElement (file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:48436:24)
    at Object.IonicModule.factory.ionicViewSwitcher.create.switcher.render (file:///android_asset/www/lib/ionic/release/js/ionic.bundle.js:46630:41)
```

**Comment by Ionitron** [comment]
Greetings @machei!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4405). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4405)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Codepen or plunker example?

**Comment by simplesmiler** [comment]
As far as I can tell, you should only inject `$element` into directive controllers.

Few relevant issues:
- https://github.com/angular-ui/ui-router/issues/1657
- https://github.com/angular-ui/ui-router/issues/71
- https://github.com/angular/angular.js/issues/2289

**Comment by machei** [comment]
@mhartington http://codepen.io/machei/pen/jbreoX

**Comment by Ionitron** [comment]
Greetings @machei!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by YijinLiu** [comment]
The bug is still there. The old example is still valid:  http://codepen.io/machei/pen/jbreoX

**Comment by diegodesouza** [comment]
I'm experiencing this issue as well
