### ISSUE TITLE
bug: Directory "release" just appeared ...

### ISSUE THREAD

**Issue by PRotig** [driftyco/ionic#4407]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi everyone, 
Please be kind with me, I'm a newbie on IONIC :(
I'm working on an old project (few month) and I don't understand why there is in /www/lib/ionic/ the directory release and not the css, js, fonts standart directories ?? 
Thus, all my links in index.html isn't working, angular isn't obvouisly found...
Pleaz can you help me ?
Thanks a lot</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @PRotig!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4407). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4407)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by DILEEP-YADAV** [comment]
http://www.plugbunch.com/

**Comment by mlynch** [comment]
Need more info, let us know if you have a directory layout example.
