### ISSUE TITLE
bug: Windows phone failed emulation

### ISSUE THREAD

**Issue by szuzul** [driftyco/ionic#4410]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Type: Bug
Platform: Windows

Error:
I follow basic steps to create ionic app:
ionic start myApp tabs, 
cd myApp
ionic platform add windows 
open config.xml and add  <preference name="windows-target-version" value="8.1" />
cordova build in command line
open  project solution in visual studio from platform/windows folder to check config changes.

in console i run "ionic run windows -- --win" 
Error: 0x89731810
and if I run app from VS in simulator I got:

 the Unhandled exception at line 12227, column 9 in ms-appx://com.ionicframework.mytest274881/www/lib/ionic/js/ionic.bundle.js
0x800c001c - JavaScript runtime error: Unable to add dynamic content. A script attempted to inject dynamic content or elements previously modified dynamically that might be unsafe. For example, using the innerHTML property to add script or malformed HTML will generate this exception. Use the toStaticHTML method to filter dynamic content or explicitly create elements and attributes with a method such as createElement. For more information, see http://go.microsoft.com/fwlink/?LinkID=247104. 

OS: Win 8.1 Profesional,
Vs: 2015 Enterprise
Cordova:5.1.1.
Ionic: 1.1

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @szuzul!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4410). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4410)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
We will not be supporting WP8 with ionic v1.

**Comment by deryfebriantara** [comment]
is ionic v1 also not supporting wp 10 ? because i had same problem
