### ISSUE TITLE
bug: Android App Icon is Too Big In Status Bar When Receiving Notification

### ISSUE THREAD

**Issue by jason-engage** [driftyco/ionic#4412]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm seeing the same issue as defined here: 

http://stackoverflow.com/questions/30727539/android-status-bar-icon-size-using-cordova-phonegap-push-plugin

When a notification comes in, the android app icon shown in the status bar, next to the msg title, is too big and cut in the center. Should ionic resources make another type of icon size?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jason-engage!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4412). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4412)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-push-issues#15
