### ISSUE TITLE
ionic setup sass fails

### ISSUE THREAD

**Issue by cxminer** [driftyco/ionic#4413]
After I created a new project with `ionic start myApp blank` I wanted to enable sass, so I ran `ionic setup sass` and got two main errors:

1st) Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/win32-x64-node-4.1/binding.node

2nd) I assume this one happened because of the 1st one, since this is like a fallback to compile manually? Python not installed?
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

I posted entire output of `ionic setup sass` in [this Gist](https://gist.github.com/cxminer/fa0144f452126b182a2a#file-gistfile1-txt).

What to do? I tried a lot of different version of node and node-sass and gulp-sass, etc...

Output of `ionic info`:
> Cordova CLI: 5.3.1
> Gulp version:  CLI version 3.9.0
> Gulp local:   Local version 3.9.0
> Ionic Version: 1.1.0
> Ionic CLI Version: 1.6.4
> Ionic App Lib Version: 0.3.8
> OS: Windows 8
> Node Version: v4.1.1

**Comment by Ionitron** [comment]
Greetings @cxminer!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4413). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4413)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by cxminer** [comment]
Apparently the only thing I did wrong was install NodeJS from main website (version 4.1.1). I had to go to the [downloads page](https://nodejs.org/dist/) and locate NodeJS version `0.12.7` [here](https://nodejs.org/dist/v0.12.7/node-v0.12.7-x86.msi), and install it. Everything works fine now. Thanks for your help @Ionitron :laughing:
