### ISSUE TITLE
bug: Tabs not in viewport

### ISSUE THREAD

**Issue by iammart** [driftyco/ionic#4415]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I've loaded an app in landscape mode only on both sim and device on iOS and the tabs are missing. Looking at the DOM it appears they are there, but positioned as if the application was in portrait. Testing the app in portrait display the tabs as expected.

I have the following setup in my config

`<preference name="Orientation" value="landscape" />`

And in Xcode I have set the following properties for the Statusbar.

- hide during application launch
- requires fullscreen

I am also using WKWebView, but I get the same result with and without this plugin.

```
Cordova CLI: 5.3.1
Gulp version:  CLI version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 7.0 Build version 7A220 
```
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @iammart!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4415). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4415)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by iammart** [comment]
Looking at this some more it looks as though `ion-nav-view` computed height has been set to 1280.

**Comment by mhartington** [comment]
What's your viewport meta tag

**Comment by iammart** [comment]
`<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">`

**Comment by iammart** [comment]
Didn't say previously, but testing the app in the browser everything works fine.

**Comment by iammart** [comment]
Removing statusbar plugin resolves the issue for me. If I install again the tabs are missing.

**Comment by jgw96** [comment]
@iammart Are you still running into this issue?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
