### ISSUE TITLE
bug: Failing hook does not fail build (exit code)

### ISSUE THREAD

**Issue by NicholasTuck** [driftyco/ionic#4417]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If I have a failing hook that exits non 0 (like a before_build doing a webpack build), ionic will recognize the hook failed, and will stop building, but it exits with code 0. This makes my automated build tool, Jenkins, not know it's actually failing.  

cordova build fails in a nearly identical way, but it does exit code 1 as expected.

Ionic reporting exit 0: 
![image](https://cloud.githubusercontent.com/assets/5945021/10056785/69896aa2-6202-11e5-90eb-3de49aca7338.png)

Cordova reporting exit 1: 
![image](https://cloud.githubusercontent.com/assets/5945021/10056799/79346f6a-6202-11e5-9d38-f84ee30aca14.png)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @NicholasTuck!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4417). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4417)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
whats the hook?

**Comment by NicholasTuck** [comment]
It's a before_build hook that does our webpack build, that's just a node script that runs webpack.  
Fairly simple: 
```
#!/usr/bin/env node
'use strict';

process.env['NODE_ENV'] = 'production';

var webpack = require('webpack');
var webpackConfig = require('../../webpack.config');

webpack(webpackConfig, function(error, stats) {
    if (error) {
        console.error('Webpack build failed: ' + error);
        if(stats) {
            console.error('Webpack Stats: ' + stats.toString({ colors: true}));
        }
        process.exit(1);
    }
});
```

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-cli#594
