### ISSUE TITLE
bug: [wp] Tabs template app doesn't look right on Windows Phone

### ISSUE THREAD

**Issue by tomchiverton** [driftyco/ionic#4422]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Unless it's run full screen, the main view port is too high, pushing the bottom buttons off the screen.

I was forced to pick 'all mobile devices' as there isn't an option for Windows Phone</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @tomchiverton!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4422). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4422)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
We're not supporting WP at the moment.

**Comment by tomchiverton** [comment]
I understood it was planned, so raising issues with it's support would be useful ?
