### ISSUE TITLE
bug: `scrollViewNative` has no `scrollingComplete` callback

### ISSUE THREAD

**Issue by bramus** [driftyco/ionic#4423]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>`scrollView` has a `scrollingComplete` callback (which one can set via the `on-scroll-complete` attribute on `ionContent`). `scrollViewNative` does not have such a callback.

As `scrollController` can use either one of these views, the options of both should be aligned.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @bramus!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4423). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4423)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by DILEEP-YADAV** [comment]
http://www.plugbunch.com/

**Comment by Ionitron** [comment]
Greetings @bramus!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
