### ISSUE TITLE
perf: I don't know why ionic send GET request before my POST request

### ISSUE THREAD

**Issue by Ben07** [driftyco/ionic#4424]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>sometimes ionic send a GET request when I send my POST request,and the error info "GET http://url:port/xxxx 404 (Not Found)" show in console.I can get data by my request,it's OK.But I have question of that Get request.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Ben07!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4424). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4424)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
