### ISSUE TITLE
collection-repeat and ion-item adding 1-2px at bottom

### ISSUE THREAD

**Issue by ajayparsana** [driftyco/ionic#4425]
Hi,

I am using collection-repeat and ion-item to display list and added swipe event. 

I am seeing 1 -2px difference when I swipe left. Please see below image.
code pen example: http://codepen.io/ajayparsana/pen/xwEoPO
![ionicissue](https://cloud.githubusercontent.com/assets/6297808/10099106/2c5ffad0-63a4-11e5-9819-f778316b5d79.PNG)

**Comment by Ionitron** [comment]
Greetings @ajayparsana!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4425). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4425)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by morellan** [comment]
Also collection-repeat doesn't work well with the `item-text-wrap` option:

With collection-repeat:
<img width="317" alt="screen shot 2015-12-01 at 4 55 42 pm" src="https://cloud.githubusercontent.com/assets/1439999/11512358/793b08c2-984c-11e5-8b0a-e1ab5b66f4fb.png">

With ng-repeat:
<img width="316" alt="screen shot 2015-12-01 at 4 55 16 pm" src="https://cloud.githubusercontent.com/assets/1439999/11512362/7ca7c4a0-984c-11e5-9ca2-7233addcc7a9.png">

**Comment by jgw96** [comment]
Hello! Are you still experiencing this issue?

**Comment by ajayparsana** [comment]
I have fixed this issue by overriding style in parent.
