### ISSUE TITLE
bug: Alert won't close if we execute $ionicPopup.alert twice without close it

### ISSUE THREAD

**Issue by pltchuong** [driftyco/ionic#4428]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>If i wrap ```$ionicPopup.alert``` into an interval, without triggering ```close()```, so ```$ionicPopup.alert``` will run twice. After that OK button won't work, or even if you trigger ```close()``` manually</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @pltchuong!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4428). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4428)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by pltchuong** [comment]
http://codepen.io/anon/pen/EVNaPm?editors=001
This example shows you what happens if ```close()``` is not triggered. Try to close Alert after 2 seconds.

If you uncomment the code that trigger ```close()```, you will see there is another issue, Try to close Alert after 2 seconds, entire application is unclickable.

**Comment by gunar** [comment]
Same as #4118.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! @pltchuong are you still experiencing this issue in the latest version of Ionic 1.x?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
