### ISSUE TITLE
bug: `ionic plugin add` eats the user's input

### ISSUE THREAD

**Issue by ptarjan** [driftyco/ionic#4429]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Doing a `ionic plugin add cordova-hot-code-push-plugin`, they have some scripts that run asking if I want to install their npm package. No matter what I type I can't get my characters to go to their prompt. Using `cordova` instead of `ionic` works great.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ptarjan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4429). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4429)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ptarjan** [comment]
Related: https://github.com/nordnet/cordova-hot-code-push/issues/8

**Comment by mlynch** [comment]
Interesting. Cross-posted to CLI list to get this resolved. https://github.com/driftyco/ionic-cli/issues/684
