### ISSUE TITLE
cache ios bug

### ISSUE THREAD

**Issue by match08** [driftyco/ionic#4430]
$stateProvider  set views 。when set cache bug。drag view is back view null。

config set  $ionicConfigProvider.views.forwardCache(true);    

angular.module('app.goodsCategory', [])
  .config(function($stateProvider) {
    $stateProvider
      .state('app.goodsCategory', {
        url: "/goodsCategory",
        cache:false,
        views: {
          'tab-goodsCategory': {
            templateUrl: 'js/routes/goodsCategory/views/goodsCategoryList.html',
            controller: 'GoodsCategoryCtrl'
          }
        }
      })

forward next view，back prev view is null，but click nav  back button is ok

**Comment by Ionitron** [comment]
Greetings @match08!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4430). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4430)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by match08** [comment]
![bug_ios_cache](https://cloud.githubusercontent.com/assets/616730/10116215/83c577b2-645f-11e5-8d3f-6a95b4886a2f.gif)


 take a look,please.thank you !

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind explaining what issue your having exactly please and maybe provide a plunkr or codepen? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
