### ISSUE TITLE
feat: No way to set dev_push from the app.

### ISSUE THREAD

**Issue by main-kun** [driftyco/ionic#4431]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I think that's an option a lot of people would find useful. Currently, there's no way to switch to dev_push mode if you are running the app in the browser and have production mode for pushes on device.
On some blog I've found it was possible to do it like this :

```javascript
app.config(['$ionicAppProvider',function($ionicAppProvider){
  if(typeof(device)!='undefined'){ //using the cordova plugin 
 $ionicAppProvider.identify({
      app_id: 'f5fb5c5d',
      api_key: '6113f45531310f36ff12ce4c05e576138965a78590240481',​
      dev_push: false
    });
​
  }else{
    $ionicAppProvider.identify({
      app_id: 'f5fb5c5d',
      api_key: '6113f45531310f36ff12ce4c05e576138965a78590240481',
      dev_push: true
    });
  }
}])
```

But this doesn't seem to work now, as the settings are retrieved from a string in $ionicCoreSettings factory.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @main-kun!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4431). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4431)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Can you let the platform team know? https://github.com/driftyco/ionic-io-issues/issues
