### ISSUE TITLE
feat: feat: implement previousIndex()

### ISSUE THREAD

**Issue by johnrobertcobbold** [driftyco/ionic#4432]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It is possible to get the current index by using currentIndex(). I believe it would also be interesting to be able to get hold of the previous slide index, for example within the slide(to, [speed]) function where some events might trigger depending on which slide the user is coming from.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @johnrobertcobbold!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4432). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4432)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
There are other ways to already do that with using `currentIndex()` and angulars `$index`. 
No need to add that when it's already possible.
