### ISSUE TITLE
bug: Meteor driftyco:ionic Blank Screen on ios simulator / ios devices

### ISSUE THREAD

**Issue by yumikohey** [driftyco/ionic#4435]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>I am building a Meteor hybrid app that using AngularJS and ionic, so I decided to use driftyco:ionic, since meteoric:ionic doesn't support Angular.
Everything works fine on web browser, however, it is blank when it runs on ios devices or simulator. I get rid of driftyco:ionic, content is able to show on ios devices. Thus, I believe there is something I did wrong, so I got a blank page.

Could you check my repo https://github.com/yumikohey/bringMe ? 

I deployed to 52.89.149.88(most updated) and bring-me.meteor.com(older version)

Thanks for your help.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @yumikohey!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4435). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4435)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hi @yumikohey. Seems like a better question for @Urigo

**Comment by Urigo** [comment]
@yumikohey can you please open an issue on the [Angular Meteor repo](https://github.com/urigo/angular-meteor/) with your source code?
thanks

**Comment by kaiquewdev** [comment]
@yumikohey Look at the repo, check pull request that i sent to your project.

**Comment by kaiquewdev** [comment]
This is a meteor environment issue, i guess.
