### ISSUE TITLE
tabs don't align center after resize

### ISSUE THREAD

**Issue by TurtleFromBupt** [driftyco/ionic#4436]
I have a problem dealing with tabs. I don't want my tabs fullfill my screen, so i edited the _tabs.scss,and made this changes:
/*default value is 100%*/
width: 50%;
/*this is added by me to get it align center*/
margin:0 auto;
 However, it doesn't work. As its show below.
![new](https://cloud.githubusercontent.com/assets/8295448/10130019/f66ac3ec-65f6-11e5-99f1-bd2292454667.PNG)

Anybody now how to fix this?

**Comment by Ionitron** [comment]
Greetings @TurtleFromBupt!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4436). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4436)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @TurtleFromBupt!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
