### ISSUE TITLE
bug: edge-drag-threshold doesn't work with tabs

### ISSUE THREAD

**Issue by iwan-uschka** [driftyco/ionic#4438]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have a problem with `edge-drag-threshold` and using `ion-tabs` simultaneously.

In the codepens mentioned in #3511 

http://codepen.io/anon/pen/WveoGV
and
http://codepen.io/mhartington/pen/raXqxW

`edge-drag-threshold` doesn't work as expected. At least for me.
Same in my project.

If you click on login, `edge-drag-threshold` works correct on the next page in the first tab. You can only open a side-menu if you start swiping close to the border of the viewport. If you switch to the next tab, you can swipe from anywhere to open side-menu.
Does this has anything to do with setting `historyRoot:true` in `$IonicHistory.nextViewOptions`? Or is it a bug?

Using two side-menus (left and right) you're able to open the side-menu on the opposite by continue swiping after closing a side-menu. That's not very good, especially if you set `edge-drag-threshold` to true or a Number > 0.
Is there a solution?

Thanks!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @iwan-uschka!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4438). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4438)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by iwan-uschka** [comment]
to set edgeDragThreshold every time a view is entered

    $rootScope.$on('$ionicView.enter',
      function(){
        $ionicSideMenuDelegate.edgeDragThreshold(true);
      });

doesn't work neither :(

**Comment by gartorware** [comment]
Same problem here.

**Comment by mlynch** [comment]
Fix landed and will be in 1.2. Let me know how that works for you.

**Comment by iwan-uschka** [comment]
I will! Thanks!
Do you know termination of milestone 1.2?

**Comment by iwan-uschka** [comment]
It works. Thanks a lot! And keep up the good work :)
