### ISSUE TITLE
feat: Enable us to set the "Back" button text (indipendent if it will be used or not)

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic#4439]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Right now you can use `$ionicConfig.backButton.text` (or similar) to set the text of the back button. If you use this, it will also be used on Android - a platform where it normally wouldn't be used. It would be great if we could change the text that will be uses for the Back button without actually activating it - so it's still the platform that decides if to show or not to show the button. This is very useful for translating apps into other languages.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @piotrowski!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4439). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4439)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by piotrowski** [comment]
Here is my current workaround for this:

    if ($ionicConfig.backButton.text()) { // Only translate if it would be set for this platform
      $translate('general.back').then(function (text) {
        $ionicConfig.backButton.text(text);
        console.log($ionicConfig.backButton.text());
      });
    }

I only set the value to the translated version if there already is a value.

**Comment by DILEEP-YADAV** [comment]
http://www.plugbunch.com/

**Comment by sidlauskaslukas** [comment]
Don't use ```$ionicConfig.backButton.text("");``` if you want to set back button text just for one particular platform (in your case iOS), because this would set the same config variable for all platforms. If you want to set it just for iOS, use the config below
```$ionicConfigProvider.platform.ios.backButton.text("Custom text");```

Is this answer your question?

**Comment by piotrowski** [comment]
Technically yes, but not really. This is another way to solve the problem to how I did it.

But what I am really looking for is a way to set the text (to translate it) that will be used on the back button if the platform (or other settings) decide that it will be used and displayed.

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!

**Comment by piotrowski** [comment]
Well, closing tickets is fine and all... but the justification seems wrong in this case.
