### ISSUE TITLE
feat: Platfrom dependency

### ISSUE THREAD

**Issue by PrithvirajChauhan** [driftyco/ionic#4442]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Does it work on windows also?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @PrithvirajChauhan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4442). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4442)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Niades** [comment]
If you're talking about windows phone, then the support is on the roadmap. See (the browser support page)[http://ionicframework.com/docs/overview/#browser-support].
If you're talking about desktop windows, then yes, however your question is not quite correct. Ionic is not a native framework, it runs in a browser, that means that it does not matter which OS do you use, as long as it is capable of running a compatible browser. You should be warned that ionic is intended to be used for hybrid/mobile apps, not websites. Once again, see (the browser support page)[http://ionicframework.com/docs/overview/#browser-support]

**Comment by simplesmiler** [comment]
I will add, that if you're talking about developing on a windows machine, then it works fine too, except for bundling apps as ios binary, you need a mac for that.

**Comment by mhartington** [comment]
The [ionic-cli](https://github.com/driftyco/ionic-cli) works on osx/windows/linux.
