### ISSUE TITLE
bug: I have a problem with a checkbox into a modal. It cant modify the variable boolean of the controller. 

### ISSUE THREAD

**Issue by josemadev** [driftyco/ionic#4444]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>  http://codepen.io/josemadev/pen/ojYKWp?editors=101</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @josemadev!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4444). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4444)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by OrangeClyde** [comment]
Modified your codepen, basically the problem was that you bound your shared variable directly to the scope. 

http://codepen.io/anon/pen/zvNOGR?editors=101

For detailed information check back here: https://egghead.io/lessons/angularjs-the-dot

**Comment by josemadev** [comment]
Thanks!
