### ISSUE TITLE
feat: Possibly allow putting a hostname as an option for --address for ios9

### ISSUE THREAD

**Issue by timhaak** [driftyco/ionic#4445]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi

Would it be possible to allow using a hostname/dns name for --address. 

Currently seems to only allow IP's

It will allow adding it as allowed for http in plist file to work around the ios9 changes.

Thanks for an awesome project :)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @timhaak!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4445). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4445)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hi @timhaak, mind filing an issue here? https://github.com/driftyco/ionic-cli/issues
