### ISSUE TITLE
ionic-toggle ng-true-value and ng-false-value don't work in docs

### ISSUE THREAD

**Issue by oneillsp96** [driftyco/ionic#4447]
This is not a change to the ionic-toggle directive itself.  However, in the html here: http://ionicframework.com/docs/api/directive/ionToggle/
 you have the following code snippet:

 <ion-toggle toggle-class="toggle-assertive"
                    ng-model="emailNotification"
                    ng-true-value="Subscribed"
                    ng-false-value="Unubscribed">
          Newsletter
        </ion-toggle>

This doesn't work because there are no single quotes on 'Subscribed' and 'Unsubscribed', like this:
ng-true-value="'Subscribed'"

Not a big deal, just had me scratching my head for a few minutes and might be nice to update and keep the docs pretty!  
By the way, I love Ionic....Thanks!

**Comment by Ionitron** [comment]
Greetings @oneillsp96!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4447). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4447)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by chiusite** [comment]
thanks, onelipse.   i was wondering why it did not work.

btw, you can fix it in github  too

**Comment by oneillsp96** [comment]
I can only edit the toggle directive itself and submit a pull request for it....it's not an issue with the toggle, just that the way it's being shown (with slightly broken code) could be confusing

**Comment by jgw96** [comment]
Thanks for opening this issue with us! Since this is an issue related to the docs site and not the actual framework i will be moving this issue to that repo. Please feel free to continue the conversation over there! Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#518
