### ISSUE TITLE
bug: on 1.1.0 automatic addition of has-tabs-top class to ion-header-bar

### ISSUE THREAD

**Issue by Gary-Pan** [driftyco/ionic#4451]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have one view with an ion-header-bar. It looks correct when I only opened this view. But when I open another view with <ion-tabs class="tabs-top">, the view with ion-header-bar will automatic add the "has-tabs-top" class.

http://codepen.io/anon/pen/dYNrZG

This issue only occurs on 1.1.0, works fine on 1.0.1.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Gary-Pan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4451). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4451)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
In Facts.html, you have this

```
        <ion-tabs class="tabs-striped tabs-top">
          <ion-tab title="Test"></ion-tab>
        </ion-tabs>
```
At the top of the view. That is not correct.
Not sure what you are trying to do, but that is causing your bug. 

http://codepen.io/mhartington/pen/zvZZNr

**Comment by Gary-Pan** [comment]
There is a two level tabs in my app. 

http://codepen.io/Gary-Pan/pen/EVWvwy
