### ISSUE TITLE
bug: Ionic deploy does not work since IOS 9

### ISSUE THREAD

**Issue by rvs-software** [driftyco/ionic#4452]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>On iOs9 the following error occurs when i start an update via deploy (with ios 8 everything works fine)

2015-10-01 17:28:36.097 ORGA-PEG[297:25607] Download Finished...
2015-10-01 17:28:36.100 ORGA-PEG[297:25607] Download complete
2015-10-01 17:28:36.102 ORGA-PEG[297:26117] Path for zip file: /var/mobile/Containers/Data/Application/AF088DFE-F6D4-457A-A3D4-E3F523C457D8/Library/Application Support/www.zip
2015-10-01 17:28:36.102 ORGA-PEG[297:26117] Unzipping...
2015-10-01 17:28:36.104 ORGA-PEG[297:26117] updating version label
2015-10-01 17:28:36.110 ORGA-PEG[297:26117] Unzipped...
2015-10-01 17:28:36.111 ORGA-PEG[297:26117] Removing www.zip 0

After that, the www directory seems to be emtpy and the app can not be started any more!

So i have to completely remove and reinstall...
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @rvs-software!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4452). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4452)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This sounds like the ATS settings that apple recently announced. You have to apply the following settings to you apps plist file.

https://gist.github.com/mlynch/284699d676fe9ed0abfa

Or you could try this plugin I wrote to automate the process.
https://www.npmjs.com/package/cordova-config-utils

**Comment by rvs-software** [comment]
Thanks Mike,

that solved the problem!

Von: Mike Hartington [mailto:notifications@github.com]
Gesendet: Montag, 5. Oktober 2015 15:04
An: driftyco/ionic <ionic@noreply.github.com>
Cc: Habermann, Christopher <christopher.habermann@rvs-software.de>
Betreff: Re: [ionic] bug: Ionic deploy does not work since IOS 9 (#4452)


This sounds like the ATS settings that apple recently announced. You have to apply the following settings to you apps plist file.

https://gist.github.com/mlynch/284699d676fe9ed0abfa

Or you could try this plugin I wrote to automate the process.
https://www.npmjs.com/package/cordova-config-utils
