### ISSUE TITLE
bug: google place autocomplete <input> got blur() when hide keyboard

### ISSUE THREAD

**Issue by limulidae** [driftyco/ionic#4455]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>If I type some words in the <input>, it pop out some place hints.
because my phone screen is small, the board is concealing the hints.
so I have to hide the keyboard,

but... after I hide the keyboard, the hints are gone as well.......

I traced the <input> events, looks like it is calling....
function keyboardHide() {
...
keyboardActiveElement && keyboardActiveElement.blur();
...
} 

is there anyway I can workaround it?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @limulidae!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4455). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4455)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @limulidae!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
