### ISSUE TITLE
feat: Native Page Transitions Integration

### ISSUE THREAD

**Issue by NgYueHong** [driftyco/ionic#4457]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>The Native Page Transitions plugin by Telerik (http://plugins.telerik.com/cordova/plugin/native-page-transitions) is awesome. It would be great if ionic can integrate it so that everyone will get smooth page transition with ionic framework by default.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @NgYueHong!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4457). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4457)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
The plugin doesn't actually cause a page transition, but takes a screen shot and animates that image. You can get smooth transitions with ionic.

**Comment by raphaelduartepinheiro** [comment]
@mhartington sorry to reopen this issue, but is known by community that Ionic has big issues when the subject is transitions. People are making and using plugins like that to offer smooth transitions:
https://github.com/shprink/ionic-native-transitions

And in fact is better than what Ionic provide. Is not perfect but still softer...

I'm using Ionic since 2014 and even using some techniques of CSS, AngularJS Perf., etc, I was not able to achieve softer results in some devices...

I don't know what kind of devices you guys are testing the performance, probably you did not noticed this lazy, but keep in mind that in markets like China, Peru, Brazil, Chile, Argentina and so on, people don't have access to high end mobile, then the performance is poor, mainly in Android. We are talking about a market of millions of customers... So why not provide a better UX?

I appreciate any reply

**Comment by NgYueHong** [comment]
@raphaelduartepinheiro  I am testing my app on some budget China branded smartphone such as Lenovo, ZTE v815w and etc, to ensure most of my users will get great UX when using my app. But honestly, it is nearly impossible to get smooth page transition with ionic on those budget devices. Unless by using some third party plugin like Native Page Transition. Therefore, I am thinking it is a great idea to implement it into ionic.

**Comment by mhartington** [comment]
We test on low quality android devices constantly to make sure that we can get smooth animations. 
Myself specifically I test on a [old android 4.1 device](http://www.gsmarena.com/motorola_electrify_m_xt905-5102.php) and I can get great animations on that.

_See video below_
[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/wg98-SEsVm4/0.jpg)](http://www.youtube.com/watch?v=wg98-SEsVm4)

**Comment by raphaelduartepinheiro** [comment]
Thanks for your reply @mhartington, it's kind weird this app be so smooth in such a old android version. What device did you used? Could you provide the source code of this app?

Here's a sample app showing the issue (Android 5, Moto G Second Generation, Ionic 1.1):
https://youtu.be/zY31d9Az4iI

Notice that is not smooth as your app.

@NgYueHong I agree, the Native Page Transition works so great. Not necessary be this plugin, but Ionic allow user to choice the default transition or a native for a better experience (yet integrated inside Ionic).

**Comment by mhartington** [comment]
Here's the same device running the tabs starter app as a baseline

_Video below_
[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/_ja8a08iSPE/0.jpg)](http://www.youtube.com/watch?v= _ja8a08iSPE)

But again, we are not integrating that plugin. It doesn't provide any actual transitions as you think it does. How the plugin works is it takes a screenshot of the current view(as a png) and animates that. 
https://github.com/Telerik-Verified-Plugins/NativePageTransitions/blob/master/src/ios/NativePageTransitions.m#L55
It's not actually a view transition (bad naming of the plugin).

**Comment by jlcarvalho** [comment]
@raphaelduartepinheiro same problem here.

I have some Android devices to test my apps (Nexus 5 Android 5.1.1, Galaxy S Advance Android 4.1.2, Galaxy Tab P5100 Android 4.1.2, Moto G Android 5.1 and Zenfone 5 Android 4.4.2).

Even in Nexus 5 sometimes I have trouble with transitions, mainly on screens with a lot of items.

@mhartington can you share de device did you used and the source code of this app?

**Comment by raphaelduartepinheiro** [comment]
@mhartington can you provide the source of this app you showed on the video?

I guess if you test on Moto G 2nd Generation you will notice this transition freezing. Any app, including the basics ones (side-menu mainly).

I know you're not integrating this plugin, and it doesn't provide actual transitions but if we work in a way to give Ionic a real transition it would be great for all mobile users. 

If native integration isn't on road map for Ionic Framework at all, I'd suggest the current transition be revisited since not all mobiles are getting smooth (and as you can see, it's not old devices).

**Comment by NgYueHong** [comment]
@mhartington  Try add in ion-slide-box with 4 to 5 images at the top of the page and see how well it animate page transition on low end devices..

**Comment by mhartington** [comment]
Again, working fine here.


_Video below_
[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/d1-rO6qj3Zs/0.jpg)](http://www.youtube.com/watch?v= d1-rO6qj3Zs)

**Comment by ffabreti** [comment]
I agree with @raphaelduartepinheiro.
@mhartington: if you try to build a real app, when things like those listened below are happening between views, you will see problems that don't exist in a master-detail movie example app:

`
//view A:
$scope.$on('$ionicView.beforeLeave', function () {
   //destroy map markers
   //unbind listeners
   //send analytics
   //save options
   //...
})
//view B:
$scope.$on('$ionicView.afterEnter', function () {
   //get user position
   //bind listeners
   //read remote api
   //...

})
`

**Comment by elvismdev** [comment]
Hi all, 

I have been playing with [ionic-native-transitions](https://github.com/shprink/ionic-native-transitions) for a couple of days now on a small app I'm testing on Android (Nexus 6 device) and personally It still doesn't convince me as a solution for "native" views/pages transitions on Ionic. However I recognize it might be a good solution for others, but on my personal preference i'd like to keep just using  what Ionic provides for now.

On other side, I also vote +1 for better or close native transitions out of the box of Ionic. Currently the less choppy option I have found to use in my Android app is the iOS style transition via `$ionicConfigProvider.views.transition('ios');`. If I leave it to default `platform` or `android` the hamburger menu toggle and view title on the top bar does a choppy quick blink while switching from one view to another. Setting the `ios` option gives me a better soft experience while changing views.
