### ISSUE TITLE
bug: ionic resources -> some images are defect

### ISSUE THREAD

**Issue by michis123** [driftyco/ionic#4459]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Dear Dev-Team,

i have a problem while building the icons and splahscreens for android an ios.

Platform Android:
- Command: ionic resources - The File "drawable-ldpi-icon.png" is defect. I cant rebuild the images (cache).

Platform iOS:
- Command: ionic resources - The Files "icon-small.png" and "icon-40.png" are defect. I cant rebuild the images (cache).

Can you reproduce this problems?

+ Another question: How can i "clear" the cache for icons and splashsceens?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @michis123!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4459). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4459)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
You can pass in --force. 

https://github.com/driftyco/ionic-cli#default-ionic-resources

**Comment by michis123** [comment]
I dont like to use default ionic images. I like to regenerate my own icon/splash. 
![force2](https://cloud.githubusercontent.com/assets/3668654/10373932/aa7e3a5c-6df0-11e5-94dd-273cdaccd520.PNG)
It would be great to use --force without --default to regenerate own icon/splash...
![force](https://cloud.githubusercontent.com/assets/3668654/10373837/2a73b7d8-6df0-11e5-8fb4-fcf80549192a.PNG)
