### ISSUE TITLE
bug: Toggle element work across popup-container

### ISSUE THREAD

**Issue by webmak** [driftyco/ionic#4463]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Toggle element work across popup-container
Problem in  pointer-events of the toggle element
To fix this bug you need add pointer-events: auto to popup-container</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @webmak!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by AdrienDC** [comment]
+1 I confirm this:   pointer-events: auto; needs to be added.
Nice hint @webmak
