### ISSUE TITLE
bug: $ionicCoreSettings is not updating when using ionic config set

### ISSUE THREAD

**Issue by blakedietz** [driftyco/ionic#4464]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>

### Problem :

`www/lib/ionic-core.js` is not updating when setting configurations with `ionic config set dev_push true` or the `gcm-key` or any other properties for that matter. 

We've also tried running `ionic config build`

### Current Workaround :

We've circumvented the issue by simply hardcoding our `.io-config.json` into line 453 of `/www/lib/ionic-core.js`. </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @blakedietz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4464). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4464)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @blakedietz!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
