### ISSUE TITLE
feat: IonicMaterial

### ISSUE THREAD

**Issue by Cygnx** [driftyco/ionic#4467]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Does anyone know how to intergrate "ionicmaterial" found here : http://ionicmaterial.com with meteor now that meteor is officially supported by ionic?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Cygnx!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4467). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4467)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This is not really an issue with us, but rather that project. I'd suggest getting in touch with them. 

https://github.com/zachsoft/Ionic-Material
