### ISSUE TITLE
Broken demo on Cards: http://ionicframework.com/demos/swipe-cards/

### ISSUE THREAD

**Issue by MichaelJCole** [driftyco/ionic#4471]
Hey, sorry if this is the wrong place.

This demo site has an error: http://ionicframework.com/demos/swipe-cards/

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module starter due to:
Error: [$injector:modulerr] Failed to instantiate module ionic.contrib.ui.cards due to:
Error: [$injector:nomod] Module 'ionic.contrib.ui.cards' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

**Comment by Ionitron** [comment]
Greetings @MichaelJCole!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4471). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4471)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Seems to work for me, maybe a network error?
