### ISSUE TITLE
bug: gulp snapshot yields "No e2e tests match pattern"

### ISSUE THREAD

**Issue by johnmarty** [driftyco/ionic#4474]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Let me know if I'm missing a step.
```
  $  gulp demos
  $  ./node_modules/.bin/webdriver-manager update --chrome
  $  gulp snapshot
```

Warning: pattern /Users/.../Development/driftyco/ionic/dist/ionic-demo/**/*.scenario.js did not match any files.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @johnmarty!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4474). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4474)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Snapshot isn't a public tool, closing since we can't support it outside of our workflow at the moment. Maybe in the future we will!
