### ISSUE TITLE
bug: $ionicSlideBoxDelegate not ready on page load

### ISSUE THREAD

**Issue by AgDude** [driftyco/ionic#4476]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>$ionicSlideBoxDelegate appears to load asynchronously, but there is not a documented API for waiting for it to load.

Calling a method on a slidebox immediately on page load (even inside a timeout) throws an error. Here for example, the slidebox doesn't yet have any slides.

http://plnkr.co/edit/zkGNHmlRlZXCftqKf6NY?p=preview

There are several other issues which are probably related. #4041, #4309</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
We just landed a new slider component that solves this issue. It's in master and will be in 1.2 To use it today, do this:

Will be back porting the delegate to work with it soon, but going to close since we can document this behavior instead of fixing it since it's a bit async in nature.

```html
<ion-slides options="options" slider="data.slider">
  <ion-slide-page>
  </ion-slide-page>
</ion-slides>
```
and your JS:

```
controller('MyCtrl', function($scope) {
      $scope.options = {
        loop: true
      }

      $scope.data = {};

      $scope.$watch('data.slider', function(nv, ov) {
        $scope.slider = $scope.data.slider;
      })

      $timeout(function() {
        $scope.slider.slideNext();
      }, 1000)

});
```
