### ISSUE TITLE
bug: add platform to ionic 

### ISSUE THREAD

**Issue by OussemosCh** [driftyco/ionic#4482]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>i'm new to ionic 
i'm working on windows and i get this error when trying to add platform to ionic 
![ionic](https://cloud.githubusercontent.com/assets/9042895/10334692/b9678a0e-6ce3-11e5-901d-0d4752864262.png)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @OussemosCh!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4482). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4482)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Zorgatone** [comment]
Are you using Node.js or io.js?

**Comment by mhartington** [comment]
Can you try again, but pass the `-d` flag? 

```
ionic platform add android -d
```

**Comment by OussemosCh** [comment]
i get this ..
![ionic1](https://cloud.githubusercontent.com/assets/9042895/10383383/02a9c1ee-6e26-11e5-8683-f87f90544e83.png)
