### ISSUE TITLE
bug: Using only two ion-tabs in wp8 renders tabs incorrectly

### ISSUE THREAD

**Issue by danyoel** [driftyco/ionic#4484]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>When using the `ion-tabs` directive with only two tabs, the tab icons are incorrectly laid out such that the second tab is out of the viewport. Using DOM Inspector, we see that the first tab is offset 192px and 150px wide; the second tab is offset 342px. Three tabs render correctly.

### Windows Phone 8 WXGA
![two-tabs](https://cloud.githubusercontent.com/assets/9189744/10354289/9c7b70c4-6d13-11e5-873e-bcc9911a81bd.PNG)

### Android 5.1.1 KitKat
![correct-layout-android](https://cloud.githubusercontent.com/assets/9189744/10354521/a1ff2df4-6d15-11e5-9ac7-b0999cbc0724.png)

```html
<ion-tabs class="tabs-icon-top tabs-stable">
  <!-- Dashboard Tab -->
  <ion-tab title="Status" icon-off="ion-ios-pulse" icon-on="ion-ios-pulse-strong" href="#/tab/dash">
    <ion-nav-view name="tab-dash"></ion-nav-view>
  </ion-tab>
  <!-- Chats Tab -->
  <ion-tab title="Chats" icon-off="ion-ios-chatboxes-outline" icon-on="ion-ios-chatboxes" href="#/tab/chats">
    <ion-nav-view name="tab-chats"></ion-nav-view>
  </ion-tab>
  <!-- Account Tab -->
  <!--<ion-tab title="Account" icon-off="ion-ios-gear-outline" icon-on="ion-ios-gear" href="#/tab/account">
    <ion-nav-view name="tab-account"></ion-nav-view>
  </ion-tab>-->
</ion-tabs>
```
Here the only change we've made to the sample tabs app is to comment out the "Account" `ion-tab` directive.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @danyoel!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4484). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4484)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
We're not supporting WP8 at the moment.
