### ISSUE TITLE
bug: Cannot Simulate iOS on XCode

### ISSUE THREAD

**Issue by ryanpager** [driftyco/ionic#4485]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>So when I updated to OS 10.11 (Capitain) along with XCode 7.0.1, I get the following error when trying to simulate an iOS 6 device.

```
The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 4.)
```

The project builds fine, and when I build it for Android (apk) it works completely fine...I've done a bunch of google searching and I cant seem to solve the issue. Has anyone else run into this?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ryanpager!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4485). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4485)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by kylefox** [comment]
Weird — it's been working fine for me. I did a quick Google search and the common "fix" seems to be simply quitting & restarting the simulator, or doing a "Simulator > Reset Content and Settings" from the menu bar. Have you given that a shot yet?

**Comment by kylefox** [comment]
Just realized you said you have Xcode 7.0.2. I have 7.0.1. However, I can't find any [downloads](https://developer.apple.com/xcode/download/) for Xcode 7.0.2 available...

**Comment by ryanpager** [comment]
@kylefox Yea i did the whole reset content and settings and nothing really changed. I just reinstalled xcode and the version i have is 7.0.1 now -- still no dice. Very strange.

**Comment by ryanpager** [comment]
So i just did the generic:
```
$ ionic start myApp tabs
$ cd myApp
$ ionic platform add ios
$ ionic build ios
$ ionic emulate ios
```

And that works fine .. so im trying to figure out what it is with the project im running which is causing problems all of a sudden.

**Comment by ryanpager** [comment]
Created a new project -- copied everything over...runs perfectly fine.

What the crap. Closing this for right now.

**Comment by ryanpager** [comment]
Nevermind -- worked a couple of times, then failed again.

**Comment by ryanpager** [comment]
So -- this is completely weird. It wasnt the plugins, or anything else outside of the www directory. I dont know why, but when I moved my uncompiled coffeescript + scss outside of the www directory (just changed my gulpfile around to do this), it works 100% of the time, every time.

Super bizarre -- glad it works now.
