### ISSUE TITLE
bug: Multiple asyncronous popups block UI

### ISSUE THREAD

**Issue by Zorgatone** [driftyco/ionic#4486]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>My app shows the Push notifications to the user using $ionicPopup, but sometimes blocks the user interaction when displaying too many popups all together.

I made an example here on codepen to show you the result (click on the button)..
You will be able to close some of the popups, but then an overlay is preventing you to close all of them, or interact with anything else on the page.

link: http://codepen.io/Zorgatone/pen/GpEZdP</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Zorgatone!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4486). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4486)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Zorgatone** [comment]
I am coding a workaround on my app now..
I am using a wrapper function that calls $ionicPopup, and keeping state in a "popup queue", and displaying only one popup after another (instead of all together)...

**Comment by Zorgatone** [comment]
Similarly I get the same issue when doing something like this:
```javascript
$ionicPopup.alert({title: "LOL"}).close();
```

**Comment by stefanmdt** [comment]
Same here. Because of similar problems in previous versions we used the close() function together with a custom event to ensure all popup are closed on certain situations. Now the call "kills" the whole app, which means that no interaction is possible anymore.
