### ISSUE TITLE
docs: about documentation

### ISSUE THREAD

**Issue by roiabrazaldo** [driftyco/ionic#4490]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm new here in ionic and I really love its concept.
Now I am trying to build an app using it but I am so confused.

Is there a documentation existed about ionic mobile DOM elements?
For example, I wanted to change the toggle color of `<ion-toggle>` into `calm` by doing `<ion-toggle class="toggle-calm">` and it doesn't work
I dig into ionic css documentation and showed me example but what's in there was html native DOM elements. in fact all examples there used native DOM elements which doesn't work with ionic mobile app.

I created a project using `ionic start myApp tabs`
there are a lot of custom tags, like `ion-content`, `ion-list` and `ion-option-button` which I don't understand yet where they came from and how they were bind and set up.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @roiabrazaldo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4490). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4490)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
The ion-contents, ion-list are angular directives, you can read more about them here
http://ionicframework.com/docs/api/

For the toggle, it seems to be working here.

http://codepen.io/mhartington/pen/jbweOJ
