### ISSUE TITLE
bug: Uncaught TypeError: ionic.Platform is not a function

### ISSUE THREAD

**Issue by robksawyer** [driftyco/ionic#4498]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I keep getting the following and I'm using the following in `bower.json`.
`"ionic": "https://github.com/driftyco/ionic.git#master",`

```
Uncaught TypeError: ionic.Platform is not a function
(anonymous function) @ app.js:24
invoke @ ionic.bundle.js:13277
(anonymous function) @ ionic.bundle.js:13099
forEach @ ionic.bundle.js:9163
createInjector @ ionic.bundle.js:13099
doBootstrap @ ionic.bundle.js:10457
bootstrap @ ionic.bundle.js:10478
angularInit @ ionic.bundle.js:10372
(anonymous function) @ ionic.bundle.js:37186
trigger @ ionic.bundle.js:11823
eventHandler @ ionic.bundle.js:12098
```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @robksawyer!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4498). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4498)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by robksawyer** [comment]
When I add the following, it works great. Is `ionic.Platform` only available in the simulator or in the actual device? 

```
controller('MyCtrl', function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    // called when ready
  });
});
```

**Comment by mlynch** [comment]
Weird, it should be around always. Maybe a file import issue?
