### ISSUE TITLE
bug: Ionic bar-subheader overrides bar-header behavior

### ISSUE THREAD

**Issue by shaoner** [driftyco/ionic#4500]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

When having an `ion-header-bar` from `ion-nav-bar` and an `ion-header-bar.bar-subheader`, the second directive seems to override the first.
So the "has-header" class (added by the 1st header-bar) is removed from ion-content and "has-subheader" is added instead. 
This is fine except if the subheader bar is hidden, in this case it removed both classes: "has-header" and "has-subheader". If hidden, it should not affect the behavior of the first bar, right?

Here is an example:  http://codepen.io/shaoner/pen/bVRPNG

In https://github.com/driftyco/ionic/blob/master/js/angular/directive/headerFooterBar.js#L138:

Would it be ok to replace:
```javascript
$scope.$hasHeader = isShown && !isSubheader;
```
by
```javascript
$scope.$hasHeader = isShown ? !isSubheader : $scope.$parent.$hasHeader;
```

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @shaoner!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4500). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4500)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
LGMT

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
