### ISSUE TITLE
bug: Display input tag not show placeholder

### ISSUE THREAD

**Issue by igitinode** [driftyco/ionic#4503]
This is my code:
----------------------------------------------------------------------
    <div class="list">
      <label class="item item-input">
        <input type="text" placeholder="姓名" ng-model="idCardInfo.name">
      </label>
      <label class="item item-input">
        <input type="text" placeholder="身份证号" ng-model="idCardInfo.number">
      </label>
      <label class="item item-toggle" style="font-size: 14px;">
        设置为默认身份证
        <label class="toggle">
          <input type="checkbox" ng-model="idCardInfo.default">

          <div class="track">
            <div class="handle"></div>
          </div>
        </label>
      </label>
      <label class="item item-input">
        <span style="font-size: 14px;">身份证一旦申请后将无法进行更改或删除, 请确认信息的正确</span>
      </label>
    </div>
----------------------------------------------------------------------
While the result is not show?
![image](https://cloud.githubusercontent.com/assets/8425329/10416187/2735b24c-703e-11e5-8e2b-037d20b14b9e.png)
Please help me.

**Comment by Ionitron** [comment]
Greetings @igitinode!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4503). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4503)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
