### ISSUE TITLE
docs: How to use browserify with ionic while cordova.js is dynamically built?

### ISSUE THREAD

**Issue by ravenjam** [driftyco/ionic#4504]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm use ionic with browserify. Everything works fine so far except I just cannot browserify cordova.js since it's dynamically built. This maybe a noob question but if anyone knows the answer, please let me know!. I really appreciate it!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ravenjam!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4504). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4504)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by msevestre** [comment]
Just add cordova.js as a separate entry in your index.html? We've had no
problem with that

**Comment by ravenjam** [comment]
@msevestre Thank you for your reply. However I wanted to use it in browserify. The way you described certainly works but is not what I want.

**Comment by mhartington** [comment]
This isn't really an issue with ionic and not the best place to ask. You'd probably have better luck on the forum. Closing this.
