### ISSUE TITLE
bug: Pull to refresh doesn't work on iOS if Native Scrolling is turned ON. (Works flawlessly on Android)

### ISSUE THREAD

**Issue by aqeelb** [driftyco/ionic#4505]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>iOS</span> <span ionic-platform-version>9.1 Beta 4</span>  <span ionic-webview>webview</span>

<span ionic-description><img width="751" alt="screen shot 2015-10-12 at 7 14 30 pm" src="https://cloud.githubusercontent.com/assets/2950322/10426761/dd12d1d0-7115-11e5-8835-2301a20ca3a1.png">
<img width="1743" alt="screen shot 2015-10-12 at 7 18 50 pm" src="https://cloud.githubusercontent.com/assets/2950322/10426786/207edbd0-7116-11e5-9ea8-d0a339ba6ddd.png">
 Consider the above markup, I would really appreciate your feedback. :)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @aqeelb!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4505). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4505)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Currently iOS is not setup to work with Native scrolling. The webview does not provide the necessary scroll-events. This is why JS-Scrolling is enabled by default on iOS.

**Comment by aqeelb** [comment]
This is my first hybrid mobile application, I'm sorry If I don't make sense to you. I believe under the hood cordova utilizes UIWebView.

Is there any way I could turn on native scrolling only for Android? JS-Scrolling on Android with a large datasets + Pull to refresh degrades the scrolling experince and it's extremely choppy. 

Thank you

**Comment by mhartington** [comment]
By default, Ionic's scroll will switch to native scrolling if it's android 4.4 or crosswalk automatically. With collection repeat, it needs js-scrolling so that will be the only time it switches.
