### ISSUE TITLE
bug: live reload doesn't work

### ISSUE THREAD

**Issue by Stajor** [driftyco/ionic#4507]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9.1</span>  <span ionic-webview>webview</span>

<span ionic-description>When I run emulate / run with --livereload the application stucks on cordova booting screen. Without flag it working fine

```
Your system information:

Cordova CLI: 5.3.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.5
Ionic App Lib Version: 0.3.9
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite (real El Capitan)
Node Version: v0.12.7
Xcode version: Xcode 7.0.1 Build version 7A1001 

```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Stajor!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4507). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4507)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This sounds like an issue with ATS, please take a look at this blog post

http://blog.ionic.io/preparing-for-ios-9/

And also consider include this plugin 

https://www.npmjs.com/package/cordova-config-utils

This will allow you to add the ATS settings to your app via the config.xml and have them added the plist file.

**Comment by billzhong** [comment]
I have exactly same issue.
I believe it is not relate to Apple's ATS.
Another discussion:
https://github.com/driftyco/ionic-cli/issues/605

**Comment by mhartington** [comment]
Closing this and moving to driftyco/ionic-cli#605
