### ISSUE TITLE
bug: Display different in browser and device when pull data via $http

### ISSUE THREAD

**Issue by kkai316** [driftyco/ionic#4510]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Hello everyone,
I am working on $http to get json from my api(start with "https://...." url). When I test on web browser (ionic serve), I can see my api json data. However, if I emulate on device(ionic run ios) it won't show anything. Does anyone know why? Is it something wrong or I miss something in my code? I am stuck at this for few days...still can't figure out.
Thank you so much!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @kkai316!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4510). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4510)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Make sure you have the whitelist plugin install and have the ios ATS settings correctly configured 

http://blog.ionic.io/preparing-for-ios-9/

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
