### ISSUE TITLE
bug: Bug BB10 ion-item href unsafe prefix

### ISSUE THREAD

**Issue by apipemc** [driftyco/ionic#4511]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi guys

I have a problem with routes that are generated in my application in blackberry
this before putting a text 'unsafe:local:///' film what generates conflict in navigating me as I remove this 'unsafe' to stay 'store: //'

![captura de pantalla 2015-10-13 a las 3 27 09 p m](https://cloud.githubusercontent.com/assets/590222/10467548/fc11baa6-71bf-11e5-808c-5cfcd03d494e.png)

thanks</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @apipemc!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4511). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4511)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Sounds similar to this 

https://github.com/driftyco/ionic/issues/1066

We're not going to be supporting Blackberry or adding anything in particular for it. 
You can edit your href sanitization to make it safe.
https://github.com/driftyco/ionic/blob/master/js/angular/service/ionicConfig.js#L654

**Comment by apipemc** [comment]
Thanks

the solution is similar but was added on unsafe and local, app.js

```javascript
.config([
    '$compileProvider',
    function(
        $compileProvider
    ){
    $compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|tel|ftp|mailto|file|ghttps?|ms-appx|x-wmapp0|unsafe|local):/);
    $compileProvider.imgSrcSanitizationWhitelist(/^\s*(https?|ftp|file|content|blob|ms-appx|x-wmapp0|unsafe|local):|data:image\//);
}])
```
