### ISSUE TITLE
bug: Fresh Ionic builds ship gulp task with 1.x error handling rather than 2.x

### ISSUE THREAD

**Issue by Jiran** [driftyco/ionic#4512]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi guys I was working off a fresh Ionic build today and was having trouble with gulp. Gulp watch would exit every time a Sass error occurred even though the gulp code out of the box was 

```
gulp.task('sass', function(done) {
  gulp.src('./scss/ionic.app.scss')
    .pipe(sass({
      errLogToConsole: true
    }))
    .pipe(gulp.dest('./www/css/'))
    .pipe(minifyCss({
      keepSpecialComments: 0
    }))
    .pipe(rename({ extname: '.min.css' }))
    .pipe(gulp.dest('./www/css/'))
    .on('end', done);
});
```

I finally found that the Gulp 2.x+ doesn't use errLogToConsole but rather .on('error). The code that solved it for me is below. 

```
gulp.task('sass', function(done) {
  gulp.src('./scss/ionic.app.scss')
    .pipe(sass()).on('error', sass.logError)
    .pipe(gulp.dest('./www/css/'))
    .pipe(minifyCss({
      keepSpecialComments: 0
    }))
    .pipe(rename({ extname: '.min.css' }))
    .pipe(gulp.dest('./www/css/'))
    .on('end', done);
});
```

I am not sure if this actually a bug or if I run an old build by accident but I thought I'd share it in case anyone else was noticing the same problem. Cheers.  </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Jiran!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4512). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4512)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Thanks, missed that change. 

Fixed now.

https://github.com/driftyco/ionic-app-base/commit/989c562eea6304a5c8417e3ae1b7474965de78db
