### ISSUE TITLE
perf: my content is halfway off-screen

### ISSUE THREAD

**Issue by ghost** [driftyco/ionic#4513]

**Comment by ThaddeusJiang** [comment]
ff

**Comment by Ionitron** [comment]
Greetings @ghost!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
