### ISSUE TITLE
bug: Ionic push google-api-key uncaught exception

### ISSUE THREAD

**Issue by arthurvirus** [driftyco/ionic#4515]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.x</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello,

I've tried to use the push api. It worked on dev mode. But when I try to set the google-api-key for production mode, an error occured : 
```
ionic push --google-api-key xxxxxxxxxxxx
An uncaught exception occurred and has been reported to Ionic

Cannot read property 'on' of undefined (CLI v1.6.4)

Your system information:

Cordova CLI: 5.1.1
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
OS: Windows 7 SP1
Node Version: v0.12.7
```

I use a non standard structure for my project  https://github.com/Justin-Credible/Ionic-TypeScript-MDHA-Starter

Is there a way to set the google api key manually ?

Thanks in advance !
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @arthurvirus!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4515). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4515)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by abhikakade** [comment]
An uncaught exception occurred and has been reported to Ionic

Cannot read property 'on' of undefined (CLI v1.7.7)
Your system information:

Cordova CLI: 5.3.3
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.7
Ionic App Lib Version: 0.6.3
OS: Windows 7 SP1
Node Version: v4.2.1


I am also facing similar error? any solution for this?

**Comment by mlynch** [comment]
Please file here: https://github.com/driftyco/ionic-io-issues/issues
