### ISSUE TITLE
bug: i can't showing dynamic data from tab view.

### ISSUE THREAD

**Issue by thuanitdn** [driftyco/ionic#4518]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I use ng-init to showing data from controller. but it's not working . i have also disabled cache from route.and when i use an event it's worked. what is the problem ? 
Sorry about my english.
my code 

     <div collection-repeat="entry in ListPost" ng-init="loadPost()" class="list card">
        <div class="item item-avatar">
          <img ng-src="{{entry.user.profile_image_url}}"/>
          <h2>{{entry.user.name}}</h2>
          <p>{{correctTimestring(entry.created_at) | date:'medium'}}</p>
        </div>
        <div class="item item-body">
          <p ng-bind-html="entry.text"></p>
          <img ng-if="entry.extended_entities" ng-src="{{ entry.extended_entities.media[0].media_url }}" style="width: 100%;"/>
        </div>
      </div>

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @thuanitdn!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4518). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4518)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by DaDanny** [comment]
Ok, first I'm going to help you with this problem and at the end, I'll recommend a "better" way to do it.

Your ng-init function will be called for EVERY entry in ListPost. If you only need to call this function once, I suggest placing your ng-init function on the parent element of the div it's currently on.
So quick example if you have:

```html
<div>
<div collection-repeat="entry in ListPost" ng-init="loadPost()" class="list card">
    <div class="item item-avatar">
      <img ng-src="{{entry.user.profile_image_url}}"/>
      <h2>{{entry.user.name}}</h2>
      <p>{{correctTimestring(entry.created_at) | date:'medium'}}</p>
    </div>
    <div class="item item-body">
      <p ng-bind-html="entry.text"></p>
      <img ng-if="entry.extended_entities" ng-src="{{ entry.extended_entities.media[0].media_url }}" style="width: 100%;"/>
    </div>
  </div>
</div>

```

I'd change it to 
```html
<div ng-init="loadPost()">
<div collection-repeat="entry in ListPost" ng-init="loadPost()" class="list card">
    <div class="item item-avatar">
      <img ng-src="{{entry.user.profile_image_url}}"/>
      <h2>{{entry.user.name}}</h2>
      <p>{{correctTimestring(entry.created_at) | date:'medium'}}</p>
    </div>
    <div class="item item-body">
      <p ng-bind-html="entry.text"></p>
      <img ng-if="entry.extended_entities" ng-src="{{ entry.extended_entities.media[0].media_url }}" style="width: 100%;"/>
    </div>
  </div>
</div>
```

If you need it called for each list card, then I'd recommend passing in the $index into the loadPost function, so you can keep track of it. 


Ok, now for my recommendation. Whenever you have a function in your view, such as the "loadPost()" function, it will be called during every digest cycle. If this function makes a network request, or changes the page, this will happen a lot and you'll get unwanted behavior.

I recommend avoiding this approach and instead of calling functions, use variables which are initialized in your controller. So in your controller, you could call your "loadPost" function once the controller loads, and then once you have your posts, you can show the cards with an ng-if="showCards" 

Let me know if that makes sense or if you are still having trouble.

PS, your english is fine :)

**Comment by thuanitdn** [comment]
@DaDanny It's perfect, tks you.

**Comment by jgw96** [comment]
Thanks for opening this issue with us! As it looks like this issue was solved already i will be closing this issue for now, but feel free to reopen if needed!
