### ISSUE TITLE
bug: transform(translate3d(0px, 0px, 0px) breaks fixed position elements

### ISSUE THREAD

**Issue by webmak** [driftyco/ionic#4520]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>You have not good behavior in the scroll element the same like this https://github.com/jakiestfu/Snap.js/issues/24.

And here https://bugs.webkit.org/show_bug.cgi?id=110478

Here why www.w3.org/TR/css3-2d-transforms/#transform-rendering
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @webmak!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4520). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4520)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @webmak!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
