### ISSUE TITLE
perf: Ionic slider do not change width

### ISSUE THREAD

**Issue by webmak** [driftyco/ionic#4524]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>When slide box is hidden and device change orientation and then make slide box visible width the same as before orientation changed, but when slide box is visible  before orientation change all work good. And monual run of $ionicSlideBoxDelegate.update() do not help</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @webmak!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
