### ISSUE TITLE
bug: ionic gestures not working in native app although works in browser

### ISSUE THREAD

**Issue by ravenjam** [driftyco/ionic#4525]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>iOS version: 9.0.2
iPhone: 6 plus

I only tested 'touch' and 'tap' event so far. It works in mobile browser (as I tested in mobile safari). However it is not working when I compile it into native app. I suspect that the event is not even triggered. Any option on this?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ravenjam!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4525). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4525)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ravenjam** [comment]
No reply to this? I'm still having this issue on my iPhone, please help

**Comment by mhartington** [comment]
Not seeing this in my tests.

https://github.com/mhartington/ionic-gestures

This works fine in the browser and on ios.

**Comment by ravenjam** [comment]
I'm using $ionicGesture to attachment event for multiple elements, can you give me a working example for that?

**Comment by ravenjam** [comment]
Code:

```
  return {
    restrict:  'A',

    link: function(scope, elem, attrs) {
      var gestureType = attrs.gestureType;

      switch(gestureType) {
        case 'touch':
          $ionicGesture.on('touch', scope.doSth, elem);
          break;
      }

    }
  }
```

**Comment by ravenjam** [comment]
Looks like not the gesture issue, the error happens during openModal function, closing this.
