### ISSUE TITLE
bug: Glitch on transition between views

### ISSUE THREAD

**Issue by brunomonteiro3** [driftyco/ionic#4527]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>For some reason, the transition between some views on my app has a weird glitch. It seems that the view is opened but is closed in the same time.

Here is a video with details: https://www.youtube.com/watch?v=m4ohaoc56w0

Any idea on what may be causing this issue?

This is in my app.js:

    // O Festival

    .state('appFestival.o-festival', {
        url: '/o-festival',

        views: {
            'menuContent': {
                templateUrl: 'templates/festival/o-festival.html',
                controller: 'FestivalCtrl'
            }
        }
    })

    // O Festival >> Line-up

    .state('appFestival.line-up', {
        url: '/line-up',

        views: {
            'menuContent': {
                templateUrl: 'templates/festival/line-up.html',
                controller: 'FestivalCtrl'
            }
        }
    })  

This is my HTML (how i'm calling the child view):

        <a href="#/app/line-up" class="opt-line-up">
            <span class="titulo">
                <img src="img/icons/ico-music.png" class="ico" /> 
                Line-up!
            </span>
        </a>

Thanks.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @brunomonteiro3!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4527). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4527)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by brunomonteiro3** [comment]
This solved the issue:
https://gist.github.com/IgorMinar/863acd413e3925bf282c

**Comment by mhartington** [comment]
Closing.
