### ISSUE TITLE
bug: Explicit column sizes in responsive grid

### ISSUE THREAD

**Issue by uloco** [driftyco/ionic#4529]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It looks like explicit column sizes like `col col-20` etc. don't work properly in a responsive grid after the breakpoints.

When you look at the following codepen, everything seems as you expect at the first. 
The columns on the right side are divided into 20 percent and the remaining space.
http://codepen.io/uloco/pen/vNeqZa

But after resizing the browser / content area into a smaller size, the breakpoint kicks in and the `.col-20` area doesn't apply its explicit size anymore and the both columns fill the entire space evenly. 

I don't think this is expected behaviour...</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @uloco!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4529). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4529)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @uloco!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
