### ISSUE TITLE
bug: Pseudo-element :after has no effect on Firefox41/IE10+11 desktop on buttons

### ISSUE THREAD

**Issue by wibtu** [driftyco/ionic#4530]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm trying to increase a hit area of a button. For this purpose ionic already implements a default hit area with a pseudo-element in style_ionic.css: 

.button:after {
  position: absolute;
  top: -6px;
  right: -6px;
  bottom: -6px;
  left: -6px;
  content: ' ';
}

Problem is that this only works in Chrome and Edge (both desktop) in my project. I overwrote that property and it still only worked in Chrome and Edge. My question is why it is working when i use a div-Element instead? I compared both properties of div and button with css diff and found nothing but differences in text-style, text-rendering and align-items. Any ideas?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @wibtu!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4530). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4530)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @wibtu!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
