### ISSUE TITLE
bug: Bug if user closes app during deploy extraction

### ISSUE THREAD

**Issue by salqadri** [driftyco/ionic#4531]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I am using the manual deploy process by performing a check, then a download and then an extract and then a load. If the user quits the app during a download and relaunches the app, performing a check still returns true, which is good. But if the user quits during the extraction process and relaunches the app, the check is false while the app does not have the latest code. Expected behavior: deploy.check should return true when the app closes during an extraction, and deploy.download should effectively do nothing, and deploy.extract should restart the extraction. Once completed THEN check should return false if there are no new updates.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @salqadri!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
