### ISSUE TITLE
feat: error when .io-config.json is 0byte

### ISSUE THREAD

**Issue by wendal** [driftyco/ionic#4533]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>when a .io-config.json is emtry at all :

```
D:\nutzbook\nutzcn-ionic>ionic package build android --profile dev
An uncaught exception occurred and has been reported to Ionic



Unexpected end of input (CLI v1.7.6)
```

and I add some debug code at io-config.js , line 178

```
console.log(data);console.log(CONFIG_BACKUP);
```

it output:

```
<Buffer >
./.io-config.json
{ [SyntaxError: Unexpected end of input] uncaught: true } undefined
object
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at C:\Users\wendal\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\io-config.js:179:28
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
An uncaught exception occurred and has been reported to Ionic
```

Is is possible to print a better/useful output?

```
D:\nutzbook\nutzcn-ionic>ionic info
Your system information:

Cordova CLI: 5.3.3
Ionic CLI Version: 1.7.6
Ionic App Lib Version: 0.6.2
OS: Windows 7 SP1
Node Version: v4.2.1
```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @wendal!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4533). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4533)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hey @wendal, sounds like an Ionic platform issue. Mind posting here so the platform team can help? https://github.com/driftyco/ionic-platform-web-client cc @ericb

**Comment by arLevi** [comment]
+1
