### ISSUE TITLE
bug: Ionic Push Google API Key error

### ISSUE THREAD

**Issue by pedrobrasileiro** [driftyco/ionic#4536]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>I trying push my Google API key and error appear

```
$ ionic push --google-api-key XXXXXXXXXXXX
An error occurred [TypeError: undefined is not a function]
```

My ionic info
```
$ ionic info

Your system information:

Cordova CLI: 5.3.3
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.6
Ionic App Lib Version: 0.6.2
ios-deploy version: 1.8.2 
ios-sim version: 5.0.2 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.0.1 Build version 7A1001 
```

My npm and node
```
$ npm -g list --depth=0
/Users/pedrobrasileiro/.nvm/versions/node/v0.12.7/lib
├── bower@1.6.3
├── cordova@5.3.3
├── ionic@1.7.6
├── ios-deploy@1.8.2
├── ios-sim@5.0.2
├── npm@3.3.8
└── npm-check@4.1.2
```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @pedrobrasileiro!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4536). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4536)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Closing as this is an Ionic Platform issue. Mind posting here so the platform team can help? https://github.com/driftyco/ionic-platform-web-client cc @ericb
