### ISSUE TITLE
bug: Slidebox dosen't continue auto play when the time switch to other view is over the slide interval and then return this carousel view

### ISSUE THREAD

**Issue by floraluo** [driftyco/ionic#4537]
I have the issue that slidebox can't automatically play, when I click the tab switch to another view and come back. Note,this switch interval is greater than slide interval
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

https://github.com/floraluo/ioncus/blob/master/www/templates/tab-home.html
<span ionic-description>
```
<ion-slide-box on-slide-changed="slideChanged(index)" does-continue="true" auto-play="true" 
slide-interval="2000" show-pager="false" pager-click="pagerClick(index)" >
	        <ion-slide>
	            <img src="img/ionic.png">
	        </ion-slide>
	        <ion-slide>
	          <h3>Using Awesome</h3>

	          <div id="list">
	            <h5>Just three steps:</h5>
	            <ol>
	              <li>Be awesome</li>
	              <li>Stay awesome</li>
	              <li>There is no step 3</li>
	            </ol>
	          </div>
	        </ion-slide>
	        <ion-slide>
	          <h3>Any questions?</h3>
	          <p>
	            Too bad!
	          </p>
	        </ion-slide>
		</ion-slide-box>
```
</span>
https://github.com/floraluo/ioncus/blob/master/www/js/controller.js
<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @floraluo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4537). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4537)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by hxzAugustinus** [comment]
active-slide="index"   ，maybe you need to add this  attr

**Comment by floraluo** [comment]
@hxzAugustinus thank you for your answer,but it's still have this issue when I add the attr

**Comment by mlynch** [comment]
Hey everyone, we just landed a new slider component that solves this issue. It's in master and will be in 1.2 To use it today, do this:

Will be back porting the delegate to work with it soon, but going to close since this should be solved now.

```html
<ion-slides options="options" slider="data.slider">
  <ion-slide-page>
  </ion-slide-page>
</ion-slides>
```
and your JS:

```
controller('MyCtrl', function($scope) {
      $scope.options = {
        loop: true
      }

      $scope.data = {};

      $scope.$watch('data.slider', function(nv, ov) {
        $scope.slider = $scope.data.slider;
      })

});
```
