### ISSUE TITLE
feat: support to windows phone app from ionic

### ISSUE THREAD

**Issue by iiitmahesh** [driftyco/ionic#4544]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>@Ionicframework eagerly waiting windows phone app build in ionic when can we expect (at least release (#alpha-version) year or month )</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @iiitmahesh!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4544). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4544)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by iiitmahesh** [comment]
support to windows phone app from ionic. we wanna(ionic developers team) develop  windows phone app , When can we expect that feature (at month year releasing  alpha version ) .Since phone gap providing

**Comment by mhartington** [comment]
We probably won't be supporting WP8. Especially considering Windows 10 will be coming out.

**Comment by iiitmahesh** [comment]
@mhartington thank you.I have been waiting for that.
