### ISSUE TITLE
bug:  Select can`t  use ng-model 

### ISSUE THREAD

**Issue by hxzAugustinus** [driftyco/ionic#4546]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Type: bug

Platform: all

hiii,

  I have made a example  <a  href='http://codepen.io/hxz/pen/MarGzE?editors=101'>Here</a>.

  When i choose the second option 'bbb',  the   {{myChoose|json}}   shows that myChoose has changed. However ,when i click the button 'Alert',it still  show  'aaa'.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @hxzAugustinus!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4546). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4546)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by MesutGulecen** [comment]
I think ccc's id is wronge. You assign id:1 but it's must be id:3. I can't see any problem except that. Everything is fine I guess.

**Comment by boostup** [comment]
I'm currently using this in my app, and it works !
<select ng-model="searchModel.platform" ng-options="option.code as option.label for option in platformMenuOptions"></select>

**Comment by boostup** [comment]
I'm using this in my current app (ionic v1.7.3), and it works

```
<select ng-model="searchModel.platform" ng-options="option.code as option.label for option in platformMenuOptions"></select>
```

this is the model in the controller:
```
  $scope.platformMenuOptions = [{code:"", label:"any"}, 
                                {code:"iOS", label:"iOS"}, 
                                {code:"OS X", label:"OS X"}, 
                                {code:"watchOS", label:"watchOS"}, 
                                {code:"tvOS", label:"tvOS"}, 
                              ];
```

**Comment by hxzAugustinus** [comment]
@boostup  can you get  searchModel.platform`s  value  in  the controller   after you choose  one option?

**Comment by hxzAugustinus** [comment]
OK!!!  I had solved the problem  .In the controller we need use angular.copy to copy the model ,then we can get the changed option!

**Comment by mhartington** [comment]
Any issue here or is this okay to close?
