### ISSUE TITLE
bug: installation failed with npm install -g ionic

### ISSUE THREAD

**Issue by elhamsarikhani** [driftyco/ionic#4547]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I'm trying to install ionic  using
npm install -g ionic
but I get this error:
![s](https://cloud.githubusercontent.com/assets/14323843/10640305/b4c67c4e-7846-11e5-8c10-b01083a1763d.png)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @elhamsarikhani!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4547). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4547)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by MesutGulecen** [comment]
you must  to  download node.js and cordova first.

**Comment by elhamsarikhani** [comment]
Thank you I installed node.js and now it's fine : ]

**Comment by MesutGulecen** [comment]
You're welcome :)

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-cli#627
