### ISSUE TITLE
bug: collection-repeat + one time binding + filter results in strange behaviour

### ISSUE THREAD

**Issue by FrikkinLazer** [driftyco/ionic#4549]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>See this example:
http://codepen.io/anon/pen/JYpYMR?editors=101

Search for ccc, it will show aaa.

Basically, one time binding like this {{::expression}}, inside a collection-repeat, with a search filter, behaves strangely.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @FrikkinLazer!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4549). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4549)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
http://ionicframework.com/docs/api/directive/collectionRepeat/

>Don't use angular one-time binding (::) with collection-repeat. The scope of each item is assigned new data and re-digested as you scroll. Bindings need to update, and one-time bindings won't.

Can't use one-time-bindings with collection repeat.
