### ISSUE TITLE
feat: Project activity

### ISSUE THREAD

**Issue by ZoRDoK** [driftyco/ionic#4550]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>113 unresolved pool requests. And no core developers activity from August. It seems that the project has suddenly died. Recommend active fork, please.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ZoRDoK!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4550). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4550)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
@ZoRDoK Hey there! So the project has not died! We're busy working on ionic2 right now, so thats we're a lot of the focus has been set. https://github.com/driftyco/ionic2

Ionic 1 is feature complete as we see it. We will still maintain the v1 code, but we're going to be focusing on V2 development and getting every V1 app on V2.

**Comment by ZoRDoK** [comment]
Ionic has feature complete, but although has many bugs. Ionic2 is based on Angular2, which too far from release and popular borwser support (even with polyfills).
