### ISSUE TITLE
bug: Deep nested input-field is hidden by keyboard

### ISSUE THREAD

**Issue by niagara18** [driftyco/ionic#4552]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Our application has formular fields that are nested very deep in a scrollable view. When selectting them, they get hidden by the upcoming keyboard.

Looking into the ionic code i found the problem in the keyboard listener function `keyboardFocusIn()`. The closest scrollable view of the selected input is determind by calling 
`ionic.DomUtil.getParentWithClass(e.target, SCROLL_CONTAINER_CSS)`. Without a third `depth` parameter this function traverses the dom tree upward for only 10 elements to find the scroll container.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @niagara18!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
