### ISSUE TITLE
bug: 2 views are showing on the same page after resuming the app from a URL

### ISSUE THREAD

**Issue by cmartin81** [driftyco/ionic#4557]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>When using the back navigation (in the top navigation header) ionic displays two views in the same page. (se image). This only happend when the app get started from a custom url (I'm using the cordova-customurlschema plugin). It only happens in the simulator and on a real device (not in a browser)
![iphone_6_-_iphone_6___ios_9_1__13b137_](https://cloud.githubusercontent.com/assets/510413/10715280/274960f2-7b11-11e5-904b-2b0fee6d27a9.png)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @cmartin81!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4557). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4557)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by cmartin81** [comment]
Well never mind. I found a bug in my code. I had 2 resume listeners that tried to change the state.
