### ISSUE TITLE
Images from API not loading 

### ISSUE THREAD

**Issue by kthotav** [driftyco/ionic#4558]
Im using the img tag with ng-src and the images are not loading on my iphone. however, when I run the same app in play.ionic.io website, the images load! 
device: iphone 5s, ios9

**Comment by Ionitron** [comment]
Greetings @kthotav!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4558). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4558)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by cmartin81** [comment]
When creating a img tag do not start the path with a slash.
I.E:
Let say you have a image test.png inside the directory: www/img.
The correct img tag will then be:

<img ng-src="img/test.png">

/Christian

**Comment by DaDanny** [comment]
Check Xcode error logs or console logs in Safari. You might be getting the App Transport error, and if this is the case, you need to update your info.plist and include TransportSecurity. It took me a while to locate this bug, so if you are seeing some errors having to do with TransportSecurity, I can help you out.

**Comment by fengsong97** [comment]
怎么没有能够直接看到的例子？
