### ISSUE TITLE
bug: $ionicHistory.goBack() is sometimes wrong.

### ISSUE THREAD

**Issue by igtm** [driftyco/ionic#4559]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>when i use this method, sometimes it leads to a wrong result.(also when i use the default ion-nav-back-button)
it sometimes goes back and forth.
specifically speaking, it goes back to a previous page and then after 50-100 ms it goes back to the first page, and again after 10-30 ms it goes back to the previous.(on my simulator)
apparently, we can't notice what happened because it causes at a fast speed. but we can easily notice the movement is something wrong.
it is OK if i use window.history.back() instead of that.( perhaps although old android versions are not supported.)
so the problem should arise from the $ionicHistory.goBack().
i'd appreciate it if someone can fix this problem.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @igtm!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4559). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4559)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by amitmtrn** [comment]
+1

**Comment by jgw96** [comment]
Hello! Are you still experiencing this issue?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!
