### ISSUE TITLE
bug: actionsheet has different style in android how to set css?

### ISSUE THREAD

**Issue by coolara** [driftyco/ionic#4560]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>actionsheet has different style in android how to set css?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @coolara!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4560). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4560)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This is to follow the material design spec for action sheets. If you want to style it further, you can use the platform classes

```
.platform-android .action-sheet {}
```

**Comment by vishuhanda001** [comment]
can you please detail it bit more as i am not able to understand this
and also it doesnt follow any style while using in android as compare to browser.
do i miss something ??
