### ISSUE TITLE
Unable to scroll horizontally using ion-scroll

### ISSUE THREAD

**Issue by ichengweb** [driftyco/ionic#4561]
类型：错误

平台：移动的WebView

在一个网页，我有一些内容，水平滚动部分，又有些内容。问题是，如果我点击和滚动的内容（而不是水平滚动部分），那么我可以垂直滚动。但是，如果我点击和滚动的水平滚动部分，我无法垂直滚动。离子滚动方向= X挡住了垂直滚动。如果水平段取屏幕的几乎全高，则用户不能在垂直方向上，这是阻塞的滚动滚动。如果我删除离子滚动，并使用自定义的CSS 溢出-X：滚动，然后我能够通过点击该水平滚动部分垂直滚动。但是这仅仅是工作在系统的浏览器，而不是在移动。

请看看代码笔http://codepen.io/rajeshwarpatlolla/pen/EjQyOJ

请按以下步骤
1）点击/水龙头旁边的“标题”，并试图拖动/上下移动
。2）向下滚动，并点击/轻点水平滚动的部分，试图拖动/上下移动。你不会能垂直移动
。3）如果水平滚动部分占用的移动的整个屏幕上，则用户不能看到上面和下面这水平滚动部分。

**Comment by Ionitron** [comment]
Greetings @ichengweb!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4561). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4561)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
