### ISSUE TITLE
bug: Issue with history service

### ISSUE THREAD

**Issue by cdbkr** [driftyco/ionic#4562]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello, I'm having a strange issue and I suppose it is related to the history functions.
In my applications I'm using few simple pages and complex pages with nested views. After a while navigating between views, it's starting throwing the following error:
```
ERROR: Error: undefined is not an object (evaluating 'hist.stack[hist.cursor].stateId')
register
```
Searching for the faulty instruction, it seems there is only a line in the history.js service (js/angular/service/history.js#L256)

Anyone else was able to got into this?
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @cdbkr!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4562). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4562)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Please provide a demo of this in a codepen

**Comment by Ionitron** [comment]
Greetings @cdbkr!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
