### ISSUE TITLE
feat: $ionicView events no works into directives

### ISSUE THREAD

**Issue by jdnichollsc** [driftyco/ionic#4566]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi guys,

I need to know if an directive is cached, is it possible?

For example, I need to know if a state in the routes is cached for know about the directive, but it isn't possible.

My temporal and horrible solution is

$scope.$on('$stateChangeSuccess', function (event, toState, toParams, fromState, fromParams) {
    if (toState.name == self.currentState && toState.cache !== false && self.initialized) {
         //The directive is cached, execute code again...
    }
});

Thanks in advance</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jdnichollsc!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4566). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4566)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @jdnichollsc!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
