### ISSUE TITLE
bug: HTML5 video player on iOS

### ISSUE THREAD

**Issue by root-io** [driftyco/ionic#4568]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>I am trying to get the HTML5 video player to work on iOS (it works on android), I have tried multiple video formats with no success. So basically, when I click to play the video, nothing happen.
Any help would be appreciated, here is a link to the code.

If you want to run it on a device: https://github.com/root-io/myApp

        <video controls="" autoplay="" width="100%">
          
          <source src="http://clips.vorwaerts-gmbh.de/VfE_html5.mp4" type="video/mp4">
          <source src="http://clips.vorwaerts-gmbh.de/VfE.webm" type="video/webm">
          <source src="http://clips.vorwaerts-gmbh.de/VfE.ogv" type="video/ogg">
        </video>

Source: http://camendesign.com/code/video_for_everybody/test.html</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @root-io!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4568). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4568)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Are you seeing on ios9? This sounds like apple's ATS is to blame. 
I have this put together to help out with that

https://www.npmjs.com/package/cordova-config-utils

**Comment by root-io** [comment]
Damn, you are totally right, I tested the files with https now it works, thanks !
