### ISSUE TITLE
bug: Flexbox Android Compatability

### ISSUE THREAD

**Issue by SERVANT14** [driftyco/ionic#4570]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.3</span>  <span ionic-webview>webview</span>

<span ionic-description>On Android 4.1, 4.2 and 4.3 (Jelly Bean), these two things are wrapping when they should be on a horizontal line together:

Grid:

```javascript
<div class="row">
  <div class="col col-50">
    Left
  </div>
  <div class="col col-50">
    Right
  </div>
</div>
```
Tabs:
```javascript
<ion-tabs>
  <ion-tab title="Tab 1">
    <ion-nav-view name="tab1-content"></ion-nav-view>
  </ion-tab>
  <ion-tab title="Tab 2">
    <ion-nav-view name="tab2-content"></ion-nav-view>
  </ion-tab>
</ion-tabs>
```
This is my current fix: https://gist.github.com/SERVANT14/f42a6f0f68545811cc68

Is there a better way? Isn't Ionic supposed to support Android 4.1+?

I also haven't looked to see if your docs are open to pull requests, this should be updated to say 4.1+ instead of 4.0.0+: http://ionicframework.com/docs/guide/installation.html

I also think this really just isn't true. Android Jelly Bean flexbox support doesn't seem to be the same flexbox y'all are targeting: http://ionicframework.com/docs/components/#grid. I'm no where near a flexbox expert, however. Just a suggestion.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @SERVANT14!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4570). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4570)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @SERVANT14!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
