### ISSUE TITLE
bug: Cannot archive app in Xcode 7.1

### ISSUE THREAD

**Issue by and1985129** [driftyco/ionic#4571]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Dear experts,

I have an issue that when I upgrade my Xcode to the latest version 7.1 and run ionic build ios successfully, I cannot archive app and publish to app store with issue "<Cordova/CDVViewCOntroller.h> file not found in MainViewController.h" or "<Cordova/CDVPlugin.h file not found in IonicKeyboard.h".

It successes if running the app on a simulator or in a testing device. The Cordova iOS version is 5.3.3 and Ionic is 1.7.7. I cannot find more information except the error message.

Thanks in advance if any clue.

Regards,
Ke</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @and1985129!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4571). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4571)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by root-io** [comment]
Did you try this http://forum.ionicframework.com/t/cordova-cdvviewcontroller-h-file-not-found-in-xcode-7-1-beta/32232 ?

**Comment by marcelfalliere** [comment]
have you tried the following ?

add $(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include to BuildSettings->Header Search Paths

http://stackoverflow.com/questions/12184767/phonegap-cdvviewcontroller-h-file-not-found-when-archiving-for-ios

**Comment by and1985129** [comment]
@marcelfalliere It now works. Thanks a lot!

**Comment by and1985129** [comment]
@root-io I tried this but not work for me. Anyhow, marcelfallierce's solution works. Thank you.

**Comment by abacusdesk** [comment]
This is solution is not working for me. Can you please help me?
![screen shot 2016-03-30 at 10 14 08 am](https://cloud.githubusercontent.com/assets/15275402/14132221/05c7abfc-f661-11e5-8e24-ecded1cf7922.png)

**Comment by lisaiceland** [comment]
I'm facing this bug still using xcode 8.2.1

plz help if you know a sloution
