### ISSUE TITLE
feat: provide a way to set $ionicPopup buttons default text globally

### ISSUE THREAD

**Issue by aumo** [driftyco/ionic#4573]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Currently, when writing an app in language that is not English, you need to specify the buttons text on each call to `$ionicPopup.(alert|confirm|prompt)` so you end up writing a wrapper service around `$ionicPopup` whose sole goal it to set the right button text.

Being able to specify a function as the default text would also be of great help when writing localized apps.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @aumo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4573). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4573)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @aumo!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by Hypher** [comment]
I don't think so!
Maybe create a $ionicPopupConfigProvider?
