### ISSUE TITLE
[Paiement] UX

### ISSUE THREAD

**Issue by marcelfalliere** [driftyco/ionic#4575]
Créé à partir du bug #126

---

Remettre les zone combinée déroulantes pour le choix du mois et de l'année.

Désolé de ce retour en arrière mais ce qui ne me convenait pas dans ces contrôles était qu'il n'y avait pas la barre "< >         OK" au dessus de l'interface de saisie. Puisque nous rajoutons cette barre ce type de contrôle peut être efficace. Sinon la saisie sur la clavier numérique nécessite des contrôles javascript qui seront trop long à développer.

Par ailleurs, lorsque l'internaute dispose d'une ou plusieurs cartes pré-enregistrées, pré-cocher la première carte dans l'interface de paiement.

**Comment by Ionitron** [comment]
Greetings @marcelfalliere!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4575). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4575)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by marcelfalliere** [comment]
my bad, wrong repo :(
