### ISSUE TITLE
bug: Issues in native scrolling on android

### ISSUE THREAD

**Issue by neelkamal0666** [driftyco/ionic#4576]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.x</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello, I just tried native scrolling on Android. However, I found some serious issues due to which I can't use native scrolling in production. And js scrolling lags a lot in a long list.

#1 : In a long list when I open the detail view of the list and come back to the list, then it always points to top of the list.

#2 : When I scroll the list, UI is breaking. It breaks for few seconds. Here are the screenshots
![screenshot_2015-10-30-12-20-00](https://cloud.githubusercontent.com/assets/5543743/10844141/7cccc738-7f23-11e5-91d4-2deb3d5c3782.png)
![screenshot_2015-10-30-12-19-15](https://cloud.githubusercontent.com/assets/5543743/10844155/887069e6-7f23-11e5-8765-3f0a7f6e7aaa.png)
![screenshot_2015-10-29-12-51-13](https://cloud.githubusercontent.com/assets/5543743/10844160/9625c31a-7f23-11e5-8fa3-a3d3c124df27.png)
![screenshot_2015-10-30-12-19-15 1](https://cloud.githubusercontent.com/assets/5543743/10844173/a628e594-7f23-11e5-9a97-c9698500eaa4.png)

This also happens when I scroll up from bottom to top. Here is screenshot
![screenshot_2015-10-29-12-51-04](https://cloud.githubusercontent.com/assets/5543743/10844185/bf2edaf8-7f23-11e5-9281-32a12467e84e.png)

Please let me know if there is any way to fix these two issues. Also the navigation is not smooth (Nowhere close to native app).</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @neelkamal0666!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4576). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4576)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @neelkamal0666!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
