### ISSUE TITLE
$ionicListDelegate.showOptionButtons() feature

### ISSUE THREAD

**Issue by devconcept** [driftyco/ionic#4577]
Currently the $ionicListDelegate supports closing opened options buttons but does not support opening then.
This would be a nice feature and useful for cases when you are building apps for peope that may have any discapacity and want to preserve the modern UI desing of ionic instead of placing buttons in your list.
What if your item is an image and you don't want to put a button on top of it or you could open the options on a tap or if you are filtering and only have one result you could present the options opened already, just to make a few examples.

**Comment by Ionitron** [comment]
Greetings @devconcept!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4577). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4577)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by sambengtson** [comment]
+1 I agree.  I'm trying to somehow briefly display the option buttons to indicate that they are there.  Almost like a bounce effect.  But if there is no support to open them, this is impossible.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by devconcept** [comment]
@jgw96 I just made a new project using the CLI and Ionic version 1.3.1 and I got the following output from the `$ionicListDelegate` object

![ioniclistdelegate](https://cloud.githubusercontent.com/assets/10549329/15657213/ed2b9fb2-267c-11e6-9be7-a766ae23b929.png)

So yes, this is still an issue because there is no available method to programatically open the buttons

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! At this time we are not planning on adding any new features to Ionic 1. Because of this, I am going to be closing this issue for now. Thanks for using Ionic!
