### ISSUE TITLE
bug: Release folder contains code older than the js folder contains in bower

### ISSUE THREAD

**Issue by masimakopoulos** [driftyco/ionic#4579]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello,

I came across the issue with controllerAs syntax referred by #2499 and #3651 that has been fixed in a665d1d2091bde55f7b3bdc765f1e79b5b515e1d in my environment although I am using version 1.1.0 that is supposed to solve the issue. After poking around for a bit I found that although the committed code exists in js directory (included in bower package), it does not in release (which is what I am including in my index.html). I also noticed the timestamp in version.json under the release directory and it seems to be much older than the latest commit in 1.1 branch.
 </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @masimakopoulos!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4579). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4579)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
We did fix our release to include bower but it might have been breaking for a bit. Let us know if this is still an issue.
