### ISSUE TITLE
bug: Unable to update ionic on Ubuntu 14.04

### ISSUE THREAD

**Issue by swapnesh** [driftyco/ionic#4583]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I am facing a weird issue with ionic update this time.

Following things I already tried -
1) Changed npm registry from http to https and vice versa as few post were referring to this.
2) My internet connection is not slow, and I swear it by the old and new gods.
3) I also tried updating ionic itself like `npm install -g ionic` other than `npm install -g cordova ionic` but no success.
4) My npm and node both updated, check screeshot.
5) I am not behind any proxies and other npm install are going successfully.

Let me know what other info you need to resolve the issue, I am happy to provide you.

![image](https://cloud.githubusercontent.com/assets/555540/10867516/090625aa-808c-11e5-85f6-63dbf7884fd8.png)
 
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @swapnesh!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4583). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4583)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Can you let us know over here if this is still an issue? https://github.com/driftyco/ionic-cli/issues

**Comment by swapnesh** [comment]
@mlynch No I resolved it, actually in Ubuntu their is a permission issue [though previously it was not when I am using ionic v1.3.x and old node/npm package] ...basically I followed the steps at https://docs.npmjs.com/getting-started/fixing-npm-permissions for the cure and restarting after completing the steps will able to install the ionic in my ubuntu 14.04.
