### ISSUE TITLE
bug: Signup form not appearing

### ISSUE THREAD

**Issue by dhiman-amstech** [driftyco/ionic#4585]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>In  LG-P769 set, the signup form is not appearing, but it appears when I swipe the screen. Please let me know for what reason I am getting this error. Help me please and thanks in advance !</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @dhiman-amstech!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
