### ISSUE TITLE
bug: Tabs are at center of screen not at bottom

### ISSUE THREAD

**Issue by tjvg91** [driftyco/ionic#4586]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Why are my tabs positioned in the center of screen, in spite of the fact that I forced it at the bottom using

```
.config(['$ionicConfigProvider', function ($ionicConfigProvider) {
    $ionicConfigProvider.tabs.position('bottom');
 }])
```

this is the image:
![tabs](https://cloud.githubusercontent.com/assets/5625925/10884594/cc268e8a-81b3-11e5-872b-da3d454aee8d.png)

Please help. Thanks
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @tjvg91!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4586). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4586)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Sounds like something else is way wrong. Need more info: browser/platform/etc.

**Comment by tjvg91** [comment]
I used the ripple emulator for this, cordova 3, latest ionic framework
