### ISSUE TITLE
bug: Right way to use flexbox for columns with space-between

### ISSUE THREAD

**Issue by irthos** [driftyco/ionic#4588]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Please help me understand the right way to use flexbox. My issue is that I needed to justify-content with space-between, which doesn't work out of the box bc the directives (ion-content) creates a sub div under it which isn't 100% tall. Then when I use angular's $window to get innerHTML to set the height, the animation breaks when routing between pages.

Thanks :)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @irthos!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4588). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4588)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
