### ISSUE TITLE
feat: implement a different method to close modal with backdropClickToClose

### ISSUE THREAD

**Issue by pierrybos** [driftyco/ionic#4591]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi all.

I have a different behavior to close my modal, and using backdrop to close has a inconsistent effect for my app.

So I need a other implementation and cant imagine how to do without change ionic.bundle.js

I opened a question on forum talking about this, but i believe i can develop something or help in building on this way.

http://forum.ionicframework.com/t/special-method-to-close-modal/36231</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @pierrybos!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4591). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4591)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com), as you already have. Thanks for using Ionic!
