### ISSUE TITLE
bug: Difference between emulator and real device

### ISSUE THREAD

**Issue by pixnlove** [driftyco/ionic#4592]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9.1</span>  <span ionic-webview>webview</span>

<span ionic-description>I had a problem with my CORS requests. They are working on a real iOS device (launch from XCode on my iPhone) but in iOS emulator (ionic run ios), it's failed. I think it's an issue related to the origin of the request, maybe it's different between a real device and the emulator?

My code:
```
$http.get(Config.serverApiUrl + '/article')
    .success(function(data, status, headers, config) {
        alert('data success');
        alert(JSON.stringify(data));
        alert('status');
        alert(JSON.stringify(status));
        alert('headers');
        alert(JSON.stringify(headers));
        alert('config');
        alert(JSON.stringify(config));
    })
    .error(function(data, status, headers, config) {
        alert('data error');
        alert(JSON.stringify(data));
        alert('status');
        alert(JSON.stringify(status));
        alert('headers');
        alert(JSON.stringify(headers));
        alert('config');
        alert(JSON.stringify(config));
   });
```
On iOS emulator ( I have a 'data error' and the request status is equal to 0.
On iOS a real device, I have all my data and the request status is equal to 200.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @pixnlove!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4592). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4592)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by petehouston** [comment]
it's already mentioned on this article, http://blog.ionic.io/handling-cors-issues-in-ionic/

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Im glad @petehouston was able to find that link for you! As it looks like a solution was found i am gonna go ahead and close this issue, if your still experiencing it feel free to reopen!

**Comment by Hanzofm** [comment]
Wich would be the origin of an Ioinic app that runs into a real device? (not serve, nots run -l)
