### ISSUE TITLE
bug: Angular2 & ionic 2 blank screen Samsung 

### ISSUE THREAD

**Issue by romanornr** [driftyco/ionic#4593]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>webview</span>

<span ionic-description>Recently I noticed that apps written with ionic 2 alpha have some problems. 

Samsung devices have problems with opening the app. The app will load & show a blank screen. 
Other devices just showed the app. 

Not sure but there seems to be a case that ionic 2 is slightly slower too. 

The app failed to load on a Samsung device 
But succeeded to open on a HTC smartphone. </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @romanornr!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4593). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4593)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by romanornr** [comment]
wrong repository. Should had been for ionic2
