### ISSUE TITLE
 Ionic deploy is not working after the first update 

### ISSUE THREAD

**Issue by brightergy-alexandermac** [driftyco/ionic#4594]
I'm using the simple example of Deploy from here: http://docs.ionic.io/docs/deploy-quick-start. Its works, but only the first time. When app is updated the first time, I can't update it anymore, I'm getting error: `IONIC_DEPLOY_MISSING_PACKAGE`.

But I don't change code, after the first update, just deploy new version with `ionic upload` command.

**Comment by Ionitron** [comment]
Greetings @brightergy-alexandermac!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4594). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4594)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by AlexanderMac** [comment]
That's cool, but when I'm traing update an issue, I'm getting an error: `Issue update error. Try again later`.

**Comment by mlynch** [comment]
Mind filing an issue over at the io issues page so the platform team can help? Thanks! https://github.com/driftyco/ionic-io-issues/issues
