### ISSUE TITLE
bug: ionic build android => Error: result.options.some is not a function

### ISSUE THREAD

**Issue by son1112** [driftyco/ionic#4595]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.x</span>  <span ionic-webview>webview</span>

<span ionic-description>When I run `ionic build android`, I get an error message:

`Error: result.options.some is not a function`

I have found no other reference to this error message in my searches so far. Does anyone know where this may come from? </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @son1112!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4595). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4595)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hey @son1112, going to close since this isn't a framework issue, but you might want to post over here: https://github.com/driftyco/ionic-cli/issues

I am not at all sure how to resolve this one top of my head, sorry.

**Comment by son1112** [comment]
@mlynch, thanks for letting me know!
