### ISSUE TITLE
bug: node.js 5.0.0 and ionic-cli problem

### ISSUE THREAD

**Issue by jalpedersen** [driftyco/ionic#4598]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It seems that nodejs 5.0 has broken something. Any ionic cli command simply quits silently without any error message of any kind.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jalpedersen!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4598). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4598)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by petarov** [comment]
[Already discussed](https://github.com/driftyco/ionic-cli/issues/634).

Use node4 until cordova 5.4.0 is out (this Friday probably).

**Comment by olivermuc** [comment]
5.4.0 doesn't fix it - tried a clean & fresh install

**Comment by mlynch** [comment]
Hey @olivermuc, can you file an issue here and let us know what version of Ionic/node/etc. you are using? Also would love to hear if the new cordova updates have fixed that: https://github.com/driftyco/ionic-cli/issues
