### ISSUE TITLE
perf: Collection-repeat not working in $ionicModal with ion slide

### ISSUE THREAD

**Issue by vsandoria** [driftyco/ionic#4600]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I am trying to use collection-repeat instead of ng-repeat on ionicModel in slidebox. 
Here is sample code, 

```javascript
<script id="image-modal.html" type="text/ng-template">
<div class="modal image-modal transparent"  ng-click="closeModal()">
   <ion-slide-box on-slide-changed="slideChanged(index)" show-pager="false">
              <ion-slide collection-repeat="image in imagesArray">
    <ion-content ng-show="($index) >= (currentSlide-1) && ($index <= (currentSlide+1) && showList" >
                    <img ng-src="{{ image.tripimageurl }}" class="fullscreen-image" />
    </ion-content>
                </ion-slide>
	        </ion-slide-box>
              </div>
</script>
 ```

When I replace ng-repeat with collection-repeat nothing shows up on modal popup. 
I am using ionic1.1.0 and also checked below issue. 

@perrygovier, can you please us in that, we are trying to load more then 100 photos and we think using collection-repeat would be good option. </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vsandoria!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4600). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4600)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by designzoo-peter** [comment]
We're facing the same sort of crossroads and would like some advice on this also! We have a large amount of images on a slide-box

**Comment by jgw96** [comment]
Hello! As `ion-slide-box` has been depecrated i will be closing this issue for now. Look out for alot of updates to slides in the near future! And thanks for using Ionic!
