### ISSUE TITLE
bug: ionic build iOS not working with node v5.0

### ISSUE THREAD

**Issue by walkr** [driftyco/ionic#4602]
Running 

```shell
$ ionic build ios
``` 
does nothing on my machine.

Also, `ionic info` incorrectly reports I'm on `El Capitan`, when in fact I have `Yosemite`. Maybe I should report this as a different issue.

`ionic info` output:

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.7
Ionic App Lib Version: 0.6.3
ios-deploy version: 1.7.0 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.1 Build version 7B91b

**Comment by Ionitron** [comment]
Greetings @walkr!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4602). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4602)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by walkr** [comment]
Oops. This has been reported on [#593] (https://github.com/driftyco/ionic-cli/issues/593)
