### ISSUE TITLE
bug: Sign up Issues

### ISSUE THREAD

**Issue by jmsherry** [driftyco/ionic#4603]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Feel free to delete if this is in the wrong place.

Your product looks amazing - your signup page is... not so amazing!

<img width="482" alt="screen shot 2015-11-05 at 23 34 33" src="https://cloud.githubusercontent.com/assets/697341/10985050/dab2da44-8415-11e5-85c6-82ccedf570a2.png">

I've tried my name (pictured), 'jmsherry', 'james_sherry_01' - there's just no UI feedback to show what's wrong and the message is vague and unattached. Even the console has next to nothing in...

Then, if you do the login page it (obviously for security) says [paraphrased] 'please enter a correct username and/or password' - so, I've no idea if I've ever registered before (I looked at ionic in the early days, so thought I might) or if the password is wrong, or whatever - there's just no feedback, so...

Then, I did the forgotten password bit. It tells me it's sent me an email. It hasn't so far. It's not in ANY folders...

Why is something so simple suddenly so frustrating?!!!!!

This seems weird to raise, but: Mac OSx El Capitan</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jmsherry!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4603). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4603)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Thanks, we will revise that. Closing since not a framework bug.
