### ISSUE TITLE
bug: Issue with URLs in Angular $compile on Windows 10 apps

### ISSUE THREAD

**Issue by pablo-martinez** [driftyco/ionic#4604]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>There is an issue when accessing URLs on Windows 10 in Remote Mode.
Currently, the schema used by Windows 10 apps is ms-appx-web and it's not included in the fix at ionicConfig.js:
```javascript
$compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|sms|tel|geo|ftp|mailto|file|ghttps?|ms-appx|x-wmapp0):/);
$compileProvider.imgSrcSanitizationWhitelist(/^\s*(https?|ftp|file|content|blob|ms-appx|x-wmapp0):|data:image\//);
```

Plase add it, otherwise Angular is prepending them with unsafe:</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @pablo-martinez!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4604). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4604)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Thanks!
