### ISSUE TITLE
npm install -g ionic ,Can't find Python27   in C:\Python27\python.exe

### ISSUE THREAD

**Issue by cuiyan** [driftyco/ionic#4605]
when I install ionic，it tell me,can't find Python27,you can set env variable. and  ensuring that file exists :C:\Python27\python.exe

but I already install Phtyon2.7.10 in my E:/ and set env variable

**Comment by Ionitron** [comment]
Greetings @cuiyan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4605). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4605)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hi, please file an issue over at the CLI project, though this might be beyond scope of Ionic: https://github.com/driftyco/ionic-cli/issues
