### ISSUE TITLE
feat: Please include my directive on Ionic Framework Core

### ISSUE THREAD

**Issue by jdnichollsc** [driftyco/ionic#4606]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi guys,

Please, include my directive! :dancers: 

Link: http://codepen.io/jdnichollsc/full/meKXQY/

Regards, Nicholls</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jdnichollsc!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4606). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4606)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Hey there. Ionic 1 won't be adding any more features. You could consider putting this up for free on the market, or creating your own module and distributing from github. Thanks.
