### ISSUE TITLE
bug: Transistions with rtl languages

### ISSUE THREAD

**Issue by elliotstokes** [driftyco/ionic#4608]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>With the ionic tabs starter project edit the index.html and add dir="rtl" in the top level element. The app should load correctly and be right to left. 

Click on the chats tab and then one of the chats, the page will transition and briefly show before going blank.

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @elliotstokes!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4608). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4608)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by elliotstokes** [comment]
<img width="373" alt="screen shot 2015-11-06 at 16 37 49" src="https://cloud.githubusercontent.com/assets/4385563/11002465/c415a8cc-84a4-11e5-993e-c72d70754433.png">

**Comment by nadavhury** [comment]
Platform : Android

Same Here, if dir="rtl" on html tag
when navigating, some screen shows for only a second and then go blank.
In firefox browser and in Edge there are no problems,
only chrome, havnt check ios yet.

**Comment by elliotstokes** [comment]
breaks on iOS also.

**Comment by nadavhury** [comment]
Found that if you specify dir="rtl" on ion-nav-bar and ion-nav-view separately (not on html or body) then 
it works ok and the direction changes...
but have not made such progress to see if it will hold.

**Comment by jgw96** [comment]
This issue is related too https://github.com/driftyco/ionic/issues/5035

**Comment by jgw96** [comment]
Hello all! Because this is going to be handled in the above linked issue i am going to be closing this issue as a duplicate for now. Thanks for using Ionic!
