### ISSUE TITLE
bug: Bug with Tabs

### ISSUE THREAD

**Issue by siliconplains44** [driftyco/ionic#4611]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am using the ionic tabbed view template.  On the first tab I have sub views that slide open perfectly, but I have a second main tab with sub views.  Although I setup the angular router perfectly and all appears correct, the sub views in the second tab will not open.  </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @siliconplains44!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4611). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4611)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
