### ISSUE TITLE
feat: ion-list with swipeable items

### ISSUE THREAD

**Issue by schoettler** [driftyco/ionic#4615]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello everyone!

I've been looking to implement something like this in my Ionic app:

http://plnkr.co/edit/5ezZJ3yFFWVQWypAgC4h?p=preview

Unfortunately, i found some incompatibility with collection-repeat (Want to render an array of objects lightning fast, and ng-repeat doesn't make me happy).

Is it any initiative we can contribute on?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @schoettler!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4615). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4615)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!

**Comment by schoettler** [comment]
If anyone is still looking for this directive, i have created it:

https://github.com/schoettler/ionic-swipe
