### ISSUE TITLE
feat: Push for Amazon Devices

### ISSUE THREAD

**Issue by nealvs** [driftyco/ionic#4616]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>webview</span>

<span ionic-description>Ionic Push needs to expand to include support for Amazon Device Messaging for Amazon Fire devices.  </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @nealvs!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4616). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4616)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
HI @nealvs, mind posting over at Ionic IO issues page for the platform stuff so the platform team can help? https://github.com/driftyco/ionic-io-issues/issues
