### ISSUE TITLE
ion-pane documentation missing

### ISSUE THREAD

**Issue by fadamakis** [driftyco/ionic#4625]
http://ionicframework.com/docs/api/directive/ionPane/

https://github.com/driftyco/ionic/blob/master/js/angular/directive/pane.js#L2

**Comment by Ionitron** [comment]
Greetings @fadamakis!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4625). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4625)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
