### ISSUE TITLE
bug: ion-refresher sometimes doesn't work with native scrolling on iOS using WKWebView

### ISSUE THREAD

**Issue by tomkelsey** [driftyco/ionic#4626]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Every 1 out of 20/30 refreshes appears to bug and the "invisible" style property of the ion-refresher is incorrectly kept. When this happens you can't pull down to refresh. It seems to happen on any page with an ion-refresher.

I'm using the latest version of Ionic (1.1.1) with the Telerik plugin to enable WKWebView (https://github.com/Telerik-Verified-Plugins/WKWebView)

I know Ionic doesn't officially support the native scroll version of pull to refresh on iOS because of the limitations of UIWebView. However, as scroll events fire during scroll in WKWebView I think the native implementation should work?

I'm guessing WKWebView will be properly incorporated into Cordova at some point so, even if no-one has any ideas as to why it might flip out at the moment, hopefully this is a helpful heads up of a quirk to watch out for.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @tomkelsey!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4626). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4626)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mcouzinet** [comment]
I notice the same problem on ios 9

**Comment by Elvistelefon** [comment]
Same here. I try dig into it.

**Comment by Athyrion** [comment]
Same here. 
Cordova 5.4.1, 
Ionic 1.1.1, 
no WKWebView-Plugin, 
iOS 9.2

**Comment by mharrisn** [comment]
+1 Same issue with UIWebview.
Ionic 1.2.1
iOS 9.2

**Comment by mlynch** [comment]
Have you tried 1.2.4? There were a few fixes in between then

**Comment by johnnyoin** [comment]
1.2.4 fixes the problem for me.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue and it looks like it was fixed in an update i will be closing it, but feel free to reopen this issue if needed!
