### ISSUE TITLE
bug: npm installation issue

### ISSUE THREAD

**Issue by lpotapczuk** [driftyco/ionic#4631]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hey guys,

I've tried to install ionic on my MacBook lately, but I have the following error: 

>MacBook:folder Uksz$ sudo npm install ionic -g
>/usr/local/bin/ionic -> /usr/local/lib/node_modules/ionic/bin/ionic

> node-sass@3.4.1 install /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/node-sass
> node scripts/install.js

>sh: node: command not found
>npm WARN install:node-sass node-sass@3.4.1 install: `node scripts/install.js`
>npm WARN install:node-sass spawn ENOENT

> spawn-sync@1.0.14 postinstall /usr/local/lib/node_modules/ionic/node_modules/ionic-app->lib/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

>sh: node: command not found
>npm WARN install:spawn-sync spawn-sync@1.0.14 postinstall: `node postinstall`
>npm WARN install:spawn-sync spawn ENOENT
>/usr/local/lib
>`-- (empty)

>npm ERR! code 1

I was wondering if any of you has came across this issue, and have any suggestions on how to solve it. 

Thanks!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @lpotapczuk!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4631). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4631)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Could you provide the following

```
node -v
npm -v 
```

**Comment by lpotapczuk** [comment]
Yes! I was using latest version of both node and npm - 5.0.0 for node, and 3.3.6 for npm. I've managed to solve the issue by downgrading to node 4.2, and using --unsafe-perm tag during installation.
