### ISSUE TITLE
bug: Card showcase quirk when nested into striped tabs

### ISSUE THREAD

**Issue by AGrzes** [driftyco/ionic#4632]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>http://codepen.io/anon/pen/KdbOqM
What I did:
Took "[Tabs And Navigation: Nightly](http://codepen.io/ionic/pen/odqCz)" pen
Added [Card showcase](http://ionicframework.com/docs/components/#card-showcase) on the home page
Added
```javascript
.config(function($ionicConfigProvider) {    
  $ionicConfigProvider.tabs.style('striped');
});
```

Now the buttons inside card are styled differently.
Is there a way to get nice buttons on a card (like in a showcase) regardless of global tabs settings?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @AGrzes!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4632). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4632)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ahmed-abdulmoniem** [comment]
Any fix?

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!

**Comment by ahmed-abdulmoniem** [comment]
It is not a question actually, I think it is a bug because this is happening not because we are using ionic in a wrong order or something but it is an error just when you try ionic card showcase with tab stripes. So, any solution or clue here?

**Comment by ahmed-abdulmoniem** [comment]
I have sent my question on ionic slack .. and I got that tabs are not supported any more in cards
https://github.com/driftyco/ionic-site/commit/d434ef5058413b1f2055761b266c1c7e7ca42449

Here is a suggested solution also
http://codepen.io/mhartington/pen/zqNRdZ
