### ISSUE TITLE
bug: Slidebox litters slide parent scopes with child directive controller names

### ISSUE THREAD

**Issue by RobiFerentz** [driftyco/ionic#4633]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When ion-slide contains directives with their own controllers using controllerAs in the directive definition object, the containing ionSlideBox scope is littered with empty properties named corresponding with the the directive controllers initially non-active slides. This causes a very annoying issue when passing values to bound attributes.

E.G:
```
<ion-slide-box show-pager="false" active-slide="ctrl.activeTab">
      <ion-slide>
        <some-dir some-bound-attr="ctrl.conversation"></some-dir> //controllerAs 'ctrl'
      </ion-slide>
      <ion-slide>
        <some-dir1 some-bound-attr="ctrl.conversation1"></some-dir>//controllerAs 'ctrl1'
      </ion-slide>
      <ion-slide>
        <some-dir2 some-bound-attr="ctrl.conversation2"></some-dir>//controllerAs 'ctrl2'
      </ion-slide>
      <ion-slide>
        <some-dir3 some-bound-attr="ctrl.conversation3"></some-dir>//controllerAs 'ctrl3'
      </ion-slide>
    </ion-slide-box>
```

The containing scope will have empty properties named 'ctrl1','ctrl2','ctrl3' .
Now imagine this if all your controllerAs names are the same name... :sob: </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @RobiFerentz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4633). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4633)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
We just landed a new slider component that solves this issue. It's in master and will be in 1.2 To use it today, do this:

```html
<ion-slides options="options" slider="data.slider">
  <ion-slide-page>
  </ion-slide-page>
</ion-slides>
```
and your JS:

```
controller('MyCtrl', function($scope) {
      $scope.options = {
        loop: true
      }

      $scope.data = {};

      $scope.$watch('data.slider', function(nv, ov) {
        $scope.slider = $scope.data.slider;
      })

      $timeout(function() {
        $scope.slider.slideNext();
      }, 1000)

});
```

**Comment by RobiFerentz** [comment]
Awesome, thank you! :+1:
