### ISSUE TITLE
bug: Ionic Modal displays only once

### ISSUE THREAD

**Issue by elhamsarikhani** [driftyco/ionic#4634]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm having a simple modal to be displayed while the data is being fetched from an API call. as I trigger the loading once, the modal gets displayed and the data will be loaded but upon second time click on loading button, the modal won't load anymore. 

     $ionicModal.fromTemplateUrl('views/loading.html', {
		scope: $scope,
		backdropClickToClose: false,
		hardwareBackButtonClose: true,
		animation: 'slide-in-up'
	}).then(function(modal) {
		$scope.modal = modal;
	});

	$scope.openModal = function() {
		$scope.modal.show();
		alertServices.getInvoices()
			.then(function(data) {
				$scope.closeModal();
			})
	}

	$scope.closeModal = function() {
		$scope.modal.hide();
	};

	$scope.$on('$destroy', function() {
		$scope.modal.remove();
	});

**Comment by Ionitron** [comment]
Greetings @elhamsarikhani!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4634). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4634)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by elhamsarikhani** [comment]
I found out the issue root cause:
the http calls to API was using  `cache: 'true'` it should have been `cache: false`

**Comment by tlancina** [comment]
Closing as it sounds like the issue was resolved.
