### ISSUE TITLE
Meteor package should add the assets as scss.

### ISSUE THREAD

**Issue by AlexFrazer** [driftyco/ionic#4639]
Pretty easy with fourseven:scss

```
api.addFiles([
 'scss/_action-sheet.scss',
 // ...
]);
```

Can put in PR

**Comment by Ionitron** [comment]
Greetings @AlexFrazer!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4639). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4639)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hi @AlexFrazer, a PR would be great, going to close since it's kind of ancillary to Ionic at this point (but happy to review a PR).
