### ISSUE TITLE
bug: bug: ion-infinite-scroll with native scrolling

### ISSUE THREAD

**Issue by luchusnet** [driftyco/ionic#4640]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi, when I try to perform pulltorefresh, immediately before it runs "on-infinite" from "ion-infinite-scroll". Here is the code:

`<ion-content> `                                                           
`	<ion-refresher>`
	`	pulling-text="Tirar para actualizar"`
	`	refreshing-text="Actualizando..."`
	`	on-refresh="doRefresh()">`
`	</ion-refresher>`
`<div class="list">`
`   ........  cards items`
`</div><!-- end: div list --> `

`<ion-infinite-scroll`
`	ng-if="moreDataCanBeLoaded()"`
`	on-infinite="loadMore()"`
`	distance="1%">`
`</ion-infinite-scroll>`

`</ion-content>`</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @luchusnet!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4640). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4640)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tonyisid** [comment]
I have the same issue. Do you have any solution yet?

**Comment by luchusnet** [comment]
I think this bug is resolved on last release 1.2.4. But this release only support from api android 4.1 . Is a problem for me :S

**Comment by jgw96** [comment]
Hello @luchusnet ! are you still experiencing this issue? I know you said it was fixed in 1.2.4 but that you needed to support android devices older than 4.1 correct?

**Comment by jgw96** [comment]
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again
