### ISSUE TITLE
bug: Intermittent installation difficulties due to large number of dependencies 

### ISSUE THREAD

**Issue by mushishi78** [driftyco/ionic#4641]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>There have been numerous reportings of installation problems due to bad connections that have been raised:

[npm/npm #8196](https://github.com/npm/npm/issues/8196)
[#4534](https://github.com/driftyco/ionic/issues/4534)
[#4535](https://github.com/driftyco/ionic/issues/4535)
[forum.ionicframework.com #20546](http://forum.ionicframework.com/t/ionic-problem-installation/20546)
[forum.ionicframework.com #34919](http://forum.ionicframework.com/t/facing-connection-reset-error-on-updating-ionic-in-ubuntu/34919)
[forum.ionicframework.com #35371/5](http://forum.ionicframework.com/t/npm-install-g-ionic-alpha-err/35371/5)
[forum.ionicframework.com  #20090/12](http://forum.ionicframework.com/t/cant-install-ionic-via-npm/20090/12)

It appears most of the users that have reported these issues have not persisted with their concerns because, as it's an intermittent problem, they have been satisfied as soon as the installation goes successfully for them. However this is probably after hours/days of superstitiously trying different versions of node, npm and ionic, until either their network connection improves or they change location.

Although network connection issues are not caused by Ionic per se, @othiym23 [suggests](https://github.com/npm/npm/issues/8196#issuecomment-152415722) they are exasperated greatly by it's large number of  shrink-wrapped dependencies and that ember-cli improved installation reliability by bundling their dependencies. Would this be possible?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mushishi78!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4641). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4641)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mushishi78** [comment]
Closing as there is already an issue for this the ionic-cli repo: [ionic-cli #636](https://github.com/driftyco/ionic-cli/issues/636)
