### ISSUE TITLE
perf: Using gulp to create dist folder, and building form it?

### ISSUE THREAD

**Issue by lpotapczuk** [driftyco/ionic#4642]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hey!

I have created a gulp script that will build and minify all of the files into couple of minified files. It will be all created ini dist folder, that has the same structure as the www folder (the one that gets build to the chosen platform). I am wondering, how can I run 'ionic build ios' so that my dist folder is considered a source for building, rather than www folder?

Thanks
Lukasz</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @lpotapczuk!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4642). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4642)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tomkelsey** [comment]
Hi @lpotapczuk 

I *think* what you're after is in the `hooks` folder - specifically within the `after_prepare` folder. You want to edit `010_add_platform_class.js` to refer to the correct directory.

Alternatively, treat the `www` folder as the distribution directory and keep your source files elsewhere.

Hope that's some help!

**Comment by mlynch** [comment]
Going to close since this question would be better on the forum or stack overflow. https://forum.ionicframework.com/. Top of my head, you would have to modify your gulpfile locally, which is certainly an okay thing to do!
