### ISSUE TITLE
bug: Radio items have no tick (on 1.1.1)

### ISSUE THREAD

**Issue by dariosalvi78** [driftyco/ionic#4644]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://codepen.io/anon/pen/VvRzvr

But it works in 1.1.0 !</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @dariosalvi78!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4644). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4644)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This was a change in 1.1.1, you're just missing an element. Probably better to use `ion-radio` instead

http://codepen.io/mhartington/pen/bVZrgJ?editors=100

**Comment by dariosalvi78** [comment]
thanks!
you should update the documentation on http://ionicframework.com/docs/components/#radio-buttons
