### ISSUE TITLE
bug: Touch Scrolling on Android really out of sync

### ISSUE THREAD

**Issue by matthiasg** [driftyco/ionic#4646]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>When scrolling via touch on chrome or anywhere really, i touch a point on the page and move it up or down. The point is fixed. I was just testing with ionic and scrolling is really off. Its sped up at about twice the actual supposed scroll rate.

When using a real device that is really irritating. When i attach with Chrome Dev Tools you can see it happening. Watch how the page scrolls around faster than the touch point. 

![ionic-fast-scroll](https://cloud.githubusercontent.com/assets/231889/11264913/104ccb9c-8e98-11e5-9603-cf0564ec2a85.gif)

Anybody have an idea why ? The same app on Chrome on that same device doesnt have this issue.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @matthiasg!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4646). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4646)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by matthiasg** [comment]
i tried it for way longer and it doesnt seem consistent. since i cannot reproduce reliably, i will close this for now. if someone else has this issue too or i find out more details it can be reopened.

**Comment by redeemedfadi** [comment]
I'm also noticing this issue on Android 6.0.1 WebView (48.0.2564.106).  However, adding the cordova-plugin-crosswalk-webview plugin seemed to resolve the issue.
