### ISSUE TITLE
bug: Reopening - bug: Navigation and history #4078

### ISSUE THREAD

**Issue by badhrin** [driftyco/ionic#4648]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I am reopening a bug reported in 2013. It was closed automatically by Ionitron around 2-Nov-2015. 

The bug is elaborated very well in the old issue (now closed). Please refer to it here:
https://github.com/driftyco/ionic/issues/4078

Restating the bug again in my own words & experience:
ISSUE 1
In an Ionic app using tabs, when we navigate using the $state.go() as below  :
 Parent State (showing initial data set 1) -> Child State 1 -> Parent State (showing updated data set 2)
The issue is that the Parent State (showing updated data set 2) shows a back button. Ideally I would expect the history stack to be reset to the Parent State & no back button should ever be shown in the Parent state.

CURRENT TEMP FIX FOR ISSUE 1: Use the 'hide-back-button' directive in Parent View

ISSUE 2:
In an Ionic app using tabs, when we navigate using the $state.go() as below  :
 Parent State (showing initial data set 1) -> Child State 1 -> Parent State (showing updated data set 2) -> Child State 1 -> Use back button in Child State 1 to go back to Parent State
The issue is that instead of going to Parent State (showing updated data set 2) it goes to Parent State (show initial data set 1).

CURRENT TEMP FIX FOR ISSUE 2: Do not cache the Parent State i.e Set cache-view = false in the Parent View
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @badhrin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4648). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4648)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#21
