### ISSUE TITLE
bug: ionic not working well with crosswalk

### ISSUE THREAD

**Issue by pranaydutta89** [driftyco/ionic#4650]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>I am making an app for which i have to give compatibility to android ranging 4.1-latest ,for 4.1-4.3 i am using crosswalk  runtime  with ionic and for latest android i am using just ionic framework , the problem is when i install crosswalk plugin the ux seems to be very small and out of shape and form ,this bug is occuring in every android version (5.1,4.4,4.0.4 i had tested) 

![screenshot_2015-11-20-22-17-16](https://cloud.githubusercontent.com/assets/3788500/11305864/c659c7fe-8fd4-11e5-8fed-27974bf4cfe7.png)
![screenshot_2015-11-20-22-18-56](https://cloud.githubusercontent.com/assets/3788500/11305868/c80baf54-8fd4-11e5-8c4a-1039276c6903.png)

the two images will show you the difference,is there any special configuration i am missing,please help me pin down the issue ??</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @pranaydutta89!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4650). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4650)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by pranaydutta89** [comment]
well i think i found the issue i didn't mention the viewport in my project, it seems that without viewport meta tag in case of normal device webview everthing seems fine but after adding cross walk we need to add the viewport meta tag
