### ISSUE TITLE
bug: error when using $ionicLoading.hide(); and show() in quick succession 

### ISSUE THREAD

**Issue by barocsi** [driftyco/ionic#4651]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Almost the same issue as https://github.com/driftyco/ionic/issues/4339 that was fixed in https://github.com/driftyco/ionic/commit/5b39fa34dcaa35108aea37c20a037f5786b00d39

When I $ionicLoading.show(opts) the loader, then close it, and instantly open another loader, that wont be displayed. 

I guess its the problem of referencing the loader OR the async nature: the loader is still in closing animation and some flag/callback is not updated. For example if I employ an 500 ms delay between closing and reopening, there is no problem.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @barocsi!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4651). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4651)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Seems to work for me in nightly, can you confirm?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
