### ISSUE TITLE
bug: Livereload on app

### ISSUE THREAD

**Issue by tumenor** [driftyco/ionic#4652]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<h6>Extraz</h6>
Used the "tabs" app template.

<h3>Actions</h3>
I change something on the dashboard file, and all custom CSS on elements isn't working properly.
It's happening on a font-awesome element, not sure if that is relevant.

I then go to style.css press spacebar, then backspace and save and it works perfectly.

<h3>Problem</h3>
So the problem is that I have to save the css files again to make the livereload reinitiate them.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @tumenor!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4652). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4652)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hey @tumenor, mind posting with more info on CLI version, etc. over at the CLI issues? https://github.com/driftyco/ionic-cli/issues

Closing since this is not a framework proper issue.
