### ISSUE TITLE
bug: Ionic Android release APK don't have access to internet

### ISSUE THREAD

**Issue by nunomaduro** [driftyco/ionic#4655]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm building an app for Android with Ionic/Cordova. The app works fine in the emulator and works fine in the Ionic view app. The app connects to an API in our internal network and everything works fine.

The problem is, when I build the cordova app to Android and install the apk, it doesn't connect to the internet. I can't seem to find what the problem is and why it is not connecting, even though it does work in the emulator and Ionic view.

Note: Over HTTP works. Over HTTPS doesn't.

Does anyone know what the problem would be and why it doesn't work?

I already add the Ionic whitelist plugin and the permissions to my AndroidAManifest.xml.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @nunomaduro!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4655). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4655)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This is less of an issue with ionic but more of a cordova question. You should direct your question to the cordova folks. http://slack.cordova.io
