### ISSUE TITLE
feat: $ionicSideMenuDelegate methods like promises

### ISSUE THREAD

**Issue by francesco-strazzullo** [driftyco/ionic#4656]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I think that it can be useful to turn toogle methods of $ionicSideMenuDelegate. So a developer can do something when the menu is just closed/opened. 

```js
$ionicSideMenuDelegate.toggleLeft(false).then(function(isOpen){
     console.log(isOpen);
});
```

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @francesco-strazzullo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4656). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4656)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hi @francesco-strazzullo, this will work in v2 but for v1 it's not on the roadmap since it's so hard coded to CSS transitions which are a pain to map like that.
