### ISSUE TITLE
bug: Live reload is undefined after getting new updated ionic-cli

### ISSUE THREAD

**Issue by jugal-ionic** [driftyco/ionic#4659]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Please have a look around this issue of live reload is undefined

![image](https://cloud.githubusercontent.com/assets/14929223/11341642/4a259594-9229-11e5-89d0-5ab89be49654.png)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jugal-ionic!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4659). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4659)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hey @jugal-ionic, mind posting over on the CLI issues? Also let us know what version you're running: https://github.com/driftyco/ionic-cli/issues

**Comment by jugal-ionic** [comment]
Where I do need to post this issue & I have tried with ionic@1.0.10 & 1.0.11 version.Both showing this issue.
