### ISSUE TITLE
bug: ion-tabs ng-class not updating

### ISSUE THREAD

**Issue by WilsonFpz** [driftyco/ionic#4662]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Follow #395 
I made a hide-tabs directive and bind the $root.hideTabs to the ion-tabs ng-class.
`<ion-tabs class="tabs-icon-top tabs-color-active-positive" ng-class="{'tabs-item-hide': $root.hideTabs}">`
As you can see in the [codepen](http://codepen.io/WilsonFpz/pen/megwxR?editors=101)
I add hide-tabs directive to 'tab.chats'  and 'tab.chat-detail' status,
but the tabs show when entering to 'tab.chat-detail'. 
and show again when navigating back to the 'tab.chats'
Please help on it . thanks.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @WilsonFpz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4662). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4662)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of wanting help with your custom directive i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
