### ISSUE TITLE
bug: When expose-aside-when is true the menu-close directive should be disabled

### ISSUE THREAD

**Issue by konsultaner** [driftyco/ionic#4663]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm using the expose-aside-when on the side-menu directive and was wondering why my side-menu would dissapear and leave a gap on the opposite site. The reason was that I was also using the menu-close directive at the same time. 

It does the right job, so this is a feature rather then a bug. I cannot see any scenario where a developer would want to close the side menu when it is exposed with expose-aside-when. If for some reason this is the case, then the content should not stay in the reduced width.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @konsultaner!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4663). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4663)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Did this fix it? #2328

**Comment by konsultaner** [comment]
I fixed it with copying the menu-close directive and fixing it:

    ['$ionicHistory', '$timeout', function($ionicHistory, $timeout) {
        return {
            restrict: 'AC',
            link: function($scope, $element) {
                $element.bind('click', function() {
                    var sideMenuCtrl = $element.inheritedData('$ionSideMenusController');
                    if (sideMenuCtrl && !sideMenuCtrl.isAsideExposed()) {
                        $ionicHistory.nextViewOptions({
                            historyRoot: true,
                            disableAnimate: true,
                            expire: 300
                        });
                        $timeout( function() {
                           $ionicHistory.nextViewOptions({
                                historyRoot: false,
                                disableAnimate: false
                            });
                        }, 300);
                        sideMenuCtrl.close();
                     }
                });
            }
        };
    }]

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
