### ISSUE TITLE
bug: installation android failed

### ISSUE THREAD

**Issue by joseterrera** [driftyco/ionic#4669]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Trying to install android platform. When I type: ionic build android

I get:
[Error: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.]

Any ideas on how to update my 'PATH?
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @joseterrera!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4669). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4669)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tcharlem** [comment]
What OS are you on? OSX, Linux, Windows...?

**Comment by joseterrera** [comment]
I'm on OSX

**Comment by tcharlem** [comment]
Ok. Might seem like a silly question, but have you installed the Android SDk. If so, was it the stand alone SDK or through Android Studio?

**Comment by tcharlem** [comment]
If you did install Android SDK correctly, you can add to your path following these insturctions: http://hathaway.cc/post/69201163472/how-to-edit-your-path-environment-variables-on-mac. You can check this page out for what you should add exactly: http://stackoverflow.com/questions/5526470/trying-to-add-adb-to-path-variable-osx. Let me know if you get it going. ;)

**Comment by joseterrera** [comment]
Thanks for your help! I'm a little bit new with this.
So, I modified my PATH:
  export PATH=/Users/joseterrera/android-sdk-mac_86/platform-tools:/Users/me/android-sdk-mac_86/tools:$PATH

  Then I reload the file:

  source ~/.bash_profile

  but it is still not working for me when I try to run:
  ionic platform add android
  ionic build android

  alternatively, I've also tried homebrew but it didn't work..

I have android studio installed. Since it is my first time using it, I don't know how it is all supposed to work together.

**Comment by tcharlem** [comment]
No worries. I'm new to Ionic myself, but have used Android SDK for a few years now. 

First, make sure you have Java SDK installed. http://www.oracle.com/technetwork/java/javase/downloads/index.html

Then do this: 
Open Android Studio 
Go to Configure > SDK Manager

In the "SDK Platforms" tab, make sure you have the following packages installed: http://puu.sh/lxWVX/a1b3826d5d.png

In the "SDK Tools" tab, make sure that you have the following installed: http://puu.sh/lxXhK/3451c34758.png

Now, in order to emulate an app on your desired Device/Android OS version, you'll have to create an AVD with those specifications. You can learn how to do that here: http://developer.android.com/tools/devices/managing-avds.html

Edit your PATH, reboot and try again. 

If it doesn't work, let me know.

**Comment by petehouston** [comment]
@joseterrera  you will also need this since Gradle will look for Android tools with this environment variable

```
$ export ANDROID_HOME=/Users/joseterrera/android-sdk-mac_86
```

**Comment by mlynch** [comment]
Thanks everyone for jumping in. This is a cordova/android installation issue not a framework issue so I'm going to close. Perhaps try reinstalling android/cordova: https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html
