### ISSUE TITLE
bug: Run error at Windows Phone Universal after plugin issue resolve.

### ISSUE THREAD

**Issue by DaniloCouto** [driftyco/ionic#4671]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I've been participating a Ionic Project that has been developed on Android and IOS, 
Sometime on the project development we need a windows phone version.
Well we used [winstore-jscompat](https://github.com/MSOpenTech/winstore-jscompat.git) , and our code worked pretty well with some issues that can be fixed.
But after detecting some errors on cordova-plugin-file and cordova-plugin-media on Android and IOS and resolving then with removing and adding the plugins, We found some bizarre errors on trying to compile for WP (Universal).
Running on Windows 10 Phone Emulator:
>'WWAHOST.EXE' (Script): Loaded 'Script Code (MSAppHost/2.0)'. 
>The program '[2988] WWAHOST.EXE' has exited with code 3 (0x3).

Running on Windows 8.1 Phone Emulator or Device:
>'WWAHOST.EXE' (Script): Loaded 'Script Code (MSAppHost/2.0)'. 
>The program '[3280] WWAHOST.EXE' has exited with code 1 (0x1).

I use Visual Studio 2015 RC on WIndows 10  

Well I just don't know what do.
I Hope that someone with good hearth could give me some direction ^^'
Thanks for the attention</span>

<span is-issue-template></span>

EDIT:
It was an Onesignal-cordova-plugin issue. This closes #4671

**Comment by Ionitron** [comment]
Greetings @DaniloCouto!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4671). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4671)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Thanks for the edit :) closing.
