### ISSUE TITLE
How good BaasBox is with IonicFramework?

### ISSUE THREAD

**Issue by amoebageek** [driftyco/ionic#4674]
I am trying to build a realtime data app,it tried with firebase and it works very smoothly,but its too costly to scale up. I found BaasBox,please suggest me how its easy and good to use for the Realtime data app. Is there documentations and supports available for ionic + BaasBox ?

**Comment by Ionitron** [comment]
Greetings @amoebageek!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4674). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4674)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by amoebageek** [comment]
I have already done,But i didn't get any update.

**Comment by mlynch** [comment]
Hey @amoebageek, this is out of scope of the Ionic project so I need to close. My guess is the tool works well but we have no experience with baasbox
