### ISSUE TITLE
collection-repeat has empty unbound items

### ISSUE THREAD

**Issue by craigp** [driftyco/ionic#4675]
I seem to have a problem in the app I'm working on (not written by me) that causes a collection-repeat to scroll past the available items. When I inspect the HTML it looks like there are more items in the repeat than there should be, and they're unbound.

I'm working through the ionic source, but wondering if this is a known bug or a misconfiguration in the app or something.

**Comment by Ionitron** [comment]
Greetings @craigp!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4675). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4675)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
