### ISSUE TITLE
bug: Unknown provider: $ionicHistoryProvider <- $ionicHistory

### ISSUE THREAD

**Issue by fgrs** [driftyco/ionic#4676]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>might be a nooby question but I have started brand new project but immediately got stuck here

app.controller('MyCtrl', function($ionicHistory) {
  console.log('testing')
})

with this error:

Unknown provider: $ionicHistoryProvider <- $ionicHistory

any idea?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @fgrs!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4676). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4676)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mvofreire** [comment]
Any solution??
