### ISSUE TITLE
Input icons without 'placeholder-icon' class do not have correct padding

### ISSUE THREAD

**Issue by gaballard** [driftyco/ionic#4677]
As you can see in [this Plunkr](http://plnkr.co/ibPbAGzlqDyGHT3WuxW0), input icons only gain right padding with the 'placeholder-icon' class applied. My understanding from the documentation is this is an optional class, but without it the icon and the input run right up against each other. To point out how stark the lack of padding can be with certain icons, I used 'ion-android-locate' rather than the 'ion-search' used in the docs. This would be an extremely easy fix - just add 'padding-right: 6px;' to the 'icon' class.

**Comment by Ionitron** [comment]
Greetings @gaballard!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4677). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4677)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Is there an issue with using placeholder icon? If not, we should make it not optional.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
