### ISSUE TITLE
bug: ui-select only scrolls list of options on ionicPopup. doesn't scroll in ion-view and ion-modal-view

### ISSUE THREAD

**Issue by boyfunky** [driftyco/ionic#4682]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>So i have a form that has a ui-select. And then it populates the data, the list of the options cannot scroll. It can only scroll if it is ionicPopup. But with ionicView and ionicModal, it refuses to scroll. 

`<ui-select name="org" ng-model="user.org.selected" theme="selectize" class="form-control ng-pristine ng-invalid ng-invalid-required" style="margin-top: -5px; margin-left: 7px;" required>
    <ui-select-match placeholder="Organization Name" focus-me="true">{{$select.selected.name}}</ui-select-match>
    <ui-select-choices  repeat="item in rea_list | filter: $select.search |limitTo: 20" position="down">
         <div ng-bind-html="item.name | highlight: $select.search"></div>
    </ui-select-choices>
</ui-select>`

http://codepen.io/mfunkie/pen/bKAaI/

This codepen works on the web but doesnt when in a mobile device. 

When i put this code on an ionicPopup, i can scroll the list of options to view the 20 options in the list but if i put this code on my ion-view on a page or in an ionicModal, i cant scroll through the 20 options.

I have no clue why this is so and I cant figure out a way to solve it too. It works perfectly on web but it doesnt work on mobile device.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @boyfunky!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4682). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4682)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by mnewmedia** [comment]
Yes still with the latest. You can scroll as long as the Keyboard is hidden. As soon as you focus the input, you can't anymore scroll.

```
ionic angular: 1.3.2
Ionic Keyboard: 2.2.1

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.10 
OS: Mac OS X El Capitan
Node Version: v5.12.0
Xcode version: Xcode 8.1 Build version 8B62 
```
