### ISSUE TITLE
feat: Change checkbox icon

### ISSUE THREAD

**Issue by evaflow** [driftyco/ionic#4683]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Is there a way for me to change the checkbox icon from a tick to an icon like ion-star?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @evaflow!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4683). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4683)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Right now it's not possible. Here's a fix for v1: http://stackoverflow.com/questions/29429779/customize-ion-checkbox-default-background-color

v2 should have this support. Thanks!
