### ISSUE TITLE
bug: Wrong VersionCode after compiling

### ISSUE THREAD

**Issue by MazzMazz** [driftyco/ionic#4684]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>My problem is that if I compile my project, it adds a 2 to the build number.

My Ionic config.xml
```
<widget id="at.company.or.so" version="0.0.1" ios-CFBundleVersion="55" android-versionCode="72" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
```

My AndroidManifest.xml

```
<manifest android:hardwareAccelerated="true" android:versionCode="72" android:versionName="0.0.1" package="at.tiddlr.app" xmlns:android="http://schemas.android.com/apk/res/android">
```
If i build a debug or release Version should be 0.0.1(72) but when i install the App it is 0.0.1(722)

Output of aapt aapt d badging apk.apk
```
package: name='at.company.or.so' versionCode='722' 
versionName='0.0.1'platformBuild
VersionName='5.1.1-1819727'
sdkVersion:'14'
targetSdkVersion:'22'
```

The related stackoverflow post:
http://stackoverflow.com/questions/32008127/ionic-build-number-wrong-in-config-xml-file
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @MazzMazz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4684). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4684)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by petehouston** [comment]
mine is running fine,

```
$ ionic --version
1.7.10
$ cordova --version
5.4.0
```

**Comment by MazzMazz** [comment]
$ ionic --version
1.7.10
$ cordova --version
5.4.1
would be my setup. But i just tested it again just to be sure.
In my config.xml
```
android-versionCode="95"
```
but in the apk file:
```
versionCode='952'
````

**Comment by petehouston** [comment]
@MazzMazz I see. It's a Cordova issue, I'm making a PR, notify you soon :)

**Comment by mlynch** [comment]
Hey guys, closing since this is not a framework issue. If necessary, can you file an issue here with more info? https://github.com/driftyco/ionic-cli/issues Thanks!
