### ISSUE TITLE
ionic resourceshangs

### ISSUE THREAD

**Issue by super-coder** [driftyco/ionic#4685]
Edit: Title: **ionic resources hangs**
i have files as described and ionic resources console log says everything is fine but it stops on this line
icon android drawable-ldpi-icon.png (36x36) generated
and nothing after this. The folders are empty

**Comment by Ionitron** [comment]
Greetings @super-coder!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4685). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4685)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
This is a CLI issue, mind posting here? https://github.com/driftyco/ionic-cli/issues
