### ISSUE TITLE
bug: iOS9.1 Cant find variable Cordova

### ISSUE THREAD

**Issue by sonukapoor** [driftyco/ionic#4687]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>My ionic application was working fine < 9.1. I now upgraded the iPod device to the latest iOS version and receive the above error: Can't find variable Cordova. Anybody knows what is going on with this?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @sonukapoor!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4687). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4687)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by sonukapoor** [comment]
Please close. False alarm.
