### ISSUE TITLE
bug: Always reloading page on back

### ISSUE THREAD

**Issue by wggley** [driftyco/ionic#4690]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,
I have a page with ng-repeat and inside anchors leaving to a detail page.
When going to detail page and back, for the first element of the ng-repeat, the view is always reloading, but just for the first one.
Other links back state is working correctly not reloading entire view.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @wggley!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4690). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4690)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by wggley** [comment]
Sorry,
It's happening to other elements too not just the first.

**Comment by mlynch** [comment]
@wggley we would need to see an example to help. As such, take a look at the lifecycle events for views to see if you could utilize one (like `$ionicView.enter`): http://ionicframework.com/docs/api/directive/ionView/. Closing for now.
