### ISSUE TITLE
Why not checking $$disconnected in reconnectScope() but not disconnectScope()

### ISSUE THREAD

**Issue by guday** [driftyco/ionic#4691]
In Fn reconnectScope:
![image](https://cloud.githubusercontent.com/assets/7075757/11497150/0167f28c-9852-11e5-86cb-0d989f32d80a.png)

And in Fn disconnectScope:
![image](https://cloud.githubusercontent.com/assets/7075757/11497159/1731aff4-9852-11e5-826e-6186ec53cbba.png)

**Comment by Ionitron** [comment]
Greetings @guday!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4691). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4691)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hey @guday, is there an issue or something this is causing? Closing for now, let me know and I'll reopen

**Comment by guday** [comment]
As setting cache:true in app-config.js to make view cached. I need to find a Fun that fired after connectScope but not initScope.

There is a event `$ionicView.enter` which fired after connectScope ,but when initScope,it fired twice.

Then i findout this event '$ionic.reconnectScope'  which fired after coming into a cached view.

**Comment by guday** [comment]
But, event '$ionic.disconnectScope' will fired not only leaving cached view but each time leaving another cached view.

To solve this problem, i fired another event to make sure fired once after leaving an cached view.
![image](https://cloud.githubusercontent.com/assets/7075757/11780114/89caf0a0-a29a-11e5-98a0-3e892275ce65.png)

**Comment by guday** [comment]
![image](https://cloud.githubusercontent.com/assets/7075757/11780152/d78efdcc-a29a-11e5-817f-a51746eff91c.png)

**Comment by guday** [comment]
Here is the code in controller
![image](https://cloud.githubusercontent.com/assets/7075757/11780331/223e8120-a29c-11e5-825a-8ea0984322dc.png)
