### ISSUE TITLE
bug: Radio buttons stopped working?

### ISSUE THREAD

**Issue by Hacktivista** [driftyco/ionic#4692]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Looks like radio buttons are not showing changes properly. I did update ionic in my project and seen the error, later checked on website, and it does not work either :\

Here is the link: http://ionicframework.com/docs/components/#radio-buttons</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Hacktivista!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4692). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4692)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Fixing.
