### ISSUE TITLE
bug: Cache dir is required

### ISSUE THREAD

**Issue by aziflaj** [driftyco/ionic#4693]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I just created a blank application and when adding Android as a platform, I got this output:

Updated the hooks directory to have execute permissions
Error: Cache dir is required

I think it might be an issue with Cordova, but I can't find how to fix it</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @aziflaj!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4693). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4693)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Please paste the out put form `ionic info`

**Comment by aziflaj** [comment]
Here you go @mhartington 

```bash
Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.1.1
Ionic CLI Version: 1.7.11
Ionic App Lib Version: 0.6.5
OS: Distributor ID:	Fedora Description:	Fedora release 23 (Twenty Three) 
Node Version: v5.1.0
```

**Comment by mlynch** [comment]
@aziflaj sounds like a possible CLI issue, mind posting over at https://github.com/driftyco/ionic-cli/issues?

In the meantime, can you try the beta to see if that helps:

`npm install -g ionic@beta`
