### ISSUE TITLE
bug: Neither "ionic platform update ios" nor "ionic build ios" updates plugins in the "platforms/ios" directory

### ISSUE THREAD

**Issue by matthewlloyd** [driftyco/ionic#4694]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Example:

```
macbook-pro-2:ionic-app mil$ diff plugins/ionic-plugin-deploy/src/ios/IonicDeploy.m platforms/ios/UAV\ Forecast/Plugins/ionic-plugin-deploy/IonicDeploy.m
242d241
<             [self updateVersionLabel:NOTHING_TO_IGNORE];

macbook-pro-2:ionic-app mil$ ionic platform update ios
...
macbook-pro-2:ionic-app mil$ ionic build ios
...

macbook-pro-2:ionic-app mil$ diff plugins/ionic-plugin-deploy/src/ios/IonicDeploy.m platforms/ios/UAV\ Forecast/Plugins/ionic-plugin-deploy/IonicDeploy.m
242d241
<             [self updateVersionLabel:NOTHING_TO_IGNORE];

```

The line added to the file in the ```plugins/``` directory was added in v0.4.1, to fix a bug which broke deploys on iOS.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @matthewlloyd!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4694). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4694)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hey @matthewlloyd, I'm trying to figure out exactly where to route this one, if you think it's a CLI or possibly Cordova command issue (i.e. does the same issue happen with cordova build instead of ionic build?) then mind filing over here? https://github.com/driftyco/ionic-cli/issues

Going to close since it's not a framework issue specifically. Almost looks like it could be related to the deploy service? https://github.com/driftyco/ionic-platform-web-client
