### ISSUE TITLE
bug: Ionic state change issues on iOS 9 post version update to 1.1.1

### ISSUE THREAD

**Issue by ymashalkar** [driftyco/ionic#4697]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>Confirming that i have updated Ionic to 1.1.1, so assuming the iOS9 webview patch is included in it. However, i am still facing issues with side menus onclick of which i am invoking $state.go() which does not render the actual page & reverts to original state. UI is completely broken.

Below is the system information:
    Cordova CLI: 5.3.3
    Gulp version:  CLI version 3.9.0
    Ionic Version: 1.1.1
    Ionic CLI Version: 1.7.10
    Ionic App Lib Version: 0.6.5
    ios-deploy version: 1.8.3 
    ios-sim version: 5.0.3 
    OS: Mac OS X El Capitan
    Node Version: v0.12.7
    Xcode version: Xcode 7.1.1 Build version 7B1005

HTML Code in the side menus:

    <ion-item menu-close href="#" ng-click="getWishlist()" ng-if="userId && userId != ''">
      <div class="row">
           <div class="col col-20">
              <i class="ion-heart"></i>
           </div>
           <div class="col col-80">
               My Wishlist
           </div>
      </div>
</ion-item>

JS Code in getWishlist():

    $scope.getWishlist = function (){
    $state.go("app.wishlist", {}, {reload: true});
}

Help appreciated!

Note: Static URL invocations within menu seem to work just fine!

    <ion-item nav-clear menu-close href="#/app/contact-us"  >
            <div class="row">
                <div class="col col-20">
                  <i class="ion-ios-telephone"></i>
                </div>
                <div class="col col-80">Contact Us
                </div>
            </div>
</ion-item></span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ymashalkar!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4697). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4697)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ymashalkar** [comment]
Well, i guess it was my bad for not reading this [post](http://blog.ionic.io/ios-9-potential-breaking-change/) properly!

I figured the issue was due to `href='#'`. The post does mention to remove empty href links if necessary which invoke the `otherwise` state in iOS 9. Once i removed them the links started to work as expected.

However, i did have to alter my CSS to cover the menu UI since there were other static links with non-empty `href`, both on iOS & Android build

Thanks for the patch & the post! Closing the issue.
