### ISSUE TITLE
ionic slidebox does-continue doesn't work if update in ajax call

### ISSUE THREAD

**Issue by ryanlin1986** [driftyco/ionic#4699]
In setup function, found the following code:
if (slides.length < 2) options.continous = false;
This is wrong because in this always true if I'm initialzing in ajax call, which will override the initial does-continue value from html.

**Comment by Ionitron** [comment]
Greetings @ryanlin1986!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4699). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4699)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hey @ryanlin1986, we just pushed a new slidebox implementation to the repo. Mind giving it a try in master (or waiting for 1.2)?

You could try it like this:

```html
<ion-slides options="options">
  <ion-slide-page>
  </ion-slide-page>
</ion-slides>
```

```javascript
controller('MyCtrl', ['$scope', function($scope) {
  $scope.options = {
    loop: true
  };
}]);
```
