### ISSUE TITLE
bug: $locationProvider.hashPrefix() crash the Ionic Tab

### ISSUE THREAD

**Issue by marcossffilho** [driftyco/ionic#4702]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I don't know if this issue is related to the `$ionicTabs` controller, or to the `$location` service from Angular, but when I define a hashPrefix for the URLs, tabs stop working.

Here's a CodePen: http://codepen.io/marcossffilho/pen/KVPYgq
The second tab is only accessible if I comment the hashPrefix.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @marcossffilho!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4702). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4702)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Wonder if it's related to this check for the hash instead of `hashPrefix`: https://github.com/driftyco/ionic/blob/336c3882a0b0767c60dc922e8d7bc3f3ab508669/js/angular/service/history.js#L810

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
