### ISSUE TITLE
feat: Feature Request: maxLength option for $ionicPopup.prompt()

### ISSUE THREAD

**Issue by gregallensworth** [driftyco/ionic#4704]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description><INPUT> elements support the *maxlength* property, which is quite handy if you want to constrain text to only short values, e.g. a nickname. $ionicPopup.prompt() does not have an option to supply a maxLength.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @gregallensworth!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4704). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4704)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Thanks! Closing since your PR got merged and going to track it there.

**Comment by DrkCoater** [comment]
Still not working? Seems like when I put the maxLength property to 40, it does not affect the input.
