### ISSUE TITLE
bug: $ionicPopup.prompt() broken if "quotes" used in inputPlaceholder

### ISSUE THREAD

**Issue by gregallensworth** [driftyco/ionic#4707]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>$ionicPopup.prompt() supports the *inputPlaceholder* option. This is not escaped, but used as-provided when passed to popup.js showPrompt()

Use of quotes will cause invalid HTML to be generated, causing at minimum the placeholder to be truncated, but potentially other strangeness, e.g. if the input contains a > character as well, it could terminate the <INPUT> tag and cause other misbehavior.

Example:

```
   $ionicPopup.prompt({
      title: 'Three Words Below?',
      inputPlaceholder: 'your "favorite" ><b>here',
   });
```

Implement check to escape these properly, since they are being placed inside an attribute.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @gregallensworth!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4707). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4707)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by gregallensworth** [comment]
Confirmed that bug is absent when using *defaultText* option since this uses *ng-model* and is subject to Angular's own escaping. Title updated.

**Comment by gregallensworth** [comment]
Commit d3fad60 just follows this same pattern that was developing, of using Angular's own templating and binding instead of raw string interpolation. This should make $ionicPopup.prompt() more forgiving of certain types of input errors, and provide a clear copy-paste-easy method for adding new options in the future.
