### ISSUE TITLE
bug: text vertical alignment on xperia z3 compact

### ISSUE THREAD

**Issue by nicolaveritas** [driftyco/ionic#4708]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>device: sony xperia z3

running my app on Android device (Xperia z3 compact) I have a little layout problem:

every text in default ionic directive (such as nav-bar title, tab title, every single button etc) is not vertically centered. It seems like a wrong padding is applied.

Testing in chrome simulating any android device the problem does not appear.
Testing on Nexus 5 layout is ok</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @nicolaveritas!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4708). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4708)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hey @nicolaveritas, thanks for the report. Any chance you could send a screenshot of the issue? Thanks.

**Comment by nicolaveritas** [comment]
Here is a screenshot, is clearly visible on navbar, tabs and button. Less visibile but still present in card-element title and content.

Thanks in advance

![screenshot_2015-12-06-12-03-12](https://cloud.githubusercontent.com/assets/10831345/11613048/1f3a6348-9c13-11e5-9727-4dc42a39a0c5.png)

**Comment by jgw96** [comment]
Hello (: Are you still seeing this issue in the latest version of ionic?

**Comment by jgw96** [comment]
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Comment by nicolaveritas** [comment]
Sorry for being late, but yes the issue is still visibile with the latest version

**Comment by aberonni** [comment]
Can we reopen this? I am having the same issue on Samsung Galaxy S6.
