### ISSUE TITLE
Feature Request - on swipe back event

### ISSUE THREAD

**Issue by SMarijic** [driftyco/ionic#4716]
Is it possible to add swipeBack event on iOS?

**Comment by Ionitron** [comment]
Greetings @SMarijic!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4716). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4716)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
You can do this to know when the swipe back happened:

```javascript
  $scope.$on('$ionicView.enter', function() {
    console.log('Enter');
  });
```

But we don't have a way to do it specifically beyond that.

**Comment by SMarijic** [comment]
@mlynch  I did take a look at the code in initSwipeBack() method, is it possible to add event in that method, before you trigger the action view switch?
