### ISSUE TITLE
docs: $ionicListDelegate: formatting wrong

### ISSUE THREAD

**Issue by mrzmyr** [driftyco/ionic#4718]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>http://ionicframework.com/docs/api/service/$ionicListDelegate/#closeOptionButtons

<img width="459" alt="screen shot 2015-12-06 at 00 51 01" src="https://cloud.githubusercontent.com/assets/746429/11610919/7d168d30-9bb3-11e5-83c6-d456c775993b.png">
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mrzmyr!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4718). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4718)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Weird, should be fixed now... Thanks!
