### ISSUE TITLE
bug: npm install -g ionic fails with ECONNRESET

### ISSUE THREAD

**Issue by super-coder** [driftyco/ionic#4721]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Can't do **npm install -g ionic**
May be related to this issue https://github.com/npm/npm/issues/8196
Log attached
[npm-debug.log.txt](https://github.com/driftyco/ionic/files/53182/npm-debug.log.txt)

</span>

<span is-issue-template></span>

Edit: Windows 8.1 x64

**Comment by Ionitron** [comment]
Greetings @super-coder!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4721). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4721)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Thanks, going to close for now since it's not an ionic framework issue, though we are aware of it and getting in touch with npm to try to figure out what's going on. In the meantime, can you post here? https://github.com/driftyco/ionic-cli

**Comment by spaquet** [comment]
I just want to let you know that I have the same issue, as reported in https://github.com/npm/npm/issues/8196\#issuecomment-162336470, on OS X version 10.11 with nam 3.3.12
Ionic is so far the only nam package that does not install or upgrade.

**Comment by super-coder** [comment]
@mlynch how is it ionic-cli issue? I am not using ionic command line, I am using npm with ionic

**Comment by super-coder** [comment]
I am going to re-open it because nothing happens, and basically fro a bunch of people ionic is unusable
