### ISSUE TITLE
bug: fail to load after updating to ionic 1.1.1

### ISSUE THREAD

**Issue by claire119119** [driftyco/ionic#4730]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>error: "$$asyncCallbackProvider <- $$asyncCallback <- $animate <- $compile" shows after I updated to ionic 1.1.1 and reloaded the site. I have tried to use ionic CLI to update and once again used bower to update, but no luck. What did I do wrong?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @claire119119!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4730). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4730)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hi @claire119119, I'm not sure but it seems like an issue with tooling or bower. Mind posting over here? https://github.com/driftyco/ionic-cli

Closing for now since not a framework-specific issue.
