### ISSUE TITLE
feat: default options in $ionicPopup

### ISSUE THREAD

**Issue by francesco-strazzullo** [driftyco/ionic#4732]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In ionicPopup you cannot set default options for prompt,confirm etc etc. It wuold be useful to set some default options during **config phase**. For example the default *cancelText* with something like:

```
myApp.config(function($ionicPopupProvider){
    $ionicPopupProvider.setConfirmDefaultOptions({
        title:'Are You sure?',
        cancelText:'No Way Bro!'
    });
})
```

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @francesco-strazzullo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4732). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4732)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adellava** [comment]
+1

**Comment by mlynch** [comment]
Thanks, while I can see the value of this, I don't think it's much to ask to just put those values in for each call, right? Also it seems like the normal case would be the standard defaults rather than a custom default for every popup. I'm going to close for now since I don't know if this is a necessary feature.

**Comment by francesco-strazzullo** [comment]
I think It could be useful to every non english application. You should set the default cancelText and okText only one time.
