### ISSUE TITLE
bug: Ionic CLI doesn't work with Node v5

### ISSUE THREAD

**Issue by jettdigital** [driftyco/ionic#4736]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>As far as I can tell doing any "ionic build" or "ionic run" command will just return the user back to the command prompt without any kind of error message. I reverted from Node v5 to Node v4 and things started working again.

Ionic Info
Cordova CLI: 5.1.1
Ionic Version: 1.0.0
Ionic CLI Version: 1.7.11
Ionic App Lib Version: 0.6.5
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.0.0
Xcode version: Xcode 7.1.1 Build version 7B1005</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jettdigital!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4736). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4736)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by andreialecu** [comment]
I noticed the cordova cli itself does not run either with node v5 by default. I haven't dug further to see what is going on, there could be a mismatched dependency somewhere.

**Comment by mhartington** [comment]
This is known. Please down grade to node 4.2x

**Comment by andreialecu** [comment]
Related: https://issues.apache.org/jira/browse/CB-9935

**Comment by jettdigital** [comment]
https://issues.apache.org/jira/browse/CB-9935
