### ISSUE TITLE
BUG: MX4 could not simple editing of image before selection

### ISSUE THREAD

**Issue by floraluo** [driftyco/ionic#4738]
Type: bug

Platform: MX4 android 5.0.1 Flyme OS 4.5.7A
when I use the plugin of camera, I test it on emulator is well ,but on my MX4 , if I provide `allowEdit:true` parameter, I could't edite the selected photo  and show the loading view all thie time

```
var options = {
	quality: 50,
	destinationType: Camera.DestinationType.FILE_URI, 
	sourceType: Camera.PictureSourceType.CAMERA, //相机拍照
	allowEdit: true,
	encodingType: Camera.EncodingType.JPEG,
	targetHeight: 320,
	targetWidth: 320,
};
if(index == 1){
	options.sourceType = Camera.PictureSourceType.PHOTOLIBRARY //从图库选择
}else if(index == 2){
	options.sourceType = Camera.PictureSourceType.SAVEDPHOTOALBUM //从图库选择
}
$cordovaCamera.getPicture(options)
.then(function(imageURI){
	// console.log(imageURI);
	$scope.myPortrait = imageURI;
}, function(err){
	console.log(err);
});
```

**Comment by Ionitron** [comment]
Greetings @floraluo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4738). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4738)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hi, thanks for the report. This looks like an issue for cordova camera plugin: https://issues.apache.org/jira/browse/CB-8454?jql=project%20%3D%20CB%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20resolution%20%3D%20Unresolved%20AND%20component%20%3D%20%22Plugin%20Camera%22%20ORDER%20BY%20priority%20DESC%2C%20summary%20ASC%2C%20updatedDate%20DESC
