### ISSUE TITLE
bug: Video Controls not working with Internet  Explorer

### ISSUE THREAD

**Issue by sujithma** [driftyco/ionic#4742]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>The html5 video controls not working in IE. Ionic bundle.js making this problem.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @sujithma!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4742). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4742)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Do you have a sample? Also what version of Ionic are you using? This might have been addressed recently

**Comment by mlynch** [comment]
Fixed in master and 1.2

**Comment by sujithma** [comment]
Sorry still the problem found.
When using Internet Explorer to serve my ionic project, the controls in Videosuch as fullscreen ,pause etc not working

**Comment by sujithma** [comment]
My index page.

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title></title>

    <link href="lib/ionic/css/ionic.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

    

    
    <script src="lib/ionic/js/ionic.bundle.js"></script>

    
    <script src="cordova.js"></script>

    
    <script src="js/app.js"></script>
  </head>
  <body ng-app="starter">

    <ion-pane>
      <ion-header-bar class="bar-stable">
        <h1 class="title">Ionic Blank Starter</h1>
      </ion-header-bar>
      <ion-content>
          <video width="530px" height="350px;" controls="controls" preload="metadata" autoplay="autoplay" webkit-playsinline="webkit-playsinline"><source src="img\intro.mp4" type="video/mp4"/></video>
      </ion-content>
    </ion-pane>
  </body>
</html>

**Comment by sujithma** [comment]
Thank you..
How can i upgrade to 1.2

**Comment by m59peacemaker** [comment]
I upgraded to 1.2.4, but had to add `data-tap-disabled="true"` to the div surrounding the video to get the controls to work in IE. In case it helps anyone, I conditionally added the attribute. `ng-attr-data-tap-disabled="{{isBrowser}}"`

**Comment by lakshmig** [comment]
Hi,
DId you find a solution for this, I am using ionic 1.7.14 and i am facing the same issue,

**Comment by m59peacemaker** [comment]
@lakshmig I posted my solution above ^
