### ISSUE TITLE
bug: Issue nesting controllers (ui freezes)

### ISSUE THREAD

**Issue by hansgill** [driftyco/ionic#4744]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have 3 controllers activitiesCtrl, ActivityCtrl and ActivityCommentCtrl

When my app starts it does so in the ActivitiesCtrl. This controllers gets a list of categories and iterates through them displaying categories and tying them to ActivityCtrl as so 

```html
<ion-view view-title="Activities" class="activities-page">
  <ion-content scroll="true">
    <ion-item ng-repeat="category in categories" style="padding:0px;" ng-controller="ActivityCtrl" ng-model="category">
      <div ng-include="activityTemplate">
    </ion-item>
  </ion-content>
</ion-view>
```

The activityTemplate then allows someone to comment on an activity by opening a modal as shown here.

```html
<div class="tab-item" ng-controller="ActivityCommentCtrl" ng-click="openModal()" ng-model="category">
  <i class="icon ion-chatbox"></i>
      Comment
  </div>
```

The ActivityCommentCtrl loads the following template and this is where things get weird

```html
<ion-modal-view ng-controller="ActivityCommentCtrl" ng-model="category">
  <ion-header-bar align-title="left">
    <div class="buttons">
      <button class="button button-clear button-negative" ng-click="closeModal()">Cancel</button>
    </div>
  </ion-header-bar>
  <ion-content>
    {{category.title}}
  </ion-content>
</ion-modal-view>
```

**If I remove the ng-controller attribute above then closeModal() is never called and I get the warning commonly reported**

_'webkitMovementX' is deprecated. Please use 'movementX' instead._

**if I leave the ng-controller attribute in there, then my app is unable to load completely and my CPU usage just stays at 100%.** This happens both on safari and chrome so doesn't seem to be an issue with the browser.

I fairly new to angular (from backbone) so maybe there is something I am not setting up right in-terms of the angular app?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @hansgill!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4744). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4744)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by hansgill** [comment]
This was a non issue. I was testing old code which somehow wasn't getting updated in my build process. So sorry.
