### ISSUE TITLE
Slidebox with scroll inside is too sensitive

### ISSUE THREAD

**Issue by ghostgrass** [driftyco/ionic#4747]
there is a slidebox with scroll content in each slide. then the slidebox is too sensitive on device (OK in browser), sometimes i actually want to scroll the content but missed to change the slide pages.
it seems sometimes when i put my finger, for the first pixel, the delta.x = delta.y = 0, then the touch move takes it as change slide pages.
this could be fixed by add following code (unsure about the impact)
if (delta.x == 0 && delta.y == 0) {
                            return;
                        }
in touchmove: function (event) after 
delta = {
                            x: touches.pageX - start.x,
                            y: touches.pageY - start.y
                        };

**Comment by Ionitron** [comment]
Greetings @ghostgrass!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4747). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4747)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Can you try the new slidebox?

```html
<ion-slides>
  <ion-slide-page>
    <ion-content>
```

Shoudl fix it for you
