### ISSUE TITLE
ionic login design

### ISSUE THREAD

**Issue by spandey301219** [driftyco/ionic#4750]
can anyone help regarding login page in ionic ,i have done but facing too much issue to keep it good

**Comment by Ionitron** [comment]
Greetings @spandey301219!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4750). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4750)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hi, this is a question for the forum: https://forum.ionicframework.com/
