### ISSUE TITLE
bug: SocketException: Connection reset

### ISSUE THREAD

**Issue by julmot** [driftyco/ionic#4751]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>After running `ionic build android` I get the following error:
![ionic-err](https://cloud.githubusercontent.com/assets/8310677/11719454/2f87e932-9f5b-11e5-8447-95eebf1823bc.png)
Unfortunately I am not able to solve the issue without some instructions. Is anyone familar with such an issue?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @julmot!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4751). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4751)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Mind posting here? https://github.com/driftyco/ionic-cli

**Comment by julmot** [comment]
https://github.com/driftyco/ionic-cli/issues/695
