### ISSUE TITLE
feat: Ionicons 3.0

### ISSUE THREAD

**Issue by douglaszaltron** [driftyco/ionic#4755]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I saw that ionic 3.0.0 was out and tried using it with the latest ionic and discovered that ionic 1.2 is only bundled with ionicons 2.0.1.

You have any directive to use ionicons v3 in ionic v1.2?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @douglaszaltron!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4755). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4755)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Not sure yet, will update everyone once we have a plan for that.
