### ISSUE TITLE
feat: on mobile browser the address bar does not hide

### ISSUE THREAD

**Issue by awebdeveloper** [driftyco/ionic#4756]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>On mobile browser the address bar does not hide. This is coz ionic fills up the available space and the way these browsers work is if u scroll down it will hide the address bar</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
I don't think there's much we can do to avoid this. An Ionic app looks and feels like an app, and takes up the available viewport space. 

Unless I'm wrong and there's an alternative here?

**Comment by mlynch** [comment]
Reopening because I think this is something we could do on mobile web

**Comment by awebdeveloper** [comment]
Good. When do you think someone will be able to look into this

**Comment by denyo** [comment]
It is possible to achieve this but it is going to get ugly when navigating between parent/child views which slide in from the side.

To achieve this the positioning model (`position: block; top: 0; left: 0; right 0; bottom: 0;`) needs to go away so that the content is naturally scrolled on the body node. The nav bar would be `position: fixed; top: 0; left: 0; right:0; height: 44px;` and the main content would be `padding: 44px 0 0;`. So far so good. 

The trouble starts when you switch between views. This is due to their different heights. To better understand this, imagine you have a long list of items and a details page which live in two separate views. Now you scroll down the list of items a bit and the height of your mobile browser increases because the address bar and/or navigation buttons disappear. Next you click one of the list items and transition into the details page which is right next to the list. What has to happen here besides the transition is the body (with natural scrolling) needs to jump back to the top so that you see the beginning details page as expected. Afterwards the height of the body needs to be adjusted to fit the actual content so that scrollbars work correctly. Now you are at the very top now and most likely you got your address bar back.

**Comment by derwu** [comment]
If anyone is solved?

**Comment by awebdeveloper** [comment]
@denyo  i don't get what u say

**Comment by denyo** [comment]
You could also try this library although it requires you to swipe that initial overlay/modal to go into fullscreen: https://github.com/gajus/brim

**Comment by jiazhengshi** [comment]
Any update on this feature request?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#22
