### ISSUE TITLE
v1.2.0, $ionicScrollDelegate.$getByHandle(delegateHandle).getScrollView(): __publish is not a function

### ISSUE THREAD

**Issue by moore-mo** [driftyco/ionic#4757]
Type: bug

Platform: all
In v1.2.0,Why  __publish is not a function for $ionicScrollDelegate.$getByHandle(delegateHandle).getScrollView()

**Comment by Ionitron** [comment]
Greetings @moore-mo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4757). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4757)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
`__publish` is a low level function in the JS scroll view, and is not needed for native scrolling. We cannot recommend relying on internal APIs like this.

**Comment by moore-mo** [comment]
ok, ths!
