### ISSUE TITLE
change tab shown or not

### ISSUE THREAD

**Issue by Mint-Zhao-Chiu** [driftyco/ionic#4759]
i am using v1.2, has a new feature. 
https://github.com/driftyco/ionic/commit/7dd620da8f8335bc340e8e49eda32b72856b7741

but first ui is cached, so  call showBar(true) did not work...how can i use it?

**Comment by Ionitron** [comment]
Greetings @Mint-Zhao-Chiu!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4759). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4759)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
```javascript
controller('MyCtrl', function($scope) {
  $scope.$on('$ionicView.enter', function() {
     // Do it here
   });
});
```
