### ISSUE TITLE
bug: When adding Windows as a platform, android icons are added

### ISSUE THREAD

**Issue by mavenius** [driftyco/ionic#4762]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>When I start a fresh app and add Windows as a platform, android icons are downloaded:

S:\Dev\Ionic\WindowsSample1>ionic platform add windows
Updated the hooks directory to have execute permissions
Downloading Default Ionic Resources
Downloading: https://github.com/driftyco/ionic-default-resources/archive/master.zip
[=============================]  100%  0.0s
Done adding default Ionic resources
Adding icons for platform: android
Adding windows project...
Running command: cmd "/s /c "C:\Users\marka\.cordova\lib\npm_cache\cordova-windows\4.1.0\package\bin\create.bat S:\Dev\Ionic\WindowsSample1\platforms\windows com.ionicframework.windowssample1986598 WindowsSample1""
Creating Cordova Windows Project:
        App Name  : WindowsSample1
        Namespace : com.ionicframework.windowssample1986598
        Path      : S:\Dev\Ionic\WindowsSample1\platforms\windows
Copying template to S:\Dev\Ionic\WindowsSample1\platforms\windows
Running command: "C:\Program Files\nodejs\node.exe" S:\Dev\Ionic\WindowsSample1\hooks\after_prepare\010_add_platform_class.js S:\Dev\Ionic\WindowsSample1
add to body class: platform-windows
Installing "cordova-plugin-console" for windows
Installing "cordova-plugin-device" for windows
Installing "cordova-plugin-splashscreen" for windows
Installing "cordova-plugin-statusbar" for windows
Installing "cordova-plugin-whitelist" for windows

This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Installing "ionic-plugin-keyboard" for windows
Saving platform to package.json file

S:\Dev\Ionic\WindowsSample1></span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mavenius!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4762). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4762)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mavenius** [comment]
I chose desktop somewhat arbitrarily, because Windows isn't available as a platform in the custom issue form.

**Comment by jgw96** [comment]
Thanks for submitting this issue! As this issue is more related to the ionic cli i will be moving this issue there. Please feel free to continue the conversation there!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#843
