### ISSUE TITLE
feat: Full support for HAML instead of HTML as an option

### ISSUE THREAD

**Issue by jonmarinello** [driftyco/ionic#4763]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>As an Ionic developer I would prefer to use HAML instead of HTML. Its a very popular replacement for HTML that is MUCH more readable and maintainable.

1. It should be an option that can be configured once and remembered (so those who prefer HTML  will be unaffected and those who what to use HAML don't have to keep asking for it via a CLI flag).
2. The HAML processor would convert and .haml source files and generate the associated .html file as part of the build and emulate flow via the CLI.

I would really appreciate getting this on the product roadmap ASAP. Originally, I posted this ask on the blog here: https://forum.ionicframework.com/t/are-there-any-plans-to-directly-integrate-haml-into-ionic/38800. I was asked to post a github issue. I searched the issue list to make sure this wasn't going to be a duplicate.

Please respond with any questions or comments you have.

Appreciate your consideration.

Thanks!

jon</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jonmarinello!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4763). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4763)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
This would be something that a dev would setup on their own. Currently we do not have any plans of adding a build option for HAML. If this is something you would want for your projects, then you can add that.
