### ISSUE TITLE
bug: v1.2: Clicking on page title doesn't scroll to top

### ISSUE THREAD

**Issue by orthodoc** [driftyco/ionic#4765]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a list using pull to refresh. Clicking on the title in the header used to scroll the page back to the top.The upgrade to 1.2 seems to make tapping on the title ineffective. Native scrolling works great on android, though! Is it a regression or am I missing something?

Changing collection-repeat to ng-repeat seems to have no effect on this.</span>

*Edit: Used `$ionicScrollDelegate.scrollTop();` to fix the issue!*

<span is-issue-template></span>

**Comment by khagesh** [comment]
It is not a bug as per ionic, this was done to close https://github.com/driftyco/ionic/pull/4466.
I also feel it should be a bug and this feature should not be removed. We also have 5-6 screens where we are using this feature and now we will have to attach click handlers and use `$ionicScrollDelegate` which feels ugly.

**Comment by mlynch** [comment]
We removed this because you don't tap the title in an native iOS app, you tap the statusbar to scroll. We can't get that event in the browser, but we can get it natively with the statusbar plugin which makes sense.

I recommend using an alternative UI approach, because our approach was already non-standard.
