### ISSUE TITLE
bug: Ionic 1.2 - has-bouncing broken in 1.2

### ISSUE THREAD

**Issue by Shinzah** [driftyco/ionic#4775]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi, since i've upgrade to ionic 1.2, 95% of my content having has-bouncing="true" are broken.
I cannot, for the moment, determine why some of them work, and why others failed.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Shinzah!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4775). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4775)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Shinzah** [comment]
Maybe i've found the issue.
When an ion-content have a ion-list > ion-item with a collection-repeat, bouncing work.
But when i use a simple ng-repeat, bouncing doesn't work.

**Comment by mlynch** [comment]
I'm closing as wontfix for now, because this is just life with the native scroll area. To gain performance, we sacrifice a bit of control. However, bouncing is not a native Android design pattern, so by not using it you're making your apps more Android-like, which is a good thing.

**Comment by Manduro** [comment]
@mlynch It seems that setting `has-bouncing=false` on iOS does not work either. I'd think this would be possible to implement even with native scrolling. Or is this a wontfix too as per iOS design guidelines? It would be useful in some non-standard scroll area's.
