### ISSUE TITLE
docs: Android Marshmallow 6.0 push icon (ionic resources

### ISSUE THREAD

**Issue by adyz** [driftyco/ionic#4776]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Any thoughts on android 6.0? From the `ionic resources` perspective.

Now it requires us to use the transparent image that will create some kind of mask for push notifications icon at least.

This is fine, but on Android I need a background to the home icon, and this tool will generate all icons based on one file. If I remove the background it's all good except on the home screen where the icon will be mixed with the phone background.

Any ideas on how to handle this use case? Where will android 6.0 search for the icon of the push notification?

![screen shot 2015-12-14 at 1 43 28 pm](https://cloud.githubusercontent.com/assets/611174/11781366/122ea640-a272-11e5-90cb-01eb22e791d6.png)
![screen shot 2015-12-14 at 12 18 35 pm](https://cloud.githubusercontent.com/assets/611174/11781367/12338804-a272-11e5-972c-31fffcca841b.png)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @adyz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4776). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4776)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hey @adyz, this is a good question for the forum or for the CLI. Mind posting on one/both of those? https://github.com/driftyco/ionic-cli

**Comment by adyz** [comment]
Ouch, thanks @mlynch 
I've added this here: https://github.com/driftyco/ionic-cli/issues/608

Thanks for your answer.
