### ISSUE TITLE
bug: Ionic 1.1/1.2 not work myScrollHandleInModalView.scrollTo()

### ISSUE THREAD

**Issue by sergeifedorenko** [driftyco/ionic#4777]
function myCall(){
  myScrollHandleInModalView = $ionicScrollDelegate.$getByHandle('my-hor-scrollin-in-modal-view');
  myScrollHandleInModalView.scrollTo(200, 0);
}
this code called from modal view
Scroll not working and does nothing

![image](https://cloud.githubusercontent.com/assets/5947223/11781325/09a9cae2-a27a-11e5-9d21-aba91b4e18f2.png)

Problem by my opinion in this line (ionic.bundle.js:57334)
$ionicHistory.isActiveScope($scope) return false 

see stack:
(anonymous function) (ionic.bundle.js:57334)
(anonymous function) (ionic.bundle.js:103)
caller (ionic.bundle.js:102)
myCall (new-post.js:446)

My instance exist see this screen ((anonymous function) (ionic.bundle.js:103))
![image](https://cloud.githubusercontent.com/assets/5947223/11781461/23878b92-a27b-11e5-9a3a-0b7dd4ea2797.png)

**Comment by Ionitron** [comment]
Greetings @sergeifedorenko!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4777). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4777)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by sergeifedorenko** [comment]
I don't understand ))) problem disappears
