### ISSUE TITLE
bug: Using ng-switch directive with ion-label is not firing the focus event on a input field.

### ISSUE THREAD

**Issue by ricardovigatti** [driftyco/ionic#4778]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Basically, the problem is that the input field is not receiving the focus when we click on a ```<ion-label>``` or ```<span class="input-label">```. That's my code:

```html
<ion-input class="item item-input" ng-switch="platform">
    <ion-label>User</ion-label>
    <input ng-switch-when="android" type="tel" name="user" />
    <input ng-switch-default type="text" name="user" />
</ion-input>
```

If i remove the ng-switch directive and let only one input field, the focus event works normally after clicking the label.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ricardovigatti!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4778). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4778)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ricardovigatti** [comment]
I think the problem is related to ```<ion-input>´´´ directive, cause it's working when i use Labels. The code above works:

```html
<label class="item item-input" ng-switch="platform">
    <ion-label>User</ion-label>

    <!--- this also works --->
    <!-- <span class="input-label">User</span> -->

    <input ng-switch-when="android" type="tel" name="user" />
    <input ng-switch-default type="text" name="user" />
</label>
```
