### ISSUE TITLE
bug: expose-aside-when cannot be applied only to one side menu

### ISSUE THREAD

**Issue by ps1dr3x** [driftyco/ionic#4779]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>With this sample code:

``` html
<ion-side-menus>
  <!-- Left menu -->
  <ion-side-menu side="left" expose-aside-when="large">
  </ion-side-menu>

  <ion-side-menu-content>
  <!-- Main content, usually <ion-nav-view> -->
  </ion-side-menu-content>

  <!-- Right menu -->
  <ion-side-menu side="right">
  </ion-side-menu>

</ion-side-menus>
```

Both menus are exposed, not only the left side menu

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ps1dr3x!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4779). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4779)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
What version of Ionic? There was a possible fix for this in 1.2 last week

**Comment by ps1dr3x** [comment]
I already upgraded to 1.2 this morning

**Comment by doorty** [comment]
+1 mlynch, the current ionic solution is to open both menus when they should be configurable independently

**Comment by ishgoel** [comment]
I am facing the same issue. expose-aside-when exposes both the menus. There should be a separate expose-aside-menu for left & right menus. Any possible fix?

**Comment by theromis** [comment]
Facing same issue on 1.2.4 any updates on this bug?

**Comment by farous** [comment]
+1

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#24
