### ISSUE TITLE
bug: ng-click in a button in ion-nav-buttons fired twice on Win10

### ISSUE THREAD

**Issue by ibewugb** [driftyco/ionic#4780]
<span ionic-description>**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi, in my windows 10 version of my apps, the ng-click event on a button in ion-nav-buttons is fired twice.
This happens with Ionic 1.3 on windows 10 (IE11)</span>

**Comment by Ionitron** [comment]
Greetings @ibewugb!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4780). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4780)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ricardovigatti** [comment]
I had this issue working with wp8 platform.

**Comment by wlw362034710** [comment]
+1

**Comment by maksad** [comment]
@ibewugb try to add `type="button"` to the button element. As @cverb pointed [in this SO issue](http://stackoverflow.com/questions/32090543/scopes-method-called-via-ng-click-executed-twice-by-ie)  the default behaviour is submit and apparently that messes with the code.

**Comment by jgw96** [comment]
Hello all! Although i would love to help solve this issue we are not currently supporting windows 10 with Ionic 1, although we do fully support windows 10 with Ionic 2. Also, we do not support windows phone 8 or Internet Explorer with either Ionic 1 or Ionic 2 although we fully support Edge with Ionic 2. Thanks for using Ionic!
