### ISSUE TITLE
bug: [1.2.0] back animation, back view is still

### ISSUE THREAD

**Issue by jrencz** [driftyco/ionic#4782]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I'm testing `1.2.0-nightly-1823`

On `1.1.1` when back button is hit then the active view slides away to the right until it goes off the viewport entirely and in the meantime the back view slides in from left with a fraction of the speed current view goes away - a parallax effect can be seen.

On `1.2.0` the back view is still - it's on its final position right from the beginning of the back transition.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jrencz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4782). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4782)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Thanks, can repro w/ overflow scrolling. Will fix for 1.2.1

**Comment by jrencz** [comment]
I applied this commit onto my copy but it didn't help.
I'll try to provide a screencast later
