### ISSUE TITLE
Question: Can ionic serve rerun gulp task when file changes?

### ISSUE THREAD

**Issue by royipr** [driftyco/ionic#4783]
Hi all.

Im very new to ionic, and I was trying to ask this question in few place but didn't get any answer, nor positive nor negative..

Is it possible that when running ionic serve, and then if some files were changed it will rerun gulp task that was specified as the `gulpStartupTasks` in the ionic project file?

**Comment by Ionitron** [comment]
Greetings @royipr!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4783). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4783)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hey, this is a better question for the forum: https://forum.ionicframework.com/

**Comment by ignaciochiazzo** [comment]
I want to know the same Issue
