### ISSUE TITLE
Permission issue when ran on OSX El Capitan

### ISSUE THREAD

**Issue by omefire** [driftyco/ionic#4784]
When I run ```ionic run ios --device```, I get the below error:

$ ionic run ios --device 

Running command:  /Users/omefire/Projects/MyApp/hooks/after_prepare/010_add_platform_class.js /Users/omefire/Projects/Projects/MyApp ERROR running one or more of the platforms: Error: spawn EACCES You may not have the required environment or OS to run this project

**Comment by Ionitron** [comment]
Greetings @omefire!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4784). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4784)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
This is a CLI issue, but the docs have some info about this permissions error (last one on here): http://ionicframework.com/docs/ionic-cli-faq/#hool=ks

**Comment by omefire** [comment]
To get around the issue temporarily, I granted permissions to this file to everyone:
```sudo chmod 777 /Users/omefire/Projects/MyApp/hooks/after_prepare/010_add_platform_class.js```
