### ISSUE TITLE
boilerplate recommendations?

### ISSUE THREAD

**Issue by varmint09** [driftyco/ionic#4786]
Hello,

Most of the ionic boilerplates I could find are a year or so old, is there a popular one that is more active that might be worth considering before I start using Ionic?

Many thanks

**Comment by Ionitron** [comment]
Greetings @varmint09!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4786). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4786)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hey @varmint09, try the market: http://market.ionic.io/

We keep all our starters up to date, though they are getting an update in v2.
