### ISSUE TITLE
Select has strange formatting

### ISSUE THREAD

**Issue by FrancescoMussi** [driftyco/ionic#4788]
Hello guys!
The normal select cut the exceeding part of text from the label.

To resolve this there can be two possible solutions:
- applying item-text-wrap class
- add custom style, for like white-space: normal!important;

In this way the text is not cut off anymore. 

BUT by doing this the select take a strange formatting. 
The label has now a max-width of 200px; 
Even by removing this property, the label still it has no more than 40% of the space available horizontally. 

Why is that?
How can i avoid cut of part of the text from the label but without distorting the formatting of the select?

Thank you!

**Comment by Ionitron** [comment]
Greetings @FrancescoMussi!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4788). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4788)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
@FrancescoMussi what browser/device?

**Comment by schirrmacher** [comment]
![screen shot 2016-02-11 at 19 09 46](https://cloud.githubusercontent.com/assets/6545822/12985467/17d827ec-d0f3-11e5-9ea1-b8e9bf940b34.png)

I have also problems with formatting of the ion-select directive. I'm using Chrome Version 48.0.2564.97 (64-bit) on Mac.

My code looks like this:
`<ion-content>

    <ion-card>

        <ion-item>
            <ion-label>Music</ion-label>
            <ion-select [(ngModel)]="articleSizeOptions" [alertOptions]="articleSizeOptions">
                <ion-option>Alice in Chains</ion-option>
                <ion-option>Green Day</ion-option>
                <ion-option>Nirvana</ion-option>
                <ion-option>Pearl Jam</ion-option>
                <ion-option>Smashing Pumpkins</ion-option>
                <ion-option>Soundgarden</ion-option>
                <ion-option (select)="stpSelect()">Stone Temple Pilots</ion-option>
            </ion-select>
        </ion-item>

    </ion-card>

</ion-content>`

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!
