### ISSUE TITLE
bug: bug: http://learn.ionicframework.com/formulas/localstorage/

### ISSUE THREAD

**Issue by cwsarahhsu** [driftyco/ionic#4791]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Getting error that I didn't get before: 

SyntaxError: Unexpected token o
    at Object.parse (native)
    at Object.getObject (http://localhost:8100/js/services.js:15:19)</span>

<span is-issue-template></span>
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @cwsarahhsu!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4791). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4791)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
This is a docs issue, though sounds like there might be an issue in your code.
