### ISSUE TITLE
docs: Change Cordova Keyboard plugin KeyboardAccessoryBar label

### ISSUE THREAD

**Issue by jvcjunior** [driftyco/ionic#4796]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi, I would like to know if someone knows how to change the label 'Done' of the HIDEKeyboardAccessoryBar. I would like to customize according to phone's language. </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jvcjunior!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4796). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4796)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Tracking here: https://github.com/driftyco/ionic-plugin-keyboard/issues/54
