### ISSUE TITLE
bug: ionSlideBox does-continue="true" ignored after handle.update()

### ISSUE THREAD

**Issue by konsultaner** [driftyco/ionic#4800]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When using ionSlide with ng-repeat and loaded models, the update is necessary to be called on the handle. For some reason the `does-continue="true"` is ignored after loading and updating the view.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @konsultaner!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4800). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4800)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Are you using the `<ion-slide-box>` component?

**Comment by konsultaner** [comment]
yes slide box. I corrected my issue title

**Comment by mlynch** [comment]
Thanks. We are removing that component in the future, can you try the new slidebox:

```html
<ion-slides>
  <ion-slide-page>
```

**Comment by konsultaner** [comment]
can i use it somehow with ionic 1.1.0?

**Comment by mlynch** [comment]
You're welcome to pull the new code down but I'd recommend trying 1.2 first to see how it works.

**Comment by konsultaner** [comment]
I updated to 1.2.1 and it still does not work

**Comment by jgw96** [comment]
@konsultaner Hello! Are you still having this issue with the latest version of ionic? (1.2.4)

**Comment by konsultaner** [comment]
yes

**Comment by danbucholtz** [comment]
Hi @konsultaner,

We've deprecated the ion-slide-box component so we won't be making any changes to it going forward.  I'm sorry you're still having troubles with that.  Can you give ion-slides a shot for your use case and let us know how it goes?

In the meantime, I'm going to close this issue.  I'll re-open if you're still having some issues with ion-slides.

Thanks for contributing to Ionic!

Thanks,
Dan
