### ISSUE TITLE
bug: [WP8.1] Module 'ngLocale' is not available!

### ISSUE THREAD

**Issue by PerfectionCSGO** [driftyco/ionic#4805]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>It isn't breaking the application, it just throws an error in the log. I didn't see this being posted anywhere and I don't use this either... I think.

This happens on a Windows Phone with Ionic 1.1.0, 1.1.1 and 1.2.0.

Exception was thrown at line 15116, column 11 in ms-appx://hop.test1/www/scripts/ionic.bundle.js
0x800a139e - JavaScript runtime error: [$injector:nomod] Module 'ngLocale' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.3/$injector/nomod?p0=ngLocale</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @PerfectionCSGO!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4805). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4805)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by szuzul** [comment]
Try to add plugin winstore-jscompat without that I wasn't able to start app in emulator because of this error. https://github.com/vjrantal/cordova-plugin-winstore-jscompat

**Comment by PerfectionCSGO** [comment]
The platformOverrides.js includes winstore-jscompat.js on windows but that doesn't solve the issue.

**Comment by szuzul** [comment]
I would said its a workaround rather than solution of that issue.

**Comment by mlynch** [comment]
Take a look at this: http://www.johnpapa.net/easy-fix-to-a-common-angular-module-error/

Guessing this is user code related. Closing for now

**Comment by PerfectionCSGO** [comment]
Sorry for wasting your time. I actually saw that page before I posted here but now I went through the comments and figured it out.  For the sake of developing in a team we include our controllers and services separately like so:

    
    <script src="js/controllers/LoginController.js"></script>
    <script src="js/controllers/AppController.js"></script>
    <script src="js/controllers/DashboardController.js"></script>
    <script src="js/controllers/PhotoController.js"></script>
    <script src="js/controllers/AdministrationController.js"></script>
    <script src="js/controllers/MutationController.js"></script>
    
    <script src="js/services/administrationService.js"></script>
    <script src="js/services/fileService.js"></script>
    <script src="js/services/logService.js"></script>

However while I was upgrading to 1.2.0 we removed a service that's no longer needed/redundant and forgot to to remove the <script>. Apparently that was causing that message... which is really strange. It is solved.

**Comment by DaniloCouto** [comment]
There is a possibility that this error only fires on Windows platform?
Because in my project on Android, iOS and browser doesn’t fire any errors.
When I'm trying to execute my project on Windows platform, it fires the exact same error.

`Exception was thrown at line 15270, column 11 in ms-appx://br.com.fulltime.fullcontrol.mobile/www/lib/ionic/js/ionic.bundle.js
0x800a139e - JavaScript runtime error: [$injector:nomod] Module 'ngLocale' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.3/$injector/nomod?p0=ngLocale`

Yes, I’m already imported the winstore-jscompat.js , seems that is a must on angular projects on Windows Platform
