### ISSUE TITLE
bug: Native Scrolling in combination with ion-pane and ion-scroll (Ionic 1.2)

### ISSUE THREAD

**Issue by 5uper** [driftyco/ionic#4806]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Native Scrolling is not working when i'm trying to do a ion-scroll into a ion-pane like this:

```html
<ion-pane>
      <ion-scroll>
      </ion-scroll>
</ion-pane>
```

i want to do something like this, but with native scrolling
http://play.ionic.io/app/cf19ffe3f4b2</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @5uper!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4806). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4806)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
I need more info. What exactly is the issue? I tried that demo and it worked fine for me.

**Comment by 5uper** [comment]
sorry my english is weak :(

in the demo I have disabled native scrolling and it works fine
```html
...
<ion-scroll overflow-scroll="false">
...
</ion-scroll>
...
```
but if the native scrolling is enabled, this does not scroll

here a demo with enabled native scrolling
http://play.ionic.io/app/8e67e6cc0e49

maybe you can now recognize the problem better?

**Comment by mlynch** [comment]
There's nothing to scroll. Are you talking about the bouncing?

**Comment by 5uper** [comment]
yes the bouncing up and down did not work anymore.

**Comment by mlynch** [comment]
That's one of the side effects of using native scrolling. Performance/control trade off. It'll bounce just fine if the content overflows the viewport, so just add more content and you'll see that.

**Comment by 5uper** [comment]
I tried it with more content, still does not work :(
http://play.ionic.io/app/8e67e6cc0e49

**Comment by mlynch** [comment]
Set a fixed height on ion-scroll: http://play.ionic.io/app/691639ef2c2f

**Comment by 5uper** [comment]
ok thx :+1:

**Comment by katche70** [comment]
I think it's a step in the wrong direction.
Say you have a list with only 3-4 items, with native scrolling enabled you didn't have any bouncing effect.  Without bouncing it appears ponderous and like a hybrid app (on iOS) 


Is there a simple workaround except disable native scrolling?
