### ISSUE TITLE
feat: Custom Tab template

### ISSUE THREAD

**Issue by Grafikart** [driftyco/ionic#4811]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Before doing any PR I would like to know if this could be interesting for the community.

## The problem

Sometimes we want to use something special for our tabs like `<img>` or `<svg>` for our tabs. The tab template is too rigdt to allow this kind of customisation.

## The solution 

Allow tab HTML template to be defined in the $ionicConfigProvider so we can inject the code we want to adapt to any situation. 

```
$ionicConfigProvider.tab.template = "<unicorns></unicorns>"
```

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Grafikart!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4811). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4811)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment]
@Grafikart Hello! I am not sure if i understand your proposal? Would you mind explaining a little more? Maybe with some code samples? Thanks!

**Comment by Grafikart** [comment]
I wanted to use tabs in my app without using ionic icons but my own SVG. To achieve that I had to edit ionic core (which is obviously not a nice way of doing things :)) 

Indeed the template is set in this file https://github.com/driftyco/ionic/blob/master/js/angular/directive/tabNav.js#L7 and I felt that it would be nice to be able to inject any template we want here.

For instance this is my code 

```
    '<a ng-class="{\'tab-item-active\': isTabActive(), \'has-badge\':badge, \'tab-hidden\':isHidden()}" ' +
      ' ng-disabled="disabled()" class="tab-item">' +
      '<span class="badge {{badgeStyle}}" ng-if="badge">{{badge}}</span>' +
      '<sprite name="{{ getIconOn() }}"></sprite>' +
      '<span class="tab-title" ng-bind-html="title"></span>' +
    '</a>',
```

Here I replaced the <icon> with a directive I created to use my SVG

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Because we do not plan on adding any new features to Ionic 1 at the moment I am going to close this issue for now. Thanks for using Ionic!
