### ISSUE TITLE
bug: button fire twice when ng-disabled reactivate

### ISSUE THREAD

**Issue by Intuitisoft** [driftyco/ionic#4813]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>environment: browser (Google Chrome / Safari)

configuration: button link `<a>` with ng-click and ng-disabled condition. 
`<a class="button" ng-click="ctrl.fct()" ng-disabled="mycondition">my button</a>`

condition: the button is enable and it is disable by ng-disabled just after the click. 

case : when the user click on the button and this button is disabled by the click (reset form) the click is fired two time.  

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Intuitisoft!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4813). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4813)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Intuitisoft** [comment]
a quickfix is to switch `<a>` with `<button>`
`<button class="button" ng-click="ctrl.fct()" ng-disabled="mycondition">my button</button>`

**Comment by jgw96** [comment]
Hello! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
