### ISSUE TITLE
$ionicBind needs better documentation.

### ISSUE THREAD

**Issue by stavinopolis** [driftyco/ionic#4816]
in trying make a swipe up directive that mimics refresher I encountered $ionicBind, but I can't for the life of me figure out what it's doing! Some more comments would make it a lot easier to take advantage of ionic's built in utilities in making my own components.

**Comment by Ionitron** [comment]
Greetings @stavinopolis!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4816). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4816)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
@stavinopolis thanks for the feedback. `$ionicBind` isn't really a user facing service. You are free to use it, though, but I can't guarantee it'll always be a stable API.

Basically, it mimic's Angular's isolate scope mechanics but without actually creating an isolated scope. You use it just like you would in the `scope: {}` of a directive. Take a look at some of the existing examples for reference.
