### ISSUE TITLE
Button back  show different

### ISSUE THREAD

**Issue by webinopoly** [driftyco/ionic#4818]
Hi  to day i find issue 
If i use this code in my state 
```
	.state('student.profile', {
			url: '/profile',
			authenticate: true,
			roles: ['student'],
			views: {
				'menuContent': {
					templateUrl: 'modules/students/profile/update/profile-update.html',
					controller: 'StudentProfileUpdateCtrl',
				}},
			resolve: {
				grades: function(gradeService) {
					return gradeService.getByCountry().then(function(data) {
					
						 return data;
					});
				}
			}
		})
```
I button back 
http://prntscr.com/9fjfer
But when i used code in my state  Without resolve

```
	.state('student.profile', {
			url: '/profile',
			authenticate: true,
			roles: ['student'],
			views: {
				'menuContent': {
					templateUrl: 'modules/students/profile/update/profile-update.html',
					controller: 'StudentProfileUpdateCtrl',
				}}
		})
```

And i but the code to controller StudentProfileUpdateCtrl
```
gradeService.getByCountry().then(function(data) {
					
						 $scope.grade = data;
					});
```
Result with button
http://prntscr.com/9fjg27

**Comment by Ionitron** [comment]
Greetings @webinopoly!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4818). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4818)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by nhoctanker** [comment]
+1

**Comment by nhoctanker** [comment]
Button back show when use resolve in my states, But i want button  ionic-nav-button

**Comment by jgw96** [comment]
Hello @nhoctanker although resolves currently kind of work with ionic 1, we are not fully officially supporting using resolves as they came out later in the ui-router development and have caused a,lot of issues with our navigation. I would recommend passing around your data using a service instead. Sorry for any inconvenience this causes, and thanks for using ionic!
