### ISSUE TITLE
bug: Slidebox zero width on Android with local images

### ISSUE THREAD

**Issue by sandymacpherson** [driftyco/ionic#4820]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a slidebox that contains a list of photographs that the app loads from the "data" directory. This directory is the one provided by the "file" plugin, in the variable cordova.file.dataDirectory. On iOS, this works without any problems at all, but on Android I have found some strange behaviour.

My slidebox markup is this:
```
<ion-slide-box>
  <ion-slide ng-repeat="photo in photos">
    <div class="text-center">
      <img ng-src="{{ photo }}" style="max-width: 100%; max-height: 100%"></img>
    </div>
  </ion-slide>
</ion-slide-box>
```

When running on an Android device (ionic run android), despite files being found, nothing appears in the view. Inspecting this with chrome://inspect shows the slidebox there and having width=0. The images are loaded and imply that the problem is with the slidebox itself.

If I use images taken directly from the internet rather than from local files, eg "http://server.com/image.jpg", then the slidebox works just fine as it is. If I replace the slidebox markup with an image list instead, as shown below, it also works fine and the local images load without a problem.

```
<ion-list>
  <ion-item ng-repeat="photo in photos">
    <div class="text-center">
      <img ng-src="{{ photo }}" style="max-width: 100%; max-height: 100%"></img>
    </div>
  </ion-item>
</ion-list>
```

Any idea what I'm doing wrong? Or is this a bug in the slidebox?

Thanks!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @sandymacpherson!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4820). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4820)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As slidebox is now depecrated i will be closing this issue. Thanks for using ionic!

**Comment by MoAsmar** [comment]
the solution is over here:

`setTimeout(function() {
                $ionicSlideBoxDelegate.slide(0);
                $ionicSlideBoxDelegate.update();
                $scope.$apply();
            });`

got it from this guy Raymon Camden, thanks a lot:
[](https://www.raymondcamden.com/2015/09/16/ionic-example-ion-slide-box/
)
