### ISSUE TITLE
bug: Scroll bar always show. How to hide it?

### ISSUE THREAD

**Issue by miftahafina** [driftyco/ionic#4822]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I just start my ioinc app, and then when I served, I saw a scrollbar. How to hide it but still scrollable?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @miftahafina!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4822). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4822)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by roonie007** [comment]
same problem here +1

**Comment by seasonstar** [comment]
same problem.
iOS 9.2, Ionic 1.2.1,

**Comment by Silvercast** [comment]
+1 . used to work with 1.1 by setting `scrollbar-x="false" scrollbar-y="false"` but now it's broken

**Comment by GnicT** [comment]
+1, same problem here. ionic 1.2.1

**Comment by Silvercast** [comment]
for me the scrollbar shows in iOS simulator

**Comment by miftahafina** [comment]
Solved after updated to the last version.
