### ISSUE TITLE
bug: ionic lib update ERROR

### ISSUE THREAD

**Issue by pinrostudio** [driftyco/ionic#4824]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Trying to update an existing project to latest 1.2.1. But running "ionic lib update" shows *Latest Version: 1.2.1 (released 2015-12-18)* but immediately it shows **Invalid version: 1.2.1**</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @pinrostudio!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4824). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4824)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ScottSpittle** [comment]
Same issue here. It's because there is no 1.2.1 release on git. Temporarily I've changed my bower job to point to a revision of 1.2.1 to get it to work.

**Comment by perrygovier** [comment]
Should be fixed. try now

**Comment by pinrostudio** [comment]
Works...thanks.
