### ISSUE TITLE
bug: Error at install time - `node postinstall`

### ISSUE THREAD

**Issue by tejasmanohar** [driftyco/ionic#4826]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm getting a blocking error at install time. Here's the full trace- https://gist.github.com/tejasmanohar/0ddc4c41b2272fe5b202. I'm guessing it's due to `node postinstall` instead of `npm run postinstall` somewhere... but again, that's just a guess.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @tejasmanohar!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4826). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4826)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tejasmanohar** [comment]
My guess about `npm run postinstall` was wrong. Just saw that `postinstall` is a script here- https://github.com/ForbesLindesay/spawn-sync/blob/master/postinstall.js. Looks like it more boils down to the path of it when it's being executed. Hmmm-- any ideas? :)

**Comment by richardsun29** [comment]
Did you accidentally change npm's install directory from `~/.npm` to `~/.nvm`?

**Comment by tejasmanohar** [comment]
@richardsun29 Didn't do anything accidentally as far as I know. `/Users/tejas/.nvm/versions/node/v5.0.0` is my NPM prefix for this node installation. [NVM](https://github.com/creationix/nvm), a very popular tool (so nothing out of ordinary as per installations), sets it up that way so that globally installed packages are managed on a version-to-version basis. i have many other globally installed CLIs working fine :)

**Comment by richardsun29** [comment]
Ah my bad :) Not sure why all the dependencies have a "no such file or directory" warning though. It could be trying to execute a file that doesn't exist

**Comment by tejasmanohar** [comment]
Yea, unsure as well :\

**Comment by tejasmanohar** [comment]
Worked after a re-install of Node. I don't know why but ok :)
