### ISSUE TITLE
Ion-slides ionic 1.2.1 loop autoplay bug. codepen provided

### ISSUE THREAD

**Issue by deliverymanager** [driftyco/ionic#4831]
https://forum.ionicframework.com/t/ion-slides-ionic-1-2-1-loop-bug-codepen-provided/39617

**Comment by Ionitron** [comment]
Greetings @deliverymanager!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4831). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4831)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment]
Hello! Is this still an issue with the latest version of ionic? Thanks!

**Comment by deliverymanager** [comment]
Yes the issue remains on the latest vesrion 1.3.1

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#27
