### ISSUE TITLE
apps.ionic.io removed user can still log in and see app

### ISSUE THREAD

**Issue by djangojack** [driftyco/ionic#4832]
As the owner of an app, I removed a collaborator, and the user was removed from the web interface showing the list of collaborators. However, this user could still log in and see the app, from which they were just removed.

**Comment by Ionitron** [comment]
Greetings @djangojack!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4832). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4832)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment]
Thanks for opening this issue! Since this issue is not related to the ionic framework i will be moving this issue. But please feel free to continue the conversation over there!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-platform-issues#47
