### ISSUE TITLE
bug: [WP8.1/Android 4.2] PTR non-functional with native scrolling

### ISSUE THREAD

**Issue by PerfectionCSGO** [driftyco/ionic#4834]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android 4.2, wp8.1</span>  

<span ionic-description>This problem is present in Ionic 1.2.1 on a Windows 8.1 Phone and android 4.2 

On android 4.2 it sort of works but messes up somewhat bad when used with ng-repeat.

iOS9.1 iPad: Works
Android 4.2 Tablet: semi-functional
Android 5.x.x Phone: Works
Windows 8.1 Phone: non-functional on Nokia Lumia 520.

My current workaround is to enable jScroll for windows phone and android 4.2, which has significant performance issues on ng-repeat lists. (Supposedly solved with collection-repeat which also breaks on windows phone)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @PerfectionCSGO!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4834). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4834)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by PerfectionCSGO** [comment]
My current workaround in my stateProvider

    /* Workaround: https://github.com/driftyco/ionic/issues/4834 */
    if (ionic.Platform.isWindowsPhone()) {
        $ionicConfigProvider.scrolling.jsScrolling(true);
    }

    if (ionic.Platform.isAndroid()) {
        if (ionic.Platform.version() === "4.2") {
            $ionicConfigProvider.scrolling.jsScrolling(true);
        }
    }
    /* End workaround */

**Comment by mlynch** [comment]
Should be fixed in a recent 1.2 release. Can you verify and let me know and I'll reopen if not? Thanks.
