### ISSUE TITLE
bug: slide-box rendered event

### ISSUE THREAD

**Issue by satore11** [driftyco/ionic#4836]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,
is there an event in 1.1.1 version which is fired when the slide-box directive is rendered?
I've seen solutions that use ng-init but this event is fired when the angular app is loaded, right?
Thanks a lot!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @satore11!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4836). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4836)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
