### ISSUE TITLE
bug: $ionicView.beforeEnter not broadcasted for initial abstract state

### ISSUE THREAD

**Issue by dibari** [driftyco/ionic#4838]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have a double nested abstract state (a view whose parent is an abstract state, which has a parent that is an abstract state) that, if initially loaded as the first state, will not fire an '$ionicView.beforeEnter' event.  Subsequent state changes will cause the beforeEvent event to fire, but not if it is the initial one.

Specifically, I'm using the ionic tabs template.  I noticed the issue because when the nested abstract state is used as the first page, the 'has-header' class is never added to ion-content.  Seems that the class is only ever added as a response to a beforeEnter event.

I'm not sure exactly where the issue lies, somewhere in beforeEnter() or a directive transition function not executing?

Here's a codepen illustrating the issue - http://codepen.io/anon/pen/pgbKRo
You'll notice on initial load, the first line of the child page is under the menu.  When navigating back to the page, the menu initializes properly.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @dibari!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4838). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4838)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by dibari** [comment]
Does anyone have any insight into this?

**Comment by danbucholtz** [comment]
Hi @dibari 

This should be resolved in the nightly build.  We did a lot of work with the life cycle events.  Can you test on the latest build?  Let me know if you need some help.

http://code.ionicframework.com/#nightly

I guess our staging site hasn't deployed in the past week or so, but we do have new and improved docs.
http://ionic-site-staging.herokuapp.com/docs/nightly/api/directive/ionView/

Basically, in addition to dispatching the event upwards (emit) from the correct scope, but we also now fire events downwards (broadcast) to work with ui-router nested views.

```
$scope.$on("$ionicParentView.enter", function(event, data){
   // woot, I received the event!
});

$scope.$on("$ionicView.enter", function(event, data){
   // woot, received the event
});
```

Please let me know if you have any issues and I'll re-open if needed.

Thanks,
Dan
