### ISSUE TITLE
bug: ion-scroll zoom stop working on 1.2.0 (and 1.2.1)

### ISSUE THREAD

**Issue by olebrun** [driftyco/ionic#4844]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,
zooming="true" stop working on 1.2.0.

Code from documentation http://ionicframework.com/docs/api/directive/ionScroll/ is working on 1.1.1, not on 1.2.x:

```
<ion-scroll zooming="true" direction="xy" style="width: 500px; height: 500px">
    <div style="width: 5000px; height: 5000px; background: url('https://upload.wikimedia.org/wikipedia/commons/a/ad/Europe_geological_map-en.jpg') repeat"></div>
</ion-scroll>
```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @olebrun!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4844). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4844)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by leschirmeur** [comment]
Try setting overflow-scroll="false" on the <ion-scroll> element as zooming requires JS scrolling and does not work with native scrolling (I think...).

**Comment by olebrun** [comment]
you're right, it's ok.
Thank you.

**Comment by jrencz** [comment]
Zooming might imply overflow-scroll="false"
Otherwise it does not make sense. The intention of someone who adds zooming="true" explicitly is to have zooming functionality. If it's blocked by native scrolling then it's not obvious what to do to really enable it.
In my case reading the code helped and then I found this issue (reading the code usually helps) but anyway - it's not obvious.

**Comment by vance** [comment]
So, I had to write my own entire zoom engine using CSS transforms. It is super janky. But, I cannot use javascript scrolling as it is not performant enough for my needs (many images). Please, can somebody at least say whether it is possible to zoom on native scroll in the future, or just not possible given the Native scrolling API?
