### ISSUE TITLE
bug: Invalid css output after running gulp sass

### ISSUE THREAD

**Issue by marekstabla** [driftyco/ionic#4847]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>So I'm using scss files from ionic lib to compile them using gulp-sass task with my project files.
The result is that compiled output for ionicons is invalid.

```
.ion-android-bulb:before {
  content: ""; }

.ion-android-bus:before {
  content: ""; }

.ion-android-calendar:before {
  content: ""; }

.ion-android-call:before {
  content: ""; }
```

I've also pulled newest ionic source files from github and running npm install, installing global gulp and then running gulp sass tasks ends up the same (creating invalid css file in dist folder).

Node 5.3
Gulp-sass 2.0.4 (2.1.1 works the same)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @marekstabla!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4847). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4847)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
