### ISSUE TITLE
bug: ionic refresher and scroll

### ISSUE THREAD

**Issue by cacordina** [driftyco/ionic#4850]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>With ionic 1.2.1 and Android 4.4.4 ( and also 4.4.2) , scrolling is not working if I have an ion-refresher in my view. The same app work well on Android 6.0.1</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @cacordina!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4850). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4850)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by cxcxcxcx** [comment]
same issue here, even xwalk doesn't help on 4.4.2

**Comment by ehynds** [comment]
+1. Works fine on Android 5.x as well.

**Comment by JrontEnd** [comment]
+1.scrolling is not working in android.

**Comment by mlynch** [comment]
Are you seeing any console logs/errors or anything?

**Comment by Emeryao** [comment]
+1

**Comment by cacordina** [comment]
I don't see any logs in console and like JrontEnd said, with two fingers it works

**Comment by ant0ha** [comment]
+1
@mlynch, I do not see any logs in the console... also, if i move finger up/down some times I can scroll but in another direction.
<img width="321" alt="authorization_and_showdashboard_html_-_boardio_mobile_-____documents_work_ionic_boardio_mobile_" src="https://cloud.githubusercontent.com/assets/787918/11975502/b5277d9a-a97f-11e5-8ab8-f415a9939f96.png">

Then i stop scrolling and now i can scroll if i try again. But if i scroll to top then scrolling is not working again.

**Comment by mlynch** [comment]
Will review and fix for 1.2.2

**Comment by zhenweiyu** [comment]
+1,in android 4.4. It works with two fingers

**Comment by FreezeSoul** [comment]
+1 same with crosswalk

**Comment by Corvi2** [comment]
I also can't get scrolling with dragged mouse to work with 1.2.1. it's not my project, because I also started a new, blank, project, with nothing in it than a huge wall of text inside index.html <ion-content> and i still am not able to scroll. 

I'm not talking about any specifiy device, but just the desktop browser using ionic serve.

it works fine again when i revert 1.2.1 changes in ionic.bundle.js.

**Comment by mlynch** [comment]
Hey everyone, in the meantime do `overflow-scroll="false"` on this container. Will have a fix hopefully tomorrow with the next release

**Comment by mlynch** [comment]
Okay, just fixed this. Let me know how it works for you!

**Comment by ant0ha** [comment]
Works good for me. Thank you!
