### ISSUE TITLE
bug: ion-header-bar no longer scrolls to top by default in 1.2.1

### ISSUE THREAD

**Issue by wbreza** [driftyco/ionic#4856]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Looking at the v1.2 ionHeaderBar directive it appears their is a new implementation that does not include the scroll to top feature.  Will this be added back or will a new directive specific to scrolling to top be introduced?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @wbreza!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4856). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4856)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
We removed this because the native statusbar plugin is now integrated with Ionic. However, I've received enough requests for this I might bring it back in 1.2.2

**Comment by wbreza** [comment]
Are you referring to the cordova status bar plugin as well as the ngCordova wrapper @ http://ngcordova.com/docs/plugins/statusbar/ ??

Looking at the ngCordova docs it doesn't appear that it supports a click/tap behavior.  Even if does, the native status bar is only ~20px and it would be nice to have a larger click target like we previously achieved in ionic 1.1 via the ion-header directive.

For the time being I've implemented my own scroll-to-top directive that can be decorated on any element to achieve the previous behavior.  Would this be something you guys would consider accepting back as a contribution?
