### ISSUE TITLE
bug: Slides and Modal including Slides problem [1.2.1]

### ISSUE THREAD

**Issue by privetr** [driftyco/ionic#4857]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>

Pagination is broken when we use the new ion-slides directive and open a Modal which also includes slides.

Here is a codepen which describes the problem : [Codepen](http://codepen.io/privetr/pen/xwGNyp)

To reproduce it : 
- Open the codepen : you see 3 slides pagination
- Open the modal : you see 2 slides pagination in this modal
- Close the modal : you see 2 slides pagination instead of 3
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @privetr!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4857). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4857)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Fixed, thanks!

**Comment by rushtehrani** [comment]
I am still seeing the issue in the CodePen.
