### ISSUE TITLE
bug: $ionicLoading strange behavior after 1.2.1 amsterdam

### ISSUE THREAD

**Issue by Tobiaswk** [driftyco/ionic#4858]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>After updating to 1.2.1 amsterdam I've noticed that $ionicLoading has some strange behavior. It shows up fine, with or without text, but whenever I call hide() it shows an small empty overlay... smaller that the one shown when calling show(). It is only visible very briefly; we're talking something like 200 milliseconds or so.

Has anyone else noticed the same behavior?

Example (the small overlay appearing just after I call hide() on $ionicLoading); 

![image](https://cloud.githubusercontent.com/assets/3562/11976462/a1400b0a-a978-11e5-8163-33192103862d.png)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Tobiaswk!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4858). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4858)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by deliverymanager** [comment]
I have noticed that too.
Before the loading dissappears it shows a smaller box.

**Comment by privetr** [comment]
Same here.

**Comment by mlynch** [comment]
Thanks, will review for 1.2.2

**Comment by mlynch** [comment]
Fixed, thanks.
