### ISSUE TITLE
bug: Defaulting all button borders to transparent

### ISSUE THREAD

**Issue by pmcbryde** [driftyco/ionic#4861]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>In the process of upgrading from 1.0.0 to 1.2.1 (I know, a ways behind). This commit broke all of the buttons in our app, removing their borders: https://github.com/driftyco/ionic/commit/21e54be63c3b39963813d83a4e2aa4c36784fe3e#diff-38983e82a6c8e46a6adaf2d5e3d81997R6

The only workaround is to re-write this mixin locally without that change. The fix (I'd guess, if you really really want to default every button to have no border) would be to set $button-stable-border to "transparent" instead of overwriting every button's border: https://github.com/driftyco/ionic/blob/master/scss/_variables.scss#L103
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @pmcbryde!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4861). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4861)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
This isn't a bug, it's a design decision. If you need borders like pre 1.2, just add them:

.button { border: blah }

**Comment by mlynch** [comment]
Note: this commit made ionic 1 buttons match v2 buttons, so we're going this way anyways

**Comment by ammulder** [comment]
There are issues with this change in Ionic 1, though.

In Ionic 2, for instance, a Segment renders a border around each button, giving it some visual distinction.

In Ionic 1, a Button Bar just renders as a big block of color with some random text floating freely within it.

With the default colors, the light and stable buttons can be really hard to distinguish from the page background.

The old style with borders (demonstrated in the current Ionic 1 CSS docs) looks way better.

I'd like to see a simple option to restore borders to all buttons built into the Ionic CSS (even something like button class="button button-stable button-with-border").  Or at a bare minimum, add borders back to buttons in a button bar.

**Comment by boltex** [comment]
Changing the styling of buttons to match another product (ionic 2) is a mistake . It should have been at most an optional feature.
