### ISSUE TITLE
bug: ion-header-bar ignores class attribute

### ISSUE THREAD

**Issue by yossi-shasho** [driftyco/ionic#4864]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>the basic example in the guides http://ionicframework.com/docs/api/directive/ionHeaderBar/ does not work:
```html
<ion-header-bar align-title="left" class="bar-positive">
  <div class="buttons">
    <button class="button" ng-click="doSomething()">Left Button</button>
  </div>
  <h1 class="title">Title!</h1>
  <div class="buttons">
    <button class="button">Right Button</button>
  </div>
</ion-header-bar>
<ion-content>
  Some content!
</ion-content>
```
results in an HTML without the class `bar-positive`
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @yossi-shasho!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4864). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4864)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Just tried this and it definitely works. Perhaps you're hitting a JS error somewhere and the page didn't fully load?
