### ISSUE TITLE
bug: installation

### ISSUE THREAD

**Issue by sufiah25** [driftyco/ionic#4883]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>installation issues. 

i am following a step from http://ionicframework.com/getting-started/ and at the 3rd step i got an error as below:

Error: No emulator images (avds) found.</span>

<span is-issue-template></span>

**Comment by JerryBels** [comment]
Hey man,

Are you on a mac ? Otherwise you can't run an IOS app, and you should then work with Android. Android doesn't have an emulator by default on PC, you need to install one. I think (never did it myself) that if you install Android Studios you will have an emulator installed. Please follow the guidelines to install Android environment for Cordova and Ionic : 

http://cordova.apache.org/docs/en/5.1.1/guide/platforms/android/index.html

Good luck.

**Comment by mlynch** [comment]
CLI issue, would love it if you posted here: https://github.com/driftyco/ionic-cli
