### ISSUE TITLE
ion-slide-box slider shows next slide in same screen when phone orientation change

### ISSUE THREAD

**Issue by ElakiyaS** [driftyco/ionic#4926]
when phone orientation changes slider crashes and next image of the slider showing along with the current image.

**Comment by ikastech** [comment]
i also face the same issue any one help to resolve this issue.

**Comment by kannadas** [comment]
i also face the same issue please any one resolve this issue.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by kannadas** [comment]
Hi jgw96, Just create simple image slide box  while change the orientation the background other image are visible and the effect also worst when more than 20 images.
Just build the code and test in phone then change orientation if more image there you get the issues. Note: don't set the width which is required to 100%.
Please check this link  **http://play.ionic.io/app/af509477c663**

Thank you for response.

**Comment by jgw96** [comment]
Hello! As `ion-slide-box` has been depecrated i will be closing this issue for now. Look out for alot of updates to slides in the near future! And thanks for using Ionic!
