### ISSUE TITLE
bug: Inconsistent treatment of non-keyboard inputs

### ISSUE THREAD

**Issue by jeremyrussell** [driftyco/ionic#4943]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>While testing the fix for another bug I opened (#3927 now resolved), I was investigating the effects of selecting/activating inputs that don't have associated mobile virtual keyboards whilst an input with an associated keyboard has focus.  What I found was inconsistent in my view.

My expectation is that while a input has focus and the keyboard is visible, when the user taps on any region of the screen that can't accept focus or can but does not have an associated virtual keyboard, should blur the currently focused field and hide the keyboard

I have created the following codepen tied to the latest version of ionic v1.2.4 http://codepen.io/jeremyrussell/pen/eJRyjg to demonstrate the difference between the various input types.

To summarise the differences I've noticed testing with iOS 9:
  - checkbox: does not blur active input - **not expected**
  - radio: does blur active input - as expected
  - toggle: does not blur active input - **not expected**
  - button: does blur active input - as expected
  - reset: does blur active input - as expected
  - submit: does blur active input - as expected
  - range: does not blur active input - **not expected**
  - image: does blur active input - as expected
  - week: does blur active input - as expected
  - hidden: see description below - **not expected**

One final test I added, which I'm not sure is a valid test case, was to wrap a hidden field with a label.  This results in the blur not occurring, however if a label is by itself (ie. not wrapping an input) the blur does occur.</span>

<span is-issue-template></span>

**Comment by 42shadow42** [comment]
This bug is not isolated to IOS, I have been able to replicate it on my droid.

I have done some digging and this is what I found:

For checkbox, toggle, and other hidden inputs this appears to be isolated to the preventing the default actions within the tap.js file. Please see the attached codepen at http://codepen.io/42shadow42/pen/WrZyBG where ionic.tap has been modified with inline js. The only change I made was commenting line 371. This undoubtedly has side effects, but I have been unable to determine what they might be. I haven't been able to run the unit tests on my system to see what may have broken.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
