### ISSUE TITLE
bug: Update meteor package on Atmosphere

### ISSUE THREAD

**Issue by canac** [driftyco/ionic#4949]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The driftyco:ionic package on Atmosphere is stuck on version 1.1.0_2. Please publish an update so that we can use Ionic 1.2.x in our meteor apps!</span>

<span is-issue-template></span>

**Comment by justinweinberg** [comment]
I would  very much like to go to production with 1.2.x and am stuck with 1.1.0.    Please update driftyco:ionic.

**Comment by plraphael** [comment]
Me too guys...or at least tell us something so we can try to help you with a PR :)

**Comment by jonmc12** [comment]
If you are in a rush, you can always publish your own version using your meteor account.  I like [Meteor Package Publisher](https://github.com/dotansimha/meteor-package-publisher) for existing repos that use bower.  In the case of you need to:
1.  Specify the JSON version per example
2.  run ```node ./meteor-package-publisher <filename>.json``` (this will generate the bower package.js file you need, but give you an error when publishing)
3.  find he newly generated package.js file in ```./bower_components/ionic/```
4.  update package.js to include appropriate assets using ```api.addAssets()``` (this is necessary because ```meteor-package-publisher``` api does not provide this automatically).
5.  from ```./bower_components/ionic/``` run ```meteor publish --create```

**Comment by canac** [comment]
I see that version 1.2.4 has been published on Atmosphere. Thank you for taking care of this!
