### ISSUE TITLE
perf: Android Performance on certain devices is too slow

### ISSUE THREAD

**Issue by ivks** [driftyco/ionic#4992]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>Device: Mi4i, Asus Zenfone
- Ripple effect is too slow and not at all smooth.
- Navigating between tabs is slow too.

Note: This issue is not noticeable in the chrome browser.</span>

<span is-issue-template></span>

**Comment by kinkaz** [comment]
Have you tried using Crosswalk ? This will use a Chrome WebView instead of your "slow" Android 4.4 WebView. http://blog.ionic.io/crosswalk-comes-to-ionic/

https://crosswalk-project.org/

**Comment by ivks** [comment]
@kinkaz Thank you for the suggestion.
I do know about the crosswalk project, but do not want to use it for its drawbacks.
In between I suggested the wrong version no, have updated it to 5.

**Comment by adamdbradley** [comment]
There have been significant improvements recently, but this will be an ongoing issue and we'll always be working to improve performance, so I'm going to close this is issue for now, thanks.

**Comment by andrefedalto** [comment]
I'm also experiencing similar issues with ZenFones, many users are reporting VERY poor performance in ZenFones. My app runs very smoothly on devices with ARM cpus, but devices with x86 (Zenfones for example) run it VERY slow, and by VERY slow I mean something like 10~20 seconds to transition between pages (open menu and tap to go to a differente page). I double checked and these users are using the x86 apk, so it should be as fast as the arm devices.

Is this something related to ionic or xwalk? I was not sure so I decided to post here instead of opening a new issue to hear what the experts can advise :)
