### ISSUE TITLE
the nav bar thanslate to show too quick

### ISSUE THREAD

**Issue by floraluo** [driftyco/ionic#5088]
The view A hide nav var and view B show nav var .The scene is the nav bar show immediately when I form A to B  the view A  not leave entirely and the view B also  not show. So, do you have any idear?

**Comment by Ionitron** [comment]
Greetings @floraluo!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic.

This GitHub issue tracker is used to track Ionic features, problems, and development.  

If you wish to get help using Ionic, the recommended place is [the forum](http://forum.ionicframework.com) or [Ionic Worldwide on Slack](http://ionicworldwide.herokuapp.com/). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
