### ISSUE TITLE
Using Stripe API keys

### ISSUE THREAD

**Issue by calebfaruki** [driftyco/ionic#5097]
Is there an efficient workflow method for switching between test and live API keys for Stripe? I've been using `angular-payments` for my app checkout but I need a more seamless way to be able to test transactions even after my Ionic app has been published to the App Store.

Any recommendations? Less of an issue and more of a general question...

**Comment by Ionitron** [comment]
Greetings @calebfaruki!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic.

This GitHub issue tracker is used to track Ionic features, problems, and development.  

If you wish to get help using Ionic, the recommended place is [the forum](http://forum.ionicframework.com) or [Ionic Worldwide on Slack](http://ionicworldwide.herokuapp.com/). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
