### ISSUE TITLE
bug: Starting scroll on a label

### ISSUE THREAD

**Issue by Manduro** [driftyco/ionic#5102]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>browser</span>

<span ionic-description>When scrolling starts on a label, the scroll is canceled. This occurs on iOS, haven't tested Android.

This problem is demonstrated in the following codepen: http://codepen.io/manduro/pen/vLpEzx/
(Open it on iOS or in Chrome device mode)</span>

<span is-issue-template></span>

**Comment by Invision70** [comment]
+1

**Comment by DomClaxton** [comment]
I can confirm this is an issue for me too. In browser using Chrome tools and switching to touch device view. Also in IOS 8.1.3 (iPhone4s). Both instances have the form element in a modal. I can only scroll the content 'between' the range element. If your finger registers a 'hit' on top of the range then scrolling ceases. Have tried using native scrolling too - no joy.

**Comment by tomasbedrich** [comment]
I think it may be an issue in a [function `tapTargetElement`](https://github.com/driftyco/ionic/blob/aef490b177406f9bd7d532294abd6c3198357622/js/utils/tap.js#L599), because `label.control` returns the labeled `<input>` even if the `<label>` doesn't wrap it – [according to HTML5 specs](https://www.w3.org/TR/html5/forms.html#labeled-control). On the other hand, `ele.querySelector` returns only the `<input>` which is inside the `<label>` tag ([source](https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelector)).

But I don't get the point [of this condition](https://github.com/driftyco/ionic/blob/aef490b177406f9bd7d532294abd6c3198357622/js/utils/tap.js#L426) at all (even after reading the comments – what does it mean to "ugly auto scroll"?).

The simplest solution which worked for me was to remove the condition mentioned above. Since then I haven't discovered any cons of this solution.

**Comment by Manduro** [comment]
For @tomasbedrich and others running in to this: the easy fix for me was to replace all `<label>`'s with regular `<div>`'s. The downside to this is of course not being able to focus the input by tapping the label. In my case I only use a placeholder, not a real label, so it isn't much of a problem.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#184
