### ISSUE TITLE
bug: Push not working properly

### ISSUE THREAD

**Issue by upmauro** [driftyco/ionic#5113]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>

### Ionic

Component | Version
---------------|-----------
Cordova CLI | 5.4.1
Ionic Version | 1.2.4-nightly-1917
Ionic CLI Version | 1.7.12
Ionic App Lib Version | 0.6.5
Node Version | v5.3.0

### Android

Component | Version
---------------|-----------
SO| 6.0
SDK| 23 

### Problem

I am using the ionic to receive push messages. All messages arrive correctly on the device, however, are displayed in the status bar, but without running the code defined in the notification event (onNotification).

```javascript
angular.module('app', ['ionic', 'ionic.service.core', 'ngCordova'])
.run(function($ionicPlatform, $rootScope, $state, $ionicHistory) {

    $ionicPlatform.ready(function() {
        var push = new Ionic.Push({
            "onNotification": function(notification) {
                console.log('Push received.')
                navigator.vibrate(700);
            },
        });
    })

});
```
The above is only triggered after clicking on the notification.
I already tried everything I found solution and it still fails.
Could you help me?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @upmauro!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=5113). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=5113)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-platform-web-client#45
