### ISSUE TITLE
bug: Ionic popover cover header when keyboard open

### ISSUE THREAD

**Issue by balicekt** [driftyco/ionic#5115]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>when open popover and also keyboard together and want to scroll popover the body of popover cover header. See attached pictures. 
![simulator screen shot 20 jan 2016 22 32 46](https://cloud.githubusercontent.com/assets/6289261/12463846/26db8ec0-bfc6-11e5-881a-f6ba890f762c.png)

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @balicekt!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=5115). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=5115)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by balicekt** [comment]
the solution is: 

.ion-popover-view{
  overflow: hidden;
}

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Are you all still having this issue?

**Comment by jgw96** [comment]
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!
