### ISSUE TITLE
Header bar missing issue in ionic material

### ISSUE THREAD

**Issue by rig1** [driftyco/ionic#5122]
I am creating an app using ionic-material project. I have created a login page.After login it displays gallery page. If i do some action in other pages and return back to gallery page the i can't see the header bar.
I have noticed one thing that when i command out this line "$ionicConfigProvider.views.maxCache(0);" in app.js the header bar will miss.otherwise it is fine.I don't know what's went wrong.Can anybody help me.

**Comment by Ionitron** [comment]
Greetings @rig1!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic.

This GitHub issue tracker is used to track Ionic features, problems, and development.  

If you wish to get help using Ionic, the recommended place is [the forum](http://forum.ionicframework.com) or [Ionic Worldwide on Slack](http://ionicworldwide.herokuapp.com/). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
