### ISSUE TITLE
can version 1.2 use segment?

### ISSUE THREAD

**Issue by zhuangtongfa** [driftyco/ionic#5123]
can version 1.2 use segment?

**Comment by Ionitron** [comment]
Greetings @zhuangtongfa!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic.

This GitHub issue tracker is used to track Ionic features, problems, and development.  

If you wish to get help using Ionic, the recommended place is [the forum](http://forum.ionicframework.com) or [Ionic Worldwide on Slack](http://ionicworldwide.herokuapp.com/). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
