### ISSUE TITLE
Modals in e2e tests are throwing an exception

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5124]
![screen shot 2016-01-21 at 11 58 26 am](https://cloud.githubusercontent.com/assets/6577830/12487709/56ec0642-c036-11e5-8fe2-15364bbe3f81.png)

**Comment by tlancina** [comment]
Seeing same issue when calling setRoot in sidemenu starter.  Looks like it's caused by https://github.com/driftyco/ionic/blob/2.0/ionic/components/nav/nav-controller.ts#L1213.  The page gets destroyed at https://github.com/driftyco/ionic/blob/2.0/ionic/components/nav/nav-controller.ts#L1191 and recursively destroys all its children as well, including the toolbar: 
![image](https://cloud.githubusercontent.com/assets/804331/12492061/00cb1420-c044-11e5-8df1-6d3e3ab361d3.png).

**Comment by brandyscarney** [comment]
No longer an issue
