### ISSUE TITLE
bug: No provider for Http

### ISSUE THREAD

**Issue by 3dd13** [driftyco/ionic#5144]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>tried to run ionic-conference-app with latest 2.0 branch. 
angular providers are not founded if i inject those providers in my App or Components. Http, LocationStrategy, etc.

For example, if I inject http into App constructor:

    @App({
      templateUrl: 'build/app.html',
      providers: [ConferenceData, UserData],
      config: {}
    })
    class ConferenceApp {
      constructor(app: IonicApp, events: Events, http: Http, confData: ConferenceData, userData: UserData) {

the error was at the App decorator bootstrap step.
I have checked that the HTTP_PROVIDERS exists in the second argument (providers array list), however, somehow none of the angular providers are found during the ConferenceApp injection stage</span>

<span is-issue-template></span>

**Comment by mikkokam** [comment]
I managed to use http with the latest 2.0 branch.
Imported http from Angular:

    import {Http, Headers} from 'angular2/http';

but also - to actually use http - had to import map and others from RxJS (breaking change in Angular, http as an Observable is missing all the operators, so even map has to be imported):

    import 'rxjs/add/operator/map';

Luckily the operator importing seems to work by just importing it once, to the app.js.

**Comment by brandyscarney** [comment]
Is this still an issue with alpha.51? I'm not seeing this error.

**Comment by brandyscarney** [comment]
@3dd13 @mikkokam Is this still an issue with alpha.54?

**Comment by tlancina** [comment]
@3dd13 were you using a `npm link` to develop against 2.0? We ran into the same thing and fixed it in: https://github.com/driftyco/ionic-conference-app/commit/43ecc2faf994f3a11bd55773f953852db08fcdb1
https://github.com/driftyco/ionic2-app-base/commit/eae8745b5ed3937ebaf9c1af6f102e057fb65859

Definitely a weird one, webpack sees the imports for Angular2 in the linked Ionic source files and finds them in node_modules in the linked folder (not the app folder), so a second copy of Angular2 gets bundled.  The provider error is because the Http imported in the app code is the second Http, different from the first one that was imported in the Ionic code during bootstrap.

Going to close this as I'm fairly certain this is the issue, let us know if that's not the case!

**Comment by 3dd13** [comment]
@brandyscarney it works with the released version, was only affecting the npm link situation.

@tlancina it looks okay, will report again if I see any weird provider injected library issues

thanks everyone !
