### ISSUE TITLE
bug: iOS navigation bar is not pixel perfect

### ISSUE THREAD

**Issue by manucorporat** [driftyco/ionic#5149]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>Number of issues:
- Go back default color is not the same.
- Title's font is not the same.
- Title's text is one pixel up.
- Navigation bar height is one pixel smaller
- The back button text is not vertically aligned with the title (MOST IMPORTANT ISSUE)
- The back arrow is smaller.
ionic one: 24x40 while native one is: 25x42</span>

<span is-issue-template></span>

Ionic 2:
<img width="901" alt="screen shot 2016-01-22 at 17 02 17" src="https://cloud.githubusercontent.com/assets/127379/12515931/113e13a6-c12b-11e5-8029-d1a55364bc35.png">

Native one:
<img width="903" alt="screen shot 2016-01-22 at 17 02 46" src="https://cloud.githubusercontent.com/assets/127379/12515941/19d00ef2-c12b-11e5-9f74-324516c45c91.png">
notice that in the native demo, the go back text is pixel-perfect aligned with the title!

**Comment by manucorporat** [comment]
I added a couple of fixed guides, so you can compare easily

**Comment by brandyscarney** [comment]
@manucorporat If you'd like to try and fix it there are a few issues I need to work on before I will get to this one. Thanks for the descriptive issue and images though! :smile:

**Comment by manucorporat** [comment]
@brandyscarney you are welcome!
in the meantime, I did some research:
<img width="544" alt="screen shot 2016-01-22 at 17 49 31" src="https://cloud.githubusercontent.com/assets/127379/12516961/9b0f90b4-c130-11e5-872c-1ed9d592ae21.png">

^ **top text** is native nav title in iOS 9 
**bottom text** was added with photoshop: it is exactly `Helvetica Neue Medium Bold, 17pt`.
While it is not exactly the same font (in iOS 9 it is `San Francisco Medium`) it looks much better than current font used by ionic.

iOS9 System Semibold 17 (San Francisco)
```objc
[UIFont systemFontOfSize:17 weight:UIFontWeightSemibold]
```

iOS8 System Semibold 17 (Helvetica Neue)
```objc
[UIFont systemFontOfSize:17 weight:UIFontWeightSemibold]
```

iOS7 System Bold 17 (Helvetica Neue)
```objc
[UIFont boldSystemFontOfSize:17];
```

**Comment by bensperry** [comment]
Hey @manucorporat, thank you for the keen eye! Here's what's we're doing:

> Go back default color is not the same.

We're not going to change this because we want the user to pick the colors and match it to their brand. We don't want to be too specific such that users have to opt out of the generic iOS/Android colors just to get their own brand colors in. If you want to change it to the iOS blue in your app you are welcome to.

> Title's font is not the same.

Good catch, we're going to bump the `toolbar-title` to `font-weight: 600`, it's currently at 500.

> Title's text is one pixel up.

We won't be able to change this because it's retina and you can't use half pixels in CSS.

> Navigation bar height is one pixel smaller

We won't be able to change this because it's retina and you can't use half pixels in CSS.

> The back button text is not vertically aligned with the title (MOST IMPORTANT ISSUE)

Agreed this is an issue, we'll be fixing this!

> The back arrow is smaller. ionic one: 24x40 while native one is: 25x42

Agreed this is an issue - we're going to bump `back-button-icon` to `font-size: 3.3rem` to fix this.

**Comment by brandyscarney** [comment]
Hey @manucorporat, I'm going to go ahead and make these changes per Ben, but thank you for offering help!

**Comment by manucorporat** [comment]
@bensperry @brandyscarney  awesome! good job!
I agree, the one pixel thing is not really an issue, I just pointed :)

**Comment by brandyscarney** [comment]
Changes above have been implemented. This will be in the next release, thanks again!

**Comment by manucorporat** [comment]
@brandyscarney just tried it! looks beautiful now!
