### ISSUE TITLE
(v2) ionic serve doesn't detect changes in vagrant host

### ISSUE THREAD

**Issue by cxcxcxcx** [driftyco/ionic#5210]
(This is for ionic v2)

I'm running ionic serve within a vagrant VM, and found that although it detects changes within the VM, but changes from the host wouldn't be respected.

On the other gulp watch works fine for my old projects.

Searching around this seems to be webpack problem, which has been resolved bug polling may need to be enabled separately: https://github.com/webpack/webpack/issues/125

Is there an easy way to enable polling for the watching for ionic serve v2?

Thanks!

**Comment by tomsun** [comment]
Same issue when running `ionic serve` in a Docker container via [Docker Toolbox](https://www.docker.com/products/docker-toolbox) on OS X

...for the same reason: In both scenarios VirtualBox's "Shared Folders" feature tends to be a part of the workflow (Edit files in the GUI on the host OS, run Node in the VM), which is why the file events do not propagate: https://www.virtualbox.org/ticket/10660

**Comment by cxcxcxcx** [comment]
The thread suggested enable --watch-poll for the webpack dev server. Not sure if there would be an equivalent for ionic serve? Thanks!

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#759
