### ISSUE TITLE
 Open alert in the app (2.0.0-alpha.52)

### ISSUE THREAD

**Issue by afrad** [driftyco/ionic#5261]
The api changed from using the popup (overlay) to  nav.present(alert). I have however since then the problem of that can open popups only in pages. I'm trying to open a popup in the app.js but couldn't since the nav controller is not available yet. Any idea how to overcome this?

**Comment by adamdbradley** [comment]
Do you have an ion-nav in your app? I'm not sure what you mean by "since the nav controller is not available yet".

Here are some examples:
https://github.com/driftyco/ionic/blob/2.0/ionic/components/alert/test/basic/index.ts#L17

**Comment by tomsun** [comment]
Assumed goal: run `navControllerInstance.present()` and other NavController methods from within the `@App()`-decorated class

Out of habit, I would try something like this:

 `ionic start --v2 --template blank navtest`
...
```
diff --git a/app/app.js b/app/app.js
index 5ffbd11..68d6db6 100644
--- a/app/app.js
+++ b/app/app.js
@@ -1,4 +1,4 @@
-import {App, Platform} from 'ionic/ionic';
+import {App, Platform, NavController} from 'ionic/ionic';
 import {HomePage} from './pages/home/home';
 
 
@@ -7,7 +7,7 @@ import {HomePage} from './pages/home/home';
   config: {} // http://ionicframework.com/docs/v2/api/config/Config/
 })
 export class MyApp {
-  constructor(platform: Platform) {
+  constructor(platform: Platform, nav: NavController) {
     this.rootPage = HomePage;
 
     platform.ready().then(() => {
```

That produces `EXCEPTION: No provider for NavController! (MyApp -> NavController)` in the browser... possibly the same problem@afrad had?

That injection approach works fine within a @Page()-decorated class - perhaps because its directive always happens to be a child of `<ion-nav>` in practice, whereas the @App()-class is a parent of `<ion-nav>`?:

```
@App({
  template: '<ion-nav [root]="rootPage"></ion-nav>',
```

Given that realization, I would ask "how do I get a reference to a child component's class in Angular 2"?

http://stackoverflow.com/a/34517518
https://angular.io/docs/ts/latest/api/core/ViewChild-var.html
https://angular.io/docs/ts/latest/api/core/QueryMetadata-class.html

Evaluation of the @ViewChild()-approach within the `--template blank` app:

```
diff --git a/app/app.js b/app/app.js
index 5ffbd11..f04f4ec 100644
--- a/app/app.js
+++ b/app/app.js
@@ -1,12 +1,15 @@
-import {App, Platform} from 'ionic/ionic';
+import {AfterViewInit, ViewChild} from 'angular2/core';
+import {App, Platform, NavController, Alert} from 'ionic/ionic';
 import {HomePage} from './pages/home/home';
 
 
 @App({
-  template: '<ion-nav [root]="rootPage"></ion-nav>',
+  template: '<ion-nav #navctl [root]="rootPage"></ion-nav>',
   config: {} // http://ionicframework.com/docs/v2/api/config/Config/
 })
-export class MyApp {
+export class MyApp implements AfterViewInit {
+  @ViewChild('navctl') nav:NavController;
+
   constructor(platform: Platform) {
     this.rootPage = HomePage;
 
@@ -27,4 +30,16 @@ export class MyApp {
       // StatusBar.setStyle(StatusBar.LIGHT_CONTENT)
     });
   }
+
+  ngAfterViewInit() {
+    console.log('nav is', this.nav);
+
+    let alert = Alert.create({
+      title: "New Friend!",
+      body: "Obi wan Kenobi just accepted your friend request!",
+      buttons: ['Ok']
+    });
+
+    this.nav.present(alert)
+  }
 }
```

This approach does seem to get the desired NavController reference; from Safari's console:
`nav is – Nav {elementRef: ElementRef_, _id: "i0", parent: null, …}`

And it does produce an alert when the app starts. But it also seems to block
the root page from loading: The root page does not show up behind the alert,
nor does it appear when the alert is dismissed.

(Ionic 2.0.0-alpha.54)

**Comment by tomsun** [comment]
Replacing `this.nav.present(alert)` in ngAfterViewInit() with `setTimeout(() => this.nav.present(alert), 1000)` seems to allow the root page to load and function as expected.

**Comment by afrad** [comment]
@tomsun This will work only if the loading is faster than 1 second.

**Comment by tomsun** [comment]
( @afrad sure, not a robust solution, not really a solution at all, just an observation for debugging purposes :-) )

**Comment by afrad** [comment]
A possible workarround is to use an own page for the popup. I don't like it. I miss here the good old $ionicPopup.

**Comment by adamdbradley** [comment]
To solve this issue I would recommend putting the alert within your root page, and not in the startup script of your app.
