### ISSUE TITLE
bug: input css bad when labels stacked

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#5298]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm using a form with stacked labels, the invalid style has a bottom border that doesn't fill the whole item and looks weird:</span>

<span is-issue-template></span>
![image](https://cloud.githubusercontent.com/assets/9698639/12755680/6c1d88a8-c99e-11e5-9a95-154e86181741.png)

**Comment by brandyscarney** [comment]
So this is because by default items have padding left and the invalid style is there to replace the bottom border that appears on the item. 

![screen shot 2016-02-18 at 6 11 29 pm](https://cloud.githubusercontent.com/assets/6577830/13161373/3ba9f9a2-d66b-11e5-8d85-33fcf98f2507.png)

Are you hiding this border? It seems like there is some custom css involved.

**Comment by Luchillo** [comment]
There was a border made of custom css and i had to extend the border also with custom css.

**Comment by brandyscarney** [comment]
Can you show me the CSS for the border extend, please?

**Comment by Luchillo** [comment]
I will if i find the commit for that, i fixed that with custom css so i would have to search for the commit in git that relate to before i fix it.

**Comment by Luchillo** [comment]
Sorry not available, the labels in ion-items have changed a lot, before the `stacked` attribute was put in the `ion-item` element, now the attribute is put directly in the `ion-label` element and the red line doesn't even show any more, this error happened when in alpha.52 i think? still how would i get back the red lines?

**Comment by Luchillo** [comment]
I also removed the custom css that deal-ed with the row border so why isn't showing any more?

**Comment by brandyscarney** [comment]
It is applied when the input is invalid and touched, so this is the styling applied to it:

```
ion-input.ng-invalid.ng-touched:after {
  border-bottom-color: #f53d3d
}
```

And the color is determined by this var: `$text-input-md-hightlight-color-invalid` 

I'm going to close this since it seems like it was related to your custom CSS. This issue is open to tweak the highlights, so if you have any ideas of how you think this should work please add them there: https://github.com/driftyco/ionic/issues/5052

Thanks!

**Comment by Luchillo** [comment]
I have noticed that the red underline still shows, but only in device, in browser doesn't work even when the `ng-invalid.ng-touched` is applied to the `ion-input`.

**Comment by brandyscarney** [comment]
It should only work on Android devices. Are you emulating an Android?

**Comment by Luchillo** [comment]
Oh i see, as chrome goes with the ios styles when not using the emulator, i was confused, thanks for taking the time :)
