### ISSUE TITLE
Splash Screen not showing on default new blank apps 

### ISSUE THREAD

**Issue by AhmedMoustafa330** [driftyco/ionic#5347]
the current ionic info: 
Cordova CLI: 6.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7
Node Version: v5.5.0

**Comment by Z3roCoder** [comment]
That is because a blank app does not contain anything. Add a splashscreen with the Cordova CLI:
cordova plugin add org.apache.cordova.splashscreen

And add the Splashscreen to the config.xml:
<preference name="SplashScreen" value="screen" />
<preference name="SplashScreenDelay" value="3000" />

You can alter this time with whatever you’d like or dismiss the splash screen at the end of your $ionicPlatform.ready() method by running navigator.splashscreen.hide()

**Comment by cho-is** [comment]
I have done it and still showing blank and not the generated files

**Comment by christianharke** [comment]
Same here, splashscreen doesn't work with Cordova 6.0.0. Downgrading Cordova to 5.4.1 fixed it.

I guess it's a Cordova-specific issue.

**Comment by jgw96** [comment]
Hello! Are you all still having this issue? Thanks!

**Comment by christianharke** [comment]
@jgw96 After a `npm install -g cordova ionic` splashscreens are working again :+1:

**Comment by jgw96** [comment]
Awesome! Glad to hear!
