### ISSUE TITLE
bug: click on ion-label does not focus input

### ISSUE THREAD

**Issue by manucorporat** [driftyco/ionic#5378]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Tapping on a `<ion-label>` text input is not focused.
This should be considered as a UX bug. I have found myself (and friends) tapping the label in order to write into the `<input>` element several times.

> run gulp watch and open

http://localhost:8000/dist/e2e/input/fixed-inline-labels/
http://localhost:8000/dist/e2e/menu/basic/
^^ this is a good example of why this is needed!

I can try to fix it by myself, but I want to hear from advice:
 - should we implement our custom JS solution?
 - should `<ion-label>` wrap a `<label for="inputs-id">`? https://teamtreehouse.com/community/form-field-focus-by-placing-input-element-inside-label-element

 - or is the current behaviour intentional?

</span>
<span is-issue-template></span>

**Comment by adamdbradley** [comment]
As far as the label, we’re purposefully not using `<label>` because it a real challenge to normalize between all browsers, especially on mobile and removing the 350ms delay, and how prevent default works, between the various browsers and versions. Ionic 1 uses `<label>` often and it’s nothing but headaches and sources of bugs. iOS should be removing the 350ms delay soon, which will make things work a lot easier, but it's widely adopted we can't trust to use `<label>` on touch devices yet. There's nothing wrong with wrapping and input with a label, and recommended actually, but for mobile and removing the delay it causes issues.

**Comment by manucorporat** [comment]
@adamdbradley gotcha!

**Comment by adamdbradley** [comment]
* Meant to close the PR, not this issue
