### ISSUE TITLE
Opening Modal randomly causes App to freeze

### ISSUE THREAD

**Issue by dgobaud** [driftyco/ionic#5399]
Hi, This bug is not fixed. It happens constantly. It is a major problem https://github.com/driftyco/ionic/issues/1912 is there any update? I posted in #1912 25 days ago but there has been no update.

**Comment by mhartington** [comment]
Can you provide a minimal demo that has this issue?

**Comment by dgobaud** [comment]
yes will work on it @nick2k5

**Comment by mhartington** [comment]
I have not been able to recreate the issue unfortunately. I'm going to close this. If you can replicate the issue in a small, isolated demo, we can revisit this.

**Comment by arruix** [comment]
I have the same issue for long time ago, my application is opening a popup every time that I have a numeric field, after some random time, my app don't recognize any touch, only if I move the device in landscape mode to portrait mode, I'm not able to give you some demo because is very randomly, some times I can work the whole day with no issues, other days happen very often, but when I try to debug backdrop div seems that is overlapping.

**Comment by sakujo** [comment]
Having the same problem. It's not fixed. In my case it happens random too, but after hitting Ok button of an alert popup. After hitting ok, i can't do anything but reopen the app. It happens on device. No errors.

P.s. Updated ionic and cordova recently. I couldn't update cordova and ionic in existing project. So i created a new project and replaced the new sass/www files with the ones of my old project. Don't know if that could be causing the problem, but i don't think so.

Ionic: 1.3.3
Angular: 1.5.3
Cordova: 6.5
Android: 7.0

**Comment by arruix** [comment]
In my case, after some research, I found that Xcode throws this error when the freezing happen
`WebKit discarded an uncaught exception in the webView:willRemoveScrollingLayer:withContentsLayer:forNode: delegate: <NSInvalidArgumentException> -[WebActionDisablingCALayerDelegate willBeRemoved]`.

And the reason was the UIWebView engine that Apache Cordova is using to build the iOS app regarding to this post http://stackoverflow.com/questions/26217160/webkit-throwing-exception-on-ios-8-for-call-to-setbeingremoved, so I switchs to WKWeb​View that is supporting by apple since iOS 8+,  the Ionic Pluging  is https://github.com/apache/cordova-plugin-wkwebview-engine, I didn't get any freezing issue so far, the memory used in the iPad was reduce by 90% less

**Comment by rafialikhan** [comment]
We have noticed this freeze issue as well and happens on device. 

**Scenario. (Android app)**
In the app open any modal and leave it on the screen and switch to any other app.  Let the phone self-lock; and allow apps to sleep in the background. Now reopen the app from the app list say after 10 mins of idle time. The modal window  will be frozen and you can not do anything other than killing the app (remove it from running apps list) and then restarting the app again. 

So just to be clear, this happens when you have a modal open and then move away from the app and come back after a while. (Again as mentioned by others, this is very sporadic, if you switch back and forth your ionic app and any other app, it works fine. But I believe its after sleep-wake up that the modal freezes over.
