### ISSUE TITLE
bug: Sass file found in a different place

### ISSUE THREAD

**Issue by RIanDeLaCruz** [driftyco/ionic#5409]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Using the Ionic 2 beta, I created a project. I've been trying to apply theme changes. 

According to the docs, the sass files where supposed to be inside the www/app folder. Instead, I've found it in a separate app folder in the root of the directory. 

When I do make changes to that directory, my changes do not apply. Additionally, the CLI notifies me that there is no gulpfile.</span>

<span is-issue-template></span>

**Comment by tlancina** [comment]
Themes should be located in the app folder, here's an example project structure: https://github.com/driftyco/ionic-conference-app/tree/master/app/theme.

You can change where the CLI looks for Sass files here: https://github.com/driftyco/ionic-conference-app/blob/master/ionic.config.js#L10.

If you are getting errors please include them in the issue so we can help you.  If you are following docs you believe to be incorrect, please link to them so that we can update them, thanks.

**Comment by RIanDeLaCruz** [comment]
Whenever I do `ionic serve`, I get a `no gulp file` in the command line

**Comment by RIanDeLaCruz** [comment]
My folder structure seems to be correct. I've already mentioned the documentation error in a different issue.

**Comment by tlancina** [comment]
Could you post the output of `ionic info` please? Also if possible some steps to reproduce the issue.

**Comment by RIanDeLaCruz** [comment]
@tlancina it was a misconfiguration of Ionic. Apparently, I was able to start a version 2 project from CLI version 1.7. That was what was causing the error. Will close this now.
