### ISSUE TITLE
Popover

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#5420]
- [x] Component
- [x] e2e tests
- [x] API docs
- [x] API demo
- [x] Add config properties to API

**Comment by djangojack** [comment]
Ionic v1 popover had a ~300ms click blocker after the popover was removed to prevent clicks from propagating down. This hurt the user experience for users who were trying trying to quickly press buttons after the popover was removed. 

Would be great if there was another solution in v2 instead of the click blocker.
