### ISSUE TITLE
How do i cache user login?i am using MEAN.JS as backend

### ISSUE THREAD

**Issue by rohitkumarvinay** [driftyco/ionic#5448]
I am using MEANJS in my server side, how do i use that to cache my login

**Comment by DILEEP-YADAV** [comment]
use local storage like  sqlite .ect

**Comment by mohamed-ahmed** [comment]
Why `not localStorage.setItem("token", token);`

**Comment by DILEEP-YADAV** [comment]
use this function with angular js:
function serverLog(level, event, data, $http) {
    var accessLogData = {
            'user': localStorage.getItem('Email'),
            'patrolPrefix': localStorage.getItem('Prefix'),
            'device': navigator.userAgent,
            'at': new Date(),
            'app': settingLoggingAppId,
            'event': event,
            'level': level,
            'json': angular.toJson(data)
        };
    if (-1 === document.URL.indexOf('http://') && -1 === document.URL.indexOf('https://')) {
        if (IN_CORDOVA) {
            accessLogData.device = device.platform + '/' + device.version + '/' + device.model;
        } else {
            accessLogData.device = 'Native/unknown';
        }
    }
    $http(dspRequest('POST', '/db/AccessLog', accessLogData)).
        success(function (data, status, headers, config) {
            return;
        }).
        error(function (data, status, headers, config) {
            return;
        });
}

**Comment by jgw96** [comment]
Thanks for posting an issue with us! Since this is more of a general programming question and not something related specifically to ionic i will be closing this issue, but here are some great links that may help you with this question:

https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API
https://nodejs.org/api/fs.html

Thanks again! And feel free to reopen this issue if you feel it was wrongly closed!
