### ISSUE TITLE
feat: Auto-import generated .scss to .core.scss

### ISSUE THREAD

**Issue by leonsas** [driftyco/ionic#5467]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Knowing that you need to import every generated `*.scss` file to the `app.core.scss` is just one more things to remember and beginners shouldn't have to do. I myself just spent 15 minutes trying to figure out why my scss changes weren't working despite the SASS compiler actually saying it was doing work. Maybe I don't know Ionic2's app structure by heart yet, but we should make it as easy and frictionless as possible for both totally new devs, as well as new devs coming from Ionic 1.

I see 2 ways, the lazy (1) and the awesome-dev-tool (2):

1. When a user runs `ionic generate x`, ensure the CLI tells the user anything they need to follow up with, in this case importing the generated .scss into the core.scss file. Just a small change, probably here: https://github.com/driftyco/ionic/blob/2.0/tooling/generator.js#L36

2. Actually overwrite .core.scss with the necessary change:
 `@import '../path/to/newly_generated_component.scss`

If you guys are down for (1) I'm happy to do commit and PR, but you should probably invest in the better longer-term solution (2).

</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Just like with any other form of web development, if a developer creates a new file, then the file needs to be wired up correctly for it to work. Yes we should make it easier to know what's happening, but we need to be careful to not overwrite any of the developers custom code, which is why number 2 is could cause more issues. Additionally, the app's css may require a certain order of files, so it's important for the developer to know what's happening. I'll move this over to the cli repo and we'll take a look at improving it, thanks.

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#773
