### ISSUE TITLE
Blur event on ion-input is not fired

### ISSUE THREAD

**Issue by xkjyeah** [driftyco/ionic#5487]
<ion-input type="text" (blur)="eventHandler()">  does not fire the eventHandler on blur.

Blur and other events should be bubbled to the parent container to allow for more complex interactions

**Comment by adamdbradley** [comment]
Is this in Ionic1 or Ionic2?

**Comment by xkjyeah** [comment]
Ionic2.

**Comment by prolink007** [comment]
Here is a current work around for "blur".

Use "focusout" or "mouseleave". Those are both working.

**Comment by brandyscarney** [comment]
So the reason these events aren't working for `ion-input` is because the `blur` and `focus` events do not bubble up from the native input, see: [blur](https://developer.mozilla.org/en-US/docs/Web/Events/blur) & [focus](https://developer.mozilla.org/en-US/docs/Web/Events/focus). 

We are now emitting these events from the `ion-input`. This should be fixed in the next release (beta.4), thanks!

**Comment by Gp2mv3** [comment]
Are you sure this issue is closed ? I have the same bug in 2.1.0.

This line doesn't fire the function:
`<ion-input type="datetime-local" formControlName="begin" (blur)="updateEndDate($event)"></ion-input>`

But this one does:
`<ion-input type="datetime-local" formControlName="begin" (focusout)="updateEndDate($event)"></ion-input>`

Tested on Chrome.

**Comment by brandyscarney** [comment]
@Gp2mv3 I'm not seeing any issues using either `type="text"` or `type="datetime-local"`. Could you see if changing the type does anything? What element are you clicking on to blur to it?

**Comment by sharonsw** [comment]
@brandyscarney I'm using ionic-angular 3.5.0, and can confirm that neither (blur) nor (focus) events are fired properly still. 

(focusout) does work though, even the docs state clearly that (blur) and (focus) are the appropriate events. 

What worked for me: 
`<ion-input type="text" formControlName="answer" (blur)="onBlur()"></ion-input>`

**Comment by Smoke1987** [comment]
`<ion-input [type]=" !showPassword ? 'password' : 'text' ">` when I try to change the `showPassword` by pressing the button `<button (tap)="showPassword = !showPassword; $event.preventDefault()">` `ion-input` loses focus, respectively, the keyboard disappears on the device. Using `<ion-input (focusout)="$event.preventDefault()">` does not help. Somebody has speculation why?

**Comment by afixibiranchi** [comment]
This worked for me.
<ion-input type="text" (ionBlur)="onBlur()"></ion-input>
