### ISSUE TITLE
Extra padding for some ion-item's

### ISSUE THREAD

**Issue by drobbins** [driftyco/ionic#5534]
#### Short description of the problem:

Padding for `ion-item`'s content is adjusted if the item is a link. This is especially apparent if you use an `item-note` but no item buttons.
#### What behavior are you expecting?

The padding to be the same, for the same content, regardless of whether it's a link or not.

**Steps to reproduce:**
1. Visit http://codepen.io/anon/pen/adrKza

**Ionic Version**: nightly, driftyco:ionic 1.2.4 for meteor

**Browser & Operating System**: OSX + Chrome. Doesn't occur on Android / Chrome

**Run `ionic info` from terminal/cmd prompt:** n/a, I don't have the CLI installed.

**Comment by mhartington** [comment]
Should be fixed in the nightly builds. Thanks for the heads up

**Comment by mhartington** [comment]
Revisiting this, seems like there could be a better solution. Going to reopen this and think on this.

**Comment by TheCopartnery** [comment]
Have noticed that when using `<ion-input>` rather than the older `<a class="item">` that a large amount of padding gets applied on the right.

In many cases it seems this extra padding is unnecessary and limits the space available for text. 

I would of expected both approaches to work in the same way, but due to <ion-input> being given the .item-complex class it adopts the following padding...

padding: $item-padding (ceil( ($item-padding * 3) + ($item-padding / 3) ) - 5) $item-padding $item-padding;

..., which is different from the default padding provided by a normal .item.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#197
