### ISSUE TITLE
V2 - Feature - Default styles for "required" inputs

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#5559]
#### Short description of the problem:

I would like to see some default input styles for Ionic inputs that have the required attribute set to true.

#### What behavior are you expecting?

I would like to see some sort of visible indication the the input is required so my users can easily differentiate between optional and required fields.

**Ionic Version**: 1.x / 2.x

2.x

**Browser & Operating System**: iOS / Android / Chrome

All

**Comment by brandyscarney** [comment]
I'm not sure if this is something that the framework should handle since this is really up to the developer to decide. [Material design](https://www.google.com/design/spec/components/text-fields.html#text-fields-search-filter) recommends using an asterisk with a note that explains what it means, which can be done using the following:

```
<ion-item>
  <ion-label>Username <span danger>*</span></ion-label>
  <ion-input [(ngModel)]="username"></ion-input>
</ion-item>
```

iOS doesn't really have guidelines on this but generally they go with an asterisk or placeholder text: http://stackoverflow.com/a/9316725/3802466

Going to add @bensperry to this issue for his opinion.

**Comment by danbucholtz** [comment]
That is fair - we could definitely do the asterisks.

I was just looking at the [ng2 documentation](https://angular.io/docs/ts/latest/guide/forms.html) and thought it was pretty nice how they had the red bars for required, etc.  It would be cool to see something like this in Ionic.

Definitely not a short term priority in my opinion.

**Comment by brandyscarney** [comment]
Oh there is an issue open (https://github.com/driftyco/ionic/issues/5052) for adding highlighting on error of a required field. It actually exists if you view it on an android device currently:

![screen shot 2016-02-22 at 2 58 48 pm](https://cloud.githubusercontent.com/assets/6577830/13230814/d6cad530-d974-11e5-8b08-9c48f6792c6f.png)

From our e2e test:
https://github.com/driftyco/ionic/tree/2.0/ionic/components/input/test/form-inputs

I just need to find a good way to make it easily customized & enabled/disabled. :smile:

**Comment by brandyscarney** [comment]
@danbucholtz is issue https://github.com/driftyco/ionic/issues/5052 the same thing you are looking for?

**Comment by danbucholtz** [comment]
Yes.  That is perfect.

**Comment by brandyscarney** [comment]
Ok thanks! I am going to close this issue then. :smile:

**Comment by sebrojas14** [comment]
What about iOS?
