### ISSUE TITLE
Testing support in ionic2-app-base

### ISSUE THREAD

**Issue by BugsBunnyBR** [driftyco/ionic#5579]
#### Short description of the problem:

the project ionic2-app-base does not provide a easy way to create tests for the project.
#### What behavior are you expecting?

I would like to have an easy way to integrate tests to my project.

**Ionic Version**:  2.x

@lathonez and I would like to add support to testing in ionic2-app-base, he already got ionic2 projects with tests in his [clicker](https://github.com/lathonez/clicker) repo, so we are willing to integrate this to the app-base, ideally having a unified build process for testing and development.
We also would like to hear about ideias e patterns the community/Ionic team would suggest.

**Comment by lathonez** [comment]
At this point some action is better than none. There's certainly a better way of testing than what I've implemented in [Clicker](https://github.com/lathonez/clicker), but if we have a starting point we can evolve it with the community as the framework grows.

We've [forked the base app](https://github.com/BugsBunnyBR/ionic2-app-base) and are going to put some work into getting the testing set up there.

see also https://github.com/driftyco/ionic/issues/5331

**Comment by tlancina** [comment]
Thanks guys! Really appreciate the discussion going on in https://github.com/driftyco/ionic/issues/5331.  Just to give you a heads up, we will be pulling much of the build out into a gulpfile, which should give more granular control of the various tasks, and would also allow the easy addition of testing tasks.  Also just a warning we may be moving off of webpack!

The starters are going through quite a few changes at the moment, so I can't give testing much attention at this exact moment, but a PR would be absolutely huge and I think a great starting point for discussion/getting things up and running in practice.  Instead of app-base, the [conference app](https://github.com/driftyco/ionic-conference-app) 
may be easier since it's already a fully fledged app and doesn't require copying any templates.  If it's rough no worries, we can iterate as we find better solutions.

Pattern-wise I think having the tests be alongside the components they are describing is what we have seen as the standard, other than that I'm not aware of any strongly held conventions.  Please ping me if you have any build questions/issues, thanks!

**Comment by BugsBunnyBR** [comment]
Thank you @tlancina for this huge heads up!

gulpfile ftw! This will save us a lot of trouble trying to make a test webpack file.

We can add testing to the conference app, but to make testing really easier to integrate in a ionic2 project or to new ionic2 projects, app-base seems to be the right place.
Our plan, at the moment, is to fork app-base and add testing support to the typescript branch with lint optional. All documented.

We are going with tests alongside with components.

If the ionic team thinks that keep a typescript branch without testing is something desirable...
One thing I think could be done is to have the support in ionic-cli, something like `ionic start project --v2 --ts --test`, the `--test` would trigger the download of a specific branch with testing enabled.

**Comment by tlancina** [comment]
@BugsBunnyBR I had the same thought regarding a flag as well, only because of the additional install time necessary for the various testing related packages, which may not always be desirable.

I think tests are a good default, I just want to make sure things are as easy and flexible as possible.  One idea we've toyed around with is allowing the start command to ask a series of questions regarding project setup - by default we download what we think to be the best presets, but if you are a power user you could specify things like which bundler to use, TypeScript vs. JavaScript, tests, etc (similar to yeoman).  For now, I don't think we need to worry about it, but definitely something to think about going forward.

Also regarding the conference app vs. app-base, they get updated at the same time, I just find developing against the conference app to be easier.

**Comment by BugsBunnyBR** [comment]
@tlancina , if tests are a good default, the additional install time seems to pay off.
but, well...
So, how about that. We would make PRs to app-base (in a given branch) and apply the diff in conference-app typescript branch files.
- Keeping test support in a given app-base branch would make ionic team worry free and the app-base would continue clean. When/if the ionic-cli become able to read the `--test` the work would be just swap branchs...
- Applying the diff into conference-app would give a public test case to the testing support.


ncina

**Comment by lathonez** [comment]
@tlancina really helpful advice particularly re gulp vs webpack, thanks for your time on this.

**Comment by ciekawy** [comment]
As the discussion and existing initiatives concern unit testing in general I wonder if there are any concepts or places to look for e2e ideas for Ionic 2?

**Comment by lathonez** [comment]
https://github.com/BugsBunnyBR/ionic2-app-base/issues/4

**Comment by BugsBunnyBR** [comment]
https://forum.ionicframework.com/t/attention-upcoming-ionic-2-starter-changes/45058

**Comment by BugsBunnyBR** [comment]
@tlancina : https://github.com/driftyco/ionic-conference-app/pull/168 , please, take a look, some feedback would be nice.

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-app-scripts#687
