### ISSUE TITLE
bug: Ionic Serve typescript  Error

### ISSUE THREAD

**Issue by kuntal-b** [driftyco/ionic#5593]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Issue describe in bellow forums link

https://forum.ionicframework.com/t/ionic-serve-error/44664</span>

<span is-issue-template></span>

**Comment by tlancina** [comment]
Thanks for the issue, I missed one of the types last night, fixed in https://github.com/driftyco/ionic2-starter-sidemenu/commit/4d727cbb8bfaf682a70fa5f374ba65e7b2cc4b52.

The animation type errors have been fixed in https://github.com/driftyco/ionic/commit/be95ac6490a378c585655b3c76d8d432d8115f79 (see https://github.com/driftyco/ionic/issues/5581).

Going to close as the first one has been fixed, and the #5581 is tracking the other ones.
