### ISSUE TITLE
defaulttimeout value too low?

### ISSUE THREAD

**Issue by Freundschaft** [driftyco/ionic#5610]
I am wondering why the value of defaulttimeout is set to a low value at https://github.com/driftyco/ionic/blob/e49818a4a978a67207c223a965fafc4251a08966/js/angular/service/viewSwitcher.js#L34
it causes the animation to cancel and jump directly to the end, which looks rather choppy. Is there any reason why the variable  is not set to a higher value? I have set it manually to 5000 and animations looks smooth for me now.

**Comment by jgw96** [comment]
Thanks for submitting this issue! Since this issue is more of a question and not really a bug you will get a better, faster answer over on our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Please feel free to ask this question through one of those channels. Thanks again!
