### ISSUE TITLE
$ionicModal missing backdrop

### ISSUE THREAD

**Issue by Tobiaswk** [driftyco/ionic#5628]
#### Short description of the problem:
ionicModal is missing backdrop when shown in portrait mode. When phone is in landscape the backdrop is shown.
After some investigation it seems the problem is related to the resolution and more specifically the width of the screen. 
http://codepen.io/SashaGeekette/pen/vOzryE
Try changing the resolution width to 1000px in inspector mode with Chrome. The backdrop is suddenly missing. Then set the width to 1150 and the backdrop appears again. 

#### What behavior are you expecting?
The backdrop should be show in portrait orientation.

**Steps to reproduce:**
1. Phone in portrait mode
2. Backdrop does not appear when modal is shown

**Ionic Version**: 1.2.4 (although this appears in 1.x versions as well) 

**Browser & Operating System**: iOS / Android / Chrome

**Comment by darshanrampatel** [comment]
We noticed this too, and added the below CSS class (taken from the original modal CSS) to resolve:

```
@media screen {
    .modal-backdrop-bg {
    -webkit-transition: opacity 300ms ease-in-out;
    transition: opacity 300ms ease-in-out;
    background-color: #000;
    opacity: 0; }
  .active .modal-backdrop-bg {
    opacity: 0.5; }
}
```

The reason is that the .modal-backdrop.bg only is applied when the width is 680px or larger; see lines [5296](https://github.com/driftyco/ionic/blob/master/release/css/ionic.css#L5296) and [5322](https://github.com/driftyco/ionic/blob/master/release/css/ionic.css#L5322) of [ionic.css](https://github.com/driftyco/ionic/blob/master/release/css/ionic.css).

**Comment by Tobiaswk** [comment]
Thank you for the feedback! Good to know!

I would still classify this as a bug.

**Comment by Tobiaswk** [comment]
bump

**Comment by jgw96** [comment]
Hello @Tobiaswk ! Thanks for opening an issue with us! So I was testing with your codepen and im having a hard time understanding what the issue is exactly. Our modal will not slide up all the way on a bigger device and will also have a backdrop. On a 7 inch tablet like a nexus 7 the modal shows up like a native android modal looks. On smaller devices, like most phones in portrait mode, the modal takes on more of an ios character in the fact that it slides all the way up from the bottom to the top of the screen, this is why no backdrop class is added then, because the modal takes up the whole screen. If im misunderstanding the issue please tell me. Thanks again!

**Comment by Tobiaswk** [comment]
@jgw96 I did not know that this behavior was intended. This issue can be closed.
