### ISSUE TITLE
bug: stacked ion-select styling

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#5715]
#### Short description of the problem:
The styling for an ion-select component with a stacked label is not correct.

#### What behavior are you expecting?
The select should fill the entire width of the available space. 

**Steps to reproduce:**
See screenshot:
![capture](https://cloud.githubusercontent.com/assets/2852839/13529304/32e54474-e224-11e5-8521-c8181324d9a7.PNG)

```
                    <ion-item>
                        <ion-label stacked>Select your University</ion-label>
                        <ion-select [(ngModel)]="university">
                            <ion-option value="tuks">Tuks</ion-option>
                            <ion-option value="wits">Wits</ion-option>
                            <ion-option value="uj">University of Johannesburg</ion-option>
                        </ion-select>
                    </ion-item>
```

**Ionic Version**: 2.x

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed in the next release. Note that the label colors are different for select right now and this is something that will be fixed in #5669

![screen shot 2016-03-09 at 3 49 18 pm](https://cloud.githubusercontent.com/assets/6577830/13650982/358b770a-e613-11e5-8d69-824e055633bf.png)

Note: floating labels on top of a select will currently work as stacked labels.
