### ISSUE TITLE
No way to disable caching of tabs

### ISSUE THREAD

**Issue by palidanx** [driftyco/ionic#5805]
#### Short description of the problem:
After you run the tabs tutorial `ionic starts projectName tabs --v2`, there is no way to disable the cache in between the tabs.  What happens is when each tab is clicked, it is cached and added to the DOM.  This is problematic on tabs that dynamically request new data when clicked.

#### What behavior are you expecting?
If caching is disable between the tabs, the expectation is that the code would fire every time a tab is clicked.

**Steps to reproduce:**
1. Install a v2 project
2. Click on the home tab button
3. Click on the chats tab button
4. Click on the home tab button
5. Click the chats tab button

Observe that when you click on the home button, and if you add logging on the constructor, there is no indication that the chats button ever loads again.  This is a problem if there is new data on the chats page.

**Which Ionic Version?** 1.x or 2.x
```
v2
```

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v5.4.1
```

**Comment by dylanvdmerwe** [comment]
This probably should be documented better. 

```
export class Page1 {
 constructor() {
   
 }
 **onPageWillEnter**(){
   console.log('page entered');
 }
}
```

**Comment by palidanx** [comment]
Ah thanks!  Just if anyone else is having the problem, to reload data on any give page

```
onPageWillEnter(){
   		console.log('****on page will enter messages pane');
   		this.messagesData.index().subscribe(
			returnedData=>{this.messages = returnedData.global_messages;
		});
 	}
```

Maybe we can add documentation on the Tabs page to link to this Page lifecycle events?

**Comment by shamank** [comment]
Though this is a way to refresh the "cached" page, it is still there in the background and turning the device more and more slow every time you change and load a new page inside. I'm here because I'm on this situation with my app and I need to remove this behaviour because with 7 tabs loading remote content (a list of news, translated to cards with images and buttons), the app gets completly slow, to the point of stop working because ran out of memory (Nexus 5 / iPhone 5s). I've tried to remove the last used page from DOM but tabs got broken.

Any workaround for this, please? Thank you.

**Comment by tanogalego** [comment]
Having same issue here. @shamank did you found any solution? Any way to remove the hidden tab content from the DOM when no active? Thanks!

**Comment by shamank** [comment]
Sorry man, I've never found a practical way to achieve this and desisted. I
don't know if there's a way now since it's not a beta anymore. Please let
me know if you found a way. Thanks!
