### ISSUE TITLE
ion-searchbar [placeholder] throws error when its more than 1 word

### ISSUE THREAD

**Issue by AdrianTeh** [driftyco/ionic#5849]
ion-searchbar [placeholder] input throws error when string consist of more than 1 word.

**Steps to reproduce:**
```
<ion-searchbar [(ngModel)]="searchQuery" [debounce]="500" [placeholder]="Search Question" (input)="search($event)" (cancel)="cancel($event)" (clear)="cancel($event)"></ion-searchbar>

[placeholder]="Search" # => works
[placeholder]="Search Question" # => doesn't work
```

Here's a screenshot of the error i am getting:
![developer tools - http localhost 8100 2016-03-15 11-08-22](https://cloud.githubusercontent.com/assets/161221/13782653/59a47cce-ea9e-11e5-97b3-59ece610b074.png)

Running on:
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by brandyscarney** [comment]
It is because you are wrapping `placeholder` in brackets like `[placeholder]`. Angular is looking at `Search Question` for an expression. It should be written: 

`<ion-searchbar placeholder="Search Question">`

From the angular [docs](https://angular.io/docs/ts/latest/guide/cheatsheet.html):

`<input [value]="firstName">`	
Binds property `value` to the result of expression `firstName`.

Thanks for the issue!

**Comment by AdrianTeh** [comment]
@brandyscarney Thanks for the clarification. I think this should be clearly stated in the docs http://ionicframework.com/docs/v2/api/components/searchbar/Searchbar/
