### ISSUE TITLE
performance : Ionic 2 - Tab page navigation

### ISSUE THREAD

**Issue by santhoshi272** [driftyco/ionic#5871]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>while navigating from tabs page from the tab pages list the tab-bar is present there  only...</span>

**Comment by jgw96** [comment]
Thanks for opening this issue with us, we just need a little more information from you so that we can better help you with this issue. Would you be able to provide a plunkr, codepen or repo that we could use to repro this issue? Also would you mind running `ionic info` and posting the output here? Thanks again!

**Comment by adamdbradley** [comment]
Sorry but we'll need more information to be able to help look into this issue. Please feel free to open another issue if you're still having issues, thanks

**Comment by JosephMendez** [comment]
how can i setup ion-navs and ion-tabs, together?
