### ISSUE TITLE
Android title offset

### ISSUE THREAD

**Issue by BugsBunnyBR** [driftyco/ionic#5923]
#### Short description of the problem:
The title in a navbar shifts too much to the right when the back arrow is being displayed.

#### What behavior are you expecting?
To show the app icon in the empty space or to the empty space not to exist.

**Steps to reproduce:**
1. Download conference-app
2. Run on Android
3. Open a details page

```
**Which Ionic Version?** 2 beta 3

**Comment by jgw96** [comment]
I can confirm this issue 
![screenshot_20160323-113302](https://cloud.githubusercontent.com/assets/8823093/13992742/46cf242a-f0eb-11e5-9a05-f4af10c4e731.png)

**Comment by brandyscarney** [comment]
Confirmed,

![screen shot 2016-03-23 at 12 40 03 pm](https://cloud.githubusercontent.com/assets/6577830/13993012/cead5d54-f0f4-11e5-9add-e17f7461fd92.png)
![screen shot 2016-03-23 at 12 40 10 pm](https://cloud.githubusercontent.com/assets/6577830/13993014/d00731d4-f0f4-11e5-9510-ab321e60054c.png)

**Comment by brandyscarney** [comment]
Thanks for the issue! This was a problem in windows mode, as well. Both will be fixed in the next release `beta.4`:

Material Design:
![title](https://cloud.githubusercontent.com/assets/6577830/13994605/fb15f520-f0fb-11e5-9ca6-8d1c67347f19.png)

Windows:
![titlewp](https://cloud.githubusercontent.com/assets/6577830/13994604/fb13b116-f0fb-11e5-90a4-899b130cea76.png)
