### ISSUE TITLE
[Enhancement] Pass data when selecting another tab

### ISSUE THREAD

**Issue by ZiFFeL1992** [driftyco/ionic#5966]
#### Short description of the problem:

Will be awesome to allow passing parameters on tabs.select(index, params) like in push/pop methods.
#### What behavior are you expecting?

Be able to pass data to another tab using tabs.select(index, params) method. 

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by sijad** [comment]
I also need this.

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#26

**Comment by roydekleijn** [comment]
What is the current state? Because above url doesn't work...
