### ISSUE TITLE
Searchbar slow with 500+ items

### ISSUE THREAD

**Issue by susanlinsfu** [driftyco/ionic#5975]
I have tested with 500-2000 items (length on average of 40 characters) . To search for an item is VERY slow . It seems to take about 5 seconds on a low wend android device to see the character show up, then another 10 seconds for the result to filter based on the criteria. 1000 items is not that much, could this be improved? My code I tested from is from: https://github.com/driftyco/ionic-preview-app/tree/master/app/pages/searchbars/basic

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better discussion started there, which if its then decided its a bug could be moved back here. (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
