### ISSUE TITLE
docs: 

### ISSUE THREAD

**Issue by Rohit3230** [driftyco/ionic#5976]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description></span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by vhoxha08** [comment]
Perhaps he's trying to point out that docs for v1 are missing specifically changes made in v1.2.
At least they are not listed in the focs navigation menu.

**Comment by jgw96** [comment]
Hello! @vhoxha08 Would you mind opening a separate issue with all the docs your having a problem finding? I would love to help you with this!
