### ISSUE TITLE
bug: Installing Tutorial for Typescript

### ISSUE THREAD

**Issue by scastaldi** [driftyco/ionic#6015]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When running: $ ionic start MyIonic2Project tutorial --ts I get this error...

Downloading: https://github.com/driftyco/ionic-starter-tutorial/archive/master.zip
 ✗ Not found: https://github.com/driftyco/ionic-starter-tutorial/archive/master.zip (404)
 ✗ Please verify the url and try again.
Please verify you are using a valid URL or a valid ionic starter.</span>

<span is-issue-template></span>

**Comment by scastaldi** [comment]
Actually I just noticed the issue is the template, if I do the same command without tutorial, it works fine...

$ ionic start MyIonic2Project --ts

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Im pretty sure this issue is related to you not passing the --v2 flag to ionic start. With your current ionic start command the ionic cli is going to try to generate an Ionic 1 project but with a typescript starter, which is not valid as currently we only have ionic 2 typescript starters. To generate a v2 project with a typescript starter first make sure you have ionic@beta installed (`npm install -g ionic@beta`, you may have to add sudo up front if your on osx or linux) and then run ionic start like so, `ionic start MyIonic2Project tutorial --v2 --ts` . This will give you a ionic 2 project with typescript.

**Comment by scastaldi** [comment]
great thank you!

**Comment by jgw96** [comment]
@scastaldi No problem at all! Thanks for using ionic!
