### ISSUE TITLE
Zone.js issues with old and outdated dependency versions

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#6020]
#### Short description of the problem:
I am having issues when using FileReader in the current version of Ionic2. The FileReader's events are not firing due to a known zone.js (and long ago fixed) issue. Not specifically a problem with Ionic, but this issue serves as a strong enforcement to ensure each and future release beta of Ionic runs the latest Angular and zone.js packages. 

See [here ](https://github.com/angular/zone.js/pull/178), [here ](https://github.com/angular/zone.js/pull/174)and [here ](https://github.com/Microsoft/cordova-plugin-code-push/issues/86)for a reference on the problem. 

I would like clarification on why the Ionic 2 project is so drastically behind on Angular2 releases. I heard there were some issues in upgrading, but this should form a part of each and every beta and future release to keep up to date to ensure Angular2 framework bugs are resolved and ruled out. 

**Which Ionic Version?** 2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.0 (cordova-lib@undefined)
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
OS:
Node Version: v5.9.1

**Comment by dylanvdmerwe** [comment]
As of today latest versions are:
> "angular2": 2.0.0-beta.13
> "es6-shim": "^0.35.0",
> "reflect-metadata": "0.1.2",
> "rxjs": "5.0.0-beta.2",
> "zone.js": "^0.6.6"

Whereas ionic 2 beta 3 is on:
>     "angular2": "2.0.0-beta.6",
>     "es6-shim": "0.33.13",
>     "reflect-metadata": "0.1.2",
>     "rxjs": "5.0.0-beta.0",
>     "zone.js": "0.5.14"

:-1:

**Comment by adamdbradley** [comment]
Our releases have used versions which have sheltered devs from ng2 bugs that would not allow them to develop. Prior to our beta3 release, the latest angular version were not recommended to upgrade to by the angular team. The large refactor of zone.js introduced a few bugs into ng2, which is why we have held off. Additionally, there are any not significant differences between the ng2 betas that warrant every developer to deal with temporary bugs in their building process.

The next ionic release will upgrade to the latest versions that we have fully tested and considered stable for developers. Thanks
