### ISSUE TITLE
what the correct way to use type: date in my ionic apphello

### ISSUE THREAD

**Issue by ivanssa** [driftyco/ionic#6030]
I created an app in ionic and added a type field = date and I can call the native version of datepicker in ios iphone but not all versions of android works which ends up leaving the free text field to incorrect user typing, so I would whether there is a way to check if you have native datepiker or force open the datepicker in all versions or if the ideal is to include some datepiker plugin in my app and if so someone has algima suggestions?

**Comment by jgw96** [comment]
Hello! Thanks for opening this issue with us! So, im guessing that your having issues with the datepicker on older android devices, most likely Android 4.3 and back, would that be correct? There are a things i can recommend to solve this. First of all, if your supporting older Android devices i would recommend using crosswalk. This will give you consistent html5 support and performance across all android devices. To set up your ionic project to use crosswalk you can run `ionic browser add crosswalk`. Android devices on 4.3 and back do not support the html5 date input. Another option is to use the cordova-datepicker plugin (https://github.com/VitaliiBlagodir/cordova-plugin-datepicker). This will give you access to the native datepicker in ios and android. If you decide to use the native datepicker instead of the html5 datepicker i would still recommend using crosswalk if your supporting older android devices. Hopefully this helps you! Thanks again!

**Comment by jgw96** [comment]
Im gonna go ahead and close this issue as i believe my solution above should work, if not please feel free to respond back!

**Comment by ivanssa** [comment]
Hello thank you, really the two solutions worked, I cool the crosswalk solution but because of increasing the size of my app in more than 10mb I opted for cord-plugin-datepicker plugin, which worked on android older devices thanks ...

**Comment by jgw96** [comment]
@ivanssa Awesome, glad to hear everything is working fine for you now!
