### ISSUE TITLE
V2: ionic button causes namespace errors, selector is too generic

### ISSUE THREAD

**Issue by bvkimball** [driftyco/ionic#6061]
#### Short description of the problem:

We maintain a internal NG2 Component library we were trying to use in conjunction with Ionic. We also hang a component off the `button` element.  we use:

```
selector: button[theme]
```

So we get a conflict that button is trying to use 2 components definitions.

#### What behavior are you expecting?

hanging a component off of `button` seem like bad practice, and although we are doing it as well, we are looking for a way to use our Button instead of yours.  There is no easy way to import all of the Ionic components with out the Ionic Button  to use ours instead.  Also it doesn't allow for both Buttons to be used at the same time, because the selector is just `button`.

**Which Ionic Version?** 2.x

**Comment by adamdbradley** [comment]
Using an actual `<button>` is important for accessibility and it keeps it simple. Why can't both directives apply?

**Comment by jgw96** [comment]
Hello! Since it has been a little while since there was any activity on this issue i will be closing it for now. Thanks for using Ionic!

**Comment by Chris-V** [comment]
Hi,

I think this should be reopened. I just stumbled on an issue where my component (`@Component({selector: '[myapp-dosomething]', template: ...})`) would make my app not render at all when applied to a button but not other elements.

It took me a while to realize button is the only Ionic Component without a prefix. In that case I don't need any of Ionic's behavior for my button but I can't prevent it because it targets every single button.

For reference Ionic's selector is: `button:not([ion-item]),[button]`

On the top of my head, I can see two possible way to solve that:

1. Add a prefix to Ionic's button. eg: `ion-button:not([ion-item]),[ion-button]`. The accessibility goal stated previously can be solved by either using the attribute selector (`<button ion-button></button>`) or adding a `role="button"` attribute to the host. _This solution would incur breaking changes because of the rename._

2. Adding a negative attribute selector to prevent Ionic from targeting some buttons, much like it is done to filter out `ion-item`s. eg: `button:not([ion-item]):not([no-ion]),[button]`. _This would not introduce breaking changes_. This doesn't fix the issue of a component targeting possibly unwanted buttons without making it clear though.
