### ISSUE TITLE
bug: Android 4.2.2 Numeric pipe TypeError lenght

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#6075]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>The app works ok with android 5.0 up, but in 4.4.2 the numeric pipe triggers the following error:
```js
TypeError: Cannot redefine property: length
```
</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
@Luchillo Hey! So, i am going to do some device testing to check this, but i bet this is due to an api support issue in android 4.4.2. Have you given crosswalk a try to see if that fixes it? To add crosswalk to your app just run `cordova plugin add cordova-plugin-crosswalk-webview`. Thanks!

**Comment by Luchillo** [comment]
I have had some issues adding crosswalk to the app, however the reason i'm not using it is that the apk size goes from 4 MB to 40 MB or more.

The weird thing is i builded the app and put the code available through an express api, so in chrome mobile browser in same device works ok, it's the webview that uses Cordova that lacks the support for it,  although i thought it used chrome, seems like not.

Also the same pipe had issues with IOS support so i had to use an `intl` polyfill, could it had something to do with this error in android 4.4.x?

**Comment by jgw96** [comment]
@Luchillo Thats exactly the issue. Android devices older than 4.4.4 do not use updated chrome webviews. Therefore thats why we recommend using crosswalk on older android devices as it solves alot of this issue because it gives you a nice modern chrome webview no matter what version of android your device is running on. Im not sure that the internationalization polyfill is gonna do anything here as im not sure that anything other than the date pipe uses that, but may be worth a try. Crosswalk does make your apk's larger, but the performance improvements and html5 support it gives you is pretty awesome.

**Comment by jgw96** [comment]
As it has been a little while since there was any activity on this issue i am going to be closing this issue for now. Thanks for using Ionic!

**Comment by Luchillo** [comment]
@jgw96 I did end up using Crosswalk to support a lot of things, so this can just be fixed by using Crosswalk and in case the pipe still not working in IOS use the `intl` package to polyfill the internationalisation api for the pipe to work.
