### ISSUE TITLE
Collection Repeat copy properties/style from old element to the new upcoming one

### ISSUE THREAD

**Issue by rajendratodkari** [driftyco/ionic#6083]
#### Short description of the problem:
Hi,

I am using collection-repeat in ionic 1.7.14. I have "more actions" icon associated with each list item. If I click on that icon, an overlay comes showing more actions for that item only. Till here so far so good.

Now if I click on more actions icon of an element and then scroll down allowing collection-repeat to insert more list items, the new item replacing the clicked item also have overlay. And this is not for one time. If I keep scrolling down, one element from new list item slots have overlay.

What is the work around??

#### What behavior are you expecting?
The new upcoming elements should not copy style, behavior of old ones

Plunker : http://plnkr.co/edit/ISBIatasUwxULyQPQ26v?p=preview

**Steps to reproduce:**
1. click on "Paint BG" button of first item
2. scroll down 12-15 items
3. you will see around 10th element that background is copied

**Which Ionic Version?** 1.x or 2.x
1.7.14

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/ISBIatasUwxULyQPQ26v?p=preview

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So, the reason collection-repeat is so performant is because it "recycles" elements. This means that whatever you change the style too in the first one is going to change the style in another list item farther down the list (it depends on the height of your viewport how far down the the list is going to recycle). I would recommend using your standard `ng-repeat` if you need to have a different background for only certain items in the list. Thanks again!
