### ISSUE TITLE
Automatic inclusion of page SCSS

### ISSUE THREAD

**Issue by paulhickman-a365** [driftyco/ionic#6090]
Would it be possible for ionic 2 to use the gulpfile to automatically pull in the scss files from the app/pages/** folder hierarchy into app.core.scss to save having to manually update the file each time you add a new page with SCSS?

**Comment by Luchillo** [comment]
This brings 2 considerations, order and performance:

1. Order: If they activate globbing for files they would be imported in uncertain order, this is not a big issue since the ionic generators wrap content with a class with the name of the component, pipe or provider, as good as you use the wrapper class for pages you're all good.
2. Performance: Traversing the file tree in search of any file that match scss ext is costly in comparison of using a well defined path, with globbing node will have to make more operations to find all files accepted by the glob pattern, defining the explicit import for each file allows the scss plugin to know immediately where to grab the file.

I think this should be possible for easy start, but recommend using the explicit import without globbing for big projects, however this needs testing to see if the performance difference is small enough to just use globbing.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1252

**Comment by jgw96** [comment]
Hello all! As this was really an issue related to the cli and not the framework i have move this issue to the appropriate repo. Thanks for using Ionic!
