### ISSUE TITLE
Ionic Reality App

### ISSUE THREAD

**Issue by Code1942** [driftyco/ionic#6106]
I am new to Ionic and started by setting up ionic@beta

The CLI command "$ ionic start cutePuppyPics --v2" followed by "$ ionic serve" works great

Then I downloaded the "https://github.com/ccoenraets/ionic2-realty"

When I run the command "npm install" in the "ionic2-realty" directory, I get warnings related to webpack dependency and fsevents

When I run "ionic serve" I get a blank page

How can I get the reality app to run correctly as shown in the blog

**Comment by thiphariel** [comment]
Hi. It's because in ionic 2 beta 4 (current version), they get ride of webpack. Your project is probably build on top of earlier beta version, so you should start a fresh starter app and edit your package.json for start.

There is also the 'es6-shim' to add in your <code>app.ts</code> imports.

To do well, you should start a new project then add your code into it, it's the better way to avoid problems when there are breaking changes.

**Comment by jgw96** [comment]
@Code1942 Hello!Thanks for opening an issue with us! So we recently made changes to our build process for Ionic 2. I would recommend (until the owner of that demo upgrades the app to beta.4) to start a new app, and then just move his code over into your freshly started app. The build process should work fine once you do that! Thanks again!
