### ISSUE TITLE
 Uncaught ReferenceError: ionic is not defined, http://localhost:8100/?ionicplatform=ios, Line: 85

### ISSUE THREAD

**Issue by JosephMendez** [driftyco/ionic#6208]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/jnOrQRtE8rN2WCXDQYQY?p=info

**For Ionic 2 issues** - http://plnkr.co/edit/TW20lftdc5s622pcJPkp?p=info

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by RAMDdFLEET** [comment]
when you are using ionic 2 and ionic cli to test run in your browser, do not use ionic serve --lab, should only use ionic serve. Anyways, you won't see any damage due to that warning. That is actually a problem with Ionic CLI which will be fixed when rolled out.
Workaround: you can type ionic serve -b, wait for Running dev server message and then open it manually: http://localhost:8100/?ionicPlatform=android for platform specific emulation

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this is an issue with the ionic cli and not an issue with the framework i will be moving this issue to that repo. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#942
