### ISSUE TITLE
V2 - Beta 4 - Rapid click on an alert button has no effects

### ISSUE THREAD

**Issue by JumBay** [driftyco/ionic#6224]
#### Short description of the problem:
If an alert popup and you rapidly click on one of its buttons, you will see the button animation as if the click had worked but the events won't fire and it won't close

#### What behavior are you expecting?
Fire button events

**Steps to reproduce:**
1. Go to http://plnkr.co/edit/YsEs0pZyTSdpoBwvO81h?p=preview
2. Click the **Thanks** button
3. Rapidly click to *yes* or *no*, you will see the button animation, but nothing happens

**Which Ionic Version?**  2.x

#### Plunker that shows an example of your issue

http://plnkr.co/edit/YsEs0pZyTSdpoBwvO81h?p=preview
![lunker20160419143937](https://cloud.githubusercontent.com/assets/216573/14627974/eab190d0-063c-11e6-9f19-5f03f8b88341.gif)

**Comment by jgw96** [comment]
Hello! Thanks for opening this issue with us! I was able to confirm this issue and am looking more into it now.

**Comment by jgw96** [comment]
@JumBay Hey, thanks for opening this issue with us. So after looking more into this and discussing with my teammates we have figured out that its due to the transition not being fully done yet until a few ms after the alert appears. If you immediately click a button in the alert when you first see the buttons (but the transition is not done yet) then no events will happen because the transition is still happening. The fix for this would involve cancelling the transition and then immediately reversing it before its even done which actually breaks more things in our NavController and causes more issues. Because of this i will be marking this as a wontfix for now and closing the issue. Please feel free to continue commenting though! Also thanks for using Ionic!

**Comment by JumBay** [comment]
Ok I understand. Hope is gonna be fixed someday

**Comment by djangojack** [comment]
@jgw96 ok, I get that the transition isn't finished.  But what about observing clicks in the region where the buttons will be during the ~300 ms before the animation finishes?
