### ISSUE TITLE
how to import/implement custom nodejs into Ionic 2 node_modules / plugins

### ISSUE THREAD

**Issue by JosephMendez** [driftyco/ionic#6232]
in typescript or javascript:

`var WooCommerceAPI = require('woocommerce-api');
 
var WooCommerce = new WooCommerceAPI({
  url: 'http://example.com',
  consumerKey: 'ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  consumerSecret: 'cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
}); `

https://www.npmjs.com/package/woocommerce-api

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/jnOrQRtE8rN2WCXDQYQY?p=info

**For Ionic 2 issues** - http://plnkr.co/edit/sSFR9jbfTsxgAmrm9hUR?p=info

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind giving us a little more info about the issue you are having? It looks like your wanting to write node.js code but run it in your ionic app, which to my knowledge is impossible. It looks like that library you have there is built for node.js and not front-end javascript. But, i may be confused on what your trying to do exactly (:.

**Comment by JosephMendez** [comment]
Hi @jgw96  so this one is really impossible, anyway i screenshot my implementation?  I thought i could include node.js into ionic app. :)
![woocommerce-api](https://cloud.githubusercontent.com/assets/1498448/14643319/8fa4f526-0680-11e6-9776-4a396926a411.png)
<hr>
![app-js](https://cloud.githubusercontent.com/assets/1498448/14643337/9fbb5144-0680-11e6-83d2-d3908c012ca6.png)
<hr>
![implementation](https://cloud.githubusercontent.com/assets/1498448/14643356/b16ecbd2-0680-11e6-9c4a-9d02a23e62b9.png)

**Comment by jgw96** [comment]
@JosephMendez Ahh, so if you want to just use a standard javascript library (one thats built for the front-end) then you can just use it like you normally would in any javascript/typescript application. Now, if the library your using has been built using es6 modules then you will be able to import from it like you were trying to do above, but this is only if the library has been written to support it. Also, with libraries like this that are using keys i definitely recommend you do this on the server instead of your ionic app as anyone could extract your apk from their android device and potentially be able to view your consumer key and secret, where if its on the server it is basically impossible for them too get ahold of your keys. I am going to be closing this issue now as i believe we have it solved, but feel free to continue the conversation! And thanks for using Ionic!

**Comment by anivaisu** [comment]
I'm working on integrating Woocommerce Rest API with Ionic 2 using this package:

npm install --save woocommerce-api

import * as WooCommerceAPI from 'woocommerce-api';

ionViewDidLoad() {
var WooCommerce = new WooCommerceAPI({
url: 'http://example.com',
consumerKey: 'ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
consumerSecret: 'cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
});
}
I'm getting this error and app stops running.
Error: Cannot find module "../package.json"
Pls Advice me,
Thanks & Regards,
