### ISSUE TITLE
ion-row margin issue with hidden rows

### ISSUE THREAD

**Issue by scunningham777** [driftyco/ionic#6238]
#### Short description of the problem:
This issue is fairly specific: currently ion-row elements [get padding of 5px](https://github.com/driftyco/ionic/blob/2.0/ionic/components/grid/grid.scss#L52), but to avoid double-padding between successive rows, [there is a style rule](https://github.com/driftyco/ionic/blob/2.0/ionic/components/grid/grid.scss#L85) set up to add `margin-top: -5px` for every row after the first, which will essentially cancel out the padding on the top of the successive elements.

However, if the first ion-row element is hidden (eg, using the HideWhen directive), the `ion-row + ion-row` selector will still take effect for the first visible ion-row, giving it a negative top-margin and causing it to overlap with the element above it (the padding overlaps anyway).

#### What behavior are you expecting?
The first visible ion-row element should not have negative margins that cancel out it's padding.

##### Potential 'gotcha'
It would seem easy to solve the problem by changing the selector cited above to `ion-row:not([hidden]) + ion-row`, but then if any intermediary rows are hidden, the following row _should_ have a negative top-margin, but it wouldn't match this new selector, so it would end up with double padding.

**Which Ionic Version?** 2.0.0 beta4

#### Plunker that shows an example of your issue

http://plnkr.co/edit/ldEYe1

(remove the `hideWhen="core"` directives in home.html to see the "desired" state)

**Comment by brandyscarney** [comment]
Thanks for the issue! So there are a few ways we can go about this. We could remove the padding top/bottom in favor of using margin, which would solve this, remove the negative margin rule entirely or remove both the padding and negative margin.

I personally don't like adding the padding to the rows or columns, and think this should be up to the user to style. Thoughts @adamdbradley?

**Comment by brandyscarney** [comment]
I deleted my previous comment after discussing this with Adam. The padding between the cols was set up so that the spacing between each column would be equal, including the spacing between the container and the columns. After looking into this more, I decided to add an `ion-grid` wrapper element that will add the padding so the columns will be evenly spaced. The `ion-row` element no longer has padding or negative margin. Here's a picture for an idea of how the spacing works, where the yellow is the `ion-grid`, the pink is the `ion-row`, and the blue is the `ion-col`:

![screen shot 2016-04-26 at 12 57 28 pm](https://cloud.githubusercontent.com/assets/6577830/14828331/8fa5d2a0-0bb4-11e6-8f1e-f8a96cb8c541.png)

And here is a screenshot showing that the spacing is still even:

![screen shot 2016-04-26 at 12 58 33 pm](https://cloud.githubusercontent.com/assets/6577830/14828332/8fabe33e-0bb4-11e6-9a72-ce30ec7c1b09.png)
 
I released a nightly version of the framework that can be used to test this. If you try it out, please let me know of any feedback. Thanks! :smile:

Installing the nightly: `npm install ionic-angular@nightly --save`
