### ISSUE TITLE
bug(infinitescroll): ion-infinite-scroll-content flickering

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#6240]
#### Short description of the problem:

When scrolling an `ion-list` that has an `ion-infinite-scroll` the content flickers at the bottom of the list even though no network calls are occurring. 

![animation](https://cloud.githubusercontent.com/assets/2852839/14666557/74d36a7a-06da-11e6-8b9c-9dec86ab1576.gif)

Plunkr to reproduce: http://plnkr.co/edit/2MdqFCDFXawwG0c1A5CS?p=preview

**Which Ionic Version?** 2.x

Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.4-201604170622
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v5.7.0

**Comment by naveedahmed1** [comment]
In RC 3 I was able to get rid of it with crosswalk but with RC 4 screen flickers even with crosswalk. Testing it on Nexus 6P Android 7.1.1

**Comment by jgw96** [comment]
Hey @dylanvdmerwe and @naveedahmed1 ! Good news, i figured out what the issue was. I made a plunker [here](http://plnkr.co/edit/wH1EO6ZrFecIuDWMZfmy?p=preview) based off of dylans plunker that shows the proper way to do this and get rid of the flashing infinitescroll at the end of a list. So the key is this line `infiniteScroll.enable(false);` which I call after there are no more pictures to load into the list. You can read about the `enable` method [here](http://ionicframework.com/docs/v2/api/components/infinite-scroll/InfiniteScroll/#enable) in our docs. When passing it false it tells the infinitescroll to not listen to scroll events anymore so that it is not enabling every time you barely scroll when the list is done. Could you guys give that shot and let me know how it works for you? Thanks!

**Comment by jgw96** [comment]
Hello all! I am going to close this issue as using the `enable()` method fixes this issue. We are tracking other flicker issues with infiniteScroll here https://github.com/driftyco/ionic/issues/9295 . Thanks for using Ionic!

**Comment by naveedahmed1** [comment]
In my case I already had this [enabled]="canLoadMore", I set canLoadMore to false when there are no more items. The issue arises when using it with VirtualScroll which randomly show/hides images and list items on scroll. I emailed you a sample few days back.

**Comment by dylanvdmerwe** [comment]
I think the debounce time for the event to fire should be increased to about `150ms`. Thoughts @jgw96 ?
