### ISSUE TITLE
Feature request: Add component for Material Design's Persistent Bottom Sheets

### ISSUE THREAD

**Issue by jabas06** [driftyco/ionic#6245]
It would be nice to have Persistent Bottom Sheets in Ionic 2. 

Persistent bottom sheets display in-app content that supplements the main view.

https://www.google.com/design/spec/components/bottom-sheets.html#bottom-sheets-persistent-bottom-sheets.

**Comment by dylanvdmerwe** [comment]
Can't this be done with a customised [toolbar](http://ionicframework.com/docs/v2/components/#toolbar)?

**Comment by jgw96** [comment]
@dylanvdmerwe Theres a couple of ways this could be done that i can think of. Might be a good issue for a community contributor (;

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#29
