### ISSUE TITLE
Don't execute function in component/app.js v2

### ISSUE THREAD

**Issue by Tubishi** [driftyco/ionic#6282]
Hi,

You add a function for the backbutton 
```
platform.backButton.subscribe(function () {
            var activeNav = _this.getActiveNav();
            if (activeNav) {
                if (activeNav.length() === 1) {
                    platform.exitApp();
                }
                else {
                    activeNav.pop();
                }
            }
        });
```
But i would like to execute my own code if activeNav.lenght === 1, to do that i comment the code in app.js, and i execute my code in my file, it works. 

But when i will do npm install, it will change your app.js, so do you think there is a better solution to do that ? 

Thank you

Ionic v2

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.04 
Node Version: v4.0.0

**Comment by zengchuan** [comment]
how to override platform.backButton.subscribe in my app.js?

**Comment by Tubishi** [comment]
Take the same code in your file, me i execute it in app.ts, and comment` platform.exitApp(); `and `activeNav.pop();` in app.js.
Be careful, if you reload the node_module folder, you have to comment again this lines.

**Comment by zengchuan** [comment]
I hava master--detail page. In my detail page I hava a ad like admob. When I click into ad and click buckbutton in android, the page go back to master not detail page. How to rewrite platform.backButton.subscribe?

**Comment by jgw96** [comment]
@zengchuan thanks for opening an issue with us! So at this point there's no plans to allow users to customize what happens when there hardware back button is pressrd. We realize that this potentially could be a limitation, although with most native mobile apps the back button almost always has the same functionality. I would recommend to just keep overwriting the functionality like you currently do, but just be aware it could potentially cause bugs. Thank you for using Ionic !
