### ISSUE TITLE
ionic v2 - menu freeze

### ISSUE THREAD

**Issue by mola10** [driftyco/ionic#6298]
Sometimes standart ion-menu just freeze in the open state and stops answering on user interactions.
It's can be reproduced if user nonstop open\close menu during 15-20 sec with swipe.

```
<ion-menu [content]="content" class="left-menu">
    <ion-toolbar>
        <div class="user-block"></div>
        <button class="icon-left ion-chevron-left menu-close" menuToggle>x</button>
    </ion-toolbar>
    <ion-content>
        <div class="left-menu"></div>
    </ion-content>
</ion-menu>
```

platform: android
ionic-framework: "2.0.0-beta.17"
angular2: "2.0.0-beta.0"

**Comment by iignatov** [comment]
@mola10 Could you please run `ionic info` from inside of projects' folder and then paste the output here?

**Comment by mola10** [comment]
@iignatov sure

```
Your system information:

Cordova CLI: 6.1.0 (cordova-lib@undefined)
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.49
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS:
Node Version: v4.2.4

```

**Comment by iignatov** [comment]
@mola10 It seems that you're using an older version of the framework and the problem that you're observing might be fixed in the meantime. Could you please [update your project to the latest version](https://forum.ionicframework.com/t/ionic-2-projects-updating-to-beta-6/50049) _(following the instructions in the linked post)_ and see if it solves the problem. Thanks!

**Comment by jgw96** [comment]
@mola10 Thanks for opening this issue with us! Since it has been a while since there was any activity on this post i am going to close it for now, but feel free to comment and ill reopen (: Thanks for using ionic!
