### ISSUE TITLE
Refresh data in Modal

### ISSUE THREAD

**Issue by johnmara** [driftyco/ionic#6332]
I have created an ion-modal which contains some replies. The user has the option to add a reply and send it to the server.
I want the $scope.replies to be updated with the new reply. 
```
newReply.$save(newReply, function(data){
      $scope.refreshData();

    }, function(error){
           //code
      }
    })
```
refreshData() actually works and when I close the modal and open it again I can see the new reply.
But I want it to be done automatically. Also <ion-refresher> doesn't update the data.
Any help?

**Comment by danbucholtz** [comment]
Hi @johnmara,

We have an Ionic [community/forum](https://forum.ionicframework.com/?utm_source=framework&utm_medium=navbar&utm_campaign=forum%20CTA) where people can ask for help.  Please ask your question there.  I am going to close this issue since it's a question, not necessarily an issue.  Please let me know if I am mistaken.

Thanks,
Dan
