### ISSUE TITLE
Slides: Flip effect doesn't work

### ISSUE THREAD

**Issue by panuganti** [driftyco/ionic#6344]
#### Short description of the problem:

I'm trying to use the 'flip' effect for the slides as described here in Swiper API.
http://idangero.us/swiper/api/#.VyDXNfkrKM8

Rest of the effects (fade, cube etc.) work fine. However, when I use 'flip', I see only the 'slide' behavior

#### What behavior are you expecting?
I'm expecting a 'flip' transition.

```
    options: any = {
        direction: "vertical",
        effect: 'flip',
         keyboardControl: true,
        mousewheelControl: true,
        onlyExternal: false,
        onInit: (slides: any) => { this.swiper = slides; this.refresh(); },
        onSlideChangeStart: (slides: any) => { this.slideChanged(); },
    };
```

**Which Ionic Version?** 1.x or 2.x
2.xxx.beta.6

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.3.2

**Comment by jgw96** [comment]
Hello @panuganti ! Thanks for opening an issue with us! So we currently do not support all the different slide attributes that the swiper api provides (although were looking into changing that when this issue is worked on: https://github.com/driftyco/ionic/issues/6198). I will close this issue for now, but keep a look out for updates to the slides to come in future releases (:
