### ISSUE TITLE
Need to limit Page History

### ISSUE THREAD

**Issue by RanjitReddy** [driftyco/ionic#6393]
I want to limit History Pages in ionic App. I mean backbuton should take limit(eg: 3 pages) pages only when I click back whuch will take to menu button after 3 history pages in Android ionic Mobile App.

**Comment by jgw96** [comment]
Hello @RanjitReddy ! Thanks for opening an issue with us! Since this issue is more of a question on how to implement certain functionality and not an issue with the ionic framework i am going to close this issue and ask that you ask this question on our forum (forum.ionicframework.com). Thanks again! There are a ton of awesome devs on the ionic forum that will be able to help you implement this.
