### ISSUE TITLE
bug: ionic login - Error  (1.7.14)

### ISSUE THREAD

**Issue by Rabbitholes** [driftyco/ionic#6415]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have seen a lot of "login" error issues, but nothing recent on this list. On the npm ionic 1.7.14 while running the "ionic login" command I was unable to login while my password while it had special characters in it. I'm assuming that the http request under the covers is encoding them making the password invalid on the other side. Once I removed special characters I was logged right in.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hey @Rabbitholes ! Thanks for opening an issue with us. So yeah, with the current beta version of the cli, beta.25, there is an issue with `ionic login` where it reports that the login failed when actually it logged in successfully. This has already been fixed in the repo and is scheduled to make it in the next beta cli release. Would you mind opening an issue on the the ionic-cli repo:https://github.com/driftyco/ionic-cli for the special characters bug? Im gonna go ahead and close this issue, as this repo is for the ionic framework and not the cli, but as i said feel free to open up an issue on the cli repo for the login bug you found. Thanks for using Ionic!

**Comment by Rabbitholes** [comment]
Sounds good. I see this wasn't the right place, but thanks for responding and taking care of it!

**Comment by jgw96** [comment]
No problem at all!
