### ISSUE TITLE
bug: npm install error in Node 6.0.0

### ISSUE THREAD

**Issue by macsermkiat** [driftyco/ionic#6420]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>When try to install npm ionic cordova on Node 6.0 running Windows10, it returned an error issue from Node-sass.
I also found that people have an error while installing node-sass 3.6.0 on Node 6.0 too, but they just released an update to 3.7.0 to correct the problems.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us! We are currently working on Node v6 support for our Ionic cli which will fix issues such as these. You can follow our progress on that here: https://github.com/driftyco/ionic-cli/issues/960 . Would you mind putting info about the issue you are having on that issue? Since we are tracking the node 6 compatibility issues on the issue linked i will go ahead and close this issue. Thanks for using Ionic!
