### ISSUE TITLE
Reload breaks tab navigation

### ISSUE THREAD

**Issue by jakob-e** [driftyco/ionic#6427]
**Problem**
Reload breaks tab navigation – if exit page is not the start tab page 

**Expected**
The sub tab page is expected to load (works)
Clicking the tab icon should route to the start tab page (fails).

**Steps to reproduce:**
1.  Open the codepen tab example in debug mode: http://s.codepen.io/ionic/debug/odqCz
2.  Click the About tab
3.  Click the Tab Nav Stack button 
4.  Reload the page
5.  The first page of About is now no longer accessible

**Comment by danbucholtz** [comment]
Hi @jakob-e,

This sort of issue is due to ui-router.  Unfortunately, we aren't making changes to this sort of functionality in V1 at this time unless enough of the community gets behind it.  We're sorry about that.  It's just too risky.  Almost all of this type of issue will be resolved in V2's navigation.

Thanks again for contributing and I'm happy to hear your thoughts on the subject.

Thanks,
Dan
