### ISSUE TITLE
Closing Modal in onPageLoaded() of a Page will 'dismiss' that page.

### ISSUE THREAD

**Issue by khanhlu2013** [driftyco/ionic#6453]
#### Short description of the problem:
When NavController present a modal M  on a page P's onPageLoaded() function, closing M will not only dismiss M but also "dismiss" P

#### What behavior are you expecting?
Closing M only dismiss M, and not dismiss P

I am using Ionic2.beta.6

#### Plunker that shows an example of your issue

http://plnkr.co/edit/uhk2awxpmxnYSVv3DCe8?p=preview

In this plunker, when M is closed, P is also 'dismiss' to reveal a 'black screen' instead of displaying P

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! I have made my own plunker here: http://plnkr.co/edit/zCoCF5KltgDBITYUsjS8?p=preview that demonstrates how i would do this currently. The issue lies in the fact that modals were not really designed to be opened on page load, and therefore when the onPageDidEnter() event fires for the "base page", it opens the modal, but then the onPageDidEnter() event fires for the modal page, which then opens another modal. As you can see from my fix, im checking the length of the nav stack in onPageDidEnter and when it reaches 2 (both the base page and modal are loaded in) it returns to prevent it from executing again. I am going to close this issue but feel free to comment ! Thanks for using Ionic!

**Comment by jgw96** [comment]
Hey @khanhlu2013 ! I now have a better solution for you. You can see this solution in [this](http://plnkr.co/edit/zCoCF5KltgDBITYUsjS8?p=preview) plunker. I am just setting the `fireOtherLifecycles` property of the modal to false so that it does not fire the lifecycle events of the "base" page.
