### ISSUE TITLE
My content is halfway off the screen

### ISSUE THREAD

**Issue by shresthaarjun** [driftyco/ionic#6455]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>my content is halfway offscreen</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Unfortunately I am going to need a little bit more info to help you with your issue. Would you mind filling out the issue template fully and putting that info here?

**Comment by danbucholtz** [comment]
Hi @shresthaarjun,

If you can provide more info we'll revisit this topic.  In it's current state, we don't have any information to go off of.  Please let us know if you've found an issue in the framework.  Otherwise, we have an awesome [support community](https://forum.ionicframework.com/?utm_source=framework&utm_medium=navbar&utm_campaign=forum%20CTA) available.
