### ISSUE TITLE
Ionic conflicts with ng-tags-input (Multiple Issues)

### ISSUE THREAD

**Issue by shyamal890** [driftyco/ionic#6472]
**Issues**: 

1. Input is not focused when tags-input is clicked or touched. It only works when 'input' (placeholder) is clicked explicitly. [Similar issue on ng-tags-input repo](https://github.com/mbenford/ngTagsInput/issues/487#issuecomment-147458989)
2. After a tag is added from autocomplete list, the input is no longer focused.

> NOTE: This all works perfectly if ng-tags-input is utilized separately from ionic.

[Plunker](https://plnkr.co/edit/X3pLCb?p=preview) 

**Which Ionic Version?** 1.2.4

**Comment by jgw96** [comment]
Hello @shyamal890 ! Does this work as expected on mobile when not using ionic? Or only in ionic apps?

**Comment by shyamal890** [comment]
@jgw96 Yes it does, check out the plunker demos [here](http://mbenford.github.io/ngTagsInput/demos)   

When utilized in conjunction with Ionic the problem arises. I think it has to do with how Ionic handles input elements. For more context, when I add a `$timeout` to `input[0].focus` event in `ng-tags-input.js` file, the first issue is solved.

**Comment by danbucholtz** [comment]
Hi @shyamal890,

Ionic implements it's own tap system, so that could be an issue.  Have you tried disabling `tap` functionality on that component?

http://ionicframework.com/docs/api/page/tap/

```
<div data-tap-disabled="true">
    <div id="google-map"></div>
</div>
```

Give that a shot and let us know how it goes.  This component probably will have a strange UX on mobile anyway, so we probably won't make any changes to the framework for this utility at this time.  Thanks for using Ionic and letting us know about this issue.

Thanks,
Dan
