### ISSUE TITLE
ionic slides unshift(picture) to ng-repeat not working

### ISSUE THREAD

**Issue by emps** [driftyco/ionic#6479]
well im using ionic slides that is using Swiper.. so what i did is using ng-repeat with inside slide elements for 3 images and then im tring swipe right to older pics by using .push(pic) to my pictures array looks working fine, but if i wanna go back to newer dated pics by unshifting , slides get mess
and not working properly

ionic 1.3

platforms ios android chrome

**Comment by jgw96** [comment]
Hello @emps ! Thanks for opening an issue with us. Would you mind making a plunker that demonstrates this issue? You can find a link to an ionic 1.3.0 plunker template in the issue template for this repo.

**Comment by emps** [comment]
yes i will create demo asap, i would also like know if there is some one success to make that working

**Comment by emps** [comment]
well the problem is while adding new slide to the front of the slides it makes slides Indexes that Swiper is using to move forward so the new one gets index 0 and all the rest gets ++ and makes swiper jump to the begin index that is the new one (0) and skip the previous slid

slides:  [0 'a'] [1 'b'] [2 'c']
after unshifting new slide
 slides: [0 'new' ] [1 'a'] [2 'b'] [3 'c']

so if im on index 1 that is 'b' and i am unshiftine new slide cause i wanna go to index 0 that is 'a'
Swiper jumping to index 0 that is the 'new' cause index 0 that was 'a' changed to index 1

i will try find solution and update it here

**Comment by danbucholtz** [comment]
Hi @emps,

I am going to close this issue since it doesn't sound like it a bug in the framework.  We have several channels available for help, I recommend checking out [our forum](https://forum.ionicframework.com/?utm_source=framework&utm_medium=navbar&utm_campaign=forum%20CTA).  Ionites in the forum are super helpful and very active.

I'll re-open if we find this is a framework issue.

Thanks for contributing.

Thanks,
Dan
