### ISSUE TITLE
question: collection-repeat creating more 19 items and i have only one item on array

### ISSUE THREAD

**Issue by wendellpalazzo** [driftyco/ionic#6522]
#### Short description of the problem:
I have only one item on array... but collection-repeat render more 19 items
in comparation of ng-repeat render only one item.

is a bug? or i used wrong?

Ionic version 1.3

**Comment by wendellpalazzo** [comment]
using ionic pen example code of collection-repeat:
http://codepen.io/ionic/pen/7ec1ec58f2489ab8f359fa1a0fe89c15

put in MainCtrl only 1 in for loop... and inpect the html code generated.. you see like this.

<ion-item>.....</ion-item> for 19 times...

**Comment by wendellpalazzo** [comment]
and sorry my english rs ;p

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Your english is fine! (: `collection-repeat` is made for large data sets where you are scrolling though large amounts of items. To make this performant it does not render all your list items at once, but renders enough to fill the viewport. When trying to use `collection-repeat` with only one item, it is going to go ahead and render enough elements to fill the viewport and get them ready to accept data because as i said, its expecting a large list. So, this is actually expected behavior from `collection-repeat` If you are going to have smaller lists, or even a list with just one item, i would recommend using `ng-repeat`. Thanks for using Ionic!

**Comment by wendellpalazzo** [comment]
Thanks!!!!
I understood... 

Ionic is the best!

**Comment by jgw96** [comment]
@wendellpalazzo Thanks! We appreciate it!
