### ISSUE TITLE
Android and Windows Platform Nav/Toolbar Title Alignment V2

### ISSUE THREAD

**Issue by Mobius77x** [driftyco/ionic#6554]
V2

For Android and Windows platforms the Title of modals and pages is either too far left or right aligned (I am expecting/wanting it to be centered) 

![image](https://cloud.githubusercontent.com/assets/17939161/15344659/11873c96-1cdb-11e6-9c82-c685864410ca.png)

![image](https://cloud.githubusercontent.com/assets/17939161/15344670/28ec4886-1cdb-11e6-921f-934aa8e71188.png)

Fixing is not as simple as using `text-align:center` because the `ion-title` div only begins or ends after the icons. In any case it doesn't appear centered even without icons.

Also, the title in Windows platform is capitalised:

![image](https://cloud.githubusercontent.com/assets/17939161/15344681/3e9dd00a-1cdb-11e6-929b-ddb3b211e1e2.png)

Is this standard for Windows phone? I always thought capitalising words was the text equivalent of shouting...

The capitalisation can be easily turned off by not using 

```
text-transform:uppercase
```

if it's not the standard and/or the developer wants to avoid the capitalisation.

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us! So the reason the title is to the left on windows 10 and Android  is because that is how it is on native android and windows 10 platforms. Also, for windows 10 it is standard to have capitalization for the title of a page, which is why we have it like that. I am going to mark this one as blocked by https://github.com/driftyco/ionic/issues/5036 as theres not much we can do about this issue yet until that issue is fixed. Thanks for using Ionic!
