### ISSUE TITLE
$ionicView.beforeEnter is not fired

### ISSUE THREAD

**Issue by didlich** [driftyco/ionic#6577]
after the update from
ionic 1.3.0 to 1.3.1
the $ionicView.beforeEnter is not fired any more as before

I have this controller:
```typescript
class MyCtrl {
 static $inject = [   
    "$scope"
  ];
  constructor(
    private $scope
  ) { 
    $scope.$on("$ionicView.beforeEnter", (event, data) => {
      this.activate();
    });
  }
}
```

in version 1.3.0 the activate() method is called as expected
in version 1.3.1 the activate() method is not called

the fix is to roll back to version 1.3.0

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind making a plunker demonstrating this issue please? That would be a huge help!

**Comment by asmund1** [comment]
I have this problem too. See plunker that reproduces: http://plnkr.co/edit/IBFQTuvARTBC9bExU3uq?p=info
(Change from ionic 1.3.1 to 1.3.0 to see working version)

Could it be something with the routing like in https://forum.ionicframework.com/t/ionicview-events-not-firing/19825/14 ?

**Comment by darthdie** [comment]
In my testing it appears this was broken in commit d63733350b73c0084f99fe285dda96f0204b2cd7

Specifically the following line returns null (thus it then has no scope to emit events to)
```javascript
var enteringScope = getScopeForElement(enteringEle, enteringData);
```

From further testing it appears it returns null because inside of `getScopeForElement`

```javascript
    if ( attributeValue !== "true" ) {
      // it's not an abstract view, so make sure the element
      // matches the state.  Due to abstract view weirdness,
      // sometimes it doesn't. If it doesn't, don't dispatch events
      // so leave the scope undefined
      if ( stateValue === stateData.stateName ) {
        return angular.element(element).scope();
      }
      return null;
    }
```

The condition `if ( stateValue === stateData.stateName )` is false because stateValue is null. (At least in my particular case)

In case anybody is interested (and/or needs these events to fire like myself) for now I've patched it simply by merging the original with the new (inside of the `emit` function in "$ionicViewSwitcher"), i.e.
```javascript
var enteringScope = getScopeForElement(enteringEle, enteringData) || enteringEle.scope();
```

**Comment by rxnh8255** [comment]
I also have this problem
$ionicView.enter is not fired
when I use code by @darthdie ,It work.tks.

**Comment by danbucholtz** [comment]
Hi all,

I'll take a look at this.

Thanks,
Dan

**Comment by danbucholtz** [comment]
Hi @asmund1,

When I use your Plunkr, I do see the issue.  However, it is because your template is not a container.  That's an edge case, so I'm not going to make a change right now to support that.  If you change your template to the following, it works correctly.
```
<ion-view>
  <h1>View one</h1>
</ion-view>
```

@rxnh8255, @darthdie, Please help me out with what is unique with your apps.  Can you make a plunkr or a codepen demonstrating the issue?  I cannot recreate it presently.  Please let me know.  Thanks for the details @darthdie.  Why is your stateValue null?

Please let me know and I'll get it resolved.

Thanks,
Dan

**Comment by rxnh8255** [comment]
@danbucholtz 
[http://plnkr.co/edit/dOXTj7](url)
Look this.
When I add this `<button ng-click="add()" class="button"></button>` at the end.It not works
When I delete the button,it works good.

**Comment by rxnh8255** [comment]
http://plnkr.co/edit/dOXTj7?p=preview

**Comment by danbucholtz** [comment]
Hi @rxnh8255,

Well, I understand why it doesn't work with the button.

Due to some challenges with ui-router, we need to look-up the element to get the correct scope to dispatch the life cycle events.  Since your template is not inside of a container like `<div></div>` or `<ion-view></ion-view>`, we have more than one child, which means the logic does not execute correctly.

See ` if (containerEle.children.length === 1) {` below.

```
createViewEle: function(viewLocals) {
      var containerEle = $document[0].createElement('div');
      if (viewLocals && viewLocals.$template) {
        containerEle.innerHTML = viewLocals.$template;
        if (containerEle.children.length === 1) {
          containerEle.children[0].classList.add('pane');
          if ( viewLocals.$$state && viewLocals.$$state.self && viewLocals.$$state.self['abstract'] ) {
            angular.element(containerEle.children[0]).attr("abstract", "true");
          }
          else {
            if ( viewLocals.$$state && viewLocals.$$state.self ) {
              angular.element(containerEle.children[0]).attr("state", viewLocals.$$state.self.name);
            }

          }
          return jqLite(containerEle.children[0]);
        }
      }
      containerEle.className = "pane";
      return jqLite(containerEle);
    }
```

Please wrap your template in an `ion-view` or a `div` and see if that fixes your issue.  I will discuss with the team members what we want to do with this code, whether we change it, or just document it better.  Typically, you want a template to be one container, though.  That is the best practice.

Thanks for your help!

Thanks,
Dan

**Comment by daangeerdink** [comment]
@danbucholtz is right, ensuring there is only 1 root element in your template fixes this issue. 

I had this issue occur when I had the following:
```
<ion view>
  stuff here
</ion-view>

<script id="some-template.html" type="text/ng-template">
  some template
</script>
```

Moving the `<script>` block to inside the `<ion-view>` fixed it for me.

**Comment by ameerhamza26** [comment]
hi im also having the same issue.. i just updated my app to 1.3.1 version.. my template is enclosed inside ion-view.. still $ionicView.beforeEnter is not fired.. any one fixed this ?

**Comment by danbucholtz** [comment]
@ameerhamza26,

I can help but I need more info.  Can you create a small sample demonstrating the issue?  So far, every issue found since we made changes to this part of the code has been a template or a ui-router configuration issue.

Thanks,
Dan

**Comment by bogomips** [comment]
Hello,
I have the same issue: the event "enter" is not fired if the page has at the end after </ion-view> tag the following :
<script id="some-template.html" type="text/ng-template">
  some template
</script>

**Comment by danbucholtz** [comment]
@bogomips,

Templates should be containers.  Throw a `<div>some template</div>` in the script tag and everything should work.

Thanks,
Dan

**Comment by jiazhengshi** [comment]
I have the same issue too.

**Comment by afourney** [comment]
Same problem here. I'm rolling back to 1.2.4

**Comment by danbucholtz** [comment]
@jiazhengshi, @afourney, are your templates containers?  There is pre-existing code in the framework that is now enforced (indirectly) that require templates to be true containers.  Try wrapping the template in a div and everything should just work.  We have several thousand lines of unit tests around this, so I'm reasonable confident this will get your life cycle events working correctly.  Give it a shot and let me know how it goes!

Thanks,
Dan

**Comment by afourney** [comment]
Thanks @danbucholtz , 

Indeed 1.3.1 broke an existing code base. My template had a script tag at the end containing an ion-modal-view, so the structure looked like:

`<ion-view>
  stuff here
</ion-view>

<script type="text/ng-template">
<ion-modal-view>
  stuff here
</ion-modal-view>
</script>`

I wrapped everything in an enclosing <div> and was able to get 1.3.1 to work. Thanks.

Probably this change should be listed in the change log under "breaking changes". Even if my prior code was out of policy, I am not the only one experiencing this, apparently. It was a pain in the butt to debug this and track down this thread.

**Comment by youssmak** [comment]
> This should probably be listed in the change log under "breaking changes".
+1


Before ($ionicView.beforeEnter is not fired) : 
```
<ion-header-bar>
...
</ion-header-bar>
<ion-view>
...
</ion-view>
```


After ($ionicView.beforeEnter is fired): 
```
<div>
<ion-header-bar>
...
</ion-header-bar>
<ion-view>
...
</ion-view>
</div>
```

**Comment by longbo666** [comment]
@danbucholtz   
`if ( attributeValue !== "true" ) {
      // it's not an abstract view, so make sure the element
      // matches the state.  Due to abstract view weirdness,
      // sometimes it doesn't. If it doesn't, don't dispatch events
      // so leave the scope undefined
      if ( stateValue === stateData.stateName ) {
        return angular.element(element).scope();
      }
      return null;
    }
`

> if ( stateValue === stateData.stateName )  

when I use $ionicGoBack(-2),    stateValue !== stateData.stateName ,
and then ,life cycle doesn't fire because of the leavingScope is NULL!

**Comment by zwacky** [comment]
I also have this issue with 1.3.2.
Can't fully follow how there should be a root element outside the template declaration since we don't use `<script type="text/ng-template">` for template declaration; we use **ngHtml2js** with `$templateCache.put(…)`.

**Comment by pliablepixels** [comment]
Good gosh. Thank goodness for this thread. Some views of my app completely broke due to this reason - `beforeEnter` and other view callbacks not being called. Downgrading to `1.2.4` fixed the issue.
