### ISSUE TITLE
Use webstorm compiler is very slow

### ISSUE THREAD

**Issue by DarrenHou1993** [driftyco/ionic#6600]
With webstorm11 to write ionic2, each modified typescript compiler is very slow. Is there any way to solve it? My webstorm11 used for a period of time, the memory will be occupied by the arrival of 2G; I usually restart a down to solve the problem.What IDE are you using?

**Comment by alexbainbridge** [comment]
I expect the Ionic team will suggest that you go to the forums for support matters.....

Anyways, as a webstorm user, I sped it up by excluding node_modules and excluding www folder. This stops webstorm rechecking all changes in there, on every field edit / file save (which happens if you are using ionic serve)

To exclude a folder, on the project list in the left window, select, then click exclude from the menu

**Comment by jgw96** [comment]
Hey all! Thanks for opening an issue with us! Unfortunately as this is not a problem with Ionic, but instead an issue related to webstorm I will be closing this issue. For matters related to webstorm I would suggest going to there support as I'm sure they could help you. Also, as webstorm is pretty popular, there may be some users on our forum (https://forum.ionicframework.com) that could help you. Thanks for using Ionic!

**Comment by BumbuKhan** [comment]
Just right click on folder, you wanna exclude, in IDE and choose 'Mark directory as' ->'Excluded'
