### ISSUE TITLE
Right side overlay menu appears when switching from portrait to landscape

### ISSUE THREAD

**Issue by fareesh** [driftyco/ionic#6740]
#### Short description of the problem:

The right side menu shows in the middle of the screen

#### What behavior are you expecting?

The right side menu should stay hidden

**Steps to reproduce:**
1. ionic start menutest tutorial --v2
2. Edit app.html, change menu to side="right"
3. Pop out menu, rotate to landscape

**Which Ionic Version?** 2.x

2.0.0 beta 7

Screenshot: http://i.imgur.com/McqRjKR.png

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This should be fixed in the beta.8 release as we have made some changes to how the sidemenu on the right side works. I will close this issue for now, but after beta.8 releases (which should be very soon (;) if you still have this issue feel free to comment and i will happily reopen! Thanks for using Ionic!

**Comment by brandyscarney** [comment]
Confirmed this is an issue for both `overlay` and `push` menu types in latest. Nice catch and thanks for the PR @fareesh, we'll look into this soon!

**Comment by manucorporat** [comment]
Overlay menu is fixed: https://github.com/driftyco/ionic/pull/6745
Working right now in the push menu type...

**Comment by manucorporat** [comment]
@brandyscarney push/overlay fixed here: https://github.com/driftyco/ionic/commit/0c885899bca2b1e7ed6fa85377edb7ecf1a682b8
