### ISSUE TITLE
Android navigation is very slow when opening page for the first time in ionic 2

### ISSUE THREAD

**Issue by mwanas** [driftyco/ionic#6769]
Android navigation is very slow when opening view for the first time in ionic 2 Menu animation flicks when opening the page for the first time after that when revisiting the same page , the menu closes smoothly.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This is due to Ionic 2 currently using dynamic template compilation. We are currently working on a new build chain that implements the offline template compiler which should get rid of this issue. We hope to get this implemented and released soon! Thanks for using Ionic!
