### ISSUE TITLE
Add a config option to resolve templateUrl to template in ionic2

### ISSUE THREAD

**Issue by lygstate** [driftyco/ionic#6795]
When we use the ionic2 template system,
we have 
```
@App({
  templateUrl: 'build/app.html',
  config: {}, // http://ionicframework.com/docs/v2/api/config/Config/
  providers: [
    JSONP_PROVIDERS,
    Itunes,
    LanguageSetting,
    UserData,
    UserApi,
    DeviceApi,
    NG2_UI_AUTH_PROVIDERS(AuthConfig),
  ]
})
```
I hope when building, we could be able to 
resolve the templateUrl as
```
@App({
  template: 'The content of build/app.html',
  config: {}, // http://ionicframework.com/docs/v2/api/config/Config/
  providers: [
    JSONP_PROVIDERS,
    Itunes,
    LanguageSetting,
    UserData,
    UserApi,
    DeviceApi,
    NG2_UI_AUTH_PROVIDERS(AuthConfig),
  ]
})
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! We are currently working on implementing the Angular offline template compiler which will take care of this issue, make our file sizes smaller, lower our startup times and make ionic 2 faster overall because we will not be dynamically compiling templates anymore. Thanks for using Ionic!
