### ISSUE TITLE
Datetime Feature - open component from code without user click event

### ISSUE THREAD

**Issue by djangojack** [driftyco/ionic#6799]
It would be great if we could open the Datetime component just like an Alert component. This wouldn't require user interaction. This would make it much more flexible. 

**Which Ionic Version?**  or 2.x

**Comment by dpsoft** [comment]
currently exists a workaround to do this without user interaction?

**Comment by brandyscarney** [comment]
Since it uses the Picker API underneath, you can call the Picker and create it that way, this isn't well documented: http://ionicframework.com/docs/v2/api/components/picker/Picker/

```
openPicker() {
  let picker = Picker.create({
    columns: [
      {
        columnWidth: "144px",
        name: "month",
        options: ["January", "February", "March"],
        selectedIndex: 0
      },
      {
        columnWidth: "144px",
        name: "year",
        options: ["90", "91", "92"],
        selectedIndex: 0
      },
    ],
    buttons: [
    {
      text: "Cancel",
      role: 'cancel',
      handler: () => {
        console.log("Clicked cancel")
      }
    },
    {
      text: "Done",
      handler: (data: any) => {
        console.log("Clicked done with", data);
      }
    }
  ]
  });

  this.nav.present(picker);
}
```

Hope that helps! See the Picker code for more info: https://github.com/driftyco/ionic/blob/2.0/src/components/picker/picker.ts

**Comment by danbucholtz** [comment]
Agreed, this would be a nice improvement to the framework.

**Comment by adamdbradley** [comment]
For this, the user's component could have a template variable, like `<ion-datetime #myDatetime/>`. Then `@ViewChild('myDatetime')` can be used to find the component. Next with that reference they can call `present()`. But I don't believe the present methods are exposed on something like ion-datetime or ion-select, so that's all we'll have to do (along with docs on how to do it).

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by comfortme** [comment]
any improvements on this issue?

**Comment by comfortme** [comment]
by the way i found this article that shows a nice little workaround similar to @adamdbradley 's solution,
https://blog.jarmemori.es/tech/2016/09/14/display_ionic_datetime_picker_programmatically.html

**Comment by gigocabrera** [comment]
+1

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#44

**Comment by gtcdevop** [comment]
Any news on that since @jqw96 mentioned a feature request that was closed.
