### ISSUE TITLE
bug: [Bug] Modals navbar menu icon hidden

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#6856]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If we use the `ion-navbar` in a modal the menu icon is hidden, in my app the modal is a child page so it should show a back arrow.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! If you would like to have a child page that has a back button in the navbar then you should push a page onto the stack instead of using a modal. This should give you the functionality you are looking for. If this does not fix your issue feel free to comment on this issue and I will happily reopen. Thanks for using Ionic!

**Comment by Luchillo** [comment]
Can i get the same behavior? from modals when dismissed i can attach an event for the dismiss and get some data from it, can i do the same just with pages?

**Comment by jgw96** [comment]
Hey! At this time there is not a way to pass data with `nav.pop()` and we recommend using our lifecycle events and services to handle passing data around as it keeps all your components nicely decoupled from one another. There is an open [issue](https://github.com/driftyco/ionic/issues/5724) for passing data through `navparams` when popping a page though.

**Comment by Luchillo** [comment]
I was reading about that issue, however it seems it's far from being implemented, also using a service just for 1 data seems overkill, for now i'll stick with the hack with `ion-toolbar`, `ion-buttons` with `start` attribute, arrow back button with `NavController.pop()` binding, and hack the `order` css on that button container to `2`.
