### ISSUE TITLE
V2: Custom component with <ion-checkbox> doesn't render within <ion-item>

### ISSUE THREAD

**Issue by Kobzol** [driftyco/ionic#6880]
#### Short description of the problem:
I have a custom component that contains a ion-checkbox.
When I try to render this component inside ion-item, nothing is rendered.
When I render the checkbox directly without the component, it renders.
When I render the component without the checkbox, it also renders.
When I render the component inside ion-list directly without ion-item and apply the .item class to it, it renders, but in a weird way.

#### What behavior are you expecting?
I expected that I could nest components with ion-checkbox inside ion-item and that it would render correctly.

**Steps to reproduce:**
1. Create a component containing ion-checkbox
2. Render it inside ion-item in a ion-list

#### Plunker that shows an example of your issue
http://plnkr.co/edit/fDQmNq?p=preview
Here you can see the behavior in `home.html`. `component.ts` contains the component with ion-checkbox in its template.

**Ionic info:**
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS:
Node Version: v6.2.0

**Comment by brandyscarney** [comment]
Item's look for specific elements & attributes in order to render content. If these elements or attributes are nested it won't place them correctly, see https://github.com/angular/angular/issues/6164. In your specific use case you can add the `item-content` attribute to your custom element and it will render, just not in the same place as if it grabbed the checkbox directly. We have some docs on item placement here: http://ionicframework.com/docs/v2/api/components/item/Item/#item-placement

More information can be found on these issues: https://github.com/driftyco/ionic/issues/6861
https://github.com/driftyco/ionic/issues/6849

Thanks!
