### ISSUE TITLE
InfiniteScroll event never fired

### ISSUE THREAD

**Issue by Nodonisko** [driftyco/ionic#6908]
#### Short description of the problem:
You can see only spinner at bottom of list, but event is never fired. See plunker for more details.

#### What behavior are you expecting?
Fire event. 

**Which Ionic Version?** 2.0.0-beta.8

#### Plunker that shows an example of your issue

http://plnkr.co/edit/IBBeqcXBLS23O2ZiiaaQ?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS: Distributor ID:     Ubuntu Description:     Ubuntu 16.04 LTS 
Node Version: v6.2.1

**Comment by brandyscarney** [comment]
All Ionic events were renamed as part of `beta 8`. The `infinite` event is now called `ionInfinite`. Please replace the event name in order to fire the event. Infinite Scroll docs: http://ionicframework.com/docs/v2/api/components/infinite-scroll/InfiniteScroll/#output-events

For a full list of event name changes, see the changelog: https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#ionic-component-events-renamed

And for step by step instructions to upgrade: https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#steps-to-upgrade-to-beta-8

Thanks! :smile:
