### ISSUE TITLE
ionic2 bug(tabs) - tab page without navbar results in navbar placeholder being transparent

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#6927]
#### Short description of the problem:
When a tab page does not contain an ion-navbar component, then the navbar placeholder in the ion-tabs component is left empty. This is fine, but because the CSS has min-height: 44px, content __behind__ the current tab page can be seen.

#### What behavior are you expecting?
I would expect the navbar placeholder to be completely hidden, or its height to be 0 if the current tab page has no ion-navbar. The plunker below shows this bug on tab page 2.

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue
https://plnkr.co/edit/XPoPzFsm03x8lvPrHMlH?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.4.4
Xcode version: Xcode 7.3 Build version 7D175

**Comment by brandyscarney** [comment]
This should be fixed by the `beta 10` release. Please see the breaking changes & update steps and let us know if it's still an issue: https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-beta10-2016-06-27

Also related: 
https://github.com/driftyco/ionic/issues/5556
https://github.com/driftyco/ionic/issues/5164

Thanks for the issue!
