### ISSUE TITLE
Ionic2 The ability to disable changing knob with tap

### ISSUE THREAD

**Issue by navid045** [driftyco/ionic#6956]
#### Short description of the problem:

In some cases when we want to scroll a list of range items, It makes unwanted changes on range controllers due to scrolling the list.
#### What behavior are you expecting?

It seems good if we could disable range changing with tap on line of range controller or add the ability to change with press (long touch) or change the range with only dragging the knob.

range + v2

**Comment by julienfle** [comment]
I have the same problem. Please can you answer the question.

**Comment by jarrodkoch** [comment]
Is there any chance that the pull request which addresses this will get into the next beta?

**Comment by frederickjansen** [comment]
I'd like to propose an alternative approach to the existing pull request. Instead of an additional setting, where you sacrifice functionality for usability, why not detect the user's intention?

The way range elements on Android work (not sure about iOS), is by not activating them on pointerDown, but rather waiting until pointerMove to see which direction the user's finger is moving to. Up/down activates scrolling, left/right activates the range component. Once you commit to one, the other behavior is ignored as long as you hold your finger down.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#159

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!
