### ISSUE TITLE
How to minimize built app.bundle.js file size if I only need run it on a browser?

### ISSUE THREAD

**Issue by aaronchen2k** [driftyco/ionic#6963]
How to minimize built app.bundle.js file size if I only need run it on a browser?
Can I drop some css, font and js files?

**Comment by manucorporat** [comment]
@aaronchen2k Hi! we are taking care of this. we are working right now in a new build chain: https://github.com/driftyco/ionic/issues/6859#issuecomment-225361039

I will close this issue, since we use Github Issues as a way to track real issues not questions, please feel free to open a topic in our forum: https://forum.ionicframework.com
