### ISSUE TITLE
Fab positioned over content when the keyboard is shown (Android)

### ISSUE THREAD

**Issue by mdelerue** [driftyco/ionic#7013]
## Short description of the problem:
Not tested on Windows, OK with iOS, in my case it only occurs with Android :

Fabs positioned at the bottom are sent up when the keyboard is shown and potentially positionned over other elements.

```
<ion-content>
</ion-content>
<button fab fab-center fab-bottom primary>
  <ion-icon name="add"></ion-icon>
</button>
```
The basic structure of the page is on the Plunkr : http://plnkr.co/edit/nhieKD .

I tried to put the button inside and outside of the ion-content, the behaviour is the same.

## Expected

The behaviour on iOS seems more logical to me with the fab staying behind the keyboard.

Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v5.11.1

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. I am making a quick native to compare this behavior to the native behavior. We generally strive to be as close to native as possible. I will get back to you with my findings! Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello @mdelerue from looking at some native examples it seems like the fab button is always displayed even when the keyboard is open. It is actually a part of the material design spec for the fab button to never be hidden, as it is meant to be the "center" of user interaction with your app, the fastest path to the main action. Since our behavior seems to be the same as the native behavior, and match the material design spec i will be closing this issue. Thanks for using Ionic!
