### ISSUE TITLE
Ionic 2 new beta with Angular 2 RC 3

### ISSUE THREAD

**Issue by alexweber** [driftyco/ionic#7041]
Hey team, even though beta 9 was released very recently, it still uses Angular 2 RC1.  Given the erratic Angular RC schedule I don't blame you for not jumping on every upgrade, however, seeing as you've already updated in master to using RC3, I was wondering how soon we can expect a new beta that includes it? Thanks!

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! So keeping up with Angular is always top priority for us, but because of all the breaking changes still happening on the Angular 2 side we have been having to make code changes to Ionic 2 to work with the newest angular releases. Angular 2 is not to the stage yet where when they do a release it will "just work" but it should be soon! Even though we are beta, we try to give you the most stable release we can, which sometimes means being one or two releases behind on which version of Angular we are using. Also, our next release, beta.10, will be on RC3, and we should be releasing very soon (; Thanks for using Ionic!
