### ISSUE TITLE
v2 Enhancement for platform style overrides in Config for ionic components

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic#7064]
#### Short description of the problem:

This is a feature request not a bug.

Currently in the config block we have the option to override the platform styling for some elements, for example iconMode: ios, pageTransition: ios etc.

It would be really useful to be able to over ride the default platform styling for other ionic components in the same way.  For example ion-range: md, ion-segment: ios.  This would be an application wide over ride for the specific component. and it would be consistent with the way platform style over rides are currently handled for other elements like icons and transitions.

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#47
