### ISSUE TITLE
Promise from bootstrap is not returned since Beta.10

### ISSUE THREAD

**Issue by frederikschubert** [driftyco/ionic#7145]
#### Short description of the problem:

Prior to [this](https://github.com/driftyco/ionic/commit/d13fa4e2cfc3b3039239a9e09ea701ad9bc624b4#diff-ebf9800fbbf7fb1848c856bf37b6a2b5L53) change it was possible to act on the Promise that is returned from the angular `bootstrap` function. Due to the removed `return` statements this cannot be done anymore.
#### What behavior are you expecting?

I would like to call `enableDebugTools` from `@angular/platform-browser` on my root component to debug change detection performance in my app.
```typescript
ionicBootstrap(App, [SINGLETON_PROVIDERS).then(enableDebugTools);
```
Then it is possible to call `ng.profiler.timeChangeDetection();` to get the speed of the change detection for the current application state.

**Which Ionic Version?**
2.0.0-beta.10

**Comment by adamdbradley** [comment]
Also as a heads up, soon with offline template compiling the `ionicBootstrap` function will be replaced with Angular's `@AppModule`, since the bootstrap process is being refactored: https://docs.google.com/document/d/13-LUm1QvOff2631tHz6C4goIHuMzma2_1_PFiLryoIs/edit?ts=57682de6#heading=h.e07aj2l7pv3h

**Comment by frederikschubert** [comment]
Great! Thanks for the quick response!
