### ISSUE TITLE
new header system strange behaviour

### ISSUE THREAD

**Issue by ChezRD** [driftyco/ionic#7151]
#### Short description of the problem:
wrong z-index of headers on layout like this:
tabs page with header -> tab with header -> nav.push page with header on android
also when i change pages with setRoot from side menu "hamburger icon flickering (hide+show new) appears"

#### What behavior are you expecting?
nav of sub sub page at the top, but not at bottom of z-index stack
not flickering menu/back icon

**Steps to reproduce:**
1. create ion-tabs page with header and nav in it
2. create ion-tab pages with headers and nav in it
3. create subpage from one of the on-tab pages with header and nav in it

**possible temporary solution**
```
ion-header + ion-tabs {
    z-index: 11;
}
```

**Which Ionic Version?** 1.x or 2.x
2.beta 10

#### Plunker that shows an example of your issue
http://plnkr.co/edit/FXwvyk38oqdG1yiuXCrj?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS: Windows 8.1
Node Version: v5.3.0

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! At this time it is not possible to use `<ion-tabs>` with other components. `ion-tabs` is meant to be used as a root component, in the sense that the template that has the `ion-tabs` should not have any other html. For an example of this you can start a tabs starter by running `ionic start TabsExample tabs --v2` and looking at the tabs.html file in the tabs folder. We are considering creating a standalone tab bar that will be able to be used anywhere in an ionic 2 app, but at this time it is not on our roadmap officially. This should have not worked before beta.10, and is something that was fixed by the beta.10 refactor, so i am sorry for any confusion this causes. Thanks for using Ionic!

**Comment by ChezRD** [comment]
@jgw96 is there a way to move searchbar under tab-bar?
here is screen https://drive.google.com/file/d/0B-f6Y6ba1-_QMUlaQzFqV2w5aXM/view?usp=drivesdk
it's setRoot(TodayPage) where today page is:
`<ion-tabs [preloadTabs]="false" [selectedIndex]="mySelectedIndex" business-law-2>
  <ion-tab [root]="tab1Root" tabTitle="Задачи" tabIcon="clipboard" [tabBadge]="notificationsCount.tasks" tabBadgeStyle="business-law-1"></ion-tab>
  <ion-tab [root]="tab2Root" tabTitle="Уведомления" tabIcon="notifications" [tabBadge]="notificationsCount.documents" tabBadgeStyle="business-law-1"></ion-tab>
  <ion-tab [root]="tab3Root" tabTitle="Просроченное" tabIcon="alarm" [tabBadge]="notificationsCount.late" tabBadgeStyle="danger"></ion-tab>
</ion-tabs>`

and header of inner tab page is:
`<ion-header>
  <ion-navbar business-law-2>
    <button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>
      Просроченные
    </ion-title>
  </ion-navbar>
  <ion-toolbar business-law-2 *ngIf="showSearch == true" no-border-top>
    <ion-searchbar
        [debounce]="10"
        [(ngModel)]="queryText"
        (ionInput)="updateSchedule(false)"
        [hideCancelButton]="shouldHideCancel"
        placeholder="Поиск"
    >
    </ion-searchbar>
  </ion-toolbar>
</ion-header>

<ion-content class="late-tasks tasklist">...`

i can move tab bar to bottom, but it's not so materialish it's more ios-like
