### ISSUE TITLE
Error replacing custom directives to Ionic directives

### ISSUE THREAD

**Issue by jdnichollsc** [driftyco/ionic#7155]
#### Short description of the problem:

I'm creating a directive to support IE browser with Ionic 1.x. Basically I'm replacing my directive ion-repeat to ng-repeat (Only on Windows) or collection-repeat (Android, iOS, etc), because the collection-repeat doesn't work good on Windows.

#### What behavior are you expecting?
The scroll works good after to replace my directive to collection-repeat directive.

**Steps to reproduce:**
1. Open my directive example: http://codepen.io/jdnichollsc/full/EyPOee/
2. Using Chrome change the view to mobile
3. You can see that the scroll doesn't work.

**Which Ionic Version?** 1.x

#### Plunker that shows an example of your issue

See the issue: http://screencast.com/t/feGW9CW7H

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this issue seems to be happening because of your custom directive i would urge you to post about this issue on our [forums](https://forum.ionicframework.com/). There are a ton of awesome devs on there that can help iron any issues out with your custom directive. Thanks for using Ionic!

**Comment by jdnichollsc** [comment]
@jgw96  But it's an error with the Ionic scroll component, because the height is 0 and the resize doesn't work dinamically

**Comment by jdnichollsc** [comment]
See please: https://forum.ionicframework.com/t/issue-collectionrepeat-directive/56583
