### ISSUE TITLE
Overlay Providers are breaking custom app providers

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#7160]
Sorry about the wordsmith'd title.

This is a pretty important issue.

If I have a page that takes an injected dependency via construction injection that is custom to my app (I am providing at the root component level), the page errors out due to being unable to find the dependency when opened in a Modal.  When I push the page onto the nav controller, it works as expected.

```
import {PROVIDERS} from './app-providers';

@Component({
  template: `<ion-nav [root]="rootPage"></ion-nav>`,
  providers: PROVIDERS
})
export class MyApp {
   // stuff in the app
}
```

Anything from the `PROVIDERS` array errors out when injected in a Modal.  I am sure this applies to other overlays like Popover as well.

Thanks,
Dan

**Comment by adamdbradley** [comment]
Could you improve this test and try to make a reproducible example? https://github.com/driftyco/ionic/commit/da6215c08e2c87e210cf7617dead5fc86a91824c

**Comment by Hufschmidt** [comment]
I ran into the same issue with Ioni2 nightly (beta 10 is current release).

The issue seems to happen when creating/instantiating a component [c1] with dependencies as popover/modal IFF the required dependencies are first introduces by the component [c2] invoking the popover creation (_PopoverController.create()_).

It seems like the popover is using the components [c2] parent injector instead of the components injector itself when trying to instantiate component [c1], thus failing.

On the contrary when component [c1] is created/instantiated via a nav-controller inside component [c2] the correct injector is used and creation succeeds.

I tried creating a plunker for this, but could not get the ionic2 nightly version running there (and the editor is so unresponsive)...
So I've created a simple webpack-based [demo application](https://github.com/Hufschmidt/ionic2-issue-7160/tree/master) instead, I hope this helps.

**Comment by danbucholtz** [comment]
@Hufschmidt, Thanks for the demo.  Adam and I continued our discussion about this offline.  This is something we still need to do.

Thanks for contributing and helping us out!

Dan

**Comment by shalaby** [comment]
any workaround? solution? have the same issue.

**Comment by aaronklaser** [comment]
I'm having a similar issue that I think might be related. 

I have a popover with a callback to the parent controller the that calls a nav.push to the next page. Your redirected to the next page but then the 'Back' button no longer works. It seems like it breaking the page array on the nav controller.

**Comment by aaronksaunders** [comment]
just ran into this issue today, can not use DI to get AngularFire into my modal login screen :-( I had to pass it in as a parameter to make everything work

```
import { AngularFire, AuthProviders, AuthMethods, FirebaseAuthState } from 'angularfire2';

@Page({
    templateUrl: 'build/pages/home/home.html',
    pipes: [MomentDate]
})
export class HomePage implements OnInit {
    textItems: Observable<any[]>;
    usersWithMessages: Observable<any[]>;
    authInfo: any
    displayName: any
    buttonTitle = "LOGIN"

    constructor(
        public af: AngularFire,
        public navCtrl: NavController,
        public modal: ModalController) {
        // dont do anything heavy here... do it in ngOnInit
    }

    displayLoginModal() {

        // I NEEDED TO HACK THE ANGULAR FIRE OBJECT INTO THE ModalController
        // BECAUSE OF A BUG IN IONIC...
        //
        let loginPage = this.modal.create(LoginPage, { af: this.af });
        loginPage.present();
    }
```



```
@Component({
    templateUrl: 'build/pages/login/login.html',
    directives: [REACTIVE_FORM_DIRECTIVES]
})
export class LoginPage {

    error: any
    af: any
    loginForm: FormGroup;

    constructor(public viewCtrl: ViewController,
        builder: FormBuilder,
        public _params: NavParams) {

        // HAD TO HACK IN THE AngularFire object... :-(
        this.af = _params.get("af");

        this.loginForm = builder.group({
            'email': [
                '', // default value
                [Validators.required, Validators.minLength(5)]
            ],
            'password': [
                '',
                [Validators.required, Validators.minLength(5)]
            ]
        })
    }
```

**Comment by Hufschmidt** [comment]
You probably have been discussing this internally already, in that case ignore my train of taught... :wink: 

The problem with popovers/modals is that they are now (as of beta-11 atleast) created on the app-root level (on the app.\_portal _NavController-like_). Thus it sits next to all your components and their injectors / injected providers.

Since the modal (_modal-component.ts:43_) and the popover (_popover-component:63_) use their viewports injector, which is a child of the app._portal's viewport (with some intermediate parent-injectors like the modals/popovers own component injector), the only providers available are the global given during bootrap.

So one quick (and dirty) workaround is to add all providers you need in your models/popovers component in the bootstrap method.
(Personally I modified the above source code to use an injector passed along via the modals/popovers _data_ parameter instead, not perfect, but the component can now at least 'stand on its own' like when used via the nav component)

As for a long-term solution, I strongly feel that we should be able to use components as modals and popovers the same way they can be used as Nav pages. For this you should be able to (manually/explicitly) set the injector used during the actual component creation (_modal-component.ts:43_ & _popover-component:63_). This should propably happen by adding another (optional) parameter to _ModalController.create(...)_ and _PopoverController.create(...)_.

**Comment by jgw96** [comment]
related: https://github.com/driftyco/ionic/issues/7621
possibly related: https://github.com/driftyco/ionic/issues/7563

**Comment by jgw96** [comment]
Thinking about this issue and NgModules in the rc5 update may actually fix this. Note to self: test this issue when that hits master (hopefully tomorrow or the next day).

**Comment by VinceOPS** [comment]
@jgw96 Hi Justin, is a fix still planed for the beta12, or should we look for a workaround? I cannot use ng-translate2 in my popovers, too.

Thanks!

**Comment by danbucholtz** [comment]
This is no longer applicable due to the move to NgModules in beta 12.

Thanks,
Dan

**Comment by raducostea** [comment]
@VinceOPS,

Add providers inside ionicBootstrap and it will work in modal views.
`
ionicBootstrap(MyApp, [User, ApiRequest, disableDeprecatedForms(), provideForms()], {});`

**Comment by ifelere** [comment]
Thank you @raducostea
