### ISSUE TITLE
feature request to use @Input() to read [rootParams]

### ISSUE THREAD

**Issue by kokokenada** [driftyco/ionic#7200]
#### Short description of the problem:

To read data passed to a component on a tab, you must inject NavParams and read it in your constructor.
#### What behavior are you expecting?

If a property in [rootParams] had the same name as an @Input() I defined in the component class, I would like that member set with the value in [rootParams].

**Other information:** 
This would make it easier to write components that are reusable in different contexts.  For example, in one app, I might place the component in a tab and in another app, I might place it within another component. 

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#49
