### ISSUE TITLE
v2 beta.10: Dismiss function apply to all objects 

### ISSUE THREAD

**Issue by paunadeu** [driftyco/ionic#7225]
#### Short description of the problem:
I have a Controller with Modal and Loading with a timeout of 10s for close loading window for avoid webService problems (i.e not loading). When I enter to controller that has Modal and Loading, and 10s has reached loading dissapear, but modal too. I executing this.loading.dismiss.

#### What behavior are you expecting?
Only close Loading Window, no Modal.

**Steps to reproduce:**
Video attached: 
https://webm.lol/v/1z44a1207e

**Which Ionic Version?** 1.x or 2.x 2.beta10

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
iMac-de-Pau: paunadeurabat$ ionic info

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: 1.8.6 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.4.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by paunadeu** [comment]
Testing on browser! ;-) platform: browser too

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by paunadeu** [comment]
Hello @jgw96, how can I provide a plunker? It's impossible, if you want i can upload to host.

Regards

**Comment by paunadeu** [comment]
The same issue here: https://forum.ionicframework.com/t/problem-with-loading/56830/9

**Comment by jgw96** [comment]
@paunadeu sorry, here is a link to the [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) template that we provide in our issue template. That should give you a good starting point! (:

**Comment by piyukore06** [comment]
here is the link to plunker http://plnkr.co/edit/L2gChmrAOIhj2n3pWINN?p=preview

you can check the function goToPage1() in home.ts

**Comment by dkobia** [comment]
Same issue at #7197

**Comment by jgw96** [comment]
Hello all, thanks for opening an issue with us! Because our navigation in Ionic 2 is completely async, when executing two transitions you have to wait on one transition to be done before the next one cant start. To make sure that this happens all of our nav methods return promises. I have made a plunker [here](http://plnkr.co/edit/q3dkC8PqrK8PGW3e7Jfr?p=preview) that shows the correct way to do this. Also, if you would like to read more about how our async nav works you can check out [this](http://ionicframework.com/docs/v2/api/components/nav/NavController/#nav-transition-promises) article. Thanks for using Ionic everyone!
