### ISSUE TITLE
clearHistory() Does Not Work

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#724]
It seems the `$ionicViewService.clearHistory();` method is not working.

Demo : http://codepen.io/quangpham/full/lkDzs - Navigate to a pet.  Click clearViewHistories, click "consoleLog".  All the histories are still there.   Click "All Pets".  Click another pet.  Click clearViewHistories.  Click "All Pets".  Notice the Back button visible now.

Reference:
http://forum.ionicframework.com/t/the-clearhistory-doesnt-clear-histories-data/1470/2

**Comment by sean-hill** [comment]
Any updates to this?

I'd like to do this

    // Don't allow back button on certain routes to navigate
    $ionicPlatform.onHardwareBackButton(function(e){

        if (state I dont want them to navigate back from) {
            $ionicHistory.clearHistory();
        }
        
    });

But the `clearHistory()` doesn't remove any of the previous histories.

**Comment by clawish** [comment]
:+1:

**Comment by yjukaku** [comment]
Does anyone know if this was ever fixed?

**Comment by pranaydutta89** [comment]
is this fixed ??

**Comment by jaumeavila** [comment]
When will it be fixed???

**Comment by sean-hill** [comment]
@yjukaku, @pranaydutta89, @jaumeavila I believe this is fixed with the latest version of Ionic. I have had no issues with it. The way I currently use it in my app is as follows:

	$scope.logout = function() {

		$storage.empty();
		
		$ionicHistory.clearHistory();
		$ionicHistory.clearCache().then(function(){
			$state.go('get-started');
		});

	};

**Comment by pranaydutta89** [comment]
@sean-hill  i tried ur solution still its not working after logging out it again tries to navigate to history

**Comment by sean-hill** [comment]
@pranaydutta89 I'm not sure what the problem is. Try this:

Navigate around your app for a while, then inspect the element. You should have a bunch of `ion-view`'s cached and such in your app because of the default Ionic behavior such as this:

![screen shot 2015-11-19 at 11 52 51 am](https://cloud.githubusercontent.com/assets/1205866/11280638/26923dda-8eb4-11e5-9e47-314355e124b6.png)

Then in some controller, call a function that includes this code:

    $ionicHistory.clearHistory();
    $ionicHistory.clearCache()

Then inspect your element again, there should no longer be any cached views, just one active view. If that's not the case, then I'm not sure what the full problem is, this is the best I can do to help.

**Comment by misaunde** [comment]
Just updated to: Ionic 1.7.10. Testing in the browser (chrome). 

Doing what you said, I see nav-view="active", instead of cached, but it's still navigating my history when I press back (in the browser).

I wasted about an hour trying to get it working using the browser, and then I got home, plugged in my phone, and it worked fine there (android). 

Thanks.
