### ISSUE TITLE
v2 beta.10 NavController.indexOf() returns -1 for Loading component

### ISSUE THREAD

**Issue by jasonwaters** [driftyco/ionic#7256]
In my app, the root component listens for loading events and instantiates a Loading component like this:

```
let this.loadingComponent = Loading.create({...})`;
this.nav.present(this.loadingComponent);
```

This happens in my root App component where nav is `@ViewChild(Nav) nav:Nav;`

Anyway, when loading stops, it attempts to destroy the loading component by doing something like this:

```
let index:number = this.nav.indexOf(this.loadingComponent);
this.nav.remove(index, 1).then(() => this.loadingComponent = void 0);
```

The problem is, indexOf always returns -1 for some reason.  This code worked great prior to beta.10.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We have refactored the loading component, along with all the overlay components, to not be part of the nav stack in the upcoming beta.11 release. We did this for multiple reasons including the fact that it makes them work like native components and that most of the issues related to overlay components were because they were part of the nav stack. This does mean that there are breaking changes though, and with those breaking changes I highly doubt your code will work. If you would like to check out these changes now you can install the latest nightly with `npm install ionic-angular@nightly`. If you check out our [api docs](http://ionicframework.com/docs/v2/api/) you will find early docs for those changes. You should specifically look at the LoadingController class. Sorry for any hassle this causes, but these breaking changes are definitely for the better. Thanks for using Ionic!
