### ISSUE TITLE
bug@v2: Opening Alert in platform.ready break rootPage rendering

### ISSUE THREAD

**Issue by HugoHeneault** [driftyco/ionic#7298]
#### Short description of the problem:
If I present an Alert before the page is rendered, the page stop rendering and when I close the Alert, I have a blank app. 

#### What behavior are you expecting?
Opening an Alert should not break page rendering.

**Steps to reproduce:**
1. Look at page1.ts (starting at line 22) on https://plnkr.co/edit/GXvKEOIVncqG7BWDe0KD?p=preview
2. If I add a timeout (eg: 100ms), to wait for view rendering, the issue is gone.

**Which Ionic Version?** 1.x or 2.x
2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 0.2.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Windows 7 SP1
Node Version: v4.4.5

Thank you guys for your great job, & keep going!

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Opening alerts and doing anything else ui related should not be done in the platform.ready() call. This is fired long before the ui is ready, which is why trying to open an alert fails here. If you would like to open an alert when the app first loads i would recommend opening it in our `ionViewDidEnter` [lifecycle](http://ionicframework.com/docs/v2/api/components/nav/NavController/#lifecycle-events) event in your first page. Thanks for using Ionic!

**Comment by HugoHeneault** [comment]
Thanks for your quick reply!

`ionViewDidEnter` doesn't seem to be triggered: https://plnkr.co/edit/GXvKEOIVncqG7BWDe0KD?p=preview

**Comment by jgw96** [comment]
Hey @HugoHeneault (: I made a more minimal plunker [here](http://plnkr.co/edit/RLq2dxy8uDNTaHA3kSk6?p=previewF) that shows the right way to do this. Hopefully this explains it better. Thanks!

**Comment by HugoHeneault** [comment]
Sometime it works, sometime it doesn't... But I'm not able to make it fail on your plunker... :(

**Comment by HugoHeneault** [comment]
This seems to happen only on web brower.
