### ISSUE TITLE
unable to  circle import for circle jump 

### ISSUE THREAD

**Issue by wanna950312** [driftyco/ionic#7345]
#### Short description of the problem:
when page class A import page class B, and page class B import page class A, 
to implement page A jump to page B, and page B jump to page A.
but it doesn't work well.

#### What behavior are you expecting?
 it could work well.

Ionic Version：2.0.0-beta.31

**Comment by ghenry22** [comment]
That creates an endless loop though.  A imports B imports A imports B imports A imports B... forever.

**Comment by wanna950312** [comment]
please tell me how to slove it?

**Comment by ghenry22** [comment]
You would really need to think about how you design your app in order to avoid circular dependencies.  I would suggest that you ask over at the ionic forums as that is the right place to look for help.  Maybe explain in more detail what you are trying to do there and see if people have some suggestions on how you could structure things differently.

Forums are here:
https://forum.ionicframework.com/

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
