### ISSUE TITLE
Ionic2 As regular Website

### ISSUE THREAD

**Issue by justme1** [driftyco/ionic#7376]
This is too basic but I can't find definite answer to this question:

I want to use Ionic2 app that will run on iOS / Android BUT I also want it to run as a regular website.

Is Ioinic2  fully supported to run as a website?

Please provide CLEAR answer as the web is full with misunderstanding on this subject.

Thanks

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! With Ionic 2 we are fully supporting the web (including eventual built in support for Progressive web apps) as a platform right alongside Android, IOS, Windows 10 and Electron. Thanks for using Ionic!

**Comment by galsch** [comment]
@jgw96 so just to verify I understand correctly:

There is no need to create 2 different projects for web and mobile and share the same logic? I can simply use the same project and assume it will work perfectly as a website as well?

Thanks

**Comment by jgw96** [comment]
@galsch Great question! Not exactly. If you are using certain cordova plugins that only work on native platforms then these will not work on the web, although if you are using [Ionic native](https://github.com/driftyco/ionic-native) they will fail gracefully. But if you stay away from using those certain plugins, or write logic to provide an alternative when on the web then it should work perfectly. Also, our browser support includes Chrome, Safari, Firefox, Opera(since its just chrome nowadays), and Edge. We do not support any version of Internet Explorer with Ionic 2. So basically, as long as you keep cordova plugins in mind, the same Ionic 2 project that works on your Android, IOS or Windows 10 device will work just as well in the browser. Thanks!

**Comment by galsch** [comment]
Great and clear answer, thanks!

Don't you even support IE 10?

**Comment by jgw96** [comment]
@galsch No problem! Nope, not at this time. Ionic 2 includes uses a lot of new HTML5 web standards that Internet explorer does not support, or does not support well, so as it stands now we do not officially support any version of Internet Explorer.

**Comment by smathson** [comment]
@jgw96 Can I suggest that you guys add a list of your officially supported browsers in a more prominent place in the documentation or repo readme? Especially with PWA support being a bigger part of Ionic 2, we got pretty far along in considering Ionic as a solution for a project of ours before discovering that Internet Explorer was not supported (which unfortunately is a deal breaker for us). Thanks!
