### ISSUE TITLE
Set margin in collection repeat items

### ISSUE THREAD

**Issue by jacquesdev** [driftyco/ionic#7381]
#### Short description of the problem:
I would like collection-repeat to support setting a margin between list items. I have used a hack to make this work for the moment but it's not pretty, and I will need to change it in the near future. Even if you could set 'margin' as an option for collection-repeat that would be great.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
I am officially creating an issue as mentioned in this forum post:
https://forum.ionicframework.com/t/how-can-i-set-margin-in-my-collection-repeat-item/19116

**Which Ionic Version?** 1.x or 2.x
I currently use ionic 1, but it would be super useful to have it in both.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! While we really appreciate this feature request, we are not currently planning on adding any new features to Ionic 1. Because of this I am going to close this issue for now. If you would like to see this feature added for Ionic 2 I would urge you to open a new feature request for Ionic 2. Thanks for using Ionic!

**Comment by jacquesdev** [comment]
@jgw96 - Hi there - as mentioned this would be great functionality in v2 as well, can you not simply change the label to v2, instead of me having to open a brand new issue?
