### ISSUE TITLE
Slides not working on Android

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#7408]
_From @AriGru on July 6, 2016 22:21_

Hello - I have built slides and they work on GenyMotion but we submitted the app and they do not work on Android. It shows I have one slide and will not scroll through. Is this being fixed?

_Copied from original issue: driftyco/ionic-preview-app#47_

**Comment by brandyscarney** [comment]
_From @danielmouraa on July 18, 2016 20:6_

I had the same problem...

**Comment by jgw96** [comment]
Hello @AriGru thanks for opening an issue with us! If you use `ionic serve` to deploy the app does it have the same issue in chrome?

**Comment by ethanmay** [comment]
I am having the same problem. I use the `ionic serve` command and I am using Ionic v. 2.0.0-beta.32. Have tested in Chrome, in browser and in emulator, and on the Ionic View app on Android, and only the first slide will display. The user cannot initiate the slide action and the bullet points that appear show only one slide in place. This functionality also happens when I am attempting to use the Slider in the [Ionic v2 docs](http://ionicframework.com/docs/v2/components/#slides).

**Comment by flew2bits** [comment]
I'm having the same problem. It works on android if the screen is rotated. I found that when using ionic serve, if I load it in Chrome and then resize the window, the other slides appear.

**Comment by flew2bits** [comment]
As a workaround, adding the following to a component that uses slides seems to fix the issue:

```
@ViewChild(Slides) slider: Slides;
ionViewDidEnter {
  this.slider.getSlider().update();
}
```

Slides is imported from "ionic-angular"

**Comment by jgw96** [comment]
Hello all! I can confirm that this has been fixed in the latest nightly and will be in the upcoming beta.11 release. Thanks for using Ionic!
