### ISSUE TITLE
Navigation not working with Tabs

### ISSUE THREAD

**Issue by waybackrider** [driftyco/ionic#7432]
See http://plnkr.co/edit/75V0tqqHOZHRwvm552rA

When clicking "navigate to Page2" the Tabs are overlayed by Page2. Clicking then "Navigate to Tab2" does not work at all. Same Problem on real Android Device.

When enabling Device Mode (use Ipad for space) in Chrome Desktop and reload plunker (F5), it starts working as expected. Also works on real Ios-Device, so seems MD-related

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. Because we follow the material design standards, by default tabs are hidden by new pages on Android devices. Therefore, while it is actually navigating to the correct tab, you cannot actually see it because the tabs are hidden. If you would like for tabs on Android to not be hidden by new pages you can set `tabSubPages` to `false` in your `ionicBootstrap`.  I have made a [plunker](http://plnkr.co/edit/uNF44cXqm8hIFarIa3nG?p=preview) that shows how to do this and gives a demonstration of how it works. Thanks for using Ionic!

**Comment by waybackrider** [comment]
Thats great thanks! But why does it behave differently in Device-Mode?

**Comment by jgw96** [comment]
@waybackrider Is tabSubPages not working for you on your Android device?

**Comment by waybackrider** [comment]
Yes it is! I meant Device-Mode in Chrome Desktop, there it also works without tabSubPages: false

**Comment by jgw96** [comment]
@waybackrider Sorry if im misunderstanding but do you mean device mode emulating an ios device, such as an ipad, in chrome?

**Comment by waybackrider** [comment]
@jgw96 yes, but now i see this uses ios theme, therefore it works as expected! Thank you!

**Comment by jgw96** [comment]
No problem!
