### ISSUE TITLE
Prevent ng-click When Scrolling

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#745]
When scrolling a list, items with `ng-click` are firing the click event.  They really should not fire as this was a scroll rather than a click / tap.

Example : http://codepen.io/calendee/pen/yqefG

Reference : http://forum.ionicframework.com/t/disable-click-onscroll-list/1334

**Comment by udeeps** [comment]
@adamdbradley , I am using ionic v1.1.1. The list item doesn't get highlighted when I try scrolling in Google Chrome. But when I run the app in Galaxy S4, Android 4.4.2, the item gets highlighted for a while when I scroll. The flicker is kind of distracting. However, it doesn't behave so in iPhone 6. The scroll would have looked smoother if that highlight wouldn't trigger. Is there any way to achieve this?

**Comment by cityzen** [comment]
I'm seeing this issue as well on a Nexus 5 with KitKat 4.4.3 and iphone 6 with ios 9.3.1. I am wrapping the whole list item as a link so the link area is fairly large. Either way, it is quite distracting while scrolling through items.

**Comment by charlesbedrosian** [comment]
I was having this issue still with ionic 1.7.16 when using an ion-list.  The fix was to put `has-bouncing="false"` on the ion-content tag.

Credit to http://stackoverflow.com/a/29911064/728379

**Comment by EmreErdogan** [comment]
I'm seeing the issue, too. Tested on iPhone 6 with iOS 10.2.1
I am ionic bundle version is 1.3.2.
I am also using cordova-plugin-crosswalk-webview@2.1.0 plugin.

For a workaround, I am using the solution offered in the following issue comment: https://github.com/driftyco/ionic/issues/1438#issuecomment-55434818

But the above workaround works only for list items. Of course it can be expanded to other elements, but you must bind the event handler to every clickable element in the page. Because every clickable element receives the click event when scrolling.

I am looking for a general approach that will apply to the whole application without code repetition.

Any ideas?

**Comment by kodeine** [comment]
i am getting this warning on

```
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.2
Node Version: v6.6.0
Xcode version: Not installed
```

**Comment by nidhi42** [comment]
can you all please help it out to find solution

**Comment by emonidi** [comment]
I'll see what I can do

**Comment by EmreErdogan** [comment]
The following solution may help: https://github.com/ionic-team/ionic/issues/1438#issuecomment-293602364
