### ISSUE TITLE
v2 range not draggable on safari

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#7454]
#### Short description of the problem:

You can't drag a slider on a range in Safari (web). However you can on Chrome. 

On Safari, you have to click a new position, and the slider moves. On Chrome you can both click a new position OR drag the slider. 

#### What behavior are you expecting?

Range slider should be draggable AND clickable both on Chrome and Safari and all devices.

**Steps to reproduce:**
1.  Go to http://ionicframework.com/docs/v2/api/components/range/Range/ in Chrome and use the example on the page there. Works. Try with Safari, doesn't work

**Which Ionic Version?** 1.x or 2.x
2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 5.4.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: 1.8.5 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Here are my findings from debugging this yesterday afternoon. After looking at this in the safari dev tools and in the chrome dev tools it seems that in safari/ios the pointerUp event and the pointerMove event are not firing on the correct element, while in chrome/Android they are. The correct element to fire events on is the handle of the slider, but instead in safari the pointerUp and pointerMove events get fired on `div.range-slider` which is the slider itself. It works when clicking around on the slider because pointerDown is actually firing on the correct element.

**Comment by brandyscarney** [comment]
Fixed by https://github.com/driftyco/ionic/commit/267ced618e4ac72ddb65ae4ea7be13fbc4b237a1. This will be in the `beta 11` release.
