### ISSUE TITLE
V2 ion-toolbar in ion-header disappears on transition

### ISSUE THREAD

**Issue by krizroring** [driftyco/ionic#7464]
When a page has a ion-toolbar in the ion-header, and you transition to a new page which also has a ion-toolbar in the ion-header, the 1st ion-toolbar gets blocked by the size of the toolbar on the next page. 

The same happens when navigating back, the toolbar on the 1st page is blocked, and only becomes visible after the transition has ended.

Created with the latest ionic v2 beta10

[![Ion-toolbar transition error video]](https://www.youtube.com/watch?v=0D9J_6u0bIQ "Ion-toolbar transition error")

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by krizroring** [comment]
After creating a plunker, i could not reproduce the problem. I turns out that my problem was that i had set a background color on the ion-header, and after removing that everything was correct again. 

Is it an idea to mention in the docs that the the main ion-header element should not have a background-color style set on it?

Greetings,
Kriz

**Comment by jgw96** [comment]
Hello @krizroring sorry for the delay on this, i have been very busy with the beta.11 release. Since this issue is now solved i will be closing this issue. Also, thanks for your docs suggestion, but the docs are not the correct place to cover small errors in implementation like this unless we have a large number of issues open about the same user implementation error. Hope I explained that well!
