### ISSUE TITLE
Input bottom borders missing when ion-item inside ion-row

### ISSUE THREAD

**Issue by daveshirman** [driftyco/ionic#7503]
#### Short description of the problem:

The usual bottom borders are missing from the inputs when the `ion-item` is nested inside the `ion-row` 
#### What behavior are you expecting?

Bottom border should be present

```
e.g

  <ion-item-group>
    <ion-item-divider>Some group:</ion-item-divider>    
    <ion-row>
      <ion-col width-80>
        <ion-item>
          <ion-label stacked>field 1:</ion-label>
          <ion-input></ion-input>
        </ion-item> 
      </ion-col>
      <ion-col width-10>
        <ion-icon danger ios="ios-sad-outline" md="md-sad" item-right></ion-icon>
      </ion-col>
      <ion-col width-10>
        <ion-icon primary ios="ios-flag" md="ios-flag" item-right></ion-icon>
      </ion-col>
    </ion-row>
  </ion-item-group> 
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Which Ionic Version?** 1.x or 2.x
2.x
#### Plunker that shows an example of your issue

http://plnkr.co/edit/dcnJTSPxVtdiFK9IHTno?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Davids-MacBook-Air:AppHazard daveshirman$ ionic info

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! May I ask what the use case is for using `<ion-row />` here? Thanks for using Ionic!

**Comment by daveshirman** [comment]
Because I'm using the grid components with rows and columns to align
buttons to the right of each input row.

Like a secondary action container related to the input field in that row.

**Comment by daveshirman** [comment]
Hey @jgw96, is there any update on this please? 
Thanks.

**Comment by brandyscarney** [comment]
Hey @daveshirman, so the issue here is that the `ion-item-group` looks for the `.item:last-child` and removes the border when it finds it. Since you are nesting the `ion-item` they are all falling into this use case and therefore the border is removed. If this rule were modified to only look for descendants then your app would look like the following:

![screen shot 2016-08-05 at 4 12 04 pm](https://cloud.githubusercontent.com/assets/6577830/17449275/8523628a-5b27-11e6-8525-037b3143ad74.png)

Is this what you are trying to achieve? Is there a reason you aren't using the `ion-item` with `item-right` on the icons and then modifying them that way? Something like this:

![screen shot 2016-08-05 at 4 16 14 pm](https://cloud.githubusercontent.com/assets/6577830/17449363/f67959b2-5b27-11e6-8228-dc779eab3b2d.png)

Where the icon could be styled to take up a specific width.

**Comment by daveshirman** [comment]
Hi @brandyscarney, thanks for your reply.

First of all, in the example you show, the icons are aligned differently, i.e. lower.
secondly, the input goes all the way to the end.

This is undesirable for several reasons:

- long text will flow past under the buttons.  Bad.
- ion-select controls (instead of a standard text input) make the right 2 buttons impossible to tap


Hence why I did the row and column thing, which reliably separates out the inputs from the buttons which have their own actions.

Does that make sense?

**Comment by brandyscarney** [comment]
Thanks for the quick reply, @daveshirman! Yes, that makes sense. The issue is it is hard for us to cover every possible use case. `ion-item-group` is really supposed to be used to group items with (optionally) sticky dividers, or take advantage of list reordering. Are you using `ion-item-group` for anything like this? Removing the `ion-item-group` wrapper would solve your problem immediately, but we can take a look into this some more.

**Comment by daveshirman** [comment]
Hey @brandyscarney, Yes I am using `ion-item-group` on a another page to facilitate list reordering in fact, e.g. a floor list (group) with items on the floor (to reorder).

I have changed the `ion-item-group` in this instance to a plain `<div>` and the problem is solved as you suggested. Thanks.

I know it must be difficult to catch all the use cases.  But I think organising a form like this is not an uncommon thing. E.g a barcode scanner icon next to an input field maybe. I can't be the only person to have done this?!

It's worth noting that using the `ion-item-group` in this case seems reasonable as the form contains lists of inputs for different logical groupings, see attached screenshot.  

![screen shot 2016-08-05 at 22 24 52](https://cloud.githubusercontent.com/assets/14280030/17451007/853a6e06-5b5b-11e6-92a1-5b1f93a32bc4.png)


Thanks again for your assistance.
