### ISSUE TITLE
feat: image placeholder before loading

### ISSUE THREAD

**Issue by jtushar53** [driftyco/ionic#7533]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,
It would be great to add spinner to ion-img before loading it fully.

it is also mentioned http://ionicframework.com/docs/v2/api/components/virtual-scroll/VirtualScroll/ in Images section 
Ionic provides <ion-img> to manage HTTP requests and image rendering. Additionally, it includes a customizable placeholder element which shows before the image has finished loading. 

Thanks</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#51
