### ISSUE TITLE
suggestion: add a warning for improper NavController usage

### ISSUE THREAD

**Issue by Kobzol** [driftyco/ionic#7543]
#### Short description of the problem:
If you present an overlay to the screen (alert, modal, loading etc.), you have to wait for it to complete before presenting any other overlay.
```javascript
toast.present().then(() => loading.present());
```
If the promise is not awaited and the other view is shown directly after the first:
```javascript
toast.present();
loading.present();
```
the application emits strange errors or it's UI breaks in a subtle way, which confuses users (see #7342 and #7449 #6209).
Could the NavController emit a warning when it detects this kind of improper usage?
I think that it could help with this problem, because it could be easily forgotten to await the promise.

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by jgw96** [comment]
Hello @Kobzol ! Thanks for opening an issue with us! While I very much appreciate your idea, because this is already mentioned in the [docs](http://ionicframework.com/docs/v2/api/components/nav/NavController/#nav-transition-promises), because we generally use warnings for only deprecated things and because it would be inconsistent to give a warning for incorrect usage of one part of the framework and not for other parts of the framework I am going to close this issue for now. Thanks for using Ionic!

**Comment by Kobzol** [comment]
Ok, I understand that. Could you at least add it to the FAQ? I've seen dozens of issues here that were facing this exact issue.

**Comment by jgw96** [comment]
@Kobzol that is not a bad idea. I am going to open an issue on the docs repo for this. Ill link it to this issue so that you can easily find it.

**Comment by Kobzol** [comment]
I'm curious, why did you move the present method from navcontroller to the individual overlay views? From a separation of concerns point of view it seems to me that the navcontroller should do the presenting, it could also batch the present calls to counter this type of wrong usage and it could support multiple navcontrollers (#7563).
