### ISSUE TITLE
bug: No Sidemenu on modal page

### ISSUE THREAD

**Issue by mpaland** [driftyco/ionic#7586]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Up to beta10 there was the possibility to present a modal page like this:
```
let modal = new ViewController(ModalPage, this.params);
this.nav.present(modal);

modal.onDismiss((data: any) => {
  if (data) {
    console.log(data);
  }
});
```
Why modal? Because of retrieving mandatory data from the modal page.
Problem: The ModalPage used the sidemenu of the app - up to beta10. In beta11 the sidemenu does not open anymore.
Meaning it opens but behind the modal page - which is an overlay now.

In beta 11 the nav.present() method is gone and got replaced by the (Modal)Controller.present().

For navigation is is required to use a sidemenu on a modal page. It is necessary to navigate from a modal page to a subpage via the sidemenu and navigate back to the modalpage which is dismissed then.
Therefore I consider taking away the nav.present() method as a bad idea - knowing why and for what intention you did that.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. So one of the main reasons we changed to our new overlay components api is that it matches native closer. In a native app with a sidemenu and modals (twitter for android, inbox by google are perfect examples) the sidemenu is not accessible from a modal. Because of this i would recommend either that you consider changing from using a modal to a page so that your user will still have access to the sidemenu or rethink the need for the user to have to use the sidemenu while in the modal. Sorry if this causes any hassle for you, but these changes were necessary to keep Ionic 2 more in line with native and what mobile users expect. Thanks for using Ionic!

**Comment by mpaland** [comment]
This should really be pointed out in the beta11 release notes / changelog!
