### ISSUE TITLE
Creating a new overlay in an other overlay handler is not possible

### ISSUE THREAD

**Issue by schankam** [driftyco/ionic#7596]
**Which Ionic Version?** 1.x or 2.x

2.x beta 11

#### Short description of the problem:

I have an ActionSheet overlay, containing one button (basically a delete action); In the handle of this button, I would like to pop a new Alert overlay (to ask for user confirmation for example). The Alert is showing up, but then we are stuck on it cause there is no effect when clicking on any buttons of the Alert Overlay.

#### What behavior are you expecting?

If I put the code of the ActionSheet button handle in a setTimeout function (tested with 1 second timeout), it is working as expected (The handlers of the alert buttons are called). I guess this is because the ActionSheet has not been popped out of the stack yet, and I am trying to insert a new overlay.

I am using ionic-beta11, but it was not working with beta 10 either. In the past, this behavior was working well (but I definetely have no idea from which version it stopped to work).

I attached 2 plunkers (one without the setTimeout, one with it) to illustrate the issue.

Both plunker are using beta10, but even with updating the ActionSheet/Alert to the new Overlay API (using AlertController, ActionSheetController), the same behavior is happening and it is also not working. (Sorry, couldn't get the plunker working with beta11...)

#### Plunker that shows an example of your issue

Not working example: http://plnkr.co/edit/umdrsPVELJkOhcLk2q2q?p=preview

Working example (using timeout hack): http://plnkr.co/edit/0LIXSGaE1KBfyUMO3DeP?p=preview

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As you can read [here](http://ionicframework.com/docs/v2/api/components/nav/NavController/#nav-transition-promises) all your navigation and presenting of components is async in Ionic 2, therefore you must wait on one transition to finish before starting the next. I have made a plunker [here](http://plnkr.co/edit/BIzR22HOZKFw09LPr0m6?p=preview) that demonstrates the correct way to use promises and events to achieve your use case. Thanks for using Ionic!

PS: the only change you will need for beta.11 is to use the new overlay API and use `onDidDismiss` instead of `onDismiss`. There is currently an issue with the issue plunker and beta.11 related to an npmcdn issue, but this should be fixed soon.

**Comment by schankam** [comment]
This looks indeed a much cleaner way to do it; Thank you for you help and keep up the good work !

**Comment by jgw96** [comment]
No problem and thanks for the kind words @schankam !
