### ISSUE TITLE
Ionic 2 backbutton issues with Android

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#7611]
#### Short description of the problem:

There are a few places where the back button behaves differently in an Ionic 2 app than in a native android app. This is a continuation of the discussion we had in our team meeting this morning.
- [x] In a native app when you have the sidemenu open and tap the back button it closes the sidemenu instead of closing the app. In ionic 2 it closes the app
- [x] In a native app with a sidemenu when you navigate to another page that is not the "home" page and then tap the back button it takes you back to the "home" page. Ionic 2 simply closes the app.
- [x] In a native app with tabs (youtube) no matter what tab you navigate too the back button will close the app. Currently in Ionic 2 we navigate back to the first tab when the back button is pressed.
- [x] Some users have expressed the desire to be able to stop the back button from closing the app in the situation where pressing the back button should close the app. I have mixed feelings about this as its generally considered bad ux to prevent a default operating system action and can seem "spammy" to stop an app from closing. Then again, I am not a ux expert 😄 .

**Which Ionic Version?** 2.0.0-beta.11

**Comment by Jyankey** [comment]
I am glad you brought this up. We've been building an app with ionic 2 for a while now, and have been conducting usability tests with a number of people; mostly university students who use android. Every single one of them (literally) is always confused about the behaviour of the back button. As far as my team is concerned, we see no advantage to the current behaviour since no one expects it.
As for the last point, if tapping the back button is supposed to close the app, then that is what it should do. Preventing it will be like stopping a desktop app from closing when a user clicks the close button. It's just confusing and even annoying to regular users. Just MHO.

**Comment by Kobzol** [comment]
I do agree that it is bad to prevent users from closing the app, but it may have some valid use cases. For example in my app, if I'm at a certain root view and I press the back button, I want to log out instead of closing the app. At least we should be able to react to the event, if not prevent it. It would be great if we could choose a backbutton behaviour when we need to and rely on the default behaviour otherwise (#7590).

**Comment by dylanvdmerwe** [comment]
As always, my advise is to follow the native paradigms as much as possible even if they do not make UX sense.

**Comment by rjv** [comment]
I think when you traverse through tabs it should not contribute to the overall navigation history. In other words, pressing back should not take me to the "previous" tab. Each tab page should essentially be treated as the root.

**Comment by jabas06** [comment]
Hello @jgw96, I've an issue with the sidemenu and backbutton but not sure whether it is the same issue you're describing here, because your are talking more about the app getting closed by the backbutton.

On Android,  when I have the sidemenu open, the backbutton always navigates back through the stack and only closes the app when the stack is empty.

In native apps the backbutton shall close the sidemenu.

**Comment by burhanyldz** [comment]
@jabas06 Yeah, that too. I had to use the following until this is fixed.
`  this.platform.registerBackButtonAction(()=>{
        if(this.menu.isOpen()){
          this.menu.close();
        }else{ ...

},1);`

**Comment by dylanvdmerwe** [comment]
Can we get this issue added into a milestone please? @jgw96 @manucorporat

**Comment by yannbf** [comment]
+1 to this, especially in regards to tabs history. Sidemenu closing is also a really important fix.

**Comment by John-Luke** [comment]
@jgw96 you can put the link of the commit that fix these issues?

**Comment by manucorporat** [comment]
@John-Luke 
Sidemenu:
https://github.com/driftyco/ionic/commit/8de253a9b1216c64eba53e87ca96febb72de42f0

Modal: 
https://github.com/driftyco/ionic/commit/5567191a45ab8e162e65c2b50c1ae324465455a9

**Comment by manucorporat** [comment]
@jgw96 
>In a native app with a sidemenu when you navigate to another page that is not the "home" page and then tap the back button it takes you back to the "home" page. Ionic 2 simply closes the app.

This is not something we can fix, but it should be in the developer-side. If the sidemenu `setRoot()` a different page, then it becomes the root page. Ionic can't make more assumptions here, if they want to navPop() to go back to Home, then they should use `nav.Push()` instead of `nav.setRoot()`

**Comment by graphefruit** [comment]
@manucorporat Sorry to grab into this closed issue.
If you use `nav.push` you'll get the next window with the back button, instead the `menu` - icon.
So the point everyone would need to do is to customize it yourself on the normal "root-pages" without having to see the `back-button`?

Thanks
Graphefruit

**Comment by yanxiaojun617** [comment]
https://github.com/yanxiaojun617/ionic2_tabs
or
http://www.jianshu.com/p/6aa5a8318092

**Comment by naveedahmed1** [comment]
> Some users have expressed the desire to be able to stop the back button from closing the app in the situation where pressing the back button should close the app. I have mixed feelings about this as its generally considered bad ux to prevent a default operating system action and can seem "spammy" to stop an app from closing.

What if an option is provided to let developer decide if they want to close the app or suspend it when back buttons is pressed? Pressing back button on Facebook and WhatsApp doesnt close the app rather it minimize the app.
