### ISSUE TITLE
Images are not showing on device in ios 10 [ionic 1]

### ISSUE THREAD

**Issue by kristiyandobrev** [driftyco/ionic#7622]
I have spotted some weird behaviour. I have recently updated my iphone 6 to iOS 10 (beta 4) and all the images in my app disappeared while running my app on a iOS device with `ionic run ios --device`. If a run the same for emulator everything seems to work fine and the images are shown. Another thing while do run the livereload like `ionic run ios --livereload', for both emulator or device everything works fine.  

Any ideas ? 

**P.S**

I found out the above is working on iphone 5 with ios 10 (beta 4) but not on iphone 6.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind posting about this issue [here](https://github.com/driftyco/ionic/issues/6901)? That is our tracking issue for IOS10 support. At this time, since ios10 is still beta, we do not officially support it, but we do plan on official support as soon as it hits stable and becomes the public release. Thanks for using Ionic!

**Comment by renjithvk** [comment]
### SOLVED

1. Add your images to `src/assets/imgs` directory

2. Set image path in **HTML** like
```<img src="assets/imgs/example.jpg">```
3. Set image path in **SCSS** like
```background-image: url(../assets/imgs/example.jpg);```

It will work **browser**, **emulator** and **build**

**Comment by loloDawit** [comment]
Same issue here. I’m getting the image dynamically from an api though. It works on google chrome but no image on iOS and safari
