### ISSUE TITLE
Beta-11: Menu white background overlay and not show menu list

### ISSUE THREAD

**Issue by nhohb07** [driftyco/ionic#7626]
![image](https://cloud.githubusercontent.com/assets/5916323/17525188/d82e3402-5e8b-11e6-8e73-e41f62f118dc.png)

Hi everyone! I try to build on ios app conference, the white menu error and no one menu item displayed. And my application is built from beta-9 was similar error, please review this issue to help me in the most recent version can build, I need this issue resolved urgently, thanks !

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-conference-app#226

**Comment by jgw96** [comment]
Hello! As this seemed to be an issue centered around the conference app and not the ionic framework itself i have moved this issue to that repo. Thanks for using Ionic!

**Comment by alexbainbridge** [comment]
I would love to know what the fix is. as I have a side menu app that has the same issue

However I had it down as a duplicate of https://github.com/driftyco/ionic/issues/7564 rather than something conference app specific so was waiting for that to be fixed to see if what I see is the same, or something different @jgw96
