### ISSUE TITLE
preloadTabs not working

### ISSUE THREAD

**Issue by chooble** [driftyco/ionic#7632]
In beta.11 (or beta.10, I updated from beta.9 to beta.11) the preloadTabs="true" is not working. And I couldn't find a post on the forum describing the issue. When you set it to true, everything on the first tab works. When you switch to another tab and push to a detail page it acts weird. Sometimes showing the tabbar. Sometimes loading the page transparent. No errors occur. When you don't define 'preloadTabs' everything works normal. 

works:
`<ion-tabs selectedIndex="1">`

doesn't work:
`<ion-tabs selectedIndex="1" preloadTabs="true">`

Steps to reproduce:
1. Start a new project --v2 tabs
2. make a button on the about page that pushes to another page (example HomePage).
3. tabs.html: `<ion-tabs preloadTabs="true">`.
4. ionic serve ->  go to about page -> push -> Page loads transparent.

**Comment by chocolei** [comment]
Simular here.

In my case, when I set 
`preloadTabs = true`

the follow
`tabsHideOnSubPages = true`
only affect to the one of default tab only,

on other tabs(example: second , third ...)
`tabsHideOnSubPages = true` 
seems like no affect and used the default value
`tabsHideOnSubPages = false`

when I remove `preloadTabs = true` 
everything is fine.

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic. We are currently actually thinking about getting rid of `preloadTabs` as most likely it wont be needed when aot compile hits (which should be in beta.12 as we already have it working nicely internally) because everything will be fast right out of the box. I will update this issue in a few days when we have decided.

**Comment by jgw96** [comment]
Hello all! We have decided for now that we are going to get rid of `preloadTabs` in beta.12 as it will not be needed anymore since all templates will be compiled ahead of time. Because of this i will be closing this issue for now. If for some reason we change out mind I will reopen this issue. Thanks for using Ionic!
