### ISSUE TITLE
Not able to resize content when using directive

### ISSUE THREAD

**Issue by dgroh** [driftyco/ionic#7645]
#### Short description of the problem:
We have an search icon in the navbar. When user clicks on this icon, the toolbar is shown with the Searchbar. The content inside `<ion-content>` has to be resized.

This works good, but we have a lot of pages referencing the **Searchbar** so that we had to create a directive to avoid code replication. The problem ist that in the directive is not possible to reference `@ViewChild(content)`

#### What behavior are you expecting?
I'm expecitng to be able to access de `Content` in a directive and that resizes works as it works in components.

**Steps to reproduce:**
1. Create a directive with a **Searchbar**
2. Reference the **Searchbar** directive (Searchbar should always be hidden) inside `<ion-toolbar>` of every page
3. Add an icon in the `<ion-navbar>` and on the click of the search icon the searchbar should be shown and the content should be resized

See the [Plunker](https://plnkr.co/edit/ayFskPyDRlpYDkMEapDL?p=preview)

**Other information:**

[StackOverflow](http://stackoverflow.com/questions/38872065/reference-viewchild-content-angular2/38872167?noredirect=1#comment65117113_38872167)
 
**Which Ionic Version?** 

2

#### Plunker that shows an example of your issue

https://plnkr.co/edit/ayFskPyDRlpYDkMEapDL?p=preview

**Run `ionic info` from terminal/cmd prompt:**

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local: Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS:
Node Version: v4.4.5

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Ion-content is not supposed to dynamically resize, although we do provide a resize method on Content that you can read about [here](
http://ionicframework.com/docs/v2/api/components/content/Content/#advanced). From looking at your plunker it does seem that you are getting a reference to content correctly. I would recommend checking out the [Angular docs](https://angular.io/docs/ts/latest/api/core/index/ViewChild-var.html) on ViewChild if you have any trouble with getting the reference correctly. Thanks for using Ionic! Since this is not really an Ionic issue, as everything is working as it should on the ionic side of things, and more of an issue with your custom directive I will be closing this issue for now.
