### ISSUE TITLE
bug: <ion-datetime> in Popover - Expression has changed after it was checked

### ISSUE THREAD

**Issue by barbsicle** [driftyco/ionic#7658]
#### Short description of the problem:
`ion-datetime` throws an exception when it is activated in a Popover. This could related to #7038 where it broke while a toast was up. 

#### What behavior are you expecting?

**Steps to reproduce:**
1. Create an `<ion-datetime>` in a popover
2. Create and present the popover with PopoverController
3. Click on the `<ion-datetime>` in the popover

#### Exception (from Chrome)
![error](https://cloud.githubusercontent.com/assets/17634303/17580526/e2253676-5fd1-11e6-9c7d-4e07f7fc9d14.png)
 

**Which Ionic Version?**
Ionic API: v2 Beta 11
Ionic CLI: 2.0.0-beta.36

#### Plunker
Working on it. Trying to find a beta11 one.

#### Ionic Info

````
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
OS: Windows 10
Node Version: v5.11.1
````

**Comment by jdepoix** [comment]
We just ran into this problem as well. We migrated to beta.11, hoping it would be fixed, since it was reported as fixed in #7038. But still, when opening a datepicker, while there is a `Toast` or some other "overlaying" undismissed component, we would get an error and the datepicker looked like shown in the initial issue.
We noticed, that we can work around this, by dismissing the `Toast` manually, before the datepicker is opened. Of course, this only is a temporary solution, but maybe this will help find the real issue, or is useful for anyone who has to get stuff working NOW (like we did ;)).

Since the `ToastController` has no `dismissAll()` or something of that kind (which should be considered btw, but that's another issue...), I implemented a service which makes sure that there's only one `Toast` at a time and keeps a reference to it, to be able to dismiss it. Then this service can be used to dismiss the current `Toast` when a `ion-datetime` is clicked:

toast.service.ts
```ts
@Injectable()
export class ToastService {
  private _toast: Toast = null;

  constructor(private _toastController: ToastController) {
  }

  // if you need something more flexible here, just pass a Toast object instead of a string
  public showToast(message: string): void {
    if (this._toast != null) {
      this._toast.dismiss();
    }

    this._toast = this._toastController.create({
      message: message,
      duration: 1800,
      position: 'bottom'
    });
    this._toast.onDidDismiss(() => this._toast = null);

    this._toast.present();
  }

  public dismiss(): void {
    if (this._toast != null) {
      this._toast.dismiss();
    }
  }
}
```

date-test.component.html
```html
...
<ion-datetime (click)="_toastService.dismiss()"></ion-datetime>
...
```

I hope this helps some!

**Comment by jgw96** [comment]
Hello all! Happy to report that this issue has been fixed and will be in the beta.12 release. We were causing https://github.com/angular/angular/issues/6005 to throw because of a errant binding on the backdrop of the toast component. This has now been refactored to use the `renderer` instead of a binding. Thanks for using Ionic everyone! Once a nightly comes out that includes this fix i will revisit this issue.

**Comment by barbsicle** [comment]
Just wanted to update with a workaround for my case (opening a semi-fullscreen overlay with a DatePicker inside) - using a Modal does not trigger the error and will be fully functional.

I do not think that this will still work with Toasts.
