### ISSUE TITLE
Delete & Options Don't Work with Reorder in Lists

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#768]
When the reorder option is included on ion-lists, the delete and other options do not show.

Forum # 1750 : http://forum.ionicframework.com/t/is-using-reorder-and-swipe-in-lists-broken/1750

Sample : http://codepen.io/calendee/pen/lcjHe

**Comment by Ionitron** [comment]
Greetings @calendee!

Sorry but this issue may no longer be applicable to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
