### ISSUE TITLE
bug: Popover wrong location with position absolute

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#7686]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have block of images, the block has position absolute with bottom 0.
When I click on any image - popover should be open from the image, the real results it's that the popover opens in the location that the block has to be without the position absolute.
Demo here:
https://drive.google.com/file/d/0B_2AM8ZhXhE9WGJVMmFZRHBHdFE/view

One more problem: below the range the border-bottom is not fully, and there is blank space in the bottom of any popover. why is that happening?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So unfortunately the first issue is not something that we can really control. We do allow passing through the position so that the developer can adjust the positioning of the popover using those values, so i would recommend playing with that to get your popover positioned correctly. The second issue is actually just the default styling of our list component, if you put the `no-lines` attribute on your `ion-list` element that will get rid of the borders and the bottom margin can be adjusted with css. Thanks for using Ionic!
