### ISSUE TITLE
Does not work with packages that require Angular2 rc5

### ISSUE THREAD

**Issue by GarettRogers** [driftyco/ionic#7740]
I am trying to use AngularFire2 -- but it requires Angular2 RC5.  The older version of AngularFire2 which works with RC4 is missing some important functionality that has been since resolved in the latest version.

The reason I am posting the issue here is because it is more justifiable to look for Ionic to update than to get the AngularFire guys to downgrade.

Ionic 2 => Angular2 RC4
AngularFire2(beta2) => Angular2 RC2 (compatible, but contains bugs that make it unusable for authentication)
AngularFire2 => Angular2 RC5 (fixes the bugs, but is not compatible with Ionic 2)

Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! We have already updated to Angular 2 RC5 internally and the beta.12 release will be running on RC5. While we try our best to stay up to date with the latest version of Angular 2, because each version has changes (and rc5 has a good amount of changes, all awesome changes though) we have to update the framework to work with these changes. This usually means that Ionic 2 is one version behind. Now, when Angular 2 hits stable and their are not as many changes between each version of Angular we should be able to update much faster. Thanks for using Ionic and sorry for any hassle this causes!

**Comment by moneal** [comment]
Are the changes for beta 12 and rc5 support posted anywhere? The updates to angularfire2 are critical to get authentication working with ionic.

**Comment by jgw96** [comment]
Hello! Good question! Beta.12 with Angular rc5 is actually not released yet as we are redoing our build process to support Ahead of time compile which finally became a thing in rc5, and it is still a work in progress as their were a'lot of internal changes in Angular 2 with rc5 which means that we have to refactor alot of internal stuff too. Its all good changes though, especially for performance!

**Comment by pradyumnaswain** [comment]
Waiting anxiously for Ionic Beta. 12. Good days ahead

**Comment by scottwittrock** [comment]
Plus one to @pradyumnaswain's comment. Can't wait for beta 12.

**Comment by bsakweson** [comment]
Plus one to @pradyumnaswain's comment. Looks like there are lots of interesting stuff coming up in that release.

**Comment by iBasit** [comment]
Any date to when we will have Beta 12?  We can't install another private library, which uses rc.5.  And looking at this ticket, its already been 30 days and still no update to when it will be relased.

Any dates please?  We are basically stuck, until the upgrade :/
