### ISSUE TITLE
Ionic 2 beta 11 Firefox http json bug (?)

### ISSUE THREAD

**Issue by theromis** [driftyco/ionic#7755]
I'm using django rest framework which sensetive to "accept" header.
My app doesn't work in latest (48.0) firefox.
The reason because of http request:
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
```
it not specifying "JSON"

example header for ionic 1 in the same firefox
```
Accept: application/json, text/plain, */*
```

my code snippet:
```
import { Http } from '@angular/http';
....
  constructor(private http: Http, .....) {
....
      this.http.get('https://host/path')
```

is it expected behavior?

**Comment by jgw96** [comment]
Hello! Thanks or opening an issue with us! In Angular 2 (and Ionic 2) you can set your own headers so that it will work with your python backend. I recommend checking out the [http docs](https://angular.io/docs/ts/latest/guide/server-communication.html) on the Angular 2 site for examples of how to do this. Thanks for using Ionic!
