### ISSUE TITLE
feat: Range in alert

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#7768]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Kust like prompt, but instead of text input - range input, and option to add the number(ngModel) beyond the range (optional of curse)</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by Alexinhoo** [comment]
Any news about this?

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#53
