### ISSUE TITLE
feat: ClearInput / autoselection in alert input

### ISSUE THREAD

**Issue by mosca90** [driftyco/ionic#7846]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Feature that allows ClearInput or automatically selection of text when user open an alert.

An exemple:
https://forum.ionicframework.com/t/how-to-add-clearinput-or-autoselection-text-in-alert-inputs/61346

Thank you and sorry for my little english!</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#55
