### ISSUE TITLE
ionic-datetime with different locale support v2

### ISSUE THREAD

**Issue by uzumakinaruto123** [driftyco/ionic#7883]
It would be great if datetime supported different locales. 

Similar to [Angular-moment-picker](http://indrimuska.github.io/angular-moment-picker/)

I recommend checking that repo. Very customizable and supports most of the locales out there.

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit?usp=sharing). I have posted this feature request there and we will be closing this issue for now. Thanks!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#60
