### ISSUE TITLE
ion-segment unstable with InAppBrowser

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#7886]
#### Short description of the problem:
ion-segment doesn't work if opening InAppBrowser from tabs

#### What behavior are you expecting?
ion-segment should work

**Steps to reproduce:**
1. Just open InAppBrowser from ion-tab
https://github.com/aggarwalankush/ionic-inappbrowser-issue/commit/771c48e8a8cb260877e4a170d31bc5bff70ca857
see changes in tabs.html and tabs.ts
 

**Which Ionic Version?** 
Ionic 2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.1.0
Xcode version: Xcode 7.3.1 Build version 7D1014 

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/8744282/18024165/dc38d4d2-6bb8-11e6-84a2-45cbe797cf59.gif)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! At this time we do not support using tab buttons for anything other than navigating to tabs because of this issue https://github.com/driftyco/ionic/issues/7769. Also, as this is the same bug as that issue I am going to be closing this one as a duplicate. Thanks for using Ionic!
