### ISSUE TITLE
Using ion-reorder-button with orderBy in ng-repeat

### ISSUE THREAD

**Issue by sarahsga** [driftyco/ionic#7900]
I have an array of objects. Each object in the array has a "displayOrder" key.
```
var items = [
  {
    name: "",
    displayOrder: 8
  },
  {
    name: "",
    displayOrder: 2
  },
  {
    name: "",
    displayOrder: 5
  },
  {
    name: "",
    displayOrder: 1
  },
  
];
```

I have to display the items in order of their "displayOrder" key. So, I use groupBy:
```
<ion-list class="symp-list" show-reorder="true">
  <ion-item ng-repeat="item in items | orderBy: 'displayOrder'">
    <div class="list list-inset" >

      <div class="item item-divider">
        {{item.name | uppercase}}
      </div>
      <div class="item  enable-pointer-events" >
        
        <ion-reorder-button class="ion-navicon" on-reorder="moveItem(item, $fromIndex, $toIndex)">
        </ion-reorder-button>

      </div>
    </div>



  </ion-item>
</ion-list>
```

```
$scope.moveItem = function(item, fromIndex, toIndex) {
      //Move the item in the array
      $scope.items.splice(fromIndex, 1);
      $scope.items.splice(toIndex, 0, item);
    };
```

But this just won't work. It gives me the error

> errorError: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Angular is throwing this error because somewhere in your data set their is a duplicate identifier. To fix this issue you can use `track by`. [Here](https://docs.angularjs.org/error/ngRepeat/dupes) is a handy link to the docs for that. Since this is a bug with your code and not something that Ionic is doing wrong I am going to close this issue for now. Thanks for using Ionic!
