### ISSUE TITLE
Failure trying to install ionic@1.3.1

### ISSUE THREAD

**Issue by tyronedougherty** [driftyco/ionic#7906]
Hi,
I'm experiencing issues preventing me from installing Ionic at version `1.3.1`. When I run `sudo npm install ionic@1.3.1 -g` I get the following response back:
```
npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504
npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504
npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ionic@1.3.1" "-g"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.7
```

It appears that [https://registry.npmjs.org/i/-/i-0.3.2.tgz](https://registry.npmjs.org/i/-/i-0.3.2.tgz) no longer exists on the NPM registry. I don't want to use the Ionic 2 Beta release which seems to install fine but has it's own issues. Anyone got an idea of how to fix this?

**Comment by mhartington** [comment]
That would be the CLI version. Are you trying to install the framework? 

Try this 

```
npm install ionic-angular@1.3.1 --save
```

**Comment by tyronedougherty** [comment]
**facepalms**

It appears I'm an idiot. Thanks so much @mhartington! 😄

**Comment by wendellpalazzo** [comment]
Hey guys... the command:
npm install -g ionic@1.3.1 has not working.. 

because this package i-0.3.2.tgz not exists in npm... 
causing error 404!

and package need update to 0.3.3
according this: 

NOTE: 0.3.2 was accidentally unpublished from the server and npm doesn't allow me to publish it back. Please upgrade to 0.3.3

see more: https://github.com/pksunkara/inflect
