### ISSUE TITLE
Android back button actions when using Searchbar 

### ISSUE THREAD

**Issue by elless** [driftyco/ionic#7937]
#### Short description of the problem:
The Android back button isn't behaving as we would've wanted when searching.
When searching (and keyboard is closed) clicking on the Android back button results in navigating back to the previous page.
 
#### What behavior are you expecting?
When searching (and keyboard is closed)
1. First click: Cancel search
2. Second click: Navigate back to previous page

**Which Ionic Version?** 2.11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
OS:
Node Version: v4.4.5

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! After testing a few native Android apps (youtube and inbox by gmail) it seems as if the behavior Ionic uses (closing navigating back a page when the keyboard is closed and searching) is the same behavior as native. Because of this i will be closing this issue for now. Thanks for the suggestion though!
