### ISSUE TITLE
Upgrade cdnjs

### ISSUE THREAD

**Issue by John-Luke** [driftyco/ionic#7956]
I would like to use the latest upgrade of the beta of ionic 2 in my web app

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Because Ionic 2 has build steps through our Ionic cli we recommend that you use the cli to build Ionic 2 apps instead of including it through a cdn. If you do want to use it through a cdn you can get it from npmcdn, but it will not work out of the box. I recommend checking out our [getting started guide](http://ionicframework.com/docs/v2/getting-started/) for instructions on how to use the cli to start an Ionic 2 app. Thanks for using Ionic!
