### ISSUE TITLE
Add enableBackdropDismiss to LoadingController

### ISSUE THREAD

**Issue by imgx64** [driftyco/ionic#7975]
This is a feature request for Ionic 2. I would like to have `enableBackdropDismiss` in `LoadingController`, similar to the same feature in `AlertController`.

My use case is cancellation. Let's say the user started a long-running task (such as uploading a file) and the app showed a loading dialog. The user should be able to tap outside the loading dialog to cancel the upload. I can handle the cancellation from the code, but the LoadingController blocks all user interaction.

Another approach for this use case is to add a way to put a spinner inside an Alert dialog. For example, a `content` property which can be set to arbitrary HTML (`<ion-spinner>`, etc.).

**Comment by askona** [comment]
Hi, is there is a way to prevent alert dismiss when pressing back-button with enableBackdropDismiss = false; ? @jgw96

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#61

**Comment by imgx64** [comment]
@jgw96 I implemented this. Please see the PR.
