### ISSUE TITLE
ionic2 - bug(toast, tabs) - Toast displayed on a tabs page displays on top of the tabs

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#7993]
#### What behavior are you expecting?
I expect the toast to display above the tabs instead of on top of them. The transition will probably have to change as well so that it will be smooth moving up from the bottom of the screen further than it used to.

**Steps to reproduce:**
1. Create a tabs page
2. Display a toast
3. Observe that it is displayed on top of the tabs
 

**Which Ionic Version?**
2.0.0@beta-11

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This is actually the desired behavior since the toast is "app-level". iOS does not have a native toast component, but on native Android the toast will always overlay no matter what elements are underneath it. But, we do have a position parameter that you can pass to the toast that will allow you to open a toast in the center or the top of your app. Because this is desired behavior I am going to close this issue for now. Thanks for using Ionic!

**Comment by zakton5** [comment]
Alright, thanks for the clarification!

**Comment by jgw96** [comment]
Also, here is the link to the docs regarding toast positioning. I meant to put this in my above comment but did not. Sorry about that! http://ionicframework.com/docs/v2/api/components/toast/ToastController/#positioning

**Comment by jabas06** [comment]
Hello @jgw96. I think this issue should be open. At least on android, the native behaviour is to show the toast  above the tabs.

Yo can take a look to the official photos app from Google. [https://play.google.com/store/apps/details?id=com.google.android.apps.photos&hl=es](url)
![screenshot_20161103-095345](https://cloud.githubusercontent.com/assets/3453385/19974160/20a25b8c-a1ad-11e6-8120-bbb70b1d90fd.png)
