### ISSUE TITLE
Feature Suggestion: Animations for Cards and List items

### ISSUE THREAD

**Issue by chandanch** [driftyco/ionic#7999]
In native Android apps we add animations to lists and cards. We can also add the animation on scroll as well to get the next cards or list items. The same fature is available is iOS native as well. Refer to this videos on Android & iOS. https://youtu.be/GYKjdx9I0Uw https://youtu.be/iO_F2m3Wwos Henceforth, This will be a great feature if added in ionic2. This will give ionic more native touch.

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#62
