### ISSUE TITLE
ionic lib 1.3.1 can write css out of <ion-view>

### ISSUE THREAD

**Issue by wzhsh90** [driftyco/ionic#8028]
my html content :  
<style type='text/css'>
xxx
</style>
<ion-view>
xxx
<ion-view>
before ionic lib version 1.3.1

the View's LifeCycle Events work well but when I upgrade the version to 1.3.1 things get worse.
View's LifeCycle Events  does not work.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind reopening this issue? It seems as if your code samples did not get rendered correctly, and the title of this issue does not match the content of it. Because of all this I am going to close this issue for now and ask that you reopen a new one. Thanks for using Ionic!

**Comment by wzhsh90** [comment]
Hi, I am so sorry to you I forget escape the html , so you can not see my html code.
I writen  a codepen ' http://codepen.io/wzhsh90/pen/pEjZXw '
you can find info from console.
the only different piont between function A and function B  is their html.
'
<style type="css/text"></style>
<ion-view></ion-view>
'
function A not work well ,function B work correctly.
