### ISSUE TITLE
Logic bug about ionViewDidEnter?

### ISSUE THREAD

**Issue by tfirer** [driftyco/ionic#8039]
#### Short description of the problem:
As mentioned in [#7843](https://github.com/driftyco/ionic/issues/7843)。the ui related things should put in the ionViewDidEnter event. but i'm not sure is these scene had been talk about?
1: When enter a new page(like a list page), i will init data from my server with a loading component, so i put this logic in ionViewDidEnter event
2: after going to another page(like a detail page), i will back to the list page, at this time i don't need to refresh the data. when put the init logic in ngOnInit event, it won't progress again, but when in ionViewDidEnter enent the logic progress again.
3: now i solved these just with a tag

#### What behavior are you expecting?
when back to the list page, the init logic won't progress again

Tips: please forget my pool english`(*∩_∩*)′

**Comment by ne6toto** [comment]
Well, from the issue you referenced you can see the link to the ionic 2 [lifecycle events](http://ionicframework.com/docs/v2/api/components/nav/NavController/#lifecycle-events) and there you can see that it is recommended to put setup code in the ionViewLoaded if you want that code to run only once. In the other issue ionViewDidEnter was mentioned because that was more suitable for that application.

Also this seems more like a support question so it is a good idea to ask it in the [ionic forum](https://forum.ionicframework.com/c/ionic-2) instead.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
