### ISSUE TITLE
NavControll stuck when pushing pages with insertPages and poping them out,

### ISSUE THREAD

**Issue by royipressburger** [driftyco/ionic#8042]
#### Short description of the problem:
Im trying to push multiply pages using insetPages.
Im pushing the pages to the top of the stack.
Everything works great until im starting to pop out the pages..
All the pages are poping out good but when the first page that was inserted is on the top of the stack the application stuck!

#### What behavior are you expecting?
the pop should not change his effects

**Steps to reproduce:**
1. create a page with a button that will insertPages, try more then 5 pages to insert
2. start clicking the back button on each inserted page.
3. the app will stuck

```js
  pushPages(i) {
    let pagesToPush = []
    for(let x=0;x<=i;x++) {
      pagesToPush.push({page: ContactPage, params:{pageNumber: x}})
    }

    this.navCtrl.insertPages(this.navCtrl.length(), pagesToPush);
  }
```
**Which Ionic Version?** 1.x or 2.x
2.x

#### Plunker that shows an example of your issue
I was not able to reproduce on plunker but was able by creating a new project.
https://github.com/royipressburger/navControll-error-example
This one is just clone of the starter tabs.
just clone it and run serve --lab

click on one of the buttons..
You will see that when pushing 1 or 2 pages all is good but when pushing 3, the app stucks.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v5.10.0

**Comment by rcjsuen** [comment]
I cloned the project and was able to reproduce the problem as well.

I may be wrong but the z-index may be the problem here. When you start popping the pages by going through the back button, the z-index of the first page (99) is less than the original home page's (100) so the home page ends up rendering on top of the first page. If I alter the z-index in the debugger to 101, the page is rendered correctly.

**Comment by royipressburger** [comment]
Hi @rcjsuen thanks for taking the time.. your answer looks good for a temporary solution, do you think its intentional behavior?

**Comment by rcjsuen** [comment]
@royipressburger I'm not sure. From looking at the code, I can't decide which solution is desired. I think that either of the following should happen...?

1. The code should consider the views "in between" the view being exited from and the view being entered and offset the Z-index accordingly. In this case, the three views would have a Z-index of 101, 102, and 103 accordingly.

2. The code should, instead of considering the Z-index of the view being exited from, take into account the (real?) view (in this case, the "home page") that's now the previous node in the stack and just offset it by one from there. In that case, all three pages would just have a Z-index of 101.

The relevant code is from `ionic/src/navigation/nav-util.ts`.

```typescript
export function setZIndex(nav: NavControllerBase, enteringView: ViewController, leavingView: ViewController, direction: string, renderer: Renderer) {
  if (enteringView) {

    leavingView = leavingView || nav.getPrevious(enteringView);

    if (leavingView && isPresent(leavingView._zIndex)) {
      if (direction === DIRECTION_BACK) {
        enteringView._setZIndex(leavingView._zIndex - 1, renderer);

      } else {
        enteringView._setZIndex(leavingView._zIndex + 1, renderer);
      }

    } else {
      enteringView._setZIndex(nav._isPortal ? PORTAL_ZINDEX : INIT_ZINDEX, renderer);
    }
  }
}
```

**Comment by rcjsuen** [comment]
I thought about the issue some more and it seems to me like the most straightforward solution would be to just iterate over the navigation stack and record the highest Z-index out of all of the views. Once we have that, we can then increment that value by one and set that value as the Z-index of the entering view. That would most certainly ensure that the entering view is visible to the user as it would have the highest Z-index value out of all the views in the navigation stack.

I feel that this is the simplest solution that guarantees a valid Z-index but I'm not sure if performance is a concern here given that we are iterating over the entire navigation stack. Perhaps we should alternatively be storing this maximum Z-index value as a member variable within NavControllerBase?

**Comment by royipressburger** [comment]
@jgw96 Any news regarding this issue?

**Comment by royipressburger** [comment]
Cannot reproduce this issue with rc.1 closing for now
