### ISSUE TITLE
Ionic 2 Tabs preload not working

### ISSUE THREAD

**Issue by anteburazer** [driftyco/ionic#8049]
#### Short description of the problem:
I have app with welcome screen and tab screens. Ones you choose an option on welcome screen you're beign redirected on one of the tab pages. Every tab pages contains ```<ion-content></ion-content>``` tag where I put my content in. I tried to set ```preloadTabs="true"``` attribute on ```<ion-tabs>``` tag, in order to initialize tab pages more quickly, and the following error shows up:

```Uncaught TypeError: Cannot read property 'style' of undefined ```

After this error the application stops working and tabs not reacting any more.

**Stacktraces and suggestions how to fix:**

I did some debugging and this is what I have found. An error appears here: https://github.com/driftyco/ionic/blob/master/src/components/content/content.ts#L581 because ```scrollEle``` is undefined. It's undefined because it's not being set here https://github.com/driftyco/ionic/blob/master/src/components/content/content.ts#L169 for every page inside the tabs navigation, but only for the first one. ```ngOnInit()``` function from ```Content``` class is being entered before every ```ngOnInit()``` function from Tab pages fires.
Since ```ngOnInit()``` function from Tab pages doesn't fire (except the first one), ```scrollEle``` is undefined for all pages inside Tab navigation, except the first one.

#### Expected behavior?
I Expected that every Tab page is initialized, so that ```ngOnInit()``` is being triggered in every Tab page class. I also expected that Tab pages will be initialized before user enters Tab navigation, when he's still on welcome screen. This would be very helpfull because app is very slow when user enters Tab navigation for the first time, when pages have not been initialized yet.

**System information**

Cordova CLI: 6.2.0
Gulp version:  CLI version 0.2.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS:
Node Version: v4.4.7

**Comment by jgw96** [comment]
Hello! We are actually removing the `preloadTabs` feature in the upcoming beta.12 release as it will not be needed anymore because we are using AOT compile. This means that tabs will be initialized even faster than the `preloadTabs` feature enabled, and get rid of the buggyness that `preloadTabs` could cause. Thanks for using Ionic!

**Comment by anteburazer** [comment]
Thanks for your quick response.
When we can expect beta.12 to be in production?

**Comment by jgw96** [comment]
soon 😃 . Here is the branch where most of the work is going on https://github.com/driftyco/ionic/tree/ngmodule-build. Thanks!

**Comment by glemiere** [comment]
I disagree. PreloadTabs would still be useful now.
I'm struggling since a while to make an home made tabs preloading without being unsync to the latest ionic version.
In my case I have a 50% transparent header turning white when I move to another tab because of the superposition of both headers on both pages during the transition.

It happens only the first time because `document.querySelectorAll('.scroll-content')[0]`, `document.querySelectorAll('.scroll-content')[1]`... is not cached and takes a few ugly milliseconds of time to load EVEN AFTER AOT.

To solve this problem the cleanest way I need to preload my tabs. It's a bit frustrating that it has been removed as it's forcing me to pollute my project with what was before unnecessary code.

Tabs should be able to be preloaded and it should also be the default behavior. Seeing that this feature has been implemented and then removed is extremely disappointing.
