### ISSUE TITLE
Ionic2 - Can't use ion-select while toast is still active

### ISSUE THREAD

**Issue by kazigais** [driftyco/ionic#8118]
#### Short description of the problem:
App crashes if I open ion-select while toast is still active.

#### What behavior are you expecting?
Open the ion-select.

**Steps to reproduce:**
1. Create ion-select
2. Add toast in constructor
3. Select something while toast is still floating

```


**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
![screen shot 2016-09-19 at 13 52 34](https://cloud.githubusercontent.com/assets/9280636/18629804/c057f084-7e70-11e6-9d97-69e476c8f672.png)


**Which Ionic Version?** 1.x or 2.x
2



**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v0.12.4
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! So the first issue here is that you should not open overlay components or do anything else UI related in the constructor of a component in Angular 2 / Ionic 2. The constructor is called before the template has been rendered. You can use our [Lifecycle events](http://ionicframework.com/docs/v2/api/components/nav/NavController/#lifecycle-events) to call logic when the template loads using `ionViewDidLoad`. The second issue is a navigation bug in beta.11 that i can confirm has been fixed in beta.12. Thanks for using Ionic!
