### ISSUE TITLE
iframe KO when emulating on iOS

### ISSUE THREAD

**Issue by mcornillon87** [driftyco/ionic#8173]
When using iframe on a page and emulating it on IOS the iframe is not working.
The same code works properly when serving it on my laptop, when emulating it on Android and when using Ionic View App.

**Steps to reproduce:**
1. start a blank Ionic v2 app
2. Add to the template file : 

`<iframe width=100% height=100% src="http://ionicframework.com/docs/v2/cli/build/" frameborder="0" ></iframe>`

3. emulate on IOS

**Which Ionic Version?** 
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.7 
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.12.0
Xcode version: Xcode 8.0 Build version 8A218a 

Thanks

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is most likely failing because you are making a call to an non-secure url (http). iOS does not allow calls to non https endpoints, including for iFrames. Would you mind trying an https url in your iframe? Also, if you can get around it we always recommend to not use iFrames in your Ionic app asiFrames have security issues and generally do not behave well on mobile. Thanks!

**Comment by mcornillon87** [comment]
Thanks a lot for the advice! I will stop using Iframe and use Cordova Inappbrowser instead... and I'll read about apps security... (I'm new to developing apps)

And thanks for making app development so easy with Ionic :)

**Comment by jgw96** [comment]
No problem at all! Welcome to the Ionic world!
