### ISSUE TITLE
Scroll component should have Content scroll features

### ISSUE THREAD

**Issue by Manduro** [driftyco/ionic#8215]
#### Short description of the problem:

The Content component has a lot of scroll-related features that would be really useful for the Scroll component as well. A few examples:
- `no-bounce` attribute
- `scrollTo(x: number, y: number, duration: number = 300)`
- `scrollToTop(duration: number = 300)`
- `getScrollTop(): number`
- `setScrollTop(top: number)`
- `scrollToBottom(duration: number = 300)`
- `getScrollElement(): HTMLElement`
- `onScrollEnd(callback: Function)`
- etc.
#### What behavior are you expecting?

It would be great to have these features available on the Scroll component as well.

**Which Ionic Version?** 2.x

**Comment by AishApp** [comment]
Agree with @Manduro . I have a page that should zoom in and zoom out along with scrolling Y. When the user reaches the end of screen, i want the user to get scroll to top on some option. Currently it works only in content and not when i use ion-scroll. Adding this feature would be great.

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#66
