### ISSUE TITLE
Page specific scss class not being applied to the ng-component

### ISSUE THREAD

**Issue by danielgek** [driftyco/ionic#8291]
#### Short description of the problem:
In the css file of each page you have the "root rule",
example in a fresh app:
```
.home-page {

}

```
if i change it to:
```
.home-page {
  h2{
  	color:red!important;
  }
}

```

the style for this specific page is not applied because as you can see in the screenshot below the class is not applied to the `<ng-component>` tag:

[![screenshot](https://s22.postimg.org/vc0ys0fz5/Captura_de_ecra_2016_09_29_a_s_12_55_48.png)](https://postimg.org/image/jmwz41p0d/)
#### What behavior are you expecting?

**Steps to reproduce:**
1. add style class to the specific tag

 
**Which Ionic Version?** 2.0-rc0

btw the plunker template for issues is outdated

**Comment by developerslearnit** [comment]
@danielgek did you add .home-page class to the pages ion-content?

I did and it worked.

**Comment by danielgek** [comment]
@developerslearnit while that work, past versions of the framework do it automatically  and i think the ionic team want it to work automatically.

**Comment by danielgek** [comment]
i'm actually tying to fix this in the framework but, it's hard because i started to work with ionic recently

**Comment by danielgek** [comment]
@mhartington @jgw96 can some one of the team confirm that this is a bug or the desired behavior ?

**Comment by danielgek** [comment]
i have a fix already, i can submit a pull request

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is actually caused by a change in the framework. Components used as pages should now have selectors added to them manually for scoped sass. Adding these selectors automatically as we have done in the past was too unreliable, especially on older Android.  I have added a note about this to the [changelog update steps](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-rc0). Thanks!

**Comment by danielgek** [comment]
ups haven't thought about this that way, thanks !!
