### ISSUE TITLE
[Feature Proposition] Shared ion-navbar across tab pages

### ISSUE THREAD

**Issue by SharkyLV** [driftyco/ionic#8301]
In Ionic2, for a tabber with a toolbar, every tab page must implement`ion-navbar` which leads to duplicate code. 

Although this could be wrapped in a component, it is still re-drawn on every tab which seems wasteful as `ion-navbar` is usually static across pages.

Would be nice, if could create a shared `ion-navbar` and only re-draw the `ion-content` part of the page. 

This would be very similar to how Android works with a single Toolbar but multiple Fragments that are swapped in a content holder.

**Comment by jgw96** [comment]
Hello! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#68
