### ISSUE TITLE
Improve logic to remove console.debugs from dist

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#8483]
This whole function is a short term solution.

https://github.com/driftyco/ionic/blob/master/scripts/gulp/tasks/release.ts#L35

Basically, let's change this to something to account for multiple line debug statements.

**Comment by manucorporat** [comment]
I don't think we have to generate the whole AST to remove a `console.debug()` statement. We could just create a simple state machine to do it.

**Comment by danbucholtz** [comment]
What'd you have in mind, @manucorporat?

Thanks,
Dan

**Comment by mattlewis92** [comment]
As long as it's es2015 and not typescript source, babel should be able to handle this 😄  https://babeljs.io/docs/plugins/transform-remove-console/

**Comment by danbucholtz** [comment]
@mattlewis92,

Totally. One of our goals is to minimize dependencies and not include stuff like that, but we may have to in this case. @manucorporat is super smart so he probably has a good idea of how to do this.

Thanks,
Dan

**Comment by manucorporat** [comment]
@danbucholtz it would be great if you could use the AST generated by Typescript to remove `console.log`, there might have a pluggable API.

(just in case, somebody does not know what a AST is)
It is basically a tree representation of the code, most of the times, it is the first step done by a compiler.
![](https://w3.cs.jmu.edu/lam2mo/cs630_2016_01/images/add_ast.png)

So, to remove the `console.debug()`, you just have to remove the `console.debug` node and regenerate the source code from the tree. It is very easy to use, but I don't think it is worthy just to remove a couple of statements since the built time is longer and longer.

If we can't reuse the AST generated by typescript, I think we could do the same, using a simple parser:
State 1: matches "console.debug"
State 2: matches 0 or more spaces
State 3: matches "("
State 4: wait until final ")"
State 5: Success!

Or we could create a crazy regex with this: https://msdn.microsoft.com/en-us/library/bs2twtah.aspx#balancing_group_definition

**Comment by danbucholtz** [comment]
Assigning @manu, go @manu go!

**Comment by aggarwalankush** [comment]
@danbucholtz Is it internal to Ionic? I have console log, error statements in my code, those are not removed in dev or prod. Do we have some documentation on debugging Ionic app?

**Comment by danbucholtz** [comment]
Yes, this is internal to Ionic @aggarwalankush.

Thanks,
Dan

**Comment by mattlewis92** [comment]
@danbucholtz I just realised, as you already have rollup as a dependency already you can add this fairly easily without suffering from dependency hell 😄  https://github.com/rollup/rollup-plugin-strip

**Comment by adamdbradley** [comment]
Please just use https://github.com/sindresorhus/strip-debug
