### ISSUE TITLE
feat: Android overscroll effect

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#8524]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>browser</span>

<span ionic-description>Video to understand what is overscroll effect: https://drive.google.com/file/d/0B_2AM8ZhXhE9ZTFyZTllclVFa00/view?usp=drivesdk
I think it will give a better UX, feel more native app.
It will come with attr to ion-content: overScroll="true"</span>

<span is-issue-template></span>

**Comment by ustims** [comment]
Hi. I would like to work on this feature but since I'm not yet familiar with ionic internals (just started my pet project with ionic v2) I have few questions to core team members:

I see that current scroll view is a subject to change based on comments in `src/util/scroll-view.ts`.
My question is: what is the best place for overscroll effect implementation? Is it current scroll-view or maybe `src/components/content/content.ts`? Or maybe separate component/util?

@adamdbradley Hello and nice meet you =) Mentioning you since git blame shows your name everywhere in `scroll-view.ts` file :) Please help me with my first steps on contributing to open-source project.

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#73
