### ISSUE TITLE
RC0: Lost page name in ion-page class

### ISSUE THREAD

**Issue by TdyP** [driftyco/ionic#8550]
#### Short description of the problem:
Up to beta 11, the `ion-page` element used to receive a class named after the page name, like, `home-page` which was very convenient to add very specific CSS on a page.
This behavior can be seen on [example plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview)
Now, the `ion-page` has become `<ng-component class="ion-page show-page" style="z-index: 102;">` and we lost the page name class.

Of course, we can still add the class we want in the HTML, but I was wondering if there was any particular or technical reasons for removing this class?

#### What behavior are you expecting?
The page name class to be back :)

**`ionic info`**
Cordova CLI: 6.2.0
Gulp version:  CLI version 1.2.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v6.2.1

Thanks!

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We removed this because adding the class dynamically was very unreliable. We now scope our css using the component selector. You can see an example of this change in our [starters](https://github.com/driftyco/ionic2-starter-tabs/blob/master/src/pages/home/home.scss). Thanks!
