### ISSUE TITLE
Modal in 2.0-rc.0 again doesn't add page class name to ion-page anymore

### ISSUE THREAD

**Issue by michael-brade** [driftyco/ionic#8556]
Hi, I have already written a comment in #7000, but that is closed already. The code that fixed #7000 was deleted again on Jun 28 with this commit 215c6d8#diff-7b81c66d6f3e9c4b82c40ee5ecd30e50 (in fact, the whole loadComponent function was deleted). So now with Ionic 2 RC0 we are back to no class name in a modal dialog. Can you please add it again?

**Comment by Luchillo** [comment]
Soo as i understand @michael-brade it's a regression?

**Comment by brandyscarney** [comment]
We are no longer dynamically adding class names because this caused issues with the latest build process. Instead, you should add a selector to the component and then target the selector as an element. For example in the component:

```
@Component({
  selector: 'modal-about',
  templateUrl: 'about.html'
})
```

then in the css:

```
modal-about {
  // any styles for the component
}
```

I've updated the changelog to include some more info on this, but please let me know if there's more we can do to make this known: https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-rc0-2016-09-28

Thanks!

**Comment by michael-brade** [comment]
Thanks, great stuff! That worked!
