### ISSUE TITLE
Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function

### ISSUE THREAD

**Issue by Anshdesire** [driftyco/ionic#8557]
when i run **ionic serve** it works on browser but ... When i **ionic emulate android**
it fails
gc: Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NtkDetailsPage
and file in which it give error
contains this code
 ```

import { Component, Inject, OpaqueToken} from '@angular/core';
let APP_CONFIG = new OpaqueToken('APP_CONFIG');
import {CONFIG} from '../../config/app-config';
import { NavController, NavParams, LoadingController } from 'ionic-angular';
import {Nav} from '../navigation/nav';
import {httpProvider} from '../../providers/http/httpProvider';
import { SafeResourceUrl, DomSanitizer } from '@angular/platform-browser';

/*
  Generated class for the NtkDetailsPage page.

  See http://ionicframework.com/docs/v2/components/#navigation for more info on
  Ionic pages and navigation.
*/
@Component({
  templateUrl: 'ntk-details.html',
  providers: [{provide: APP_CONFIG, useValue: CONFIG }]
})
export class NtkDetailsPage {
  title: string;
  ntkItem;
  isLink;
  isVideo;
  url: SafeResourceUrl;
  constructor(private sanitizer: DomSanitizer, private nav: NavController, private navParams: NavParams, private http_service: httpProvider, @Inject(APP_CONFIG) private config, private loader: LoadingController) {
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is actually an error in your code that is being caught by NGC (the Angular AoT compiler). NGC does type/error checking in your templates when it runs. NGC does not run when running in dev mode which is why you are not seeing this error when running `ionic serve`. I will be closing this issue since it is not an error on our end but an error in your code, but feel free to ask around on our [forum](https://forum.ionicframework.com). Thanks!
