### ISSUE TITLE
500ms delay after Modal close before view registers finger scroll

### ISSUE THREAD

**Issue by CyrisXD** [driftyco/ionic#8558]
#### Short description of the problem:
Building an iOS app I have a the following [modal view](https://codepen.io/rdelafuente/pen/tJrik/) to click and open images, but when you click on the image to close it, the modal closes but the view is unresponsive for roughly 500ms, until you can scroll again. After inspection in Chrome dev tools I believe it to the be animations causing this issue. This may not seem like a huge problem but I always have to try scroll twice before it's responsive. I have attempted to disable the animations but it does not seem to help. 

#### What behavior are you expecting?
Quicker response time for the view after modal is closed.

**Steps to reproduce:**
1. Click to open modal
2. Click to close modal
3. Quickly try scroll (swiping with finger up or down)

**Which Ionic Version?** 1.7.16

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: Not installed
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This is actually expected behavior as that is our click block that is causing that slight delay. There are multiple reasons for the click block but the main one is perf. We block scrolling until we are sure that the animation has completely finished so that the scrolling is smooth. If you tried to scroll while the webview was still finishing the animation there would be a potential for scroll jank.
