### ISSUE TITLE
Having trouble on initial run of scripts using ionic serve

### ISSUE THREAD

**Issue by sjgmojica** [driftyco/ionic#8599]
Hi Everyone,

I'm newbie with this framework. I need answer to solve the issue that I'm getting everytime I started the scripts using ionic serve. Kindly see attached file. Thanks
<img width="406" alt="screen shot 2016-10-10 at 4 02 33 pm" src="https://cloud.githubusercontent.com/assets/14226982/19229821/fb9a1d28-8f02-11e6-8347-5613077f6623.png">
<img width="1176" alt="screen shot 2016-10-10 at 3 57 28 pm" src="https://cloud.githubusercontent.com/assets/14226982/19229802/d5330924-8f02-11e6-9905-d500eed3c08f.png">

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us and welcome to Ionic! This issue is caused by you running NPM 2. With Ionic 2 RC0 we now require NPM 3. To update to NPM 3 you can run `npm install -g npm` or simply install Node 6, which installs NPM 3 by default and is going to become the LTS node release this month. Thanks!
