### ISSUE TITLE
The name of pages are minified on devices

### ISSUE THREAD

**Issue by Katur7** [driftyco/ionic#8611]
#### Short description of the problem:
In beta 11 I could do check if the app was navigating to the same page as the current page by comparing the names of the pages. I got the names in the openPage(page) function in app.component.ts.
```
openPage(page) {
  const currentPage = this.nav.last().component.name;
  const nextPage = page.component.name;
}
```
Now in RC0 the page names are minified on the device so I only get "t" for both currentPage and nextPage. This only happens when I run on a device with "ionic run android", when I run "ionic serve" I can see the page name.

#### What behavior are you expecting?
* To get the same output when using "ionic serve" and "ionic run android"
* Have a way to get the name of pages even when the code has been minified

**Steps to reproduce:**
1. Start a new project with "ionic start MyIonic2Project tutorial --v2"
2. Place this code in the openPage function in app.component.ts
```
console.log('Current page =>', this.nav.last().component.name);
console.log('Next page =>', page.component.name);
```
3. Run app with "ionic run android -lc" and navigate to the "My First List" page from the side menu.

**Which Ionic Version?**
2.0.0-rc.0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	LinuxMint Description:	Linux Mint 18 Sarah 
Node Version: v4.6.0

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is actually expected behavior as when an app is built to a device it uses our prod build which runs the Angular AoT compiler. The Angular AoT compiler (which gives Ionic 2 RC0 its speed) will compile down the templates which results in 1 letter template names. To accomplish the functionality that you are looking for you can use our new lifecycle event called `ionViewCanEnter`  which runs before the view can enter. This can be used as a sort of "guard" in in views where you need to check things before the view can enter. Thanks!
