### ISSUE TITLE
Restriction of Slider's update methods param

### ISSUE THREAD

**Issue by nikoTM** [driftyco/ionic#8660]
I would like to know why [Swiper's update method](https://github.com/driftyco/ionic/blob/master/src/components/slides/swiper-widget.js#L894) updateTranslate param is ignored [here](https://github.com/driftyco/ionic/blob/master/src/components/slides/swiper-widget.d.ts#L8) and [here](https://github.com/driftyco/ionic/blob/master/src/components/slides/slides.ts#L731). In order to get access to the parameter  I have to do this 

``` Typescript
let swiper: any = this.slider.getSlider();
swiper.update(true);
```

Forcing type **any** on swiper variable, because **getSlider()** returns [Swiper class](https://github.com/driftyco/ionic/blob/master/src/components/slides/swiper-widget.d.ts) and update method on that class does not have updateTranslate parameter.

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this since slides have been refactored and these files no longer exists. Here is the update method: https://github.com/driftyco/ionic/blob/master/src/components/slides/swiper/swiper.ts#L597

Please let me know if it's still an issue and I'll reopen it. Thanks!
