### ISSUE TITLE
[Feature Request] Collapsable List Dividers

### ISSUE THREAD

**Issue by gperdomor** [driftyco/ionic#8762]
Please add options to collapse the content of the ion-item-group component (List Dividers) :D

**Comment by m00g33k** [comment]
+1

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#75
