### ISSUE TITLE
Can't upgrade from Beta 10 to the latest version of IONIC2

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#8790]
Currently, I am running my app in Beta 10 which is fully written in JavaScript.
So far, it's working fine. I've tried to upgrade to the latest version of IONIC2, but I don't have any clue so far.
I was not able to find any documentation of upgrade from Beta 10 to the latest release, especially in JS.
Can you please help me on that?

**Comment by ghenry22** [comment]
The ionic team switched to 100% typescript focus a few versions back

I also started working in JS and then converted to TS format when that was announced, it's a bit of a pain but really not that hard.  The easiest way I found was to start a new project and then merge in my old pages / providers one at a time updating each as I went.  Took a day for a reasonably large app.

I then had to go through a do a similar task again for the migration to RC0 because of the large changes there.

So you're lucky in a way because if you start a new project now it will already be on RC1 and you can run through a 1 time migration to get everything over into Typescript AND onto the latest RC release after which there shouldn't be further huge breaking changes.

It's the price of working with beta software I guess.  I was also worried about the ts vs js thing at first but the typing and ahead of time compiling, compile time error catching is really handy.

**Comment by HamzaLJ** [comment]
@ghenry22 Thanks for your comment, the issue I am having is that the app I am working on it right now, is a pretty large app that took almost 5 months to build, knowing that I am the only developer. Learning TypeScript, and converting from JS to TS seems to me like climbing the Everest mountain. I have 0 knowledge in TypeScript, and I really don't have time to invest to learn a new language. I believe that there should be a way to update to the latest release and keep JS, but I really don't have an idea on how to do so.

**Comment by ghenry22** [comment]
@HamzaLJ I also had never touched typescript before but it is just javascript with some decorations (or decorators!) don't think of it as a whole new language.  I also ported a large app that I had been working on for several months as a sole developer and it only took a day.  Use the ionic conference app for reference or just a clean new starter project and it's pretty easy.

Since typescript is the only supported option going forward with ionic2 I would recommend putting in the time as it's going to get harder and harder to maintain otherwise.  Also as I mentioned there was a big step between beta and RC which basically required you to port your app into a new starter project anyway for the easiest migration so at least you are doing it once where I had to do it twice!

Check this out:
http://www.joshmorony.com/converting-ecmascript-6-to-typescript-in-ionic-2/

Very useful guide showing the bare minimum you need to do to convert from es6 js to ts with an ionic2 project and then showing you a couple of steps beyond the bare minimum that you can tackle later if you want to.

**Comment by HamzaLJ** [comment]
@ghenry22 thanks again, I believe I would take the way and convert my project from JS to TS.
Just a quick question before, do I need to upgrade from Beta 10 to Beta 11, then from Beta 11 to RC0 or I can upgrade from Beta 10 to the latest RC directly?

**Comment by ghenry22** [comment]
If it was me I go directly to the latest RC (RC1).  just update your ionic commandline tools, start a new project.  Use the built in generator to create the base templates for all your pages / components / providers etc then follow the guide I posted cutting and pasting your content from the old project to the new one and adjusting each file one at a time.  After the first couple it becomes pretty obvious and fast.

Also make sure to read through the change logs for Beta 11, RC0 and RC1 before and as you go as there are breaking changes in a number of areas like naming of lifecycle events, how alert / actionsheet etc controllers work and various others.  None hard to deal with just be aware though.

**Comment by HamzaLJ** [comment]
@ghenry22 Thanks a ton!
By the way, when I was developing in JS, many errors where not shown in the browser. In case of an error, it shows a blank page. 
I've heard that typeScript shows errors, etc.. Is that right?

**Comment by ghenry22** [comment]
typescript will catch a lot of errors at compile time rather than relying on you to figure them out after a build which can be very useful.

Otherwise once it's running it's basically just javascript so debugging with console / xcode etc is the same as usual.

**Comment by d3head** [comment]
Hi! You may create new project of 2.0.0-RC0 and transfer your app code from 2.0.0-beta10 to new app.

**Comment by jgw96** [comment]
Hello all! Thanks for helping @HamzaLJ out! I just want to add a note that beta to rc update instructions can be found [here](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-rc0) in our changelog. The only thing you would do different would be to install rc1 instead of rc0.
