### ISSUE TITLE
error :  ionc build ios or android, uglifyjs failed: SyntaxError: Unexpected token: operator (>)

### ISSUE THREAD

**Issue by tianleios** [driftyco/ionic#8817]
when i run ionic build ios. will display fllow errror，uglifyjs cannot support es6 feature arrow function
]  ngc finished in 32.81 s 
[19:52:49]  bundle started ... 
[19:53:01]  bundle finished in 12.33 s 
[19:53:01]  uglifyjs started ... 
[19:53:01]  sass started ... 
[19:53:02]  uglifyjs failed: SyntaxError: Unexpected token: operator (>) 
[19:53:02]  ionic-app-script task: "build" 
[19:53:02]  Error: SyntaxError: Unexpected token: operator (>)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! uglifyJS does support arrow functions. Are you using the correct syntax for arrow functions? ```setTimeout(() => {}); ```

**Comment by haxpor** [comment]
@jgw96 it happens the same for me with `uglifyjs failed: SyntaxError: Unexpected token: operator (>)`. For my case, it's due to one of node modules I imported has es6 code, specifically arrow function. I tried not to import that module, and it passes, no error but not the other way around.

It seems uglifyJS has es6 support but in another branch `harmony`, once I tried hooking it up with gulp and failed. I don't know how to do it.

Is it the case? If not, how to make this works with ionic 2.

**Comment by tianleios** [comment]
@haxpor  can you display you resolve function detail

**Comment by tianleios** [comment]
@jgw96  i confirm i use correct arrow function

**Comment by haxpor** [comment]
@tianleios On your root project directory, edit `node_modules/@ionic/app-scripts/package.json` file. Then in that file update `uglify-js` like this `"uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony"`.

Then after that execute `npm install` (make sure right now you're at `node_modules/@ionic/app-scripts`. Ignore error that shown. I have shown error about jasmine's build for path variable that it seems like it need `src`, but it works at the end.

**Comment by zhang-z** [comment]
@haxpor , the 'harmony' solution is working, thank you!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#239

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is a build issue i have moved this issue to the app-scripts repo.
