### ISSUE TITLE
cancelButtonText not working on search bar

### ISSUE THREAD

**Issue by RDerrow** [driftyco/ionic#8838]
`<ion-searchbar [cancelButtonText]="Search" [showCancelButton]="true" (ionBlur)="dismissKeyboard()" (ionInput)="getMovies($event)" placeholder="search by name: director: type: year: before: after:">
  </ion-searchbar>`

This is the code I am using for the search bar. Howerver, when I try and change the text of the cancel button nothing shows up where the cancel button should be.

**Comment by cleever** [comment]
Related https://github.com/driftyco/ionic/issues/8403

**Comment by brandyscarney** [comment]
Thanks for the issue! This is actually caused by the brackets `[]` surrounding `cancelButtonText`. When you wrap the property in brackets you are telling it to evaluate the value as an expression. So while `showCancelButton` works because it understands `true` as an expression, `cancelButtonText` is looking for the variable `Search` to find the value. If you change it to `[cancelButtonText]="'Search'"` (notice the quotes) you will see it shows up. So basically, you should remove the brackets so it evaluates as a string:

```
<ion-searchbar cancelButtonText="Search" showCancelButton="true" (ionBlur)="dismissKeyboard()" (ionInput)="getMovies($event)" placeholder="search by name: director: type: year: before: after:"> </ion-searchbar>
```

For more info on property binding, check out the Angular documentation: https://angular.io/docs/ts/latest/guide/template-syntax.html#!#property-binding

I've confirmed that this is working in the latest release rc.1, using the conference app: https://github.com/driftyco/ionic-conference-app
