### ISSUE TITLE
ionic-angular shouldn't list compiler-cli as a peer dependency

### ISSUE THREAD

**Issue by mirkonasato** [driftyco/ionic#8843]
#### Short description of the problem:

Trying to use Ionic 2 with a custom setup (i.e. not a project generated with the Ionic CLI) I get

```
npm WARN ionic-angular@2.0.0-rc.1 requires a peer of @angular/compiler-cli@^0.6.2 but none was installed.
```

I believe `ionic-angular` declares more peer dependencies than it needs to.

```
$ npm view ionic-angular peerDependencies

{ '@angular/common': '^2.0.0',
  '@angular/compiler': '^2.0.0',
  '@angular/compiler-cli': '^0.6.2',
  '@angular/core': '^2.0.0',
  '@angular/forms': '^2.0.0',
  '@angular/http': '^2.0.0',
  '@angular/platform-browser': '^2.0.0',
  '@angular/platform-browser-dynamic': '^2.0.0',
  '@angular/platform-server': '^2.0.0',
  rxjs: '^5.0.0-beta.12',
  'zone.js': '^0.6.21' }
```
#### What behavior are you expecting?

The `ionic-angular` package should only list as peer dependencies those packages that are needed to _run_ an Ionic 2 app, not to _build_ it.

**Which Ionic Version?** 2.x

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! So the reason that we have a peer dep on the `compiler-cli` package is because only that specific version of NGC has been vetted to work with that specific version of Angular. If we did not put it as a peer dep it is possible that users would run into issues where there app was not building because of a different version of NGC being installed. We have gone back and forth on this internally, but from experience we have found that it provides a better out of the box user experience for us to have very strict dependences.
