### ISSUE TITLE
ionCanViewEnter not fired

### ISSUE THREAD

**Issue by gimox** [driftyco/ionic#8963]
ionCanViewEnter is not fired on ionic 2.RC1. 

```js
import {Component} from '@angular/core';
import {NavController} from 'ionic-angular';

import {LibraryComponent} from '../library/library.component';
import {MagazineComponent} from '../magazine/magazine.component';
import {SettingsComponent} from '../settings/settings.component';

import {DisplayTabService} from '../services/displayTab.service';


@Component({
    templateUrl: './tabs.component.html'
})

export class TabsPage {

    tab1Root: any = LibraryComponent;
    tab2Root: any = MagazineComponent;
    tab3Root: any = SettingsComponent;

    constructor(displayTab: DisplayTabService, public navCtrl: NavController) {
        displayTab.show();
    }

  ionViewDidLoad() {
    console.log("It work!");
  }

  ionCanViewEnter(): boolean{

    console.log("NOT WORK");
    return false;
  }


}
```

**Comment by vjanssens** [comment]
I just started my first Ionic 2 application and ran in the exact same problem. It seems the documentation on NavController is mixing up method names. Under the [lifecycle events](http://ionicframework.com/docs/v2/api/navigation/NavController/#lifecycle-events) you'll find a table with an event called `ionViewCanEnter`. That's the one you need to use instead of `ionCanViewEnter` (see placement of the word `Can`).

You probably found `ionCanViewEnter` below the [Nav Guards](http://ionicframework.com/docs/v2/api/navigation/NavController/#nav-guards) section (at least I did and stumbled upon your issue).

**Comment by gimox** [comment]
good catch! thanks!

ionViewCanEnter work perfect. 

So, the docs need some improvement.

**Comment by manucorporat** [comment]
It was already fixed! change available in RC2
