### ISSUE TITLE
Feature: combine datetime picker columns

### ISSUE THREAD

**Issue by Manduro** [driftyco/ionic#8974]
#### Short description of the problem:
I'd like the user to be able to see the day of the week of the date they are selecting, by combining it in a single column for the picker, like 'Wed 19'. Or even combine it with the month like below.

Maybe providing a custom function that returns the content to be displayed in a column based on the date would be a great solution.

![image](https://cloud.githubusercontent.com/assets/2545042/19886297/e2be14d6-a022-11e6-9ce0-bf92465c477e.png)

**Which Ionic Version?** 2.x

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#76
