### ISSUE TITLE
`npm run link` does not install Angular

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#9016]
#### Short description of the problem:
when running `npm run link` to run our `"link": "gulp release.prepareReleasePackage && cd dist/ionic-angular && npm link"` task when testing a local copy of the repo you get this error `Uncaught Error: Can't resolve all parameters for provideLocationStrategy: (PlatformLocation, ?, Config).(…) `. After doing some testing I was able to figure out that this was because Angular was not being installed which then caused all the things to break. Changing the `link` task to `"link": "npm install && gulp release.prepareReleasePackage && cd dist/ionic-angular && npm link"` makes everything work perfectly. All of this points to an issue deeper in our gulp tasks.

**Steps to reproduce:**
1. run `npm run link` in a local copy of the framework repo
2. run `npm link ionic-angular` in a test app
3. notice error

**Which Ionic Version?** 2.x

**Comment by paulsouche** [comment]
Hi !

I've got the same issue here. You can reproduce on my [repo](https://github.com/paulsouche/ionic2-webpack-starter)

**Ionic version:**  (check one with "x")
[ ] **1.x**
[ X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`Uncaught Error: Can't resolve all parameters for provideLocationStrategy: (PlatformLocation, ?, Config).(…)` at runtime

**Expected behavior:**
The app module should be loaded

**Steps to reproduce:**
clone my [repo](https://github.com/paulsouche/ionic2-webpack-starter) 

```
npm i
npm start || npm test
```

**Related code:**
N/A

**Other information:**
N/A

**Ionic info:**
N/A

Thanks for the great work btw

**Comment by paulsouche** [comment]
We found that we can require umd bundle without this error if ionic bundles it without rollup configuration.

See this [task](https://github.com/driftyco/ionic/blob/master/scripts/gulp/tasks/release.ts#L124). If you remove plugins, bundle is "correctly" generated and can be imported in webpack 1. But we don't know really why ?

Hope it helps

**Comment by jgw96** [comment]
Closing this issue as it is not relevant anymore with the latest changes in our build.

**Comment by rumpl** [comment]
Hey @jgw96,

Could please be more specific? What changes in the build?
