### ISSUE TITLE
Adding JS libraries to Ionic 2 project

### ISSUE THREAD

**Issue by mbj36** [driftyco/ionic#9035]
I want to add sw-toolbox library in ionic 2 project. I tried adding in index.html file inside the src folder
How i added the file : <script src="../bower_components/sw-toolbox/companion.js" data-service-worker="service-worker.js"></script>

But it gives the error - Failed to load the resource: server returned with status of 404 not found 

My path is 100% correct 

What am i doing wrong ?
My project repo - https://github.com/mbj36/githubIonic

**Comment by AndreasGassmann** [comment]
When you build your project, ionic copies/transpiles all your files into a new folder called www. However, as far as I know, it will not include the the files in your bower_components. So the easiest solution is to manually copy the js files you need into your src/assets/ folder because its contents will be copied to the www folder. You then have to adjust the path in your html to point to something like assets/sw-toolbox/companion.js. A better solution would be to find/write typings for the sw-toolbox so it will automatically get bundled with the rest of the libraries. I hope that helps.

**Comment by mbj36** [comment]
Thanks @AndreasGassmann  I also went through this and it helped me http://ionicframework.com/docs/v2/resources/third-party-libs/

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
