### ISSUE TITLE
geolocation plugin access to geolocation was blocked over insecure connection

### ISSUE THREAD

**Issue by zefrench** [driftyco/ionic#9082]
Since the update to RC2 I'm unable to use the native plugin Geolocation..

Did someone get the same problem ?

Here is the error I get: 
geolocation plugin access to geolocation was blocked over insecure connection

**Comment by msio777** [comment]
It happens just if you use livereload -l on emulator (tested with ios emulator). try without it a it will work

**Comment by zefrench** [comment]
I don’t use livereload.
I just type ionic run iOS

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#780

**Comment by charan-kanaparthi** [comment]
hello guys , i am new to ionic , currently i m developing  a android and ios app using ionic 3 my requirement is to show client current location in google maps, using gmaps java script api i have done in it  , it is working fine in chrome so i build android app but in app its is not working , after a small research i found that issues is due to geolocation plugin access to geolocation was blocked over insecure connection.. please help how to get current location using ionic 3 in android
