### ISSUE TITLE
EXCEPTION: Error in ./ArticleDetails class ArticleDetails_Host - inline template:0:0 caused by: Cannot read property 'params' of undefined; NavParams seems not working

### ISSUE THREAD

**Issue by kluz116** [driftyco/ionic#9134]
import { Component } from '@angular/core';

import { NavController, NavParams } from 'ionic-angular';
import {HomeService} from '../home/homeService';

@Component({
  selector: 'article-details',
  templateUrl: 'articleDetails.html',
  providers:[HomeService]
})
export class ArticleDetails {
 public selectedId:any;
 public selectedData:any;
 public feeddetails=[];
  constructor(  public navCtrl: NavController, public params: NavParams, private _home: HomeService) {
    
    this.selectedId.params.get('id');
    

    this.loadDetails();
    
  }

  loadDetails(){

    this._home.getFeedDetails(this.selectedId).subscribe(res=>{
      this.feeddetails = res;
      console.log(this.loadDetails);
     });

}
}

**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

**Note: for Ionic-Native related issues you can open up an issues on the Ionic-Native repo**

https://github.com/driftyco/ionic-native

#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/GJte2b?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by ghenry22** [comment]
You haven't actually assigned any value to this.selectedId in your code above, hence it would be undefined.  You need to set the value from navparams into that first.

Also you should probably update your app to typescript inline with the ionic2 teams focus to typescript only.  There will likely be more and more.incompatibilities or quirks trying to run a straight es6 is project rather than typescript and I don't believe they are actually supporting it any more.

You also might be better off asking questions on the ionic forums to get some input first and if something is confirmed as a bug or affecting others then log as an issue here, along with the basic details that the issue template requests.
