### ISSUE TITLE
Rating component that will take care of visualising a star rating bar

### ISSUE THREAD

**Issue by aspidvip** [driftyco/ionic#9160]
**Hello!!!**

**PLease!!! add Rating component for IONIC 2**

**exemple**
http://valor-software.com/ng2-bootstrap/#/rating

Thansk...

**Comment by ghenry22** [comment]
why not just include ng2-bootstrap in your app and use the one from the link?

**Comment by ekhmoi** [comment]
I have a simple component, should i make a pr ?

**Comment by ekhmoi** [comment]
check this out! 
[https://github.com/ekhmoi/rating-bar](RatingBar)

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#78
