### ISSUE TITLE
[IDEA]ionic2 Please add a gallery component for photo like the PhotoSwipe

### ISSUE THREAD

**Issue by fssgh** [driftyco/ionic#9184]
I hope the ionic have a support pinch  to the picture zoom view components 

like the  [PhotoSwipe](http://photoswipe.com/)

Do you make it?

**Comment by dylanvdmerwe** [comment]
You can normally build things like this yourself. However I did log an issue [here](https://github.com/driftyco/ionic/issues/6482) on something that prevented me from building my own.

**Comment by fssgh** [comment]
@dylanvdmerwe   Thank you for your advice

**Comment by diegofalciola** [comment]
Looks like there are a lot of people experiencing this problem, but none of them have been able to find a solution to it. 

The latest thing I found comes from this repo: https://github.com/nikini/ionic-gallery-modal/tree/master/src

It implements a custom zoomable-image, which seems to work fine. Cons are that its complexity is quite high if you need to build it on your own. Also, this must be supported in Ionic2, so eventually it might change.

If anybody has something better, please share!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#79
