### ISSUE TITLE
color attribute doesn't work on ion-content

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#9208]
#### Short description of the problem:
color attribute doesn't work on ion-content

#### What behavior are you expecting?
setting color should change ion-content background color

**Steps to reproduce:**
Following code doesn't change anything

```
<ion-content color="light">
```

**Which Ionic Version?** 1.x or 2.x
Ionic 2 rc2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.44
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.1 Build version 8T61a

**Comment by vitaliy-bobrov** [comment]
According to the docs there is no color property for ion-content component
http://ionicframework.com/docs/v2/api/components/content/Content/

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#81
