### ISSUE TITLE
can i load  usual angular js  along with ionic-angular.js  ?  Can they both exist together ?

### ISSUE THREAD

**Issue by jpca999** [driftyco/ionic#9212]
I'm already usign angular in the project.. Now including ionic on top of it..  Whats the solution ?

**Comment by wbhob** [comment]
Ionic IS Angular, so you don't need it twice. Please close this issue.

**Comment by jpca999** [comment]
If Ionic is Angular they why don't they use the angular.js  in the file system why do they have their own ionic.js ?  

Secondly I in the app.js they use  'meanuContent'  I've never seen this thing before..

**Comment by wbhob** [comment]
Because angular is more of a compiler, and ionic builds on angular, which is why it's in the file system. 

Ionic also developed their own router so it works better for mobile apps, where angular was designed for web. All your angular code will work in ionic for the most part, as long as you change the routing, and even then just the components from ionic should work in a normal angular app.

**Comment by jpca999** [comment]
|  Ionic also developed their own router

I'm having issues transporting  ionic routes on to my angular ( mean js ) app. Can you suggest what i might be missing ?  I only loaded, js/ionic.bundle.min.js

**Comment by patrickmcd** [comment]
This isn't the right place for this.

Use the docs:
http://ionicframework.com/docs/v2/getting-started/

And ask on the forums:
https://forum.ionicframework.com/

**Comment by wbhob** [comment]
Can you show me some code?

**Comment by wbhob** [comment]
Thank you, Patrick. @jayp, can you close the issue please?

**Comment by jpca999** [comment]
@wbhob   Heres' the code, branch 5.  https://github.com/jpca999/ionic-mean/tree/5-test-menu-trying-to-work
