### ISSUE TITLE
Can't find variable: Symbol in lang.ts iOS 8.1

### ISSUE THREAD

**Issue by chandanch** [driftyco/ionic#9221]
#### Short description of the problem:
When I run the application on iOS 8.1  I get the following error:
ReferenceError: Can't find variable: Symbol:
function: getSymbolIterator — lang.ts
source path: node_modules/angular2/src/facade/lang.ts at line: 455:26

It shows a blank white screen and does not load the app

#### What behavior are you expecting?
The App must load correctly

**Steps to reproduce:**
1. Create an ionic2 app with  2.0.0-beta.10 version
2. Add the build the ios app.
3. Run app and debug using safari web inspector

Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 8.1 Build version 8B62

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Unfortunately we cannot support such an old version of Ionic 2 at this time. This has since been fixed in newer version of Ionic 2. You can find the instructions on how to update to our RC release [here](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-rc0) Thanks!
