### ISSUE TITLE
$list-md-header-color is fixed instead of inheriting $text-color

### ISSUE THREAD

**Issue by barocsi** [driftyco/ionic#9229]
https://ionicframework.com/docs/v2/theming/overriding-ionic-variables/
$list-md-header-color	#858585
while
$list-ios-header-color	$text-color

**Comment by brandyscarney** [comment]
Thanks for the issue! This is by design to match the Material Design spec. See this image for reference:

<img src="https://material-design.storage.googleapis.com/publish/material_v_9/0B6Okdz75tqQsNlAwTVZUcXB1M0U/components_lists_keylines_single9.png" width="400">

The `$text-color` variable defaults to `#000` which doesn't match the spec. :)
