### ISSUE TITLE
Feature: Modal.present could return Promise<any>

### ISSUE THREAD

**Issue by abierbaum** [driftyco/ionic#9235]
I find myself often calling modal.onDidDismiss(...) immediately after creating a modal.  I think it would be nice if the Modal.present method could return a Promise to handle this use case easier.  Seems like a very common action to present a modal and want to be notified when it is dismissed.

So the current example code that looks like:

```
presentProfileModal() {
   let profileModal = this.modalCtrl.create(Profile, { userId: 8675309 });
   profileModal.onDidDismiss(data => {
     console.log(data);
   });
   profileModal.present();
 }
}
```

could end up looking like this instead if people wanted to use the promise.

```
presentProfileModal() {
   let profileModal = this.modalCtrl.create(Profile, { userId: 8675309 });
   profileModal.present()
      .then(data => {
        console.log(data);
      });
}
```

This has the nice benefit of allowing the promise to be stored if needed and also enables using the present method with async/await syntax as it becomes more widely available.

**Comment by FdezRomero** [comment]
@abierbaum I think that wouldn't work because `modal.present()` already returns a Promise that resolves when the navigation animation is finished, so you can easily chain them.

Doing what you are suggesting would break the most common case, that is async transitions. I guess that is why the API has `onDidDismiss()`.

Just my 2 cents ;-)

**Comment by abierbaum** [comment]
@FdezRomero Ah, ok.  got it.  I Hadn't checked the code in modal.ts, I was just looking at the docs and didn't see anything about a return value.  Thanks for the pointer.

**Comment by FdezRomero** [comment]
@abierbaum Yeah, it was more obvious in the betas where you had to do `this.navCtrl.present(modal)` instead, because you saw it was coming from the navigation. I know they made some changes in the recent releases to queue some transitions, but I'm not sure if it works in all scenarios. If the Ionic team now has another way to handle transitions maybe it would be feasible, though a breaking change.

**Comment by manucorporat** [comment]
Thanks for the idea! but it is too late (RC) for a breaking change this big
