### ISSUE TITLE
AJAX CORS Problem since ReleaseCandidate

### ISSUE THREAD

**Issue by nickwinger** [driftyco/ionic#9251]
Hi,

i have a really urgent problem and i hope someone can point me into the right direction.
Since i upgraded to the release candidate my ajax (cors) calls on the android device
are extremly slow and sometimes the just timeout or keep pending.

However in the web browser i don't have theses problems, only on the android device.

I'm also using the whitelist plugin for allowing cors.

Anyone has ideas why this problem is there since RC ?

With beta.11 i didn't had any problems with ajax calls on android device.

This is very urgent as the app should go live soon, but i don't know how i can fix this and currently i have no clue what could cause this strange behaviour

**Comment by jgw96** [comment]
Hello, thanks for using Ionic and sorry your running into issues. This sounds like an issue with your backend server. Ionic does not do anything special with the standard Angular 2 HTTP module. Because of this i am going to close this issue and recommend that you ask around for help on our  forum (forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages?]. Thanks!
