### ISSUE TITLE
Get rid of loading-wrapper class ionic v2

### ISSUE THREAD

**Issue by barocsi** [driftyco/ionic#9252]
How do I do it?

useCss has no effect
adding custom content has no effect, the wrapper is still there.

**Comment by manucorporat** [comment]
Hi, can you follow the provided issue template? thanks

**Comment by barocsi** [comment]
Sure, but its obvious: loadingcontroller shows a loader with a loading-wrapper class. We do not want it, or at least useCss to change that so we could override it per component.

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

following the doc at http://ionicframework.com/docs/v2/api/components/loading/LoadingController/
```
presentLoadingCustom() {
  let loading = this.loadingCtrl.create({
    spinner: 'hide',
   usecss:'test',
    content: `
      <div class="custom-spinner-container">
        <div class="custom-spinner-box"></div>
      </div>`,
    duration: 5000
  });
```
**Expected behavior:**
ion-wrapper with customCss assigned
but it can happen that this is not the desired behavior. No one knows when it comes to ionic :)

**Comment by brandyscarney** [comment]
Thanks for the issue, @barocsi! Filling out the issue template helps us to understand the problem without having to ask follow up questions. While the issue may be obvious to you, it is not always immediately obvious to us. :) The loading wrapper is necessary in order to add the animation to the loading component. All of the properties the loading component accepts can be found here: http://ionicframework.com/docs/v2/api/components/loading/LoadingController/#advanced. We don't have a `usecss` property; I think `cssClass` is what you're looking for. We have e2e tests created for each component, so if our docs are ever behind you can always check the component's folder in the repository under `src`. For example, each folder here is a different example using the loading component: https://github.com/driftyco/ionic/tree/master/src/components/loading/test. If you notice we have some documentation lacking, please create an issue at https://github.com/driftyco/ionic-site/issues so we can take care of it. Thanks!
