### ISSUE TITLE
Access to the SCSS-Variables

### ISSUE THREAD

**Issue by sburak** [driftyco/ionic#9260]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Hi, how i can access to the Ionic 2 scss variables in a page.scss?

I try to get this variable in about.scss:
$navbar-ios-height // toolbar-height

I get a error ,that dont know what variable that is.
But if I import the "../../../node_modules/ionic-angular/components/toolbar/toolbar.md" then i have access to the variable.

But thats not beautiful. They write the complet scss twice time.

Sorry for my bad English :S

**Comment by brandyscarney** [comment]
Hi @sburak, this is actually a support question since you are asking how to do something in the framework. :) We recommend using one of these channels for support questions: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

I have tried this out, however, and I am able to access the Sass variable `$navbar-ios-height` from the `about.scss` page of the [conference app](https://github.com/driftyco/ionic-conference-app).

I placed the following code at the top of the `about.scss` page:

```
@debug $navbar-ios-height;
```  

and in my terminal during `ionic serve` this is printed:

```
/ionic-conference-app/src/pages/about/about.scss:1 DEBUG: 44px
```

Please try the same in the conference app and then compare your `package.json` file to the conference app's: https://github.com/driftyco/ionic-conference-app/blob/master/package.json.

If you continue to have issues please use one of the above links I shared. Thanks! :)
