### ISSUE TITLE
Expandable Component

### ISSUE THREAD

**Issue by jtushar53** [driftyco/ionic#9262]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Currently we don't have any expandable component in ionic 2. 
it can used in sidemenu or settings or list item

**Expected behavior:**

https://material.google.com/components/cards.html#cards-behavior
or 
https://material.google.com/components/expansion-panels.html

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#87
