### ISSUE TITLE
hideNavBar attribute of ionView directive doesn't remove has-header class from contained ionContent directive

### ISSUE THREAD

**Issue by ciastek** [driftyco/ionic#927]
Using hideNavBar attribute you can hide navBar on selected ionView as described on [ionView documentation page](http://ajoslin.github.io/docs/nightly/api/directive/ionView/).

Using Ionic v0.9.27 it was possible to not add hasHeader attribute to ionContent to make view look decent with navBar hidden (see [example](http://codepen.io/ciastek/pen/lxmyC)).

It's not possible with Ionic v1.0.0-beta.1 as it has removed hasHeader attribute from ionContent directive. Instead it adds has-header class to the ion-content element automatically (see [example](http://codepen.io/ciastek/pen/GIbcd)).

hideNavBar attribute of ionView directive should conform with new behaviour and remove has-header class from ion-content element.

NOTE: As a workaround you can set $scope.$hasHeader=false on view's controller to prevent adding has-header class to the ion-content element.

**Comment by lambrospetrou** [comment]
If I have the ion-nav-bar hidden but I have another HTML code acting as header with the class 'bar-header' then the ion-content class 'has-header'  is being removed on SECOND load of the view whreas it works fine the first time.
It seems that ionic removes the has-header class when it loads the view from cache because it sees that the ion-nav-bar is hidden, but it ignores the fact that I have another element with the bar-header class.

**Comment by yonirab** [comment]
@lambrospetrou did you find a solution for this problem? I am seeing the exact same issue...

**Comment by ievhenganchin** [comment]
@lambrospetrou , @yonirab 

if this is still actual:

```
$timeout(function() {
       angular.element(document.getElementById("content")).removeClass("has-header");
 });
```
