### ISSUE TITLE
ionic select looks ugly by going outside the screen - is there a better option to implement it, that i'm missing ?

### ISSUE THREAD

**Issue by jpca999** [driftyco/ionic#9290]
![image](https://cloud.githubusercontent.com/assets/1026325/20535053/71100a7a-b0b1-11e6-836b-f60bd035b590.png)

**Comment by brandyscarney** [comment]
We have a Select component which uses the Alert or Action Sheet interface in order to present the options: http://ionicframework.com/docs/v2/components/#select

For future support questions, please use one of the following channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/. Thanks! :)
