### ISSUE TITLE
could you please support tecent x5 engine

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic#9324]
hi guys,
there is an app called wechat,
almost every chinese use it everyday.

the x5 engine is a webview engine made by wechat team
and embedded for upgrade webview performance like crosswalk
but the size is only around 250k,

and the most amazing feature is base on blink

so could you please support it like crosswalk or add it to ionic-native?

there is the sdk
http://x5.tencent.com/doc?id=1004

**Comment by infinnie** [comment]
You can deploy web apps on WeChat as a service account.

**Comment by wbhob** [comment]
@yozman I don't think Ionic will be supporting x5 since it is a special use case. They recommend WKWebView for iOS because it is made by Apple, and is tried and true, and above all not third party. I don't work for Ionic, but they traditionally want to keep things as light as possible and keep dependency low. However, if you made an x5 plugin, I am sure the community of Ionic devs in China would love you forever 👍

**Comment by jgw96** [comment]
Hello @yozman ! Thanks for the idea (: So this is not something we would really want to incorporate into Ionic as it is a specialized use case, but this seems like it would be perfect for a third party cordova plugin!
