### ISSUE TITLE
[Ionic2] Modal z-index changes incorrectly resulting in animation in the "background"

### ISSUE THREAD

**Issue by eduboxgithub** [driftyco/ionic#9409]
**Ionic version:**  (check one with "x")
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report

**Current behavior:**
Adding multiple modals one on top of another the modal on top when closed, slides in the background and not in his previous z-index. This is more noticeable if one of the modals has semi transparent background.

**Expected behavior:**
I think it should slide in front of all other elements.

**Steps to reproduce:**
1 - Have a root page;
2 - Add a modal width transparent background to .5 ou similar;
3 - Add another modal over the called from the modal added in step 2.
4 -  When closing the modal added in number 3 we will see it slide in the background, and not in front of the modal added in 2.

**Other information:**
![modal_1](https://cloud.githubusercontent.com/assets/13800439/20718206/dbe32384-b64f-11e6-83c2-db4344a109cb.JPG)

The modals were added to the dom:
1 - Modal was addded on top of the page, and the modal was semi transparent background;
the z-index of this modal is 1009.
2 - A new modal is added from modal 1. The new model have z-index 1010.

The second modal is removed from the dom (dismiss):
![modal_2](https://cloud.githubusercontent.com/assets/13800439/20718327/3fc9ec2a-b650-11e6-9df7-097f466ca4c7.png)

1- The first modal change its z-index to one higher than the second modal in the exact the button is pressed to close the second modal;
2 - The second modal keeps its z-index and slides in the background. The animation is visible because the first modal has semi transparent background.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
 ordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v5.11.1
Xcode version: Not installed
```

**Comment by manucorporat** [comment]
I think this is regression caused by https://github.com/driftyco/ionic/commit/70f8a8e5eb855d407487c8088a6924b1edc15d1a

**Comment by nicobytes** [comment]
**Ionic version:**  (check one with "x")
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report

**Current behavior:**
Same @eduboxgithub when add multiples modals don't show animate dismiss

**Expected behavior:**
The modals (overloads) should change the z-index then that finish the animate dismiss 

**Steps to reproduce:**
1 - Have a root page
2 - Add multiples modals
3 - When close a modal don't show animate dismiss

**Related code:**

Code: https://github.com/nicobytes/issue-9409/
Demo: http://www.nicobytes.com/issue-9409/
Video: https://drive.google.com/file/d/0BybyjeN9vSwhRkdmOGhZTFZlUlE/view?usp=sharing

**Other information:**
I think error is caused by https://github.com/driftyco/ionic/commit/70f8a8e

**Ionic info:**


```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.2.0
Xcode version: Not installed

```
