### ISSUE TITLE
Feature Request: Tags Input

### ISSUE THREAD

**Issue by shyamal890** [driftyco/ionic#9492]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request

Would be great if Ionic2 would support input field for tags.

**Comment by brandyscarney** [comment]
Hey @shyamal890. Do you have an image of what you're looking for? I'm not sure what a tags input is. Are you looking for chips: http://ionicframework.com/docs/v2/api/components/chip/Chip/?

**Comment by shyamal890** [comment]
Hey @brandyscarney I was looking for something like http://mbenford.github.io/ngTagsInput/

**Comment by manucorporat** [comment]
Chips + autocomplete

**Comment by graphefruit** [comment]
https://material.angularjs.org/latest/demo/chips here's a  good example how it could look like. (Contact-chips)

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#85
