### ISSUE TITLE
Feature Request: Animating html elements

### ISSUE THREAD

**Issue by heldertb** [driftyco/ionic#9529]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[x] support request

**Current behavior:**
Animation is a hazard now in Ionic. It should be a default feature in Ionic to have animations for your html.
I'm trying to animate a `<div>` tag that I'm toggling in hiding and showing. What I want is it to slide up and down, but doing a google search on the only shows some basic css animations. And all of them are animations for when the view loads.
If there is already support for this, I couldn't find it.

Also, doing a search in the docs and navigating to 'Animation' gives a 404...

**Comment by mhartington** [comment]
The animation page in our docs is an internal animation class that is private.

Since ionic 2 is Angular 2, you should be using angular 2 animations.

https://angular.io/docs/ts/latest/guide/animations.html

Also note that the issue templates states that "support requests" should post to the ionic forum or slack channel.
