### ISSUE TITLE
feat: Model support back button

### ISSUE THREAD

**Issue by iron9light** [driftyco/ionic#9603]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When touch the hardware back button in a Modal view. The app will be closed.

**Expected behavior:**
Close this Model view, same as `viewCtrl.dismiss()`;

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by manucorporat** [comment]
Already fixed in nightly!

```
npm install ionic-angular@nightly --save
```

**Comment by iron9light** [comment]
@manucorporat thx!

**Comment by yozman** [comment]
@manucorporat 
modal should not close with back button.
because it not a page not match a url.

somecase like login modal,
I have a main page and check if user is login.
when not will show a login modal.
but if modal close with back button.
the main page will show without user login

so restore it plz !!!!!!!!!!!!

**Comment by yozman** [comment]
@iron9light 
in your case you should use navPush not modal!!!!!!!!!!!!!!
