### ISSUE TITLE
Click performance on Android devices (ionic.tapElement changes)

### ISSUE THREAD

**Issue by tmiskin** [driftyco/ionic#970]
Click performance on Android devices for items with hrefs significantly degraded from the changes made to ionic.tapElement recently.  I verified on multiple devices that the problem was occurring and then they went away when I reverted ionic.tapElement to the March 19th commit - 26c8f304e7d9d24006d17fcb4161195717ca26a0 and everything was back to the performance of .9.27.  Tap responsiveness is slower with the new changes and sometimes you have to click 2-4 times on elements for the click to register.  I haven't had the time to narrow it down to what changed that is causing the issue, as there were significant changes to it over the last week.

**Comment by danielzzz** [comment]
I think this problem still persists with the latest nightly.

Version: 1.0.0-beta.14-nightly-1042
Platform: android 2.3.4 (I hope you still support older systems)

I have a very simple app where taping on buttons changes the app state, but on my android device the tap is not detected randomly. Sometimes it works every time, then suddenly I have to tap the button many times in order to get it working. It's quite frustrating...

on the pc browser everything works perfectly
