### ISSUE TITLE
alert() does not work on Windows 10

### ISSUE THREAD

**Issue by joshstrange** [driftyco/ionic#9737]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
````alert()```` does nothing on Windows 10

**Expected behavior:**
Alert box should pop like on iOS and Android

**Steps to reproduce:**
Use ````alert('Whatever');```` anywhere in your code

**Related code:**
See above

**Other information:**
None

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.2.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question and since `alert()` is a function built into the browser, not an ionic method, i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by joshstrange** [comment]
For anyone that wants to follow up on this I opened a forum topic [here](https://forum.ionicframework.com/t/cant-call-alert-in-windows-app/74034)
