### ISSUE TITLE
Swiper Slide version - 3.4.1

### ISSUE THREAD

**Issue by zywh** [driftyco/ionic#9771]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Current version doesn't seem supporting responsive breakpoints option

**Expected behavior:**
[http://idangero.us/swiper/demos/33-responsive-breakpoints.html](http://idangero.us/swiper/demos/33-responsive-breakpoints.html)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I am going to close this issue for now as we have removed swiper as of RC5 and instead are using our own slides implementation now. The reasoning for this was mainly the size of swiper and how large it made our bundle and the fact that because it was not written in typescript it made our bundling process more complicated than it needed to be.
