### ISSUE TITLE
broken ionic in macOS 10.12.2 update

### ISSUE THREAD

**Issue by jagannathTL** [driftyco/ionic#9774]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ X] support request 

After updating macOS to 10.12.2 ionic serve command not working even its not recognising ionic command (bash: ionic: command not found) please have a look into this

Getting warnings while reinstalling Ionic2
`npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.3.3: use uuid module instead
/Users/zaggu/.npm-packages/bin/cordova -> /Users/zaggu/.npm-packages/lib/node_modules/cordova/bin/cordova
/Users/zaggu/.npm-packages/bin/ionic -> /Users/zaggu/.npm-packages/lib/node_modules/ionic/bin/ionic
/Users/zaggu/.npm-packages/lib
├── cordova@6.4.0
└── ionic@2.1.18

npm WARN In ionic@2.1.18 replacing bundled version of mime-types with mime-types@2.0.14
npm WARN In ionic@2.1.18 replacing bundled version of cross-spawn with cross-spawn@4.0.2
npm WARN In ionic@2.1.18 replacing bundled version of semver with semver@4.2.0
npm WARN In ionic@2.1.18 replacing bundled version of form-data with form-data@0.2.0
npm WARN In ionic@2.1.18 replacing bundled version of request with request@2.51.0
npm WARN In ionic@2.1.18 replacing bundled version of ionic-app-lib with ionic-app-lib@2.1.9`

**Comment by graphefruit** [comment]
@jagannathTL that looks more a support request then a bug report.

1. Make sure you installed latest Node.js.
2. Make sure you installed: `npm install -g ionic cordova`
3. If now ionic isn't available, first make `sudo su` and then `npm install -g ionic cordova`
4. Please post your npm version.
5. Stack overflow: http://stackoverflow.com/questions/25127738/cannot-run-ionic-receives-no-command-ionic-found

Greetings
Graphefruit

**Comment by jagannathTL** [comment]
@graphefruit I tried that too before posting but its not working ,btw i have updated to support ticket.

**Comment by graphefruit** [comment]
Check if ionic is installed below your node modules, `/usr/local/lib/node_modules/ionic/bin/ionic` also make sure that NPM is linking to the right path: http://stackoverflow.com/questions/14803978/npm-global-path-prefix

**Comment by jagannathTL** [comment]
Linking NPM fixed the issue thanks @graphefruit.
`npm config set prefix /usr/local `

**Comment by Bliepjes** [comment]
Hi everyone,

I finally succeeded in creating a project and using the Ionic CLI, after doing some manual updating as I had the same issues as described above. I used npm-check-updates 'npm install -g npm-check-updates' for this since the errors are about deprecated packages, and need to be updated. 

1. Open terminal or equivelant on Windows
2. enter 'sudo su' and enter your password (sudo should not be used!)
3. Install ionic 'npm install -g ionic cordova'
4. You will get the errors but you need the files first before you can update the package.json file in ionic
5. cd into 'cd /usr/local/lib/node_modules/ionic'
6. run 'ncu -u' to update the package.json file
7. run 'npm update' to update all the node modules 
8. cd into your project folder and run 'ionic start PROJECT_NAME --v2'

This worked for me and I hope this helps
