### ISSUE TITLE
npm WARN deprecated minimatch

### ISSUE THREAD

**Issue by ops5** [driftyco/ionic#9919]
I'm try to install ionic cordova and i get some errors:

![1](https://cloud.githubusercontent.com/assets/25004133/21762007/0e075252-d65f-11e6-8b74-7a136dff642c.png)
![2](https://cloud.githubusercontent.com/assets/25004133/21762008/0e07c1ec-d65f-11e6-9459-3dd73bad3792.png)

what i'm doing wrong?

**Comment by jsayol** [comment]
Hello @ops5. What you're seeing are just warnings, not errors, and you can safely ignore them in this case. You can check that those were installed correctly by running `ionic -v` and `cordova -v`.

There's not much that can be done absout those deprecation warnings since all come from dependencies of Ionic's dependencies, which ionic itself has no control over.

As a side note, if you want to check the latest version of an npm package, like `minimatch`, you should do it like this:

```
npm view minimatch version
```

Running `npm -v` will only tell you your version of npm itself and it doesn't take any arguments.
