### ISSUE TITLE
Repeating ion-button in the page renders extremely slow

### ISSUE THREAD

**Issue by ozexpert** [driftyco/ionic#9995]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have made a page with *ngFor on `<button ion-button>`. I may have around 1000+ buttons in the page. When nav.push(<to that page>), it opens the page very slowly. Seems rendering the ion-button takes super long. Instead, i've just used `<span>` and result is pretty fast. 

**Expected behavior:**

Renders fast with <button ion-button>

**Steps to reproduce:**

**Related code:**

```
No code example. Just do `*ngFor` with ion-button more than 1000+ and open page.
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hey @ozexpert , thanks for opening an issue with us! So the reason this is slow is not because of anything we are doing, but is just because you are rendering 1000 elements to the dom. While it may be faster with a span, which does make sense as a span is a very simple element that does not have any styling or anything of the sort to paint, you would still not want to render 1000 of them to the dom. Every element you render has to be parsed, put into the dom tree, composited into a layer and then painted. While on a desktop device this may not seem so slow, on a mobile device (even a high end Google Pixel or Iphone 7) this will be very slow as computational resources are in limited quantities on mobile devices. I would recommend considering another UX where you do not need to render 1000 elements to the dom. You will notice a much faster experience, especially on mobile devices. Hope this helps! Also btw, if you are interested in the details of how rendering elements to the screen in browsers works i would recommend checking out [this](https://www.html5rocks.com/en/tutorials/internals/howbrowserswork/) article. Thanks for using Ionic!
